### ISSUE TITLE
Inventory Label (Show Supplier)

### ISSUE THREAD

**Issue by istationonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1000]
No option to at the supplier to an inventory label.

Please make available

**Comment by Uzair-RepairDesk** [comment]
Hey @istationonline  
I hope you are doing well. We have made this improvement LIVE. Now you can add supplier name in the inventory label. You can add **supplier macro** in the inventory label template from **the settings** => **Module Configuration** =>**Template editor**.
