### ISSUE TITLE
Spelling Mistake "Deice" 

### ISSUE THREAD

**Issue by istationonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1001]
![Untitled copy](https://user-images.githubusercontent.com/59316784/71886395-0af35100-3134-11ea-882c-05c0829734c9.png)

**Comment by MuhammadAdnan32** [comment]
Hi @istationonline,
Thank you for bringing this to our attention! I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hi @istationonline 
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have a question.
Thanks!
Regards,
M Adnan

**Comment by usmanalikhan93** [comment]
Hi @istationonline 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
