### ISSUE TITLE
Improvements In Bill Payments

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1002]
Not a bad bill payment module.  It’s missing one item.

Some States like Iowa and Illinois charge (2) types of Tax on prepaid products:

1. Sales Tax
2. E911 Tax (which you already have built in)

3. Some prepaid carriers pay all taxes for the customer (Boost).  Boost Mobile does not have us collect or charge any tax to customers.  So $50, means $50.   There is no E911 Tax or Sales Tax for a Boost Mobile payment.

**There needs to be an option to select:**

1. No Tax
2. Sales Tax
3. E911 Tax

**Comment by Uzair-RepairDesk** [comment]
Currently we have the following workaround for this case in our system:

1. If the user does not want to charge any tax on bill payments transaction, he can simply mark NO for 911 tax from module settings page and no tax will be charged against these transactions. 
2. If he wants to charge both sales tax and 911 tax, he can rename the 911 tax to Sales Tax and its value should be equal to 911 tax+ sales tax value. 

We will also add this improvement in our roadmap to include these settings on one tab in module configurations.

**Comment by Uzair-RepairDesk** [comment]
Its live
