### ISSUE TITLE
 invoice terms and conditions disappear when making multiple payments

### ISSUE THREAD

**Issue by gijoe911** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1003]
I have an issue that when the customer makes multiple payments on an invoice the terms and conditions disappears. I have asked @Danny Hassan to address this before but haven’t heard anything. Can u guys please take a look? seems to work fine when single payment is made against an invoice. thanks

![WhatsApp Image 2020-01-14 at 4 37 27 PM](https://user-images.githubusercontent.com/25240657/72328882-bb41f600-36ee-11ea-993d-484dc351ce2e.jpeg)

**Comment by usmanalikhan93** [comment]
Hi @gijoe911 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by MuhammadAdnan32** [comment]
Hi 
I have checked your concern but unfortunately, I am unable to reproduce your issue and its working fine for me with multiple payments of invoice. It would be great if you can share a video of this issue or detailed steps to reproduce the issue.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.Thanks
Regards,
M Adnan

**Comment by gijoe911** [comment]
Hi there, another customer made more than 1 payment yesterday and the same thing happened. did u use the ipad to make multiple payments and double check the invoice? please, this is a serious issue that should be checked and addressed thoroughly.

![Untitled](https://user-images.githubusercontent.com/25240657/72774539-f2139100-3c45-11ea-9f2a-efd3c3c51781.png)

**Comment by MuhammadAdnan32** [comment]
Hi @gijoe911 ,
I hope you are doing well. I have double-checked your concern on my account its working fine for me. Could you please share your Repairdesk account credentials on adnan@repairdesk.co, So I will check it on your account. Thanks,
Regards,
M Adnan

**Comment by gijoe911** [comment]
Yes no problem. Thanks

fly@digitalexpertmo.com
password1.

**Comment by usmanalikhan93** [comment]
Hi @gijoe911 

I hope you are doing well. I have deleted your last message which has credentials. Because it's a public so anyone can see it. I have noted down your credentials and @MuhammadAdnan32 will look into this issue and revert back to you if he needs more info. 

Thanks 
Usman Ali

**Comment by gijoe911** [comment]
Thank you very much.

**Comment by MuhammadAdnan32** [comment]
Hi @gijoe911 ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Regards,
M Adnan

**Comment by gijoe911** [comment]
Great thanks

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-816

**Comment by MuhammadAdnan32** [comment]
Hi @gijoe911 ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
