### ISSUE TITLE
Expense difficult to select correct payment option

### ISSUE THREAD

**Issue by Thayis** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1005]
Found a small glitch that when you release the mouse click on payment option under expenses. It will scroll up to the top again. Easy to get around but i have accidentaly selected wrong payment method a few times because of it.

**Comment by MuhammadAdnan32** [comment]
Hi @Thayis ,
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hi @Thayis ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-808

**Comment by usmanalikhan93** [comment]
Hi @Thayis 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
