### ISSUE TITLE
Facing display - terms text

### ISSUE THREAD

**Issue by gsmgps-star** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1007]
hi.

it is possible to set the term text to a smaller font?
picture: https://i.imgur.com/u06hiI9.jpg

regards

**Comment by Uzair-RepairDesk** [comment]
Hi @gsmgps-star 
If you set terms & conditions, it displays complete text on the customer-facing display widget. 
Can you please specify why you exactly asking for a smaller font?

**Comment by gsmgps-star** [comment]
because my terms text occupy the full screen :-)

solved it by rearranging the text in terms

tnx

**Comment by Uzair-RepairDesk** [comment]
Thanks for the update @gsmgps-star
