### ISSUE TITLE
Ability to print inventory item barcode using RepairDesk iPAD POS

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1009]
To have the ability in **[RepairDesk iPAD POS](https://www.repairdesk.co/iPAD-POS-Register)** to print inventory label, when you tap an inventory item from shopping cart and on the pop up it shall allow you to print inventory label/barcodes

![iPAD POS App](https://user-images.githubusercontent.com/21986026/72868225-2e58f700-3d03-11ea-9f85-6384b0b10191.jpg)

**Comment by Uzair-RepairDesk** [comment]
This improvement has been made and is live in release version 5.0.
