### ISSUE TITLE
Ability to upload attachments on repair tickets / leads

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1010]
I need the ability to attach files other than images to tickets. PDF, etc. Is this going to be available? I can see you can attach any file to a customer record, so why not to a ticket?

**Comment by Uzair-RepairDesk** [comment]
#1044

**Comment by Uzair-RepairDesk** [comment]
Hey @Repair-Desk 
I hope you are doing well,  it is to inform you that we have added an option in the ticket section from where you can upload attachments.
you can upload attachments for the specific ticket items and with the whole ticket as well.
Here Is the link For KB article:
https://help.repairdesk.co/knowledgebase/articles/1944004-how-to-upload-attachments-while-creating-tickets
