### ISSUE TITLE
iOS App - Add Dispatch Calendar

### ISSUE THREAD

**Issue by BG-RLTech** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1012]
Can you add the Dispatch Calendar to the iOS application. This allows better management for management to review tech's jobs for the day.

**Comment by Uzair-RepairDesk** [comment]
Hey @BG-RLTech 

Thank you for sharing your idea. The dispatch module is already planned in Q2 of 2020 in a new app.
Currently, we are working to revamp our mobile app and the initial version is expected before the end of Q1 2020. 
The new app will be a hybrid app that will work on both iOS and Android platforms. Please check the repair ticket-workflow that is currently in development. You are welcome to share your feedback:-

**[Create Ticket Workflow](https://projects.invisionapp.com/share/PHVG2NFR8X3#/screens/400952258_Create_New_Ticket)**

**[View Ticket Workflow](https://repairdesk.invisionapp.com/console/RepairDesk-Mobile-App-ck53oarqy0avi014r0oouficj/ck53odbk50anr0165ksq79ixu/play)**

**[Edit Ticket Workflow](https://editticketmodule.invisionapp.com/public/share/MNYNT5B42#/screens/475742163)**

Please feel free to let me know if you have any questions in our new app workflow. 

Regards,
Uzair
