### ISSUE TITLE
Customer Facing Display - text translate

### ISSUE THREAD

**Issue by gsmgps-star** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1014]
hi.

i translated all the text but it still shows me in english...
any help please
PICTURE
1. https://i.imgur.com/v0OIp7F.jpg
2. https://i.imgur.com/qCyd5VI.jpg
3. https://i.imgur.com/R4rc1se.jpg

regards

**Comment by MuhammadAdnan32** [comment]
Hi @gsmgps-star 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-824

**Comment by MuhammadAdnan32** [comment]
Hi @gsmgps-star ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Regards,
M Adnan

**Comment by gsmgps-star** [comment]
hi.

still need to translate: https://i.imgur.com/qCyd5VI.jpg

regards

**Comment by MuhammadAdnan32** [comment]
Hi @gsmgps-star ,
I hope you are doing well.Yes, you need to translate first then it will be working fine for you.If you face any issue kindly PM me (on adnan@repairdesk.co) your store credential and your language which you have set on store, so I will do this for you.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Regards,
M Adnan

**Comment by gsmgps-star** [comment]
ok tnx..works like a charm now :-)
