### ISSUE TITLE
Tickets Counter Display

### ISSUE THREAD

**Issue by MPrepairs** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1018]
Is there a way to add on this feature from showing tickets for the day to like tickets from last 3 days or 7 days? Or display tickets from custom days?

**Comment by MuhammadAdnan32** [comment]
Hi @MPrepairs ,
I hope you are doing well. Are you referring Ticket counter? As on the ticket counter, we have displayed the ticket data for today only.
Thanks,
Regards,
M Adnan

**Comment by MPrepairs** [comment]
Yes, my apologies. Thats what I was referring to.

**Comment by MuhammadAdnan32** [comment]
Hi @MPrepairs ,
Thanks for the feedback. I have forwarded this to the product manager. I will keep you posted here.
@Uzair-RepairDesk FYI
Thanks,
Regards,
M Adnan

**Comment by Uzair-RepairDesk** [comment]
Hi @MPrepairs 
It's already in our plan. We will add an option to display tickets for the last 3 and 7 days and will release it soon. 
You can track progress here #1006 

Regards,
Uzair

**Comment by Uzair-RepairDesk** [comment]
Hi @MPrepairs 

This is to inform you that we have added the option to display **yesterday**, **the last 3** or **last 7-day** repair tickets on the ticket counter display.
Please check on your end and do let us know if you have any questions.
Regards
