### ISSUE TITLE
Search All box

### ISSUE THREAD

**Issue by mrjoeham** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1021]
I am new to repair desk and have been using repairshoppr the last two years. One of the feautre that works for us well is the search all box.  We can search any number, name, ticket number, invoice number anything that could be related to a specific search we can type in a number or a name and it will pull up all matches from all areas of the database, if there are double customer entries with the same name it will pull it up and also allows us to merge the two to keep it clean, it also pulls up anything related to the search, .. invoices, inventory,   This feature is very useful..  Repair desk does not have this option and that makes it  harder to use.  We have to navigate properly to get the information we are looking for or don't find it.

**Comment by Uzair-RepairDesk** [comment]
Hi @mrjoeham 
I welcome you to RepairDesk. **Please find my feedback below:-**

- We can search any number, name, ticket number, invoice number anything that could be related to a specific search we can type in a number or a name and it will pull up all matches from all areas of the database
**We have one specific area in the header where you can select the specific section and search the desired data. You can search for customers, invoices or tickets anytime. Please check screenshot attached**
![uzairshah- Dashboard](https://user-images.githubusercontent.com/22955861/73514595-19bbe380-4414-11ea-8568-a12726411eb5.png)

- if there are double customer entries with the same name it will pull it up and also allows us to merge the two to keep it clean
We are going to make improvements in the customer's module in this quarter and we will also introduce the "Merge" option of customers.
