### ISSUE TITLE
repair desk automatically is creating invoices

### ISSUE THREAD

**Issue by Patrickskeates1977** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1022]
hi repair desk is creating invoices for all jobs automatically please correct

**Comment by Uzair-RepairDesk** [comment]
Hey @Patrickskeates1977 

You can enable the following trigger **Don't auto Create Invoice on Create Ticket** from **Settings** **Module Configuration**  **Tickets**.
![image](https://user-images.githubusercontent.com/22955861/73715398-aed11c00-4735-11ea-9ee4-7a370b1b8801.png)
once you enable this trigger invoice will not be created automatically. 
Hope this helps.

Regards
