### ISSUE TITLE
Improvement In Campaigner Module

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1023]
At present, a follow up email is triggered based on the due date. 

If the due date is empty Repairdesk won't send an automatic follow up email to a customer.

We should update the module so that if a repair ticket is marked as paid or "repaired & collected" it should trigger automated follow up email.

**Comment by ProductTeam-RepairDesk** [comment]
Hey, @Repair-Desk Hope you are doing well, above mentioned improvements is live now if the ticket is marked as paid or repaired and collected an automated email is triggered. 

Regards:
Humza
