### ISSUE TITLE
LEADS Enhancement Request

### ISSUE THREAD

**Issue by Shane-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1025]
When adding a new lead, need to be able to create new task from within manage leads...

**Comment by Shane-RepairDesk** [comment]
@Uzair-RepairDesk  you can close this and a rabbit hole....new task leads to new device and so on.

**Comment by Uzair-RepairDesk** [comment]
@Shane-RepairDesk 
Can you please share more details on it with screenshot?

**Comment by Shane-RepairDesk** [comment]
@Uzair-RepairDesk  I think best if we close,  current LEADS functions pretty well as it is, being built around the scheduling widget.    I'm trying to use for phone calls and other things.........I was telling usman that leads should be renamed to widget leads or something so people are not confused in thinking it's for any lead.
