### ISSUE TITLE
Cell Spot - Quantity in Bill Payments

### ISSUE THREAD

**Issue by dfazal-RD** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1029]
The quantity section in bill payments is not enabled. Which means if a customer gets two top ups of the same value and network, the user has to make two separate transactions, which means checking out twice. 

It would be a great help if we can have the ability to add quantity for bill payments, as it would save a lot of time and we won't have to create multiple transactions for one customer. 

![image](https://user-images.githubusercontent.com/60787402/74042186-e0254280-49e8-11ea-9285-9ae00af12aaa.png)

Improvement Request posted on Behalf of Shafi from Cell Spot.

**Comment by Uzair-RepairDesk** [comment]
@dfazal-RD its live. Please update customer
