### ISSUE TITLE
Loyalty Module - Automatic Loyalty points award on customer referral

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1031]
It be good to be automatic tho. So when we choose referral as the ‘how did you hear about is’ it gives the option to choose the other customer, then that customer gets an email saying “thanks for referring Bob, here is $10 in loyalty points..” 

And that would be part of the setup.. setting how many points will be applied when a customer refers someone.

**Comment by Uzair-RepairDesk** [comment]
This improvement is already in progress and is expected to GO LIVE in next week release IA

**Comment by Uzair-RepairDesk** [comment]
Its LIVE now.
