### ISSUE TITLE
Customer Referal Earns Loyalty Points

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1032]
When we choose referral as the ‘how did you hear about us’ it gives the option to choose the referring customer, then that customer gets an email saying “thanks for referring Bob, here is $10 in loyalty points..” etc.

The amount of loyalty $$ earned would be determined in the loyalty setup, where you would choose how many loyalty $ earned when referring a new cusotmer.

**Comment by Repair-Desk** [comment]
**Hello @afrahm** 

Thanks for sharing your feedback & here's how we plan to add suggested improvements.

**Amount of loyalty $$ earned will be managed from loyalty setup screen**

![image](https://user-images.githubusercontent.com/21986026/74735284-2cd30e00-5272-11ea-8d2f-751fa6b1806b.png)

When you choose referral source ‘how did you hear about us’ it also gives the option to choose the referring customer and you can also save it for the future so you don't have to select it every time.

![loyalty referral](https://user-images.githubusercontent.com/21986026/74735412-77548a80-5272-11ea-84de-6f60ba92bc65.png)

**On the checkout screen, they'll also be able to see this info**

![2](https://user-images.githubusercontent.com/21986026/74735444-889d9700-5272-11ea-9ba0-54ae8f405fae.png)

Please let us know if we're heading in the right direction

**Comment by afrahm** [comment]
That looks good. So when you select referral it gives you a lookup to search for existing customers? And that would have a trigger to add the loyalty points to the referring customer and ability to auto send email?

**Comment by Repair-Desk** [comment]
> That looks good. So when you select referral it gives you a lookup to search for existing customers? And that would have a trigger to add the loyalty points to the referring customer and ability to auto send email?

Correct :)

**Comment by Uzair-RepairDesk** [comment]
Hi @afrahm 
Hope you are having a good time. 

I am glad to inform you that your suggested improvement to reward loyalty points to referrals has been LIVE. Please give it a review at your end and keep us updated with new suggestions and improvements. 

Looking forward to some more valuable feedback from your end. 

Kind regards,

**Comment by afrahm** [comment]
How do I choose who the referring customer is when I set the 'how did you hear about us' as referral? Without this there is no way for the system to know who to award the referral points to??

**Comment by afrahm** [comment]
<img width="553" alt="Screen Shot 2020-03-04 at 9 37 50 pm" src="https://user-images.githubusercontent.com/1414304/75876040-a6691f80-5e60-11ea-894d-789bcaf67609.png">
 Would have thought there would be an option to choose who the referring customer is with a lookup field..

**Comment by Uzair-RepairDesk** [comment]
Hi @afrahm 
I will be happy to assist. 
Definitely you can check who the referring customer is. Please enable the trigger to offer loyalty to referring person from loyalty module settings and then you will get the field to choose referring person when you will select how did you hear about us. 

Please check the screenshots for your reference. 

![Screenshot_2020-03-06 How to use the RepairDesk Loyalty Program – RepairDesk Knowledge Base](https://user-images.githubusercontent.com/22955861/76051198-dbbe5c00-5f8b-11ea-9e3a-25b968a7d809.png)

![referral loyalty](https://user-images.githubusercontent.com/22955861/76051321-38217b80-5f8c-11ea-97f9-da4abdf85ce4.PNG)

**Comment by afrahm** [comment]
OK thanks.

So what happens when the referring customer has not yet signed up to the loyalty program. Will they still receive the points?

Will they be prompted to sign up first then receive the points?

Or will they be automatically signed up and the points applied?

**Comment by Uzair-RepairDesk** [comment]
Yes the referral will receive the points even if he is not signed up to the loyalty program. He will receive the following email about referral points which is listed under emails and notifications. 

![Screenshot_2020-03-06 RepairShop - EmailContent](https://user-images.githubusercontent.com/22955861/76053201-41abe300-5f8e-11ea-860a-701b92b0d9bf.png)

Once he visits the store to redeem his loyalty points, you can enable loyalty against him manually from POS.
