### ISSUE TITLE
Choose recipient or gift card

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1034]
Be able to set who the recipient is on the gift card.

This will then attach the gift card to their customer profile.

May need to separate Gift cards purchased and Gift cards received in the customer profile as well.

**Comment by Uzair-RepairDesk** [comment]
Hi @afrahm , 
Thanks for making this suggestion. We have pinned it to our roadmap and plan to take this up soon in near future. We are trying our best to cater as many suggested improvements as possible. 

Keep sharing your feedback. 

Regards,

**Comment by Uzair-RepairDesk** [comment]
Hi @afrahm 
Hope you are doing great 
I am glad to inform you that your suggested improvement to email gift card directly to receipeint is LIVE now. Please review it on Live and let me know if you have any questions. 

Please refer to this [article](https://help.repairdesk.co/knowledgebase/articles/1937014-how-to-use-gift-cards-in-repairdesk) to learn more about how it works 

Looking forward to your feedback

Kind regards,
