### ISSUE TITLE
Customer Portal Payments

### ISSUE THREAD

**Issue by tinkertechguy** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1038]
Problems:

- There is only one option to take payment  (PayPal) - Please add a field for Customer to Pay using Credit Card.

- Pay Pal payment does not reflect back to customer Invoices on Repair Desk

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you please check the following:-
- Pay Pal payment does not reflect back to customer Invoices on Repair Desk

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk Haider Zaidi is assisting on this. I have asked him about the update on this and he said he will check with the customer today and then create a task for this. 

Thanks.

**Comment by usmanalikhan93** [comment]
Hi @tinkertechguy 

I hope you are doing well. Can you please confirm are you still facing this issue or not ?

**Comment by tinkertechguy** [comment]
This is still not working all the way correctly. I had a customer pay thru the portal today, he had to do two payments (not sure why there isn't an option to pay for entire bill together).   One of the payments did work, but the other one did not

**Comment by tinkertechguy** [comment]
Took Payment today and nothing worked at all, customer paid thru pay pal using the customer portal and it did not clear thru Repair Desk and mark it off PAID>  I had to manually check pay pal and confirm it was paid and then go over to repair desk pull up the invoice and do a OFFLINE credit and Put PAY PAL as reference to mark it as paid.  This is annoying and a complete waste of my time going back and forth.  Please look closer to fixing this issue.

**Comment by usmanalikhan93** [comment]
Hi @tinkertechguy 

Let me check this and update you in 24 hours.

**Comment by usmanalikhan93** [comment]
Hi @tinkertechguy 

Can you confirm me that when customer adds payment from portal, does it reflect on Paypal ? 
If yes, then it should work fine. 
But if it does not, then you have to check paypal settings that when you are confirming the payment. 
In our scenario Invoice only gets paid when paypal confirms the payment right away.

Do let me know if you have any question. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @tinkertechguy 

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Usman Ali
