### ISSUE TITLE
Sales Reports Issue

### ISSUE THREAD

**Issue by tinkertechguy** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1039]
Sales Reports only Credits the employee that checks out the customers, we verified and tested this.  It doesn't matter who makes the invoices or who is assigned to the repair work.  The sales credits only the person logged in when checking out a customer and taking payment.

- It does not credit the Tech who does the Repair ( our organization credits the repair assigned to the tech that completes the repair and should be considered as a Sale Made in the report)
 
-There is no easy way to Adjust who gets credit for the Sale/Repair at the invoice stage if changes are necessary at check out.  Repair Shopper has this feature and it's easy to do from drop-down menu.  Within the invoice line. 

![Capture](https://user-images.githubusercontent.com/43980680/74625960-ef9c3e00-5102-11ea-867d-20f58aced647.PNG)

- We want Sales/Repairs to be credited to the appropriate Tech/Sales personnel by the invoice item line and assigned To .

**Comment by Uzair-RepairDesk** [comment]
Hey @tinkertechguy  
I hope you are doing well.
Can you please provide more details so that we can get a clear idea of what you are trying to highlight. Are you referring to employee commission?

Regards:

**Comment by tinkertechguy** [comment]
Currently the sales report credits ther personnel that is sighned in and takes the payment.

we want the credit to go to the person who does the work for the ticket ASSIGNED TECH should get the credit in the reporting showing how much they made for the repair or the Sale.

I went over this with help on the phone, my account rep knows about this, but I have not heard of any updates

**Comment by Adski01** [comment]
Did this item get taken any further?
