### ISSUE TITLE
Wrong Estimated Profit

### ISSUE THREAD

**Issue by antoinegali** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1042]
Hello,

In this example, we are repairing an Apple Watch, price is 120$, cost price of part is 46.84$. Profit is 73.16$.

We also have 2 SKU items, cost 10$ sale price 10$, profit should be 0$.

However, it seems like the system calculates only the cost of 1 item instead of two. It adds a profit of 10$ on the repair which makes it at 83.16$ (wrong).

Thanks
![Screen Shot 2020-02-17 at 3 11 05 PM](https://user-images.githubusercontent.com/37091836/74683697-c1b50900-5197-11ea-8013-3e6575db6703.png)
![Screen Shot 2020-02-17 at 3 02 58 PM](https://user-images.githubusercontent.com/37091836/74683698-c1b50900-5197-11ea-8e44-968402e3a012.png)

**Comment by antoinegali** [comment]
If I separate SKU items into 2 lines, it now calculates the profit accordingly.
![Screen Shot 2020-02-17 at 3 13 03 PM](https://user-images.githubusercontent.com/37091836/74683789-06d93b00-5198-11ea-98c0-e043f73fae61.png)

**Comment by MuhammadAdnan32** [comment]
Hi @antoinegali ,
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Regards,

**Comment by MuhammadAdnan32** [comment]
Hi @antoinegali ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For Internal use:
https://repairdesk.atlassian.net/browse/RB-891

**Comment by antoinegali** [comment]
Thanks.

**Comment by usmanalikhan93** [comment]
Hi @antoinegali 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
