### ISSUE TITLE
Gratiuity and Tips on reciepts and reports

### ISSUE THREAD

**Issue by tinkertechguy** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1043]
Gratuity and tips is not showing up on invoices and receipts, I also would like to run a report for a specific date or block of time for a total of tips.

**Comment by Uzair-RepairDesk** [comment]
Hi @tinkertechguy 

Can you please let me know if you are using an integrated payment integration with RepairDesk where you process tip/gratuity? 

Waiting for your response. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi @tinkertechguy  
I hope you are doing well. We have made this improvement live, Now you can view employee Tip/Gratuity via a report. The report will display tip received against each invoice. you can view this report under employee reports.
![image](https://user-images.githubusercontent.com/22955861/75971973-5f2c6e80-5ef4-11ea-957f-a0b75ca01ce2.png)

we have also added Tip Macro in **template editor** for **Invoice templates** **Service Receipt Template** and  **Thermal Receipt Template**. you can add a specific macro in the desired template and based on that tip will be visible on receipts.
You can access template editor via **Settings** => **Module configuration** => **Template Editor**
for more informantion on tempalte editor kindly follwo the link.
https://help.repairdesk.co/knowledgebase/articles/886713-how-can-i-customize-my-invoice-ticket-label-rece
