### ISSUE TITLE
Mulitple Photo Attachements on Notes, Tickets, and Email

### ISSUE THREAD

**Issue by tinkertechguy** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1044]
i had to upload about 10 photos to a ticket and then also email the customer, it was a lot of work and time having to go back and forth to copy links to add to the email.  There should be an option to do this in bulk or do it like how repairshopr does it.  the photo is uploaded to the ticket library and can is always readily available on the left side and check the box if want to add photos as an attachment to Notes, email or SMS

**Comment by Uzair-RepairDesk** [comment]
Hi @tinkertechguy 
I really appreciate that you took the time to share your ideas.

I can certainly see how the suggested improvements would be useful. Option to upload attachments on the ticket is already available in our current quarter roadmap however we will see that how we can add an option to use uploaded images in the email.  

Let me know if I can help you with anything else in the meantime! 😄 

Regards,
Uzair

**Comment by Uzair-RepairDesk** [comment]
Hey @tinkertechguy 
We're going to add the option to upload attachments against a repair ticket. You will also be able to select attachment while sending an email. Here's a clickable prototype.
https://rddeveloper.invisionapp.com/public/share/CD122TXKFH#/screens/476797754

Your feedback will be appreciated. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey @tinkertechguy 

We have made this feature LIVE. To keep a record of every repair, you can now add/attach documents with repair tickets.
You can also send attachment while sending an email to the customer from the repair ticket.

Please check following knowledgebase article for your understanding:-

https://help.repairdesk.co/knowledgebase/articles/1944004-how-to-upload-attachments-on-repair-ticket
