### ISSUE TITLE
Alert on defaulter customer

### ISSUE THREAD

**Issue by JaviPlana** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1045]
Is it possible to add an alert on a customer profile to alert next time you enter a new ticket that they have an oustanding debt?

**Comment by Uzair-RepairDesk** [comment]
Hi @JaviPlana 
You can add notes against a customer profile and "**Save and Flag**" it. Once you select the customer again for the transaction, an automatic popup alert with the same note displays automatically. 
Check the screenshots attached. 

![uzairshah - POS](https://user-images.githubusercontent.com/22955861/74902275-5a7d9b80-53c7-11ea-946d-2cf14f543046.png)

![uzairshah - POS1](https://user-images.githubusercontent.com/22955861/74902284-5fdae600-53c7-11ea-8a6d-3f9df7c88b01.png)

I hope it helps

**Comment by JaviPlana** [comment]
Thank you!!

Javi Plana
