### ISSUE TITLE
Option to void store credits and loyalty points

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1047]
If loyalty points or store credits are added by mistake there should be a way to void them from customer profile or respective reports.

![Option to void store credit   gift card](https://user-images.githubusercontent.com/21986026/74908852-c3b9da80-53d8-11ea-96c2-6333a7b446e7.png).

At present, you can adjust store credits by making an invoice but that may mess up EOD or accounting

**Comment by Uzair-RepairDesk** [comment]
The option to revert loyalty points manually is LIVE now. Reverting store credits is still pending

**Comment by Uzair-RepairDesk** [comment]
We have also added an option to "Void Store Credits".
