### ISSUE TITLE
Multiple Credit Card Terminal One Till

### ISSUE THREAD

**Issue by tinkertechguy** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1049]
We have had this issue from day one and have been just trying to work around it.

We have 4 terminals with Genius TSYS with differant IP address.  We set up the intergration for multiple Registers.  However we operate with only one Cash till and use 4 credit card terminals.  The systems only works on one Terminal.  Only the Terminal that is 1st open will work even if we check someone out on a different Station.  If the Terminal is on the other side of my shop and I check someone out at the opposite side, we have to walk over to the terminal, this is not how we want to operate.  We need this fixed.  Each station should be able to take credit card payments from it's own Terminal

**Comment by jawad-Repairdesk** [comment]
@tinkertechguy Sorry for the inconvenience. It seems you are having the issue with its setup. 

I have asked my support guy to contact you, he will ask your credentials and we will look at your settings and try to resolve your issue.

Secondly, if our support guy is not able to contact you. Please come over to live chat so we can help you ASAP.

Regards,

**Comment by fahadimran303** [comment]
I have been in contact with him on WhatsApp. Looking after the issue.

**Comment by usmanalikhan93** [comment]
Hi @tinkertechguy 

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Usman Ali
