### ISSUE TITLE
Cybertek - Loyalty point credit exclusions

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1050]
Can we block customers earning loyalty money when purchasing gift cards?
And if a customer gets a refund on something they purchased with Loyalty dollars does this convert to store credit? Or do they get the loyalty money back?

And if someone purchases with loyalty do they earn loyalty again? This could make a continuous loop that may or may not break the spacetime continuum

**Comment by Uzair-RepairDesk** [comment]
Hi, 
I will be happy to help you with your queries regarding loyalty module. 
1. Currently we don't have the functionality to block loyalty on selling gift cards. So your customers will earn loyalty on purchasing gift cards. 

2. Invoice paid through loyalty cannot be refunded from loyalty. You can refund that invoice through any other payment method i.e. through store credits or cash or any other method.

3. No loyalty is earned when an invoice is fully paid through loyalty. However if the customer has made the partial payment through loyalty, then he will earn the loyalty. 

Hope that helps. If you still have any questions, please don't hesitate to reach out to us. 

Thank you!

**Comment by Uzair-RepairDesk** [comment]
Hi @Cybertekww 
Hope you are having a great time. 

I will like to update you on the above improvement to have an option of not to issue loyalty on selling gift cards. We have added a new trigger in loyalty settings which will allow you not to offer loyalty on selling gift cards as shown in the screenshot below 

![Screenshot_2020 03 31 RepairShop   Loyalty 2 ](https://user-images.githubusercontent.com/22955861/78048579-5adc5f80-7393-11ea-8b39-9909b14e7416.png)

This trigger will be visible only if your gift cards module is enabled and by default will be set to OFF. 
This improvement is LIVE Now. Please review at your end and let us know if it works for you

Looking forward

Kind regards
