### ISSUE TITLE
Customer Duplicates

### ISSUE THREAD

**Issue by tinkertechguy** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1052]
There is no ability to merge duplicated Customer inputs.  We would like this ability to merge the customer ticket history and anything related to the customer when there are two customer profile that are the same person but was entered in twice by accident.

**Comment by Uzair-RepairDesk** [comment]
#840

**Comment by Uzair-RepairDesk** [comment]
Hi @tinkertechguy 

Thank you for sharing your idea. We have already plan to improve customer's module in Q3 of 2020 where we will also introduce the "Merge Customers" option so you will be able to merge different customers if you have duplicate records.

**Comment by Uzair-RepairDesk** [comment]
Hi @tinkertechguy 
Hope you are staying safe

I am here with an update on this thread. We have added the functionality to merge customer profiles as you have requested for our customers module. Please review at your end and share any feedback if you have. 

To learn more on how this functionality works, please have a walk through to our [KB Article.](https://help.repairdesk.co/knowledgebase/articles/1945498-merge-customers-in-repairdesk) 

Looking forward to your response

Regards,
