### ISSUE TITLE
Terms and conditions for repairs in the iPad went blank

### ISSUE THREAD

**Issue by gijoe911** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1055]
Hello, 

Terms and conditions in the iPad went blank just now. Seems like it’s happened just now. I checked the invoice settings and all the terms are there so this looks a bit abnormal. Can you guys please look into this?

![image](https://user-images.githubusercontent.com/25240657/75308833-60252680-588a-11ea-8324-928eec9d6a60.png)

![image](https://user-images.githubusercontent.com/25240657/75308848-67e4cb00-588a-11ea-9bc5-9914bb5ff5b4.png)

**Comment by Uzair-RepairDesk** [comment]
Hi @gijoe911 
Thanks for bringing this to our attention. We apologize for inconvenience. It seems like a bug that has just popped up. Our engineers are looking into it. I will update you as soon as its fixed and sent in a release. 

Meanwhile please let us know if we can assist you with something else. 

Thank you.

**Comment by gijoe911** [comment]
any updates on this?

**Comment by usmanalikhan93** [comment]
Hi @gijoe911 

We have pushed our release to App store for approval. It's been pending on Apple's end. Hopefully it will be live today or tomorrow. I will update you once it is available on App store. 

Thanks
Usman Ali
