### ISSUE TITLE
Incorrect due amount in invoice

### ISSUE THREAD

**Issue by gijoe911** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1056]
Hello, i dont understand why the due amount is -301.00 when the invoice has been paid. can u guys please look into this?

![Untitled](https://user-images.githubusercontent.com/25240657/75308949-a67a8580-588a-11ea-893f-ab469c0891f0.png)

**Comment by usmanalikhan93** [comment]
Hi @gijoe911 

I believe Haider has updated you on Facebook chat group. Do let me know if you have still any question. 

Thanks 
Usman Ali

**Comment by gijoe911** [comment]
yes issue is resolved. thanks
