### ISSUE TITLE
Dark Mode iPadOS issue

### ISSUE THREAD

**Issue by istationonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1058]
When in dark mode in RD iPad App.

Text can’t be seen, see attached in various area’s

![C5B17384-7DE4-476E-A85F-B4ABEC1358FD](https://user-images.githubusercontent.com/59316784/75614564-fc248b80-5b31-11ea-96ff-f109de496331.png)
![44E752E4-64CB-44D8-9C31-41E05ABE411C](https://user-images.githubusercontent.com/59316784/75614565-fcbd2200-5b31-11ea-83b0-fbbefce173a2.png)

**Comment by hitman1986** [comment]
Im facing same issue , although i deleted the app and reinstalled it

**Comment by MuhammadAdnan32** [comment]
Hi @istationonline @hitman1986 ,
I hope you are doing well. Our RD iPad App did not support dark mode. So kindly disable the dark mode then it will work fine for you. 
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Regards,
M Adnan

**Comment by Afnan-Mahmood** [comment]
Dear @istationonline @hitman1986 

Hope you are doing well and staying safe.

We have pushed our release 5.2 to app store and release has been lived. You can download the latest version from app store. Now you can use app with dark mode as well. Just enable dark mode from iPad setting and app will remains in light mode and things will be readable and will work fine.

Please try it at your side and give us feedback. Hope it works well for you.

If there is any thing else we can do for you please don't hesitate to reach out.

Best,
Afnan Mahmood
RepairDesk Team
