### ISSUE TITLE
Cybertek - Not importing cost prices

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1059]
When I export a spreadsheet and add a heap of items in with SKU and Barcode details as well as retail and cost price the cost prices arent importing. I can see them on the pages leading up to the final import selection but when it completes they dont include the cost price. And each time I am uploading the same spreadsheet it says that 9 items will be added and 217 will be updated but I am importing the same spreadsheet so dont know how that is possible?

**Comment by MuhammadAdnan32** [comment]
Hi @Cybertekww ,
I hope you are doing well. When you are importing the inventory file you have to add cost price in the column "New Inventory Item Cost" and also you have to add quantity in the column "New Stock Adjustment" then cost price of the inventory items will update in the system.
You can see the details in the attached image as well.
![Cost price](https://user-images.githubusercontent.com/50608942/75648382-c8507f80-5c71-11ea-8a4d-8314f4337234.png)
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Regards,
M Adnan

**Comment by Cybertekww** [comment]
Thanks mate.

Not my first rodeo. I've done all that and have imported spreadsheets with all the cost prices in the column but nothing is being put in the system after it imports.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MuhammadAdnan32** [comment]
Hi @Cybertekww ,
Can you please share the file which you are importing and also shared your Repairdesk account credentials at adnan@repairdesk.co ,So I will check and update you accordingly.
Thanks
