### ISSUE TITLE
Appointent Calendar widget

### ISSUE THREAD

**Issue by marianabut** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1063]
Hi, I try to start the pick-up & delivery service for my clients. 
I give to 10 people, and nobody can finish the appointment!
Guys, did you test this module? The user experience is not good at all, is confusing, and not predictable I found a couple of bugs what report about four months ago:

APPOINTMENT CALENDAR  - on desktop
- On the calendar, randomly it’s showing just a part o it, not all the time
- Notification: there are working on RD ( pop-up) but not receive the email (3 persons are selected to receive the new lead notification) 
APPOINTMENT CALENDAR  - on mobile
- Status Boxes from the beginning, are very confusing and have improper functionality. Video link here https://www.youtube.com/watch?v=AeFdjeSXKRY&feature=youtu.be
- after selecting the model the page is scrolling to the bottom, it’s very confusing for the user. Video link here 
https://www.youtube.com/watch?v=M9w0RGLE-w0&feature=youtu.be
- after selecting the problem it’s happened the same, the page it’s scrolling to the bottom 
- after you check the GDPR it appears very long pop-up and you must scroll back.
It’s very confusing for the user. 
Video link here https://www.youtube.com/watch?v=Vt8eqxSuIJg&feature=youtu.be

- About a couple of months ago ( in November 2019) we talk about it is possible to customize the fields or to remove some of them. For user must be very easy and simple to use. 

- Also in the video is one warning pop-up who is looking more like an error. I think is the txt. content can be better. Video link https://www.youtube.com/watch?v=zFwuPuelDIc&feature=youtu.be

After I wait for four months, after many delays I found the two solutions:
- Facebook appointment 
- Google forms

It is not integrated with RD but is working fine, and easy yo use. 

Big thanks!

**Comment by usmanalikhan93** [comment]
Hi @marianabut 

I hope you are well. We have already escalated the task internally for Mobile Version. Developer is working on it and will provide you with the best solution. I will update you once it's done. 

For the desktop issue, let me check and update you in 12 - 24 hours. 

For Internal Use: 
https://repairdesk.atlassian.net/browse/RB-932

**Comment by marianabut** [comment]
Thank you very much for your feedback.
Have great day!



[image: photo]
*Marian Abutoaiei*
 +40729 300 300


În mar., 10 mar. 2020 la 09:56, Usman Ali Khan <notifications@github.com> a
scris:

**Comment by usmanalikhan93** [comment]
Hi @marianabut 

The email will only goes to admin and customer and not to the employees which you have marked in alerts. It only displays pop up when lead creates against those employees. 
Do let me know if you have any question.

Thanks
Usman Ali

**Comment by marianabut** [comment]
Ok, I understand.
I will check.
Thank you!

**Comment by marianabut** [comment]
I test, it's ok the notifications. Thank you!

**Comment by usmanalikhan93** [comment]
Hi @marianabut 

I hope you are doing well. We have made some changes now and it looks like all your points are now fixed. I have checked at my end. Can you please test this on mobile and send us your feedback ?

Thanks 
Usman Ali

**Comment by marianabut** [comment]
Hi!
Ok, I will give you feedback in 1h

**Comment by marianabut** [comment]
Hi Usman!
The feedback is positive! Everything is working well now!
BIG THANKS to you, and to your team!



[image: photo]
*Marian Abutoaiei*
 +40729 300 300


În mie., 11 mar. 2020 la 13:22, Usman Ali Khan <notifications@github.com> a
scris:

**Comment by usmanalikhan93** [comment]
Hi @marianabut 

Glad to know that :). You are welcome. 

Regards,
Usman Ali
