### ISSUE TITLE
Cybertek - Add SKU to Purchase Order

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1065]
When emailing the purchase order to suppliers they need to be able to use the item codes to make ordering easier, not just the barcode.

**Comment by Uzair-RepairDesk** [comment]
Hey Adam @Cybertekww 

When you email the purchase order to a supplier from RepairDesk, a PDF file of a purchase order is sent to supplier by email. SKU/Item ID of each item also displays in the PDF file so the supplier can track items with the same.

If you also want to keep a specific code for the item to aware of your supplier, you can keep it under the description of each line item while creating a purchase order. 

Please let me know if I am able to answer your question or you can add a comment if you have any confusion on this. Thanks

**Comment by Cybertekww** [comment]
Thanks Uzair, I am putting the SKU in the description
