### ISSUE TITLE
Cybertek - Inventory count changes

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1066]
When doing an inventory count I would like to be able to select supplier as well, not just manufacturer.

Also with the count I would like to see a total number of items scanned so I know I have scanned the correct amount of items.

Can there also be an error when scanning an item not in the system? Sometimes I need to update items not in system but cant see any issue when scanning an item thats not in the system.

When scanning items in the "Counted" collumn is not set to 0 and is making my stock count numbers incorrect. When doing a stock count I would like it to override any stock level in the system.

**Comment by Uzair-RepairDesk** [comment]
Hey @Cybertekww 
Thank you for bringing this to our attention! 
1. When doing an inventory count I would like to be able to select suppliers as well, not just manufacturers. we can add supplier criteria in inventory count.

2. Also with the count, I would like to see a total number of items scanned so I know I have scanned the correct amount of items. This is not possible as we already have an option where you scan an item and its count is updated.

3. Can there also be an error when scanning an item, not in the system? Sometimes I need to update items, not in the system but cant sees any issue when scanning an item that's, not in the system.
we can add the error message for those items which are not created in the system.

4.When scanning items in the "Counted" column is not set to 0 and is making my stock count numbers incorrect. When doing a stock count I would like it to override any stock level in the system. this option is not available for a bulk count but you can increase the quantity for each item by counting them individually.
![12135](https://user-images.githubusercontent.com/22955861/76306238-5c60bd80-62e8-11ea-8626-ee8a3d0b0bbe.png)

Hope this helps ,we will keep you posted once we start work on these issues.

**Comment by usmanalikhan93** [comment]
Internal Task for Point no. 3:
https://repairdesk.atlassian.net/browse/RB-971

**Comment by usmanalikhan93** [comment]
Hi @Cybertekww 

I hope you are doing well. We have added error message as "Item is not available in the system." if you scan item barcode which is not present in system. Please check at your end and do let us know if have any question. 

Thanks 
Usman Ali
