### ISSUE TITLE
Bill Payments - Network fee doesn't display if cost price is set as zero

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1069]
![iTech Connections - West Columbia - POS](https://user-images.githubusercontent.com/21986026/77249752-354da880-6c65-11ea-877e-670614eea029.png)

If the cost is zero it doesn't display network service fee line item in shopping basket

**Comment by MuhammadAdnan32** [comment]
Hey @Repair-Desk 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards,

**Comment by MuhammadAdnan32** [comment]
Hey @Repair-Desk ,
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue so we can release a fix during our next release.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hey! 👋 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1024

**Comment by usmanalikhan93** [comment]
@MuhammadAdnan32 what's the latest on this ?

**Comment by MuhammadAdnan32** [comment]
Hello @Repair-Desk ,
I have checked your concern but unfortunately, I am unable to reproduce your issue. I have also attached a video and its working fine for me with a cost price of Zero(0.00). Kindly see the attached video.
https://drive.google.com/file/d/1lE86C8F_DJDvdYO0kYpvLXeH-bPjrJwF/view
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan
