### ISSUE TITLE
Appointment Widget (GDPR)

### ISSUE THREAD

**Issue by istationonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1071]
Trying to edit the GDPR Compliance title in the language editor.

Made changes but they dont update

<img width="1659" alt="Screenshot 2020-03-22 at 21 31 06" src="https://user-images.githubusercontent.com/59316784/77261216-eb74ba80-6c84-11ea-96e5-574486ffb4e8.png">
<img width="737" alt="Screenshot 2020-03-22 at 21 29 34" src="https://user-images.githubusercontent.com/59316784/77261219-f16a9b80-6c84-11ea-9a0c-551023a30514.png">

**Comment by usmanalikhan93** [comment]
Hi @istationonline 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by phonefixcenter** [comment]
Hi Usman, you guys definitely need to add the signature box for pre-authorization(liability waiver and such) if they making an ppoinment same as self-check-in or anything you working on it that involve pre payment from home in this covid-19 situation, you need to add the pre-signature otherwise for someone like me that before working on any gadgets before taking customer signature on my liability waiver agreement is useless, I still need to have close contact to get his/her signature.
this would complete your task and eliminate any worry of not taking customer;s signature before working on their gadgets. 
Thank you.

**Comment by MuhammadAdnan32** [comment]
Hey @istationonline , 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up . 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1021

**Comment by usmanalikhan93** [comment]
Hi @istationonline 

I hope you are doing well. Can you please confirm are you following these steps, I have mentioned in video below in order to update this ? 
Video link: https://drive.google.com/file/d/1I-wCZoKehpLbdNPyAqkB3DK8EiYTIRVD/view

Do let me know if it works. 

Usman Ali

**Comment by usmanalikhan93** [comment]
> Hi Usman, you guys definitely need to add the signature box for pre-authorization(liability waiver and such) if they making an ppoinment same as self-check-in or anything you working on it that involve pre payment from home in this covid-19 situation, you need to add the pre-signature otherwise for someone like me that before working on any gadgets before taking customer signature on my liability waiver agreement is useless, I still need to have close contact to get his/her signature.
> this would complete your task and eliminate any worry of not taking customer;s signature before working on their gadgets.
> Thank you.

@Uzair-RepairDesk can you please check this and update accordingly ?

**Comment by istationonline** [comment]
Yes that’s how I do it…

Is there a limit on characters…?

This is what we have tried to update it with…

"I authorise iStation to hold my personal data to process repairs, in line with General Data Protection Regulation (GDPR)"

Regards




This e-mail may contain confidential and/or privileged information. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), you must not use, distribute, copy or take any action in reliance on it, since to do so is strictly prohibited and may be unlawful. If you have received this e-mail in error, please return it to the sender immediately and delete it from your system. E-mail messages are not secure and attachments may contain software viruses which may damage your system. Whilst we have taken every reasonable precaution to minimise this risk, we cannot accept any liability for any damage which you sustain as a result of these factors. You are advised to carry out your own virus checks before opening any attachment. Any views or opinions expressed in this e-mail are solely those of the author and do not represent those of iStation unless otherwise stated. 

Registered Office: iStation Ltd, 26 Silver Street, Stockton, Cleveland, TS18 1SX.
Registered in England number 9206740.

**Comment by usmanalikhan93** [comment]
Hi @istationonline 

I hope you are doing well. I have tried with your given text and it successfully updated. Please check screenshots 
![istation2](https://user-images.githubusercontent.com/39614480/77615364-024f3180-6f51-11ea-85c4-f3681aa34fdb.png)
![istation1](https://user-images.githubusercontent.com/39614480/77615367-0418f500-6f51-11ea-93ab-47fb2ecf759c.png)

If you still unable to do this, do share your RD credentials with me on usmanali@repairdesk.co. I will do the needful for you. 

Thanks
Usman Ali

**Comment by istationonline** [comment]
Tried it again this morning and now it's appeared, although off centre.

Elsewhere is the terms and conditions box enabled..?

Regards




This e-mail may contain confidential and/or privileged information. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), you must not use, distribute, copy or take any action in reliance on it, since to do so is strictly prohibited and may be unlawful. If you have received this e-mail in error, please return it to the sender immediately and delete it from your system. E-mail messages are not secure and attachments may contain software viruses which may damage your system. Whilst we have taken every reasonable precaution to minimise this risk, we cannot accept any liability for any damage which you sustain as a result of these factors. You are advised to carry out your own virus checks before opening any attachment. Any views or opinions expressed in this e-mail are solely those of the author and do not represent those of iStation unless otherwise stated. 

Registered Office: iStation Ltd, 26 Silver Street, Stockton, Cleveland, TS18 1SX.
Registered in England number 9206740.

**Comment by usmanalikhan93** [comment]
Hi @istationonline 

Let me guide you. Go to integrations > Appointment Calendar > Advance Configuration > Go to bottom and you will see a box of Terms and Conditions.
Add terms and conditions in it and this box will be enabled on Appointment Calendar. 

Regards,
Usman Ali

**Comment by istationonline** [comment]
Ok thanks that s in just need to work out what’s causing it to be off set

Regards




This e-mail may contain confidential and/or privileged information. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), you must not use, distribute, copy or take any action in reliance on it, since to do so is strictly prohibited and may be unlawful. If you have received this e-mail in error, please return it to the sender immediately and delete it from your system. E-mail messages are not secure and attachments may contain software viruses which may damage your system. Whilst we have taken every reasonable precaution to minimise this risk, we cannot accept any liability for any damage which you sustain as a result of these factors. You are advised to carry out your own virus checks before opening any attachment. Any views or opinions expressed in this e-mail are solely those of the author and do not represent those of iStation unless otherwise stated. 

Registered Office: iStation Ltd, 26 Silver Street, Stockton, Cleveland, TS18 1SX.
Registered in England number 9206740.

**Comment by istationonline** [comment]
Another query, what is the default font used in the calendar page so I can replicate it in my customer message…?



Regards




This e-mail may contain confidential and/or privileged information. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), you must not use, distribute, copy or take any action in reliance on it, since to do so is strictly prohibited and may be unlawful. If you have received this e-mail in error, please return it to the sender immediately and delete it from your system. E-mail messages are not secure and attachments may contain software viruses which may damage your system. Whilst we have taken every reasonable precaution to minimise this risk, we cannot accept any liability for any damage which you sustain as a result of these factors. You are advised to carry out your own virus checks before opening any attachment. Any views or opinions expressed in this e-mail are solely those of the author and do not represent those of iStation unless otherwise stated. 

Registered Office: iStation Ltd, 26 Silver Street, Stockton, Cleveland, TS18 1SX.
Registered in England number 9206740.

**Comment by usmanalikhan93** [comment]
Hi @istationonline 

I apologize for the late reply. It's "Open sans" Font. 

Regards,
Usman Ali

**Comment by istationonline** [comment]
That font isn’t available in the advanced calendar widget config.

Regards




This e-mail may contain confidential and/or privileged information. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), you must not use, distribute, copy or take any action in reliance on it, since to do so is strictly prohibited and may be unlawful. If you have received this e-mail in error, please return it to the sender immediately and delete it from your system. E-mail messages are not secure and attachments may contain software viruses which may damage your system. Whilst we have taken every reasonable precaution to minimise this risk, we cannot accept any liability for any damage which you sustain as a result of these factors. You are advised to carry out your own virus checks before opening any attachment. Any views or opinions expressed in this e-mail are solely those of the author and do not represent those of iStation unless otherwise stated. 

Registered Office: iStation Ltd, 26 Silver Street, Stockton, Cleveland, TS18 1SX.
Registered in England number 9206740.

**Comment by usmanalikhan93** [comment]
Sorry @istationonline, Use "Arial".
