### ISSUE TITLE
Bundles

### ISSUE THREAD

**Issue by istationonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1072]
Bundle Cost & Profit Margin not updating

<img width="492" alt="Screenshot 2020-03-22 at 21 39 02" src="https://user-images.githubusercontent.com/59316784/77261336-bae15080-6c85-11ea-940c-dae63a31a57c.png">

**Comment by Uzair-RepairDesk** [comment]
Hey @istationonline 
I hope you are doing well, the above-reproted issue is resolved on the Beta server. you can check and if you have any further feedback feel free to share.
Regards

**Comment by istationonline** [comment]
Thanks ill take a look

Regards




This e-mail may contain confidential and/or privileged information. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), you must not use, distribute, copy or take any action in reliance on it, since to do so is strictly prohibited and may be unlawful. If you have received this e-mail in error, please return it to the sender immediately and delete it from your system. E-mail messages are not secure and attachments may contain software viruses which may damage your system. Whilst we have taken every reasonable precaution to minimise this risk, we cannot accept any liability for any damage which you sustain as a result of these factors. You are advised to carry out your own virus checks before opening any attachment. Any views or opinions expressed in this e-mail are solely those of the author and do not represent those of iStation unless otherwise stated. 

Registered Office: iStation Ltd, 26 Silver Street, Stockton, Cleveland, TS18 1SX.
Registered in England number 9206740.
