### ISSUE TITLE
Suggestion: "Last Name" placeholder.

### ISSUE THREAD

**Issue by iFoneRepair** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1074]
Hello team, I am fine tuning my text message responder for: Repair status "In Progress" (see SMS template attachment) Since during most of my customer visits, I at most times typing the customer's last name manually and can possibly have a **typo** without noticing and **don't want the customer to struggle with not being able to know how i spelled their last name.**

**Suggestion**: It would be great to have a customer **"Last Name" place holder** so i can embed it in my SMS template to inform the customer that they can track their repair on our website (https://www.ifonerepairservice.com/repair-tracker) using their Ticket ID + LAST NAME.

**Summary**: Have macro for Last name instead of Full First and Last name.

Please let me know if this is something your team is looking to create :)

<img width="610" alt="Screen Shot 2020-03-24 at 2 52 25 AM" src="https://user-images.githubusercontent.com/62595033/77412691-71732d00-6d7b-11ea-93d4-574c7838c7cb.png">
<img width="671" alt="Screen Shot 2020-03-24 at 2 52 48 AM" src="https://user-images.githubusercontent.com/62595033/77412697-733cf080-6d7b-11ea-8724-09e8ab4a016a.png">
<img width="935" alt="Screen Shot 2020-03-24 at 2 59 01 AM" src="https://user-images.githubusercontent.com/62595033/77412707-759f4a80-6d7b-11ea-8cd1-6f579fdb7bb8.png">

**Comment by iFoneRepair** [comment]
This edit is **no longer needed,** as I have found a setting to enable Ticket + phone, instead of Ticket + Last name. Placeholder isnt need for "just incase" employee typos.

:)

Settings > Module > Widgets > **"Customer can check repair status by entering mobile number instead of last name from Repair Tracker widget"**

**Comment by Uzair-RepairDesk** [comment]
great. you are legend
