### ISSUE TITLE
Cybertek - Trade in pricing issue

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1076]
When we create a new trade in and then select the sell price and print the barcode, when we scan it into the system the price is incorrect. It adds on gst when gst is already included in the price and we are having to manually discount each trade in item we are selling.

**Comment by Uzair-RepairDesk** [comment]
Hi @Cybertekww 

Can you please check if you have setup the right tax settings under **Store Settings > Module Configurations > Trade-In > Buyer Invoice Settings > Trade-In Default Tax Class** and make sure that the tax inclusive trigger is enabled if you want to include tax value in the price. 

Please check the screenshot attached. 

![uzairshah - Tradein Config](https://user-images.githubusercontent.com/22955861/77627568-ec4d6b00-6f68-11ea-8746-bee6cf6512aa.png)

**Comment by Cybertekww** [comment]
Thanks mate,

That fixed it

Legends!


Adam Donovan

Store Support, Accounts

Cybertek Nambour

P: 07 5343 7590

W: www.cybertek.com.au<http://www.cybertek.com.au/>

[Capture]

________________________________
