### ISSUE TITLE
Cybertek - eftpos tabs annoying

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1077]
we disabled the eftpos receipt printing from our thermal printer but now every time we sell an item using eftpos two new tabs open up in our chrome browser, a merchant copy and customer copy. This is redundant as it is already on the thermal receipt we print for the customer or email to the customer and is annoying as if left unchecked opens a whole heap of tabs we dont need.

**Comment by usmanalikhan93** [comment]
Hi @Cybertekww 

I hope you are doing well. Due to Covid-19 situation we are working from home, and our all hardware is in office. So for now it is impossible to check this on our end. I will let you know once the office will open. 

Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @Cybertekww 

I hope you are doing well. I have discussed with Danish that you said you are not facing this issue now. I am closing this task for now. But in future, if you face this issue again, you reopen this task. 

Regards, 
Usman Ali
