### ISSUE TITLE
Serialized items & WooCommerce Integration

### ISSUE THREAD

**Issue by antoinegali** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1080]
Hello,

Here is a suggestion.

When a customer purchases a serialized item from WooCommerce, you then have to go and edit this invoice to select the serialized item you are going to ship to them and then save the invoice.

It would be nice to choose the serial without editing the invoice, just as you can change a ticket status without editing the ticket.

Thanks for the good work

**Comment by Uzair-RepairDesk** [comment]
Hey @antoinegali 
I really appreciate that you took the time to share your ideas. Selecting are serial and updating ticket status are different things, we can only select serial by editing the invoice, without editing it's not possible.
Hope this helps,let me know if I can help you with anything else 
Regards
