### ISSUE TITLE
Ability to restrict certain ticket status to be updated by administrator

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1081]
I don't want an employee to be able to change a repair ticket status to 'Invoice Paid' because they are not the ones that check if invoices are paid

So if they were to change it to that, it would say access denied or something

But the other status' they can change

**Comment by Uzair-RepairDesk** [comment]
Is "Invoice Paid" a custom ticket status @Repair-Desk ?
Can you please elaborate on it?

**Comment by Repairdesk-QA** [comment]
Hello @Repair-Desk,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
