### ISSUE TITLE
Terms & Conditions | Jose | ITechConnections

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1083]
Hi Sir,

***Business Name / Store Name***
Jose | iTech Connections

***Customer Stature:***
2 Store Location with Annual Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

***Module:***
Receipt/ Invoice

***Improvement:***
Customer has requested an improvement to have an option to add terms and conditions separately fora Accessories, Bill Payments, Repairs instead of having same terms and conditions for all the services.

***Video:***
https://drive.google.com/file/d/1L_O77aW33SgzJJhhLfta9G__U0J23Rnx/view

***Source:***
Facebook

**Thanks and Regards,**
Talha

**Comment by fahadimran303** [comment]
Internal Jira [Link](https://repairdesk.atlassian.net/browse/REP-2484?atlOrigin=eyJpIjoiNGYyZGY0Yjg2M2Q0NGM0NWI1NWFhMjg5NmE3NGI1MDYiLCJwIjoiaiJ9)

**Comment by Uzair-RepairDesk** [comment]
Linked with #870

**Comment by Uzair-RepairDesk** [comment]
Its live. Please update customer
