### ISSUE TITLE
Bill payment price | Jose | ITechConnections

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1084]
Hi Sir,

***Business Name / Store Name***
Jose | iTech Connections

***Customer Stature:***
2 Store Location with Annual Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

***Module:***
Bill payment

***Improvement:***
Customer has requested an improvement to have an option to edit the price at the time of check out when taking bill payments.

***Video:***
https://drive.google.com/file/d/1pN-HwlIheK2PnjUm2V8q_NiLa8CCbGpd/view

***Source:***
Facebook

Thanks and Regards,
Talha

**Comment by fahadimran303** [comment]
Internal Jira [Link](https://repairdesk.atlassian.net/browse/REP-2485)

**Comment by Uzair-RepairDesk** [comment]
Currently, It's not possible to allow the user to change the price of the bill payment plan. There is always a specific value for each plan and in general, they don't update the price. 
There is also technical restriction so we didn't give option to change the price and in-line discount for the bill plan. 
However, if a customer still wants to reduce the price please suggest applying "Overall Discount". 

Hope it helps. Thanks.

**Comment by Uzair-RepairDesk** [comment]
@fahadimran303 
Did we update to the customer on this?
