### ISSUE TITLE
Appointment Calendar - 'Finalise  button' on the end is not working!

### ISSUE THREAD

**Issue by marianabut** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1091]
Hi guys!
I start using the appointment calendar 3 - 4 weeks ago.
I had some costumers who give us feedback about Appointment Calendar the interface. They fill all the fields, but in the end, the finalize button is not working! And they quit...

Yoiu have the link here
 https://www.gsmzone.ro/programari/

Can you check, please! 

https://www.youtube.com/watch?v=BGPR2RV9Q5g&feature=youtu.be
Thank you!

**Comment by MuhammadAdnan32** [comment]
Hey @marianabut , 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Reagrds,
M Adnan

**Comment by usmanalikhan93** [comment]
Hi @marianabut 

I hope you are doing well. Can you please share your Appointment booking link ? And can we make a test lead for test ? 

Regards, 
Usman Ali

**Comment by marianabut** [comment]
Hi Usman, of course!

https://www.gsmzone.ro/programari/

Thank you!


[image: photo]
*Marian Abutoaiei*
 +40729 300 300


În joi, 9 apr. 2020 la 09:27, Usman Ali Khan <notifications@github.com> a
scris:

**Comment by usmanalikhan93** [comment]
Hi @marianabut 

I hope you are doing well.  I have created one lead from Mobile device and it works perfectly. Lead PD062. Please check and do let me know if you have any question. 

Thanks 
Usman Ali

**Comment by marianabut** [comment]
Thank you!
Even today we receive feedback from our clients. They have the same problem, in the end ... it is not working. The last feedback is coming from a client who uses Samsung S10 plus.    I think the problem is coming from the ''security code'' field.  
Can you guys disable this field?  We no need to be mandatory. And another suggestion, when something is not filled correctly, please make red the area so see the costumer exactly what is about.
Thank you!

**Comment by usmanalikhan93** [comment]
Hi @marianabut 

Thank you for your suggestion. Let me discuss this with the team and revert back to you. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @marianabut 

I hope you are doing well. We have done some changes in code in order to fix the issue related to submit and I hope now your customer's will not face this issue again. If you have any questions or find any confusion, do let us know, we will help you :)

Regards,
Usman Ali

**Comment by marianabut** [comment]
Thank you!
