### ISSUE TITLE
Need low stock parts hide trigger | Owner | SPRSC

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1092]
Hi Sir,

**Business Name / Store Name:**
SPRSC

**Improvement:**

Customer has requested to have a trigger option to hide those parts on POS which are not in stock.

**Video:**

**Chat Source:**
https://app.intercom.com/a/apps/mq09yl4f/inbox/inbox/3841891/conversations/26496492250

_**Thanks and Regards,
Talha**_

**Comment by fahadimran303** [comment]
Internal Jira [link](https://repairdesk.atlassian.net/browse/REP-2511?atlOrigin=eyJpIjoiN2YyZGZlODY0MjFkNDY1OTlkNWYxYTgzYjI3ZDE3NWIiLCJwIjoiaiJ9)

**Comment by Uzair-RepairDesk** [comment]
If it's about out of stock products then we have already a trigger to "Hide out of stock items from POS". Please confirm? @fahadimran303 

![uzairshah - Pos Config](https://user-images.githubusercontent.com/22955861/78985378-08910080-7b42-11ea-9811-263a32fafbaa.png)

**Comment by fahadimran303** [comment]
@Uzair-RepairDesk,
I and Hamza have updated the Internal Jira Link and attached a video as well.

**Comment by fahadimran303** [comment]
Internal Jira Link:
https://repairdesk.atlassian.net/browse/REP-2511

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303 
I hope you are doing well, we have made this improvement live, now you can hide out of stock repair parts from POS just by enabling this trigger added in **Module configuration**  **POS section**.
![FIXAPHONE_Pos_Config](https://user-images.githubusercontent.com/22955861/81048394-b1c6de80-8ed5-11ea-9047-18367a6ee12b.png)
