### ISSUE TITLE
Inventory Adjustment - Syntax Error / Animation Loop

### ISSUE THREAD

**Issue by DVTGroup** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1094]
**Bug Report**
**----------**

By: DVTGroup

**POST** Data (postAdjustment)
type=1
adjustment_qty=1
new_cost_price=0
notes=test4
prod_id=21330184
idx=27250957
in_stock=41
created_on=(int variable)

**Response**:
{"error":0} - Assuming this means that there is no error

**Conclusion**:
`https://app.repairdesk.co/index.php?r=InventoryAdjustment/postAdjustment`
Fails because of the syntaxing error in the "notes" field.

Normally:
notes= test

Failing:
notes= firstline
secondline

POST Data when we fill in 2 lines:
type=1
adjustment_qty=2
new_cost_price=0.00
notes=firstline
secondline
prod_id=21330184
idx=27250957
is_serialize=0
adj_popup=""
openedFromPos=0
tabInPos=0
in_stock=42
created_on=(time variable)

Second line doesn't get parsed from the field to the POST data because of the syntax error but the form data (in the browser request) does include the text:
notes:	"firstline\nsecondline"

**Result**:
The browser keeps loading and it doesn't get updated. The load icon (or animation) keeps showing, when pressing ESC the menu does close but the loading animation keeps going.
When you add /n to the notes field (first line) it will still continue without issues.  It is because of an unescaped line break. But this is just me assuming from what I have seen before.
I've seen this happen with more than just the inventory adjustment, once I do I will file it under this report.

I still have the request where the error is caused, if this is needed for the Dev Team. 
If so, please contact me directly so I can send the file in private.

**Comment by MuhammadAdnan32** [comment]
Hey @DVTGroup , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hey! @DVTGroup,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up .
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1103

**Comment by MuhammadAdnan32** [comment]
Hey @DVTGroup ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.
Thanks!
Regards,
M Adnan
