### ISSUE TITLE
RepairDesk - IOS App Crash + Invoice Error / null value

### ISSUE THREAD

**Issue by DVTGroup** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1095]
**Bug Report**
**----------**

By: DVTGroup
Bug: The app crashes when adding signature to invoice payments

**Explanation**:
I found this while searching for bugs in the IOS App of RepairDesk (not the Reports app)
The app crashes when you open an invoice and try to add a signature, but also trying to add a payment (partial payment) will fail and cause an "something went wrong" popup.

**Replicate** (Add signature app crash):
1. Open the App
2. Select "Invoices"
3. Open any random invoice
4. Select the "Invoice Actions" menu (top right)
5. Select "Customer Signature"
6. The app crashes after the screen is initialized
OR
5. Select "Add Payment"
6. Select "Signature" 
7. The App crashes after the screen is initialized

**Replicate** (Invoice Error)
1. Open the App
2. Select "Invoices"
3. Open any unpaid invoice (has to be unpaid)
4. Select the "Invoice Actions" menu (top right)
5. Select "Add Payment"
6. Fill in the details (Amount, Payment Method, Date)
7. Select "Done"
8. The App shows you a "Alert! something went wrong" pop-up

This only happens when the amount is **less** than the full amount. (This doesn't happen when you de-select Full Payment and the amount filled in is the same as the total amount)

At last there is a small detail which should be fixed.
When viewing a Invoice, if the price of an item is filled in as 0.00 the invoice will show:
`€(null)`
This will only show under the "Item Information" section.

**Comment by MuhammadAdnan32** [comment]
Hey @DVTGroup , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards,
M Adnan

**Comment by Afnan-Mahmood** [comment]
Dear @DVTGroup 

Hope you are staying safe.

This is Afnan from iPad team. I am looking in to your reported issues.
I just tried at my side with same steps from iPad App on our testing account and found all functionality working fine. It might be account specific issues or it can be understanding issue.
Can we have a one to one discussion?
You can drop your Whatsapp number or you can reach me out directly at: afnan@repairdesk.co

Looking forward to hearing back from you.

Best,
Afnan Mahmood
RepairDesk iPad team

**Comment by Afnan-Mahmood** [comment]
Dear @DVTGroup 

I found out that you are using our old app which is depreciated for now. We are near to launch our very exciting new hybrid app. In this hybrid app you can do all upper mentioned functionalities with out crash. 

Hope this helps.

If there is anything else we can do for you please don't hesitate to reach out.

Best,
Afnan Mahmood
RepairDesk iPad Team
