### ISSUE TITLE
HTML Code - Attributes Showing - Possible HTML Injection

### ISSUE THREAD

**Issue by DVTGroup** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1096]
**Bug Report**
**----------**

By: DVTGroup
Bug: HTML Code starts to show when using slashes in item names. 

**Explanation**:
I found this while looking for bugs in the RepairDesk web interface. 
When you have a item name that includes slashes in the item name, and you search for the item at Point of Sale.
The search results will result in the item name, and the HTML attribute <b>.
(Which could be escelated to a HTML injection, seeing as it needs a user to be logged in it shouldn't be that critical)

**Replicate** (Add signature app crash):

**1. Log in on the RepairDesk Web interface
2. Create an item which has (amount you prefer, I choose 3) slashes in it.
	For example: Item Name / With / Slashes
3. Go to Point of Sale
4. Search for the item you just created with the slashes.
5. When using 3 slashes you will see that the amount of <b> attributes shown will be increased the more slashes are in the item name.
	Example: When you fill in "Item /" you will see "Item</b>Name / With / Slashes
	Example: When you then fill in "Item Name /" you will see "Item</b> Name</b> / With / Slashes
	Example: When you after that fill in all 3 slashes (to fill in the entire item name), you will see "Item</</b>b> Name</</b>b> /</b> With</b> /</b>"
6. Selecting the specific item will just show the Item Name correctly.**

**Note**: This bug also appears when you use the Inventory Filter function.
The amount of HTML <b> or </b> attributes will increase the more slashes are filled in.
This is not limited meaning:
`Item Name / With / Slashes / / / `
Can be filled in and doesn't stop showing the Item with slashes. 
While normally the item would disappear from our filter search when it contains more in the itemname (search) than the actual item name contains.

The result of the above search:
```
Item</</b></</b>b></</b></</b>b>b></</b></</b>b>
</</b></</b>b>b>b>b> Name</</b></</b>b></</b></</b>b>b>
</</b></</b>b></</b></</b>b>b>b>b> /</b></</b>b></</b>
</</b>b>b></</b></</b>b></</b></</b>b>b>b> With</</b>
</</b>b></</b></</b>b>b>b>b> /</b></</b>b></</b></</b>b>b>
</</b></</b>b></</b></</b>b>b>b> Slashes</</b></</b>b>b> ,
```

The more slashes the more chaos it becomes.
Yes, I have typed the above directly over because it's not copy-pastable.
Also what I noticed was that '%' character can be filled in without any actions taken against it.
The output still gives back the one with all the slashes and including the '%' character.

**Comment by MuhammadAdnan32** [comment]
Hey @DVTGroup , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hey! @DVTGroup 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up . 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1102

**Comment by MuhammadAdnan32** [comment]
Hey @DVTGroup ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.
Thanks!
Regards,
M Adnan
