### ISSUE TITLE
Lead ID Appt Calender Email | Alexander Thompson | iCare Repair Milford

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1097]
**Hi Sir,**

**Business Name / Store Name:**
iCare Repair Milford

Admin: Yes

**Customer Stature:**
He has 5 Store Locations, Already On-Boarded with 3 Store, 2 Stores will be coming in future.

**Module:**
Integration/Appointment Calender

**Issue:**
Is there a way to add the lead number directly to the confirmation instead of just the confirmation email on the appointment calendar?

**Video Link:**
https://drive.google.com/file/d/1VfI0GYMX2KzwYoa2D4kARzRP5Ab_SCyc/view

Chat Source:
https://app.intercom.com/a/apps/mq09yl4f/inbox/inbox/3841902/conversations/26465783010

Thanks and Regards,

**Comment by fahadimran303** [comment]
Internal Chat Link:
https://repairdesk.atlassian.net/browse/REP-2490

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303 
I hope you are doing well, the above-sugessted improvement is now live. you can add **Lead Id** tag to the success page from **appointment calendar** **advance configurations**. 
![FIXAPHONE_RepairDesk_Bookrepair_Config](https://user-images.githubusercontent.com/22955861/82052378-f6702800-96d4-11ea-82e3-52366a8d298c.png)
Kind regards,
