### ISSUE TITLE
Improvement to have Delivery label | Curro Quevedo Bueno | ZOOO

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1101]
Hi Sir,

**Business Name / Store Name**
ZOOO

**Module:**
Label templates

**Improvement:**

Customer has requested that because of Lock-down their business is mostly running online. He wants to have a parcel delivery Label so when he send a parcel through a courier, he can paste a particular label on it.

Kindly let us know your opinion on this request.

**Chat:**
https://app.intercom.com/a/apps/mq09yl4f/inbox/inbox/3841891/conversations/26655196103

**_Thank You and Regards,
Talha_**

**Comment by fahadimran303** [comment]
Internal [Jira ](https://repairdesk.atlassian.net/browse/REP-2528?atlOrigin=eyJpIjoiZjVjNTY0OWY0YjFkNDYyZmExYTU0NTg3ZGMyYTY4YmMiLCJwIjoiaiJ9)Link

**Comment by Uzair-RepairDesk** [comment]
Did you refer him existing ticket label? @fahadimran303 
What's the exact information he wants on the delivery label? 
The requirement seems to be incomplete with no use case.
