### ISSUE TITLE
Improvement in selecting appointment slot | Raphael Schlemann | 4tronics

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1102]
Hi Sir,

**Business Name / Store Name**
4tronics

**Module:**
Appointment calendar

**Improvement:**
Customer has requested to have a small improvement in appointment calendar's time slot booking. When customer comes on the page where he has to select a slot, the very first time slot is already selected and that option is already blue. He wants that no option should be selected prior to the customer does that.

Kindly share your opinion on this request.

**Video:**
https://drive.google.com/file/d/1ckt5IPCNUCguCGu_XXXKCoUBKu9iMuV1/view

**Chat:**
https://app.intercom.com/a/apps/mq09yl4f/inbox/inbox/all/conversations/26557666664

_**Thank You and Regards,
Talha**_

**Comment by fahadimran303** [comment]
Internal Jira [Link](https://repairdesk.atlassian.net/browse/REP-2529?atlOrigin=eyJpIjoiNDFhZGYzNjE5ZTY5NDE4M2E5ZjlkZTk5NGUwYTNmZTgiLCJwIjoiaiJ9)

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303  
Hope you are doing well, we have made this improvement live. now at the time of slot selection on the option will be selected and the user needs to select the option all by himself.
