### ISSUE TITLE
Buy & Sell Widget Issue

### ISSUE THREAD

**Issue by istationonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1111]
URL's getting blocked in buyback widget "ICloud Agreement for Apple Devices"

**Comment by usmanalikhan93** [comment]
Hi @istationonline 

I hope you are doing well. Can you provide more info on this ?

**Comment by usmanalikhan93** [comment]
Hi again @istationonline   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards, 
Usman Ali
