### ISSUE TITLE
Ticket Status Behavior from Manage Ticket | Jose | iTech Connection

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1115]
**Hi Sir,**

**Business Name | Store Name:**
Jose | iTech Connection

**Customer Stature:**
2 Store Location with Annual Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

**Module:**
Manage Tickets

**Improvement:**
Customer has come up with a request that once we go to Manage Ticket Section and Search for Ticket Status as Repaired and Collected, it doesn't give us any results in case we have enabled the trigger of Hide Closed Tickets.

**Video:**
https://drive.google.com/file/d/1XKn9RRGCMwqTKHRvn6jppokmyVYoFd8L/view

**Source:**
Facebook

**Thanks and Regards,**
Fahad Imran

**Comment by fahadimran303** [comment]
Internal Jira Link:
https://repairdesk.atlassian.net/browse/REP-2549

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303
I hope you are doing well. we have made this improvement live. now if the user searches with specific status the ticket will be shown despite that we have enabled the trigger of Hide Closed Tickets.
