### ISSUE TITLE
Improvement in Manage Ticket Flow | Jose | iTech Connections

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1117]
**Hi Sir,**

**Business Name | Store Name:**
Jose | iTech Connection

**Customer Stature:**
2 Store Location with Annual Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

**Module:**
Manage Tickets

**Improvement:**
Customer has come up with a request that once he edits the ticket and add a new problem, it doesn't show the Due Amount in the Invoice after the new problems are added.

**Video:**
https://drive.google.com/file/d/1kcEePlnzKdIxafIvJJi3QYIzAqARf2d7/view

**Source:**
Facebook

**Thanks and Regards,**
Fahad Imran

**Comment by fahadimran303** [comment]
Internal Task Link:
https://repairdesk.atlassian.net/browse/REP-2551

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303  
Hope You are doing well,  the above mention improvement is now live. you can view due amount upon edit from manage tickets section and from the POS section as well.
attached is the reference screen from POS.
![FIXAPHONE_POS](https://user-images.githubusercontent.com/22955861/87664902-78390c00-c77f-11ea-9927-b33a76a87fe5.png)
