### ISSUE TITLE
Improvement in Refund Invoice Behavior | Jose | iTech Connection

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1118]
**Hi Sir,**

**Business Name | Store Name:**
Jose | iTech Connection

**Customer Stature:**
2 Store Location with Annual Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

**Module:**
Manage Tickets

**Improvement:**
Customer has come up with a request that Refund of OverPaid/Due Invoice is very time consuming and its very hard to implement specially with multiple employees on the store.

**Video:**
https://drive.google.com/file/d/15oTNIar-skeg8a8JmxSFaixJNrpC8GGK/view?usp=sharing

**Source:**
Facebook

**Thanks and Regards,**
Fahad Imran

**Comment by Uzair-RepairDesk** [comment]
Dear @fahadimran303 
I believe you have already suggested the right workaround based on our discussion. If the invoice is already paid, it's not suitable to update the price of service. This is a data anomaly created by the customer. 
Can you please confirm that what is the feedback of Jose on this? Also, did you suggest enabling the trigger i.e. "Can't edit the ticket once the invoice is created" so he shouldn't update the price if the invoice is paid? If the service price is less, he can add the notes and refund the payment invoice.

**Comment by Uzair-RepairDesk** [comment]
@fahadimran303 
??

**Comment by fahadimran303** [comment]
Jose has a work flow in which after checking the phone, most of the time he has to adjust a different problem, Also he says its very hard for his employees as they are getting 2-4 tickets daily in which they have to adjust this

Please keep this in the loop and see when we can have this work flow a bit better.
