### ISSUE TITLE
New Problem in Appointment Calendar | Jose | iTech Connection

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1119]
**Hi Sir,**

**Business Name / Store Name:**
Jose | iTech Connection

**Admin:**
Yes

**OS:**
Windows / MacBook

**Module:**
Appointment Calendar

**Configuration Setting:**
Correct

**Roles & Permissions:**
Correct

**Issue:**
Customer has reported an issue that Appointment Calendar books a Lead even if the customer just enter any word in Problem Section

**Steps to Reproduce Issue/Provide Video:**
https://drive.google.com/file/d/1ekiLmjgjc-XRnxWpjYZrYWjWkofc8tvU/view

**Chat Source:**
FB

**Thanks and Regards,**
Fahad Imran

**Comment by fahadimran303** [comment]
Internal Jira Link:
https://repairdesk.atlassian.net/browse/REP-2553

**Comment by usmanalikhan93** [comment]
Hi @fahadimran303 

I hope you are doing well. If customer didn't find any problem listed then he/she writes over there and proceed. This is functionality. Rest , @Uzair-RepairDesk can guide you on this. 

Regards,
Usman Ali

**Comment by Uzair-RepairDesk** [comment]
@fahadimran303 
This is the default functionality and option for the customer to write the problem if he doesn't find it in the list. This is not an issue. If a customer writes anything, its added and appears on the lead so admin/users can reach out to the customer to find out the details. 

Hope it helps.

**Comment by Uzair-RepairDesk** [comment]
@fahadimran303 Please update if you got the understanding of this?

**Comment by fahadimran303** [comment]
Customer is using the option of Email Invoice via RD Payment. He is getting a lot of leads with new problems with 0 price. Also he doesn’t want the customer to select any other problem.

Please check if we can make this as a trigger based.

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303 
I hope you are doing well. We have made this feature live. now you can restrict customers from creating device issues on the go. we have added a trigger, once you enable the trigger customer will not be able to create the device issue. 
attached is the screen for reference.
![FIXAPHONE_RepairDesk_Bookrepair_Config](https://user-images.githubusercontent.com/22955861/84764991-fb800a00-afe7-11ea-9a11-ceb42256c0c5.png)
