### ISSUE TITLE
Mobile App Feedback Thread

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1120]
Creating a thread so beta users can submit feedback for the android and iOS app here

**Comment by iMrPhix** [comment]
There is no current sales dashboard on the app 
So as a manager when I login I can’t see current sales on the app

**Comment by Uzair-RepairDesk** [comment]
Hi @iMrPhix 
Thank you for your feedback. Appreciate it. We have a plan to make dashboards for managers/admin and employees separately. It is included in our roadmap. Here is a link from our public roadmap:-

https://trello.com/c/pI8XcwDr/42-repairdesk-mobile-app-admin-employee-dashboards-and-kpis
