### ISSUE TITLE
Edit Ticket Information Issue | Jose | iTech Connection

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1121]
**Hi Sir,**

**Business Name / Store Name:**
Jose | iTech Connection

**Admin:**
Yes

**OS:**
Windows / MacBook

**Module:**
Inventory

**Configuration Setting:**
Correct

**Roles & Permissions:**
Correct

**Issue:**
Customer has reported an issue that once we edit the ticket and add some information, we have to save the ticket on every step.

**Steps to Reproduce Issue/Provide Video:**
https://drive.google.com/file/d/1kcEePlnzKdIxafIvJJi3QYIzAqARf2d7/view

**Chat Source:**
FB

**Thanks and Regards,**
Fahad Imran

**Comment by fahadimran303** [comment]
As per feedback from Usman Ali Khan, creating an improvement request.

**Comment by fahadimran303** [comment]
Internal Task Link:
https://repairdesk.atlassian.net/browse/REP-2556

**Comment by fahadimran303** [comment]
Another customer who recently Signed Up for Annual Plan is also reporting this. Can we have this fixed right after Eid?

**Comment by Uzair-RepairDesk** [comment]
Let's discuss this when we meet after Eid @fahadimran303
