### ISSUE TITLE
Resume of due invice reminder problem

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1122]
Hello,
# 1053 is indeed corrected, thank you. however, the # 463 reporter on October 3, 2018 and the # 706 reporter on March 7, 2019 (to name a few), still doesn't work. That is to say that the tags (macros) used do not match anything. See attached photo of what our customers have received since 2018 as being assumed to be their statement of account.
Here are the errors:
1- the tags do not all work. I have taken care to look at the list of macros available below so as not to be mistaken in their spellings. I also re-initialized the model to make sure there is no other problem.

2- the summary in table with the date, the invoices, the amounts etc, which is attached in the pre-defined message of the invoice reminder, does not display any result. Invoices due are not shown there and no details either. (see attachment with me as client who currently owes 2 invoices)

more in the # 735 reporter on March 20, 2019 here is what we found:
3- I would like to have a box "attach invoices" to shipments of customer statements. Currently, almost all customers send us an email telling us to send them the invoices regarding their statement of account. We know that the invoices have already been sent to them, but almost all of our customers with an open account ask for them.

4- Also, regarding task # 417 (3) the account statement of the client groups should be sent automatically according to the due date. When the invoice is created, it is automatically sent by email. however, since the due date is scheduled according to the client group, an automatic email should be sent. In this sense, no email is sent automatically at this time.
<img width="674" alt="invoice reminder resume" src="https://user-images.githubusercontent.com/40500094/80424591-123f9580-88b0-11ea-89dc-eebbbccc64ba.png">

-----
French: 

Bonjour, 
Le # 1053 est effectivement corrigé, merci. cependant, le #463 reporter le 3 octobre 2018 et le #706 reporter le 7 mars 2019 (pour ne nommer que ceux la), ne fonctionne toujours pas. C'est à dire que les tag (macros) utilisé ne correspondent avec rien. Voir photo en pièce jointe de ce que nos clients recoivent depuis 2018 comme étant suposé être leur état de compte. 
Voici les erreurs:
1- les tag ne fonctionnent tous pas. J'ai pris soin de regarder la liste plus bas des macros disponible afin de ne pas me tromper dans leurs orthographes. J'ai aussi réunitialisé le modèle afin d'être certaine qu'il n'y ai pas un autre problème. 

2- le résumé en tableau avec la date, les factures, les montant etc, qui est jointe dans le message pré-défini du invoice reminder, n'affiche aucun résultat. Les factures dû n'y sont pas montrés et aucun détails non plus. (voir pièce jointe avec moi comme client qui doit 2 factures actuellement)

deplus dans le #735 reporter le 20 mars 2019 voici ce qu'on y trouvait:
3- J'aimerais avoir une case "joindre les factures" à l'envois des états de compte des clients. Actuellement, presque tous les clients nous envoie un courriel nous mentionnant de leur envoyer les factures concernant leur état de compte. Nous savons que les factures leur ont déjà été envoyé, mais presque tous nos clients ayant un compte ouvert nous les demande.

4- Aussi, concernant la tâche #417  (3) l'état de compte des groupe de client devrait s'envoyer automatiquement selon la date dû. Lorsque le facture est créé, elle est envoyé automatiquement par courriel. cependant, puisque la date dû est programmé selon le groupe de client, un courriel automatique devrait s'envoyer. Dans ce sens, aucun courriel ne s’envoie automatiquement actuellement.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk can you please check point number 3 and 4 as she is asking for improvement.

**Comment by usmanalikhan93** [comment]
For point 1 and 2 I have created a bug, for internal use: 
https://repairdesk.atlassian.net/browse/RB-1152

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported point 1 and 2 has been resolved and verified, do verify at your end and let us know if you have any question. 

Thanks
Usman Ali

**Comment by Uzair-RepairDesk** [comment]
@JessicaSOS 
Can you please verify points 1 and 2 at your end? Thanks.

**Comment by JessicaSOS** [comment]
For now I found how desactivate other store exept Limoilou (the only one is open now)

But for this store, the modification is not working, please check Limoilou store.

The “holiday” are made for Monday but it don’t appear on the website. 

If I change the normal hour in appointment widget, is not change anything on the website. 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 4 mai 2020 07:30
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Resume of due invice reminder problem (#1122)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

I hope you are doing well. Your reported point 1 and 2 has been resolved and verified, do verify at your end and let us know if you have any question.

Thanks
Usman Ali

**Comment by JessicaSOS** [comment]
My laste emai is not for this issue, sorry, Is about the appointment calender

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 4 mai 2020 07:30
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Resume of due invice reminder problem (#1122)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

I hope you are doing well. Your reported point 1 and 2 has been resolved and verified, do verify at your end and let us know if you have any question.

Thanks
Usman Ali

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you please check the response by Jessica. Thanks

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Can you please share your Website link here, so I can review the issue on it ?

**Comment by JessicaSOS** [comment]
I tested today and here are the results IN ALL CAPLOCK:

1- the tags do not all work. I have taken care to look at the list of macros available below so as not to be mistaken in their spellings. I also re-initialized the model to make sure there is no other problem. 
**NOT FIXED YET**

2- the summary in table with the date, the invoices, the amounts etc, which is attached in the pre-defined message of the invoice reminder, does not display any result. Invoices due are not shown there and no details either. (see attachment with me as client who currently owes 2 invoices) 
**FIXED :)**

more in the # 735 reporter on March 20, 2019 here is what we found:
3- I would like to have a box "attach invoices" to shipments of customer statements. Currently, almost all customers send us an email telling us to send them the invoices regarding their statement of account. We know that the invoices have already been sent to them, but almost all of our customers with an open account ask for them. 
**NOT FIXED YET**

4- Also, regarding task # 417 (3) the account statement of the client groups should be sent automatically according to the due date. When the invoice is created, it is automatically sent by email. however, since the due date is scheduled according to the client group, an automatic email should be sent. In this sense, no email is sent automatically at this time. 
**NOT FIXED YET**

---- french:-----
J'ai tester aujourd'hui et voici les résultats EN MAJUSCULE:

1- les Tag ne fonctionnent pas toutes. J'ai pris soin de regarder la liste des macros disponibles ci-dessous afin de ne pas me tromper dans leur orthographe. J'ai également réinitialisé le modèle pour m'assurer qu'il n'y a pas d'autre problème. 
**PAS ENCORE RÉGLÉ**

2- le récapitulatif en tableau avec la date, les factures, les montants etc, qui est joint dans le message prédéfini du rappel de facture, n'affiche aucun résultat. Les factures dues n'y figurent pas et aucun détail non plus. (voir pièce jointe avec moi en tant que client qui doit actuellement 2 factures)
**RÉGLÉ :)**

plus dans le journaliste n ° 735 du 20 mars 2019, voici ce que nous avons trouvé:
3- Je souhaite avoir une case «joindre les factures» aux envois de relevés clients. Actuellement, presque tous les clients nous envoient un e-mail nous demandant de leur envoyer les factures relatives à leur relevé de compte. Nous savons que les factures leur ont déjà été envoyées, mais presque tous nos clients avec un compte ouvert les demandent. 
**PAS ENCORE RÉGLÉ**

4- De plus, en ce qui concerne la tâche # 417 (3), le relevé de compte des groupes de clients doit être envoyé automatiquement selon la date d'échéance. Lorsque la facture est créée, elle est automatiquement envoyée par e-mail. cependant, puisque la date d'échéance est planifiée en fonction du groupe de clients, un e-mail automatique doit être envoyé. En ce sens, aucun e-mail n'est envoyé automatiquement pour le moment. 
**PAS ENCORE RÉGLÉ**

**Comment by JessicaSOS** [comment]
1- fixed
2- fixed
3- not done
4- not done 

--

1- réglé
2- réglé
3- pas fait
4- pas fait

**Comment by usmanalikhan93** [comment]
Update: 
Bugs are resolved now. Enhancements are left. 
@Uzair-RepairDesk FYI

**Comment by Uzair-RepairDesk** [comment]
Hello @JessicaSOS 
Hope you are well. Is it possible to log points 3, 4 with a new task as it is a request for a new feature so we can log it separately on your behalf. Thanks. 

Regards,
Uzair
