### ISSUE TITLE
Invoices

### ISSUE THREAD

**Issue by homesick4de** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1123]
So, on previously made invoices, I see that there always an amount due. Upon research, it is adding one tax to the total then taxing it fully again. 

So most orders I have say owe an additional $1-$10.

I have not tested created an invoice yet, but this is based on the few minutes I've spent checking around the Android App.

Edit: for example, one order for $30 is now $31.72 before tax and now taxed again making it higher.

**Comment by Uzair-RepairDesk** [comment]
Hello @homesick4de 
Thank you for taking interest in beta testing of our android app. You can directly log your feedback here #1120 so we can accumulate all the feedback to work and improve the Android app. Thanks

**Comment by usmanalikhan93** [comment]
Hi @homesick4de 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
