### ISSUE TITLE
Repair Issues that are disabled on widgets still showing up on booking app.

### ISSUE THREAD

**Issue by EDDYAGGI** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1128]

**Comment by MuhammadAdnan32** [comment]
Hey @EDDYAGGI , 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hey @EDDYAGGI , 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1177

**Comment by usmanalikhan93** [comment]
Hi @EDDYAGGI 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks,
Usman Ali

**Comment by EDDYAGGI** [comment]
Thanks brother
