### ISSUE TITLE
Serialized & P.O issues 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1129]
Hello, 

Im having issues, with the serialized merchandized as well as the Purchase orders. I made a video and they were sent to Fahad via email.

**Comment by Omar1892** [comment]
Email address: 
fahadimran85@gmail.com

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards
M Adnan

**Comment by Uzair-RepairDesk** [comment]
@MuhammadAdnan32 @usmanalikhan93

**Comment by usmanalikhan93** [comment]
@MuhammadAdnan32 can you please discuss this with Fahad Imran ? So he can guide Omar.
