### ISSUE TITLE
Security Code | Sajid | Capital Solutions

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#113]
Customer is facing issue regarding security code.
If he clicks on manage tickets and then select a ticket number, he should be able to click on pre conditions and see the security code. But it does not show. Instead he has to save the ticket and then click print which is where he would be able to see it. It only shows up during print. 

Customer: Sajid | Capital Solutions

**Comment by Repair-Desk** [comment]
@Fazal-RepairDesk Can you share screenshot for better understanding?

**Comment by Fazal-RepairDesk** [comment]
![sajid github](https://cloud.githubusercontent.com/assets/22954033/20478909/e805a54a-affd-11e6-9d4c-d4a62041c995.png)

**Comment by Fazal-RepairDesk** [comment]
When Sajid create an estimate in pos, it shows up as an invoice and it shows the wrong tax. check invoice 003
