### ISSUE TITLE
Ticketing Editing Issues 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1130]
Hello, 

Ive created a video about an issue regarding when ever a ticket is edited the taxes are removed as well as the warranty from the parts that are going to be used. The video was sent to 
fahadimran85@gmail.com

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!
Thanks 
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1188

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.
Thanks!
Regards,
M Adnan

**Comment by Omar1892** [comment]
Its working but taxes are not being calculated right. To get the error Im getting what im doing is adding and removing services on the same "device issue box" as well as adding and removing parts. When you do this the taxes get distorted.

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!
Thanks,
Regards,
M Adnan

**Comment by Omar1892** [comment]
If you guys can also check up on when applying a discount from the ticket edited the taxes are marked down to $0.00 in taxes.

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Omar1892** [comment]
@MuhammadAdnan32 Hello, it seemed that the issue had being fixed until yesterday. We had created a ticket with no parts and once the parts were placed in the ticket. The taxes were being calculated on the total repair cost. I had to calculate them manually.

**Comment by Omar1892** [comment]
@MuhammadAdnan32 Hello, ive sent a video to fahadimran85@gmail.com showing how the taxes are still being miss calculated.

**Comment by MuhammadAdnan32** [comment]
Hello @Omar1892 ,
Alright! thank you for sharing the video with us.l will take a look into this and circle back to you asap.
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hello @Omar1892 ,
I have watched the video but video content is not visible and showing blur results. Can you please share the same video again in a better format? So I will look into the issue and update you accordingly.
Thanks,
Regards,
M Adnan

**Comment by Omar1892** [comment]
@MuhammadAdnan32 Video was resent to  fahadimran85@gmail.com let me know if it works this time.

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
Alright! thank you. Sure! I will update you asap.
Thanks & Regards,

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any question.
Thanks & Regards,
M Adnan
