### ISSUE TITLE
Customer reminder for appointments 

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1131]
Can we send an auto email and text on day of appointment to remind customer to come in for booking

**Comment by Uzair-RepairDesk** [comment]
Hey @jeffsand8243  
Yes, you can send an email or SMS to the customer to remind for the booking.
Open specific lead from mange leads click on send Email at the end on the screen and you can send email or SMS  to the customer.
![FIXAPHONE_Update_Leads](https://user-images.githubusercontent.com/22955861/81168679-e0fe4e00-8fb0-11ea-9a32-744c0c9ae9af.png)
 Hope this helps.if you have any other question feel free to ask.
Regards

**Comment by jeffsand8243** [comment]
Thanks. I just meant was there a way to auto sent email on day of appointment 

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7559 Highway 72 W. Suite B Madison, AL 35758

(Across from Academy Sports at corner of Nance Rd and 72, in front of Marcos pizza)

(Hours) 10-6pm weekdays, 
10-5pm Saturday. Closed Sunday

**Comment by Uzair-RepairDesk** [comment]
Hey @jeffsand8243 
Thanks for your response, currently we have a trigger in appointment calendar configuration by enabling that customer gets a reminder SMS for an appointment on that specific day.
 The auto-email reminder option is not available for now.
I will forward this request to the product team and will keep you posted on this.
Regards

**Comment by jeffsand8243** [comment]
Ok thank you!

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7559 Highway 72 W. Suite B Madison, AL 35758

(Across from Academy Sports at corner of Nance Rd and 72, in front of Marcos pizza)

(Hours) 10-6pm weekdays, 
10-5pm Saturday. Closed Sunday
