### ISSUE TITLE
Item number modify won’t work on pos 

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1136]
When we accidentally ring up two items of same type and you try to change it to 1 it won’t let you change the number. You have to delete the item and start over. Please fix this

**Comment by MuhammadAdnan32** [comment]
Hey @jeffsand8243 ,
Can you please provide more info on this as I am unable to understand this issue?
Thanks & Regards,
M Adnan

**Comment by jeffsand8243** [comment]
when you try to modify the quantity of an item it won’t let you on pos.  if i accidentally ring up 2 iPhone 6 trade ins then i can’t change the qty back to 1. i have to delete them both and start over.

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199 <tel:256-414-1199>
www.TheSmartphoneMedics.com <http://www.thesmartphonemedics.com/>
 <>7559 Highway 72 W. Suite B Madison, AL 35758 <x-apple-data-detectors://2/2>

Corner of Nance Rd. and 72
(Across from Academy Sports) 

(Hours) 10-6pm <x-apple-data-detectors://6> Weekdays,
  		 <>10-5pm  <x-apple-data-detectors://4> <>Saturday <x-apple-data-detectors://4>

**Comment by MuhammadAdnan32** [comment]
Hey @jeffsand8243 ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up . 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1181

**Comment by jeffsand8243** [comment]
This is still not working today 

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7559 Highway 72 W. Suite B Madison, AL 35758

(Across from Academy Sports at corner of Nance Rd and 72, in front of Marcos pizza)

(Hours) 10-6pm weekdays, 
10-5pm Saturday. Closed Sunday

**Comment by jeffsand8243** [comment]
Any update on this?

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7559 Highway 72 W. Suite B Madison, AL 35758

(Across from Academy Sports at corner of Nance Rd and 72, in front of Marcos pizza)

(Hours) 10-6pm weekdays, 
10-5pm Saturday. Closed Sunday

**Comment by Uzair-RepairDesk** [comment]
Hey @jeffsand8243 
As we have already marked the label that it has been assigned to the engineering team. We will post a comment once we get an update. Thank you for your patience.

**Comment by MuhammadAdnan32** [comment]
Hey @jeffsand8243 ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.
Thanks!
Regards,
M Adnan
