### ISSUE TITLE
I dont need select customer

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1139]
I dont need select customer in accessories tab checkout in ipad apps just i need select customer in creat repair ticket , this issue in new update.

**Comment by Afnan-Mahmood** [comment]
Hello @hitman1986 

We fixed a bug related to this.
For customer selection there is two separate trigger. 
You need to update these triggers setting from web.
One trigger is under: **Module configuration > Repairs**. This trigger only for **repairs**. If this trigger is active than in this case app makes mandatory customer info in case of repairs only.
2nd trigger is under: **Module configuration > invoices**. This triggers only for **accessories**. If this trigger is active than app makes mandatory customer info in case of Products/Trade-In/Casual.

Earlier these two triggers are conflicting with each other. We resolved this bug. Just update your trigger setting from web and manual sync iPad app. It surely works for you.

If still there is any question or input required from our side please don't hesitate to mention. We love to sort out problems.

Best,
Afnan Mahmood
RepairDesk Team

**Comment by hitman1986** [comment]
Thanks, its sloved.
