### ISSUE TITLE
Post Signatures Behavior | Jose | iTech Connection

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1140]
**Hi Sir,**

**Business Name | Store Name:**
Jose | iTech Connection

**Customer Stature:**
2 Store Location with Annual Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

**Module:**
Manage Tickets

**Improvement:**
Customer has come up with a request that if they have taken the complete payment up front and when the customer comes back in order to collect the phone, there is no way of taking Post Repair Signatures against Terms and Conditions.

In case there is a way, please guide me.

**Source:**
Facebook

**Thanks and Regards,**
Fahad Imran

**Comment by fahadimran303** [comment]
Internal Task Link:
https://repairdesk.atlassian.net/browse/REP-2579

**Comment by fahadimran303** [comment]
I have already gave a work around to take $1 less however he is taking most of the payments via Card.

**Comment by Uzair-RepairDesk** [comment]
Is he using a customer-facing display widget or direct signature option? No clear task description of the video is attached to this.  @fahadimran303
