### ISSUE TITLE
Commission Amount Behavior in Split Case | Jose | iTech Connection

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1141]
**Hi Sir,**

**Business Name | Store Name:**
Jose | iTech Connection

**Customer Stature:**
2 Store Location with Annual Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

**Module:**
Employee Commission

**Improvement:**
Customer has come up with a request that there should be an option to give 50% commission to both technician or to the person who creates an Invoice.

Also the word used in the module is SPLIT which means we are dividing commission however currently it gives 100% to both employees.

**Video:**
https://drive.google.com/file/d/1NmHW93JHMMN8RX18QuM011FugzvBucMs/view

**Source:**
Facebook

**Thanks and Regards,**
Fahad Imran

**Comment by fahadimran303** [comment]
Internal Task Link:
https://repairdesk.atlassian.net/browse/REP-2581

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303 
Hope you are doing well, we have made this improvement live,   now if the commission is set against any service then the commission percentage or amount sent on the service will be split in both technician and salesperson.E.g. if the commission on service is $10 then $5 will be given to each employee.
