### ISSUE TITLE
Multiple Improvements in Repair Section | Jose | iTech Connection

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1142]
**Hi Sir,**

**Business Name | Store Name:**
Jose | iTech Connection

**Customer Stature:**
2 Store Location with Annual Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

**Module:**
Manage Services

**Improvement:**
Customer has requested for 2 improvements in Manage Services Section:

1) Filter to Search on the basis of Repair Category
2) Option to Clone Problem against Multiple Devices

**Video:**
https://drive.google.com/file/d/1VNqB9fCy6UMMeO36vjBWvekDTV8HRPXK/view

**Source:**
Facebook

**Thanks and Regards,**
Fahad Imran

**Comment by fahadimran303** [comment]
Internal Task Link:
https://repairdesk.atlassian.net/browse/REP-2582

**Comment by fahadimran303** [comment]
Nicholas having 4 Store Locations wants this improvement as well.

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303 
i hope you are doing well.we have this **Filter to Search on the basis of Repair Category** improvement live. now users can search on the basis of the repair category in the Manage services section.
![FIXAPHONERepairDesk_Inventory](https://user-images.githubusercontent.com/22955861/84765420-a1cc0f80-afe8-11ea-9ab5-b8a028217466.png)
