### ISSUE TITLE
Customer don't receive Email after downloading Customer data from Manage | TECNICO 2 | EXPERIMAC GALERIAS HERMOSILLOCustomer

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1145]
**Business Name / Store Name:**
TECNICO 2 | EXPERIMAC GALERIAS HERMOSILLO

**Admin:** Yes

**Store Name for the issue:**
Experimac Galerias Hermosillo

**OS:**
Windows / MacBook

**Module:**
Manage Customers

**Configuration Setting:**
Correct

**Roles & Permissions:**
Correct

**Chat Source:**
https://app.intercom.com/a/apps/mq09yl4f/inbox/inbox/conversation/26981639684

**Current Results:**
NA

**Expected Result:**
Kindly give ETA on this case of Jira. on LiveChat & Jira

**Comment by fahadimran303** [comment]
Jira link:
https://repairdesk.atlassian.net/browse/REP-2585

**Comment by Afnan-Mahmood** [comment]
@fahadimran303 

we checked this issue with the help of developer. As per our logs email forwarded to his account.
Email might goes to spam.

Jira ticket updated.
