### ISSUE TITLE
Reports module

### ISSUE THREAD

**Issue by marianabut** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1147]
To manage better your business you need numbers, statics to optimize your work.

For me is almost impossible to know at the end of the month, for example:
- which is the best selling display
- which are the most frequently repaired phones
- which are the best selling batteries, etc
- what is the income for hardware and on the software operations

If I will have this info, I will know:
-  how to optimize my stocks;
-  what new tools, the equipment for repairing I should  buy;
- I can focus better on the operations that matter.

It would be very useful if we could customize our daily reports at the end of the day, to know:
How many new phones came in;
How many repaired phones were given back to the customers;
How many phones are still on work progress.

What do you think guys?

**Comment by Uzair-RepairDesk** [comment]
Hi @marianabut 

Thank you for your post. Please find my comments below:-

For me is almost impossible to know at the end of the month, for example:
which is the best selling display
which are the most frequently repaired phones
which are the best selling batteries, etc
what is the income for hardware and on the software operations

**I believe to track all the above, you can check our "Sales by Item Type Report". You can track it with relevant search filters to track best selling products, most frequent repairs, you can track the most popular products from specific product categories like "Batteries". You can also track "Net Profit" and "Margin" with each record. https://help.repairdesk.co/knowledgebase/articles/1885114-sales-by-item-type-report ** 


If I will have this info, I will know:

how to optimize my stocks;
what new tools, the equipment for repairing I should buy;
I can focus better on the operations that matter.

**To optimize your stock, I recommend keeping "Stock Warning" and "Reorder level" with each item so you can track low stock items from "Low Stock Report" and you can order directly to your supplier from the report by creating a purchase order. I will also recommend using the "Inventory Count" feature on regular intervals to keep track of your exact stock. Please check following knowledgebase article:-
https://help.repairdesk.co/knowledgebase/articles/1892974-low-stock-report
https://help.repairdesk.co/knowledgebase/articles/1119253-how-does-the-inventory-count-functionality-work**

It would be very useful if we could customize our daily reports at the end of the day, to know:
How many new phones came in;
How many repaired phones were given back to the customers;
How many phones are still on work progress.

**You can go to "Manage Tickets" section and you should apply the date filter along with "Ticket Status" to find new, closed and open tickets**

Hope it helps.
