### ISSUE TITLE
Missing Icon on Appointment Calendar Widget

### ISSUE THREAD

**Issue by marianabut** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1148]
https://www.youtube.com/watch?v=iaASSM6Lh3U&feature=youtu.be

<img width="1179" alt="Screenshot 2020-05-14 at 19 04 49" src="https://user-images.githubusercontent.com/60131264/81958090-23a9d100-9616-11ea-9cea-427360e5580a.png">

**Comment by MuhammadAdnan32** [comment]
Hey @marianabut ,
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hey @marianabut ,
I have double checked it at my end but I am not able reproduced the issue on my test account.It seems to be an account specific issue. 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up . 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use: https://repairdesk.atlassian.net/browse/RB-1231

**Comment by marianabut** [comment]
OK, thank you!
I will wait for your answer.

**Comment by MuhammadAdnan32** [comment]
Hey @marianabut ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.
Thanks!
Regards,
M Adnan

**Comment by marianabut** [comment]
Hi, yes, is working again!  Thank you!
