### ISSUE TITLE
Issue back again when export invoices 

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1153]
When select manage invoices and search filters and select invoice status unpaid and press search and export it, not export anything and open new tab empty,why?
![ED61F996-52F6-476C-8523-9D7F0FB9D39F](https://user-images.githubusercontent.com/44485797/82167956-0f8bfb00-98c6-11ea-93f9-da0639460bf5.png)
![2C317FB5-06A7-461E-A8D4-BF396BBA7CD0](https://user-images.githubusercontent.com/44485797/82167957-1155be80-98c6-11ea-824d-d4ecf5321a3f.png)

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Thanks

**Comment by usmanalikhan93** [comment]
Hey @hitman1986  
 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

For internal use: 
https://repairdesk.atlassian.net/browse/RB-1236

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by hitman1986** [comment]
Same issue not fixed

**Comment by usmanalikhan93** [comment]
Hi @hitman1986  

I hope you are doing well. I have checked this and it is working fine. Can you please check this again ?

**Comment by hitman1986** [comment]
It fixed , just i change browser from chrome to safari
