### ISSUE TITLE
 Appointment Calendar Widget - asking a quotation / price, not working 

### ISSUE THREAD

**Issue by marianabut** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1154]
Hi, on Appointment Calendar Widget, at the prices before was 0.00 price ( if I don't have a quotation for that operation), now is '' ask a quotation''...and if you click on it,  nothing is happening. It is ok? 
![Screenshot 2020-05-20 at 11 04 05](https://user-images.githubusercontent.com/60131264/82426223-4150bd80-9a90-11ea-86dc-d1026d9191a9.png)
![Screenshot 2020-05-20 at 11 19 13](https://user-images.githubusercontent.com/60131264/82426236-457cdb00-9a90-11ea-999f-2634b3b3c5ed.png)
![Screenshot 2020-05-20 at 11 20 08](https://user-images.githubusercontent.com/60131264/82426241-46ae0800-9a90-11ea-8c89-d04f0a9c5d32.png)

**Comment by usmanalikhan93** [comment]
Hi @marianabut 

I hope you are doing well. This is the current behavior, if you have didn't set the price for repair e.g. it is 0.00, on Appointment Calendar widget it will show as "Call For Quote" against that repair. 

Regards, 
Usman Ali
