### ISSUE TITLE
Warranty Ticket 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1157]
Hello, 

Video was created and it was sent via email to 

fahadimran85@gmail.com

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,
