### ISSUE TITLE
Can't delete Manufacturers from the Inventory 

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1165]
Hi, I talked with guys from support 1 month ago with a problem which persists. I can't delete any manufacturers form the inventory. Can you resolve this bug?
![rgasa](https://user-images.githubusercontent.com/65545272/83614168-821afd00-a58d-11ea-8ee8-f71d15881745.png)

**Comment by usmanalikhan93** [comment]
Hi @adigsm07 

I hope you are doing well. Can you share you RD Credentials with me at usmanali@repairdesk.co. And do let me know which Manufacturers you want delete. 

Thanks

**Comment by adigsm07** [comment]
I discuss allready with someone from support to delete some manufacurers which are flagged with DELETE in front of their name. I don't want to do this everytime when I have something to delete. It's not possible to resolve this?

**Comment by usmanalikhan93** [comment]
@adigsm07 can you check at your end is there any device, inventory associated with this Manufacturer ?

**Comment by adigsm07** [comment]
Thank you very much Usman! I'm waiting for your resoults!

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1432

**Comment by usmanalikhan93** [comment]
Hi @adigsm07 

I hope you are doing well. We have released on fix for this issue. Can you please try now to delete this Manufacturer ? And do let me know if it deletes or not. 

Thanks 
Usman Ali

**Comment by adigsm07** [comment]
Hi Usman,
I'm doing well, thanks for asking. I tried now to delete manufacturers but
I received same error message.

Kind regards!
~Addis.

**Comment by usmanalikhan93** [comment]
Hi @adigsm07 

Can you send me your RD Credentials on usmanali@repairdesk.co

**Comment by adigsm07** [comment]
adi.gsmzone@gmail.com
pw: accesadi8899

**Comment by Uzair-RepairDesk** [comment]
@adigsm07 
We have noted down your credentials and I have removed your comment because of the privacy policy. It's an open and public forum.

**Comment by usmanalikhan93** [comment]
Hey @adigsm07 I have checked in your account and didn't find Archoss and Archosss. Can you please check again ?

**Comment by usmanalikhan93** [comment]
Hi again @adigsm07 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Usman Ali
