### ISSUE TITLE
SKU Pictures are not uploading 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1166]
When adding new inventory, the pictures are not being uploaded. 
![Screen Shot 2020-06-03 at 3 30 53 PM](https://user-images.githubusercontent.com/47898011/83695903-f1a1e400-a5af-11ea-91ca-63a20a2e55ce.png)

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up . 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1332

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.
Thanks!
Regards,
M Adnan
