### ISSUE TITLE
Improvement for Trade-In | Kevin Lopez | Eagle Eye Repairs

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1171]
**Hi Sir,**

**Business Name | Store Name:**
Kevin Lopez | Eagle Eye Repairs

**Customer Stature:**
1 Store Location with Monthly Professional Plan.
High Presence on Social Media.
It can help us a lot in other verticals as well.

**Module:**
Trade-In

**Improvement:**

The customer had requested for improvement that every time he purchases an item through the Trade-In, there should an option available for commission as well while filling up the item detail/description.

**Video:**
https://drive.google.com/file/d/18jJPsvvYoD8gxvOZtaOK0PjfTarWZT7J/view

**Source:**
Facebook

**Thanks and Regards,**

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303
As discussed we can not proceed with this request as the commission is set once the trade-in item is purchased, we cannot add commission before that. The commission is for the employee once they sell a particular trade-in item, not at the time of purchase.
