### ISSUE TITLE
Improvement in Inventory Count | Sunny | Head office

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1173]
**Hi Sir,**

**Business Name / Store Name:**
Sunny | Head office

**Module:**
Inventory Count

**Improvement:**

The Customer came up with a request that when doing Inventory Count, Currently system shows the Counted Values exactly the same as of Expected Value

I proposed a solution that we can set a button/trigger which gives us the option to make all Counted to 0. I have explained this in the video below:

**Video:**
https://drive.google.com/file/d/1Hh4i-mUvIaIreRMJlJMthwbQPmA9lUcu/view

**Source:**
WhatsApp

**Thanks and Regards,**
Fahad Imran

**Comment by fahadimran303** [comment]
Internal Task Link:
https://repairdesk.atlassian.net/browse/REP-2623

**Comment by fahadimran303** [comment]
Another customer with 2 Stores on Annual Plan also reported the same problem.

Can we prioritize this and push an update soon?

**Comment by fahadimran303** [comment]
Andrew Mourer | YCD Ionia

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303 
Hope you are doing well, we have made this improvement live, based on the trigger in inventory count section counted value will be zero by default.  and once you disable the trigger counted value will be the same as expected.
![image](https://user-images.githubusercontent.com/22955861/87665934-2e512580-c781-11ea-8d12-7cebfc51728c.png)
