### ISSUE TITLE
Option to add Customer Organization | Stacey Cossey | Powertools and Servicing Ltd

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1174]
**Hi Sir,**

**Business Name / Store Name:**
Stacey Cossey | Powertools and Servicing Ltd

**Customer Stature:**
1 Store Location with Annual Plan.

**Module:**
Manage Customer

**Improvement:**
The Customer came up with a request that he would like Customer Organization in various places in software.

I have highlighted them in the video below:

**Video:**
https://drive.google.com/file/d/1NmAglS_X00GCNdqkD1HJxNRSEnL05nTj/view

**Source:**
WhatsApp

**Thanks and Regards,**
Fahad Imran

**Comment by fahadimran303** [comment]
Internal Task Link:
https://repairdesk.atlassian.net/browse/REP-2626

**Comment by Uzair-RepairDesk** [comment]
It has been assigned to developer and he is working on it already

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303 
Hope you are doing well, it is to inform you that we have made this improvement live, now you will be able to search customer by the organization from POS screen, customer organization is available under customer detail in ticket listing section. In the invoice section, customer organization is available in a separate column and you can also search for specific tickets or invoices via customer organization.
