### ISSUE TITLE
Print Node doesnt Print Proper Invocie

### ISSUE THREAD

**Issue by DOM260096** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1175]
Hi this is difficult to explain but i feel there is an issue with the print invoice button using print node, if i manually print a A4 invoice it has no repair conditions and has a bar code showing the invoice number which fits on 1 a4 page nicely. if i select print invoice via print node it will print a similar document to the print service receipt button but the printout is stretched, has all the pre and post repair conditions and has a bar code with the ticket number instead, i spoke to Danish about this issue and showed him a video also , this is defiantly a issue with the button printing the wrong document. please call me if you need me to show you 07754584605

**Comment by fahadimran303** [comment]
I have asked Danish Hassan to connect with him today.

**Comment by DOM260096** [comment]
nobody has called ref this.

**Comment by Uzair-RepairDesk** [comment]
@fahadimran303 can you please update the thread or @usmanalikhan93 Can you please follow up with Danish on this?

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk I have asked Danish Hassan again to check this issue with customer.

**Comment by usmanalikhan93** [comment]
Hi @DOM260096 

I hope you are doing well. Let me check this with my team and I will update you.

**Comment by usmanalikhan93** [comment]
Hello @DOM260096 

I hope you are doing well. I just wanted to know that are you still facing this issue or not ? Just let me know so we can connect offline and see what's the actual issue and we can try to resolve this issue for you. 

Regards, 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @DOM260096 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
