### ISSUE TITLE
Unlocking Service Tickets 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1177]
Hello, Unlocking service tickets are not being closed once the ticket has being repaired and collected. We have to manually closed them our selfs from the tickets section.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. When you create a ticket and then open it up on POS again and made a full payment, you see on left it shows Repaired and Collected option. It it is yes, it does change the status to Repaired and Collected. I have verified on my end. Can you please check again ? 

Thanks

**Comment by usmanalikhan93** [comment]
Hi again @Omar1892  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
