### ISSUE TITLE
Save time scanning IMEI with barcode scanner?

### ISSUE THREAD

**Issue by marianabut** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1179]
We have a barcode scanner on RD, to scan the ticket or the invoice, etc.

Why can we use for scanning the IMEI form phones? 
![104352708_314999362847822_4381233544963344436_n](https://user-images.githubusercontent.com/60131264/85044291-155f4f80-b196-11ea-8547-27b9e426c7dd.jpg)
![Screenshot_20200618-121347_Service mode](https://user-images.githubusercontent.com/60131264/85044299-17291300-b196-11ea-9827-1798638f0f8b.jpg)
IMEI with barcode is available on iPhone and Samsung, and these models are the most popular.

Some times writing the IMEI takes time, with barcode we can save time.
For the rest of the model, we can write manually the IMEI.

**Comment by Uzair-RepairDesk** [comment]
Hey @marianabut 
Do you have the same IMEI record with the item in RepairDesk? 

Waiting for your response

**Comment by geelongmicrosoldering** [comment]
Hey there, I can answer this.

A standard laser barcode scanner doesn't have the hardware to "see" the barcode. They rely on the laser producing the light, and the reflection of that light translating into a barcode. The phones produce their own light, and this is why a barcode scanner like the LS2208 for example cannot see them.

If you have a more expensive barcode scanner, like a 2D barcode scanner designed to scan QR codes, they should work fine. This is because they actually have the optics to see the barcode like our eyes do.

There's more information about this, and why laser scanners cant scan smart phone screens here: https://www.id123.io/blog/barcode-scanners-phone-screens/

**Comment by Uzair-RepairDesk** [comment]
Thanks for the explanation @geelongmicrosoldering.
I believe there will be no issue to scan any barcode and RepairDesk doesn't restrict any barcode scanner to scan the barcodes. 
All you need to do that if you want to keep the same IMEI in SKU/UPC and scan it with a barcode, it should work. 

Are you keeping the same log in item ID before you scan the IMEI from the box?

**Comment by marianabut** [comment]
Yes, exactly!  When we make a new ticket on the IMEI field, no need to write manually, just scan with the bar code scanner. We can save time and mistakes.

**Comment by geelongmicrosoldering** [comment]
> Thanks for the explanation @geelongmicrosoldering.
> I believe there will be no issue to scan any barcode and RepairDesk doesn't restrict any barcode scanner to scan the barcodes.
> All you need to do that if you want to keep the same IMEI in SKU/UPC and scan it with a barcode, it should work.
> 
> Are you keeping the same log in item ID before you scan the IMEI from the box?

I don't think @marianabut is suggesting there is an issue with RD restricting the scan. Just querying why the particular setup they have doesn't work. Unfortunately its hardware related 

Perhaps recommended hardware article could be updated to note that typical Laser Barcode scanners (like LS2208) cannot scan LCD/LED screens, and if a user would like that ability to purchase a 2D/hybrid barcode scanner capable of scanning barcodes on those devices.

Standard printed barcodes still work fine, like on the label under the battery of devices with removable batteries, or the label on the battery inside most Samsung devices.

On a side note, there is software available to convert a camera, or even android device to a barcode scanner. Converting an old android device into a barcode scanner would be fine for this. Here is an example: https://play.google.com/store/apps/details?id=com.barcodetopc
(Note, I haven't used this app and there are many available, so YMMV)
