### ISSUE TITLE
Can't 'Update Ticket' on POS Web App

### ISSUE THREAD

**Issue by RepairPros** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1180]
We cannot update a ticket on the P.O.S web app, because there is no option. On the IOS app we can click the 'update ticket' icon and update it easily. On the web app it gives a red circle icon if you try to add anything that was not originally on the ticket. This causes us to either make an all-new ticket in a hurry, or look for the preexisting ticket and add the item, which takes a lot more time.

**Comment by Uzair-RepairDesk** [comment]
Hey @RepairPros 
Thank you for your post. The behavior of our iPad POS Register is different than a web app. 
However, I have marked your request under enhancements so we can check the feasibility to add it in our future roadmap. Thanks.
