### ISSUE TITLE
My employee cannot creat purchase order

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1182]
My employee cannot creat purchase order from low stock report just,
Although another employee in same role permission can creat it ,why?
I told Mr, Danish about this issue aweek ago.
![43B793B5-654F-44FE-B2C2-8165BFDD25C6](https://user-images.githubusercontent.com/44485797/85213928-71300100-b36d-11ea-87bb-0d315bda3aa1.png)

**Comment by MuhammadAdnan32** [comment]
Hey @hitman1986 , 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1403

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by hitman1986** [comment]
It fixed , thank you.
