### ISSUE TITLE
Tickets who disapper from my platform

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1195]
Hi guys, this week I found a new bug on repairdesk. Actually I didn't find an ticket. I searching on logs, I see the the people who comments on this but If I want to search on platform it didn't find, has gone.

![ggg](https://user-images.githubusercontent.com/65545272/85716666-61117c00-b6f5-11ea-9c9c-97628b97207a.png)
![fsafa](https://user-images.githubusercontent.com/65545272/85716797-7c7c8700-b6f5-11ea-949d-543a1cc935ca.png)

**Comment by usmanalikhan93** [comment]
Hi @adigsm07 

I hope you are doing well. We have recovered this ticket 13445. Please verify at your end and do let us know if you have any question. 

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @adigsm07 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Usman Ali

**Comment by adigsm07** [comment]
Hi Usman! Yes, the ticket is now available. Can you tell me if I make something wrong? What happened exactly with this ticket?

**Comment by usmanalikhan93** [comment]
Hi @adigsm07 

Can't say exactly but may be it didn't save right or may be a glitch. However just do notice if you face the same issue again and just do let me know the steps that what did you update or did to ticket.
