### ISSUE TITLE
Tickets are disappearing! 

### ISSUE THREAD

**Issue by marianabut** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1197]
Hi guys, this bug is back again.
https://www.youtube.com/watch?v=lpKREo72Szk&feature=youtu.be

**Comment by usmanalikhan93** [comment]
Hi @marianabut 

I hope you are doing well. We have recovered this ticket 13489. Please verify at your end and do let us know if you have any question. 

Thanks
Usman Ali

**Comment by marianabut** [comment]
Ok, I confirm, is recovered. Thank you!
