### ISSUE TITLE
Improvement in the customised field - e.g. search option

### ISSUE THREAD

**Issue by orvarb** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1200]
Our workshop handles repairs for walk-in customers as well as wholesale customers (for example when a customer purchases a phone from his / her phone company and the phone needs repair, the customer brings the phone to his / her phone company. The phone company then brings the phone to our workshop). Repairs that come through wholesale customers have a specific ticket number from THEIR system and when we create the repair in OUR system, it gets a new ticket number / ticketID from our system. We've created the custom field "Wholesale ticketID" where we input the ticketID which the wholesale customer has in their system. The problem is, we can't search the custom field for "Wholesale ticketID" but **we need** to be able to search after their ticketID because we get a lot of repairs from wholesale customers and they never know our ticketID so when they ask us about the progress of a certain repair, they ask about the number from their system.

Please contact Örvar for progress update (orvar@mii.is).

**Comment by Uzair-RepairDesk** [comment]
Hi @orvarb 
Hope you are doing well 

We have already implemented the functionality where you can search for any customer details using the custom fields data which has been added to the system. Please see if it fulfills your request. Otherwise we will be happy to assist you further on it. 

Regards,

**Comment by orvarb** [comment]
Hi @Uzair-RepairDesk 

Thank you, hope you are also doing well.

I've looked at the implemented functionality and there looks like my ticket was mistaken, at least it does not meet my request unfortunately. I've spoken to your customer service and he said that the field which was added is for Manage customer group but the data we are inserting and trying to pull is from the tickets so I was asked to comment here with a better details about our functionality:

Like I said above we are doing repairs for other companies and those other companies have their own ticketing system. For that reason we created a Custom field and named it "Viðgerðarnúmer söluaðila" (translates to "Ticket number from wholesale customer) where we will insert the ticket number from the wholesale customer when we are creating the ticket in our system. When we've created ticket in our system for wholesale customer, let's say it has the ticket number T-161, it has "Custom Fields" and below that it has for example "Viðgerðarnúmer söluaðila: 115157". We need to be able to search this number (in this case the number 115157) and the search should return the ticket number T-161. 

If there is something unclear feel free to reach out anytime.

**Comment by jphansendk** [comment]
We really need this feature as well.. @Uzair-RepairDesk Any news? :-)

**Comment by Uzair-RepairDesk** [comment]
Hi @orvarb @jphansendk 
We have already noted it down to add it to the roadmap. We will update you once we plan to add it to the system. Thanks for helping us make this a platform you'll depend on and we hope to support your business for many years to come.

**Comment by Uzair-RepairDesk** [comment]
Hey @orvarb  
Hope you are doing well. we have added an option to search tickets using repair custom fields, now you can search specific ticket based on the custom field. you need to go to the manage ticket page and then select repair custom fields from search criteria.
![FIXAPHONERepairDesk-Ticket](https://user-images.githubusercontent.com/22955861/100876419-2fcd8100-34c9-11eb-9289-9ea6c3099169.png)
How this helps.

Regards.
