### ISSUE TITLE
ticket status

### ISSUE THREAD

**Issue by DOM260096** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1203]
hi having used this software for about 1 months fully we have noticed ticket status changing them selves, especially to repaired and collected or cancelled, we are a small shop so its easy to ask if anybody changed the status we notice quite a lot. I wonder if anybody else sees this issue.?

**Comment by usmanalikhan93** [comment]
Hi @DOM260096 

I hope you are doing well. I have asked Danish Hassan who is our customer support guy to contact you and note down your queries.

**Comment by usmanalikhan93** [comment]
Hello @DOM260096 

I hope you are doing well. I just wanted to know that are you still facing this issue or not ? Just let me know so we can connect offline and see what's the actual issue and we can try to resolve this issue for you. 

Regards, 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @DOM260096 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
