### ISSUE TITLE
print node and reconcillation reports

### ISSUE THREAD

**Issue by DOM260096** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1204]
hi i have two till drawers and two thermal printers that all work independently until we close the till sessionsat the endof the day and print the reconciliation report automatically with print node. both printers print and both drawers eject, this happens on either till.

**Comment by usmanalikhan93** [comment]
Hi @DOM260096 

I hope you are doing well. I have asked Danish Hassan who is our customer support guy to contact you and note down your queries.

**Comment by usmanalikhan93** [comment]
Hello @DOM260096 

I hope you are doing well. I just wanted to know that are you still facing this issue or not ? Just let me know so we can connect offline and see what's the actual issue and we can try to resolve this issue for you. 

Regards, 
Usman Ali

**Comment by DOM260096** [comment]
Yes we are mate

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Repairdesk-QA** [comment]
Hey @DOM260096,
I hope you are doing well. Sorry for the delay but I was pulled away and caught up with work. Can you please connect with one of our support agent on live chat so that he can look into the issue you are facing in detail? Thanks!
