### ISSUE TITLE
Ticket Status 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1207]
Hello, we're having issues with the ticket status on Unlocking service. They won't marked them self as repaired and collected once we have received the payment. 

Please check tickets T-1063 and T-1009. We had other tickets with the same issue but they were marked manually as repaired and collected. Ive left this two tickets unchanged so that you can see the issue.

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards
M Adnan

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
Could you please share your updated Repiardesk account credentials in PM at adnan@repairdesk.co?
Thanks & Regards,
M Adnan

**Comment by usmanalikhan93** [comment]
Hi again @Omar1892 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
