### ISSUE TITLE
Warranty Claims and No Warranty 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1212]
Hello, 

we've being having the following issues. On the following ticket it shows that the costumer doesn't have any warranty altho we offer a Limited Life Time Warranty and on the second ticket it won't give us the option to due a warranty claim. This happens randomly.

Ticket with not warranty: T937

Ticket No option for a warranty claim: T-1028
![Screen Shot 2020-07-13 at 3 23 27 PM](https://user-images.githubusercontent.com/47898011/87359996-eda5a200-c51d-11ea-8b63-147e657db617.png)
![Screen Shot 2020-07-13 at 3 26 25 PM](https://user-images.githubusercontent.com/47898011/87359998-eed6cf00-c51d-11ea-9d79-22213819c4b8.png)

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Uzair-RepairDesk** [comment]
What's the update on this @MuhammadAdnan32 @usmanalikhan93 ?

**Comment by MuhammadAdnan32** [comment]
@Uzair-RepairDesk I am waiting for customer credentials and today I have received. I will update this task soon.

**Comment by Omar1892** [comment]
@MuhammadAdnan32 Hello, I have already sent them. Please let me know if you got them.

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
I have received and thank you for sharing and I m looking into this and I'll circle back to you soon.

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1541

**Comment by MuhammadAdnan32** [comment]
Hello @Omar1892 ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any questions.
Thanks!
Regards,
M Adnan

**Comment by Omar1892** [comment]
@MuhammadAdnan32 thank you.
