### ISSUE TITLE
Need Easy Way to Add New Item in Inventory

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1219]
It's taking lot of time to add new product everyday.

In our mobile phone repair industry, we always have the same products, Just model number get changed. For Example ;

OtterBox
Murcury Flip Case
Lifeproofe Case
Screen Assembly
Back Camera
Frotn Camera ,,,,, and so on.

Currtnely, to add new product we have to type all this information.

Why not we just pre-add all these products ( mentioned above )
and we just selected option in drop down menu. For example, 

1. we choose " Screen Assembly " in first drop down menu
2. we choose " iPhone 7 " (model) in second drop down menu
3. we choose " White " (color) in third drop down menu 
and click save.
It creates a new product name " Screen Assembly for iPhone 7 Plus White "  ( or whatever we pre-configure in that module )

what do you guys think about it?

because every day we have a new model, and we have the same brand accessories and parts.

all we have to do is just add new model, and all other options are pre-configures.

Let me know if its something you can consider working on.

**Comment by Uzair-RepairDesk** [comment]
Hi @BharatPRC 
Did you try our new one-page inventory UI. Does it help you to solve the above concerns? 

Please feel free to share your feedback. Thanks.
