### ISSUE TITLE
Customer Invoice and Ticket Data is GONE ?

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1221]

**Comment by BharatPRC** [comment]
http://sc.com.ly/show/UNxeEazwGpD6ok4PVOhJ1F8yTsfSmcgd

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1531

**Comment by MuhammadAdnan32** [comment]
Hi @BharatPRC ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any questions.
Thanks!
Regards,
M Adnan

**Comment by BharatPRC** [comment]
Now it showing error 500 
See video, please.
http://sc.com.ly/show/kz3Ro4fb1tDqLVl2vdJ6YBs9COicUZEQ

**Comment by MuhammadAdnan32** [comment]
Hi @BharatPRC ,
It's working fine on my test account. Can you please share your Rpairdesk account credentials in PM on adnan@repairdesk.co?
Thanks & Regards,
M Adnan

**Comment by BharatPRC** [comment]
> Hi @BharatPRC ,
> It's working fine on my test account. Can you please share your Rpairdesk account credentials in PM on [adnan@repairdesk.co](mailto:adnan@repairdesk.co)?
> Thanks & Regards,
> M Adnan

Email Sent.

**Comment by MuhammadAdnan32** [comment]
Hi @BharatPRC,
Received and thank you for sharing.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1534

**Comment by MuhammadAdnan32** [comment]
Hi @BharatPRC ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.
Thanks!
Regards,
M Adnan

**Comment by BharatPRC** [comment]
Thanks . Seems OK Now :-)
