### ISSUE TITLE
option to print bulk barcode labels

### ISSUE THREAD

**Issue by ciprianro** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1224]
we cant spend all day to print one by one barcode labels. please resolve this. thank you

**Comment by Uzair-RepairDesk** [comment]
Hi @ciprianro 
Is it about inventory labels? We have already the option to select the items and print the barcode labels in bulk. 
**Please check the screenshot attached.** 
<img width="1272" alt="Screen Shot 2020-07-20 at 10 09 08 AM" src="https://user-images.githubusercontent.com/22955861/87901778-52f31900-ca71-11ea-9949-b98450aa71de.png">

Can you please specify where you exactly print the barcode labels?

**Comment by ciprianro** [comment]
Hi.
When making new GRN. There must be the option.

lun., 20 iul. 2020, 08:11 Muhammad Uzair Shah <notifications@github.com> a
scris:

**Comment by Uzair-RepairDesk** [comment]
@ciprianro 
When you open the GRN, there is also option to select all the received items from GRN to print the barcodes at once. Please check the screenshot attached. 

![uzairshahRepairDesk_View_Grn](https://user-images.githubusercontent.com/22955861/87911472-2517cf80-ca85-11ea-8d6a-82f2b26c2686.png)

**Comment by ciprianro** [comment]
Wont work.
There will print just 1 laber/ item.
Please check

lun., 20 iul. 2020, 10:33 Muhammad Uzair Shah <notifications@github.com> a
scris:

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you please verify this?

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1540

**Comment by usmanalikhan93** [comment]
Hi @ciprianro 

I hope you are doing well. We have added the functionality of print bulk quantity label in GRN. Just select the items, and press print barcode, it will work according to quantity. Please verify at your end and do let us know if you have any question. 

Regards,
Usman Ali

**Comment by ciprianro** [comment]
yes it's working. thank you

În mar., 21 iul. 2020 la 14:07, Usman Ali Khan <notifications@github.com> a
scris:
