### ISSUE TITLE
Sub-Categories for the Accessories and Parts system

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1233]
With the category system, can I suggest maybe having sub-categories too so e.g. main category: Computer Parts | Sub-Category: Power Supplies etc.

**Comment by Uzair-RepairDesk** [comment]
Hi @TechTraders 
Thank you for the suggestion. We have a plan to add the "Sub Categories" module in RepairDesk. I have marked it under enhancements of the inventory module. 
I will update you on this thread once we start working on it. Thanks.

**Comment by TechTraders** [comment]
Thanks Uzair I look forward to seeing the update come out

Thanks,
Nat
Technology Traders

**Comment by MyTechnopolis** [comment]
Great! To add on this...

It would be great to see departements, categories and sub-categories for store like us who are not just in repairs.

Example:

Mobile (Department 1)
   - Cases
        - Otterbox
        - MyBat
        - Puregear
    - Cellphones
        - Bell
        - Rogers
        - Refurbished
Audio (Departement 2)
    - Speakers
         - Bluetooth
         - Others
Etc...

**Comment by Uzair-RepairDesk** [comment]
Hi @TechTraders 
I am pleased to inform you that we have introduced the "Subcategories" module in RepairDesk. You can not create multiple subcategories under a specific category. 
You can go to Store Settings > Module Configurations > Manage Product Categories to create and manage subcategories. 
Please check the screenshot attached. 

![image](https://user-images.githubusercontent.com/22955861/103064161-2a99b880-45d5-11eb-9905-ecd24e452490.png)

Please let me know if you have any questions.
