### ISSUE TITLE
Ability to search customer by their phone or mobile 

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1234]
It should allow you to search a repair ticket, customer or an invoice by customer phone or a mobile number.

If a customer forgets to add - or +1 they should still be able to search a profile

![St-LouisRepairDesk-Ticket](https://user-images.githubusercontent.com/21986026/88707454-b1805d00-d12b-11ea-91b4-eaa4dfe6a7c2.png)

**Comment by Repair-Desk** [comment]
It would be good to search an inventory item by SKU, UPC or item name

**Comment by MyTechnopolis** [comment]
I agree with this post. It's a great idea. We've seen other system with a search bar to search anything and it works amazingly without the need to select the category in what to search in.

It's surprising we can't search the inventory from there. It a duly needed addition.

**Comment by Uzair-RepairDesk** [comment]
Hey @Repair-Desk 
Hope you are doing well, we have update the search that allows you to search for a repair ticket, customer, or an invoice by customer phone or a mobile number.
we have also added the options for the inventory item. user can search them by  SKU, UPC, Serial, or item name.
![image](https://user-images.githubusercontent.com/22955861/90608309-d85a1c80-e21b-11ea-9fad-21884711cc48.png)
