### ISSUE TITLE
Scanning stock counts - Cybertek

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1238]
When scanning stock counts, there is a delay in scanning, I will scan 5 items and only 2 will show up. I am having to scan, count one-mississippi, two-mississippi, and then scan the next item. This takes too long, especially if the item is not in the system and there is no way of telling if it is or not.
Can we have a chime when an item scans succesfully and an error alert when something is scanned that it not in the system?
And also a count at the top of the page telling how many items have been scanned so I can count in my head 50 items and the stock count can count 49 and then I can figure out which 1 I missed a lot easier.
Could we also get a list of the barcodes that are scanned but not in the system so I can find the barcode and add it in the system for all future stock counts.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you check the first part that is about the delay in scanning the items?

**Comment by TechTraders** [comment]
I 2nd this! :)

**Comment by usmanalikhan93** [comment]
Hi @Cybertekww 

I hope you are doing well. I have checked your concern related to scanning but it's working fine. And if item is not present in the system, it does prompts a message. Please check video and do let me know if you have any question. 

Video Link: https://drive.google.com/file/d/1jWhxHkCotjkZ1RgQ1xPPxLtvIES3zN36/view

**Comment by Cybertekww** [comment]
In the video you scan items and the error comes up, at the top of the page where it is unseen unless you scroll up to the top. this means I need to scan items into the computer and stare at the computer screen to make sure it goes in to the system instead of being able to walk around the store scanning items. If there is an audible charm that alerts me to an item being scanned in that would be very helpful

**Comment by usmanalikhan93** [comment]
Hi @Cybertekww 

Sure I will discuss this with development team and will try to implement something like this as you mentioned. I will update you once I get more info on this. 

Regards, 
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1663

**Comment by usmanalikhan93** [comment]
Hello @Cybertekww 

I hope you are doing well. We have improved your below point which you have highlighted.

**Comment by Repairdesk-QA** [comment]
Hello @Cybertekww,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
