### ISSUE TITLE
Customer Comments on Leads Management

### ISSUE THREAD

**Issue by yourrepairdepot** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1239]
![Customer Comments Field Repair Desk](https://user-images.githubusercontent.com/69055067/89067907-0a671580-d325-11ea-8900-43969d73392a.JPG)
When entering a customer comment in the customer comment on Leads Management field doesn't save.

**Comment by usmanalikhan93** [comment]
Hi @yourrepairdepot 

Sorry for the delay response. I have made a video in which I have explained how you add customer comments in manage leads section. Please check and do let me know if you have any questions. 
Video link: https://drive.google.com/file/d/1l7pyHfd3_X56sso-tGW3a0dgefXH19D6/view

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @yourrepairdepot - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
