### ISSUE TITLE
Purchase Order PO Toggle " Add tax on Cost Price " doesn't work

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1242]
![Screenshot 08-03-2020 11 52 32](https://user-images.githubusercontent.com/34261339/89138738-da677e80-d57f-11ea-8e5b-ea25053336be.jpg)

Either if this option ticked or not ticked we still have to keep the calculator with us to add cost price and tax.

can you guys please fix this asap.

**Comment by MuhammadAdnan32** [comment]
Hey @BharatPRC , 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by BharatPRC** [comment]
This issue and #1228  are going side by side. 
so please consider both at the same time when you work on it.  thanks

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-2717

**Comment by BharatPRC** [comment]
I think there is a confusion between two triggers with the same/similar functionality.
One is in " Store General Setting "
and
One is in " Purchase Order "

I have tried to explain the issue in the following video. Please watch it for clear understanding. 

http://sc.com.ly/show/upSrFHAQtVg85J094lzECbheBY6Wcf3y
