### ISSUE TITLE
Print Node is not receiving any command - Not Printing

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1243]
Hi Print node is not working.

RD shows msg that printing job is sent to print node, but nothing gets to print out.

I have check Integration settings, that seems ok.

I have logged in to Print Node account to see any pending job, and I found out that its not even receiving the command from RD.
No job in quoue .

![Screenshot 08-03-2020 12 29 28](https://user-images.githubusercontent.com/34261339/89140436-fd486180-d584-11ea-9f8a-a03ddb44b5c1.jpg)

**Comment by Uzair-RepairDesk** [comment]
We have fixed the issue @BharatPRC 
Can you please check at your end?

**Comment by BharatPRC** [comment]
Thank you for the quick fix. 
It also has fixed the other issue I reported #1241 
Great.
