### ISSUE TITLE
Tickets are not showing Added Parts items

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1245]
When we add items in tickets, it doesn't show it.
Outside its visible.
plz, check the video to see what exactly is happening.

http://sc.com.ly/show/5BfI6qxFzXC9yDVpiudtTHbL7NaP1m8k

**Comment by usmanalikhan93** [comment]
Hi @BharatPRC 

I hope you are doing well. It's fixed now. Can you please check now by creating a new ticket with ticket items? For the old tickets, please share the ticket id's and credentials with Danish and then we will update it from Database. 

Thanks
Usman Ali

**Comment by BharatPRC** [comment]
Thanks! It's all good and working now.
I will fix old tickets by myself. Cheers !!!
