### ISSUE TITLE
Ticket assigment not clickable when ticket is open

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1249]
Please make the ticket assigned section clickable when you are viewing the ticket,
![image](https://user-images.githubusercontent.com/68912093/89596100-b2d32780-d899-11ea-9b1c-9d014b9e7e7a.png)

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-2721

**Comment by usmanalikhan93** [comment]
Hi @TechTraders 

I hope you are doing well. We have now changed the behavior on your request on view ticket page that you can change the assignee in view page. Please check at your end and do let me know if you have any question. 

Thanks,
Usman Ali
