### ISSUE TITLE
Unable to select supplier when adding part to ticket

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1254]
Unable to add a part to a ticket that has uses the Suppler/Vendor SKU

![Screen Shot 2020-08-10 at 5 50 08 pm](https://user-images.githubusercontent.com/1414304/89761544-f647c300-db31-11ea-9450-eef13ee7a2eb.png)
![Screen Shot 2020-08-10 at 5 49 56 pm](https://user-images.githubusercontent.com/1414304/89761550-f942b380-db31-11ea-96b3-573fb56abd4c.png)

**Comment by usmanalikhan93** [comment]
Hey @afrahm 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by afrahm** [comment]
Here is a short video on the problem - https://www.screencast.com/t/fVPLjbRle1A

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1612

**Comment by usmanalikhan93** [comment]
Hi @afrahm 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
