### ISSUE TITLE
Low Stock Report Not able to add to exsisting PO

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1256]
Please fix this!! half the time when I try to add items to an existing PO through the low stock report it does not give me the option to add to the existing PO??? 
![Captu123re](https://user-images.githubusercontent.com/68912093/89847342-25f4da80-dbc7-11ea-9195-f32b9048ac91.PNG)
![12312 3](https://user-images.githubusercontent.com/68912093/89847350-29886180-dbc7-11ea-8343-a6ef3dac754d.PNG)

**Comment by usmanalikhan93** [comment]
Hey @TechTraders 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @TechTraders 

I have reviewed your issue bu I am unable to replicate this on my test account. Can you please tell me that are you facing this issue every time when perform these steps or this is random ?

**Comment by TechTraders** [comment]
it does not always but most of the time It does it...

**Comment by usmanalikhan93** [comment]
Hi @TechTraders 

Thanks for the information. I will try on my end to reproduce this issue. Meanwhile if you face this issue do let me or Danish know so we can check this in detail. 

Regards, 
Usman Ali

**Comment by TechTraders** [comment]
Seems to work fine now
