### ISSUE TITLE
Confirm if you want to delete pop up

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1259]
Hi There, Can you please add a confirmation pop up when you go to delete a Purchase order. I have accidentally deleted Purchase Orders multiple times now and it would be good if that pop came up to give me a chance to cancel the deletion.

Thanks

**Comment by Uzair-RepairDesk** [comment]
Hello @TechTraders,
Thank you for your suggestion. It should certainly give an alert popup if you go to delete the purchase order. I am adding it under enhancements so we can add it to our current sprint. Thanks.

**Comment by TechTraders** [comment]
It does not pop up when you select it through this list
![image](https://user-images.githubusercontent.com/68912093/90141326-5a7eb700-ddbe-11ea-874f-b31a7fdc29a2.png)

**Comment by Uzair-RepairDesk** [comment]
@TechTraders 
We have local holiday tomorrow

@usmanalikhan93 
Please check this on Monday

**Comment by TechTraders** [comment]
no worries have a good holiday 😄

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1638

**Comment by usmanalikhan93** [comment]
Hi @TechTraders 

I hope you are doing well. We have added a confirmation pop up when you delete a PO in view mode. Kindly verify at your end and do let me know if you have any question. 
![image](https://user-images.githubusercontent.com/39614480/90605802-4ac8fd80-e218-11ea-90d5-da5138814a3b.png)


Regards, 
Usman Ali
