### ISSUE TITLE
Employee Productivity Report - Cybertek

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1263]
for the Employee Productivity Report can I see all employees from all stores at once? instead of selecting one store and then the other to see who is being the best sales person across all the stores.

**Comment by Uzair-RepairDesk** [comment]
Thank you for your idea. We are introducing a KPI dashboard that will allow you to track store & employee performance so you can make better decisions.
I will update you on this soon. 
@Cybertekww

**Comment by Uzair-RepairDesk** [comment]
Hey, @Cybertekww  Hope you are doing well, here is the link for the KPI dashboard knowledge base.
Now in RepairDesk, you can view the Employee and Store KPIs through the Admin Dashboard. Simply go to the Admin Dashboard, where you will see two different tabs. Click on the Store KPIs and you will be able to view the KPI Dashboard. With the help of this dashboard, you will be able to make decisions and understand your business performance.

Hope this helps.
Regards,
