### ISSUE TITLE
Editing Line Items on PO

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1265]
With editing a PO if I delete a line item it will reset all of the quantities I just edited beforehand.

E.g. if I am going through my PO list and editing quantities on items and then I decided to remove an item from the list. unless I save and then re-open the edit window I will lose all of my progress on editing the quantities. can this be fixed please. it is just really time-consuming and frustrating that I cannot make the edits I need to without jumping through hoops to make sure I don't lose progress or stuff something up...

**Comment by usmanalikhan93** [comment]
Hi @TechTraders 

I have checked your concern but unfortunately, I am unable to reproduce your issue on my test account. Would be great if you can share a video of this issue so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Regards,
Usman Ali

**Comment by TechTraders** [comment]
Here is a video link for this issue 
https://drive.google.com/file/d/1_SeQ5_vsxB38QBjpomT1S045oWuxHQHz/view

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA can you please check this?

**Comment by Repairdesk-QA** [comment]
Hello @TechTraders,
Hope you are doing well.

Thanks for your patience. Your reported issue has been fixed and is live.
Kindly verify at your end and do let us know if you still have any questions.
Waiting for your feedback!

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @TechTraders ,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain
