### ISSUE TITLE
Filtering Options in Inventory Summary Report

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1266]
Hi Guys, Are we able to add the "Supplier" search Criteria in the inventory summary report?

**Comment by Uzair-RepairDesk** [comment]
Hey @TechTraders 
Hope you are doing well, we have added "Supplier" search Criteria in the inventory summary report. now you can filter your results based on supplier.
![FIXAPHONE-Inventory-Summary-Report123](https://user-images.githubusercontent.com/22955861/91526209-89e40680-e91c-11ea-8fb8-96ae15e35dd8.png)
