### ISSUE TITLE
Discount Issues - Cybertek

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1267]
When we make customer codes to receive discounts the discounts sometimes dont apply and when we add the 10% the math is all wrong. The discounts dont show on the invoice either so that the customer knows they are getting a discount as well.

**Comment by Cybertekww** [comment]
![badmath](https://user-images.githubusercontent.com/61297564/90201581-a3665800-de1e-11ea-90de-ce579eb7c63f.PNG)

**Comment by usmanalikhan93** [comment]
Hey @Cybertekww 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hello @Cybertekww 

I hope you are doing well. I believe Danish has guided you on this task. Do let me know if you have any questions.

**Comment by usmanalikhan93** [comment]
Hi again @Cybertekww  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards, 
Usman Ali

**Comment by Cybertekww** [comment]
The discounts were working fine and then over the weekend the POS system was a mess. Payments for some items were showing up on other invoices. THe guys were calling me to let me know but I had no idea what they were saying as I had not seen the issue before but it seemed like the system would freeze and when refreshed accept the payment but then on the next invoice it was added on to the new invoice?

**Comment by Cybertekww** [comment]
The same with a refund. the purchase amount was wrong and the figures were a bit odd

**Comment by Cybertekww** [comment]
![20200822_124122](https://user-images.githubusercontent.com/61297564/91007659-de873900-e61f-11ea-957a-0ea32cdb21f1.jpg)

**Comment by Cybertekww** [comment]
![20200822_123302](https://user-images.githubusercontent.com/61297564/91007676-ea72fb00-e61f-11ea-8e95-f6f58bad91b5.jpg)

**Comment by usmanalikhan93** [comment]
Hello @Cybertekww 

I hope you are doing well. Can you please reach out to Danish and explain this issue via screenshare ?
