### ISSUE TITLE
Uniqness in SKU not working when Using Custom SKU settings

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1268]
I am using SKU Generation Custom Setting as in picture below :
![Screenshot 08-14-2020 16 39 00](https://user-images.githubusercontent.com/34261339/90221086-d7f10880-de4c-11ea-8cfc-429d1af297c7.jpg)

I am re-organising my inventory by re-assigning SKU's starting from the letter " P "
When I delete my old SKU and save the product, it doesn't regenerate new SKU automatically from P series. 
and when I add SKU manually, it is actually allowing to add the same SKU which is already available; which is creating confusion. 
![Screenshot 08-14-2020 16 44 53](https://user-images.githubusercontent.com/34261339/90221401-8137fe80-de4d-11ea-8be4-2417d358c896.jpg)

Can you please have a look.

**Comment by BharatPRC** [comment]
Please try to look at it today.

System is generating SKU which is already available in system

**Comment by MuhammadAdnan32** [comment]
Hey @BharatPRC, 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanaks & Regards,

**Comment by BharatPRC** [comment]
any update ?

**Comment by MuhammadAdnan32** [comment]
Hello @BharatPRC ,
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
M Adnan

**Comment by BharatPRC** [comment]
I thought so. Because every time I get a late reply from you, it means you couldn't find the issue. :-)
I will try to post all issues with the video next time. 


Anyways!

Here is the video.:

http://sc.com.ly/show/gLT1ROpFyNXErt8oMHicnGhKfaC90I2Zhttp://sc.com.ly/show/gLT1ROpFyNXErt8oMHicnGhKfaC90I2Z

**Comment by MuhammadAdnan32** [comment]
Hey @BharatPRC ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1647

**Comment by MuhammadAdnan32** [comment]
Hi @BharatPRC ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any questions.
Thanks & Regards,
M Adnan
