### ISSUE TITLE
Barcode Scan error while creating Repair Tickets 

### ISSUE THREAD

**Issue by R2Repair** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1269]
Hi, 

While receiving parts for Repairs in POS, as soon as we scan the Serial Number with a barcode scanner, the system automatically saves the part without letting us entering the rest of the fields like Repair Task status, Repair Task type, Physical location, etc. 

Please find the video attached for your reference. 

https://drive.google.com/file/d/12yWVSB5Tzuhf_wvbUkXKG6_fRwmHhv6M/view?usp=sharing

**Comment by Uzair-RepairDesk** [comment]
Hi @R2Repair 
Can you share the file with open access?

**Comment by R2Repair** [comment]
Hi, 

I have removed the restrictions from the file. Please use the link below:

https://drive.google.com/file/d/12yWVSB5Tzuhf_wvbUkXKG6_fRwmHhv6M/view?usp=sharing

**Comment by usmanalikhan93** [comment]
Hi @R2Repair 

I hope you are doing well. I have watched your video and just wanted to let you know that, that field does not support scan. It is only for manual entry. Hope it helps. Do let me know if you have any questions. 

Regards, 
Usman Ali

**Comment by R2Repair** [comment]
Hi Usman,

Thank you for your email,

This functionality was actually working properly until last month and it
was discussed in the earlier meetings with RepairDesk team as well that
this function was required by our team.

Even right now it is able to scan the part but instead of just scanning, it
directly saves the device and moves to the next one.

Thank you,

Rishab Bhalla

R2 Repair


[image: r2logo]


O:  905-901-3108 ext 50

E:   rishab@r2gaming.com

*Technical or General Inquiries: **r2service@r2gaming.com*
<r2service@r2gaming.com>

*Technical Support contact number: 905-901-3108 Ext 15 (or Ext 24 after
3:30 pm and at weekends)*

*Repair Services and parts quotes: **R2repair@r2gaming.com*
<R2repair@r2gaming.com>

*www.R2Gaming.com* <http://www.r2gaming.com/>

**Comment by usmanalikhan93** [comment]
Hello @R2Repair 

I have just checked again your issue and yes in case of Serial it confirms the ticket, which is wrong. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Regards, 
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1662

**Comment by usmanalikhan93** [comment]
Hello @R2Repair 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by R2Repair** [comment]
Thank you Usman!

We have checked this and this is working fine now! Really appreciate your help.

Best Regards, 
Rishab Bhalla
