### ISSUE TITLE
Search Ticket Listing by Device Location

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1273]
Need to be able to search ticket listing by device location so we can see by search what devices are in any given location.

**Comment by Uzair-RepairDesk** [comment]
Hey @afrahm  
Hope you are doing well, we have made this improvement live , now you will be able to search ticket by device location.
![image](https://user-images.githubusercontent.com/22955861/91291161-191edc00-e7ae-11ea-84af-e6dd37bf5b07.png)
