### ISSUE TITLE
Emails going to Junk - Cybertek

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1275]
We keep emailing customers their invoices or suppliers a PO but they arent receiving them in their inbox as it goes straight to their junk mail. Can we fix this?

**Comment by usmanalikhan93** [comment]
Hi again @Cybertekww  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards, 
Usman Ali

**Comment by Cybertekww** [comment]
Sorry I didnt see this update until now. It works fine for some accounts but others like office 365 or hotmail accounts it goes to their junk mail.

**Comment by usmanalikhan93** [comment]
Hi @Cybertekww 

I hope you are doing well. This needs to be fix by them self by click on looks safe when they receive email in spam. Hope it helps. 

Regards, 
Usman Ali

**Comment by Cybertekww** [comment]
This is still happening. We are getting emails replied to from the customer and automatic emails generated from repair desk going straight to peoples junk mail. This cant happen as we are missing out important updates and the customers are missing out on their invoices and updates.
This is a photo of the emails in our junk mail at the moment. Nearly all of them are repair desk.
![20200902_212958](https://user-images.githubusercontent.com/61297564/91976362-29adf400-ed64-11ea-98a7-87f08aea4738.jpg)
