### ISSUE TITLE
Costumer Facing Display

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1278]
Hello, the costumer facing display hasn't being working correctly for the past few months. When ever we select an option to have a  costumer checked in or to have them sign for our terms and conditions the display will not reload. It goes to a blank white page we have to manually reload it our self every time it has to be used. 

The video was sent to Costumer

fahadimran85@gmail.com

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 @afrahm ,
I hope you doing well. Could you guys please share your IOS version of IPAD, Browser name, and Browser version which you are using CFD?
Thanks & Regards,
M Adnan

**Comment by Omar1892** [comment]
Yes, its the iPad air 2 13.1.6 - browser would be Google Chrome, browser should be the latest I see no new updates for the app it self.

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. I have checked your reported issue on your account and also attached a video
https://drive.google.com/file/d/1du6bGdiaDU59GTq8wkRpvMauNlxrz4DY/view?usp=sharing
kindly look into this and also kindly make sure your iPad and chrome browser version is up to date.
Do let me know if you have any questions?
Thanks & Regards,
M Adnan

**Comment by usmanalikhan93** [comment]
Hi again @Omar1892  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by Omar1892** [comment]
Hello, the issue still there. Ive tried it with multiple other tablets and it continues to due the same thing. And with different computers as well using the browser chrome on both the tablet and computer.
