### ISSUE TITLE
date entry box on new expense form

### ISSUE THREAD

**Issue by DOM260096** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1279]
hi please add a date entry box on the expenses form so my staff can add previous expences for differnt dates. this issue must be seen by other people , thank you.

**Comment by Uzair-RepairDesk** [comment]
Hi @DOM260096 

Thank you for your post. Currently, our expense is linked up with our "Start / End Shift" i.e. "Register Shift" functionality. You can log expense entry during a specific shift only. 
This is the reason, we cannot allow changing date when you log the expense. However, I still discuss with a technical team if we can allow using the expense without shift log and if we can also add an option to update the date. 

I have logged it under enhancements. 

Regards,
Uzair

**Comment by Uzair-RepairDesk** [comment]
Hey @DOM260096 
Hope you are doing well, we have updated the expanse module where you can add expanse entry without using shift functionality, moreover, you can also add expanse in back dates.

Note: if the shift is started then you can not add expanse in back dates as it's associated with Register/ shift.
Hope this helps, fell free to share your feedback.
Regards,
