### ISSUE TITLE
Search Ticket Listing by Repair Category

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1280]
Be able to filter the ticket listing based on Repair category. So we can look at all PC repairs, or all tablet repairs etc.

**Comment by Uzair-RepairDesk** [comment]
Hey @afrahm 
Hope you are doing well, the above improvement is now live and you can now search for tickets by repair category from manage ticket listing. 
![image](https://user-images.githubusercontent.com/22955861/91520887-e3920400-e90f-11ea-9392-88b373bab082.png)
