### ISSUE TITLE
Importing Customers

### ISSUE THREAD

**Issue by canofwhoop** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1281]
I am trying to import about 3000 customers into Repair Desk, but I have more categories than you have available. For example, I want to import ticket information with the customer so I can access it in the future. Some categories I would like to add are like Tech, Device Type, passcode, IMEi, and information on past purchases (made outside of RepairDesk). I see that I can add custom categories for future customers. But I would like the opportunity to customize the import. The options now are quite limited. I would like repair desk to be my one stop shop, but it wouldn't be possible without having accurate customer data from the past.

**Comment by Uzair-RepairDesk** [comment]
Hi @canofwhoop 
Hope you are doing well 

Thanks for sharing your concern. I have discussed it with our development team and currently, it's not possible for us to customize the import process as it will lead to several challenges. However, what we can do for you is we can manually import the customer information in your account. If possible then please do us a favor and create the required custom fields in your RepairDesk account. 
Also please email us the file with data that you want to import along with your account credentials at uzair@repairdesk.co or yusrazakir1995@gmail.com. 

We will be happy to assist 

Looking forward to figure it out for you.

**Comment by canofwhoop** [comment]
Ok, I will do that shortly.
