### ISSUE TITLE
Refunds (crashing)

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1287]
Hello, 

when we try to make a refund with the new set up you guys just added its crashing. 

We tried to due a warranty replacement by exchanging a faulty item with a new item and at the moment we try to due the refund the thing crashes

**Comment by usmanalikhan93** [comment]
Hey! @Omar1892 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Regards, 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hello @Omar1892 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by Omar1892** [comment]
Its working fine now. Thanks
