### ISSUE TITLE
Improved search functionality 

### ISSUE THREAD

**Issue by orvarb** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1290]
Hi!

After a discussion with your support team I was asked to create a ticket here on GitHub regarding improving the search functionality. 

The thing is, let's say we've created a ticket and the customer name is "Örvar Blær Guðmundsson". If I try to search "Örvar Bl", that is to say, I don't write the full name and stop somewhere in the middle of the name, the search query returns "No results found". If I search "Örvar" or "Örvar Blær", the query returns the ticket on this name. 

This can be a bit annoying, for example when our staff doesn't here customers full name and we have a large customers database so our staff tries to write as much as he / she heard but that search returns nothing unless he / she only writes customers first name and has to search manually from all search results.

**Comment by usmanalikhan93** [comment]
Hello @orvarb 

I hope you are doing well. We have improved the search now as you said above. Please verify at your end and do let us know if you have any question. 

Regards, 
Usman Ali

**Comment by orvarb** [comment]
Hi @usmanalikhan93 
Thank you for a fast work, I can confirm that the search function has been improved and is working properly. 
Thank you!
