### ISSUE TITLE
Customer name error 

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1291]
Hello,
This problem had already been mentioned and it had already been fixed. However, he's back. All EMAIL and TEXT with the "customer_name" tag displays the name of "David Fournier" instead of the customer's name. All the customers therefore tell us that there is an error in their name because his name is all David Fournier. See example of this email.
<img width="689" alt="david fournier" src="https://user-images.githubusercontent.com/40500094/92261880-3fc4cd00-eea8-11ea-830e-62846aa47942.png">

--

Bonjour,
Ce problème avait déjà été mentionné et il avait déjà été corrigé. Cependant, il est de retour. Tous les COURRIELS et TEXTOS avec le tag "customer_name" affiche le nom de "David Fournier" au lieu du nom du client. Tous les clients nous mentionne donc qu'il y a une erreur dans leur nom car il s'appel tous David Fournier. Voir exemple de ce courriel.

**Comment by usmanalikhan93** [comment]
Hello @JessicaSOS 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hello @JessicaSOS 

Jessica I have just checked and wanted to update you that please change Macro {RECIP_NAME} with {Customer_name} where you want to display customer name. {RECIP_NAME} displays admin name. Please change these. 
![image](https://user-images.githubusercontent.com/39614480/92355973-beb34300-f0fe-11ea-9e76-7da480b1ff23.png)

Do let me know if you find any confusion. 

Thanks,
Usman Ali

**Comment by JessicaSOS** [comment]
Hello,
its actually seems to be working well. I will contact you if there is anything but at the moment it seems to be fixed. Thank you for your observation and your speed.
