### ISSUE TITLE
Inventory items not marked as used 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1294]
Hello, 

Ive sent a video of the issue to fahadimran85@gmail.com

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1760

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. Your reported issue related to change status from the ticket view page has been fixed. Please verify at your end and do let us know if you have any question.
Thanks!

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. For second concern related automatically change ticket part status when we make an adjustment against the part added in the ticket. Kindly found the developer comment below.
Technically it's not possible in current behavior as we have no link of that line item in which stock is going to be adjust.

For example if stock is less than 0 and if we click on Order part => and then create GRN. we have a link from that part to PO and then to GRN so we can easily update the status of the state of that line item.

In this case, the system doesn’t know for which line item of ticket stock we are going to increase so it auto set the status from Pending to Used.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by Omar1892** [comment]
@MuhammadAdnan32 Hi, so unless we do it from the ticket it self we will not updated once we receive it on our regular P.O? We usually just create a P.O with out looking at the ticket that needs the parts since we buy in whole sale. Once the part arrives we create a GRN and I tough that once the GRN would go in the system it would update the stock with in the ticket as well. Before the system would have this functionality with out us having to due it manual.

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. Technically it's not possible in current behavior. If you want to update the ticket part status automatically then you have to create a purchase order by clicking on the "Part Order" link On the ticket view page under the "On hand" field then it will automatically update the ticket item status when GRN will be created against PO.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan
