### ISSUE TITLE
Repair Categories Admin Section 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1295]
Hello, 

Ive sent a video to fahadimran85@gmail.com

**Comment by Omar1892** [comment]
Along with the video I sent you, I also have issues were the wrong devices will appear on the wrong repair category and I can't  no longer remove the from the "Repair Categories" since as stated on the video last time I moved one of the device the Repair Category it messed up my inventory, trade in, repair buttons and who knows what else. 
![Screen Shot 2020-09-08 at 9 45 50 AM](https://user-images.githubusercontent.com/47898011/92505126-76585b80-f1b8-11ea-82b8-0ebd81105e35.png)
![Screen Shot 2020-09-08 at 9 44 08 AM](https://user-images.githubusercontent.com/47898011/92505130-76f0f200-f1b8-11ea-9695-c4b0998a9459.png)

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,
