### ISSUE TITLE
PO Received

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#130]
Purchase Order cannot fully received. When i clicked on Received status, it generate GRN. I checked all items on GRN and click received. But PO status show Partially Received, when it should be Received. Please review this issue.

**Comment by HafizAnas** [comment]
Hi @quangc 
Sorry for inconvenience, Let me check at our end and revert back to you.

**Comment by HafizAnas** [comment]
Hi @quangc 

I have reviewed at my end and I am not able to reproduce this issue. Please can you share screenshot/small video or steps with us so we can track this issue.

Thanks!

**Comment by quangc** [comment]
Will upload screenshot soon and more explain into this one.
