### ISSUE TITLE
HIDE NOTEs Date and Time printed on Invoice

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1306]
If we add any notes on ticket the inovie printing showing the date and time of added notes.Which is not neccessory and most of the time we don't need to tell customer when the ticket was last updated.
Any way to remove date and time on notice from invoice ?

![Screenshot 09-11-2020 19 10 24](https://user-images.githubusercontent.com/34261339/92900176-cbb79580-f462-11ea-9955-5a867afb07c6.jpg)

**Comment by BharatPRC** [comment]
Also , hiding warranty information from invoice.

**Comment by Uzair-RepairDesk** [comment]
Hello @BharatPRC 

Currently, it is not possible to hide the date & time for notes and the warranty information. We have a plan to make improvements to the template editor that will allow you to update the line items of the template as well. I have marked it under enhancements so we can pick up your request once we start working on this improvement.
