### ISSUE TITLE
Expense 

### ISSUE THREAD

**Issue by KEZSVS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1309]
Please if you can do to get the opcion to change the date of any payments 

like if i do a payment last week i can change the data

**Comment by Uzair-RepairDesk** [comment]
Hey @Eliezer138  
Hope you are doing well, we are already working on the improvement where you can add expense in previous dates.
We will keep you posted once this improvement will be live. 

Regards,

**Comment by Uzair-RepairDesk** [comment]
Internal Task:
https://repairdesk.atlassian.net/browse/REP-2708

**Comment by Uzair-RepairDesk** [comment]
Hey @Eliezer138
Hope you are doing well, we have made this improvement live where you can add an expense in backdate.
Note: this can be done only when the shift is not started, once the shift is started then you will not be able to add an expense in backdate.

Hope this helps.
Regards,
