### ISSUE TITLE
Tag in du invoice reminder doen'st work

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1310]
Try to email you invoices to pay with the "from invoice reminder" in "manage invoices" + "action". Once the reminder is received by email, you can see "store_name" for example instead of the company name.
<img width="935" alt="invoice reminder" src="https://user-images.githubusercontent.com/40500094/93391761-ad281480-f83d-11ea-9040-dbb0854fa6ba.png">

Essayer de vous envoyez un courriel des factures à payer avec le "du invoice reminder" dans "gérer les factures" + "action". Une fois le rappel recu par courriel, vous pouvez voir "store_name'' par exemple à la place du nom de l'entreprise.

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hey! @JessicaSOS 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by usmanalikhan93** [comment]
For Internal use: 
https://repairdesk.atlassian.net/browse/RB-1791

**Comment by usmanalikhan93** [comment]
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!

**Comment by JessicaSOS** [comment]
Here are the tags that are registered in the model:

Regards,

{store_name}
{store_address}
{store_email}
{store_mobile}

What is displayed is only the: {store_email}
look at the attachment.

So it's not settled.
<img width="528" alt="taggg" src="https://user-images.githubusercontent.com/40500094/93887792-25b32900-fcb5-11ea-97b1-7560f5481799.png">

-- french: --

Voici les tag qui sont inscrit dans le modèle :

Cordialement,

{store_name}
{store_address}
{store_email}
{store_mobile}

Ce qui s'affiche est seulement  le : {store_email} 
regardez la pièce jointe. 

Ce n'est donc pas réglé.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have fixed the issue on your account. And also verified by making invoice FL-26020. Now it's working. Please check and you can delete this invoice. 

Regards, 
Usman Ali

**Comment by JessicaSOS** [comment]
fixed Usman Tnx a lot :)
