### ISSUE TITLE
Tax Box & Refurbishing batch 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1315]
Hello, 

When editing the ticket, we try to remove the taxes from the tax box to $0.00 dollars. When the ticket is saved the tickets go back to what they were before. 

Refurbishing Batch: When creating the refurbishing batch, the system will auto select the wrong model. We ran the serial number for an iPhone 8 and the system select an iPhone Xs Max. 

Videos where sent to: 

fahadimran85@gmail.com
--

**Comment by Omar1892** [comment]
This is a pic from one of our refurbishing batch.


![Screen Shot 2020-09-21 at 4 41 34 PM](https://user-images.githubusercontent.com/47898011/93832149-b47a6400-fc29-11ea-8258-35fa00278893.png)

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Omar1892** [comment]
Any updates?

**Comment by Omar1892** [comment]
@MuhammadAdnan32 Hello, do you have any updates? We're having a lot of issues due to this problem. We're not able to not charge taxes in certain occasions.

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. Kindly found our product team comment bellow.
This is the current functionality that tax is charged on the part cost price, if you will change the tax for the service then it will have no impact on the part tax. change in tax on run time is not possible. 
For your second concern if you add a serial number in Refurbishing Batch and then create a ticket then you can't change the device as serail will not change and your selected serail will be refurb.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by Omar1892** [comment]
So if the taxes are shown in the Refurbishing batch it will have no affect on my Tax reports?

**Comment by Repairdesk-QA** [comment]
Hello @Omar1892,
I hope you are doing well. Yes, it does"t have any impact on the tax report because until the invoice has been not created there is no impact on the tax report and we don't allow to create an invoice for refurbishment ticket.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan
