### ISSUE TITLE
Expense delete or edit option

### ISSUE THREAD

**Issue by ciprianro** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1316]
Will be great to have the edit or delete expense option. also the expense code edit  option. Thank you

**Comment by Uzair-RepairDesk** [comment]
Hi @ciprianro 
Currently, our expense module is linked up with Start/End shift functionality. Once you enter the expense, you can edit/delete it before you actually post it and end the shift. Once you post it and end the shift, it means that you have reconciled the shift transactions and then system doesn't allow you to edit/delete the expense transaction. If we allow to edit/delete after you end the shift, it means that complete shift reconciliation will be disturbed. 
Please check screenshot attached that allow you to edit/delete the expense before you post and end the shift.

![uzairshahRepairDesk-Manageexpense-Expenses](https://user-images.githubusercontent.com/22955861/93973676-0b00b300-fd8e-11ea-956a-065b1826db35.png)

We are making updates that will allow you to enter the expense without the shift and you will be able to change the date as well. We can check the possibility that it should allow you to edit/delete the expense if you post it without the shift. 
Please note that expense code is a system generated code and its a primary key for the expense so we will not be able to allow you to edit expense code however if you have a specific code you can mention it along with the "Expense name". 

Hope it helps. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey @ciprianro  

we have added an option where you can edit expenses and also add an expense in the back date. 
Note: Expenses can be added in backdate only when a shift is not strated.  
Hope this helps.

Regards,

**Comment by ciprianro** [comment]
Hi, i cant find the option to edit an expense

În joi, 21 ian. 2021 la 09:40, Muhammad Uzair Shah <notifications@github.com>
a scris:

**Comment by Uzair-RepairDesk** [comment]
Hi @ciprianro 
Can you please make sure that you haven't posted the expense yet. You are only allowed if your expense entry is Unposted. Once it is posted, the system doesn't allow editing it. 
You can just save the entry of the expense in case you want to edit it later and once you are confirmed, you can post the expense. 

Hope it helps.

**Comment by ciprianro** [comment]
Sometimes your answers seem like jokes to me. What options have you
added? These options were before. This is not an answer I have been
waiting for since September 2020! I'm sorry to say this, but with such
answers I will definitely be a lost customer.


În vin., 22 ian. 2021 la 07:13, Muhammad Uzair Shah <
notifications@github.com> a scris:

**Comment by Uzair-RepairDesk** [comment]
Hi @ciprianro 
I sincerely apologize if you didn't like my response. I just updated you about the option we already have. I have also explained to you the reason in my first comment to restrict users to edit the expense once you post it. Please check my response above or check the screenshot attached below:-

![image](https://user-images.githubusercontent.com/22955861/105668469-31328d00-5eff-11eb-92f5-3575587d7668.png)

**Comment by ciprianro** [comment]
I don't like to lose my time and prove something. Please check the image.
In the email you said that you *ADDED THE OPTION TO BE ABLE TO EDIT AN
EXPENSE.*
This option was already there. Maybe you *JUST* added the option to add an
expense for a previous date.
and now in this email you turn it around and say that you just reminded me
of an already existing option.
Please next time check the request carefully before giving an answer. And
before saying that an update or a new option has been made, please check
very carefully if it works correctly.
Please understand that my time is not paid by RD. I chose RD to make money,
not to waste time.

În lun., 25 ian. 2021 la 08:20, Muhammad Uzair Shah <
notifications@github.com> a scris:
