### ISSUE TITLE
Customer Facing Display - issue

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1319]
I use this function from the begging and it's a big deal to have in our shop. 1 year ago after an update ( I think), my signature was affected. Actually, my signature is very small on receipt paper and looks like an dotted line. For intake signature I use an iPad which display was tested and everything it's oke.

**Comment by usmanalikhan93** [comment]
Hello @adigsm07 

I hope you are doing well. Is it possible for you to share a video with us about this query ?

**Comment by adigsm07** [comment]
> Hello @adigsm07
> 
> I hope you are doing well. Is it possible for you to share a video with us about this query ?

Of course 

--> here is the video: https://youtu.be/KDqGOW_-EyE

**Comment by adigsm07** [comment]
Any News?

**Comment by usmanalikhan93** [comment]
Hello @adigsm07 

I hope you are doing well. I have performed a inhouse testing regarding your issue but it is printing fine. Please check screenshot
![image](https://user-images.githubusercontent.com/39614480/94573446-892bf080-028b-11eb-93ea-f2243e3925ca.png)

**Comment by adigsm07** [comment]
Hi Usman! Today I tested the signature and now it's visible. However the signature is small, it's any setting that can adjust the size?

**Comment by usmanalikhan93** [comment]
Hello @adigsm07 

I hope you are doing well. Currently there is no option like this, because it takes an image of that signature and show it on receipt. 

Regards,
Usman ali
