### ISSUE TITLE
Custom color under specific device in "Manage Devices" vs adding device in "Trade-in".

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1330]
When you add a new device in "Manage Devices" you have an option to select custom colors for a specific model you add. The problem is that the choice doesn't show when you add a new device in Trade-in. Right now we have 119 different colors in the "Manage Device Colors". That means that it's way to hard to find the right color for - lets say Huawei Honor 8 color option "Pearl White" and I have to remember what color name that device have even though I added the color under "Manage Device". That doesn't make sense.

<img width="1419" alt="Screenshot 2020-09-30 at 18 08 01" src="https://user-images.githubusercontent.com/68819320/94721618-729e9b80-0356-11eb-83da-52ce372a7ec2.png">
<img width="1671" alt="Screenshot 2020-09-30 at 19 54 34" src="https://user-images.githubusercontent.com/68819320/94721909-d0cb7e80-0356-11eb-857a-d48117f89c68.png">

**Comment by MuhammadAdnan32** [comment]
Hey @jphansendk , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Uzair-RepairDesk** [comment]
Hey @jphansendk  
I have checked the reported issue, we have added this request in Sprint. I will keep you posted once it's done.

Regards,

**Comment by Uzair-RepairDesk** [comment]
For Internal use:
https://repairdesk.atlassian.net/browse/REP-2910

**Comment by jphansendk** [comment]
Thanks Guys.. would actually be cool to do the same with sizes - not as important but a cool feature 👍🏻

**Comment by jphansendk** [comment]
Any news on this topic? We now have 144 different device colors to choose from when adding a device in Trade-in. It's impossible to remember what is the right color for a special model. :-(

**Comment by Uzair-RepairDesk** [comment]
Hi @jphansendk 
It is expected to go live in our next release

**Comment by Uzair-RepairDesk** [comment]
Hey @jphansendk 
Hope you are doing well, we have made is improvement live, now while creating trade in colors will be populated based on the selected device, and if no color is associated with the device then all the clours will be shown against that device.
![image](https://user-images.githubusercontent.com/22955861/95977633-86f09700-0e32-11eb-8c1d-27b6c1e8f8aa.png)

Regards,

**Comment by jphansendk** [comment]
Thank you sooooo much 👍🏻🤘🏻🙌🏻🙏🏻
