### ISSUE TITLE
Inventory Items not adding correctly while editing a ticket

### ISSUE THREAD

**Issue by Shane-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1331]
![Capture](https://user-images.githubusercontent.com/60683772/94758811-3bd38000-036c-11eb-8fea-6721a71c3d55.PNG)
![Capture2](https://user-images.githubusercontent.com/60683772/94758815-42fa8e00-036c-11eb-931c-93ae42f550da.PNG)

Show correct amount while editing ticket once saved the totals are wrong.  Trying to re-edit the ticket you can see the totals are wrong as well after that initial save.

**Comment by Shane-RepairDesk** [comment]
I think this is also causing a random issue of (inventory items) not loading into the POS while checking out.  We are on the fly using casual to correct the cart and check out.

**Comment by MuhammadAdnan32** [comment]
Hey @Shane-RepairDesk , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by MuhammadAdnan32** [comment]
Hey @Shane-RepairDesk ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1862

**Comment by Shane-RepairDesk** [comment]
appears to me that it's just tax exempt inventory items...

**Comment by MuhammadAdnan32** [comment]
Hey @Shane-RepairDesk ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have questions.
Thanks & Regards,
M Adnan
