### ISSUE TITLE
Option to Sync cost prices accross all stores

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1333]
Please Please Please!!!! add the ability to sync the cost price from the main to store to the rest!!

**Comment by Uzair-RepairDesk** [comment]
Hey @TechTraders  
Hope you are doing well, we have planned an improvement release in a couple of weeks related to inventory module revamp, in that you will be able to sync cost price once at the time product creation to other stores. I will keep you posted on that.

Regards,

**Comment by TechTraders** [comment]
That is not what i am meaning.... 

what i need to be able to happen is that if i change the cost price on a particular product at our main store, i need that cost price to update at our other stores too.

**Comment by Uzair-RepairDesk** [comment]
hey @TechTraders 
We have made this improvement live that allows you to sync cost price across all stores. Please feel free to reopen this thread if you have any further questions. Thanks.
