### ISSUE TITLE
look wild to me--showing two devices but not two

### ISSUE THREAD

**Issue by Shane-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1335]
![Capture](https://user-images.githubusercontent.com/60683772/94861994-5fe39f80-0406-11eb-82e1-77cc85738bcb.PNG)
![Capture 2](https://user-images.githubusercontent.com/60683772/94862010-6540ea00-0406-11eb-8898-73985941f1ea.PNG)

**Comment by Shane-RepairDesk** [comment]
We are seeing this here and there

**Comment by MuhammadAdnan32** [comment]
Hey @Shane-RepairDesk ,
I hope you are doing well. Just an update we have fixed the reported issue and it’s available for beta testing on the app.repaircrm.co. We are hoping to go live with this today or Monday hopefully.

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1847

**Comment by usmanalikhan93** [comment]
Hi @Shane-RepairDesk 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
