### ISSUE TITLE
Merchandise Showing as in stock when it isn't 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1336]
We've being having a lot of issues still with the serialized merchandise. The items are marked are still being stocked once an RMA is created on them and the RMA is marked as sent to supplier. Video of the issue was sent to 

Video proof was sent to fahadimran85@gmail.com

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,
