### ISSUE TITLE
Remove special order item from ticket (not removing tax)

### ISSUE THREAD

**Issue by Shane-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1337]
Archived a special order item,  removes  cost of part from ticket, no way to remove the item as a whole and it's still charging tax on the special order item...Having to completely delete the ticket and start over.

**Comment by Shane-RepairDesk** [comment]
![Capture](https://user-images.githubusercontent.com/60683772/94950408-9675f480-04b0-11eb-9c5f-95b5ca26e6eb.PNG)

**Comment by MuhammadAdnan32** [comment]
Hey @Shane-RepairDesk ,
I hope you are doing well. You can delete a special part item from the listing page of Special Ordered Items with pending status only in current functionality and it will be removed from the ticket as well and tax will also remove from the ticket.
Just an update we have fixed the reported issue and it’s available for beta testing on the Beta server (app.repaircrm.co). We are hoping to go live with this tomorrow hopefully.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For inter use:
https://repairdesk.atlassian.net/browse/RB-1716

**Comment by MuhammadAdnan32** [comment]
Hey @Shane-RepairDesk ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have questions.
Thanks & Regards,
M Adnan
