### ISSUE TITLE
Sales Tax Issue 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1338]
I sent a video to Fahadimran85@gmail.com 

Taxes are still appearing in the ticket section even if we mark the ticket as no tax or mark the tax to 0.00.

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 ,
I hope you are doing well. Kindly found our product team comment bellow.
This is the current functionality that tax is charged on the part cost price, if you will change the tax for the service then it will have no impact on the part tax. So the change in tax on run time is not possible if tax is has been applied on the part cost price.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by Omar1892** [comment]
@MuhammadAdnan32 Hello, but it doesn't make any since that its "impossible" how come it was possible before? The box gives the option to change the tax collected by how ever much you want it. If im doing a refurbishing batch and the system is collecting the taxes who im I going to be charging those taxes to if im the one fixing the device for our own benefit. The taxes will still be collected and they will be coming out my pocket if I can't voided them. I sent you a video to show you have you seen it? It just doesn't make any since that it was possible for the past 4 years and now it just all of sudden isn't.
