### ISSUE TITLE
Paypal & Refund amount missing in Shift End Reconciliation report sent to XERO

### ISSUE THREAD

**Issue by DavidTsangFixpod** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1339]
Hi Repairdesk,

Thank you for intergrating XERO and repairdesk. 

At the end of each shift the reconcilation report that gets sent to XERO is missing Paypal sales figures and also refund figures. There are two bugs here.

1) There is two scenarios where the paypal function can be used. One method works, the other doesn't. If the ticket has been repaired and an email was sent to with the paypal link, if the client pays for it the ticket will be marked as paid. However once you go to End shift and check the reconciliation report it is not there. 

Second scenario, if paypal was selected on "check out" in POS, then it will show up in the reconcilation report. 

2) Refund figures. Reconcilation report only includes Merchant's "In" amount when it should take the "total" amount which has deducted the "out" (refund) amount. If sales was $1000, then made $100 refund for the day, total that gets exported to XERO should be in two lines.
Line 1 $1000 sales - sales account
Line 2 ($-100) sales refund - sales account
Total $900

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-1890
