### ISSUE TITLE
Emails still going to Junk - Cybertek

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1344]
Hi team,

We still have emails going to junk, most commonly emails that are hotmail, live or office 365 which mine are. All emails from the system go straight to my junk, this includes end of day reports, updates and even setting up a customer portal for myself.

Can we please get this fixed as I am wanting to start using the customer portal but looks really unprofessional when my emails go into a customers junk mail.

Adam
![Screenshot_20201006-120845_Outlook](https://user-images.githubusercontent.com/61297564/95151094-25df1880-07cd-11eb-8a07-f3e9a85344ab.jpg)

**Comment by Repairdesk-QA** [comment]
Hello @Cybertekww 

I hope you are doing well. Sorry for the delay response. I have discussed this with developer and he said the email address which is going in spam, please add that in your hotmail contact so that hotmail will not cater that email as suspicious. And hopefully it will resolve your issue. 

Regards,

**Comment by Cybertekww** [comment]
Hi team,

This doesnt work for our customers as they might not know how to do this and as we rely on the automatic emails to keep our customers in the loop on all changes to their tickets we really need a fix for this one

**Comment by Repairdesk-QA** [comment]
Let me discuss this today with our CTO.

**Comment by Repairdesk-QA** [comment]
Hello @Cybertekww,

There is one more thing to test. Go to your store setting and left blank store verified email field.
![Domain](https://user-images.githubusercontent.com/39614480/96713357-525e6d00-1355-11eb-829f-304c0fd613bd.PNG)

Hope this will sort out your issue. Please let us know which email you are using like, Gmail, Yahoo, or something else.

Regards,
Afnan Mahmood
