### ISSUE TITLE
Trade-in Barcode label with 2 barcodes

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1348]
How can I add both Item ID barcode and IMEI barcode to the Trade-in barcode label. I only seem to be able to add the item ID as a barcode?
<img width="341" alt="Screenshot 2020-10-11 at 00 15 39" src="https://user-images.githubusercontent.com/68819320/95666163-5f11e280-0b57-11eb-89fb-ce2f9fa5771b.png">

**Comment by Uzair-RepairDesk** [comment]
Hi @jphansendk 
We recommend putting IMEI under the "SKU" field while adding a trade-in device. If there will be an SKU with the IMEI number, the barcode will automatically be generated based on the IMEI number. 
Hope it helps.
