### ISSUE TITLE
Inventory item disappeared 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1349]
Video was sent to: @fahadimran303

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Omar1892** [comment]
Hello, do you guys have any updates on this matter? Its causing issues with our staff.

**Comment by Omar1892** [comment]
MuhammadAdnan32 we are starting to have more issues due to this problem. We can't create purchase orders because the system says that the item doesn't exist in the inventor altho it does and it has being in the inventory for years.

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892 ,
I hope you are doing well. Can you please share the video of the issue at adnan@repairdesk.co?
Thanks & Regards,
M Adnan

**Comment by Omar1892** [comment]
@Repairdesk-QA Video was forward
