### ISSUE TITLE
Error when edit ticket

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1351]
When edit ticket service information hidden in the tab look photo
![C287466E-1B31-4D72-A8FF-AF210AD85610](https://user-images.githubusercontent.com/44485797/96060527-660f5c80-0e99-11eb-8239-e936ac0b0b43.jpeg)

**Comment by Repairdesk-QA** [comment]
Hey, 
Afnan here 👋 Sure thing! 
Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
Hello @hitman1986 

Hope you are doing well and staying safe.

I have tried to reproduce your issue currently, it's working fine on our side. It might be a temporary system glitch.
Please double-check at your side and let me know if you are still facing the same issue.

Thanks and Regards
