### ISSUE TITLE
Template edit barcode size.

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1356]
Is there a way to edit the size of the barcode on labels templates? Right now mine is dithered and looks unprofessional for some reason. I dont see what I did wrong. I'm on mac and has not the possibility to remove dithering on our Zebra printer? And for me it looks like the barcode is getting converted to a picture instead of making it in vector like the rest of the label?
<img width="1407" alt="Screenshot 2020-10-14 at 11 54 31" src="https://user-images.githubusercontent.com/68819320/96351883-fda1c480-10be-11eb-839c-f1ddd5cfd000.png">
![IMG_0549](https://user-images.githubusercontent.com/68819320/96351895-114d2b00-10bf-11eb-99ca-93ea7f7df3be.jpg)

**Comment by Repairdesk-QA** [comment]
Hey , 
Amy here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Regard,
Afnan Mahmood

**Comment by Repairdesk-QA** [comment]
Hello @jphansendk,

Hope you are doing well. Sorry for the delayed response.

I have tried printing label from your account. It seems everything is working fine in your account. I am unable to find the same item from your account with ID:12616. Please give it try at your end if still there is an issue regarding this please mention item ID, store name so I can test at my side as well.

Regards,
Afnan Mahmood

**Comment by Repairdesk-QA** [comment]
Hi again @jphansendk - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by jphansendk** [comment]
Sorry just haven't had time to test it.. Maybe it's a conversion issue on mac.
