### ISSUE TITLE
Merge Customer Not Working

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1358]
I am trying to merge customers and it will not give me the option to select any customers to merge with

![Capture](https://user-images.githubusercontent.com/68912093/96540442-1ee1fb00-12e1-11eb-860a-1bd09f2679e0.PNG)

**Comment by Repairdesk-QA** [comment]
Hey @TechTraders , 

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
Hello @TechTraders 

I hope you are doing well. Customer merge functionality works on the basis of First name and Last name. E.g. If you have Customer with name John smith and you want to merge customer with him, only those customer's will come up for merge who's first name is "John" or last name is "Smith".
Do you have customers with Ian or Blackwood more in your Manage Customer ? 

Usman Ali

**Comment by Repairdesk-QA** [comment]
Hello @TechTraders,

Hope you are doing well and staying.

I have checked in detail on your account. There is different customers with same First and Last name. These supposed to show while merging customers. This looks like account specific issue. Same functionality working fine on other accounts. I have created an internal task to sort this out. I will keep you posted about the progress.
For internal use:
https://repairdesk.atlassian.net/browse/RB-1942

Regards,
Afnan Mahmood

**Comment by Repairdesk-QA** [comment]
Hello @TechTraders,

Hope you are doing well and staying safe.

We have checked this issue in your account in detail. There is a minor system limitation that you can merge only those customers who fall in the same store. Customers those created in-store 2 can't be merged in-store 1.

Hope this helps. Please give it try at your end and let us know if you need further assistance. 

Regards,
Afnan Mahmood

**Comment by TechTraders** [comment]
Is this somthing that will be fixed though? because a lot of our Duplicates are from different stores?

**Comment by Repairdesk-QA** [comment]
@TechTraders 

We can delete duplication customers. Our development team will check duplication on the base of name, email, phone, mobile in your account. If duplication found in the different stores than we will check for transactions against that customer in each store. If we found customers with no transaction then we will delete it from that store.

If you want us to delete then please allow us so we can proceed.

Regards,
Afnan Mahmod

**Comment by TechTraders** [comment]
Hi Afnan, 

Sure go ahead, but if there is a duplicate customer with transactions on both records are you still able to merge them without loss of data?

**Comment by Repairdesk-QA** [comment]
@TechTraders 

If any customer falls in both stores with a transaction record then we are unable to merge these due to data loss.

**Comment by Repairdesk-QA** [comment]
@TechTraders 

We have merged customer on the base of first name, last name, mobile, and email. Only 27 customers merged from the backend other than this we also found 223 duplicate entries but these have transactions as well on different stores so, we can't delete them to avoid data loss.
