### ISSUE TITLE
Trade in Refund Bug

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1367]
Please fix the issue that i am having... if you refund a trade in device and we do select to add back into inventory but i still is listed as sold... please fix this.

![Capture1123](https://user-images.githubusercontent.com/68912093/96825864-774a0180-1475-11eb-92e4-8200b0820a5a.PNG)
![capture123](https://user-images.githubusercontent.com/68912093/96825866-787b2e80-1475-11eb-884e-44a3eed07389.PNG)

**Comment by Repairdesk-QA** [comment]
Hey , 
Afnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Regards,
Afnan Mahmood

**Comment by Repairdesk-QA** [comment]
Hello, @TechTraders 

I have tried to reproduce this bug at my end with your specified case. It seems everything is working fine.
To sort this out the issue we have changed this trade-in status from sold to In stock from the backend. 
Please verify this at your end. I hope this will fulfill your need.

Regards,
Afnan Mahmood
