### ISSUE TITLE
Campaigner/Text Characters way too short please remove 160 character limit

### ISSUE THREAD

**Issue by Gofixmobile** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1368]
can you remove the 160 character limit on the sms sections?

**Comment by Repairdesk-QA** [comment]
Hello @Gofixmobile,

Hope you are doing well.

Let me discuss your concern with the team. I will get back to you after the Rediscussion.

Regards,
Afnan Mahmood

**Comment by Repairdesk-QA** [comment]
Hey @Gofixmobile,

I have discussed this with the team. For the time being, we can't do this if the character length increases then SMS will not show in the correct format. It will show like small empty boxes. 

Hope you understand.

Regards,
Afnan Mahmmood
