### ISSUE TITLE
URGENT: API GET devices problem.

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1369]
Hi.

I was just told by our development team that when our client are looking in our trade-in stock through the API and search for - lets say iPhone 7. The API doesn't show each iPhone 7 in different colors or sizes when they request device_id.. only "iPhone 7 Black 128GB" and it bundles alle the iPhone 7's and Black 128GB models even though we also have other colors and sized.. Thats a HUGE problem and it needs to be fixed fast.. We miss SO many orders from our client because of this bug and have around 80-100 orders as I write this, we don't get in our system/repairdesk.

**Comment by jphansendk** [comment]
I think our dev team has found a solution.. Dont know what yet :-/

**Comment by Uzair-RepairDesk** [comment]
Hi @jphansendk 
If you are able to sort out this concern, we can close this task. Please confirm?

**Comment by jphansendk** [comment]
Yes.. found a solution thanks.
