### ISSUE TITLE
Ensure loan device is returned

### ISSUE THREAD

**Issue by orvarb** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1371]
Hi!

Our workshop sometimes gives a loan device to customers, for example when you bring a phone to the workshop you can get a loan phone while your phone is being repaired. The devices we have for loan are very well marked with their own code (for example, let's say we have 50 loan phones and their code starts with 'LS' and ranks up, LS1 - LS2 - LS3 - etc.) and we've created a custom field when creating a ticket called "Loan device?" and if a customer got phone for loan, we select from the drop-down which phone they got. 

The problem we have with this setup is that sometimes the employees forget to take back the loan devices. It would be amazing if we could somehow ensure that a loan devices is returned when the ticket is closed. Something like when you are closing a ticket and if an option is selected in the "Loan device?", the employee would be asked (with a pop-up window or something) if the loan device has been returned and the employee has to confirm it has been returned.

**Comment by Uzair-RepairDesk** [comment]
Hi @orvarb 

Thank you for sharing your workflow. Please find a quick solution to your problem below:-

- We have "Flag" functionality available in RepairDesk that allows you to mark "Diagnostic Note" or "Customer Profile" note with a flag. When you enter the note and make it flag, the system gives you an alert with the same note when you open the ticket. 
In your case, when your employees mark the loan device you can also ask them to enter a note in the diagnostic note/customer profile note that "Loan device needs to be returned". 
This note will appear for your employees when they reopen the same ticket on the POS or Manage tickets screen. 

Please check the screenshots attached when you can mark the note with a flag. 
![uzairshah-POS flag](https://user-images.githubusercontent.com/22955861/97137285-491b3900-1777-11eb-8313-72b1cd73490b.png)


Hope it helps
