### ISSUE TITLE
Thermal Receipt Template not showing "{{technical_repair_report}}"

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1372]
Im trying to set up a "Thermal Receipt Template" for our micro-solder so he can print a ticket receipt including post rep cond. and any notes under "{{technical_repair_report}}". But for some reason the "{{technical_repair_report}}" doesn't show?
![ticket_T-761](https://user-images.githubusercontent.com/68819320/97299989-1a27c480-1856-11eb-923b-7fa7435c41de.jpg)

Here is the template code..
One more thing.. is it possible to remove the price?

```<!doctype html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
	<style type="text/css">* {margin: 0;padding: 0;}
body {color: #000;font-size: 12px; line-height:16px; }
.miniReceipt2{ margin:0 auto; max-width:454px}
table{border-collapse:collapse;border-spacing:0;width:100%}
.table1 td{padding:2px 0; font-size:12px; line-height:16px;}
.table2 td{ padding:5px 0; font-size:12px; line-height:16px;}
.table2 .seprator{ height:3px; border-top:1px   dotted #000;border-bottom:1px  dotted #000; padding:0; text-indent:-999em; line-height:1px;}
.table2 .seprator2{ border-top:1px  dotted #000; padding:0;text-indent:-999em; line-height:1px;}
.text-center{ text-align:center;}
img{ max-width:100%;}
	</style>
</head>
<body>
<div class="miniReceipt2">
<div style="text-align:center"><strong style="font-size:18px">{{tittle}} </strong></div>
<br />
{{store_logo}}
<div><br />
<strong>{{store_name}}</strong><br />
<span>{{store_address}}</span><br />
<span>Phone: {{store_phone}}</span><br />
<span>Website: {{store_website}}</span><br />
<span>Registration Number: {{store_registration_no}}</span><br />
<span>Date: {{generated_datetime_stamp}}</span></div>

<div class="mini-customer">{{Customer_complete_details}}</div>
&nbsp;

<table border="0" cellpadding="0" cellspacing="0" class="table1" width="100%">
	<tbody>
		<tr>
			<td><strong>Ticket: </strong> {{ticket_no}}</td>
			<td align="right"><strong>Prepared By:</strong>&nbsp;{{ticket_created_by}}</td>
		</tr>
		<tr>
			<td colspan="2">&nbsp;</td>
		</tr>
	</tbody>
</table>
&nbsp;

<table border="0" class="table2" style=" font-size:12px;" width="100%">
	<tbody>
		<tr>
			<td class="seprator" colspan="3">&nbsp;</td>
		</tr>
		<tr>
			<td id="inventory-grid_c0"><strong>Item Name</strong></td>
			<td align="right" id="inventory-grid_c1"><strong>QTY</strong></td>
			<td align="right" id="inventory-grid_c2">&nbsp;</td>
		</tr>
		<tr>
			<td class="seprator" colspan="3">&nbsp;</td>
		</tr>
		<tr class="tr-error">
			<td colspan="3">
			<p>{{invoice_line_items_table}}</p>
			</td>
		</tr>
		<tr class="tr-error">
			<td colspan="3">
			<p>Notes: {{technical_repair_report}}</p>
			</td>
		</tr>
	</tbody>
</table>

<div class="barcodecell">
<div>{{barrcode}}</div>

<div>
<p><span style="font-size:8px; margin-top:-5px;">{{reference_no}}</span></p>
</div>
</div>
&nbsp;

<div class="text-center">{{footer}}</div>
</div>

<div>&nbsp;</div>

<div>&nbsp;</div>
<style type="text/css">.barcode {
    padding: 1.5mm;
    margin: 0;
    vertical-align: top;
    color: #000044;
}
.barcodecell {
    text-align: center;
    vertical-align: middle;
}
</style>
</body>
</html>```

**Comment by Repairdesk-QA** [comment]
Hey,
 
Afnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Regards,
Afnan Mahmood

**Comment by Repairdesk-QA** [comment]
Hey! 👋 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

For internal use:
https://repairdesk.atlassian.net/browse/RB-1972

Regards,
Afnan Mahmood

**Comment by Repairdesk-QA** [comment]
Hello @jphansendk,

Hope you are doing well and staying safe.

This issue has been sorted out in the case of tickets. To show this on thermal receipt it's mandatory to select repair reference first from a dropdown. If repair reference is selected then it will show on thermal receipt otherwise it will show only on manage tickets technical repair report section.

Please verify it at your end. Hope it works fine for you.

Regards,
Afnan Mahmood

**Comment by jphansendk** [comment]
hmm.. Now it's only showing repair report.. Not the device info?

<img width="911" alt="Screenshot 2020-10-29 at 13 56 59" src="https://user-images.githubusercontent.com/68819320/97576657-b97fbf80-19ee-11eb-9cbd-9fd2675dd6a8.png">

**Comment by Repairdesk-QA** [comment]
@jphansendk,

Currently, It'showing repair line items. We are working on it. I will update as soon as this issue is sorted out.

Regards,
Afnan Mahmood

**Comment by Repairdesk-QA** [comment]
Hello @jphansendk,

Hope you are doing well.

Your reported issue has been fixed. Please verify at your end and do let us know if you have questions. Now line items and technical repair report note both will show.

Regards,
Afnan Mahmood

**Comment by jphansendk** [comment]
Thanks.. Working now.. Great work people :-)
