### ISSUE TITLE
mandatory customer signature

### ISSUE THREAD

**Issue by gijoe911** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1375]
Is there a way to mandate customer signature on every ticket/invoice? i cant seem to find this option anywhere. this is important as to prevent our asses being sued.

anyone knows? thanks

**Comment by Uzair-RepairDesk** [comment]
Hi @gijoe911 

Can you please specify how exactly you are taking signatures? Did you try our "Customer Facing Display" widget that allows you to display order information to your customer and you can take a signature while creating a ticket or an invoice? 

Please check the screenshot attached below:-

![uzairshah-Customer-Facing-Display-Widget-Configuration](https://user-images.githubusercontent.com/22955861/97420760-89241c80-192d-11eb-9283-d7fb1cbe6d2e.png)

You can learn more about it from the following knowledgebase article:-
https://help.repairdesk.co/knowledgebase/articles/1102397-taking-customer-signatures-through-customer-facing

**Comment by gijoe911** [comment]
Hi uzair,

we currently don't use customer facing display and just rely on our ipad to take signatures as below. it lets me create tickets and check out without taking signatures. any ideas i can make this mandatory?

![WeChat 圖片_20201028175959](https://user-images.githubusercontent.com/25240657/97421429-76b6dc80-1947-11eb-86c4-b1b52060244f.jpg)

**Comment by Uzair-RepairDesk** [comment]
Hi @gijoe911 

Currently, it is not possible to mark it mandatory to take the signature. We can log it on behalf of your request to check the feasibility to add it. 

Most of the customers use a customer-facing display widget that is really easy to set up and allows a better customer experience for your customers. You can setup it on any touch, tablet screen even on an iPad. We can also assist you in setting up the widget. 
Please feel free to let me know if you are interested in using it. Thanks

Regards,
Uzair

**Comment by gijoe911** [comment]
would be great if u can make it mandatory. it's probably a couple simple lines of code. some of our staffs doesnt know how to work a computer and can only use an ipad so it's best to keep it simple for them. looking forward for this on the next update.

**Comment by gijoe911** [comment]
also they dont know english so the facing display is harder for them.

**Comment by Uzair-RepairDesk** [comment]
Hi @gijoe911 
Thank you for your feedback. Appreciate it. It is not just about the simple line of code, we check the feasibility of the request and our audience response before we start working on the enhancement. 

There are 2 criteria we follow for the enhancements request:-

1: We log it in our product backlog and pick up based on community feedback in our future roadmap
2: If you want to prioritize your requests you can list all your enhancement request, we can check the feasibility and we can quote you for the customization and prioritize it in our quarter roadmap.

Regards,
Uzair
