### ISSUE TITLE
Unable to do partial refund.

### ISSUE THREAD

**Issue by iCellsouthcity** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#138]
Unable to do partial refund. Not a major problem as we are not doing refunds all them time but plz do look into it when you have time.

**Comment by HafizAnas** [comment]
Hi @iCellsouthcity 
Currently, Our system is not dealing with partial refund and it only allows you to do overall refund but I will add your suggestion for enhancement.

 Scenario currently dealing with Refund
Suppose you sold out more than one item against one Invoice and customer want to returns/refund one of them against this invoice. you can do that but if you make invoice for $100 and wants to refund $50. you can't do this.

Let me know if you have any question.
Thanks!

**Comment by quangc** [comment]
Load the invoice back into POS and then delete individual item before processing to check out. This may go around for this to be done. I guess.

**Comment by Uzair-RepairDesk** [comment]
You can do partial refunds in "Amount" or "Qty" for fully paid invoices. You can find details from the following link:-
https://repairdesk.uservoice.com/knowledgebase/articles/895113-how-can-i-process-refund-exchange-in-repairdesk
