### ISSUE TITLE
Shopify Integration

### ISSUE THREAD

**Issue by JeffFIZUAS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1380]
We would like to see an integration with Shopify as well so we can use Repair Desk as our inventory management and to bring sales in from that system. That would be great. At least the inventory would be great to sync up with Shopify.

**Comment by ProductTeam-RepairDesk** [comment]
Hey, @JeffFIZUAS  Shopify integration is live now, for more detail you can review the KB article link attached below.
https://help.repairdesk.co/knowledgebase/articles/1975338-how-to-setup-shopify-integration-in-repairdesk

Regards:
Humza
