### ISSUE TITLE
Booking Widget/ All Bookings are classified as "Quotes" 

### ISSUE THREAD

**Issue by Gofixmobile** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1382]
Everytime someone books online, I receive a text saying " Customer's Name and then followed by : is requesting a "quote" even when they pay.

and when its an actual quote, and I create an estimate. the estimate is sent out and the price shows "$0.00"

I need to be able to know what's a quote and an actual booking request.

**Comment by Repairdesk-QA** [comment]
Hey @Gofixmobile  ,
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
