### ISSUE TITLE
Additional tab in manage tickets

### ISSUE THREAD

**Issue by waynza** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1383]
Can you add an additional tab in "manage tickets," or possible customise the tabs that are available.
We outsource some of our repairs, and we would like to have the suppliers case/ticket number clearly visible as a tab.

**Comment by Uzair-RepairDesk** [comment]
Hi @waynza 
You can add "Custom Fields" for tickets with respect to the repair category. Once you fill the field, you are also able to see/track it on the manage tickets page. 

Please check the screenshot attached below. You can learn more about the custom fields functionality from the following knowledgebase article:-
https://help.repairdesk.co/knowledgebase/articles/1921693-custom-fields

![uzairshahRepairDesk-Ticket](https://user-images.githubusercontent.com/22955861/97859695-cb30d200-1d22-11eb-8495-a9e2abcc154e.png)
