### ISSUE TITLE
Sales tax option when buying phones on Trade-In

### ISSUE THREAD

**Issue by techm89** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1387]
Do you guys have any plan on adding sales tax option on buying devices on Trade-In? Let me give an example.

Normally when you buy phone from customer, you don't have to pay taxes. This part is OK, everything is working well. But when you buy phones from a business, you have to pay the taxes and then you get em back later. This is the issue I got. If I buy a device from a business I have to create an inventory item and create a PO. But if I need to refurbish the device I cannot do it from an inventory item. I need to use Trade-In. Trade-In don't have the option to add taxes to the buying price, this issue is complicating the buying process and if not very user friendly.

**Comment by Uzair-RepairDesk** [comment]
Hi @techm89   you can create a refurbishment ticket for inventory Items if you can make them serialized.
Attached is the link for knowledge for the refurbishment module.
https://help.repairdesk.co/knowledgebase/articles/1906375-refurbishment-module
if you have any more questions do let us know.
Hope this helps 

Regards,

**Comment by techm89** [comment]
My bad, thanks. I didn't see that.
