### ISSUE TITLE
Not Closing Tickets

### ISSUE THREAD

**Issue by foneworkshop** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#139]
Still having problems where tickets are not "Repaired and collected" when payment has been taken

i have pages of "PINK" tickets that need to be resolved

**Comment by HafizAnas** [comment]
Hi @iCellsouthcity,
Sorry for Inconvenience. Let me check at our end and revert back to you soon.

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk can you reach out to client today and do screenshare to see why its happening?

Thanks

**Comment by Uzair-RepairDesk** [comment]
I have contacted Ian @foneworkshop him on Facebook and requested him to add me over Skype so I can give him a call

**Comment by Uzair-RepairDesk** [comment]
We fixed this issue a while ago. You can mark the ticket "Repaired & Collected" while checking out.
