### ISSUE TITLE
Inventory Summary Filter Request

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1393]
Hi, I would like a filter to be appied to the Inventory summary report for me to be able to view all item that are out of stock ( 0 qty in all stores) i understand that the low stock report exists but i want to be able to see absolutely every item regardless of if there is low stock warnings set. can this happen?

**Comment by Uzair-RepairDesk** [comment]
Hey @TechTraders 
For now, you can click on the total value column in the report and sorting will be applied.you can get your desired result, a screenshot is attached for reference. 
![store-1-Inventory-Summary-Report](https://user-images.githubusercontent.com/22955861/98656869-ffc80d80-2362-11eb-8021-19f4cb943ed7.png)
Hope this helps

Regards,

**Comment by TechTraders** [comment]
not what i was asking at all... i want to filter the list so it wil ONLY populate 0 QTY items. i did not say anything to do with the total value. 

also selecting the "sort by" option for QTY is not what i am asking either because that will still show the in stock items in the list if i go to print it out or export.

**Comment by Uzair-RepairDesk** [comment]
Hey, @TechTraders  Hope you are doing well.
Sure thing I have added your request to the product backlog and I will keep you posted on this. 

Regards.

**Comment by TechTraders** [comment]
thank you, can i request you to add the "technology traders" label to this post please

also can this filter include anything that is a negative QTY as well please

**Comment by TechTraders** [comment]
Hi there, any updates on this request?

**Comment by Uzair-RepairDesk** [comment]
Hey @TechTraders 
Hope you are doing fine. we have made this imoprovmetns live , now you can apply fitler and check all the item with zero  stock or negative stock. when you apply filter will show zero quantity item then items with zero qty and negatvie will be displayed in the report. 
**Note: if you apply Exclude zero qty and show zero quantity item filter at the same time then their will be no impact on report data.**

Regards,
