### ISSUE TITLE
Task Alerts with Due Dates

### ISSUE THREAD

**Issue by GeniusRepair1** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1395]
We have due dates for repairs but we would love to be able to have a pop up reminder or notification about the repairs that are coming up

**Comment by Uzair-RepairDesk** [comment]
Hi @GeniusRepair1 

RepairDesk certainly gives you a notification if the due date is passed for the repair job. Also, if you enable email/SMS notification, the system sends an alert by email/SMS that the due date has passed for the job. 

Please check the screenshots attached

![image](https://user-images.githubusercontent.com/22955861/98777430-81c33f80-2412-11eb-8984-94a30a57461f.png)

![image](https://user-images.githubusercontent.com/22955861/98777485-acad9380-2412-11eb-8740-753f76ea27bb.png)

Hope it helps.

**Comment by Uzair-RepairDesk** [comment]
Hey @GeniusRepair1 
Hope you are well. Can you please confirm if you got the solution above? Please feel free to let me know if you have any questions. Once you confirm, we can close this. Thanks

**Comment by Repairdesk-QA** [comment]
Hello @GeniusRepair1,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
