### ISSUE TITLE
Invoice Pulling Wrong Terms & Conditions / Estimate Form Has issues

### ISSUE THREAD

**Issue by JeffFIZUAS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1397]
The terms and conditions in the invoice are pulling it from somewhere else not from the store that we are working in. Can this be resolved?

Also, when we make a change to the invoice or estimate it changes the fields shift. Doesn't really matter what fields we shift?

On Estimate it says GST, we need it to read Sales Tax. When we modify GST to says Sales Tax it shifts fields around.

We need these fixed ASAP.

**Comment by Repairdesk-QA** [comment]
Hello @JeffFIZUAS,

Hope you are doing well and sorry for the delayed response.

I need more details regarding this to verify. Please share Estimates, invoice id's in which you are facing the reported issue. It will be highly appreciated if you can share your RepairDesk Login details at afnan@repairdesk.co

Regards,
Afnan Mahmood

**Comment by JeffFIZUAS** [comment]
001

It does it on all of them pulling the wrong field. We need this fixed quickly we are about to go live

**Comment by Repairdesk-QA** [comment]
Hello @JeffFIZUAS,

Please share your login details with me at afnan@repairdesk.co So I can verify this in your account.

Regards,
Afnan Mahmood
