### ISSUE TITLE
Request to Add Payment Method Filter in Manage Invoice | Shavaiz | iTech Office

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1398]
**Hi Sir**,

**Business Name**:
iTech Office

**Customer Stature**:
8 Store Locations on Professional Package with Monthly Plan.
High Presence on Social Media.
Can help us a lot in other verticals as well.

**Module**:
Invoices

**Improvement**:

Need to add a filter in which we can pull up all Invoices on the basis of Payment Method like TSYS, Cash, Offline Credit Card

**Source**:
Intercom

_Thanks and Regards_,
**Faisal Ali**

**Comment by fahadimran303** [comment]
Jira link:
https://repairdesk.atlassian.net/browse/REP-3025

**Comment by Uzair-RepairDesk** [comment]
Hi @fahadimran303  , Faisal,

Currently, a filter is not available under "manage invoice" however we have a "Register Sales" report that is specifically linked with the invoices and cash basis report. You can apply the filter with "Method" under the criteria to filter the report with a specific payment method. 
Please check the screenshot attached. 

![image](https://user-images.githubusercontent.com/22955861/99029061-4ac86780-2593-11eb-83ea-e9e438a39e29.png)
