### ISSUE TITLE
Customer Facing Display 

### ISSUE THREAD

**Issue by Cumbr1at3ch** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1400]
hi guys 
Just a quick thought after discussions with your arnold re the customer facing display. Im taking advantage of the facility to capture customers signatures pre- repair after them agreeing our t+c of business. On this marvellous software there is the capability for us to capture these signatures post repair and yet I cant do this and Arnold suggested I escalate this to you as a suggestion ?

**Comment by Uzair-RepairDesk** [comment]
Hi @Cumbr1at3ch 

Hope you are well. Thank you for your post. Perhaps, Arnold didn't get your query properly. I apologize on his behalf. 
We have already an option available to take the signature of "Post-repair" terms. 
You can set the post-repair terms & conditions from configurations of the customer-facing display widget. 
Once you repair the device and checkout to make the payment, you can enable the toggle to take the "Post-repair" signature. Once you do this, the customer will be able to see post-repair terms and mark the signature. 

Please check the screenshot attached. 

![image](https://user-images.githubusercontent.com/22955861/99214735-c116d500-27f2-11eb-9c62-47740e0c3dbc.png)

Hope it helps. Please feel free to let me know if you have any questions about this.

**Comment by Uzair-RepairDesk** [comment]
Hey @Cumbr1at3ch 
Hope you are well. Can you please confirm if you got the solution above? Please feel free to let me know if you have any questions. Once you confirm, we can close this. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi @Cumbr1at3ch 
Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up. Thanks.
