### ISSUE TITLE
Bookings

### ISSUE THREAD

**Issue by Gofixmobile** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1401]
Hello

I have noticed that every time a booking is made, its notifies us a “quote” even when the customer has paid for an on-site repair. Can you make it so it notifies with the proper language, so if a customers book, it sends a “ you have a new order or booking” as opposed to it just saying “customer has requested a quote”

**Comment by Uzair-RepairDesk** [comment]
Hi @Gofixmobile 
You can customize the email template and text according to your choice from Emails & Notifications. 
You can go to **Store Settings > Email & Notifications > In-House > Leads/Appointments > Select the template and update it > Save**

Please check the screenshot attached

![image](https://user-images.githubusercontent.com/22955861/99213752-39c86200-27f0-11eb-83bd-bf2ca8b6529d.png)

Please feel free to let me know if you have any further questions. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey @Gofixmobile 
Hope you are well. Can you please confirm if you got the solution above? Please feel free to let me know if you have any questions. Once you confirm, we can close this. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi @Gofixmobile 
Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up. Thanks.
