### ISSUE TITLE
email generated from RepairDesk

### ISSUE THREAD

**Issue by waynza** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1402]
We created a ticket for a repair, email was send from repair desk to customer.
THe email sent to the customer is missing data, background, text etc.
<img width="728" alt="Screenshot 2020-11-17 at 12 32 36 pm" src="https://user-images.githubusercontent.com/64277204/99337220-c72fb300-28d1-11eb-852c-81514bff5f09.png">

**Comment by Uzair-RepairDesk** [comment]
Hey, @waynza  did you check the email template from Settings **=>** Email Notification section. kindly check the template.
if the issue still there do let us know.

Regards

**Comment by Repairdesk-QA** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
