### ISSUE TITLE
Price changing after pressing save item when creating new inventory item

### ISSUE THREAD

**Issue by techm89** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1403]
When I create a new item under inventory. I enter the coast price: 651.60$, then the retail price: 699$. When I press Save Item, the price is changing to 698.97$ by itself. I think this might have something to do with the markup % but I am not sure.

**Comment by Repairdesk-QA** [comment]
Hey @techm89 , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hey @techm89 ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2075

**Comment by Repairdesk-QA** [comment]
Hey @techm89 ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have questions.
Thanks & Regards,
M Adnan
