### ISSUE TITLE
Cant change quality

### ISSUE THREAD

**Issue by vertechd** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1404]
Cant change quality for labor when device is checked in.

**Comment by Repairdesk-QA** [comment]
Hello @vertechd,

Hope you are doing well.

Can you please share more info on this so we can understand and proceed with the solution.

Regard,
Afnan Mahmood

**Comment by Repairdesk-QA** [comment]
Hi again  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
