### ISSUE TITLE
Item serial missing in inventory report

### ISSUE THREAD

**Issue by yourfone** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1405]
i registed my phone device
Under manage inventory--mobile. acceccories-----then serialise the item based on IMEI...
So that i can categorize a particular model of phones based on color and memory.....the serial number there is my IMEI number...

now on the inventory report....i can get the list of all my phones with their imei..

how can it be solved 

thanks

**Comment by Uzair-RepairDesk** [comment]
Hey, @yourfone  you can view all your serials from the inventory summary report, by searching the specific item and then click on view serials for a specific store. or you can search from any specific serial and view all details.

![image](https://user-images.githubusercontent.com/22955861/99631668-ca57aa00-2a5d-11eb-8f65-55b31b6c15e5.png)
Hope this helps

Regards
