### ISSUE TITLE
Be able to take a deposit when sending a ESTIMATE!

### ISSUE THREAD

**Issue by Lchapmanrepairs** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1406]
im a watch repair company and i use a deposit system where the cusotmer must pay half the cost of the repair before i start.

i always send a estimate before repair and it would be really good to have a button after the approve for them to pay the deposit ammount.

Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi @Lchapmanrepairs 

Thank you for sharing your workflow. Once the estimate is approved it means that the customer is willing for the job. Our current recommended solution is this case to convert an estimate into a repair ticket and go to the ticket page or POS to reopen the ticket and to add partial payment against the job. 

Please let me know if it could work for you. Thanks
