### ISSUE TITLE
The estimate notes created from the leads are no longer displayed on the estimate

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1413]
The estimate notes created from the leads are no longer displayed on the estimate. In order for it to be visible to the customer, we must enter a note BEFORE CLICKING ON ADD LINE and this is what we do but after trying several times, the notes still do not appear. I tried to create multiple leads and reset the template, but no luck. You can run tests in my account without any problem.
<img width="939" alt="comment" src="https://user-images.githubusercontent.com/40500094/100803877-ecf0a800-33f9-11eb-9b81-b87d3cf9c5db.png">
<img width="937" alt="download estimate" src="https://user-images.githubusercontent.com/40500094/100803880-ed893e80-33f9-11eb-9309-f3316d1503cb.png">

French :
Les notes des estimations créé à partir des lead ne s’affiche plus sur l'estimation. Pour qu'elle soit visible par le client, nous devons inscrire une note AVANT DE CLIQUER SUR ADD LINE et c'est ce que nous faisons mais après avoir essayer plusieurs fois, les notes ne s'affiche toujours pas. J'ai essayer de créé plusieurs lead et de réinitialiser le modèle, mais sans succès. Vous pouvez faire des tests dans mon account sans problème.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS, 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2161

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have questions.
Thanks & Regards,
M Adnan

**Comment by JessicaSOS** [comment]
the notes in "additional information" work, but the notes in "customer comment" do not work, even if they are entered before adding the line "add row".

--
les notes dans "aditional information" fonctionnent, mais les notes dans "customer comment" ne fonctionnent pas, même si elles sont inscrites avant d'ajouter la ligne "add row".

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I hope you are doing well. In current functionality, if notes in the "customer comment" are entered before adding the line "add row" the notes will be displayed on the lead history only and the notes added in the Additional Info field will be displayed on the estimate. Kindly also see the attached screenshots as well.
![Screenshot_185](https://user-images.githubusercontent.com/39614480/102579525-70123d80-411e-11eb-9ef9-9c14b39896c4.png)
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by JessicaSOS** [comment]
Hello M Adnan,
The two places weren't working when I first wrote to you. Now the notes in "additional information" are displayed in the lead estimate. Thank you for this change. Before your changes, it was the other way around. As long as there are notes showing up, that's fine with me.

Have a good day
