### ISSUE TITLE
Keep newlines in the comment editor

### ISSUE THREAD

**Issue by KEZSVS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1414]
Can you please respect newlines as entered in the comment editor.

![newlines-issue](https://user-images.githubusercontent.com/69765024/100910913-753c7f00-34c6-11eb-8623-bb7d27ccb7cc.png)

Thank you

https://www.php.net/manual/en/function.nl2br.php

**Comment by Repairdesk-QA** [comment]
Hello @KEZSVS,

Hope you are doing well and sorry for the delayed response.

We have logged this as an improvement and assigned it to the developer. I will update once this is done. 
Please expect an update from us on coming Thursday.

Regards,
Afnan Mahmood

**Comment by Repairdesk-QA** [comment]
Hello @KEZSVS, 

Hope you are doing well and staying safe.

Your reported issue has been fixed. Please verify at your end and do let us know if you have questions.

Thanks!

**Comment by KEZSVS** [comment]
Confirmed.

Working fine, thank you.

**Comment by KEZSVS** [comment]
Can you fix this for all messages, including SMS and email?
