### ISSUE TITLE
Customer Custom Field Suggestion

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1415]
I am wanting to have a custom field to account manager assigment. so can we add a custom field option for the staff list drop down to be a option? like the staff assigned on a repair ticket

**Comment by Uzair-RepairDesk** [comment]
Hey @TechTraders 
Hope you are doing well, can you provide more detail for the above request so that we can look into this.

Regards,

**Comment by TechTraders** [comment]
nevermind i have found a workaround that suits my custom needs.
