### ISSUE TITLE
Loyalty Points 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1416]
Issues with loyalty points. Video was sent to Fahad via email.

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892 ,
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892 ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Reagrds,
M Adnan

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2188

**Comment by Omar1892** [comment]
Any updates yet?

**Comment by Omar1892** [comment]
@Repairdesk-QA Any updates yet?

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892,

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have questions.

Thanks & Reagrds,
M Adnan

**Comment by Omar1892** [comment]
It is fixed, thank you.
