### ISSUE TITLE
Searchable field for customers who have phone from us.

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1418]
Hi Guys! We propose to implement a system that can be searchable or a special box who semnalize tickets with phones from us. 
In our shop, we give our customers phones from our requisite when they let a phone to repair. 
All is good but we can't search what tickets have a phone from us.
I think it's a better idea for everyone who uses this platform and will be a good benefit for customers when all shop brings with this.
Now we have a problem, we don't know where is our phone because we can't search tickets with a special criteria.

**Comment by Uzair-RepairDesk** [comment]
Hey, @adigsm07  
you can use the custom fields option for tickets and you can add the phone details in the custom field. once you add the phone against the custom field, after creating a ticket you can also search those tickets with phone via search criteria using custom feild
![FIXAPHONERepairDesk-Ticket](https://user-images.githubusercontent.com/22955861/101473185-54af7180-396b-11eb-88ca-9858ed0ab88f.png)
Attached is the KB link for repair custom fields.
https://help.repairdesk.co/knowledgebase/articles/1921693-custom-fields
Hope it helps

Regards,
