### ISSUE TITLE
remove email requirement

### ISSUE THREAD

**Issue by icare-howell** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1419]
Please remove the email requirement for an Inquiry.

**Comment by Uzair-RepairDesk** [comment]
Hey @icare-howell  
Hope you are doing well. thanks for your feedback we have already planned this improvement and it's under development. I will update you here as well once it's live.

Regards,

**Comment by Uzair-RepairDesk** [comment]
For internal Use:
https://repairdesk.atlassian.net/browse/REP-3028

**Comment by Uzair-RepairDesk** [comment]
Hi @icare-howell, Hope you are doing well we have made this improvement live. Now email address is not mandatory while creating an inquiry. 
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks,
