### ISSUE TITLE
Extract info - Popular customers / Popular phone with many repairs.

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1422]
Hi Guys!
I want to extract from my database top 10 customers who are come many times at my shop, also I want to know which phone was popular at repairs. What steps do I need to do for these requirements?

**Comment by Uzair-RepairDesk** [comment]
Hi @adigsm07 
You can check the "Total Revenue bu Customers" report and click on "Revenue" or "Total Profit" to filter the customers with the most revenue/profit. 
If you want to check the most popular repairs, you can go to the "Sales by Item Type" report and apply the filter with type "repairs" and relevant search filters to check the report. 

Please check the screenshots attached below:-

![uzairshah-Total-Revenue-By-Customer](https://user-images.githubusercontent.com/22955861/102306942-3954ef80-3f85-11eb-91b0-fe63dab9b709.png)


![uzairshah-Sales-By-Item-Report](https://user-images.githubusercontent.com/22955861/102306960-407bfd80-3f85-11eb-951e-bc9a6e1bf674.png)

Hope it helps

**Comment by adigsm07** [comment]
Thank you very much Uzair! I will be back with feedback after I will check this category.
