### ISSUE TITLE
Add info to Custom fields on existing ticket and repair task?

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1423]
Odd behavior on some of our test tickets. We are not able to edit the info? They are added via API?

Actually we need to add some of the data for the custom fields via API when they are created.. 

What are we doing wrong?

https://drive.google.com/file/d/19SKjSbDdpZrnWEEtf6iqBBwPKgKoQTw5/view

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk, 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by jphansendk** [comment]
Is there a way to add data to custom fields on an existing ticket if none is entered from start?

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
I hope you are doing well. Your reported issue has been fixed on beta. Please verify at your end on the Beta server(https://app.repaircrm.co/) and do let us know if you have any questions.

Thanks & Regards,
M Adnan

**Comment by jphansendk** [comment]
Yes now it shows.. But the custom fields doesn't show in the once added via API?
<img width="1973" alt="Screenshot 2020-12-17 at 15 01 01" src="https://user-images.githubusercontent.com/68819320/102497404-e5c3ce00-4078-11eb-9beb-4676da9b4bca.png">

This one is manual added..

<img width="1973" alt="Screenshot 2020-12-17 at 15 01 15" src="https://user-images.githubusercontent.com/68819320/102497453-f3795380-4078-11eb-9dbf-af07d42a1d85.png">

We need to be able to add the custom fields via the API or add them to the ticket manually to an already existing ticket..

Sorry for being a pain ;-)

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
I hope you are doing well. Can you please share the Payload of your API? So I will check with the development team why custom fields data is not showing?
Thanks & Regards,
M Adnan

**Comment by jphansendk** [comment]
We need to know what the payload in a POST /ticket request should be, in order for the value of those custom fields to show in the Repairdesk UI.
This is taken from a GET /tickets/xxxxxxxx:

```
                "custom_fields": [
                    {
                        "name": "ibsuiteclaimnumber",
                        "label": "IBSuite Claim Number",
                        "value": "1041242400055137",
                        "order_by": "1",
                        "field_type": "1"
                    },
                    {
                        "name": "orderreferencenumber",
                        "label": "Order Reference Number:",
                        "value": "1575463213905",
                        "order_by": "2",
                        "field_type": "1"
                    },
                    {
                        "name": "ordertrackingnumbert1",
                        "label": "Order tracking number (T1)",
                        "value": "JJTN111111111111111",
                        "order_by": "5",
                        "field_type": "1"
                    },
                    {
                        "name": "returtrackingnumbert2",
                        "label": "Retur Tracking Number (T2)",
                        "value": "JJTN111111111111112",
                        "order_by": "6",
                        "field_type": "1"
                    },
                    {
                        "name": "imeiofdamageddevicetextline",
                        "label": "IMEI of damaged device (TEXT_LINE)",
                        "value": "356573087145815",
                        "order_by": "3",
                        "field_type": "1"
                    },
                    {
                        "name": "deliverymethoddeliverymethod",
                        "label": "Delivery Method (DELIVERY_METHOD)",
                        "value": "Delivery method: F05 - Posti Home Parcel + Return Label",
                        "order_by": "4",
                        "field_type": "1"
                    },
                    {
                        "name": "ordershipmentconfirmationdate",
                        "label": "Order Shipment Confirmation Date",
                        "value": "14 Dec, 2020",
                        "order_by": "9",
                        "field_type": "5"
                    },
                    {
                        "name": "ordercollectiontrackingnumbert3",
                        "label": "Order Collection Tracking Number (T3)",
                        "value": "",
                        "order_by": "7",
                        "field_type": "1"
                    },
                    {
                        "name": "ordercollectionreturntrackingnumbert4",
                        "label": "Order Collection Return Tracking Number (T4)",
                        "value": "",
                        "order_by": "8",
                        "field_type": "1"
                    }
                ],
              
 
```

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
I hope you are doing well. let me check this Payload with our development team and I'll get back to you as soon as I have more information!
Thanks & Regards,
M Adnan

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk ,
I hope you are doing well. Kindly Found our developer comment below.
Please inform the customer that our post API cannot understand the exact payload he gets from GET API. The response is different and the payload for the custom field is different.

Can you please confirm the endpoint which you are using for creating ticket?
Thanks & Regards,
M Adnan

**Comment by jphansendk** [comment]
This is the endpoint we use when creating a ticket: POST https://api.repairdesk.co/api/web/v1/tickets?api_key=
Can you show us how we create a ticket with the custom fields in the body so the value of those custom fields is shown on the ticket in the user interface?

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
I hope you doing well. This is a sample payload of custom fields to create ticket API.
For each device object in the array, you have to set an object in custom fields, in which you have to set the custom fields of that device.
In a respective example, I have set custom fields as
color: gold
size: large

For a device in the device's array.

"customFields": [
{
"color": {
"field_type": "2",
"label": "Color",
"name": "color",
"order_by": "1",
"value": " Gold"
},
"Size": {
"field_type": "2",
"label": "Size",
"name": "Size",
"order_by": "1",
"value": "Large"
}
}
]

Hope it help. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by jphansendk** [comment]
So I tried to create a ticket with the custom field “ibsuiteclaimnumber” to this endpoint: https://api.repairdesk.co/api/web/v1/tickets?api_key=nYxH8G3-jvbg-ckGA-1bhc-MCr46MzPm <https://api.repairdesk.co/api/web/v1/tickets?api_key=nYxH8G3-jvbg-ckGA-1bhc-MCr46MzPm>
 
{
    "summary": {
        "customer_id": "4488729"
    },
    "devices": [
        {
            "staff_comments" : "TESTORDRE",
            "name": "SWAP TEST 233",
            "device": "13327142",
            "task_type": "102",
            "custom_fields": [
                {
                  "ibsuiteclaimnumber": {      
                   "name": "ibsuiteclaimnumber",
                   "label": "IBSuite Claim Number",
                   "value": "1041242400055137",
                   "order_by": "1",
                   "field_type": "1"
                 }
               }
             ]
          }
       ]
    }
 
 
The ticket was created, but it doesn’t show in custom fields in the UI? Any ideas why?

 
The idea is to have it look like this in the UI:

**Comment by jphansendk** [comment]
So I tried to create a ticket with the custom field “ibsuiteclaimnumber” to this endpoint: https://api.repairdesk.co/api/web/v1/tickets?api_key=nYxH8G3-jvbg-ckGA-1bhc-MCr46MzPm
 
{
    "summary": {
        "customer_id": "4488729"
    },
    "devices": [
        {
            "staff_comments" : "TESTORDRE",
            "name": "SWAP TEST 233",
            "device": "13327142",
            "task_type": "102",
            "custom_fields": [
                {
                  "ibsuiteclaimnumber": {      
                   "name": "ibsuiteclaimnumber",
                   "label": "IBSuite Claim Number",
                   "value": "1041242400055137",
                   "order_by": "1",
                   "field_type": "1"
                 }
               }
             ]
          }
       ]
    }
 
 
The ticket was created, but it doesn’t show in custom fields in the UI? Any ideas why?
![image003](https://user-images.githubusercontent.com/68819320/102880244-4c673400-444b-11eb-923a-b5b25ae61441.jpg)

The idea is to have it look like this in the UI:
![image004](https://user-images.githubusercontent.com/68819320/102880262-525d1500-444b-11eb-92d7-126f4544d6d9.jpg)

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
Happy to help with this. You have added custom fields payload inside the Device array, that's why it's not working for you. It should be separate according to the device’s attached like mentioned. Your Payload should be like this.
"devices": [
{
"staff_comments" : "TESTORDRE",
"name": "SWAP TEST 233",
"device": "13327142",
"task_type": "102"
],
"custom_fields": [
{
"ibsuiteclaimnumber": {
"name": "ibsuiteclaimnumber",
"label": "IBSuite Claim Number",
"value": "1041242400055137",
"order_by": "1",
"field_type": "1"
}
}

I hope it helps.
 If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by jphansendk** [comment]
t still doesn’t show in the Custom Field section in the UI when doing that.
 
"devices": [
        {
            "staff_comments" : "TESTORDRE",
            "name": "SWAP TEST 233",
            "device": "13327142",
            "task_type": "102"
        }
    ],
    "custom_fields": [
                {
                   "ibsuiteclaimnumber": {
                        "name": "ibsuiteclaimnumber",
                        "label": "IBSuite Claim Number",
                        "value": "1041242400055137",
                        "order_by": "1",
                        "field_type": "1"
                    }
                }

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
I hope you are doing well. We have created a test ticket on your account using your key and the URL is https://api.repairdesk.co/api/web/v1/tickets?api_key=nYxH8G3-jvbg-ckGA-1bhc-MCr46MzPm using the payload mentioned below.


{
    "summary": {
        "customer_id": "388",
        "signature": ""
    },
    "customFields": [
        {
                    "Color": {
                        "field_type": "2",
                        "label": "Color",
                        "name": "color",
                        "order_by": "1",
                        "value": " Gold"
                    },
                    "Size": {
                        "field_type": "2",
                        "label": "Size",
                        "name": "Size",
                        "order_by": "1",
                        "value": "Large"
                    }
                }
    ],
    "devices": [
        {
            "device": "12229",
            "repairProdItems": [
                {
                    "name": "SIM card tray / Holder",
                    "id": "40440"
                },
                {
                    "name": "Battery Replacement",
                    "id": "40439"
                }
            ],
            "imei": "111111111111111",
            "serial": "",
            "security_code": "9876",
            "status": "Pending",
            "task_type": "2",
            "due_on": "1472122800",
            "price": "116.36",
            "line_discount": "0.00",
            "gst": "23.27",
            "assigned_to": "149",
            "staff_comments": "",
            "public_comments": "",
            "PreConditions": [
                {
                    "name": "Power Button",
                    "result": "0"
                },
                {
                    "name": "Volume Button",
                    "result": "1"
                }
            ],
            "supplied": [
                {
                    "name": "Battery",
                    "result": "1"
                },
                {
                    "name": "Charger",
                    "result": "1"
                }
            ],
            "taxclass": "1047",
            "device_location": "",
            "network": "T-Mobile",
            "Parts": [
                {
                    "product_id": "492565",
                    "supplier": "",
                    "warrenty": "190",
                    "warranty_timeframe": "1",
                    "sku": "090000",
                    "name": "Antenna for iPhone 4S",
                    "quantity": "1",
                    "price": "6.67",
                    "gst": "1.33",
                    "taxclass": "1047"
                }
            ]
        }
    ]
}

**And to get details of the ticket you can use the below URL**
https://api.repaircrm.co/api/web/v1/tickets/2837007?api_key=nYxH8G3-jvbg-ckGA-1bhc-MCr46MzPm

Kindly check at your end and If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnan

**Comment by jphansendk** [comment]
I will send this to our development team.. Please next time do not post our API key in a public forum.. We have a lot of partners that needs to change the key now :-(

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
Sure! I have also hight light above please don't share the API key in Public.
Now kindly reset your API key from the store setting.
Thank you

**Comment by jphansendk** [comment]
I will as soon as I have a response from our involved partners.. They have to be aware of this as well..

**Comment by jphansendk** [comment]
Just tested the one you made - When I click edit the box is empty. :-/
<img width="1973" alt="Screenshot 2020-12-28 at 10 32 19" src="https://user-images.githubusercontent.com/68819320/103205577-2681d980-48fa-11eb-807d-bdf84d42e47f.png">

**Comment by Repairdesk-QA** [comment]
Hi again @jphansendk  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
