### ISSUE TITLE
Info missing on tickets when adding a Trade-in item

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1424]
When adding a trade-in item to a ticket it's not possible to see SKU, color or size on the device?

<img width="1969" alt="Screenshot 2020-12-15 at 14 32 11" src="https://user-images.githubusercontent.com/68819320/102237956-85585380-3ef5-11eb-85f0-a408a40ae94d.png">

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
I hope you are doing well. I have checked your concern on my test account and it's working fine for me. Unfortunately, I am unable to reproduce your issue. Would be great if you can share detailed steps or a video of this issue so we can release a fix during our next release. You can put together a video using Screencastify. Kindly also see the attached screens shots as well.
![Screenshot_179](https://user-images.githubusercontent.com/39614480/102310273-7c669100-3f8c-11eb-9418-dbb5c1f309cc.png)
![Screenshot_180](https://user-images.githubusercontent.com/39614480/102310280-81c3db80-3f8c-11eb-8fcf-750abe512ab8.png)

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Reagrds,
M Adnan

**Comment by jphansendk** [comment]
Here it is: https://drive.google.com/file/d/1Q7HnE2tC2KKYZGoSCvAa4xOo96oqoQMQ/view

**Comment by jphansendk** [comment]
Found it my self.. 
<img width="1914" alt="Screenshot 2020-12-18 at 13 23 55" src="https://user-images.githubusercontent.com/68819320/102614452-8cb97000-4134-11eb-89ca-9576ee6d9c1d.png">
