### ISSUE TITLE
RMA + Inventory 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1430]
When creating an RMA, the inventory will not update the inventory on hand. I have sent a video to fahadimran85@gmail.com

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892 ,
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892,
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards,
M Adnana

**Comment by Omar1892** [comment]
@Repairdesk-QA Have you logged in to my account to see if you can replicate the issue? Because its very real to us that we can't create PO or look for items in our system due to this issue.

**Comment by Omar1892** [comment]
@Repairdesk-QA I already have. This isn't my first time. It has being about 1 year since I have being asking for this issue to be fixed. I have proof of it happening an its messing up my inventory on hand as well as the orders we place for products. So I should be expecting this to never be fixed since this is the same answer I get every single time.

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA 
Can you discuss this with Fahad to find out the exact issue/concern?

**Comment by Omar1892** [comment]
@Repairdesk-QA I already have so many times, that doing it one more time is just a waist of time.
