### ISSUE TITLE
Inventory items not appearing

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1431]
I have sent the video about the times that won't apear in the search box by name and we can't also create a PO due to this issue. Video was sent to fahadimran85@gmail.com

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892 ,
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Reagrds,

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892, 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
M Adnan

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2297

**Comment by Omar1892** [comment]
@Repairdesk-QA Any updates?

**Comment by Repairdesk-QA** [comment]
Hi @Omar1892 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!

**Comment by Omar1892** [comment]
Hello, the issue hasn't being fixed yet. Picture for the items we have in stock are not appearing in our inventory, when creating a PO the system will say that the item doesn't exist in our inventory altho it is in our inventory. 
![Screen Shot 2021-01-20 at 10 59 59 AM](https://user-images.githubusercontent.com/47898011/105225286-35cbff80-5b13-11eb-89a2-21dd0940391d.png)
![Screen Shot 2021-01-20 at 10 57 49 AM](https://user-images.githubusercontent.com/47898011/105225290-3795c300-5b13-11eb-9c3a-c7ddf60bb2a1.png)
![Screen Shot 2021-01-20 at 10 59 07 AM](https://user-images.githubusercontent.com/47898011/105225296-38c6f000-5b13-11eb-9f42-973b5f7e69e3.png)

**Comment by Omar1892** [comment]
Any updates?

**Comment by Repairdesk-QA** [comment]
@Repairdesk-QA FYI
