### ISSUE TITLE
Signatures via POS and via repair tickets problems

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1439]
We are having difficulty with signatures via POS and via repair tickets. Here are the 3 different problems:

1) **Missing signature via POS**
For several weeks and randomly, from the POS, the signature window for customers (and the order confirmation window for us) simply does not appear when we click on "create a ticket". See attached image "missing step".
<img width="937" alt="Missing step" src="https://user-images.githubusercontent.com/40500094/104615069-dbd0c300-5656-11eb-8844-7886af0b0981.png">

This option is not even visible at all and we land directly at the window of the final stage. See "final step" image for the result. No signature is even required. This happens randomly before repair and after repair, sometimes even for both signatures. Here is an example of a post: L-21454 SOS Phone LImoilou.
<img width="940" alt="étape final" src="https://user-images.githubusercontent.com/40500094/104615101-e25f3a80-5656-11eb-92ac-eb4ef0f5e460.png">

2) **Signature in repair tickets**
As of this week, it is impossible for us to take a signature from a created repair ticket. By modifying an existing ticket, click on the field "take signature before repair" or "take signature after repair" and the option "display the basket" and the option "display the general conditions" are not possible selected. The window opens and the mouse lets us believe that it is possible to select one of the two options, but when we click, absolutely nothing happens.
<img width="934" alt="impossible to click" src="https://user-images.githubusercontent.com/40500094/104615895-b1cbd080-5657-11eb-946b-fcbbbcd3208a.png">

3) **No signature possible**
As of today, it is not possible to obtain the signatures of our customers. We have checked the settings (although nothing has been changed since yesterday on our side) and yet none of our stores are able to get their customers to sign. Terminal 1 (for example) is well registered and if we copy and paste the link from the same terminal into a browser, no information is sent.

_------  French: ----
Nous éprouvons des difficultés avec les signatures via le POS et via les billets de réparations. Voici les 3 différents problèmes: 

1) **Signature manquante via le POS**
Depuis plusieurs semaines et de façon aléatoire, à partir du POS, la fenêtre de signature pour les clients (et celle de la confirmation de la commande pour nous) n'apparait simplement pas lorsque nous cliquons sur "créer un billet". Voir image en pièce jointe "étape manquante". 
<img width="937" alt="Missing step" src="https://user-images.githubusercontent.com/40500094/104615150-f145ed00-5656-11eb-9a9d-d2bdac521f05.png">

Cette option n'est même pas visible du tout et nous atterrissons directement à la fenêtre de l'étape finale. Voir image "étape finale" pour le résultat. Aucune signature n'est même demandée. Cela se produit de façon aléatoire avant la réparation et après la réparation, parfois même pour les deux signatures. Voici l'exemple d'un billet: L-21454 SOS Phone LImoilou.
<img width="940" alt="étape final" src="https://user-images.githubusercontent.com/40500094/104615160-f4d97400-5656-11eb-8d58-ed66146579a6.png">

2) **Signature dans les billets de réparation**
Depuis cette semaine, il nous est impossible de prendre une signature à partir d'un billet de réparation créé. En modifiant un billet existant, cliquer sur le champ"prendre signature avant réparation" ou "prendre signature après réparation" et l'option "afficher le panier" et l'option "afficher les conditions générales" sont impossible a sélectionné. La fenêtre s'ouvre et la souris nous laisse croire qu'il est possible de sélectionner une des deux options, mais lorsque nous cliquons, absolument rien ne se passe. 
<img width="934" alt="impossible to click" src="https://user-images.githubusercontent.com/40500094/104615940-c0b28300-5657-11eb-8654-148d19d97b58.png">

3) **Aucune signature possible**
Depuis aujourd'hui, il est impossible d'obtenir les signatures de nos clients. Nous avons vérifié les réglages (malgré que rien n'ait été modifié depuis hier de notre côté) et pourtant, aucune de nos boutiques n’est en mesure de faire signer ses clients. Le terminal 1 (par exemple) est bien enregistré et si nous copions-collons le lien du même terminal dans un navigateur, aucune information ne s'envoie._

**Comment by Uzair-RepairDesk** [comment]
Hi @JessicaSOS 
Thank you for notifying this. Our QA representative will check it in detail and revert back to you early next week. Thanks.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards, 
M Adnan

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2387

**Comment by JessicaSOS** [comment]
thank you

**Comment by Repairdesk-QA** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!

**Comment by JessicaSOS** [comment]
yes fixed thank you !

**Comment by JessicaSOS** [comment]
PLEASE REOPEN
Signatures are no longer displayed at all since today when we create a ticket via the POS and this, for all tickets created. The same problem is present for the signature after repair during the checkout.

--
Les signatures ne s'affiche plus du tout depuis aujourd'hui lorsque nous créons un billet via le POS et ce, pour tous les billets créé. Le même problème est présent pour les signature après réparation lors du checkout.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
M Adnan

**Comment by JessicaSOS** [comment]
Its seems to be settled today. Thank you
