### ISSUE TITLE
Ticket number resetting after estimate conversion

### ISSUE THREAD

**Issue by techm89** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1440]
Everytime a customer clicks on approval on an estimate, it auto convert to a ticket. This ticket numbers goes back to 0-1. Then every new ticket I am creating in POS goes 0-2, 0-3, 0-4 and is messing up everything. I need to manually change the numbers for each ticket for it to work properly again.

**Comment by Repairdesk-QA** [comment]
Hey @techm89, 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hey @techm89,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!
Thanks & Regards,
M Adnan

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2408

**Comment by Zain-javed** [comment]
Hi @techm89,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any questions.

Thanks
M.Zain

**Comment by Repairdesk-QA** [comment]
Hi @techm89,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any questions.

Thanks
M.Zain
