### ISSUE TITLE
problem with manufacturers and devices in inventory items

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1448]
Many inventory items no longer have the manufacturers and the devices for which they are associated. I have had this problem for a long time, but I didn't know where it came from. I corrected ALL the items in November 2020. However, I still see that this problem is present, but not on all the items. I believe it is present on the items after we have received new quantities. This is the only recurrence that I observe. It's rather annoying since we deprogram the items themselves without leaving a precise trace in the history. See also item: # 13133, # 13117, # 11080, # 10459, etc ...
<img width="936" alt="Manufacturer and Device" src="https://user-images.githubusercontent.com/40500094/105062297-727ef480-5a48-11eb-95bf-fb5385a28f78.png">
<img width="939" alt="historique" src="https://user-images.githubusercontent.com/40500094/105062303-7448b800-5a48-11eb-9e35-f80f82b4184b.png">

----French : ----
Plusieurs items d'inventaires n'ont plus les manufacturiers ainsi que les appareils pour lesquels ils sont associés. Ça fait longtemps que j'ai ce problème, mais je ne savais pas d'où il provenait. J'avais corrigé TOUS les items en novembre 2020. Pourtant, je constate toujours que ce problème est présent, mais pas sur tous les items. Je crois qu'il est présent sur les items après que nous ayons réceptionné de nouvelles quantités. C'est la seule récurrence que j'observe. C'est plutôt tannant puisque nous les items se déprogramment par eux même sans laisser de trace précise dans l'historique. Voir également item: #13133, #13117, #11080, #10459, etc...

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892, 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hye @JessicaSOS,
I hope you are doing well.

I have checked your concern but unfortunately, I am unable to reproduce the issue on my end. If you face this issue again it would be great if you can share a video so we can release a fix during our next release. 
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Thanks & Regards,
Ayesha Aamer

**Comment by JessicaSOS** [comment]
I gave you several examples and I corrected them all manually. I mentioned to you that these were items that we had received a new quantity in inventory, but it was only a lead. the problem may not be directly related to adding new inventory quantity to the items. It's up to you to find the source of the problem. I still have this problem and it is very unpleasant. Please see items 13742, 13288, 12835, 12584, 12089, 11880, and many others. I haven't fixed them so you can spot the problem.

--
 Je vous ai donné plusieurs exemple et je les ai tous corrigés manuellement. Je vous ai mentionné que c'était des items que nous avions réceptionné une nouvelle quantité en inventaire, mais ce n'était qu'une piste. le problème n'est peut-être pas directement lié a l'ajoue de nouvelle quantité d'inventaire dans les items. À vous de trouver la source du problème. J'éprouve toujours se problème et c'est très désagréable. Merci de regarder les items 13742, 13288, 12835, 12584, 12089, 11880, et plusieurs autres. Je ne les ai pas corrigé afin que vous puissiez repérer le problème.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
I hope you are doing well. Thank you for your patience but I have checked this issue on the specific item id(13742) you have mentioned earlier and get to know that the manufacturer is removed by one of your employee as you can see in the reference screenshot attached below. Can you please investigate this on your end?

I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks,
Zain
![image (2)](https://user-images.githubusercontent.com/39614480/106857309-b11bdc80-66e1-11eb-8e19-fd4d7c6f490b.png)
![image (1)](https://user-images.githubusercontent.com/39614480/106857311-b24d0980-66e1-11eb-8243-bf69de9fc6c0.png)

**Comment by JessicaSOS** [comment]
Hello, 
We can indeed see in the history that the item has been deleted by Simon. On the other hand, Simon has no access to modify the manufacturers. See a screenshot of the settings and another connected with its user.
So he was not the one who made these changes. Thank you for further research.
![manufacter simon](https://user-images.githubusercontent.com/40500094/106919681-5cc02f00-66d8-11eb-858e-a9bddecf57d6.jpg)
<img width="936" alt="setting" src="https://user-images.githubusercontent.com/40500094/106919696-5f228900-66d8-11eb-924f-9244eab610e4.png">

--french---

Bonjour,
Nous pouvons effectivement voir dans l'historique que l'item a été supprimé par Simon. Par contre, Simon n'a aucun accès à modifier les manufacturiers. Voir une capture d'écran des réglages et une autre connecté avec son utilisateur. 
Ce n'est donc pas lui qui a effectué ces changements.  Merci d'approfondir vos recherches.

**Comment by Repairdesk-QA** [comment]
> Hello,
> We can indeed see in the history that the item has been deleted by Simon. On the other hand, Simon has no access to modify the manufacturers. See a screenshot of the settings and another connected with its user.
> So he was not the one who made these changes. Thank you for further research.
> ![manufacter simon](https://user-images.githubusercontent.com/40500094/106919681-5cc02f00-66d8-11eb-858e-a9bddecf57d6.jpg)
> <img alt="setting" width="936" src="https://user-images.githubusercontent.com/40500094/106919696-5f228900-66d8-11eb-924f-9244eab610e4.png">
> 
> --french---
> 
> Bonjour,
> Nous pouvons effectivement voir dans l'historique que l'item a été supprimé par Simon. Par contre, Simon n'a aucun accès à modifier les manufacturiers. Voir une capture d'écran des réglages et une autre connecté avec son utilisateur.
> Ce n'est donc pas lui qui a effectué ces changements. Merci d'approfondir vos recherches.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS,
Thanks for the update on this. We will investigate it internally and let you know once we have further information on it.

Please let me know if there’s anything else I can do for you.

Thanks,
Zain

**Comment by JessicaSOS** [comment]
Same thing here. The problem is still here.
I work to report problems to you and close tasks to you without even asking you about the problem. This is not resolved so please reopen

example 13547, the manufacturer is no longer there but the device is. How is it possible ?

**Comment by JessicaSOS** [comment]
It will be 1 year since I postpone this problem. I feel like if I don't follow up you are doing nothing and paying no attention to my reported issues. After several months sometimes, you just tell me that you don't have this problem on your end. It takes me a while to list all the issues with images and translate the text into 2 languages, while keeping track of me to get the job done.

Here are items that I have not corrected so that you can see the problem and the history of the item: 9148, 2258 and 2259. Thank you for coming back to me soon!

--

Cela va faire 1 an que j'ai reporter ce problème. J'ai l'impression que si je ne fait pas de suivi, vous ne faite et rien et ne porter aucune attention à mes problèmes reportés. Après plusieurs mois parfois, vous faite simplement me dire que vous n'avez pas ce problème de votre côté. Cela me prend du temps de répertorier tous les problèmes avec des images et traduire le texte en 2 langues , tout en me gardant un suivi afin que le travail soit effectué. 

Voici des items que je n'ai pas corrigé afin que vous visualisiez le problème et l'historique de l'item: 9148, 2258 et 2259. Merci de me revenir rapidement !

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

Sorry for the delay and inconvenience.
We will investigate it internally and let you know once we have further information on it.
Your patience means a lot to **_RepairDesk._**

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

I have checked your concern and have the following findings.
We will take **_item#9148_** as an example.

**_Item #9148_** first has been **_removed_** its Manufacturer from **_Apple_** on **_21 Dec, 2020_** on **_Store Levis_**
![image](https://user-images.githubusercontent.com/39614480/145573731-8964db1d-681b-4a68-b1ec-ceb5842d99d8.png)

**_On 19 Jan, 2021_** the same item (9148) has been **_set its Manufacturer to Apple_** on **_Store Limoilou_**
![image](https://user-images.githubusercontent.com/39614480/145573960-55caa846-6f1b-485d-b51a-a7ae665efed1.png)

**_On 25 Jan, 2021_** the same item (9148) has been **_removed its Manufacturer from Apple_** on **_Store Levis_**
![image](https://user-images.githubusercontent.com/39614480/145574123-d1ee97b2-30df-4781-9fa5-ca84d33b2b14.png)

I hope this will help you to understand the flow done by your store members.
If there is anything else I can do for you, please do not hesitate to let us know.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain

**Comment by JessicaSOS** [comment]
If the ticket is still open, it is not fixed. Problems do not resolve themselves. If you didn't do anything, the problem is still there. In this case, it is an intermittent and always present problem.

I still have this problem on my side, Please reopen the ticket.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

We have checked from backend and have explained this in the comment. 
https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/1448#issuecomment-990934668

Priorly, our hiding/displaying manufacturers, devices were **_businesswise_** in **_RepairDesk_**. It means, if we hide a manufacturer from store1 it will hide it from other stores too.
That's what is done with your inventory items. Your inventory items have removed its Manufacturer from Store Levis & then add to Store Limoilou & then again removed on Store Levis.
That's why is not visible in any store.

We have done an improvement against this with **_Store wise._** It means, if you want to enable or show a Manufacturer/device/category on Store1 & wants to hide it on Store2, you can do this. But this functionality is available to only some of our customers(who wants it). If you want us to enable this for you, kindly let us know & will surely guide you about the new functionality.

Waiting for your kind response!

**_Thanks & Regards,_**
Quratul Ain

**Comment by JessicaSOS** [comment]
Hello,
I would be interested in this option, but I would like to know before activating it if it is possible to withdraw access to employees? In the privileges of the stations, the access not given to them, therefore they are not supposed to be able to modify this ... See photo.
![change manufacturer](https://user-images.githubusercontent.com/40500094/146975074-33db73b7-17ff-42f9-85d4-d48f105144c6.jpg)

---

Bonjour,
Je serais interessé par cette option, mais j'aimerais savoir avant de l'activer s'il est possible de retirer l'accès aux employés ? Dans les privilèges des postes, l'accès ne leur ai pas donné, donc ils ne sont pas suposé être en mesure de modifier cela... Voir photo.

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

Yes, you can manage the access to employees at your convenience.
If you are interested in this setting, kindly let us know.
It would be better to have a demo of these settings before activating on to your store.
Our support team is always ready for that.
You can use our live chat feature or if you want to schedule a call with any of our support agents, you can use the following links:

Fahad Imran, Manager Customer Success and Support
https://calendly.com/fahadimranI 

Faizan Zaheer
https://calendly.com/faizan-zaheer20111/trainings?month=2020-09

Danish Hassan, Customer Success and Support
https://calendly.com/danishhassan

It would lovely to help you and get you out of the troubles you are facing.

**_Regards,_**
Quratul Ain

**Comment by JessicaSOS** [comment]
and how to withdraw access to employees? They don't already have privileges access so I don't understand why they have access right now. Please answer me in writing, it's easier for me with Google translate.

--
 et comment retirer l'accès aux employés? Ils n'ont déjà pas accès dans les privilèges donc je ne compremd pas pourquoi ils ont accès en se moment. Merci de me répondre par écrit, c'est plus facile pour moi avec Google traduction.

**Comment by Repairdesk-QA** [comment]
That might be issue with the permissions @JessicaSOS.
I will check this at my end and will update you shortly here.

Thansk for your explanation and time!

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

We have checked your issue according to the previous details you have mentioned and have prepared test data for that but unfortunately, we have not seen any manufacturer removed from the inventory item.
We are still looking into it and will update you shortly as soon as the issue reproduces.
If you notice any action or case regarding this issue, kindly share it with us. That might be helpful to track the issue.

Thanks for your patience and time.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

I would like to inform you that we have checked our test data prepared against the issue you have reported, but we have not seen any Manufacturer removed from the inventory item.
Kindly let us know if you are facing this issue on recent inventory items.
Waiting for your kind response!

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_** https://repairdesk.atlassian.net/browse/RB-4396

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

I would like to inform you that we have found your issue and have fixed it.
Kindly Set Manufacturers for the items you have mentioned**(**for example ID#9148**)** and ask the same Employee(I think he was Simon) to open the item and hit the save button.
The Manufacturer will be there.

Kindly verify at your end and do let us know if you have any questions or issues.
Waiting for your kind response.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @JessicaSOS, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Ayesha Aamir

**Comment by JessicaSOS** [comment]
REOPEN PLEASE

Simon actually no longer has access to the manufacturer, which is perfect. What is the option to check or uncheck in the privileges that gives this result?

Simon is an employee of the Lévis store only. He therefore does not have access to the limoilou store. Only David has made adjustments in certain products without having to modify the manufacturer. However, the manufacturer of these items is still withdrawing.

You also asked me if there were more recent items with the same problem. Here they are if you want to verify that the problem is indeed caused by an employee modifying a product. I have not modified the items yet but the problem is still present on these items: 13683, 13454, 13233, 13158.

--

Simon n'a effectivement plus accès au fabriquant, ce qui est parfait. Quel est l'option a cocher ou décocher dans les privilège qui donne ce résultat?

Simon est un employé du magasin de Lévis uniquement. Il n'a donc pas accès au magasin de limoilou. Seul David a fait des ajustements dans certain produit et ce, sans avoir modifier le manufacturier. Cependant, le manufacturier de ces items se retire encore.

Vous m'aviez aussi demandé s'il y avait des items plus récent avec ce même problème. Les voici si vous souhaitez vérifier que le problème provient bel et bien de la modification d'un produit par un employé. je n'ai pas modifier les items encore mais le problème est toujours présent sur ces items: 13683, 13454, 13233, 13158.
