### ISSUE TITLE
Costumer Self Check In + Mobile Number + Email

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1451]
When we have a costumer due a self check in, for some reason the information will not be transferred over to the POS system. This information is the Mobile number, Phone number and email. What we only get is the costumer name and last name.

**Comment by Repairdesk-QA** [comment]
Hey @Omar1892,
I hope you are doing well. Sorry for the continued inconvenience. Your reported issue has been fixed. Please verify at your end and do let us know if you have questions.
Thanks & Regards,
M Adnan
