### ISSUE TITLE
Bug/problem with signature (customer facing display)

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1452]
Hello, it is the third time when I post this problem and nothing happened.  Guys, the signature is small and it's made from dots I think.  So in conclusion is not clear and enough to be oke.  I'm using an iPad for signature, I tested the screen for this tablet and don't have any problems. Can you check on your systems the signature to show me your examples?

Link with video -- > https://www.youtube.com/watch?v=_JRW2HBNyks

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07,
Sorry for the inconvenience. Thank you for your patience and understanding through some of the bumps in the road – I am working with our product team to make sure we solve these problems more quickly and avoid them going forward.
Thanks & Regards, 
M Adnan

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07,
I have checked on my test account, it is the current functionality of our software, also the signature depends on the printer and the size of the paper you are using and at the moment we are not working on our iPad app development or bug fixing.  

If you still have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Thanks & Regards,
Ayesha Aamer

**Comment by adigsm07** [comment]
Actually the signature it's viewed just on receipt, when we make checkout on invoice is not appear the signature, but in app is taken.

**Comment by adigsm07** [comment]
> Hey @adigsm07,
> I have checked on my test account, it is the current functionality of our software, also the signature depends on the printer and the size of the paper you are using and at the moment we are not working on our iPad app development or bug fixing.
> 
> If you still have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
> 
> Thanks & Regards,
> Ayesha Aamer

Actually the signature it's viewed just on receipt, when we make checkout on invoice is not appear the signature, but in app is taken.

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07, 
I hope you are doing well. Sorry for the delay but I was pulled away and caught up with work. Can you please connect on live chat with our support guy so that he can assist you via screen share. 
Thanks & Regards, 
Ayesha Aamer

**Comment by adigsm07** [comment]
https://www.youtube.com/watch?v=2OcXVVl8MA0&feature=youtu.be

**Comment by Repairdesk-QA** [comment]
> Actually the signature it's viewed just on receipt, when we make checkout on invoice is not appear the signature, but in app is taken.

Hey @adigsm07,
I hope you are doing well. I have just checked the above-reported scenario on your account and found that the trigger to **show the signature on the Invoice** is OFF on your account. I have just turned it ON on your account and verified after creating a test invoice, signatures are now displaying, reference screenshots are attached below. Can you give it another try?

Thanks,
M.Zain

![adi cus](https://user-images.githubusercontent.com/39614480/106461798-150e8d00-64b7-11eb-99b0-26345a3812a0.png)
![adi cus1](https://user-images.githubusercontent.com/39614480/106461819-1a6bd780-64b7-11eb-9c77-bd6f3ad22d4a.png)

**Comment by adigsm07** [comment]
Thanks,  it's working after cleared cache from browsers.
