### ISSUE TITLE
Sub Categories

### ISSUE THREAD

**Issue by NickSteinbeck** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1455]
When an inventory item is assigned a sub category the item no longer shows that it is assigned to a category on the Inventory Summary Report. This causes the item not to be included in the filter feature to drill down by category.

**Comment by Repairdesk-QA** [comment]
Hey @NickSteinbeck, 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards,

**Comment by Repairdesk-QA** [comment]
Hey @NickSteinbeck, 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up.

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!
Thanks & Regards,
Ayesha

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2472

**Comment by Repairdesk-QA** [comment]
Hey @NickSteinbeck,
Ayesha here. I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any question.
Thanks!
