### ISSUE TITLE
Add the ability to check customers out on another computer without opening a separate cash register

### ISSUE THREAD

**Issue by thecellplug** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1457]
at this time we only have one cash register set up but we have 3 tech computers in the back. Is there a way to keep the register pop from coming up. We only want to keep one but sometimes we need to cash out trade ins from another computer and the front counter pays the customer out. is that possible?

**Comment by Uzair-RepairDesk** [comment]
Hi @thecellplug 

If you want to use one cash register but with different computers, we have the functionality available to "Join the register" even if you login with a separate computer. 
If the same user signs it on another computer, the system asks to "Continue using the same shift" 
![image](https://user-images.githubusercontent.com/22955861/105667119-90db6900-5efc-11eb-9202-ffefd7db6101.png)

If a different user signs in and access to use the same cash register, the system allows you to "Join" the shift with the same cash register. 

![image](https://user-images.githubusercontent.com/22955861/105667252-bbc5bd00-5efc-11eb-9a42-a372e6e56969.png)

Please check the following knowledgebase article for your understanding:-
https://help.repairdesk.co/knowledgebase/articles/810153-how-to-use-the-cash-register-module-in-repairdesk

If you have any further questions, please feel free to ask. Thanks

**Comment by Repairdesk-QA** [comment]
Hello @thecellplug,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
