### ISSUE TITLE
Invoice option enabled even though item not in stock 

### ISSUE THREAD

**Issue by danmurari** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1458]
Hello Team 

we having issues as my employees can invoice any products even though units are not in stock. 

We mainly invoice only through create invoice option ( we don’t use POS) and it’s creating a large data base of negative stock . 

We are about to take stock so fix will be really appreciated.

Thanks
Dan

**Comment by Uzair-RepairDesk** [comment]
Hi @danmurari 

We recommend POS screens to sell items (create invoices). We have also a trigger available under Store Settings > Module Configurations > POS > Hide Out of stock items from POS product listing. If you enable it, users are not able to view out of stock items to sell. 
![RepairDesk-Pos-Config](https://user-images.githubusercontent.com/22955861/105666609-7a80dd80-5efb-11eb-8cce-62132215c28f.png)


If you still allow displaying out of stock items and if you have stock available and you see out of stock items in the system, you can also make an adjustment "Increase Quantity" before you sell it. 

![St-Louis-POS](https://user-images.githubusercontent.com/22955861/105666748-c2a00000-5efb-11eb-8079-b2ab2ed1b125.png)

Hope it helps

**Comment by Repairdesk-QA** [comment]
Hello @danmurari,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
