### ISSUE TITLE
Add data to custom fields on already added ticket

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1461]
How can I add data to our custom fields on a already created ticket?

**Comment by Uzair-RepairDesk** [comment]
Hey, @jphansendk  hope you are doing well, yes you can update a custom field via manage ticket section by editing the specific ticket. under the custom field column, click on **view all** to update the custom field.
Hope this helps.

Regards,

**Comment by jphansendk** [comment]
Can you show me where? I dont see the "view all"?
<img width="1694" alt="Custom fields editing" src="https://user-images.githubusercontent.com/68819320/105828658-af586780-5fc3-11eb-8b1e-5191f0b70689.png">

**Comment by Uzair-RepairDesk** [comment]
Have you selected the repair category, because based on that custom fields are populated?
Have you added custom fields against the repair category?
OR
you can connect with over live chat, over support executive will help you out in detail.

**Comment by jphansendk** [comment]
yes sir - but the custom fields are not filled when the ticket is created via the API. We need to fill out the custom fields after the ticket is created? 
<img width="1985" alt="Screenshot_2021-01-26_at_10_55_08" src="https://user-images.githubusercontent.com/68819320/105830766-31499000-5fc6-11eb-8091-642ea87ff162.png">

**Comment by Uzair-RepairDesk** [comment]
@jphansendk  kindly connect on live chat so that the support executive can understand your issue in detail and we can resolve it.

Regards,

**Comment by jphansendk** [comment]
I will.. TIA
