### ISSUE TITLE
Physical Location not showing when adding part to Ticket

### ISSUE THREAD

**Issue by CaseyFMC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1463]
Screencast - https://drive.google.com/file/d/1l8hww-m_Vupo3lVfMeh0IQ-ahrRCVotg/view

When selecting an adittional part to be used in a ticket, the physical location field shows no value. Critical bug for us as we have multiple part stores.

Thank you!

**Comment by Repairdesk-QA** [comment]
Hey @CaseyFMC,
I hope you are doing well. Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

Thanks & Regards,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
For Internal Use:
https://repairdesk.atlassian.net/browse/RB-2514

**Comment by Repairdesk-QA** [comment]
Hey @CaseyFMC,
Ayesha here. I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any question.
Thanks!

**Comment by Repairdesk-QA** [comment]
Hi again @CaseyFMC - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
