### ISSUE TITLE
Custom fields not editable from Manage Tickets

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1464]
We are running some tests from the API.. And for some reason I suddenly can not edit the custom fields.. This is what I get when I click "View All"?

<img width="1814" alt="Custom_fields_veiw_all_bug" src="https://user-images.githubusercontent.com/68819320/106257477-e1183b00-621c-11eb-9d19-99e02af6eb37.png">

**Comment by Uzair-RepairDesk** [comment]
Hi @jphansendk 

Happy to help you with your question. Custom fields are always set on behalf of a specific repair category. Once you select a specific category, custom fields come up to update on the edit ticket screen. Once you receive the ticket info with API you can make sure that you get the category information or you can go to the edit ticket page to select the category, device, and device issue to update custom fields accordingly. 

Hope this helps.
