### ISSUE TITLE
MS Integration out of stock

### ISSUE THREAD

**Issue by Shane-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1465]
MS integration not showing availability of items or accounting for out of stock.

**Comment by Shane-RepairDesk** [comment]
![Capture](https://user-images.githubusercontent.com/60683772/106335797-7df9c900-625b-11eb-9d1f-bb00b0f952ad.JPG)

**Comment by Shane-RepairDesk** [comment]
![snippet2](https://user-images.githubusercontent.com/60683772/106335817-894cf480-625b-11eb-8765-982739016298.JPG)

**Comment by Shane-RepairDesk** [comment]
Verified on demo account as well.

**Comment by Repairdesk-QA** [comment]
Hey @Shane-RepairDesk,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-2526

**Comment by Repairdesk-QA** [comment]
Hey @Shane-RepairDesk,
Ayesha here. I hope you are doing well. I have checked the above reported issue with our development team and found that this issue is occurring due to the service provider API's call from the Mobile Sentrix side. We have forwarded the request to them. I'll get back to you as soon as I have more information.

**Comment by Repairdesk-QA** [comment]
Hey @Shane-RepairDesk,
I hope you are doing well. I believe this issue has been fixed in the recent update. Can you give it another try?
I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Thanks,
Ayesha Aamer
