### ISSUE TITLE
Estimates Module Attachements

### ISSUE THREAD

**Issue by istationonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1467]
Unable to attached files in estimates

Always greyed out

<img width="747" alt="Screenshot 2021-01-31 at 16 12 51" src="https://user-images.githubusercontent.com/59316784/106390234-503d8d00-63df-11eb-8e89-980309c68d11.png">

**Comment by Repairdesk-QA** [comment]
Hey @istationonline, 
I hope you are doing well. I have checked the above mentioned scenario and its working fine on my end, attached is the screenshot. It seems to be an account specific issue. Can you please connect with our support team on live chat so that we can further investigate the issue.
Thanks & Regards,
Ayesha Aamer

![Estimate upload attachment](https://user-images.githubusercontent.com/39614480/106425091-22ab1f00-6485-11eb-94ca-7c87686f5616.png)

**Comment by Repairdesk-QA** [comment]
Hi again @istationonline  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by istationonline** [comment]
Still the same we can’t add attachement to the estimate module

Regards

iStation Team







This e-mail may contain confidential and/or privileged information. It is for the exclusive use of the intended recipient(s). If you are not the intended recipient(s), you must not use, distribute, copy or take any action in reliance on it, since to do so is strictly prohibited and may be unlawful. If you have received this e-mail in error, please return it to the sender immediately and delete it from your system. E-mail messages are not secure and attachments may contain software viruses which may damage your system. Whilst we have taken every reasonable precaution to minimise this risk, we cannot accept any liability for any damage which you sustain as a result of these factors. You are advised to carry out your own virus checks before opening any attachment. Any views or opinions expressed in this e-mail are solely those of the author and do not represent those of iStation unless otherwise stated. 

Registered Office: iStation Ltd, 27 Wellington Square, Stockton, Cleveland, TS18 1RG.
Registered in England number 9206740.

**Comment by Repairdesk-QA** [comment]
Hey @istationonline,
I hope you are doing well. 
Definitely strange! I have checked your concern with the product team and it's working fine on your account as well, screenshot attached below. I think there’s some wonky data hung up in your browser. Can you try clearing your cache, cookies, and logout & login again in the software? 
If this doesn’t work or you have more questions, just let me know and I’ll be happy to help! Thanks!
Regards,
Ayesha Aamer

![istation](https://user-images.githubusercontent.com/39614480/108346523-4a2e1580-7201-11eb-81b8-eb6ad83b8858.png)

**Comment by Repairdesk-QA** [comment]
Hey @istationonline,
Ayesha here. I hope you are doing well. Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up. Thanks!
