### ISSUE TITLE
Edit template mail.

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1469]
Hi Guys, I want to edit my template mail but I don't find anything in language template editor.
I just want to translate this into my country language.

![rrtemplate mail](https://user-images.githubusercontent.com/65545272/106460416-023a8f00-649c-11eb-843c-26e6b42904fe.png)

**Comment by Uzair-RepairDesk** [comment]
Hey @adigsm07 
We have already given an editor within the template that allows you to change the text according to your language. You can go to Store Settings > Email & Notification > Edit Template > You can update the text in the editor > Save Changes

Please check the screenshot attached

![image](https://user-images.githubusercontent.com/22955861/106553288-ec2fdb80-653a-11eb-9cbd-0a19b68fce77.png)

Hope it helps

**Comment by adigsm07** [comment]
Thank you very much, I succeeded to update my template.
