### ISSUE TITLE
Allow User to Select "Won" In Leads

### ISSUE THREAD

**Issue by screenfixing** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1472]
When a customer is won but doesn't pass through the system, perhaps correctly, we need to be able to change the status to "Won". I realize how they become "Won" in the system but we'd like to be able to select it as well.

**Comment by Uzair-RepairDesk** [comment]
Hi Nate,
Currently, the system marks the "Won" status when you convert a lead into a repair ticket. It means that the lead has actually closed. If you don't want to create a ticket but want to place a specific status, the workaround is that you can create a custom status of lead to mark it. 
You can manage the lead statuses under Store Settings > Order Status > Lead Status > New

Hope it helps.
