### ISSUE TITLE
Cannot PUT or PATCH to existing tickets

### ISSUE THREAD

**Issue by spenco100** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1477]
I am working on a RepairDesk integration using your open API. The only documentation I've found on it is [here](https://help.repairdesk.co/knowledgebase/articles/1189105-public-api)

Using that information, I'm trying to be able to add a note to a ticket using PATCH, as described in your documentation. When I PATCH to 
```https://api.repairdesk.co/api/web/v1/tickets/3280051?api_key=${MY_KEY}```
with a body of
```
{ 
	"op": "add",
	"path": "/devices/0/notes/1", 
	"value": {
        "tittle": "added an internal note",
        "id": "2946259",
        "type": 0,
        "user": "Spencer Speas",
        "msg_text": "Note goes here",
        "image": "https://app.repairdesk.co/themes/repairdesk/img/img.jpg",
        "created_on": 1612465546,
        "devicename": " ",
        "deviceId": ""
    }
}
```
This is an attempt to add a new note to the notes array, which when using a GET request, I've found is at the root of the response's body.

PATCH to this url with this body just returns the same as GET (the ticket, without my changes), while PUT responds with this:
```
{
    "success": true,
    "statusCode": 200,
    "message": "Ticket was Updated successfully",
    "data": {
        "id": 3280051,
        "order_id": "001",
        "customer_id": 0,
        "ticketLabels": null,
        "devicesRepairItems": null,
        "notification_message": "{\"errors\":[\"You must include which players, segments, or tags you wish to send this notification to.\"]}"
    }
}
```
But my ticket is never successfully updated. I'd imagine that the "notification_message" error is only related to OneSignal, which I'm guessing your backend uses to send SMS/email notifications between RepairDesk user's when a ticket is assigned to a person.

Please help me understand how I should properly going about updating an existing ticket, especially to add a note, using your open API.

P.S. it would also be awesome if I could pull the "modified_on" data with a GET to /tickets, instead of only receiving that data when I GET a specific ticket (/tickets/:TICKET_ID)

**Comment by Repairdesk-QA** [comment]
Hey @spenco100,
First of all the endpoint https://api.repairdesk.co/api/web/v1/tickets/3280051?api_key=${MY_KEY} you are using is just for updating ticket items. you cannot add notes with this endpoint. The above endpoint requires 4 basic objects to create/update tickets.
"devices" : {},
"items" : {},
"summary":{},
"customFields" : {}
there is no option for add note.
However, you can add notes by the following endpoint
---------------------
URL :
https://api.repaircrm.co/api/web/v1/ticket/addnote
Request method: POST
There are two types of notes you can save with each line item
 you have to pass deviceId which is basically the line item id to link notes with that specific device
you can find deviceId from the GET request of /ticket -> "summary" : {"id" : [line_item_id]}}
Secondly type = 1 means Diagnostic notes,   type = 0 means Internal notes
For Internal notes
{
  "id" : "3280832",
  "employee_id" : "20578",
  "deviceId" : "65442460",
  "device_issue" : "Keypad Replacement",
  "device_name" : "BlackBerry Bold 9900",
  "type" : "0",
  "assigned_to" : "20578",
  "order_id" : "T-403",
  "note" : "internal note test",
  "employee_name" : "Fred"
}
For diagnostic notes
{
  "employee_name" : "Fred",
  "order_id" : "T-403",
  "id" : "3280832",
  "assigned_to" : "20578",
  "device_name" : "BlackBerry Bold 9900",
  "employee_id" : "20578",
  "device_issue" : "Keypad Replacement",
  "type" : "1",
  "note" : "diagnostic note test",
  "deviceId" : "65442460"
}

Thanks,
Saif Ali

**Comment by spenco100** [comment]
Thanks for the quick response and full explanation. 

I can successfully add notes to tickets, but I have 2 new problems with the newly created notes. After creating the note, when I GET the /ticket/:ticket_id, or opening the ticket from RepairDesk itself, I see the ticket is created by the owner's name and id/ 

Even when I've set the "employee_id", "assigned_to", and "employee_name", I only see the owner's name on the ticket, not the user from the employee_id.

Thank you again for your help on this

**Comment by Repairdesk-QA** [comment]
Can you explain more with the payload you sent to which API? or provide us your credentials and ticket number as reference to check it further

**Comment by Repairdesk-QA** [comment]
The employee_id and employee name is the one who will enter the note against that ticket. there is no link with the creator of that ticket. creator of the ticket can be any other employee

**Comment by Repairdesk-QA** [comment]
Hi again @spenco100  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by spenco100** [comment]
I apologize! I am not yet situated completely, but another client's project has kept me busy this past week. Can I reopen this ticket this coming Monday (22nd), or should I create a new issue then?

**Comment by Repairdesk-QA** [comment]
Hey @spenco100,
I hope you are doing well. Kindly reopen the same ticket & please provide details regarding your concern. Thanks!
Regards, 
Ayesha Aamer
