### ISSUE TITLE
Customers' SIGNATURES NOT SHOWING ON THE TECKET ANY LONGER

### ISSUE THREAD

**Issue by UNIFIX1** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1478]
Customers' SIGNATURES NOT SHOWING ON THE TECKET ANY LONGER

<img width="769" alt="Screen Shot 2021-02-04 at 7 03 32 PM" src="https://user-images.githubusercontent.com/78572530/106971468-02958d00-671d-11eb-88ed-b5ea5855fb0a.png">

**Comment by Repairdesk-QA** [comment]
Hey @UNIFIX1,
It looks like this bug has been resolved! Can you please refresh your browser and let me know if you are able to print the signature in the Receipt? 

If there’s anything else I can do for you please let me know.

Thanks,
Zain

**Comment by Repairdesk-QA** [comment]
Hi again @UNIFIX1  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
