### ISSUE TITLE
Switch user option on iPad POS app

### ISSUE THREAD

**Issue by Honeybee5058** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1482]
Please add the option for switching users on the iPad POS app so that we can correctly track which employee is creating tickets and managing transactions. Thank you

**Comment by Uzair-RepairDesk** [comment]
Hi @Honeybee5058 
At present, We have decided not to release new features on the iPad and web app for the next few months as one of the feedback we constantly receive is to simplify RepairDesk, make it more stable, and remove unnecessary options.
With that in mind, we've decided to pause "new feature development" and over the course of the next few months our entire team will be working on "RepairDesk 2.0"
It's going to be clean, fast, and reliable! I hope you'll like it!

Thanks,

**Comment by Uzair-RepairDesk** [comment]
Hi @Honeybee5058 
Thank you for your request. We are not making any updates to our iPad POS Register app at this time. If you want to use an iPad for a transaction with a different employee, you can logout and login with another employee. Thanks
