### ISSUE TITLE
Searching issues

### ISSUE THREAD

**Issue by Shane-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1483]
Along with some last names we have now seen a ticket number that is not searching.
![Capture](https://user-images.githubusercontent.com/60683772/107096382-a728d500-67d8-11eb-9bf0-4f38c56e909a.JPG)

**Comment by Repairdesk-QA** [comment]
Hey @Shane-RepairDesk
I hope you are doing well. I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
Ayesha Aamer
