### ISSUE TITLE
MANAGE CUSTOMER 

### ISSUE THREAD

**Issue by Cumbr1at3ch** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1484]
Hi 

When entering one mobile number the software is duplicating this so there is two of the same mobile numbers showing 
![image](https://user-images.githubusercontent.com/40138325/107121253-54f3bc80-6889-11eb-9340-15fb6b1c8925.png)

**Comment by Repairdesk-QA** [comment]
Hey @Cumbr1at3ch,
I hope you are doing well. Thank you for bringing this to our attention! It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2570

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA 
Can you update the status of this? Thanks

**Comment by Repairdesk-QA** [comment]
Hello @Cumbr1at3ch,
Hope you are doing well.

Sorry for the delay as it was a big module to fix but there's good news for you.
Your reported issue has been fixed and lived. Kindly verify at your end and do let us know if you have any questions or face any issues.
Waiting for your feedback!

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Cumbr1at3ch,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
