### ISSUE TITLE
Inventory item does not appear in the purchase order

### ISSUE THREAD

**Issue by technofuse** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1487]
I have an item that is out of stock and when I go to the purchase orders to order some more, the item does not appear as an item I can order. 
![Screenshot 2021-02-10 153334](https://user-images.githubusercontent.com/78879436/107569196-078f8c00-6bb6-11eb-82d0-6207215b41c2.png)
![Screenshot 2021-02-10 153525](https://user-images.githubusercontent.com/78879436/107569245-170ed500-6bb6-11eb-9717-014d25405891.png)

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA  can you please check this issue.

Thanks

**Comment by Repairdesk-QA** [comment]
Hey @technofuse,
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Thanks,
Zain

**Comment by Repairdesk-QA** [comment]
Hey @technofuse,
Thank you for reaching us Can you please go to Store **Settings > Module Configuration > Inventory** and see if your trigger  **Hide Out of Stock Serialize Item** is checked or Unchecked, If the trigger is checked you are not able to search Out of stock serialized item.

Please let me know if I can do anything else for you.

Thanks,
Zain
![tech](https://user-images.githubusercontent.com/39614480/107738863-5f9acf80-6d29-11eb-921c-dff1416fa5f3.png)

**Comment by technofuse** [comment]
It was checked but that doesn’t make any sense. I’m using a purchase order to buy more of those out of stock items. It shouldn’t be hidden on that form.

**Comment by Repairdesk-QA** [comment]
Hey @technofuse,
Thanks for the update on this. Your reported issue has been assigned to the development team and hopefully, it will be fixed.

Your patience would be highly appreciated.

Thanks,
Zain

**Comment by Repairdesk-QA** [comment]
Hey @technofuse,
Your issue regarding the purchase order has been fixed.

Please verify at your end and do let us know.

Thanks,
Zain
