### ISSUE TITLE
Iphone App Crashs and Android App crashes

### ISSUE THREAD

**Issue by technofuse** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1488]
I start by creating a refurbishment ticket in the webapp, then when I try to open that ticket in the android repair desk mobile app and the Iphone app, the app just crashes and disappears. 
![Screenshot_20210210-154442_RepairDesk](https://user-images.githubusercontent.com/78879436/107570789-01021400-6bb8-11eb-8523-54f5c069492b.jpg)

**Comment by Repairdesk-QA** [comment]
Hey @technofuse,
I hope you are doing well. At present, Currently, we are not working on the new features/bug fixing on the Mobile App and iPad app for the next few months as one of the feedback we constantly receive is to simplify RepairDesk, make it more stable, and remove unnecessary options. With that in mind, we've decided to pause working on iPad & Mobile app and over the course of the next few months our entire team will be working on "RepairDesk 2.0"
It's going to be clean, fast, and reliable! I hope you'll like it!
Thanks,
Ayesha Aamer
