### ISSUE TITLE
Customized device tests do not save

### ISSUE THREAD

**Issue by technofuse** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1489]
I created these custom device pretests. I click all of them to pass and then click save. Then click save for the ticket. 

![Screenshot 2021-02-10 153525](https://user-images.githubusercontent.com/78879436/107571677-3a874f00-6bb9-11eb-8869-154c0f7f0e82.png)

Then when I click on the ticket again to see the device tests again, the results all say fail 

![Screenshot 2021-02-10 155758](https://user-images.githubusercontent.com/78879436/107571894-82a67180-6bb9-11eb-952e-fa4e9e2b3590.png)

And then when I click on the pre tests again to turn them back on, the default tests are showing, instead of the tests I created. 

![Screenshot 2021-02-10 155818](https://user-images.githubusercontent.com/78879436/107572070-bf726880-6bb9-11eb-85b2-e129d5bd263f.png)

**Comment by Repairdesk-QA** [comment]
Hey @technofuse,
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Thanks,
Zain

**Comment by Repairdesk-QA** [comment]
Hey @technofuse,
Can you please connect with us on a live chat with our support team as we need to make a test ticket on your account because we are unable to regenerate this issue on our end?

Please let me know if I can do anything else for you.

Thanks,
Zain

**Comment by Repairdesk-QA** [comment]
Hey @technofuse,
Ayesha here. Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up! Thanks!
