### ISSUE TITLE
Android Repair Desk App doesn't save the pre test device photos I take.

### ISSUE THREAD

**Issue by technofuse** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1490]
I created a repair ticket through the Android mobile app. Then I click the pre-test device photos to take a photo. I get this screen then click Save, after I took the photo. So it should upload the file so I can then view it.

![Screenshot_20210210-160955_RepairDesk](https://user-images.githubusercontent.com/78879436/107573671-d31ece80-6bbb-11eb-9428-64fcf9a34fb8.jpg)

But the picture is not saved to the repair ticket. 
![Screenshot_20210210-161529_RepairDesk](https://user-images.githubusercontent.com/78879436/107573763-f9446e80-6bbb-11eb-8e65-08de5c486513.jpg)

**Comment by Repairdesk-QA** [comment]
Hey @technofuse,
I hope you are doing well. At present, we are not working on the new features/bug fixing of the Mobile App and iPad app for the next few months as one of the feedback we constantly receive is to simplify RepairDesk, make it more stable, and remove unnecessary options. With that in mind, we've decided to pause working on iPad & Mobile app and over the course of the next few months our entire team will be working on "RepairDesk 2.0".
It's going to be clean, fast, and reliable! I hope you'll like it!
Thanks,
Ayesha Aamer
