### ISSUE TITLE
New Customer details 

### ISSUE THREAD

**Issue by KEZSVS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1493]
Please if some one can do anything about this 

![image](https://user-images.githubusercontent.com/69765024/107992689-1f5d7a80-6fd1-11eb-935c-9d8bc3e1353b.png)

**Comment by Repairdesk-QA** [comment]
Hello @KEZSVS 

I hope you are doing well. Can you please upload the image again as we are unable to see it ? 

Thanks

**Comment by Repairdesk-QA** [comment]
Hi again @KEZSVS  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by KEZSVS** [comment]
Please stop validating the phone number every time, I want the number to be treated as a string, DO NOT VALIDATE, I also want to format it like I want.

NOT FORCED like now, with no spaces or dashes (-).

I WANT a number like this: 11345-7852-5241

OR like this: 05421 452 000

Understand?

**Comment by KEZSVS** [comment]
Please reopen issue

**Comment by Repairdesk-QA** [comment]
Hey @KEZSVS,

**Comment by Repairdesk-QA** [comment]
Hey @KEZSVS,
I hope you are doing well. Sorry for the inconvenience. Could you please share your store name & login credentials with me via email at ayesha.aamer@repairdesk.co so that we can look into your concern? Thanks!
Regards, 
Ayesha Aamer

**Comment by KEZSVS** [comment]
![image](https://user-images.githubusercontent.com/69765024/108766091-9d2f0200-754c-11eb-92f0-6763aaec1907.png)

**Comment by KEZSVS** [comment]
@Uzair 

Kindly see this is the image that went missing previously , Kindly see if this is possible as its very helpful for my business flow.

**Comment by Repairdesk-QA** [comment]
@Uzair-RepairDesk FYI

**Comment by Uzair-RepairDesk** [comment]
> Please stop validating the phone number every time, I want the number to be treated as a string, DO NOT VALIDATE, I also want to format it like I want.
> 
> NOT FORCED like now, with no spaces or dashes (-).
> 
> I WANT a number like this: 11345-7852-5241
> 
> OR like this: 05421 452 000
> 
> Understand?

Hi @KEZSVS,
Hope you are doing well. I can understand that it is important to record the phone number in this format and sorry for the inconvenience, however, this option is available for the international phone format library only and the library has been depreciated from the backend. Currently, it is not possible for us to write the custom library for this option. We will certainly consider this option in the future.

Hope you can understand. I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks
