### ISSUE TITLE
SMS Inbox only shows todays SMS

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1499]
When viewing the SMS inbox, you can't filter the list view by date as it only shows todays inbox.

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,
I hope you are doing well. I have checked your concern on my end and worked fine for me, screenshot attached below. Can you please give it another try and let me know if you still face the same issue. Thanks!
Regards,
Ayesha Aamer

![SMS Inbox filter](https://user-images.githubusercontent.com/39614480/108461032-b2c9d080-729b-11eb-8067-dd109b7b3b52.png)

**Comment by afrahm** [comment]
OK, seems to be working now. However when you click the 'Today, This Week' buttons it loads but doesn't change the listing, you have to click run report again.

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,  
Thank you for bringing this to our attention! It looks like there's a bug that just popped up with the main filters in the Inbox section. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Regards,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2678

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,
I hope you are doing well. It looks like this bug has been squashed! Can you please give it another try.
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Regards,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,
Ayesha here. I hope you are doing well. Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up! Thanks!
