### ISSUE TITLE
Ticket and parts repair status

### ISSUE THREAD

**Issue by JiwanGrewal** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1501]
Hi, 

on the ticket dashboard there is no status for ticket itself. we can assign multiple status to parts associated with it but there is no status for ticket, is it something that can be added ?

**Comment by Uzair-RepairDesk** [comment]
Hi, @JiwanGrewal  Hope you are doing well, can you please some more detail for better understanding.

Thanks,

**Comment by Repairdesk-QA** [comment]
Hello @JiwanGrewal,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
