### ISSUE TITLE
Battery Health 

### ISSUE THREAD

**Issue by AMott-2020** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1505]
A place where we can put battery health and recommended replacement date.

**Comment by Uzair-RepairDesk** [comment]
Hi @AMott-2020 
You can create custom fields and fill in the data while creating a ticket for each device. You can learn more about custom fields from the following knowledgebase article:-
https://help.repairdesk.co/knowledgebase/articles/1921693-custom-fields

**Comment by AMott-2020** [comment]
ok sounds good thanks for the help
