### ISSUE TITLE
New Customer Details  

### ISSUE THREAD

**Issue by KEZSVS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1507]
Please stop validating the phone number every time, I want the number to be treated as a string, DO NOT VALIDATE, I also want to format it like I want.

NOT FORCED like now, with no spaces or dashes (-).

I WANT a number like this: 11345-7852-5241

OR like this: 05421 452 000

Understand?

**Comment by Uzair-RepairDesk** [comment]
Hi, @KEZSVS  Hope you are doing well,  sorry for the inconvenience but this option is available for the international phone format library but that is now deprecated from the back end and we can not change it now.

Thanks
