### ISSUE TITLE
improvements to POS / cash registers

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1508]
can i make a very important improvement suggestion. currently your POS / cash registers are designed to be one employee per register or using the switch user function to switch between employees to process transactions. im my company, our sales staff jump between serving customers all the time so an option would be nice that at the start of any transaction on the POS that the confim pin displays so any employee that comes to the POS machine they can quickly assign this particular sale to them. is that somthing that could be implemented?

**Comment by Uzair-RepairDesk** [comment]
Hi, @TechTraders Hope you are doing well, We can certainly see how suggested improvements would be useful. We are short-staffed because of COVID 19. We have to pick new enhancements based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one however we can consider it in the future while updating the feature in RepairDesk 2.0.
I really appreciate that you took the time to share your idea. Thanks for helping us make this a platform you'll depend on.

Thanks,

**Comment by Uzair-RepairDesk** [comment]
Hi @TechTraders ,

Happy to help with this. You can certainly assign multiple employees to a single register with our updated cash register functionality where your employees will be allowed to join the existing shift and enter access pin to confirm the transaction. For more information, please visit the knowledgebase article: http://help.repairdesk.co/knowledgebase/articles/810153-how-to-use-the-cash-register-module-in-repairdesk

Hope this helps. Let me know if there are any further questions related to this. Thanks.

**Comment by TechTraders** [comment]
Hi Uzair, i have looked into your suggestion. one main issue i faced with testing it. can we make it so anyone that joins the shift can end it? i believe that would be an important aspect to this function so that if the original emplyee who opens the shift does not need to be the one who closes the shift.

**Comment by Uzair-RepairDesk** [comment]
@TechTraders,

Currently if you want your employee to end the shift, simply switch the user and the employee will be allowed to end the shift. At the moment, we won’t be able to make this one, however we can consider it in the future while updating the cash register feature in RepairDesk 2.0. 

I really appreciate that you took the time to share your idea. Thanks for helping us make this a platform you'll depend on.

**Comment by TechTraders** [comment]
Ok thanks for informing me.

**Comment by TechTraders** [comment]
Ok thanks for letting me know.

**Comment by Uzair-RepairDesk** [comment]
You are most welcome!
