### ISSUE TITLE
Tickets & Invoices disappearing 

### ISSUE THREAD

**Issue by TechDoctors** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1512]
I found out today that if you create a ticket through the "Manage Ticket" fill everything out and hit create invoice - BOTH the ticket and new invoice disappears from the Manage pages 

Can you guys just have everything save automatically

**Comment by Repairdesk-QA** [comment]
Hey @TechDoctors,
Ayesha here. I hope you are doing well. Could you please try to create a ticket & invoice by following the steps as mentioned in the video attached below? Thanks!
https://drive.google.com/file/d/1_UPYvgYvyv2W8KqN9AynZjlI2-OYgN2s/view

**Comment by TechDoctors** [comment]
This does not help us! It is not every time we make a ticket/invoice. It happens randomly. We will make a ticket. It will show up for a while then randomly disappears. This is completely unacceptable to us as it is wasting our time and money! This is an internal issue with your software. Please fix.

 
Henri Grimm
Owner & Technician
M (805) 201-1211
P (805) 698-1450
E Henri@techdoctors.io
Tech Doctors 
919 Linden Ave Unit B
Carpinteria, CA 93013
www.TechDoctors.io <http://www.techdoctors.io/>
 <https://www.facebook.com/yourtechdoctors/>  <https://twitter.com/techdrs>  <https://www.linkedin.com/in/henri-grimm-8766b360/>  <https://www.instagram.com/tech_doctors_/>

**Comment by Repairdesk-QA** [comment]
Hey @TechDoctors,
I hope you are doing well. Currently, it's not possible to save the ticket and invoice automatically if the create invoice button from the Manage Tickets is clicked. If you want to save the ticket and invoice while creating kindly follow the steps that I have mentioned above. Thanks!
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
Ayesha
