### ISSUE TITLE
Customer Not listed on Employee Productivity Report

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1516]
When looking at Repair listing on Employee Productivity Report it shows as 'Walkin Customer' not the actual customer.

![Annotation 2021-02-26 092755](https://user-images.githubusercontent.com/1414304/109233190-2c6e3b00-7815-11eb-9bb0-3b060a2a848a.png)

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Regards,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-2723

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,
I hope you are doing well. I believe this issue has been fixed in the recent update. Can you give it another try? 
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out. 
Thanks!
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
Hi @afrahm,
Ayesha here. Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up! Thanks!
