### ISSUE TITLE
Loyalty Points not removed when invoice deleted

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1517]
When you delete an invoice that a customer earned loyalty points on, it does not remove the loyalty points from the customer, it just deletes the invoice number.
![Annotation 2021-02-26 125743](https://user-images.githubusercontent.com/1414304/109248856-5aae4380-7832-11eb-825c-7c7331619126.png)

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,

Thank you for bringing this to our attention! But in our current workflow if you want loyalty points to remove for the customer which he earned against some invoice you have to refund that invoice. On deleting the invoice it didn't revert back loyalty points for the customer.

Hope it helps and Please let me know if I can do anything else for you.

Thanks,
Zain

**Comment by afrahm** [comment]
That is still a bug.. as sometimes we delete an invoice that is created incorrectly. Rather than having to refund it then delete it.

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,

Thanks for the update on this. Your reported issue has been assigned to the development team and hopefully, it will be fixed soon.

Please let me know if I can do anything else for you.

Thanks,
Zain

**Comment by Repairdesk-QA** [comment]
Jira link : https://repairdesk.atlassian.net/browse/RB-2725

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,

I just discussed this with my development team and it seems it is not possible in our current workflow. Sorry for the inconvenience.

Please let me know if there anything else I can help you with.

Thanks,
Zain

**Comment by afrahm** [comment]
How is it not possible?

So you're happy to let our customers get free loyalty points and cost
repair shops money...

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,

Sorry for the inconvenience, As loyalty points are associated with the invoice and they revert back only once you refund that invoice (not on the deletion of invoice). However, here is the workaround for deleting the loyalty points given to the customer when invoice is created.

**After deletion of Invoice**

1. Open that customer in point of sale.
2. Click on the small + sign on the right-hand side of the loyalty points.
3. On popup select Void from the dropdown 
4. Enter the value you want to void from Loyalty points
5. Hit save 

**A video of these steps is also attached for your convenience.**  

Thanks,
Zain

https://user-images.githubusercontent.com/39614480/109301575-f99a6600-7859-11eb-8c35-058fced57644.mp4
