### ISSUE TITLE
Integrate payroll with quickbooks payroll

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#152]
Or add ability to show a weekly or bieeekly payroll hours summery for all employees on one sheet so we can quickly see total hours for the pay period for all employees at once to be able to pay them quickly

**Comment by Repair-Desk** [comment]
Already on our roadmap: #140

**Comment by jeffsand8243** [comment]
Great thank you!

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199
www.TheSmartphoneMedics.com
7449 Highway 72 W. Suite D Madison, AL 35758


Locations

Madison (main location) - 
7449 Hwy 72 between Nance Rd. and Jeff rd. across from the new Hobby Lobby (next to Valley pools and Whiskers barber shop) suite D

(Hours) 10-6pm weekdays, 
10-3pm Saturday. Closed Sunday 


Huntsville (drop off location) - 
Jordan Ln. and Holmes Ave.  (inside Boost Mobile)
(Hours) 11-7pm Monday- Saturday
