### ISSUE TITLE
Website imported items from Repairdesk 

### ISSUE THREAD

**Issue by DarrinCart** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1528]
Can imported items to my website from repairdesk be sized smaller to fit more items on a page ? Or at least more than what is currently being displayed?

https://www.myphonedr.com/start-repair

**Comment by Uzair-RepairDesk** [comment]
Hi, @DarrinCart  Hope you are doing well, can you please share more detail for better understanding.

Thanks,

**Comment by DarrinCart** [comment]
Hello Muhammad,

I got it resolved changing properties within squarespace.. But thank you for looking into this.

Darrin
________________________________
