### ISSUE TITLE
Device Images Missing at first in POS

### ISSUE THREAD

**Issue by onebitetechnology** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1529]
When navigating through the repair section to create a ticket in the POS, the first time you click on the device category, the device images are missing. You can then click on "Device" in the navigation and the images show up. See linked vid: 

https://youtu.be/pL82BsdMgwg

**Comment by Repairdesk-QA** [comment]
Hey @onebitetechnology, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks!

**Comment by Repairdesk-QA** [comment]
Hey @onebitetechnology, 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
For Internal Use:
https://repairdesk.atlassian.net/browse/RB-2820

**Comment by Repairdesk-QA** [comment]
Hey @onebitetechnology,
I hope you are doing well. I believe this issue has been fixed in the recent update. Can you give it another try?
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Ayesha Aamer

**Comment by onebitetechnology** [comment]
Confirmed it has been fixed :)
