### ISSUE TITLE
Invoice numbering issue

### ISSUE THREAD

**Issue by MmiddletonSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1533]
At the current moment if a tech "creates" a new invoice and then closes that invoice without actually creating anything that invoice number gets used and cannot use it. This throws off the invoice numbering and leaves gaps at times. Is there a way that we could fix this or be able to fix the numbering? I tried to manually use the number that was skipped but it would not be accepted.

**Comment by Repairdesk-QA** [comment]
Hey @MmiddletonSC, 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! Thanks.
Regards,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-2839

**Comment by Repairdesk-QA** [comment]
Hey @MmiddletonSC, 
Hope you are doing well. As I have discussed your reported issue with our development team they told me that this is our system behavior that we are logging unsaved tickets and invoices too, so we have to save the sequence with those invoices as well. 
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know. 
Thanks,
Ayesha Aamer
