### ISSUE TITLE
Edit contact information 

### ISSUE THREAD

**Issue by KEZSVS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1534]
Hi,

Please if you can sorted this ASAP it's making a lot of problem when i change any detail of delete any detail from a customer is delete another information Terrible 

Please see the video bellow 

https://www.awesomescreenshot.com/video/3069877?key=5823e234c301ccbc4f3e18dd74b65194

**Comment by Zain-javed** [comment]
Hey @KEZSVS,

Sorry for the inconvenience, your reported issue has been assigned to the developer and it will be fixed soon.

Please let me know if there anything else with which I may assist.

Thanks, 
Zain

[Jira](https://repairdesk.atlassian.net/browse/RB-2837)

**Comment by KEZSVS** [comment]
Hi 

It's two days over and i can't see any Update on this please

**Comment by Zain-javed** [comment]
Hey @KEZSVS,

Your reported issue has been fixed and hopefully, it will be lived today.

I'll update you once the release is live.

Thanks,
Zain

**Comment by Zain-javed** [comment]
Hey @KEZSVS,

The release is live and your reported issue has been fixed, can you please verify at your end and update us.

Thanks for your patience and is there anything else I can help you with.

Thanks,
Zain
