### ISSUE TITLE
Device Passcode

### ISSUE THREAD

**Issue by AMott-2020** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1535]
unable to type letters in passcode box 
can you make it where you can type both letters and numbers for customers device passcodes?

**Comment by Repairdesk-QA** [comment]
Hey @AMott-2020,
Ayesha here. I hope you are doing well. Can you please elaborate on your concern? Which screen you are referring to? Will be happy to advise you once you share additional details. Thanks!

**Comment by AMott-2020** [comment]
it is on the POS screen when you're creating a ticket and it asks for a passcode for the device but it only allows numbers no letters.

**Comment by Uzair-RepairDesk** [comment]
Hi @AMott-2020 
It certainly allows you to enter letters in the passcode/pattern field on POS. Please check the screenshot attached. 
Can you please share details along with a screenshot / a quick video if it is not working for you? 

![image](https://user-images.githubusercontent.com/22955861/111583052-9eff8480-87dd-11eb-892f-f9108be823b1.png)

**Comment by AMott-2020** [comment]
it seems to be working now if I have the problem again ill upload a picture of the issue.
