### ISSUE TITLE
Missing Invoice

### ISSUE THREAD

**Issue by MmiddletonSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1536]
Is there a way we can find a deleted invoice. I have the original printed so I know it was created but it is not in repair desk. My techs say they did not delete it, but we cannot find it. When I look up the Customer it says there are no invoices for him. Thank you for the help.

**Comment by Uzair-RepairDesk** [comment]
Hi @MmiddletonSC 
If you are sure about the invoice, can you please go to the Reports > Employee Reports > Employee Activity Log Report and apply the filter with the criteria " Delete Invoice". It will give you insight if an invoice is deleted from your account. You will also be able to find the user who deleted it. 

Please check the screenshot attached. 

![uzairshahRepairDesk-EmployeeActivityLog-Stats](https://user-images.githubusercontent.com/22955861/111582346-804cbe00-87dc-11eb-886b-f4e085e3de92.png)

I hope it helps
