### ISSUE TITLE
tax is being applied to cost of parts when calculating store cost and profit in reports

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#154]
tax on part should not be added to my cost when calculating totals in reports.  tax should only be applied to a part that is bundled with a repair or if customer is purchasing.  we don't pay tax on parts so that is not part of our cost.  it is only paid by customer and therefore should only show up on pos for customer not on my summary sales reports raising the cost of all of my parts.

**Comment by Uzair-RepairDesk** [comment]
We have already trigger available to apply tax on the cost price of parts.
