### ISSUE TITLE
Ticket status bug?

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1547]
I just discovered a "bug" - kindda anyway. We just changed the spelling in a ticket status. For some reason the tickets with that status dont get updated with the new spell corrected status.. and we are not able to search these tickets by status anymore. The only way is to extract the excel file of all the tickets and via that list find them and give them the "new" status.. Hope this makes sense..

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
Ayesha here. Hope you are doing well. I have checked your concern but its not a bug but the current functionality of the system i.e. if you change the spellings or delete any custom created ticket status, the tickets related to that status will not get associated with the updated ticket status/any other status & user have to manually update the ticket status against each and every ticket. The user can search tickets with the updated status once the status of the already created tickets is updated. 
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Thanks!

**Comment by jphansendk** [comment]
So how can we change a ton of status that needs to be corrected in one or another way?

**Comment by Repairdesk-QA** [comment]
Hey @jphansendk,
Ayesha here. I hope you are doing well. Can you please connect with one of our support agent on live chat so that he can look into the issue you are facing in detail? Thanks!

**Comment by Repairdesk-QA** [comment]
Hi again @jphansendk,  since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by jphansendk** [comment]
Sure.. Sorry I did contact the support.. Don't even remember the outcome 🙈
