### ISSUE TITLE
outgoing email 

### ISSUE THREAD

**Issue by AMott-2020** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1548]
out going email keeps popping up failure to send email when send customer a estimate but when I go to my outbox it sent it but I click on it to view the estimate and it says page not found 404

**Comment by Zain-javed** [comment]
Hey @AMott-2020,

Sorry for the inconvenience, Your reported issue has been assigned to the development team and hopefully, it will be fixed early next week.

Thanks,
Zain

[jira](https://repairdesk.atlassian.net/browse/RB-2860)

**Comment by Zain-javed** [comment]
Hey @AMott-2020,

Your reported issue has been fixed can you please check on your end and let us know.

Thanks,
Zain
