### ISSUE TITLE
Assign/Link a purchase order to a customer

### ISSUE THREAD

**Issue by Adski01** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1549]
We would like to be able to assign or link purchase order items to customers

**Comment by Repairdesk-QA** [comment]
Hye @Adski01,
I hope you are doing well. Can you please elaborate on your concern? Will be happy to advise you once you share additional details. 
Thanks!
Ayesha Aamer

**Comment by Adski01** [comment]
What would be great is another column added to the purchase order detail to assign specific items to a customer.  This helps us to streamline our processes of delivering the products to customers, or using them to complete our tickets and get the work done faster for our customers.  Does that make sense?  If not, can we do a screenshare?

**Comment by Uzair-RepairDesk** [comment]
Hi @Adski01 

We have special order functionality available in RepairDesk that allows you to create a special purchase order for out-of-stock or new items based on the specific customer request. You can order an item or part in a special order. 
Once you do that, PO is automatically linked with special order. You can also track it from the "Special Ordered Items" listing. Please check the screenshot attached.
![RepairDesk-Specialorder](https://user-images.githubusercontent.com/22955861/113129806-c53d0f80-9234-11eb-8030-e808b06549a2.png)

You can learn more about it from the following knowledgebase articles:-
https://help.repairdesk.co/knowledgebase/articles/1967952--special-part-and-special-part-order
https://help.repairdesk.co/knowledgebase/articles/1968369-special-part-and-special-part-order

If you have any questions, please free to ask. Thanks

**Comment by Repairdesk-QA** [comment]
Hi again @Adski01 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
