### ISSUE TITLE
label for customer devices 

### ISSUE THREAD

**Issue by AMott-2020** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1552]
I need to be able to make a label with the customers name and number from the POS screen before creating a ticket or estimate to be able to keep track of devices.

**Comment by Uzair-RepairDesk** [comment]
Hi, @AMott-2020 Hope you are doing well, there is no option to print a label before creating a ticket or estiamte. or you can provide more detail on this.

Thanks
Humza

**Comment by AMott-2020** [comment]
yeah i know there isn't an option I'm saying I would like for one to be integrated into RepairDesk

**Comment by AMott-2020** [comment]
it would just be an option where we could print a label from the POS when creating an estimate that would maybe have the customer's number and name.

**Comment by Uzair-RepairDesk** [comment]
Hi @AMott-2020 
Thank you for the explanation. The system needs a document with device details to generate a label like a ticket etc. Currently, there is no option to generate a label with customer information only. 

Regards,
Uzair

**Comment by AMott-2020** [comment]
ok, but can that be implemented in Repairdesk 2.0?

**Comment by Uzair-RepairDesk** [comment]
There should be a source document for a label so I am not sure if we are able to implement it in RD2.0 however I can discuss with the team to check the possibility.

**Comment by AMott-2020** [comment]
ok
