### ISSUE TITLE
Search tickets with discount.

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1553]
Hello Guys!
Sometimes we make discounts to our clients. But the problem is when we want to identify what tickets have discounts. Is any option filter for this? Or can I make other steps to see what percent from my tickets have discounts?

Thanks in advance!

**Comment by Uzair-RepairDesk** [comment]
Hi @adigsm07 
Currently, it is not possible to filter the tickets with discounts. You can open the ticket to find the value of the discount (if any).
I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
Uzair
