### ISSUE TITLE
Appointment calendar - doesn't work.

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1560]
Hello, yesterday I reported a problem with the appointment calendar and I didn't received an answer in this way.
I recorded my screen to show the problem.

Link with the problem --> https://youtu.be/S3SsF0MT0Dw

Many clients call us because they can't make an appointment on our website.

I talked yesterday on WhatsApp group support but nothing happened.

thanks...

I'm very disappointed because the support of RepairDesk is superficial....

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07,
I hope you are doing well. Sorry for the inconvenience you have faced. I have discussed your concern with the support team for a better understanding of it. Danish from support told me that he has guided you with some steps. Kindly follow them and let me know if you still face the same issue, would be more than happy to help. Thanks!
Regards,
Ayesha Aamer

**Comment by onebitetechnology** [comment]
Don't forget to join the facebook group: https://www.facebook.com/groups/1566154750347714

Have you double checked/repasted the widget code in the back end of your website? Try creating a new blank page with the code, see if it shows up.

**Comment by Repairdesk-QA** [comment]
Hey @onebitetechnology,
Ayesha here. I hope you are doing well. Are you still facing this issue?

**Comment by adigsm07** [comment]
Hello! The problem was resolved. Thanks for asking!

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07,
That's great! And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Thanks,
Ayesha Aamer
