### ISSUE TITLE
How to calculate a fix commission per repair/operation.

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1561]
Hello guys,

We want to put a fixed commission for a specific category of repair.
For example:  Changing battery: 22$,  Changing display 40$.
How to show this on POS?  This commission is not the final price, is just for our technicians

If you want more details, just feel free to ask me.

**Comment by Uzair-RepairDesk** [comment]
Hey, @adigsm07 
 Hope you are doing well, currently we don't have the option to add commission against repair catagoery, you need to give specific commission while creating each service.  However, we will certainly look for the possibility to add this improvement when revamping our Commission module in RD 2.0.


Thanks,
Humza Mehmood

**Comment by adigsm07** [comment]
Can you show me how to put a specific commission on each service?  


Hey, @adigsm07
Hope you are doing well, currently we don't have the option to add commission against repair catagoery, **you need to give specific commission while creating each service**. However, we will certainly look for the possibility to add this improvement when revamping our Commission module in RD 2.0.

**Comment by Uzair-RepairDesk** [comment]
Hey, @adigsm07  

Once you click on add service there is an option to activate commission once you activate commission you have the option to give either percentage or amount commission.
![image](https://user-images.githubusercontent.com/22955861/113967916-79e5bb00-984b-11eb-82c3-a18b8dcbce48.png)

Hope this helps.
Humza Mehmood

**Comment by adigsm07** [comment]
> Hey, @adigsm07
> 
> Once you click on add service there is an option to activate commission once you activate commission you have the option to give either percentage or amount commission.
> ![image](https://user-images.githubusercontent.com/22955861/113967916-79e5bb00-984b-11eb-82c3-a18b8dcbce48.png)
> 
> Hope this helps.
> Humza Mehmood


Oke and this commission where will be visible?

**Comment by Uzair-RepairDesk** [comment]
Hi @adigsm07  You can view employee commission in commission reports.

you need to go to **Reports section** => **Employee reports** and then you can view commission reports. 
![image](https://user-images.githubusercontent.com/22955861/114345703-a1a28f00-9b7b-11eb-971b-0722ae4b440c.png)

Hope it helps,
Thanks,
Humza Mehmood

**Comment by adigsm07** [comment]
This is a single way to put a commission?  In Integrations, I see an option to put commission. Percentage or fix commission. But we can't put a fixed commission on all operations because they are not equal. Changing display with changing the button.
There is not a future update to answer with RD 2.0... this is a bug... All responses now are with "maybe will be added on RD2.0". This is not a solution... maybe you need to fix integrations that is available now not in the future.

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA 
Can you please check this?

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07,
Ayesha here. Hope you are doing well. Can you please elaborate on your concern regarding integrations commission with a relevant screenshot? How you exactly use commission at this point in time? Will be happy to advise you once you share additional details. Thanks!

**Comment by Repairdesk-QA** [comment]
Hi again @adigsm07, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
