### ISSUE TITLE
Sales Summary Report

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1562]
When viewing the sales summary report, it shows the total sales before tax, but when looking at the COGS it includes tax. Can this be fixed to be no tax?

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,
Ayesha here. I hope you are doing well. Can you please elaborate on your concern? As I have checked on my account and it's showing COGS correct value without including tax in it, as you can see in the screenshots attached below.
Thanks!

![Sales Summary report 1](https://user-images.githubusercontent.com/39614480/113975009-4b221180-9858-11eb-96c5-4d9e51d6f645.png)
![Sales Summary report 2](https://user-images.githubusercontent.com/39614480/113975013-4cebd500-9858-11eb-8529-163dbef1e1ad.png)

**Comment by Repairdesk-QA** [comment]
Hi again @afrahm - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by afrahm** [comment]
All our parts/accessories are marked as inclusive of tax, as that is
default for Australia, so all our cost prices are entered inclusive of tax.

Regards,

[image: Kixup iPhone Repairs] <https://htmlsig.com/t/000001C2V70S>

Andrew Frahm / General Manager
***@***.***

Kixup Repairs
www.kixup.com.au

[image: Facebook]  <http://facebook.com/kixuprepairs> [image: Instagram]
<http://instagram.com/kixuprepairs>
