### ISSUE TITLE
WooCommerce integration to use PNG images as well..

### ISSUE THREAD

**Issue by jphansendk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1565]
I just discovered with the support team that RepairDesk doesn't support PNG images. That would be more than useful when you have the integration running with WooCommerce. Our site uses PNG because transparency is a part of the design of the site. So at the moment, we need to reupload the device images in PNG to WordPress to have the images working.. The conversion RepairDesk use makes a REALLY ugly border if there is transparency in the image.. Please support PNG.. JPG is SOOO last year ;-)
![PNG](https://user-images.githubusercontent.com/68819320/114389187-fb638300-9b94-11eb-82dd-7d9975f8ef1c.jpg)
![PNG_converted](https://user-images.githubusercontent.com/68819320/114389196-fdc5dd00-9b94-11eb-9851-aebeb80f83ad.jpg)

**Comment by Uzair-RepairDesk** [comment]
Hi @jphansendk 
Thank you for the suggestion. I discussed this with our technical team. There are security concerns attached with the PNG images. We will not be able to allow PNG images with the items to support with WooCommerce. 
Hope you can understand.

**Comment by jphansendk** [comment]
Ooh ok. Didn't know PNG could be a risk? Is there an alternative if I want transparency in images?
