### ISSUE TITLE
Sales Summary Report Improvement

### ISSUE THREAD

**Issue by onebitetechnology** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1572]
Every morning I run the current Sales Summary Report to see my profit from the previous day so I can do my banking. 

Since I'm still new to the workflow of inventory items & ticket items on a repair ticket, I find myself sometimes forgetting to add an item being used as part of a service. I'm sure new staff will make this mistake as well. 

Right now, there doesn't seem to be a report that shows all the services, inventory items, sales, etc on one report. I would love to have a listing of all line items sold, with items used as part of them, with my total gross, and total cost at the bottom. 

- Need a report that shows ALL sales, of both services and the products tied to them, with cost and sale price on a single page

**Comment by Uzair-RepairDesk** [comment]
Hi @onebitetechnology 
Thank you for the suggestion. By the way, did you try "Parts Consumption Report", or "Ticket Items Report" to track the parts with the ticket?

**Comment by onebitetechnology** [comment]
Ah excellent! I'd prefer to see it in a single report (I'll leave that to your capable hands to squeeze that info into a readable format hehe). The Ticket Items Report will help me make sure I don't miss any parts. Looks like I haven't missed any yet, so that's good!
