### ISSUE TITLE
iPad app

### ISSUE THREAD

**Issue by sebhyork** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1574]
iPad app keeps on freezing when trying to add a ticket
when trying to take a signature its grayed out
if I close a ticket and forgot to take a signature why it won't allow me to re open it and get the signature

**Comment by Repairdesk-QA** [comment]
Hey @sebhyork !

Can you please tell which IOS version of IPAD you are using is it (12,13 or 14)?

Thanks,
Zain

**Comment by sebhyork** [comment]
The current 14 update


________________________________

**Comment by Repairdesk-QA** [comment]
Hey @sebhyork ,

Thank you for the confirmation, Ill check it on my end and revert back to you. 

Please let me know if there anything else I can help you with.

Thanks,
Zain

**Comment by Repairdesk-QA** [comment]
Hey @sebhyork,

It is working fine on my end, please Install the app again and see if the issue still exists.

Thanks,
Zain
