### ISSUE TITLE
Daily Sales/Parts Report

### ISSUE THREAD

**Issue by onebitetechnology** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1578]
Every morning I run the Sales Summary report to see my profit and calculate how much to set aside for taxes, profit, and inventory. 

Right now, if I (or a staff member), forget to add a part to a service during a ticket, there is not way to catch it. The Ticket Items report (I just discovered this morning), ONLY shows you ticket items used. It does not list all services to make sure you did add an item to the service. 

Ideally, a Sales Summary report would include: 
- all the services sold with price and cost
- all items attached to those services and their cost
- all items sold independently with price and cost

In the end, I want to see a full list of line items on all invoices for the day, with a summary of price, cost, and margin $$.

**Comment by Uzair-RepairDesk** [comment]
Hey, @onebitetechnology  Hope you are doing well. we have a report named as  **Item wise sales report**, in this specific report, you can view all the items sold, their cost price and margins as well.
Hope this helps. If there is anything else I can help you with do let us know.

Regards,
Humza

**Comment by onebitetechnology** [comment]
Ah awesome! Did I miss this before or is it brand new? It did just help me find a ticket from last week I forgot to add the part. Thanks a million :)

**Comment by onebitetechnology** [comment]
@Uzair-RepairDesk I just noticed today, the new Item-wise Sales report does not include invoices created on one day, but paid another. 

Etc, I created an invoice on April 29th. It was paid on April 30th, so it shows up in the Sales totals for April 30th. The Itemwise sales report does not pick up that invoice.

**Comment by Uzair-RepairDesk** [comment]
Hey, @onebitetechnology  Hope you are doing well, item wise sales report is basically on a cash basis, this report records data only when payment is done against the invoice. It's also mentioned on the report that it's on a cash basis.
![image](https://user-images.githubusercontent.com/22955861/116860585-3b110e00-ac1b-11eb-98d0-11226a76195a.png)

Hope this helps.

Regards,
Humza

**Comment by onebitetechnology** [comment]
Right, so if I get paid for 5 invoices on a day, it should show the data for those 5 invoices? 

I'm saying it didn't... I got paid for invoices on the 30th, but because one was created (but not paid for yet) before the 30th, this report didn't show that data.

**Comment by Uzair-RepairDesk** [comment]
Hey, @onebitetechnology thanks for the feedback, I have forwarded your request to the QA department they will look into it, and once it's fixed I will update you here as well. 

Thanks,
Humza

**Comment by Uzair-RepairDesk** [comment]
Hey, @onebitetechnology Hope you are doing well, the above mention issue is fixed.
Hope this helps. If there is anything else I can help you with do let us know.

Regards,
Humza
