### ISSUE TITLE
Repairdesk iphone app bugs needing attention

### ISSUE THREAD

**Issue by Yucatech2013** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1580]
The time on your repairdesk app for iphone is wrong, it is about 1hr ahead, It shows me that a customer repair check in was 11:37AM PST when the real time on my iphone at that same time is 10:37AM

The total amount of sales is also often times wrong, some days it says that I have $3,550 in sales when in reality my total store sales is $650 all day

**Comment by Repairdesk-QA** [comment]
Hey @Yucatech2013, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks!

**Comment by Repairdesk-QA** [comment]
Hey @Yucatech2013,
Hope you are doing well. I have checked on my end, clock in / clock out transactions are displaying the correct date & time further the sales values are also displaying correctly when transactions are made from the RepairDesk mobile app. Could you please give it another try? 
Thanks,
Ayesha

**Comment by Repairdesk-QA** [comment]
Hi again @Yucatech2013 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by Yucatech2013** [comment]
the issue it’s not fixed,
-in my store the employee uses a destop imac to chec-in a customer for an iphone repair at 9:31am since i’m not in the store I would open the repair desk App in my iphone to check on how many tickets there are, that’s when I see that it says that the check-in the employee did at 9:31am shows 10:30am (but the real time it’s 10am here in california usa) 
so it looks like the repairDesk app time on iphone is 1hr ahead. can that be adjusted?

**Comment by Repairdesk-QA** [comment]
Hey @Yucatech2013, 
I hope you are doing well. Can you elaborate on your request with a relevant screenshot? Thanks!

**Comment by Yucatech2013** [comment]
Hi there,



Notice:
-this is a screenshot from an iphone 12
-we close at 6pm (the screen shot was taken at 6:15)
-the real check-in time for the second ticket was 5:04pm NOT 6:04pm
-So the problem is that the time on your RepairDesk iphone Application it’s 1 hour ahead

Would you Please fix it?

Thank you

**Comment by Repairdesk-QA** [comment]
Hey @Yucatech2013,
Hope you are doing well. I am unable to see the screenshot, can you please upload it? Thanks!

**Comment by Repairdesk-QA** [comment]
Hi again @Yucatech2013, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
