### ISSUE TITLE
Review request being sent to b2b customer

### ISSUE THREAD

**Issue by creator72** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1582]
My b2b customers are complaining about reviews being sent to them, is there a way to stop review requests for b2b customers?

**Comment by Repairdesk-QA** [comment]
Hey @creator72,
I hope you are doing well. Are you using the Review Campaign for getting reviews from the customers, if yes then kindly disable it and by doing so your customers will stop getting the review emails? Hope it helps.
Thanks,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
Hi again @creator72 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
