### ISSUE TITLE
Dual payment on POS

### ISSUE THREAD

**Issue by techm89** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1586]
In the POS checkout. If a customer wants to pay a repair with 2 payment methods (eg: cash + debit). Could we make it possible to do both at the same time? Right now we have to select cash, enter amount, press confirm then it takes 5 seconds for the page to refresh, then I need to select the ticket again, then select the 2nd payment (debit). This takes time and it's annoying when other customers are waiting to get served. It would save us lots of time and hassle.

**Comment by Uzair-RepairDesk** [comment]
Hey, @techm89  yes you can add split payments, on the checkout screen you need to add the payment for cash and press green checkmark, and then you can add a payment for another payment method.
kindly see the image attached,
![image](https://user-images.githubusercontent.com/22955861/116654183-16f6c800-a9a2-11eb-9636-c10d37e98dd7.png)
once you selected the first payment method then add the payment to another method
![image](https://user-images.githubusercontent.com/22955861/116654391-7ce34f80-a9a2-11eb-986d-5871bcf3a1a1.png)
Hope this helps

Regards:
Humza

**Comment by techm89** [comment]
Wow, I really did miss this. Thank you!
