### ISSUE TITLE
Add payfacto receipt directly to invoice sent to customer

### ISSUE THREAD

**Issue by techm89** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1588]
Would it be possible to include the payfacto receipt directly in the invoice sent to customer by email. Right now we have no way to give it to customer directly.

**Comment by Uzair-RepairDesk** [comment]
Hey @techm89 
You can print the receipt of Payfacto. Please check the video attached for your assistance:-
https://www.awesomescreenshot.com/video/3575838?key=f8855b8bc087115c4a1bef9541470997

Regards,
Uzair

**Comment by techm89** [comment]
Thanks for the update. Will look into it.

**Comment by techm89** [comment]
Hmmm actually you guys didn't resolve this. I asked for a receipt to be included in the email we send to customer. You sent me a link to print the receipt. This is not what I was asking.

**Comment by Repairdesk-QA** [comment]
Hello @techm89,
I would like to inform you that we have done the related improvement.
If you have enabled **_PayFacto_** on RepairDesk & wanted to email the Payfacto Receipt, you can.

**_Please have this video for reference:_**
https://www.screencast.com/t/UPNrpgf0VY

Kindly check again & do let us know if you have any issues.
Waiting for your feedback!

**_Regards,_**
Quratul Ain
