### ISSUE TITLE
Square integration not finalizing setup

### ISSUE THREAD

**Issue by PruittPCsolutions** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1591]
Enabling square integration brings up both logins, but the confirm location window is not appearing. iPad POS states "square is not set up on my account"

**Comment by Repairdesk-QA** [comment]
Hi @PruittPCsolutions,

Sorry for the trouble can you please confirm which integration you are using Square or Square Deep.

Please let me know if there anything else I can  help you with

Thanks,
Zain

**Comment by Repairdesk-QA** [comment]
Hi again @PruittPCsolutions, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
