### ISSUE TITLE
Invoices with an edited date show up on the created date

### ISSUE THREAD

**Issue by Stylemyphones** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1592]
Invoices with an edited date show up on the created date instead of the date that was meant for that particular invoice.
When I make the edit on the invoice's date, I am trying to tell the system that it is when the transaction should be reflecting in the Transaction Logs.
However, I am having discrepancies in the EOD reports due to the transactions being considered on the created date vs. corrected date.

**Comment by Stylemyphones** [comment]
Ref. invoice # [2053](https://stylemyphones.repairdesk.co/index.php?r=invoice/view&id=4393227) and Transaction Log [with](https://stylemyphones.repairdesk.co/index.php?r=cashDrawer/transactionLog&shift_id=)


EOD ( End of Day ) Report for 23-Apr-2021

[ReconciliationReport-23-Apr-2021.pdf](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/6437843/ReconciliationReport-23-Apr-2021.pdf)

**Comment by Uzair-RepairDesk** [comment]
Hi, @Repairdesk-QA  can you please check at your end and update here?

**Comment by Stylemyphones** [comment]
I'm unable to attach a video but I can connect through phone and AnyDesk or Zoom.

**Comment by Stylemyphones** [comment]
No worries the issue was discussed and 95% resolved by the support team ( Arnold ) mostly. 
However, I was able to make a video in case this help to have the issue resolved on your side for any future invoice edits.  

Video :   
https://drive.google.com/file/d/1S3oR26rhIpNCCX0sdPNtB-Uy2ifQkkwH/view
