### ISSUE TITLE
pre repair and post repair checklists

### ISSUE THREAD

**Issue by DOM260096** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1597]
pre repair and post repair checklists it would be great if these were in alphabetical order because some phones have  large list and ours are not in any time or order is the system could move them into an order that would be awesome.

**Comment by Uzair-RepairDesk** [comment]
Hey @DOM260096 
Thank you for the suggestion. However, there is comma-separated (,) behavior to display the "Pre/Post Repairs" checklist. It will be a one-time effort but you can setup according to the order your want to display. 
You can go to Store Settings > Module Configurations > Pre/Post Device Condition > Update for each category > Setup the order you want to display with comma separation. 
It will display according to the order you set. 

Please check the screenshot attached. Hope it helps 

![image](https://user-images.githubusercontent.com/22955861/117651149-0b2db180-b1ab-11eb-856e-433a7b4c1108.png)


If you have any further questions, please feel free to write back. Thanks

Regards,
Uzair

**Comment by Repairdesk-QA** [comment]
Hello @DOM260096,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
