### ISSUE TITLE
Barcodes printing $0.00

### ISSUE THREAD

**Issue by AbbyCSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1604]
When I print barcodes after creating a GRN it sometimes prints the retail price at $0.00 even though the product is setup correctly with a retail price.  You team connected to my system and confirmed it is a bug.  To fix it, I enter the same retail price in the promotional price field and it then prints correctly.  This makes no sense because there is no field for the promotional price setup in my product labels.  This happens on a regular basis but not all the time.  I cannot detect a pattern for when it happens.  I thought it may have had something to do with the markup % but I did some testing and could not create the issue.

**Comment by Repairdesk-QA** [comment]
Hey @AbbyCSC, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
Hey @AbbyCSC,
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
Hi again @AbbyCSC, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
