### ISSUE TITLE
Request to add sub-category to POS

### ISSUE THREAD

**Issue by Jonmarr95** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1611]
It would be great to have the option to add a sub-category to the POS, so we can better organize our devices by series/generation in addition to just one category and the manufacturer. On the same note, it would be great to be able to reorganize the order of the POS, for example starting with Manufacturer and then Category.

**Comment by Uzair-RepairDesk** [comment]
Hey, @Jonmarr95  Hope you are doing well, we have already an option to add a subcategory for products on POS. if you have added any subcategory against any product category then the subcategory option will be shown on pos. 

whereas for the other request, I can certainly see how suggested improvements would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
Hamza
