### ISSUE TITLE
Signature is small and almost invisibile

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1612]
Hello guys. I write you again with a problem with the signature. I post the problem every 4,5 months and the problem is in the same situation.

The signature is very small and almost invisible. 

![20210531_102030](https://user-images.githubusercontent.com/65545272/120155880-02545c80-c1fa-11eb-8838-1115be1e9ec0.jpg)

**Comment by Repairdesk-QA** [comment]
Hi @adigsm07,
Ayesha here. I hope you are doing well. Sorry for the continued inconvenience. Can you please elaborate on your concern? Which screen you are referring to and which app you are using for printing our WEB or iPad app? Will be happy to advise you once you share additional details. Thanks!

**Comment by adigsm07** [comment]
Is the same equipment. iPad 4 ( A1460 ) - With safari browser.

**Comment by Repairdesk-QA** [comment]
Hi @adigsm07,
I hope you are dog well. Sorry for the delay but I have pulled away and caught up with work. Actually, the size of the signature is fixed and we cannot further adjust it at the moment. Further, I have noted this improvement and will certainly see how suggested improvements would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work during this Quarter. Thanks!
