### ISSUE TITLE
A request for new payment integration

### ISSUE THREAD

**Issue by cellphoneninja** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1617]
Hello, we have some stores, we need new integation for processing paymnent.
"fidelity"
https://www.fidelity.com/
direct phone number: 407-625-0236

**Comment by Uzair-RepairDesk** [comment]
Hi @cellphoneninja 
Thank you for the post. Currently, it is not possible for us to integrate with any third-party payment provider. 
RepairDesk has its own integrated payment solution "RepairDesk Payments" that is quite convenient to use and we take the pain out of payment processing by offering clear & custom rates.
You can learn about it from the following link:-
https://www.repairdesk.co/RepairDesk-Payments

Let me know if you are interested to discuss this. Thanks

Regards,
Uzair
