### ISSUE TITLE
Issue with invoices

### ISSUE THREAD

**Issue by AMott-2020** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1618]
Not all items are showing up on invoices.
Ref. Ticket #100 Inv. #118

**Comment by Repairdesk-QA** [comment]
Hey @AMott-2020,
I hope you are doing well. Your reported issue has been assigned to development team and hopefully it will be fixed early next week. Your patience would be highly appreciated.
Thanks!
Azka 

For internal use only: https://repairdesk.atlassian.net/browse/RB-3301

**Comment by AMott-2020** [comment]
ok thanks.

**Comment by Repairdesk-QA** [comment]
Hey @AMott-2020 
I believe this issue has been fixed in recent update. Can you give it another try?
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks!
Azka

**Comment by AMott-2020** [comment]
it appears to be fixed for now ill let you know if I have anymore problems
