### ISSUE TITLE
Export module is not working.

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1625]
Hello guys! I need to update all prices from my RepaiDesk database. I tried to export my operation but is not working. Appear a message to wait 10-15 minutes, I waited 3 hours and nothing happened.

https://youtu.be/s4DU54va8CE

This is frustrating because I can't update my price.... 

RepairDesk have many problems, bugs and others... Nobody wants to resolve this...Appear new and new module.... I'm feeling disappointed

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07 
Hope you are doing well. 
Azka here. Sure thing! Let me take a look to your issue.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!
Thanks!

**Comment by onebitetechnology** [comment]
Have you tried selecting (use the checkboxes) a small batch and seeing if the export works? I know not ideal, but might get you through it to get the work done.

**Comment by Repairdesk-QA** [comment]
Hello @adigsm07 
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.
 If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
Azka

**Comment by adigsm07** [comment]
In the main post, I shared a video on youtube --> https://youtu.be/s4DU54va8CE

Actually, export module work just with  1000rows. If is many rows, appear a message "wait 10-15 minute" but after this time, remain the message..like an loop...

**Comment by adigsm07** [comment]
Toda I received an email --> Your request to export data has been successfully completed.
Please click the link below:

When I click to view my export, The page is Is's empty and the old files disappear.

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA 
Please check this

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07 
I hope you are doing well. Here is another way to export inventory:
1: Hit the export button
2: Cross the pop up " wait for 10-15 minutes. "
3: Go to reports --> Employee reports --> Export log --> There must be a link to download it.
If you have any other questions or feedback for us, please get in touch. 
Regards,
Azka
