### ISSUE TITLE
"Restock on" not working

### ISSUE THREAD

**Issue by antoinegali** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1630]
Hello,

In the POS, when a part is in Purchase Order, it should display "Restock on (date)". Now as you can see, it just says "Restock on 1". Am I doing something wrong?

Thanks
![Screen Shot 2021-06-13 at 10 28 04 PM](https://user-images.githubusercontent.com/37091836/121831952-d1af0100-cc96-11eb-82b2-252b66cfc3c3.png)

**Comment by Repairdesk-QA** [comment]
Hello @antoinegali,
Hope you are doing well.

I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can **share a video** of this issue or detailed steps so we can release a fix during our next release. You can put together a video **using Screencastify**.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Regards,
Quratul Ain

**Comment by antoinegali** [comment]
I've made this video; https://www.icloud.com/iclouddrive/01rjifKDIGM1uagMWWyA1_Nlg#RepairDesk

At the end of the video, shouldn't it display the date on which the product will be back in stock? Thanks!

**Comment by Uzair-RepairDesk** [comment]
@Repairdesk-QA 
Please check

**Comment by Repairdesk-QA** [comment]
Hello @antoinegali,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed early next week.
Your patience would be highly appreciated.
Thanks!
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-3401

**Comment by Repairdesk-QA** [comment]
Hello @antoinegali,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any question.

Thanks!
Quratul Ain

**Comment by antoinegali** [comment]
Hello,

Looks good on my end!

Thanks

**Comment by Repairdesk-QA** [comment]
Glad you like it.
Closing this issue as it has been fixed
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for your time. Enjoy your day!

Regards,
Quratul Ain
