### ISSUE TITLE
Template Editor issues

### ISSUE THREAD

**Issue by TechTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1631]
can we please have a consistent template editor that actually works how you would expect? for example if I select "reset template" to return the template to the default one, when I go to edit the newly reset template the editor does not reflect the same template??

**Comment by Uzair-RepairDesk** [comment]
Hey, @Repairdesk-QA  please check this in detail and update accordingly.

**Comment by Repairdesk-QA** [comment]
Hi @TechTraders ,
Hope you are doing well.
It is to inform you that this is the current functionality of our system as when we set "Reset to Default", it will reset to that default template provided by the Repairdesk System. 
You can copy your template via the Source button and paste it again to get the expected result or get your template again.
Please find the following picture for your reference.
![image](https://user-images.githubusercontent.com/39614480/122339968-22568080-cf5b-11eb-9ac5-844015195c6a.png)

Hope you can understand. I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks & Regards,
Quratul Ain

**Comment by TechTraders** [comment]
I had a phone call with Faisal regarding this. please speak to him regarding it.

**Comment by Repairdesk-QA** [comment]
As per discussion with Faisal, this issue has been fixed.
Closing this issue.
