### ISSUE TITLE
Invoices show as "Unpaid" even if they are fully paid

### ISSUE THREAD

**Issue by antoinegali** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1633]
Hello,

When I go to Invoices, and filter by "unpaid", there is some invoices that show as unpaid even tho they are. Please check attached pictures.

Thanks
![Screen Shot 2021-06-16 at 10 23 28 PM](https://user-images.githubusercontent.com/37091836/122321353-bb50b180-cef1-11eb-8ff8-bc37c4da0d6a.png)
![Screen Shot 2021-06-16 at 10 23 34 PM](https://user-images.githubusercontent.com/37091836/122321362-bf7ccf00-cef1-11eb-9fbb-8c77bd9142a8.png)

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali,
I hope you are doing well! Thank you for bringing this to our attention! It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Ayesha

**Comment by Repairdesk-QA** [comment]
**For internal use:**
https://repairdesk.atlassian.net/browse/RB-3383

**Comment by antoinegali** [comment]
Hello, thanks!

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any question.
Thanks,
Ayesha Aamer

**Comment by antoinegali** [comment]
Hello,

The invoice specified in my first post is indeed marked as "paid" now in the invoices list.

There is still some invoices that show as unpaid now. In my account, invoice 655 is an example.

Thanks!

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali, 
Thank you for bringing this to our attention! I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks!
Ayesha

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali,
I hope you are doing well. Your reported issue has been fixed now for the remaining invoices as well. Please verify at your end and do let us know if you have any question.
Thanks,
Ayesha Aamer

**Comment by antoinegali** [comment]
Hello!

Looks good on my side now. I will update here if it happens again.

Thanks!
Antoine

**Comment by creator72** [comment]
This is an ongoing bug that keeps on reoccurring every few weeks and is highly annoying for me as I have chased up said customer several times with this bug to be told by said customer that they had already paid. This looks bad and unprofessional on our part.  My accountant has access to the system and is constantly complaining that she needs to open the invoice to make sure its paid. 

I'm sure all the tech is doing at repair desk is marking the database entry manually for the affected invoice rather than finding the bug and fixing it.

**Comment by Repairdesk-QA** [comment]
Thanks @antoinegali. And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

**Comment by Repairdesk-QA** [comment]
Hey @creator72,
I hope you are doing well. Sorry for the continued inconvenience. We have fixed this issue, now it won't come on newly created invoices and for the already created invoices we are fixing it and it will be pushed live in our next release. Thanks for your patience.  
Regards,
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
Closing this task for now, and I hope that if there’s anything else I can do for you, you won’t hesitate to let me know. 
Thanks,
Ayesha

**Comment by antoinegali** [comment]
Hello,

It seems to be fixed as of now. However, when I go to one of my customers, it says there's an account receivable although all their invoices are showing as paid for. Is it related to that bug, or should I open a new issue? Customer name is "Cellupro", if you want to check on my account.
![Screen Shot 2021-06-27 at 9 01 05 PM](https://user-images.githubusercontent.com/37091836/123565645-9aa71800-d78b-11eb-8d07-d3b306f33673.png)

Thanks!

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali, 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks!
Ayesha Aamer

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-3447

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali,
I hope you are doing well.
I believe your reported issue has been fixed in recent update. Can you give it another try? 
Thanks,
Ayesha

**Comment by antoinegali** [comment]
Hello,

It seems to be working now. Thanks!
