### ISSUE TITLE
Tickets are being marked as unpaid

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1636]
Im having issues with transactions. I sent video to fahad via email.

**Comment by Uzair-RepairDesk** [comment]
Hey @Repairdesk-QA 
Can we get the video from Fahad and look into it?

**Comment by fahadimran303** [comment]
@Repairdesk-QA Please close this task as we never got the email.
Also we will make sure Omar is using RepairDesk 2.0 so all such issues can be taken care off.

Thanks and Regards,
Fahad Imran
