### ISSUE TITLE
Repair Desk Bug Forces to reset subscription

### ISSUE THREAD

**Issue by DerrickRepairs** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1637]
I try to set up my terminal but my account cannot access anything other than billing and it askes me to cancel my subscription first before i can do anything and now that i have its still giving me the same message , please help,

**Comment by Uzair-RepairDesk** [comment]
Hey, @DerrickRepairs  Hope you are doing well.  can you please connect over live chat, over support executive will help you out.

Hope is there anything else I can help you with, please feel free to ask.

Regards:
Humza

**Comment by Repairdesk-QA** [comment]
Hello @DerrickRepairs,
Hope you are doing well.

I hope your issue has been resolved on live chat. Would be great if you can confirm here.
Waiting for your feedback.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hey @DerrickRepairs,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
