### ISSUE TITLE
Warranty shows "out of warranty"

### ISSUE THREAD

**Issue by creator72** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1638]
When checking a warranty claim from POS, no matter what ticket number, serial or customer name is used the warranty on the ticket is always "expired". When checking the warranty terms, this is set to "90 days", The warranty on the ticket is within the 90 days but the POS reports it as "expired" regardless.

**Comment by Repairdesk-QA** [comment]
Hey @creator72,
Azka here. hope you are doing well.
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by antoinegali** [comment]
![Screen Shot 2021-06-29 at 4 54 07 PM](https://user-images.githubusercontent.com/37091836/123892161-0d4cfa80-d928-11eb-94e4-dc1dc369ec37.png)
I think I'm having the same issue. In this screenshot, the repair is well under warranty, but the only option to "redo" the job is to take it in as a "Out of warranty".

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali
I hope you are doing well. 
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
Azka
Usman Ali

**Comment by Repairdesk-QA** [comment]
Hi again @antoinegali, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Thanks,
Ayesha Aamir
