### ISSUE TITLE
Special parts are not being assigned to a ticket sometimes

### ISSUE THREAD

**Issue by creator72** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1639]
I have already reported this bug to your team last week and had a remote session to show the bug to your team, the affected ticket still has no special parts on it however the the special part list shows the ticket its assigned too. I have had this problem in the past and I resolved it by creating a new ticket, however this is not a fix due to the customer then having to ticket id's sent to them and the get confused.

**Comment by Repairdesk-QA** [comment]
hey @creator72  
Azka here,
I hope you are doing well. Thank you for your coordination. Our teams are working to make sure we solve this problem more quickly. I believe this issue will be fixed in recent update.
Your patience would be highly appreciated.
Regards!

**Comment by Repairdesk-QA** [comment]
Hey @creator72 
hope you are doing well.
I believe this issue has been fixed in recent update. Can you give it another try? If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
Azka
