### ISSUE TITLE
Invoice History (in POS) - Filtering by Customer Name doesn't work

### ISSUE THREAD

**Issue by onebitetechnology** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1641]
Example: Trying to find an old receipt to do a return

In the POS
- Click "View Invoices"
- Click "Search Filter"
- enter anything in the customer name field and search... it just seems to refresh but doesn't filter

**Comment by Repairdesk-QA** [comment]
Hello @onebitetechnology ,
Hope you are doing well.
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @onebitetechnology,

Hope you are doing well.
I wanted to inform you that I have tested your concern with different scenarios and I have found the same issue.
Thank you for bringing this to our attention! It looks like there's a bug that just popped up.

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks & Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For Internal Use:
https://repairdesk.atlassian.net/browse/RB-3430

**Comment by Repairdesk-QA** [comment]
Hello @onebitetechnology ,

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any question.

Thanks & Regards,
Quratul Ain

**Comment by onebitetechnology** [comment]
Nice work thanks! It now functions for me under the invoice lookup. 

However... I noticed now it is also broken under the ticket lookup, lol.

**Comment by Repairdesk-QA** [comment]
Hi @onebitetechnology,
Hope you are doing well.

I have checked this Ticket issue and I have found the same issue.
Thank you for bringing this to our attention! Your reported issue has been assigned to the development team and hopefully, it will be fixed early next release.
Your patience would be highly appreciated.

Thanks & Regards!
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For Internal Use: https://repairdesk.atlassian.net/browse/RB-3442

**Comment by Repairdesk-QA** [comment]
Hello @onebitetechnology,

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any questions.

Thanks & Regards,
Quratul Ain

**Comment by onebitetechnology** [comment]
Confirmed it is working. Thanks for your quick response!
