### ISSUE TITLE
Inventory Upload Updates Cost Price To 0$

### ISSUE THREAD

**Issue by antoinegali** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1645]
Hi,

Here's a very annoying bug I found. Whenever you export an (or multiple) item(s) to make changes, and then re-upload it, it resets the cost price to 0$.

Attached is a video of that problem; https://www.icloud.com/iclouddrive/06g6ITSFXCuQr53cSsKNLWx3Q#Repairdesk2

Thanks

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali,
Hope you are doing well.

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed early next week.
Your patience would be highly appreciated.

Thanks & Regards!
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For Internal Use: https://repairdesk.atlassian.net/browse/RB-3446

**Comment by antoinegali** [comment]
Hello,

Thank you for the update!

Have a great one

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali,

I hope you are doing well. Your reported issue has been fixed.
Please verify at your end and do let us know if you have questions.

Thanks!
Quratul Ain

**Comment by antoinegali** [comment]
Hello,

Seems to work good on my end now!
Thanks,
Antoine

**Comment by Repairdesk-QA** [comment]
That's good to know!
Closing this issue as it has been fixed
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for your time. Enjoy your day!

Regards,
Quratul Ain
