### ISSUE TITLE
(Dual Tax) Taxes Not Loading Correctly On PO

### ISSUE THREAD

**Issue by antoinegali** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1646]
Hello,

When I use Dual Tax Rates, it doesn't load the 1st tax rate on the PO. Furthermore, even the rates are not correctly calculated, as in this example, TPS should be at 5% and TVQ should be at 9.975% (Total of the invoice should be 1.15$)

Attached is a video of the issue; https://www.icloud.com/iclouddrive/0UOtQKrVX3FAtxnW32OPt62XQ#RepairDesk3

Thanks!

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali,
Hope you are doing well.

I have checked your concern and I have found the same issue. It looks like there's a bug that just popped up.
Thank you so much for letting us know. Your reported issue has been assigned to the development team and hopefully, it will be fixed in our next release. 
Your patience would be highly appreciated.

Thanks & Regards!
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For Internal Use: https://repairdesk.atlassian.net/browse/RB-3448

**Comment by Repairdesk-QA** [comment]
Hello @antoinegali,
Hope you are doing well.

I have come to know about **Dual Tax**'s store settings, and I wanted to share this with you.

For setting Dual Tax,
**First**, we have to set **Tax Configurations** from Store settings. Steps for these settings are:
**Store Settings->Tax Configuration  (Set two tax classes default for use of dual tax)**

**Second**, we have to set Dual Tax Classes from **General Store Settings** and have to hit the **Save Changes** button.
Also, don't forget to mark **YES** for this pop-up after hitting the **Save Changes** button.
![image](https://user-images.githubusercontent.com/39614480/123779824-02747480-d8ec-11eb-95a4-acd9eb13630a.png)

Please have a look at this video attached for detailed steps,
https://www.awesomescreenshot.com/video/4300062?key=6b2280ca5533991c84633b02c5ade01a

I hope this will solve your problem. If the issue still persists, please do not hesitate to let me know.

Waiting for your kind response!

Thanks & Regards,
Quratul Ain

**Comment by antoinegali** [comment]
Hello,

I did all these steps and it still doesn't work. I have the same issue.

Thanks

**Comment by Repairdesk-QA** [comment]
Hello @antoinegali,

Thanks for letting us know, we are working on this.
I'll get back to you as soon as I have more information! 

Thanks,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hey @antoinegali ,
I hope you are doing well. Your reported issue has been fixed.
Please verify at your end and do let us know if you have questions.
Thanks!
Quratul Ain

**Comment by antoinegali** [comment]
Hello,

Looks great on my end. Thanks a lot again!

Does it help you guys a lot when I report some bugs like that? It seems like I always find a bug here and there.

**Comment by Repairdesk-QA** [comment]
Yes, your efforts are really helpful for us and we appreciate that.
Thanks for your time and love to RepairDesk.

**Comment by Repairdesk-QA** [comment]
Glad you like it.
Closing this issue as it has been fixed
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for your time. Enjoy your day!

Regards,
Quratul Ain
