### ISSUE TITLE
Products with # print wrong on bar code

### ISSUE THREAD

**Issue by AbbyCSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1655]
If you product SKU has a # in the code, it causes the bar code to print on two labels and the product code doesn't print after the hashtag.  HP products (printers, ink cartridges, and computers) often have a # in the code and this is where we noticed this.

**Comment by Repairdesk-QA** [comment]
Hey @AbbyCSC,
Hope you are doing well.

I am looking into your issue and having a discussion over this with our development team.
I'll get back to you as soon as I have more information! 

Your patience would be highly appreciated.

Thanks & Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hey @AbbyCSC,

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed in our next release.
Your patience would be highly appreciated.

Thanks!
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For Internal Use Only: https://repairdesk.atlassian.net/browse/RB-3509

**Comment by Repairdesk-QA** [comment]
Hey @AbbyCSC,

I hope you are doing well. Your reported issue has been fixed.
Please verify at your end and do let us know if you have questions.

Thanks & Regards!
Quratul Ain
