### ISSUE TITLE
Tax error in sales register

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1658]
I am sending you our "sales register". My accountant has brought to my attention that the majority of the reimbursement invoices to the customer "SOS Phone Levis" contain an error. The subtotal is entered negatively as well as the total. However, "taxes" does not display negatively. At first I thought it was an error displaying the report, but it didn't. You can see some examples highlighted in yellow that have tax errors. I bring to your attention the column "taxes". You will find an example highlighted in blue on page 33 of the client "Carl Audet" for which the taxes are displayed correctly.

I await your return,
Thank you and good day
[Limoilou avril 2021.pdf](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/6817607/Limoilou.avril.2021.pdf)
<img width="937" alt="resgitre des ventes" src="https://user-images.githubusercontent.com/40500094/125660501-ca7fdc58-d627-44e6-ae92-c3f5e7946641.png">

-- French: --
Je vous envoie notre "registre des ventes". Ma comptable a porté à mon attention que la majorité des factures de remboursement au client "SOS Phone Levis" comporte une erreur. Le sous-total est bien inscrit négativement ainsi que le total. Cependant, les "taxes" ne s'affiche pas négativement. J'ai d’abord pensé qu'il s'agissait d'une erreur d'affichage du rapport, mais il n'en ait rien. Vous pouvez voir quelques exemples surlignés en jaune qui comporte les erreurs de taxes. Je mets à votre attention la colonne "taxes". Vous trouverez un exemple surligné en bleu à la page 33 du client "Carl Audet" pour lequel, les taxes s'affichent correctement. 

J'attends votre retour,
Merci et bonne journée

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS 
I hope you are doing well.
Azka here.
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks & Regards.

**Comment by Repairdesk-QA** [comment]
Hey @JessicaSOS 
I hope you are doing good.
Thank you for bringing this to our attention. It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as It is fixed.
Thanks!
Azka

**Comment by Repairdesk-QA** [comment]
For internal use only:
https://repairdesk.atlassian.net/browse/RB-3542

**Comment by Repairdesk-QA** [comment]
hey @JessicaSOS 
I hope you are doing great. 
We have fixed this issue for highlighted invoices. can you please give it a try?
If you face this issue again it would be great to record a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Azka

**Comment by JessicaSOS** [comment]
The problem is well resolved! thanks a lot
