### ISSUE TITLE
Need to get Confirmation for When will the Date ranges for the Inventory Summary Reports 

### ISSUE THREAD

**Issue by SandraGibbs** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1659]
![image](https://user-images.githubusercontent.com/87668089/126206207-c326a2c7-7d15-4fec-abde-94037280a245.png)

Need to have that Date ranges filter here   ASAP/  @Uzair

**Comment by SandraGibbs** [comment]
@Uzair  Kindly look this Issue

**Comment by SandraGibbs** [comment]
How it used to work
![20201231 Total All Stores](https://user-images.githubusercontent.com/87668089/126213552-505aa465-e1c5-4d8e-bce5-507441c94a03.PNG)

**Comment by Uzair-RepairDesk** [comment]
Hey @SandraGibbs 

There is a technical concern to hide the date filter from inventory summary report. 
Our engineering team is away on local holidays. 

I will check with the team early next week and update you accordingly. 

Regards,
Uzair

**Comment by SandraGibbs** [comment]
Please advise as you have not replied since 12 days ago.

**Comment by Repairdesk-QA** [comment]
Hello @SandraGibbs,
Hope you are doing well.

We sincerely apologize for the wait you had to bear.
We are actually in discussion with our development team regarding this issue as we had some technical concerns with this issue. I'll get back to you as soon as I have more information! 

Be with us, your patience means a lot to RepairDesk.

Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hey @SandraGibbs,
Hope you are doing well.

Your reported issue has been assigned to the development team and hopefully, it will be fixed early next week.
Your patience would be highly appreciated.

Thanks & Regards,
Qurat ul Ain

**Comment by Repairdesk-QA** [comment]
For Internal Use Only: https://repairdesk.atlassian.net/browse/REP-3253

**Comment by Repairdesk-QA** [comment]
Hello @SandraGibbs,
Hope you are doing well.

We have worked on your issue and concluded that If we add Date Filter in Inventory Summary Report, it will work for the dates after the date of fix.
For example, if it goes live next Tuesday(i-e, 28 Sept 2021) the report will work after that date.
Please let us know is it ok for you because this is the way it will work in its good way.

Waiting for your precious reply.

**Regards,**
Quratul Ain

**Comment by SandraGibbs** [comment]
This is fine.

Just let me know when it goes live

**Comment by Repairdesk-QA** [comment]
Sure thing @SandraGibbs,
We will update you about this.
Your patience means a lot.

**Regards,**
Quratul Ain
