### ISSUE TITLE
Repair Ticket Missing without deletion

### ISSUE THREAD

**Issue by alliedcomputers** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1660]
We have faced one error which is very much frustrating. 
> Create repair ticket from POS
> Update status 
> Take printout 
> After few minute, tried searching the ticket 

BUG: Ticket is missing surprisingly. 

We did check the employee logs but couldnt find any log which shows the deletion of the ticket or anything else. 
Ticket no: RMA-751

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers,

I hope you are doing well. Your reported issue has been fixed.
Please verify at your end and do let us know if you have questions.

Thanks!
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For Internal Use Only: https://repairdesk.atlassian.net/browse/RB-3550

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers,
I hope you are doing well. Your reported issue has been fixed.
Please verify at your end and do let us know if you have questions.

Thanks!
Quratul Ain
