### ISSUE TITLE
Taxes not updating with customer update

### ISSUE THREAD

**Issue by Stylemyphones** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1662]
Hello,

We have noticed another bug in the system.
My employees check prices for different customers so they scan items and then change the customer, or vice versa.

I have attached a video link below to show what is happening.

The taxes don't come back after a tax exempt customer is selected, and then switched back to a regular customer. The item must be removed and re-scanned after the regular (tax incurring) customer has been selected.

Please help!

https://drive.google.com/file/d/1P_GzemzLnL1gCS994s2VgJrdwb-T1GPn/view

**Comment by Repairdesk-QA** [comment]
Hey @Stylemyphones 
Azka here.
I hope you are doing well.
Thank you for bringing this to our attention. It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of.
I'll get back to you as soon as the issue gets fixed.
Thanks!
Regards.

**Comment by Repairdesk-QA** [comment]
For internal use only:
https://repairdesk.atlassian.net/browse/RB-3562

**Comment by Stylemyphones** [comment]
You're welcome and thank you for your support.

Regards

**Comment by Repairdesk-QA** [comment]
Hey @Stylemyphones 
I hope you are doing well.
Thank you for reaching out to us and helping us make this a platform you'll depend on.
I believe this issue has been fixed in today's update. Can you give it another try?
If you have any questions or if there is anything else with which I may assist, please
do not hesitate to let me know.
Regards
Azka

**Comment by Stylemyphones** [comment]
Great! Thanks so much.
We have checked it on our side and it's working here too.

Thanks again.

**Comment by Repairdesk-QA** [comment]
Thanks for the update on this.
Be sure to let us know if there's anything we can do to make it even better.
Regards
Azka
