### ISSUE TITLE
Diagnostic note not editable by super admin

### ISSUE THREAD

**Issue by alliedcomputers** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1664]
We have noticed one bug, please resolve. 
Following are the test cases. 

* Lead created by the customer from website 
*  Mentioned the requirement in "Diagnostic Note"
* Received by super admin & convert to ticket 
* Tried editing the diagnostic note because its not printing on service receipt ( ticket) 

Bug: System not allowing to edit the diagnostic note even if the user is is SUPER ADMIN. 
        Its not printing on service receipt either.

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers 
Azka here
I hope you are doing well.
thanks for reaching out to us. I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share related screenshots, a video of this issue or detailed steps so we can release a fix during our next release. 
You can put together a video using Screencastify. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards.

**Comment by alliedcomputers** [comment]
https://user-images.githubusercontent.com/87709069/127305984-f110f00a-0d63-44ed-825f-818ccc4cfcc7.mp4

Please find attached video where, both of the diagnostic note mentioned. 
When customer made the diagnose note ( its not editable by super admin ) 
Super admin has to write same diagnostic note once again to edit or add some more info.

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers 
I hope you are doing well.
Thanks for the update on this. But I am unable to reproduce this issue. attaching a video for guidelines.
https://www.awesomescreenshot.com/video/4649490?key=b415d88649963f9c8150f747b7a6ff8f
Also it is being printed on service receipt.
![image](https://user-images.githubusercontent.com/39614480/127434282-32814992-587d-4b9e-ab1d-5276eb3f3f0d.png)
Can you please give it another try? If issue reproduces, kindly share the detailed video.
Also specify which widget you are using to create leads on your website.
Be sure to let us know if there's anything we can do to make it even better.
Thanks & Regards
Azka

**Comment by Repairdesk-QA** [comment]
Hi again @alliedcomputers, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Regards,
Ayesha Aamir

Closing this task for now.
