### ISSUE TITLE
Ticket list sorting issue

### ISSUE THREAD

**Issue by alliedcomputers** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1665]
Whenever any new ticket is added.  It should display on top.

Bug: After creation of any new inquiry its not displaying in current page. 
Click on "ID" column title 2 times, it starts displaying. 

This bug has started since last couple of weeks only.

**Comment by Repairdesk-QA** [comment]
Hello @alliedcomputers,

Hope You are doing well.
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @alliedcomputers, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Regards,
Ayesha Aamir

Closing this task for now.
