### ISSUE TITLE
Invoice PDF Price and Discount fields are swapped

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1666]
[Invoice 417.pdf](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/6897079/Invoice.417.pdf)
As you can see in the attached file. The price amount is showing up in the discount column and the discount amount showing up in the price column. Shows fine within RD.

I have temporarily adjusted the template by swapping the headers.

**Comment by Repairdesk-QA** [comment]
Hey @afrahm 
I hope you are doing well.
Thank you for reaching out to us. We have provided flexibility to change settings of invoices in the system flow. You have done exactly the right step towards solution. We really appreciate your system understanding. 
Please let me know if you face this issue again.

**Comment by afrahm** [comment]
But does that mean that everyone else is currently setup with them all
around the wrong way.


Regards,

[image: Kixup iPhone Repairs] <https://htmlsig.com/t/000001C2V70S>

Andrew Frahm / CEO & Founder
***@***.***

Kixup Repairs
www.kixup.com.au

[image: Facebook]  <http://facebook.com/kixuprepairs> [image: Instagram]
<http://instagram.com/kixuprepairs>

**Comment by Repairdesk-QA** [comment]
Hey @afrahm 
Thanks for your concern.
I will discuss the issue with business development team and we will work on what we can do to improve the software.
Regards
Azka

**Comment by Repairdesk-QA** [comment]
Hey @afrahm 
I hope you are doing well.
We had a discussion with our business development team and it will be fixed in next version of RepairDesk.
Thank you for your precious time.
Regards
Azka
