### ISSUE TITLE
COG showing improperly on reports when a refurbished item has "Special Order Parts"

### ISSUE THREAD

**Issue by onebitetechnology** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1674]
Scenario: 
- Trade-In item (iPhone)
- Purchase price of the item was $90 
- Refurbished the item, and used a Special Order part with a cost of $107. 
The refurb cost shows up in the item, and in the column on the trade-in listing page. 

I sold the item, and in the report (Item Wise, and Sales Summary) the COG of this item specifically is only $90. 

The lowdown: A "Special order part" added to a refurbishment doesn't add to the COG of the product in reports.

**Comment by Repairdesk-QA** [comment]
Hello @onebitetechnology,
Hope you are doing well.

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed early next week.
Your patience would be highly appreciated.

Thanks & Regards!
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For internal use only: https://repairdesk.atlassian.net/browse/RB-3617

**Comment by Repairdesk-QA** [comment]
Hey @onebitetechnology,
I hope you are doing well. Your reported issue has been fixed.
Please verify at your end and do let us know if you have questions.
Thanks!
Quratul Ain

**Comment by onebitetechnology** [comment]
Confirmed the report is now showing the proper cost of goods. THanks so much!!
