### ISSUE TITLE
"Device model" back blank on inventory item update.

### ISSUE THREAD

**Issue by ProntoFix** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1682]
Every time I want to change something (price, amount, name description, etc...) in an inventory item, the "Device model" box is blank again. If it is then forgotten to fill it in again after saving, this item is no longer connected to the device and as a result can no longer be found in POS.

<img width="1280" alt="Schermafbeelding 2021-08-17 om 11 23 11" src="https://user-images.githubusercontent.com/89073213/129701687-a795645e-0f95-4934-a198-7b3343c6d768.png">
<img width="1276" alt="Schermafbeelding 2021-08-17 om 11 23 52" src="https://user-images.githubusercontent.com/89073213/129701695-40658bc2-6fca-4843-82c0-c9e43444120e.png">
<img width="1280" alt="Schermafbeelding 2021-08-17 om 11 24 18" src="https://user-images.githubusercontent.com/89073213/129701697-8e8a773d-9f87-4096-a813-4f3276ae9798.png">

**Comment by Repairdesk-QA** [comment]
Hey @ProntoFix 
Azka here.
I hope you are doing well.
I have checked your concern and I believe you have not selected the manufacturer for which device model is getting disappeared again and again. Device model is dependent on manufacturer. 
Kindly give it a try after setting manufacturer and device model and hit save button. If you face this issue again or  have any query with which I may assist, please do not hesitate to reach out.
Thanks & Regards

**Comment by Repairdesk-QA** [comment]
Hey again
Azka here.
I hope you are doing well. Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Thanks and Regards.
