### ISSUE TITLE
Pre repair device condition glitch 

### ISSUE THREAD

**Issue by alliedcomputers** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1685]
We are facing prerepair device condition error. following are the steps 

* Create repair ticket from customer portal by customer 
* Send the device by courier and receipt by the admin team. 
* Edit ticket by admin user to update the pre repair device condition

Bug: Only partial pre repair device condition is visible to be selected. 
Note: When ticket is created from POS, user can see all the pre-repair device conditions to be selected.

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers 
Azka here.
I hope you are doing well.
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video or screenshot of this issue for better understanding. So we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers 
Hope you are doing well.
Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Thanks and Regards
Azka

**Comment by alliedcomputers** [comment]
Dear azka, still the issue hasnt solved. 
![image](https://user-images.githubusercontent.com/87709069/131989429-af44efae-d739-43f1-9ca6-e03654424746.png)
( This ticket is created from customer portal & you can see the pre repair device condition is not same as set by admin)
RMA-852 ( Ticket number)
![image](https://user-images.githubusercontent.com/87709069/131989531-a8d22f7d-e59b-48b9-985a-ca923f203c34.png)

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers 
Can you please put togather a video of detailed  work flow through screencastify for a better understanding of bug. 
Regards
Azka

**Comment by alliedcomputers** [comment]
We have already provided the screenshot & explained. 

 

Bug: Pre repair device condition is partially visible at the time of ticket is generated from customer porta. 

 

Thanks & Regards,

                                            Technical & Customer Support

                                            T: +44 020 84276809

                                            E:  ***@***.***> ***@***.***

 

Allied Computers International Limited

189, Ealing Road

Wembley HA0 4EJ

**Comment by Repairdesk-QA** [comment]
Hello @alliedcomputers,
Hope you are doing well.

Sorry for the delay. 
Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks for your patience & time.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @alliedcomputers,
Hope you are doing well.

I have checked your concern & wanted to inform you that the **_Pre- Repair & Post- Repair Device Conditions_** are linked with the **_Category._** When we create a **_ticket from the Customer Portal_**, no category will be counted in that and it will pick the **_Default Pre & Post Repair Conditions._**

**_We can set Default Conditions from_**
Store Settings -> Module Configuration -> Pre/Post Device Conditions -> Default (Action button click will led you to Edit)

**_For better understanding, kindly have a look at the attached video:_**
https://www.screencast.com/t/D4zPDDQJh0S 

I hope this description will solve your problem but if not, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @alliedcomputers,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
