### ISSUE TITLE
Commissions for other types

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#169]
We will need to set commissions for other types not only default types in the system. We have higher margins of other things that we sell and we want to have ability to pass on some comms to our staffs.

**Comment by RepairDeskPOS** [comment]
@quangc have you checked this knowledgebase article: https://repairdesk.uservoice.com/knowledgebase/articles/895878-how-can-i-setup-employee-commission

**Comment by Uzair-RepairDesk** [comment]
Hey @quangc 
I am pleased to inform you that we’ve gone live with following improvements in employee commission module: 
1: Employee commission can be set in amount or percentage
2: Commission value can be set globally, with respect to inventory item categories e.g. cases, chargers or individual items too.
3: Setup to split commission between a sales-person and technician
4: Configuration to set commission based on total sales or profit earned (Trigger based)
5: Added an option to void commission in case of a refund (Trigger based)
6: Option to pay commission via payroll module.
7: Improved Commission report

For more info on how to setup and use the updated module is available here:
https://repairdesk.uservoice.com/knowledgebase/articles/895878-how-can-i-setup-employee-commission
