### ISSUE TITLE
Invoices, estimates & tickets: difference in layout and font between printed and mailed.

### ISSUE THREAD

**Issue by Rikkertsie77** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1692]
There is a significant difference between a mailed or printed invoice/estimate. There is a totally different font style between the two versions. Also is the alignment different, with the mailed one being the worst. I ask to make both type of documents uniform, so that a company can keep its professional appearance.  See the different files for comparison in the attachments.
[Invoice255_1630994310.pdf](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/7119536/Invoice255_1630994310.pdf)
[Rick de Graaf Reparaties RepairDesk - Print Invoice.pdf](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/7119537/Rick.de.Graaf.Reparaties.RepairDesk.-.Print.Invoice.pdf)

**Comment by Repairdesk-QA** [comment]
Hello @Rikkertsie77,
Hope you are doing well.

I have checked your concern and I have checked at my end but it has some confusion. Would be great if you can share a video of this issue or detailed steps so we can see which screens you are using. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Regards,
Quratul Ain

**Comment by Rikkertsie77** [comment]
Hello @Repairdesk-QA,
Yes i'm fine, thank you for asking. I hope you doing well too.
Thank you for responding to my issue. 

I have made a video for you with the differences of the layout and font between the printed and digital (pdf) version.
Hereby the link from WeTransfer https://we.tl/t-SlxD0pmmYZ.

Best Regards,

Rick de Graaf

**Comment by Rikkertsie77** [comment]
@Repairdesk-QA The link with the video is almost expiring.

**Comment by Repairdesk-QA** [comment]
Hello @Rikkertsie77,
Hope you are doing well.

I have downloaded the video & seen it too. I just want to know which font you are preferring? The one in Email or Invoice or Pdf.
Please let us know. After that, I have to discuss that format with our development team because there are some formats supported by the only pdf and not in Repairdesk and vice-versa.

Waiting for your precious reply.
Regards,
Quratul Ain

**Comment by Rikkertsie77** [comment]
Hello @Repairdesk-QA 
Thank you for the quick response! 

I prefer the printed one, because this one has the best layout. The most important thing is that the Email, Invoice & Pdf version all have the same font, fontsize and layout. So that everything looks professional and has the same feeling for the customer. 

I maybe have the following solution for the problem:

Go to invoices > print invoice > open pdf preview > save file. If you follow this steps (Mac user), than the printed invoice will be the same as the pdf one. Maybe your team can program this into the software, so everything is exactly the same. I hope i have explained the above well enough.

**Comment by Repairdesk-QA** [comment]
Hi again @Rikkertsie77,
Thanks for elaborating on your concern.

I am currently in discussion with our development team and will inform you about the updates.
Be with us, your patience means a lot to RepairDesk.

**Regards,**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Rikkertsie77,
Hope you are doing well.

Your reported issue has been assigned to the development team & hopefully, it will be fixed in our next release.
Your patience would be highly appreciated.

**Thanks & Regards,**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For internal use only: https://repairdesk.atlassian.net/browse/RB-3898

**Comment by Repairdesk-QA** [comment]
Hello @Rikkertsie77,
Hope you are doing well.

Your reported issue has been fixed. Please verify at your end and do let us know if you have any questions.
Waiting for your feedback!

**Thanks & Regards,**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Rikkertsie77,
Hope you are doing well.
Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Quratul Ain
