### ISSUE TITLE
Customer comment not editable or printable. 

### ISSUE THREAD

**Issue by alliedcomputers** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1696]
> Created lead by customer from website booking widget. 
> customer comment parked under "customer comment" section.
> Lead converted to ticket 
> Customer comment transferred under ticket area "Diagnostic note"
**> Tried editing the customer comment as super admin but not editable, evenif the edit button is there ( BUG )
> Tried printing the ticket, even if the diagnostic note is auto parked from the lead, its not showing in print preview or not printing as well. (BUG)**

https://user-images.githubusercontent.com/87709069/132676701-32327bda-9a24-4f9c-9c06-917b66c111eb.mp4

**Comment by Repairdesk-QA** [comment]
Hello @alliedcomputers,
Hope you are doing well.

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Thanks & Regards! 
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hey @alliedcomputers,
Your reported issue has been assigned to development team and hopefully, it will be fixed in our next release.
Your patience would be highly appreciated.

Thanks!
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For Internal Use Only: https://repairdesk.atlassian.net/browse/RB-3786

**Comment by Repairdesk-QA** [comment]
Hello @alliedcomputers,
Hope you are doing well.

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have questions.
Now you can Edit Customer Comment(Diagnostic Note in Ticket) and can see in Description/Notes while printing.
Please find the attached pictures for reference:
![image](https://user-images.githubusercontent.com/39614480/133255103-116e60df-0fbb-43af-bd29-f09411ca4cd2.png)
![image](https://user-images.githubusercontent.com/39614480/133255244-be4cf1ca-0849-410d-b352-cc6da317e671.png)


Thanks!
Quratul Ain

**Comment by alliedcomputers** [comment]
Hello, It looks like you havent read or understand the bug. 
Please carefully read the steps mentioned. when the bug arises. 
RMA-875 still customer comment is not editable. (attached video)

https://user-images.githubusercontent.com/87709069/133406574-7755ccfb-64ec-40b0-bc11-201cb7ab7650.mp4

**Comment by alliedcomputers** [comment]
Another video when, customer created LEAD from the website booking form and after converting the lead to ticket. 
Customer comment is not editable.

https://user-images.githubusercontent.com/87709069/133408749-883be1de-3618-4db5-8a74-5932487443b5.mp4

**Comment by Repairdesk-QA** [comment]
Hello @alliedcomputers,
Hope you are doing well.

I have checked your issue again and have made a short video. Kindly have a look at that:
https://www.screencast.com/t/vGLZ9bK4

If you verify at your end again on your account it would be really kind and if you think we are missing some steps, please let us know.

Your help & efforts would be highly appreciated.
Regards,
Quratul Ain

**Comment by alliedcomputers** [comment]
Thanks for the video but this is not happening on our tickets.

**Comment by Repairdesk-QA** [comment]
> Thanks for the video but this is not happening on our tickets.

No need to worry @alliedcomputers, we are just checking at our end. It seems an account-specific issue. I will discuss this with our development team and will let you know further. 
Please be with us, your support means a lot to RepairDesk.

Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
For internal use only: https://repairdesk.atlassian.net/browse/RB-3799

**Comment by Repairdesk-QA** [comment]
Hello @alliedcomputers,
Hope you are doing well.

As per discussion with our Development Team, this Edit Customer Comment/Diagnostic Notes functionality is applicable **after the date of fix that was 14 Sep, 2021.** Comments/Diagnostic Notes before 14 Sep, 2021 will have to make Editable from backend (will be done by our developers) and it's not possible to do this for all the Tickets (that might cause functionality disturbance). 

If you want to take this functionality for previous tickets, kindly share ticket numbers via email address.
**You can share ticket numbers on:  qurat-ul-ain@repairdesk.co**

Looking forward to hearing back from you and hopefully speaking soon.

Thanks & Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @alliedcomputers,
Hope you are doing well.
 
Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Regards,**
Quratul Ain
