### ISSUE TITLE
ISSUES IN REPAIR DESK

### ISSUE THREAD

**Issue by ZAGRAL** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1705]
please my query is that in invoice DASHBOARD pls add assigned column also we don't wont to go in every ticket to see who is assigned for product repair

**Comment by Repairdesk-QA** [comment]
Hey @ZAGRAL 
Azka here
I hope you are doing well.
I have checked on your concern but we need some elaboration on the purpose of this requirement. Because invoices do not get assigned to any  employee only tickets do and tickets dashboard has a column of "assigned to" as shown in attached screenshots.
https://www.awesomescreenshot.com/image/13711418?key=4d92695255a1f00e3ec361b57558504a
https://www.awesomescreenshot.com/image/13711502?key=1bb1bf6cd99cd44326fbb5bbdcb199ec 
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards

**Comment by ZAGRAL** [comment]
But in this there is no invoice number

Sent from Yahoo Mail on Android 
 
  On Mon, 20 Sep 2021 at 5:04 pm, ***@***.***> wrote:   


Hey @ZAGRAL
Azka here
I hope you are doing well.
I have checked on your concern but we need some elaboration on the purpose of this requirement. Because invoices do not get assigned to any employee only tickets do and tickets dashboard has a column of "assigned to" as shown in attached screenshots.
https://www.awesomescreenshot.com/image/13711418?key=4d92695255a1f00e3ec361b57558504a
https://www.awesomescreenshot.com/image/13711502?key=1bb1bf6cd99cd44326fbb5bbdcb199ec
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Repairdesk-QA** [comment]
Hey again,
Thanks for your update on this. Let me discuss this with my development team and I will let you know once the improvement is released.
I hope that if there’s anything else I can do for you, you won’t hesitate to let me know. 
Thanks and Regards
Azka

**Comment by Repairdesk-QA** [comment]
Hey @ZAGRAL 
Hope you are doing well.
After discussion with team we have reached to the conclusion that we can add invoice id column in ticket listing where assigned to column is already added. I hope it will  work for you fulfilling your requirement.
Please let me know if I can help you in anything else.
Thanks and Regards
Azka

**Comment by Repairdesk-QA** [comment]
For internal use only:
https://repairdesk.atlassian.net/browse/REP-3298

**Comment by ZAGRAL** [comment]
PLEASE CHECK ATTACHMENT IN THIS WE WANT TO ADD INVOICE COLUMN BECAUSE WE HAVE INVOICE ID IN CSV FILE ITS GOOD THAT IN CSV FILE THE TICKET ID WILL COME THEN ITS BETTER TO FIND UNASSIGNED EASILY 
    On Tuesday, September 21, 2021, 03:09:02 PM GMT+5:30, Repairdesk-QA ***@***.***> wrote:  
 
 


Hey @ZAGRAL
Hope you are doing well.
After discussion with team we have reached to the conclusion that we can add invoice id column in ticket listing where assigned to column is already added. I hope it will work for you fulfilling your requirement.
Please let me know if I can help you in anything else.
Thanks and Regards
Azka

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZAGRAL** [comment]
THEN PUT TICKET COLUMN IN CSV FILE WHEN WE DOWNLOAD DAILY REPORT. I KNOW EVERY TICKETS CONTAINS INVOICE BUT EVERY INVOICE DOES NOT HAVE TICKET BUT ITS NECESSARY TO GET TICKET COLUMN IN CSV FILE BECAUSE MANY EMPLOYEE ARE NOT PUTTING DAILY THERE NAME IN ASSIGNED TO AFTER A MONTH WE WANT TO CHECK A ASSIGNED TO EVERY MONTH. PLEASE INSERT INVOICE COLUMN IN MANAGE TICKET DASHBOARD FOR EASY TO SEARCH WHO HAVE ASSIGNED THE TICKET 
2. PLEASE INSERT SHORTCUT KEY IN VIEW TICKET e.g. ALT  + V OR ELSE
PLEASE DO NEEDFUL
THANK YOU 
    On Monday, September 20, 2021, 05:04:44 PM GMT+5:30, Repairdesk-QA ***@***.***> wrote:  
 
 


Hey @ZAGRAL
Azka here
I hope you are doing well.
I have checked on your concern but we need some elaboration on the purpose of this requirement. Because invoices do not get assigned to any employee only tickets do and tickets dashboard has a column of "assigned to" as shown in attached screenshots.
https://www.awesomescreenshot.com/image/13711418?key=4d92695255a1f00e3ec361b57558504a
https://www.awesomescreenshot.com/image/13711502?key=1bb1bf6cd99cd44326fbb5bbdcb199ec
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks & Regards

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZAGRAL** [comment]
PLEASE SOLVE THIS PROBLEM AS SOON AS POSSIBLE. WHEN I HAVE NOT CHANGED ANY OF PASSWORD WHY IT SHOWING INCORRECT EMAIL & PASSWORD (AUTOMATIC ITS CHANGE THE PASSWORD) IT'S VERY URGENT MY WORK IS PENDING
PLS RESOLVE THIS PROBLEM AS SOON AS POSSIBLE ..........

**Comment by Repairdesk-QA** [comment]
Hey @ZAGRAL 
I hope you are doing well.
Kindly contact live support agent for urgent reset password. we can not reset your credentials due to security concerns.
Thanks & Regards
Azka
