### ISSUE TITLE
THREE COLUMN IN INVOICE DASHBOARD

### ISSUE THREAD

**Issue by ZAGRAL** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1708]
WE WANT TO ADD THREE COLUMN WHICH IS EASY FOR USER

![2](https://user-images.githubusercontent.com/91052481/133972062-7bea3412-9fc8-4d67-82b5-3f7a38cbc9ab.jpg)

in the month of end, we have too much difficult to go in every invoice to find who have assigned the product and help us to do work fast with creating your website easier

**Comment by Uzair-RepairDesk** [comment]
Hey, @ZAGRAL  Hope you are doing well.
I can certainly see how suggested improvements would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work during this Quarter. i will keep you posted once we start working on it.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
Humza
