### ISSUE TITLE
INCORRECT EMAIL & PASSWORD

### ISSUE THREAD

**Issue by ZAGRAL** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1713]
PLEASE SOLVE THIS PROBLEM AS SOON AS POSSIBLE. WHEN I HAVE NOT CHANGED ANY OF PASSWORD WHY IT SHOWING INCORRECT EMAIL & PASSWORD (AUTOMATIC ITS CHANGE THE PASSWORD) IT'S VERY URGENT MY WORK IS PENDING
PLS RESOLVE THIS PROBLEM AS SOON AS POSSIBLE ..........

![image](https://user-images.githubusercontent.com/91052481/134608562-28309a85-b308-402e-869b-cd76740dbec8.png)

**Comment by Repairdesk-QA** [comment]
Hello @ZAGRAL,
Hope you are doing well.

We have checked your concern and assigned it to the development team, they will check and inform you about the updates.
Your patience means a lot.

**Regards,**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @ZAGRAL,

We have checked from the backend, there was no update about your password change.
Please check again your password, remove extra spaces & if still, you can't log in,  you can use our **Forgot Password** option.
That would be more secure and easy for you.
I hope this will solve your issue and if there's anything else with which I may assist, please do not hesitate to reach us.

**Regards,**
Quratul Ain

**Comment by jphansendk** [comment]
Maybe you should disable caps lock on your computer and try again? The password is case sensitive.

**Comment by ZAGRAL** [comment]
please reset my password and give its very urgent
    On Friday, September 24, 2021, 10:08:27 AM GMT+5:30, Repairdesk-QA ***@***.***> wrote:  
 
 


Hi again @ZAGRAL,

We have checked from the backend, there was no update about your password change.
Please check again your password, remove extra spaces & if still, you can't log in, you can use our Forgot Password option.
That would be more secure and easy for you.
I hope this will solve your issue and if there's anything else with which I may assist, please do not hesitate to reach us.

Regards,
Quratul Ain

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ZAGRAL** [comment]
sir i have check all keys but its showing incorrect email or password please reset my password & give me its very urgent my work is pending since last 2 days

    On Friday, September 24, 2021, 11:16:52 AM GMT+5:30, JP Hansen ***@***.***> wrote:  
 
 


Maybe you should disable caps lock on your computer and try again? The password is case sensitive.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Repairdesk-QA** [comment]
Hello @ZAGRAL,
Hope you are doing well.

Due to privacy concerns, we can't change or update your password on Git.
Please go to live chat of the Repairdesk Website. Our support agents will fix this on live chat within 2 minutes.
Please have a look at this image attached
![image](https://user-images.githubusercontent.com/39614480/134634928-d46bbb37-5348-477a-aff4-92d8eb6a9ac1.png)

**Regards,**
Quratul Ain
