### ISSUE TITLE
RMA + Inventory Bug/Glitch 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1715]
Hello, our RMA section messes up our quantity on hand numbers when the RMA status is switched from in progress to sent to supplier. I sent video to Fahad.

**Comment by Repairdesk-QA** [comment]
Hello @Omar1892,
Hope you are doing well.

Let me check this with Fahad and will update you shortly.
Your patience would be highly appreciated.

**Regards,**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Omar1892,
Hope you are doing well.

I have checked your concern and wanted to tell you that this is the current functionality of the RepairDesk.
When we set RMA's status In Progress, we meant to open that RMA and when we set Sent to Supplier, it means we have nothing to this with that item in the RMA because that has been sent to the supplier. That's why every time we change status from In Progress to Sent to Supplier it decreases the Quantity by 1.

If we have an RMA's status Sent to Supplier, we can restrict this to not change again to In Progress. So you can't decrease your quantity more than once.
If you want us to do the above mentioned restriction, please let us know.
We will be happy to solve your issues

**Regards,**
Quratul Ain

**Comment by Omar1892** [comment]
If we have an RMA's status Sent to Supplier, we can restrict this to not change again to In Progress. So you can't decrease your quantity more than once.
If you want us to do the above mentioned restriction, please let us know.
We will be happy to solve your issues 



Yes please set it up the way it was before. Its causing a lot of issues in my store the way it is now. 

Thank you.

**Comment by Uzair-RepairDesk** [comment]
Hey @Omar1892  Hope you are doing well, now we will add a restriction that once RMA is marked as **sent to supplier** then the user can not change it to **In progress** again. we will update you here once its live.

Regards:
Humza

**Comment by Repairdesk-QA** [comment]
For Internal Use Only: https://repairdesk.atlassian.net/browse/REP-3319

**Comment by Omar1892** [comment]
@Uzair-RepairDesk My question would be now. If we can't switch it back from sent to supplier to in progress it we will not be able to make any edits to the RMA if need it. How can we edit an RMA if the option to edit the RMA isn't there?

**Comment by Omar1892** [comment]
@Uzair-RepairDesk Can I get this fixed? or can I get an answer to my question. We've being stuck with issue for the past 2 weeks.

**Comment by Uzair-RepairDesk** [comment]
Hey @Omar1892  once you mark RMA as sent to supplier then the on-hand stock is deducted from the system. now you will have the option to either take a refund or add a credit note. I will ask Fahad to get a call scheduled and he will update you in detail.

Regards:
Humza

**Comment by Omar1892** [comment]
I'm not sure if you understand what is going on or if you saw the video I sent you. But the issue still there and I just don't understate why you guys would change an option that need no fix. Its causing issues and I need a solution for it that doesn't include me having to go through each dam RMA manually if I have to switch them from Sent to supplier to in progress each freaking time. That is the dumbest thing ever.

**Comment by Omar1892** [comment]
Do I really have to keep on pushing you guys for you guys to do your work. I haven't heard from you guys. This is ridiculous for me to be pushing for a service that should be provided since Im a paying costumer. I would like to talk to a manager about this issues since no one cares.

**Comment by Repairdesk-QA** [comment]
Hello @Omar1892,
Hope you are doing well.

We sincerely apologize for the inconvenience and we have released a fix for this issue. Can you please confirm if you are still getting the same issue?
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Omar1892,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain
