### ISSUE TITLE
Partial Refund

### ISSUE THREAD

**Issue by RepairDeskPOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#172]
We should add an option for partial refund.

Let's say customer buys 3 cases on one invoice how do I just return and refund just one or how about restocking fee like a 15% restocking fee

**Comment by ibroken** [comment]
Yes please 
Some companies may have a restocking fee for cases and such 
Or many other situations where we may not want to refund full invoice amount

**Comment by Uzair-RepairDesk** [comment]
We added functionality that allows you to refund a partial amount with respect to "Quantity" or "Amount" for fully paid invoices. You can find more details from the following link:-
https://repairdesk.uservoice.com/knowledgebase/articles/895113-how-can-i-process-refund-exchange-in-repairdesk
