### ISSUE TITLE
POS Ticket Currency Setting

### ISSUE THREAD

**Issue by AVECorp** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1720]
Hi Team,

The default system shows the currency as USD, regardless of the setting in the Store settings.

![image](https://user-images.githubusercontent.com/91883389/135839723-5d994eea-8994-4618-af2c-fcc775de0369.png)

![image](https://user-images.githubusercontent.com/91883389/135839821-dc67e0d0-9587-4707-a1e8-0f489b50cf9b.png)

**Comment by Repairdesk-QA** [comment]
Hey @AVECorp 👋 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by Repairdesk-QA** [comment]
Hey, @AVECorp I hope you are doing well.
The issue has been fixed. You can check it at your convenience. 

I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Thank you.
