### ISSUE TITLE
Ticket Status Search Not Functioning

### ISSUE THREAD

**Issue by AVECorp** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1723]
Hi Team,

The status filter on the ticket window is not functioning correctly.
When a status is selected, and you click "confirm" to enable the filter no tickets are showing (example below)
![image](https://user-images.githubusercontent.com/91883389/135946145-3e673dd2-fdca-40e6-abd3-be625e8daca0.png)

But when using the advanced filter the filtered search works fine;
![image](https://user-images.githubusercontent.com/91883389/135946547-cf965b86-de6b-44e0-b8ae-9190ce3f19b1.png)

**Comment by Repairdesk-QA** [comment]
Hey @AVECorp 👋 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by Repairdesk-QA** [comment]
Hey @AVECorp 

Hope you are doing well!
The reported issue has been fixed. You can check it at your end as per convenience. 
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
Hina
