### ISSUE TITLE
Ability to report total sum of commissions against an individual employee.

### ISSUE THREAD

**Issue by UrgentPhoneRepair** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1730]
After promising employees commissions on things they have sold, it is now extremely time consuming adding these up line by line. I feel there should be a way to report all total commissions within the chosen timeline. Please help find a faster solution to this. Thank you!

This is a secondary request if possible. I set quotas on certain items for them to receive commissions for our items we push, and if they don't meet the quota (this means they aren't making effort to push it) they will not receive commissions, because they are only making passive sales. Right now I have to click each invoice and see what the item was individually and make sure they have reached their quota for the month for that item. One of ours is "Protection Pro". They are required to sell at least 30 within the 30 days to get paid for it. Without the quota, employees can make extra money off of customers that intended to buy it in the first place. I have ideas on how this can function to its fullest, but at the very least it would be nice to have the ability to see what product or "product name" was sold at a glace when viewing the line by line report.

**Comment by Repairdesk-QA** [comment]
Hello @UrgentPhoneRepair,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
