### ISSUE TITLE
PDF Attachements not opening in Tickets

### ISSUE THREAD

**Issue by AVECorp** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1733]
Uploaded PDFs are not viewable on job tickets.
![image](https://user-images.githubusercontent.com/91883389/136733471-ff0119cd-49cb-4bf0-a2e3-719c62649b26.png)

When selected the below page is displayed;

![image](https://user-images.githubusercontent.com/91883389/136733461-a49d4d6b-df7c-49d7-8754-360bd834a3ea.png)

**Comment by Repairdesk-QA** [comment]
Hey @AVECorp 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by Repairdesk-QA** [comment]
Hey @AVECorp 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any question.

Thanks!
