### ISSUE TITLE
Purchase order status not updated correctly when line items are deleted

### ISSUE THREAD

**Issue by AbbyCSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1735]
If you have a Purchase order with 2 lines - one received and one not received it will have a status of partially received.  If you then delete the line item that is not received (which happens often these days as orders are not being filled) the purchase order keeps the status of partially received when it should be received as there is now only one line item and it is fully received.

**Comment by Repairdesk-QA** [comment]
_For internal use only:_ https://repairdesk.atlassian.net/browse/RB-3942

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Your reported issue has been fixed.
Please verify at your end and do let us know if you have any questions.
Waiting for your feedback!

**Thanks & Regards,**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.
Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Quratul Ain
