### ISSUE TITLE
No Due Date Notifications

### ISSUE THREAD

**Issue by AVECorp** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1739]
We have noticed that the ticket due dates are not triggering any notification or email to the assigned users.

![image](https://user-images.githubusercontent.com/91883389/137660144-c1660382-1bc0-49ac-bbc5-09ec12650596.png)

**Comment by Repairdesk-QA** [comment]
Hey, @AVECorp  I hope you are doing well.
I can certainly see how suggested improvements would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. We have added to the backlog. I will keep you posted once we start working on it.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
Hina

**Comment by Repairdesk-QA** [comment]
Hey, @AVECorp I hope you are doing well.
Issue has been fixed 

I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Thankyou
