### ISSUE TITLE
Online payments in transaction log not showing up in excel download. 

### ISSUE THREAD

**Issue by RDimprovement** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1742]
When the payment source in the transaction log is "online", the amount of the payment is not showing up in the excel download. Please fix this. Thanks.

**Comment by Repairdesk-QA** [comment]
Hello @RDimprovement,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
