### ISSUE TITLE
Custom Repair Status Not Editable

### ISSUE THREAD

**Issue by AVECorp** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1744]
Hi Team,

We are missing the edit function for custom statuses in Repair Desk 2.0
![image](https://user-images.githubusercontent.com/91883389/138636739-ea936a31-8903-4706-8b86-187ca3012921.png)

**Comment by Repairdesk-QA** [comment]
Hey, @AVECorp I hope you are doing well.
I can certainly see how suggested improvements would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. We have added it to the backlog. I will keep you posted once we start working on it.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
Hina
