### ISSUE TITLE
Edit Estimate - Needs to show sku/part number not just description for product

### ISSUE THREAD

**Issue by AbbyCSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1745]
When you create an estimate for a product you enter the part number.  Once you save it you can only see the part description not the part number/sku.  As I can have multiple products with the same description I need to see what part number was assigned to that estimate.  For example Lenovo T14 - I have multiple sku's that are all T14 i7 16gb 512.  I can't tell which unit I have assigned to the estimate by the part description.  I do not want to put the part number in the description as I don't want the end user to see the manufacturer part  number.

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

I have double checked but couldn't find the video.
It would be great if you check at your end and upload the video again so that we will be able to test it.
Waiting for your response.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @AbbyCSC, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Regards,
Ayesha Aamir

Closing this task for now.

**Comment by AbbyCSC** [comment]
I would like this item to remain open as it has not been resolved.  I don't know what further information you need as I have explained the issue below.  When you edit an estimate it does not show the sku/id of the items.  Compare this to when you edit an invoice and you do see the sku/id.  The problem is I have many parts with the same description and once the estimate is created there is no way to see what model number computer was used on that estimate.

Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line

**Comment by AbbyCSC** [comment]
I have attached a screen shot of an estimate
Repairs - Manage Estimate - Edit existing estimate
You will see that you only see the product description  not the sku/id

I have also attached a screen shot of an invoice
Repairs - Manage Invoices - edit existing invoice
You will see that you can see the sku/id - that is what I would like to see when I edit an estimate.



Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Your reported issue has been assigned to the development team and hopefully, it will be fixed in our next release.
Your patience would be highly appreciated.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_**https://repairdesk.atlassian.net/browse/RB-4171

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Your reported issue has been fixed. Now you will be able to see the SKU of the product item while creating Estimate.
Kindly verify at your end and do let us know if you have any questions or issues.
Waiting for your feedback.

**_Regards,_**
Quratul Ain

**Comment by AbbyCSC** [comment]
The problem is not when you create the estimate but after you have saved the estimate and go back and edit.  When you edit an estimate it only shows description not part number.  That is what I was showing in the photos.  I am out of the office today but can talk to you next week if that would be helpful.
Thank you for your attention to this matter.
Abby

________________________________

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Thank you for your patience and understanding.
Kindly inform us once you are in the office so we can discuss this in more detail.

**_Regards,_**
Quratul Ain

**Comment by AbbyCSC** [comment]
Hello,
Sorry for the delay in responding. I can talk anytime today until 4:00PM EST or anytime Thursday or Friday 9:00AM to 4:00 PM EST.

Thank you
Abby

Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

No issues on that. We totally value your time.
I have checked your concern in invoices too but we are also not able to see the SKU in edit mode.
Actually, this is related to the database & is our current functionality.
I hope you understand but if you still have issues you can tell us or can connect with Danish or Shakeeb our support agents on live chat so that they can look into the issue you are facing in detail?

![image](https://user-images.githubusercontent.com/39614480/144405821-1d8f0d0f-030d-4e93-9e41-12e6d4deaad2.png)

**_Regards,_**
Quratul Ain

**Comment by AbbyCSC** [comment]
Thank you for your reply.
If I understand you correctly, you are saying you understand my issue but that the current functionality.  We don't need a call to discuss if that is the case.

Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line

**Comment by Repairdesk-QA** [comment]
Hello again @AbbyCSC,
Thanks for understanding.
If you have any other questions or feedback for us, please get in touch. 
We really appreciate any suggestions you have.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi @AbbyCSC,
I hope you are doing well. I'm closing this task for now and I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Thanks,
Ayesha Aamir
