### ISSUE TITLE
Bar codes printing & scanning wrong price

### ISSUE THREAD

**Issue by AbbyCSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1749]
When I printed a bar code yesterday from a GRN it printed an amount that was not in any field on the product setup.  On a different product today when we scanned bar code it brought up a sale price that was not anywhere on the product setup.

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

By default, when we print the barcode of a GRN, it will pick the Retail Price.
Hope your query has been solved.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
