### ISSUE TITLE
PO Glitch with Tax-Exempt Items

### ISSUE THREAD

**Issue by Stylemyphones** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1757]
Hello,
There is a time consuming issue happening in the system when I am adding PO items.
The taxes show even though tax-exempt is selected, so I must click on sales-tax, then again tax-exempt for the system to reset to the correct setting needed.
PLEASE HELP!
https://user-images.githubusercontent.com/83790373/138973261-6b5cfaac-0d71-4762-8eb5-18c034598063.mp4

**Comment by Repairdesk-QA** [comment]
Hello @Stylemyphones,
Hope you are doing well.
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Your patience means a lot!

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @Stylemyphones,

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed early next week.
Your patience would be highly appreciated.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_** https://repairdesk.atlassian.net/browse/RB-4078

**Comment by Stylemyphones** [comment]
Great!
Thank you for your help.

Best regards,
Alejandra Salazar

**Comment by Repairdesk-QA** [comment]
Hello @Stylemyphones,
Hope you are doing well.

I would like to inform you that your reported issue has been fixed & live.
Please check at your end & do let us know if you have any questions.
Waiting for your feedback.

**_Regards,_**
Quratul Ain

**Comment by Stylemyphones** [comment]
Great! Thank you it is indeed working on my end too!

Best Regards,
Alejandra Salazar

**Comment by Repairdesk-QA** [comment]
Glad you like it.
Closing this issue as it has been fixed
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for your time. Enjoy your day!

**_Regards,_**
Quratul Ain
