### ISSUE TITLE
Invalid Integrer error when processing manual entry with Stripe integration

### ISSUE THREAD

**Issue by techm89** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1758]
Tried today taking a deposit for an order and every time I was entering the CC information and pressing Pay button it gave me an error saying: Unable to Pay Invalid integer: 7990.000000000001 (79.99 being the deposit amount). I had this issue numerous time and it was going away when I logged out and log back on but right now I am always getting the issue. The issue in in the POS when Stripe as payment on checkout.

**Comment by Repairdesk-QA** [comment]
Hey @techm89, 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks!
Ayesha

**Comment by Repairdesk-QA** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-4124

**Comment by Repairdesk-QA** [comment]
Hey @techm89, 
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let me know if you have any questions.
Thanks,
Ayesha

**Comment by Repairdesk-QA** [comment]
Hi again @techm89, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Regards,
Ayesha Aamir

Closing this task.
