### ISSUE TITLE
Cybertek - thermal receipt layout issue

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1760]
When I change the font on the customer name, address etc to be more readable on the thermal receipt, the store logo disappears and cannot be seen unless i change the format back to default. This is annoying as the customer names and details are hard to read and making them larger and bold solves this issue but i still want the store logo to appear

**Comment by Repairdesk-QA** [comment]
Hi again @Cybertekww, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Regards,
Ayesha Aamir

Closing this task.
