### ISSUE TITLE
Cybertek - Inventory count quantity redundant

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1761]
When doing an inventory count, if i have 5 items, i will put 5 in the quantity box and then scan the item. The count however only shows that 1 item has been scanned.

**Comment by Repairdesk-QA** [comment]
Hello @Cybertekww,
Hope you are doing well.
Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Regards,**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Cybertekww,
Hope you are doing well.

I have checked your issue and wanted to tell you that this is the flow of our system.
When you scan an item, it will increment one every time you scanned that item & if you want to count by adding item name or SKU, you first have to type the name and then the quantity.

Please have this video for reference:
https://www.screencast.com/t/mlLc9MkwaIG

I hope this will solve your query & if not, please do not hesitate to reach us.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Cybertekww,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
