### ISSUE TITLE
Cybertek - importing new items headache

### ISSUE THREAD

**Issue by Cybertekww** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1762]
When I add multiple items using the spread sheet I would like to be able to add in the cost price of the item, even if I have 0 stock of the item. THe only way this is working is that I have to put a 1 in the "New Stock Adjustment" collumn and then add in the cost price to the "New inventory item cost" collumn. THis is annoying as I then have to manually edit each individual items stock level.
I would like to be able to adjust the price of a stocked item even if there is 0 stock in the store.

**Comment by Repairdesk-QA** [comment]
Hello @Cybertekww,
Hope you are doing well.
I have checked your concern and would like to inform you that your requested functionality is already in RepairDesk.
Please have this video attached for reference:
https://www.screencast.com/t/ZGOjOspY

I hope this will solve your problem but if not, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @Cybertekww, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Regards,
Ayesha Aamir

Closing this task for now.
