### ISSUE TITLE
Customer select ALL option

### ISSUE THREAD

**Issue by danmurari** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1765]
Hello Team 

how do we select all customer email list and save as excel file. Currently giving only 500 option and also if you select page 1 and go to page 2 all page 1 will be lost. 

Can you please have select all customer option instead of only 500 which is consuming lot of time. 
![Uploading image.jpg…]()

**Comment by Repairdesk-QA** [comment]
Hello @danmurari,
Hope you are doing well.

We are not able to open the image attached in the description. Can you please share that again so that we will look into your problem?
Waiting for the information required.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @danmurari,
Hope you are doing well.

Just checked your concern & wanted to tell you that If you want to export all the customers at once, you just have to click **_Export Customer_** in the Manage Customer Section without selecting any customer from the list.
Please have this video for reference:
https://www.screencast.com/t/Nh9FrbAm

I hope this will solve your problem but if not, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @danmurari,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
