### ISSUE TITLE
PLEASE Update so Import Wizard MAPs Mobile Sentrix like IG

### ISSUE THREAD

**Issue by Naegele412** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1768]
Hey Guys,

So I've been using RepairDesk for 2 years and it's been a very frustrating 2yrs due to many issues surrounding inventory and models, mapping products, tickets, repairs, etc. I have recently deleted our ENTIRE inventory in an attempt to re-import the products from Mobile Sentrix and Injured Gadgets and have them mapped correctly WITHOUT DUPLICATES. 

Herein lies the problem... Each parts distributor (and even often times the same distributor) doesn't use a unified system for naming their products and devices. Which means that when we import the products, if the name differs slightly the system automatically adds the devices to your inventory and creates duplicates. If for instance you already have the "iPhone X" in your inventory and "iPhoneX" is on the new import or the "iPhone 10", you'll now have 2 or 3 versions of the same model in the computer, then ALLLL the parts for that item are going to be mapped incorrectly or to multple devices etc. It creates a mess and a nightmare! 

This could EASILY be remedied if you guys would simply add the capability to MAP MobileSentrix products, the same as the way we can currently MAP IG. Frankly, this would solve a lot of problems for a lot of shop owners, I've spoken to several that all have similar complaints about the system and we're all doing various things to avoid having problems, doing things to work around it, or purely just being frustrated with it (as I was for 2 yrs now).. 

If you guys could add this functionality, it would be HUGE. I know it would alleviate alot of the reasons why I've considered switching and I know I've spoken to at least a half dozen or more shop owners who have similar complaints. Please try to update this functionality so we can all have better control over our inventory without having to do everything manually. 

Thanks! 
Andrew Naegele
IFIX Enterprises, Inc.

**Comment by Repairdesk-QA** [comment]
Hello @Naegele412,
Hope you are doing well.

We are really sorry for the inconvenience you have been facing for 2 years.
I have noted your issue & will check at my end. Also, needs to discuss this with our Development Team & Product Team. 
Will update you shortly.

Your patience means a lot to **_RepairDesk_**.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Naegele412,
Hope you are doing well.

I have checked your concern but unfortunately, I am unable to reproduce your issue. 
Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @Naegele412, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
**_Regards,_**
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hello @Naegele412,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this when you want to.

**_Regards,_**
Quratul Ain
