### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by ProntoFix** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1771]
API questions
 
- On the get for devices we do not receive the colour variations in the request  (Get /devices )
- On the get for problems we do not receive de detail information  (Get/problems/:id)

**Comment by Repairdesk-QA** [comment]
Hey @ProntoFix, 
I hope you are doing well. Thank you for bringing this to our attention! It's an improvement. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks!
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
**_For internal use:_**
https://repairdesk.atlassian.net/browse/REP-3415

**Comment by Repairdesk-QA** [comment]
**Hey @ProntoFix,**
I hope you are doing well. Your suggested Improvement is live now. Can you give it another try?
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out. 
**Have a good day!**

**Thanks,**
_Ayesha Aamir_
