### ISSUE TITLE
Ticket Search Parameter

### ISSUE THREAD

**Issue by LordofJesters** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1773]
What if we could look up Tickets by comments? or even by most recently edited? I have had a few technicians that had forgotten the exact ticket they were looking at. and when there are multiple of the same ticket type, either of these may be useful parameters.

**Comment by ProductTeam-RepairDesk** [comment]
Hey, @LordofJesters hope you are doing well, I can certainly see how suggested improvements would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work.

Regards:
Humza
