### ISSUE TITLE
Phone Number Formatting 

### ISSUE THREAD

**Issue by XRP2011** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1780]
Could you create an option in settings that allow the user to choose how they wish to have the phone number displayed. Ex:  (123)456-7890 || +1 1234567890. For me, quickly looking at tickets it's easier to read formatted (123)456-7890. Don't know if this has been brought up before but would be awesome to be able to choose. 

Thanks, 
Have a great day.

**Comment by Repairdesk-QA** [comment]
**Hey @XRP2011,**
Ayesha here. I hope you are doing well. Can you please share your business name associated with the RepairDesk account so that we can help you out with this? 
**Thanks!**

**Comment by XRP2011** [comment]
Xcell Repair Plus

**Comment by Repairdesk-QA** [comment]
**Hye @XRP2011,**
Thanks for sharing the details. Let me have this fixed for you. I'll get back to you as soon as I have more information!  
Your patience would be highly appreciated.
_**Regards,**_
**_Ayesha Aamir_**

**Comment by Repairdesk-QA** [comment]
**For internal use only:**
https://repairdesk.atlassian.net/browse/RB-4296

**Comment by Repairdesk-QA** [comment]
Hey @XRP2011,
Ayesha here. I hope you are doing well. We have enabled the mentioned functionality on your account, but it will only work for newly added customers numbers and not for the existing customers numbers. Can you give it another try and let us know if it's working for you?

**Comment by XRP2011** [comment]
Still doesn't show phone number formatted correctly

**Comment by Repairdesk-QA** [comment]
**Hey @XRP2011,**
I hope you are doing well!

Definitely strange! Can you please elaborate on your concern with a relevant screenshot or you can put together a video using Screencastify? Will be happy to advise you once you share additional details. 

_**Thanks,**_ 
_**Ayesha Aamir**_

**Comment by Repairdesk-QA** [comment]
Hi again @XRP2011, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
_**Regards,**_
**Ayesha Aamir**

**Comment by XRP2011** [comment]
Thank you. Everything is good now. Appreciate your help.

**Comment by Repairdesk-QA** [comment]
**Hey @XRP2011,** 

Glad you like it.
Closing this issue as it has been fixed.
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for your time. Enjoy your day!

**_Regards,_**
**_Ayesha Aamir_**
