### ISSUE TITLE
TAX triggers

### ISSUE THREAD

**Issue by ProntoFix** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1782]
About those triggers, here in Belgium we could use them too ;)

Is it possible to make those available for Belgium users too?

Thanks in advance!

![Uploading Schermafbeelding 2021-12-16 om 15.37.13.png…]()

**Comment by ProntoFix** [comment]
![Uploading Schermafbeelding 2021-12-16 om 15.37.13.png…]()

**Comment by ProntoFix** [comment]
<img width="695" alt="Schermafbeelding 2021-12-16 om 15 43 00" src="https://user-images.githubusercontent.com/89073213/146392728-2bb27e30-ad64-469b-a715-6931d2bb0f88.png">

**Comment by ProductTeam-RepairDesk** [comment]
Hello @Repairdesk-QA 
Can we create a task to enable this triggers option for Belgium as well. Thanks

**Comment by Repairdesk-QA** [comment]
**Hello @ProductTeam-RepairDesk,**
Ayesha here. I hope you are doing well. 
Acknowledged! 

**Task link for internal use only:**
https://repairdesk.atlassian.net/browse/REP-3427

**Comment by Repairdesk-QA** [comment]
Hello @ProntoFix,
Hope you are doing well.

Your reported improvement is now live for Belgium too.
Kindly verify at your end and do let us know if you have any questions.

**_Regards,_**
Quratul Ain
