### ISSUE TITLE
taxes

### ISSUE THREAD

**Issue by AMott-2020** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1783]
a way to separate sales taxes from other fees like card processing fees, etc.

**Comment by Repairdesk-QA** [comment]
Hello @AMott-2020,
Hope you are doing well.

Can you please elaborate on your concern? Will be happy to advise you once you share additional details.

**_Regards,_**
Quratul Ain

**Comment by AMott-2020** [comment]
ok i have a card processing fee as well as sales tax but on the overview page it groups everything together as taxes it would be nice to make it separate.

**Comment by ProductTeam-RepairDesk** [comment]
Hey, @AMott-2020 hope you are doing well, can you please share that from which channel you are processing payments. and can you also share the screen where it groups everything together as you said above?

Regards:
Humza

**Comment by AMott-2020** [comment]
i process payments thru blockchyp and yes I will upload a picture of the screen

**Comment by Repairdesk-QA** [comment]
@ProductTeam-RepairDesk FYI!

**Comment by Repairdesk-QA** [comment]
**Hey @AMott-2020,**
**I hope you are doing well.** 

Could you please share the screenshots, or a small video using Screencastify of your process so that we can guide you in a better way?

**Thanks,** 
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hey @AMott-2020, 
Kindly share your business name as well associated with the RepairDesk account. Thanks!

**Comment by Repairdesk-QA** [comment]
Hi again @AMott-2020, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this task for now.

Regards,
Ayesha Aamir
