### ISSUE TITLE
Group Discount

### ISSUE THREAD

**Issue by PostWireless** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1784]
Not sure if its a bug but its driving me crazy lol 

This discount feature only works when there is already a set price added to an item in the problem list. But it will not work when selecting repair charges and adding a custom price. I will try to explain in more detail.

Here is the process (steps) we go through: 
1- select a customer who has been added to a group that has a 30% discount.
2- select mobile repair
3- select manufacture
4- select device
5- select problem - here all our problems listed do not have price, we use this to let technician know what needs to be done to the device.
6 - select parts
7 - details section - her we input all the device info like device IMEI, passcode, tech assigned ect... and also here is where we use the repair charges box to input our desire price. and finally click on confirm.

The program should automatically calculate the discount price from the amount we have specified in the repair charges field but it does not. The only way for the program to apply any group discount is when there is a price already set up on any of the options in step number 5. 
So why give the option to specify your own price in the final tab if we have to add a price to all the problems to all the hundreds of devices already listed in the software in order to apply a discount?

**Comment by Repairdesk-QA** [comment]
Hello @PostWireless,
Hope you are doing well.

Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @PostWireless,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed in the next release.
Your patience would be highly appreciated.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_**https://repairdesk.atlassian.net/browse/RB-4321

**Comment by Repairdesk-QA** [comment]
Hello @PostWireless,
Hope you are doing well.

Your reported issue has been discussed with our **_Business Analyst_** and would like to inform you that this is the behaviour of the system. Group Discount will always be counted on the prices saved in the system, not with runtime changes.

I hope you understand. If you still have any issues or solutions to discuss, please do not hesitate to reach out.
It would be a pleasure to assist you

**_Regards,_**
Quratul Ain

**Comment by PostWireless** [comment]
> Hello @PostWireless, Hope you are doing well.
> 
> Your reported issue has been discussed with our **_Business Analyst_** and would like to inform you that this is the behaviour of the system. Group Discount will always be counted on the prices saved in the system, not with runtime changes.
> 
> I hope you understand. If you still have any issues or solutions to discuss, please do not hesitate to reach out. It would be a pleasure to assist you
> 
> **_Regards,_** Quratul Ain

well it is what it is i guess, seems counter intuitive if you ask me but hey thanks for looking into this. take care.

**Comment by Repairdesk-QA** [comment]
> > Hello @PostWireless, Hope you are doing well.
> > Your reported issue has been discussed with our **_Business Analyst_** and would like to inform you that this is the behaviour of the system. Group Discount will always be counted on the prices saved in the system, not with runtime changes.
> > I hope you understand. If you still have any issues or solutions to discuss, please do not hesitate to reach out. It would be a pleasure to assist you
> > **_Regards,_** Quratul Ain
> 
> well it is what it is i guess, seems counter intuitive if you ask me but hey thanks for looking into this. take care.

Thanks for understanding @PostWireless.
Actually, we are busy with RepairDesk 2.0 and for the time being, we are not doing any improvements.
But in future, if we do regarding this, we will surely update you.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
Enjoy your day!

**_Regards,_**
Quratul Ain
