### ISSUE TITLE
Changing Service Price in a ticket -> Line item doesn't show up on the invoice

### ISSUE THREAD

**Issue by onebitetechnology** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1789]
I noticed when I change the price of a service (or multiple services) on a ticket, contrary to applying a discount, the service line item will not show up on the invoice. The total is there... but the line item will be missing. 

Thanks!

**Comment by Repairdesk-QA** [comment]
Hello @onebitetechnology,
Hope you are doing well.

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @onebitetechnology,
Hope you are doing well.

I have checked your concern with both the cases (with/without discount) and is working fine on our end.
Kindly have a look at the attached videos for the steps I have followed.
**_Without Discount_**
https://www.screencast.com/t/fr06PJqe0Og

**_With Discount_**
https://www.screencast.com/t/OuhTqR0nIB

If you are following steps other than that or I am missing one, kindly let me know.
Would be great if you can share a video of this issue or detailed steps so we can investigate in detail. **_You can put together a video using Screencastify._**
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**_Thanks & Regads,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @onebitetechnology, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Regards, 
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hi again @onebitetechnology, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Closing this task for now.

Regards,
Ayesha Aamir
