### ISSUE TITLE
Email Reconciliation Report Option

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#179]
It would be nice if there was an option to receive daily reconciliation report via email. Admin should be able to specify email address where it should be sent.

![image](https://cloud.githubusercontent.com/assets/21986026/21541830/63ef55d4-cddb-11e6-947b-1574718c8bc0.png)

**Comment by luisvae** [comment]
It would be great to have in the reconciliation report the Totals, totals per payment method, total in repairs, total in sales and listing the sales in a PDF.

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk

**Comment by Uzair-RepairDesk** [comment]
Its already done
![uzairshah shiftclosesetting cashdrawer](https://user-images.githubusercontent.com/22955861/51454928-10139080-1d69-11e9-908a-98aaa4085a1a.png)
