### ISSUE TITLE
Getting an error message while creating the invoice through API

### ISSUE THREAD

**Issue by mmahmood2014** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1790]
We have used the sggested method to create invoice though API and getting below error:

"Your Request is invalid system is unable to find Items object in you request"

We are using this format:

**create POST /invoices/:id**

Request Sample:
{"summary":{"customer_id":"388","due_on":"1472122800","created_date":"1472122800"},"items":[{"product_id":"1742698","sku":"090000","name":"Antenna Interconnect Cable for iPhone 5","quantity":"1","description":"test desc","notes":"test notes","line_discount":"","price":"30.00","gst":"3.00","taxclass":"1047"},{"product_id":"40775","description":"","notes":"test notes","sku":"090000","name":"Antenna Interconnect Cable for iPhone 5","quantity":"1","line_discount":"","price":"18.33","gst":"3.67","taxclass":"1047"}]}

Can you suggest what we are doing wrong or you have any different format? or sample code?

**Comment by Repairdesk-QA** [comment]
Hello @mmahmood2014,
Hope you are doing well.

The API issue needs to be discussed with the Development Lead, will update you shortly after the discussion.
Your patience means a lot to **_RepairDesk._**

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @mmahmood2014,

Please make sure the request type is JSON and a POST request.
the URL must be https://api.repairdesk.co/api/web/v1/invoices?api_key=api_key to create invoice

Kindly share your feedback with us, means a lot.

**_Regards,_**
Quratul Ain

**Comment by mmahmood2014** [comment]
It works fine, Thank you for your reply.

**Comment by Repairdesk-QA** [comment]
Glad your issue has been fixed.
If there is anything else with which I may assist, please do not hesitate to reach out

**_Regards,_**
Quratul Ain
