### ISSUE TITLE
Getting Trade in Items from Inventory API

### ISSUE THREAD

**Issue by mmahmood2014** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1791]
Is there any way to get tradein items using the inventory API?

**Comment by Repairdesk-QA** [comment]
Hello @mmahmood2014,
Hope you are doing well.

This needs to be discussed with our Development Lead. I will update you shortly after the discussion.
Your patience means a lot to RepairDesk.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @mmahmood2014,

This is the comment from our Development Lead, kindly have a look into this:
we have an inventory listing API that returns accessories and parts by default.
but if you pass an extra parameter type then it will return a trade-in
the request URL will look like this
https://api.repairdesk.co/api/web/v1/inventory?type=2&api_key=api_key

**Comment by mmahmood2014** [comment]
Thank you for your response. We have checked and its only returning instock trade in items. Is there any parameter we can pass which can give us all tradein items no matter if they are in stock or not?

**Comment by Repairdesk-QA** [comment]
Hello again @mmahmood2014,
your requirement has been assigned to our Development Lead and will be fixed in the next release.
Will update you shortly once done.

Your patience means a lot to RepairDesk

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only: _**https://repairdesk.atlassian.net/browse/RB-4367

**Comment by mmahmood2014** [comment]
How soon do you think it will take?

**Comment by Repairdesk-QA** [comment]
> How long do you think it will take?

hopefully, it will be live till 6 today.

**Comment by Repairdesk-QA** [comment]
Hello again @mmahmood2014,
Hope you are doing well.

We have added a new parameter to call api with an extra param named “tradeinstatus” with value “all“
like
 /inventory?type=2&tradeinstatus=all
so API will return all tradein items

Kindly try now and let us know if you have any issues.
Waiting for your feedback!

**_Regards,_**
Quratul AIn

**Comment by mmahmood2014** [comment]
Dear Quratul Ain,

Thank you for your team to help us out with the API. Our client has been using your system from a while and he wanted to have access of tradein items from a while. New changes you have done are working well and we are moving forword with the integration. 

Thanks again for your prompt response and support. 

Ragards,

Mansoor

**Comment by mmahmood2014** [comment]
Have another small question. The API is not returning the "Condition" column of the product. Can you tell me how we will get it using API?

**Comment by Repairdesk-QA** [comment]
Hello @mmahmood2014,
Hope you are doing well.

Glad you like it.
Helping you is our priority.
I will inform you about your recent query after discussing it with our Developer.
Will update you shortly.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
> Have another small question. The API is not returning the "Condition" column of the product. Can you tell me how we will get it using API?

Our Development Lead is looking into this and will update you shortly after the fix.
Your patience means a lot.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_** https://repairdesk.atlassian.net/browse/RB-4378

**Comment by Repairdesk-QA** [comment]
Hello again @mmahmood2014,

Now you can get the Condition column too. 
Kindly check and let us know with your feedback.
Waiting for your feedback.

**_Regards,_**
Quratul Ain

**Comment by mmahmood2014** [comment]
We have checked and condition column is coming up fine in API resultset. Thank you very much for taking time to add this. I will let you know if we need anything else.

**Comment by Repairdesk-QA** [comment]
> We have checked and condition column is coming up fine in API resultset. Thank you very much for taking time to add this. I will let you know if we need anything else.

Glad you like it!
Please do not hesitate to reach out if you have any queries.
Have a nice day.

**_Regards,_**
Quratul Ain
