### ISSUE TITLE
POST Repair problem with Custom Status

### ISSUE THREAD

**Issue by adigsm07** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1792]
Hello, Adis here.
I can't use POST Repair Condition because I use custom status. Can you guys resolve this bug?

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
Hey @adigsm07,
Hope you are doing well. 

I have checked your concern but unfortunately, I am unable to reproduce your issue and everything is working fine on my end. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using **Screencastify**.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Thanks,
Ayesha Aamir

**Comment by adigsm07** [comment]
Oke I will be back with an video.

**Comment by Repairdesk-QA** [comment]
Hi again @adigsm07, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hi again @adigsm07, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Closing this task for now.

Regards,
Ayesha Aamir
