### ISSUE TITLE
Updated Ticket Status to custom status after payment is received.

### ISSUE THREAD

**Issue by Jonmarr95** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1793]
Currently the only option after taking payment is to set the ticket to "Repaired & Collected" however for shops that have disabled the default statuses this causes confusion on the tickets screen. It would be very helpful if we could choose what the default status is after the invoice is paid.

**Comment by Repairdesk-QA** [comment]
Hello @Jonmarr95,
Hope you are doing well.

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @Jonmarr95,
We have checked your concern and it might seem like a bug.
I'm going to reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_** https://repairdesk.atlassian.net/browse/RB-4371

**Comment by Repairdesk-QA** [comment]
Hello @Jonmarr95,
Hope you are doing well.

I have discussed your concern with our Development Team and would like to inform you that this is the flow of our system.
But if you uncheck the **_Repaired & Collected_** when taking the payment from POS or Manage Invoices, your status will not get changed and you can set it to whatever status you want.

**_For better understanding, kindly look into the video attached:_**
https://www.screencast.com/t/IGmHwKUKcD3B

I hope your query has been answered but if you still have questions, please do not hesitate to reach out.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Jonmarr95,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain
