### ISSUE TITLE
New Item through PO, Model Name Glitch

### ISSUE THREAD

**Issue by Stylemyphones** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1794]
Hello,

I am writing today because there is a glitch I keep getting when I need to add a new item while creating a new PO.

I try to enter in the Manufacturer, and then the Model; however, it seems that the manufacturer doesn't always registers in the system because ALL the models from ALL manufacturers still come up.
Then I must spend extra time clearing and resetting the manufacturer's name in order for the models to reflect that set of manufacturers.

Please see the attached video for more clarity and let me know if I may further assist.

Thank you and Best Regards,
Alejandra Salazar.

https://user-images.githubusercontent.com/83790373/147514371-3e6b821a-dafb-49da-ac8f-a57067aeb230.mp4

**Comment by Repairdesk-QA** [comment]
Hello @Stylemyphones,
Hope you are doing well.

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @Stylemyphones,
Hope you are doing well.
Thanks for sharing the detailed video. It is really time-saving and helped us to understand the issue.

I have checked your concern and would like to inform you that upon selecting a Manufacturer, the dropdown in Device/Model will show all the devices which have been mapped against that Manufacturer.
**_You can see your devices from_**
Store Settings -> Module Configuration -> Manage Devices ( in Manufacturer, select any)

**_For better understanding, kindly look into the video attached:_**
https://www.screencast.com/t/Q6PBkQoUo

Kindly review your store settings/manage device section to see which devices have been mapped against the Manufacturer.

I hope your query has been answered but if you still have any questions or want to share more issues, please do not hesitate to reach out.
 Helping you is the priority of RepairDesk.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Stylemyphones** [comment]
Thank you Quratul,
I hope you're having a great day!

I have checked the section of the settings you mentioned, and also all the devices are mapped against a specific manufacturer.
However, it seems as if the manufacturer doesn't register when I select it before adding the specific model as I am creating a new item through the PO module since ALL the devices from ALL the manufacturers come up.

Please let me know if perhaps we can have a meeting over phone and AnyDesk in order to help clear up the issue.

Thanks so much & Regards,
Alejandra Salazar.

**Comment by Stylemyphones** [comment]
Hello,
I have now gone deeper into all the devices and I am getting error when I try to delete some that are not correctly paired.

Why is this happening?
Please help!

**Comment by Repairdesk-QA** [comment]
Hello @Stylemyphones,
Hope you are doing well.

You can schedule a call with **_Danish Hassan, Customer Success and Support_**. Kindly book a slot from the link in order to connect with him:
https://calendly.com/danishhassan

I am sure he will be able to assist with the above query and take relevant information so we can address your concerns timely.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
> Hello, I have now gone deeper into all the devices and I am getting error when I try to delete some that are not correctly paired.
> 
> Why is this happening? Please help!

It would be great @Stylemyphones  if you can share the error screen or message to help us understand the issue.

**_Regards,_**
Quratul Ain

**Comment by Stylemyphones** [comment]
Hello Quratul,
I hope you are having a great day too!

I have tried to schedule a call with Danish; however, he only has time slots available when I am no longer in the office as you can see below, so is there another agent with day time appointment slots or will Danish get more times?
![image](https://user-images.githubusercontent.com/83790373/147692685-427fd8a7-347d-48ef-adcd-4bc8b1acb1ad.png)

Also, below I have added a video with the error I am getting when attempting to delete the wrongly paired devices.
The error doesn't make sense since we would not have erroneously paired devices on inventory.

Please adivise.

https://user-images.githubusercontent.com/83790373/147692468-e507d868-c1ef-4548-8e55-3068f8184e26.mp4

**Comment by Repairdesk-QA** [comment]
Hello @Stylemyphones,

Yes you schedule a call with our other support agents like
**_Fahad Imran, Manager Customer Success and Support._**
https://calendly.com/fahadimran
OR
**_Faizan Zaheer_**
https://calendly.com/faizan-zaheer20111/trainings?month=2020-09

I am sure they will be able to assist with the above query and take relevant information so we can address your concerns timely.

Also, the error message is because you have some inventory items against that device in the Inventory.
![image](https://user-images.githubusercontent.com/39614480/147721819-2c2143eb-12aa-487e-8fa6-215afc87e1e9.png)

To resolve this error, you can have two options.

**_First,_** If you want to remap that device, you can delete the inventory item and then delete the device.
**_As shown in the given video:_**
https://www.screencast.com/t/YB7qSDzZ

**_Second,_** You can just edit that device and reset the Manufacturer.
**_As shown in the video given below:_**
https://www.screencast.com/t/eDBGgPM3gU

You can go with any option at your convenience.

I hope your query has been answered but if not, please do not hesitate to reach out.
Helping you, is our priority.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Stylemyphones** [comment]
Hello Quratul,

Thanks so much for your message with these very helpful videos.

I have already scheduled an appointment with Sir Fahad, and also, I have one question... If I edit the devices and reset the manufacturer, will that cause for doubles?
If so, what would be most appropriate to do, or what would proceed?

Thank you in advance for your support. I wouldn't want to do all this work to remap, and it turns out being double work.

Best Regards,

**Comment by Stylemyphones** [comment]
Hello,
I have also tried to remove the erroneously matched devices and have checked that there is no inventory before deleting it.
However, I get the same error as if there were inventory.

Please see the attached video.
Thank you and Best Regards,

https://user-images.githubusercontent.com/83790373/147781182-d2a99931-69a3-44bf-b706-bdba7c9b5e37.mp4

**Comment by Repairdesk-QA** [comment]
> Hello Quratul,
> 
> Thanks so much for your message with these very helpful videos.
> 
> I have already scheduled an appointment with Sir Fahad, and also, I have one question... If I edit the devices and reset the manufacturer, will that cause for doubles? If so, what would be most appropriate to do, or what would proceed?
> 
> Thank you in advance for your support. I wouldn't want to do all this work to remap, and it turns out being double work.
> 
> Best Regards,

Hello @Stylemyphones,
It is great that you have scheduled a call with Sir Fahad Imran. I hope you will get all answers to your queries.
Also, I would like to add that editing a manufacturer against a device will not cause duplication.
And if you have an inventory item against that device, you also have to reset the Manufacturer from the inventory.
**_Please have this video for reference:_**
https://watch.screencastify.com/v/aQjJ4t46wrBCQTI9PUGE

I hope you got your answer but if not, please do not hesitate to reach out.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
> Hello, I have also tried to remove the erroneously matched devices and have checked that there is no inventory before deleting it. However, I get the same error as if there were inventory.
> 
> Please see the attached video. Thank you and Best Regards,
> 
>  Device.and.Manufacturer.Error.with.No.Inventory.mp4

I will check this from the backend and will update you shortly.
Your patience means a lot.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Stylemyphones,
Hope you are doing well.

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed early next week.
Your patience would be highly appreciated.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_**https://repairdesk.atlassian.net/browse/RB-4399

**Comment by Repairdesk-QA** [comment]
Hello @Stylemyphones,
Hope you are doing well.

Your reported issue against devices has been fixed. Kindly verify at your end and do let us know if you have any questions or have any issues.
Waiting for your feedback!

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @Stylemyphones,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain
