### ISSUE TITLE
Pay Now button missing from email Device Repaired template

### ISSUE THREAD

**Issue by coreyjiles** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1797]
When you send a Device Repaired email with the {payment_button} macro, the button is not displaying in the email. This is when using RepairDesk payments as the payment processor.

**Comment by Repairdesk-QA** [comment]
Hello @coreyjiles,
Hope you are doing well.

Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @coreyjiles,

I have checked your concern and would like to inform you that the macro {payment_button} is working fine on our end.
**_Kindly look into the video attached:_**
https://www.screencast.com/t/K67EKoumSyjU

Kindly make sure the placement of {payment_button} macro in your email template and let us know with the feedback.
Waiting for your response.

**_Regards,_**
Quratul Ain

**Comment by coreyjiles** [comment]
We do not use PayPal payments as shown in your video (we use RepairDesk payments through BlockChyp). The macro does show the Pay Now button when emailing an, but not on ticket.

**Comment by Repairdesk-QA** [comment]
Hello again @coreyjiles,
Hope you are doing well.

I have checked again and would like to inform you that the macro {payment_button} is related to Invoices and will be working with that. We can't use this in Tickets.
This is the flow of our system.

I hope you understand but if there is anything else with which I may assist, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @coreyjiles,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Thanks & Regards,_**
Quratul Ain
