### ISSUE TITLE
Inventory Count - Inv Adj report has bug with negative variances

### ISSUE THREAD

**Issue by AbbyCSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1798]
Manage Inventory Count - Inventory Adjustment Report - if the variance between the expected count and actual count is negative the cost variance should be negative.  It works correctly when the counted number is 0 but if the counted number is a positive number but less than the expected  count the cost variance is showing as a positive value instead of negative

Example Expected 10, Counted 8 Qty Variance -2 Cost Variance should be -20 but it shows as 20 (assuming a cost of 10)

If the expected  is 10, counted is 0 variance is -10 the cost variance correctly shows -200. it seems to be a problem with the counted is something other than 0.

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @AbbyCSC,

I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using Screencastify.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Waiting for your response!

**_Regards,_**
Quratul Ain

**Comment by AbbyCSC** [comment]
I find it very frustrating that you have never been able to duplicate my issues despite the fact that I have explained how it failed.  I do not have time to create videos showing you bugs.  Attached is the report where I have entered a few comments so that you can clearly see there is a bug in the report.
Thank you
Abby

Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Sorry for the inconvenience but the purpose of asking for the video or picture of the screen is just for confirmation.
Issues with calculations would be better understood if we have screenshots or video.
We are still looking into it.
Your patience would be highly appreciated.

**_Thanks & Regards_**,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @AbbyCSC,
Hope you are doing well.

We have checked and would like to inform you that Inventory Count is displaying cost variance negative in both the cases you have mentioned.
Please find the following attachment for reference:
![image](https://user-images.githubusercontent.com/39614480/148173233-f13b8f3b-b141-4556-8ba3-0f62793163f4.png)

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**_Thanks & Regards,_**
Quratul Ain

**Comment by AbbyCSC** [comment]
To clarify the problem is with the report I sent you not with the actual inventory update process.  The report is displaying the cost amount incorrectly.  Please refer to my previous email and look at the REPORT I sent.
Thank you
Abby

Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Sorry to inform you but we have not received any attachments in your email.Would be great if you check again at your end.
It would be really helpful.
Also, we just have stats in Inventory count so we might have an issue with the Inventory count.
The inventory adjustment report has no stats in that.
![image](https://user-images.githubusercontent.com/39614480/148335074-e5b87cfe-aa75-4947-8f59-d84cf336a600.png)
![image](https://user-images.githubusercontent.com/39614480/148335103-01d6ed1d-56e3-468e-a825-3504ed3aab01.png)

Waiting for your response.
Your patience and time mean a lot to RepairDesk.

**_Regards,_**
Quratul Ain

**Comment by AbbyCSC** [comment]
Abby – Have you gotten a response? Brian

Brian Desrosier
Lighthouse Technology Partners
President
Greenwich, CT | 203-242-8648
Managed IT Support<https://lighthousemsp.com/services/managed-services/> | Cyber Security<https://lighthousemsp.com/services/security-compliance/> | Teams & SharePoint<https://lighthousemsp.com/services/sharepoint-collaboration-intranet-portals/>
Ask me about  #Digital Transformation and #Co-Managed IT

From: Abby Katz ***@***.***>
Date: Tuesday, January 4, 2022 at 11:00 AM
To: Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS ***@***.***>, Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS ***@***.***>
Cc: Mention ***@***.***>, Brian Desrosier ***@***.***>
Subject: RE: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Inventory Count - Inv Adj report has bug with negative variances (Issue #1798)
I find it very frustrating that you have never been able to duplicate my issues despite the fact that I have explained how it failed.  I do not have time to create videos showing you bugs.  Attached is the report where I have entered a few comments so that you can clearly see there is a bug in the report.
Thank you
Abby

Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line

**Comment by AbbyCSC** [comment]
Attached is the report I sent you with the original request for assistance.  To be clear the inventory count works properly but the attached report does not.  If you open the report you will see notations illustrating the issue.  The issue is that when the counted amount is less than the expected count but not 0 it displays the cost variance as a positive value rather than a negative value.  I'm sure it is a simply formula error in the program that you can correct if you look at my sample and look at the programming behind it.

Thank you
Abby

Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

It seems to be an account-specific issue. One of our support ninjas will reach out to you to get more information.
Your patience would be highly appreciated.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC ,
Hope you are doing well.

Kindly schedule a call with **_Fahad Imran, Manager Customer Success and Support_**. Kindly book a slot from the link in order to connect with him:
https://calendly.com/fahadimran
I am sure he will be able to assist with the above query and take relevant information so we can address your concerns timely.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @AbbyCSC, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Ayesha Aamir

**Comment by AbbyCSC** [comment]
I am going to put together a list of all my items that I need you to dial in and look at and we can setup a time next week
Thank you
Abby

Abby Katz
Purchasing Manager
Computer SuperCenter of Greenwich
103 Mason St
Greenwich CT 06830
203-661-1700 option 2 Service
203-242-8654 direct line
