### ISSUE TITLE
{amount_due} macro is not calculating correctly

### ISSUE THREAD

**Issue by coreyjiles** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1799]
When sending an invoice via email or SMS, the {amount_due} macro is not subtracting any payments the customer has already made
![screenshot](https://user-images.githubusercontent.com/96924320/148125560-befc5b1e-94fd-4b24-8205-aa835374d63f.png)
![screenshot2](https://user-images.githubusercontent.com/96924320/148125569-85869f0e-db3e-47c3-894e-e467f61a1f8c.png)

**Comment by Repairdesk-QA** [comment]
**Hey @coreyjiles,**
**I hope you are doing well.** 
 
Ayesha here. According to your above mentioned screenshots, the total amount = $125, and the $0 amount is paid that's why Amount Due = $125, which is correct. 

Still, let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
**Hey @coreyjiles,**
I hope you are doing well!

I have checked your concern but didn't find any issue as everything is working fine on our end. Could you give it another try plus would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using **Screencastify**. Attaching a screenshot for reference. 

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Regards,
Ayesha Aamir

<img width="467" alt="Payment Invoice #1391 from Repair Shop (message id_10291248136) - ayesha aamer@repairdesk co - Repai" src="https://user-images.githubusercontent.com/39614480/148168347-eff7b310-eb28-4bbb-bd86-71d455a3a189.png">

**Comment by Repairdesk-QA** [comment]
Hi again @coreyjiles, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hi again @coreyjiles, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Closing this task for now. 

Regards,
Ayesha Aamir
