### ISSUE TITLE
RepairDesk Payments not working with Customer Portal

### ISSUE THREAD

**Issue by coreyjiles** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1800]
As the title says, there is no option in the Customer Portal to pay for an invoice with RepairDesk Payments. I am assuming this is a bug because PayPal works in the portal.
![screenshot4](https://user-images.githubusercontent.com/96924320/148126909-7ce812af-acae-427e-a3b2-9c807fc73c89.png)

**Comment by Repairdesk-QA** [comment]
**Hey @coreyjiles,**
**Hope you are doing well.** 

Actually, the RepairDesk Payments integration is not supported with the Customer Portal. For the time being it is just supported with our Appointment Calendar widget. 

Closing this task as I think your query has been answered and If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Have a good day! 

_**Thanks & Regards,**_
_**Ayesha Aamir**_
