### ISSUE TITLE
Default SKU for newly added products

### ISSUE THREAD

**Issue by MobileFusion** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1803]
Hello Devs.

The issue we are having is when we add a new product we select Vendor/Supplier SKU and then input the said vendors SKU so that if we need to create a P.O. it comes up with the correct part I assume that's what that feature is for? 

The system then genereates a random SKU to use in store which is great so that customers don't see our supplier's SKU. Issue is that everytime we check out with that item it now displays 2 SKUS and we must select one. 

Is it possible to select a defult SKU for the point of sale so that it doesn't make us select a SKU each time
![VENDOR_SKU_1](https://user-images.githubusercontent.com/97478656/148901576-d47ef4a4-c28d-4c75-ae66-c88101e9b0bb.png)
![VENDOR_SKU_2](https://user-images.githubusercontent.com/97478656/148901583-2794d534-3b4e-4de4-8968-ba9fcb48d0b2.png)
?

**Comment by Repairdesk-QA** [comment]
Hey @MobileFusion, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
Hello **@MobileFusion** ,
Hope you are doing well !

I have checked your concern, according to systems current workflow **one** way is this system allowing us to sell non-serialized item with default SKU each time from POS by simple checking out the item from POS where you don't need to select any SKU, you can better check in the attached video, the **other** way is this if you want to sell non-serialized item with default SKU each time than there is no need to create multiple vendor's SKUs against the item, you can always have default SKU available against the item in inventory. 

**Video Reference:** https://www.screencast.com/t/tdxyx58z

Thanks & Regards,
**Nida Khalid**

**Comment by Repairdesk-QA** [comment]
> Hello **@MobileFusion** , Hope you are doing well !
> 
> I have checked your concern, according to systems current workflow **one** way is this system allowing us to sell non-serialized item with default SKU each time from POS by simple checking out the item from POS where you don't need to select any SKU, you can better check in the attached video, the **other** way is this if you want to sell non-serialized item with default SKU each time than there is no need to create multiple vendor's SKUs against the item, you can always have default SKU available against the item in inventory.
> 
> **Video Reference:** https://www.screencast.com/t/tdxyx58z
> 
> Thanks & Regards, **Nida Khalid**

If you have any other questions or if there is anything else with which I may assist, please provide us the video link using Screencastify & do not hesitate to reach out.

**Comment by Repairdesk-QA** [comment]
> > Hello **@MobileFusion** , Hope you are doing well !
> > I have checked your concern, according to systems current workflow **one** way is this system allowing us to sell non-serialized item with default SKU each time from POS by simple checking out the item from POS where you don't need to select any SKU, you can better check in the attached video, the **other** way is this if you want to sell non-serialized item with default SKU each time than there is no need to create multiple vendor's SKUs against the item, you can always have default SKU available against the item in inventory.

> If you have any other questions or if there is anything else with which I may assist, please provide us the video link using Screencastify & do not hesitate to reach out.

> > **Video Reference:** https://www.screencast.com/t/tdxyx58z
> > Thanks & Regards, **Nida Khalid**
>

**Comment by Repairdesk-QA** [comment]
Hello **@MobileFusion** ,
Hope you are doing well !

I have checked your concern, according to systems current workflow **one** way is this system allowing us to sell non-serialized item with default SKU each time from POS by simple checking out the item from POS where you don't need to select any SKU, you can better check in the attached video, the **other** way is this if you want to sell non-serialized item with default SKU each time than there is no need to create multiple vendor's SKUs against the item, you can always have default SKU available against the item in inventory. 

If you have any other questions or if there is anything else with which I may assist, please provide us the video link using Screencastify & do not hesitate to reach out.

**Video Reference:** https://www.screencast.com/t/tdxyx58z

Thanks & Regards,
**Nida Khalid**

**Comment by MobileFusion** [comment]
Okay thank you. I noticed you cannot just input the item code, but you must scan or input the SKU code then it won't ask for the SKU before checking out. This will work as a work around for us and we will use that method going forward.

**Comment by Repairdesk-QA** [comment]
**Hey @MobileFusion,**
 
I really appreciate that you took the time to share your idea. If you have any other questions or feedback for us, please get in touch. We really appreciate any suggestions you have.

**Thanks,** 
**Ayesha Aamir**
