### ISSUE TITLE
RMA without items

### ISSUE THREAD

**Issue by mobilexpertmiami** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1804]
When creating a RMA the system should prevent you to save it if no items has been added.

It had happened to me a couple of times that I forget to click add row and the RMA is saved without any item.

**Comment by Repairdesk-QA** [comment]
Hey @mobilexpertmiami, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
**Hey @mobilexpertmiami,** 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

**Thanks!**
**Ayesha Aamir**

**Comment by Repairdesk-QA** [comment]
**For internal use only:**
https://repairdesk.atlassian.net/browse/RB-4439

**Comment by mobilexpertmiami** [comment]
Ok, do you have any updates on this?

**Comment by Repairdesk-QA** [comment]
Hello @mobilexpertmiami,
Your reported issue is identified and has been assigned to our development team. 
I'll get back to you as soon as I have more information!

Thanks,
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hey @mobilexpertmiami,

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks,
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hi again @mobilexpertmiami, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Ayesha Aamir
