### ISSUE TITLE
Employee Productivity Report

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1805]
The Repair Time only shows for tickets created that day.

So when using Date Wise criteria is correct, but using Repair Wise criteria it does not change to reflect the Repair Time correctly.

**Comment by Repairdesk-QA** [comment]
Hey @afrahm, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,
 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Thanks,
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
**For internal use only:**
https://repairdesk.atlassian.net/browse/RB-4456

**Comment by jphansendk** [comment]
👀

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks,
Ayesha Aamir

**Comment by afrahm** [comment]
Yes looks like that has fixed the issue I mentioned.
However now the success ratio is not changing based on date or repair wise.

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,
I hope you are doing well.

I have checked your concern but the above mentioned scenario is working fine for me. Would be great if you can share a video of this issue or detailed steps so we can release a fix during our next release. You can put together a video using **Screencastify**. Attaching a video from my test account for your reference. 

https://watch.screencastify.com/v/NlcV81KXRcd6DyHg2tua

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Regards,
Ayesha Aamir

**Comment by afrahm** [comment]
In your video you have 100% success ratio when you had 2 assigned jobs and only 1 completed.. should be  50%..

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,

It's not an issue but the current functionality of the **Employee Productivity Report in Repair-Wise** case i.e. in this section the repair jobs completed according to the selected date will be displayed and a repair job will never be completed partially so the **Success Rate will be displayed as 100%** always.

But if you will see the success rate according to the ticket status then kindly apply a Date-wise filter. It will show a 50% success ratio when you had 2 assigned jobs and only 1 is completed.

I hope it helps. Let me know if still you have any question. 

Thanks,
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hey @afrahm,
I am closing this task for now as the reported issue has been fixed. But you can always give me a shout here if anything else comes up!
Regards,
Ayesha Aamir
