### ISSUE TITLE
Ticket Search Function Error

### ISSUE THREAD

**Issue by AVECorp** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1806]
Hi Team,

We are seeing a reoccuring issue when searching for a ticket in the 'manage tickets' screen.
When we filter/search a ticket using the "manufacturer" criteria search we are seeing the default ticket list, not the manufacturer that was selected. Thisis the same regradless of the manufacturer we select in the criteria search.

![image](https://user-images.githubusercontent.com/91883389/149243273-69f8d2a7-885a-4046-8a4e-97e73b30474c.png)

![image](https://user-images.githubusercontent.com/91883389/149243347-70f273f1-17d5-4b00-8af0-0804ae218492.png)

![image](https://user-images.githubusercontent.com/91883389/149243379-e2d8ec55-a362-4388-8a15-f39ef5b9c66f.png)

**Comment by Repairdesk-QA** [comment]
Hey @AVECorp, 
Ayesha here. Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Repairdesk-QA** [comment]
Hey @AVECorp, 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Thanks, 
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
**For internal use only:**
https://repairdesk.atlassian.net/browse/RB-4441

**Comment by Repairdesk-QA** [comment]
Hey @AVECorp,

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks,
Ayesha Aamir

**Comment by Repairdesk-QA** [comment]
Hi again @AVECorp, since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
Ayesha Aamir
