### ISSUE TITLE
Purchase Orders Imports

### ISSUE THREAD

**Issue by kjtechcity** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1814]
We would like to be able to import orders from suppliers and have a purchase ordered created.

**Comment by Repairdesk-QA** [comment]
Hello @kjtechcity,
Hope you are doing well.

I would like to inform you that there is a functionality to import Purchase Order in RepairDesk.
**_For better understanding, kindly look into the video attached:_**
https://watch.screencastify.com/v/EJr6ZyhNa0eOfaj2kftL

I hope this might solve your query but if not, kindly let us know in detail.
We will surely solve your query.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hi again @kjtechcity - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards,
