### ISSUE TITLE
RMA excel export not working. Excel sheet blank. 

### ISSUE THREAD

**Issue by RDimprovement** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1822]
When clicking the blue Export RMA button an excel sheet is downloaded but other than the header it's completely blank. No RMA items are exported. Can this be looked into?

**Comment by Repairdesk-QA** [comment]
Hello @RDimprovement,
Hope you are doing well.

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @RDimprovement,

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed early next week.
Your patience would be highly appreciated.

Thanks & Regards!
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_** https://repairdesk.atlassian.net/browse/RB-4579

**Comment by Repairdesk-QA** [comment]
Hello @RDimprovement,
Hope you are doing well.

Your reported issue has been fixed. Kindly verify at your end and do let us know with the feedback.
Waiting for your kind response.

**_Thanks & Regards,_**
Quratul Ain

**Comment by RDimprovement** [comment]
Fixed, thanks. Would it be possible to add the option to export the description and note fields as well? Would be really helpful!

**Comment by ProductTeam-RepairDesk** [comment]
Hey @RDimprovement  we can show the notes against RMA Export as a user can add notes for an RMA, but the description is added Line wise which is not possible to Show in the export file.

looking forward to hearing from you

Regards,
Humza

**Comment by Repairdesk-QA** [comment]
Hello @RDimprovement,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Waiting for your response.

**_Thanks @ Regards,_**
Quratul Ain
