### ISSUE TITLE
Retail price of used parts for repair on invoice

### ISSUE THREAD

**Issue by ProntoFix** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1834]
In Belgium we are obliged to state on the invoice which parts we have used for the repair and which profit/sales price we include here, on the part separately.

Now it is only possible to charge a price for the service, but the invoice does not state which part was used and what the retail price was for this.

**Comment by ProductTeam-RepairDesk** [comment]
Hey @ProntoFix 
Hope you are doing well, we have a trigger in setting under Module configuration => Receipts => Show part details on the receipt. Enabling this will allow users to view the part being used.
for now, you can view the part used.
Rest of the details I have noted and will add to the roadmap.
Hope this helps if there is anything else I can help you with do let me know.

Regards:
Humza
