### ISSUE TITLE
Cant finish an unlocking ticket because repair time obligatory

### ISSUE THREAD

**Issue by kmcorp27** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1838]
.

**Comment by Repairdesk-QA** [comment]
Hello @kmcorp27,
Hope you are doing well.

Would be great if you can provide us with a short video or screenshots of where you are facing this issue.
This would be really helpful for us to understand this issue.
Waiting for your kind response.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @kmcorp27,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @kmcorp27 
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain

**Comment by kmcorp27** [comment]
We stopped taking in unlocks anyway, the issue still exists, but only for
people who has repair time obligatory enabled.
