### ISSUE TITLE
Is it possible to create our own custom payment ingregation?

### ISSUE THREAD

**Issue by bonbon12** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1839]
Would like to create a custom payment method which when confirmed fires off a call to another POS API.

I have read: https://help.repairdesk.co/knowledgebase/articles/1189105-public-api

**Comment by Repairdesk-QA** [comment]
Hello @bonbon12,
Hope you are doing well.

I have discussed your concern with our development lead and as per discussion with him, I would like to add that it is not possible to create custom payment integration as there is no Open APIs are available for this.
You can contact our support agents via live chat to figure out the best solution.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @bonbon12,
Hope you're doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain
