### ISSUE TITLE
Customer reply doesn't get into repairdesk

### ISSUE THREAD

**Issue by tomdamman** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1840]
When a client replies to us by mail, our email forwards this to repairdesk. 

With a certain client this does not work. I suppose this is because the title of the message is changed to include their reference number (also a ticketing system).

They reply with this title "Informatie nodig ticket 8696 (message id:22832172552) com346.765.087" 

The "com346.765.087" is added, all other customers this is not a problem. 

This is a B2B client for us that makes a lot of communication. Since the original message id is not removed, it should be possible to correctly filter the message.

**Comment by Repairdesk-QA** [comment]
Hello @tomdamman,
Hope you are doing well.

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Your patience means a lot.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @tomdamman,

I have checked your concern and would like to add that **_Message-Id_** in the subject line should remain at the end.
If it remains so, you would be able to receive the email with an edited subject line.

**_For better understanding, kindly look into the video attached:_**
https://www.screencast.com/t/06bOaZGPmEW

I hope this will solve your issue but if you still have any questions, please do not hesitate to reach out.
Helping you is our priority.

**_Thanks & Regards,_**
Quratul Ain

**Comment by tomdamman** [comment]
Hello,

I understood this already like i said in the report.

The problem is that the other party adds this for their internal systems.
And will not remove this (since they are a stock listed company with > 10
000 employees). Even if i remove it manually (which i for sure won't do),
they will not allow it bc they need it for their communication.

My request is that you fix the bug so it doesn't matter where it is. Not
tell me this is "designed this way".

I don't need a video to make me "understand" i already explained in the bug
report where the problem is. I fully understand, I want it fixed.

I don't think it is an outlandish request. Just parse the subject on
(message: and not just the last x characters?

Kind regards,

Tom Damman




Op ma 28 mrt. 2022 07:43 schreef Repairdesk-QA ***@***.***>:

**Comment by Repairdesk-QA** [comment]
Hello again @tomdamman,
Hope you are doing well.

Your reported improvement has been assigned to the development team and hopefully, it will be fixed early next week.
Will update you shortly with the status.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_** https://repairdesk.atlassian.net/browse/REP-3571

**Comment by tomdamman** [comment]
Hey Quratul!

Thanks for the update!

Kind regards

Op di 29 mrt. 2022 13:30 schreef Repairdesk-QA ***@***.***>:

**Comment by Repairdesk-QA** [comment]
Hello @tomdamman,
Hope you are doing well.
 
It's great to assist you and I hope you will be happy with the fix.
Closing this issue for now, but you can always open this whenever you want to.

 And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.
 
**_Thanks & Regards,_**
 Quratul Ain

**Comment by tomdamman** [comment]
Dear Sir/madam,

The ticket comes into the system (inbox) and recognized the ticket. But
doesn't show up in the ticket itself?

Kind regards

Op wo 30 mrt. 2022 06:43 schreef Repairdesk-QA ***@***.***>:

**Comment by Repairdesk-QA** [comment]
Hello @tomdamman,
Hope you are doing well.

I have checked your concern and is working fine on my end.
![image](https://user-images.githubusercontent.com/39614480/161498870-931f8e32-fbe1-4a27-9deb-9cf1cd95669f.png)
 Would be great if you can share your business name and the ticket number with us so we can check from the backend and would be able to track the issue.
 If you are not comfortable here, you can contact our support agents via live chat and can share the required information over there.
 We will update you shortly after checking at our end.
 Waiting for your kind response.
 
 **_Regards,_**
 Quratul Ain

**Comment by tomdamman** [comment]
works

**Comment by Repairdesk-QA** [comment]
> works

Good to know.
If there is anything else with which I may assist, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain
