### ISSUE TITLE
Transaction receipt not being sent by email after payment (PayFacto)

### ISSUE THREAD

**Issue by techm89** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1841]
A while back we asked for the card payment transaction receipt to be sent to customer directly via email instead of having to print the receipt each time since invoice is already sent by email anyway. 

Someone got back to me saying this had been done. I just tested today and the receipt is not included with the invoice by email. Could someone look into this?

**Comment by Repairdesk-QA** [comment]
Hello @techm89,
Hope you are doing well.

Let me check at my end and will surely update you in a while.
Your patience means a lot to RepairDesk.

**_Regards,_**
Quratul Ain

**Comment by techm89** [comment]
Has this been resolved?

**Comment by Repairdesk-QA** [comment]
Hello @techm89,
Hope you are doing well.

We have checked your concern and would like to inform you that this is under development.
Also, I would like to mention that if we sent an email from the Manage Invoice section,  the email contains PayFacto and Invoice Receipt both. 
https://watch.screencastify.com/v/pLT4APCkE6ayi1FwwwuP
But we are working on automatic email too and also from POS. Hopefully, it would be live in our next release.

Your patience means a lot to RepairDesk.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_** https://repairdesk.atlassian.net/browse/RB-4830

**Comment by Repairdesk-QA** [comment]
Hello @techm89,
Hope you are doing well.

Your reported issue has been fixed and is live. Kindly check at your end and do let us know with your valuable feedback.
Waiting for your response.

**_Regards,_**
Quratul Ain
