### ISSUE TITLE
Bug in invoice numbering

### ISSUE THREAD

**Issue by tomdamman** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1843]
Hello,

When creating a standalone invoice, and you don't save it, the numbering goes up anyway. And you can't use the invoice number anymore afterwards. (new invoice skips a number and you can't change the new invoice number).

I guess somehow the invoice number is assigned as "being used" in the database but not in reality?

This should be an urgent fix since the numbering should be correct for taxes...

**Comment by Repairdesk-QA** [comment]
Hello @tomdamman,
Hope you are doing well.

This is our current flow of the system.
We have criteria in the search to see unsaved invoices and you can edit those from there.
_Kindly find the following attachment:_
![image](https://user-images.githubusercontent.com/39614480/161260382-f715c5b4-887a-4fa6-84e7-d27b0f7a2343.png)

If there is anything else with which I may assist, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @tomdamman,
Hope you are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
Closing this issue for now, but you can always open this whenever you want to.

**_Regards,_**
Quratul Ain
