### ISSUE TITLE
Sales Tax Not Calculating Correctly on Services

### ISSUE THREAD

**Issue by rabidnerd** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1845]
Services need sales tax in PA when the service is on a taxable item.

However, when I add a taxable service to a ticket, it may show it on the line when added, but not in the total, it may or may not show it in the invoice, and it virtually never applies it when cashing out the invoice using the POS.

![63ticket34](https://user-images.githubusercontent.com/5092412/161896887-2909d395-334f-4c51-941a-21c8e87b70e4.PNG)
![63](https://user-images.githubusercontent.com/5092412/161896654-c4ad7451-3e92-4565-b5c3-00864a32c74e.PNG)
![63pos](https://user-images.githubusercontent.com/5092412/161896656-0680407d-6331-4d10-a008-a77a41afa7d4.PNG)

It's not a calculation error, it's a complete inconsistent on-and-off application of taxes to services.

**Comment by Repairdesk-QA** [comment]
Hello @rabidnerd,
Hope you are doing well.

I believe you are using one of these triggers (mentioned below)
![image](https://user-images.githubusercontent.com/39614480/161916858-010c90fb-b139-439b-a64d-b582c1997955.png)

When we use these triggers, the tax will be calculated on the parts attached to the ticket, not on the service.
If there is no part in the ticket, the tax would be 0.

I hope this is the scenario but you can correct me if you are not using these triggers.
Would be happy to assist you.

If there is anything else, with which I may assist, please do not hesitate to reach out.

**_Thanks & Regards,_**
Quratul Ain

**Comment by rabidnerd** [comment]
Yes, that was precisely it.

Although, I had done it when going through and saw "Florida, Michigan, OTHER US STATES...", I just chose tax on full retail price and moved on.

Both are unselected now, and it appears to calculate right now.

**Comment by Repairdesk-QA** [comment]
Hello @rabidnerd,
Hope you are doing well.
It's great to know that you have found the solution.
If there is anything else with which I may assist, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain
