### ISSUE TITLE
Invoice Summary - Negative items

### ISSUE THREAD

**Issue by AbbyCSC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1849]
When you print the report excluding items with 0 on hand it should still print those with a negative qty on hand.  The logic should be to exclude qty = 0 and it appears to be =< 0.
Also the dollar amount of items with negative on hand should be displayed as a negative amount and currently it shows it at 0.

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Thank you for bringing this to our attention!
Your reported issue has been assigned to the development team and hopefully, it will be fixed in the next release.
Thanks for your patience and time. We will update you shortly with the status of the issue.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For Internal Use Only:_** https://repairdesk.atlassian.net/browse/RB-4877

**Comment by Repairdesk-QA** [comment]
Hello @AbbyCSC,
Hope you are doing well.

Your reported issue has been fixed. Now you are able to see the negative items in Inventory Summary Report.
But I would like to add here that showing cost for a negative On Hand is not possible as it will disturb the stats.
I hope you can understand. Kindly let us know with your valuable feedback.
Waiting for your response.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @AbbyCSC,
Hope you are doing well.

I have discussed your concern with our Development Lead and would like to add here that in RepairDesk, the negative cost has never been saved in the database and it has impacts on a large number of areas.
If we change this, for now, it will take a lot of time and the whole system needs this change wherever we have costs.
With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work during the 3rd Quarter. 
With that said you can use this workaround for now.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

**_Regards,_**
Quratul Ain
