### ISSUE TITLE
"This Week" in reports is not this week, it's the last 7 days. All the other presets dates are correct, why isn't that one?

### ISSUE THREAD

**Issue by CGOwner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1850]
If I click on "REPORTS", then click on TODAY.. I get TODAYS numbers..  If I click on Yesterday, I get YESTERDAYS numbers. LAST MONTH, would be MAR 1st thru March 31st. Not the last 31 days...  if I click on LAST YEAR, guess what I get? Not the last 365 days, but Jan 1st thru Dec 31st.   Someone PLEASE FIX "This Week" to be Sunday thru what ever day you select the report on...   Yes I know I can work around this incorrect working button by selecting the dates that I want to report on, but that's not a FIX, that's a work around.   Changing it to "The Last 7 Days" as they did in the drop down date menu was not a fix either, I'm not a coder, but I've been asking for this verbally for OVER A YEAR, and it's gone no where.  I'm starting to wondering if your coders don't know how to fix it?   Time to open a ticket.  

<img width="1879" alt="ThisWeek1" src="https://user-images.githubusercontent.com/103802225/163659688-24c30981-20fc-4174-a819-259a2d151c3f.png">
<img width="554" alt="ThisWeek2" src="https://user-images.githubusercontent.com/103802225/163659692-10a1bddf-cf7d-444b-a860-3f3320deb83c.png">

**Comment by Repairdesk-QA** [comment]
Hello @CGOwner,
Hope you are doing well,

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
Your reported issue has been assigned to the development team and hopefully, it will be fixed in the next release.
We will update you shortly with the status.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_** https://repairdesk.atlassian.net/browse/RB-4882

**Comment by Repairdesk-QA** [comment]
Hello **@CGOwner**,
Hope you are doing well,

I believe that your reported issue has been fixed. Please verify at your end and do let us know if you have question regarding this.

**_Regards,_**
  Nida Khalid

**Comment by Repairdesk-QA** [comment]
Hi **@CGOwner,**
Hope you are doing well,

Thanks for sharing your concern in detail. I'm going to reach out to our BA Team to get this taken care of, I'll get back to you as soon as I got some feedback regarding your concern!

_Regards,_
Nida Khalid

**Comment by ProductTeam-RepairDesk** [comment]
Hey @CGOwner, I hope you're doing well.
I really appreciate that you took the time to share your ideas.

I can certainly see how suggested improvements would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work during 2nd Quarter. 
With that said you can use this work around for now.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards
Haider shah
