### ISSUE TITLE
tax deducted twice

### ISSUE THREAD

**Issue by tomdamman** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1851]
Dear Sir/Madam,

When I edit a ticket, and adjust the service problem, the price changes but the tax is deducted twice.

For example. 121€ in total with 21% included will put a 100€ total and a 82.64€ without tax. This problem started 1 or 2 weeks ago.

When i just add a completely new service line it does it correctly.

kind regards.

**Comment by Repairdesk-QA** [comment]
Hello @tomdamman,
Hope you are doing well.

I would like to inform you that this issue has been reported by another customer and it has been fixed.
The fix is live now. Kindly check again and let us know if you still have this issue.
Waiting for your feedback.

**_Regards,_**
Quratul Ain

**Comment by tomdamman** [comment]
Great to hear!



Op vr 22 apr. 2022 08:45 schreef Repairdesk-QA ***@***.***>:

**Comment by Repairdesk-QA** [comment]
Hello @tomdamman,
Hope you are doing well.

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
If there is anything else with which I may assist, please do not hesitate to reach out.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello again @tomdamman,
I have checked at my end and is working fine. Can you please share your business name and ticket id so we can check from the backend?
Waiting for your response.

**_Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only: https://repairdesk.atlassian.net/browse/RB-4978_**

**Comment by Repairdesk-QA** [comment]
Hello @tomdamman,
Hope you are doing well.

Your reported issue has been fixed and is live.
Kindly verify at your end and do let us know with your valuable feedback.

If you have any questions, please do not hesitate to reach out.

**_Thanks & Regards,_**
Quuratul Ain
