### ISSUE TITLE
Trade-in Item missing from report if it was added to an invoice via a Ticket

### ISSUE THREAD

**Issue by onebitetechnology** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1852]
Situation: Customer bought a device (sitting in the Trade-in module). They wanted the hard drive upgraded, so I created a ticket, added the service/part, and added the device as an inventory item to the ticket. Once the upgrade was done, I invoiced it and billed the customer. 

This particular trade-in device is missing from the trade-in report for the day.

**Comment by Repairdesk-QA** [comment]
Hello @onebitetechnology,
Hope you are doing well.

Thank you so much for reporting this issue. It looks like there is a bug that popped up.
We have checked your concern and it has been assigned to the developer.
Hopefully, it will be fixed and live in next week.
We will update you shortly with the status.

If there is anything else with which I may assist, please do not hesitate to reach out.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_** https://repairdesk.atlassian.net/browse/RB-4905

**Comment by Repairdesk-QA** [comment]
Hello @onebitetechnology,
Hope you are doing well.

Your reported issue has been fixed. Kindly check at your end and do let us know with the feedback.
Waiting for your feedback.

**_Regards,_**
Quratul Ain
