### ISSUE TITLE
Total Employee Hours

### ISSUE THREAD

**Issue by conlan0** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1862]
It would be nice if when you chose a time period for an employees hours that it would just give you a total.

**Comment by ProductTeam-RepairDesk** [comment]
Hi @conlan0 

Can you please elaborate on your request? Do you want to update the logs of hours for an employee? What exactly you are referring to as "Chose a time period"?

Looking forward to hearing from you

**Comment by conlan0** [comment]
Yeah I'm sorry if I wasn't detailed but what I mean is when you are looking at the "Employee TimeSheet - Clock In / Clock Out Time" and select the dates you want, for it to show a total amount of hours worked between those dates.
