### ISSUE TITLE
appointment time slot problem

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1863]
Hello,
Our customers are no longer able to select an appointment time slot via our website. The appointments plugin mentions that there are no appointments available. Still, there is no date restriction in plugin settings. As of June 12, the problem seems to be fixed. What's the problem ? Here is a video that demonstrates the problem: https://www.awesomescreenshot.com/video/9091576

-- French:
Bonjour,
Nos clients ne sont plus en mesure de sélcetionner de plage horaire de rendez-vous via notre site internet. Le plugin des rendez-vous mentionne qu'il n'y a aucun rendez-vous de disponible. Pourtant, il n'y a aucune restriction de date dans les paramètres du plugin. À partir du 12 juin, le problème semble être corrigé. Quel est le problème ? Voici une vidéo qui démontre le problème: https://www.awesomescreenshot.com/video/9091576

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
Hope you are doing well.

Sure thing. Let me take a look to see if I am getting the same issue.
Will update you shortly with the status.

**_Thanks & Regards,_**
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Hello @JessicaSOS,
I hope you are doing well.

Your reported issue has been fixed, kindly check at your end and let us know if you have any questions.
If there is anything else I may assist with, please do not hesitate to reach out.

**_Thanks & Regards,_**
Quratul Ain

**Comment by JessicaSOS** [comment]
It's fixed, thank you very much for your speed

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579
 ***@***.***> ***@***.***
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
2750, 1re Avenue, Limoilou, G1L 3N8

5375, boul. Guillaume Couture, Lévis, G6V 4Z3

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Repairdesk-QA ***@***.***> 
Envoyé : 27 mai 2022 02:16
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS ***@***.***>
Cc : JessicaSOS ***@***.***>; Mention ***@***.***>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] appointment time slot problem (Issue #1863)

 

Hello @JessicaSOS <https://github.com/JessicaSOS> ,
I hope you are doing well.

Your reported issue has been fixed, kindly check at your end and let us know if you have any questions.
If there is anything else I may assist with, please do not hesitate to reach out.

Thanks & Regards,
Quratul Ain

**Comment by Repairdesk-QA** [comment]
Glad you like it.
Closing this issue as it has been fixed
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks for your time. Enjoy your day!

**_Regards,_**
Quratul Ain
