### ISSUE TITLE
Customer export incomplete

### ISSUE THREAD

**Issue by RDimprovement** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#1869]
Hi, 

The customer phone field in RepairDesk is not exporting to the Phone column in excel (the phone column is empty). The mobile field is exported to excel ONLY if there is one number in the mobile field in RepairDesk. If there are two numbers in the mobile field in RepairDesk only the first one exports. Could the phone fields and all numbers in the mobile fields export correctly to excel?

**Comment by Repairdesk-QA** [comment]
**_For internal use only:_** https://repairdesk.atlassian.net/browse/RB-5293
