### ISSUE TITLE
Log for system

### ISSUE THREAD

**Issue by luisvae** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#189]
It would be great to have a log of all actions of every user in the system. Including:

- Invoice creation
- Invoice update
- Invoice delete
- Product creation
- Stock update
- Product delete
- Ticket created
- Ticket updated
- Payment modification

This way admins can check if something goes wrong, what has happened and which user has done it.

**Comment by Uzair-RepairDesk** [comment]
You can track all of the above from our "Employee Activity Log" report by applying the relevant criteria filter. Hope it helps.
