### ISSUE TITLE
Commission behaviours

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#196]
How the commission will be if the sales are refund? Will the commission will be deducted or not?

Also how we know which commissions have been paid or not paid? Since it has status as Paid, Not Paid.

Thanks.

**Comment by Uzair-RepairDesk** [comment]
Hi @quangc 

I hope you are doing good. There is no possibility to deduct commission if invoice is refund right now. In a logical point of view, once sales commission is calculated, specific employee owns it. There could also be a scenario when you already pay commission to the employee and customer comes for refund after that so there should not be a negative value of commission for employee. 

Regarding status of commission, Thank you for your suggestion. I think that’s an awesome idea! Having it would definitely provide the ease to track paid and unpaid commission of employees.

We’re not working on that at the moment but I’ll pitch it to the team and see what they think.

If you have any other questions, just let me know and I’ll be happy to help.

Best Regards,
Uzair

**Comment by Uzair-RepairDesk** [comment]
Hey @quangc 
We are working on employee commission functionality improvements and I am pleased to inform you that I have added your above feedback under the improvements.

**Comment by Uzair-RepairDesk** [comment]
Hey @quangc 
I am pleased to inform you that we’ve gone live with following improvements in employee commission module: 
1: Employee commission can be set in amount or percentage
2: Commission value can be set globally, with respect to inventory item categories e.g. cases, chargers or individual items too.
3: Setup to split commission between a sales-person and technician
4: Configuration to set commission based on total sales or profit earned (Trigger based)
5: Added an option to void commission in case of a refund (Trigger based)
6: Option to pay commission via payroll module.
7: Improved Commission report

For more info on how to setup and use the updated module is available here:
https://repairdesk.uservoice.com/knowledgebase/articles/895878-how-can-i-setup-employee-commission
