### ISSUE TITLE
Report on email sent 

### ISSUE THREAD

**Issue by wirelessrepairzone** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#201]
Would like to see a report or any reporting options on Automated Followup Email Campaign 

i have tested so i know emails are being sent but it would be nice to have a report or the option to create a campaign based on type of device or other condition to send out emails to past customers

**Comment by Uzair-RepairDesk** [comment]
Hey @wirelessrepairzone 
You can try our updated Campaigner module that allows you to create a campaign with different criteria's of repairs or products. You can also view insights of the campaigns. 
https://repairdesk.uservoice.com/knowledgebase/articles/1126435-how-can-i-send-follow-up-emails-to-customers
