### ISSUE TITLE
Edit ticket option on POS

### ISSUE THREAD

**Issue by RepairDeskPOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#202]
Just like we can re-open ticket to create invoice we should be able to just edit ticket only and make changes on it i.e. Lets you book a repair for Diagnostic and now want to Update problem or add an accessory item or you can add part so you dont have to switch b/w different screens

**Comment by Uzair-RepairDesk** [comment]
Listed new request:-
https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/602
Closing it from here
