### ISSUE TITLE
Refund showing $0.00

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#206]
For some reasons, refund invoice is now always showing as $0.00, instead of the original amount and this has create big issues for us.

Please look into this one ASAP.

![screen shot 2017-01-31 at 5 37 51 pm](https://cloud.githubusercontent.com/assets/22993605/22454775/7fcffffe-e7dc-11e6-96a7-c7c65446909b.png)

**Comment by HafizAnas** [comment]
Hi @quangc 

We have tried many times at our end, even from your account but we are not able to reproduce this issue It would be appreciated if you share steps or more screenshots with us.

Thanks!
