### ISSUE TITLE
Register Sales Report Error

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#212]
The total for the Paid column does not add properly.

**Comment by HafizAnas** [comment]
Hi @smarttechrepair 

we have tried at our end and we are not able to reproduce this issue. Kindly check at your end again if problem still exist then It would be really appreciated to share screenshots with us.

**Comment by Uzair-RepairDesk** [comment]
This issue already fixed and we have also updated the "Register Sales Report".
You can check the updated report from the following URL:-
https://app.repairdesk.co/index.php?r=stats/registersales
