### ISSUE TITLE
Multi Store Reports Date Ranges

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#215]
When pulling store reports, there must be a way for pulling report dates by calendar months and weeks.  A calendar week starts on Monday and ends on Sunday.  A calendar month starts on the 1st.    Currently reports can only be pulled based on months based on numerical 30 days or weeks based on 7 days.  No business in the real world runs this way thus reports are worthless.  Please make the changes ASAP!!!

**Comment by Fazal-RepairDesk** [comment]
@smarttechrepair Thanks for your feedback. It sounds like a great idea and we will definitely include it along with other improvements.

**Comment by Uzair-RepairDesk** [comment]
We have already updated the multi-store sales report that allows you to apply custom date filter. 
You can check the updated report from the following URL:-
https://app.repairdesk.co/index.php?r=stats/multiStoreSales
