### ISSUE TITLE
Sales by Item Report Does not Work PropErly.

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#216]
When pulling a sales by item report, the totals are not shown correctly for that day.  The only way to pull the correct report is by using search filter and selecting the dates manually.  By default the sales by repairs pulls reports correctly for the current day.  Sales by item should also by default report current day sales.

**Comment by Uzair-RepairDesk** [comment]
We have updated the "Sales by Item Type" report. 
You can check the updated report from the following URL:-
https://app.repairdesk.co/index.php?r=stats/salesbyitem
