### ISSUE TITLE
Sales by Repairs & Sales by Items Reports

### ISSUE THREAD

**Issue by smarttechrepair** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#218]
Must be able to track invoice and ticket numbers on both of these reports.  It is useless having a report that we cannot audit and trace back to original tickets and original dates of transactions.

**Comment by Fazal-RepairDesk** [comment]
@smarttechrepair Thanks for your feedback. It sounds like a great idea and we will definitely include it along with other improvements once we improve our reports section.

**Comment by Uzair-RepairDesk** [comment]
We have updated "Sales by Item type" report that has both "Repairs" and "Products" criteria to see the insights. 
You can check the report from the following URL:-
https://app.repairdesk.co/index.php?r=stats/salesbyitem
