### ISSUE TITLE
Set access permissions for employee role per report

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#228]
Be able to set which reports an employee role can access. Rather than them having full access or no access. In particular the employee productivity report. Also being able to restrict to only viewing their own data within the report.

**Comment by Repair-Desk** [comment]
@afrahm 

Thanks for your feedback. It sounds like a great idea and we will definitely include it along with other improvements once we re-write employee permission module

**Comment by Uzair-RepairDesk** [comment]
Hi Andrew @afrahm,
We have already added separate permissions for each report under employee roles permissions module. 
Please check screenshot attached. 

![AwesomeScreenshot-uzairshah-Roles-Permission-2019-07-30-15-07-94](https://user-images.githubusercontent.com/22955861/62122044-487ac500-b2de-11e9-8f2b-6e59c9e0a22d.png)
