### ISSUE TITLE
Have button on the manual in/out page that opens cash drawer

### ISSUE THREAD

**Issue by Celeste110** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#230]
I was looking for a button on repair-desk that would allow us to open the cash drawer but couldn't find it.

It would be great if a button could be added to the manual in/out page that would open the cash drawer.

**Comment by Repair-Desk** [comment]
@Celeste110 

Thanks a lot for your feedback. It sounds like a great idea and having it would really improve your workflow. However since RepairDesk is a cloud based point of sale solution you cannot open a cash drawer until we send a print command to your receipt printer.
