### ISSUE TITLE
Detailed info in Exported CSV files

### ISSUE THREAD

**Issue by josephifixhq** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#238]
nclude more detailed information in the exported CSV files especially the invoices file. Currently the file doesn't include the device colour, or the ticket items/parts used on the repair.
theses details would have to be in seperate columns for it to be functional though. I.E the current *description* field contains the due date of the repair and in 99% of cases i have to delete the due date before being able to use the data in another program, due to the format not being recognised.

**Comment by Fazal-RepairDesk** [comment]
Hi @josephifixhq 
Thanks for sharing. I've forwarded this feature request to my team and I'll keep you posted here about the latest developments.

Best,
Fazal
RepairDesk

**Comment by Uzair-RepairDesk** [comment]
We have added details CSV file for invoice and ticket.

Hope this helps.
Regards,
