### ISSUE TITLE
Feature Suggestion - Special Part Order

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#240]
One of the things we do on a daily basis is monitor Special Order parts.  We have direct accounts with FedEx, UPS, DHL, and USPS and we monitor all incoming special orders.  Almost everything we order has a tracking #.

What would be great is to have optional fields for "special order parts" where you can fill in a short description, carrier, and tracking #.  The carrier will be from a pre-defined list of major carriers and custom carriers we can add. Then be able to ADD a new line and repeat.  Then when you pull up the ticket you can OPEN the special order section and see that information.  The tracking number will become a link that when clicked will open a pop up window with the tracking details similar to eBay.  While it prob wont be practical to automatically parse and provide details for any "custom" added carrier it would allow the user to denote things like "John Doe parts" if that guy delivers like some of our suppliers do.

Then you would have a special section for "Special Order" sort of like a report where you can see all the outstanding special orders, tickets their associated with, status (pending, ordered, received).  A user would be able to run this report, sort by status and literally be able to use it as a list to order all parts in one shot or update those statuses as parts are actually ordered or delivered.  It would give you a nice global view of what's outstanding.

To take it one step further it could also have an extra field on expected delivery date and those dates can be displayed (for example) in green if today is before that date and in red if today is after that date.

That would be an amazing feature for any busy shop like ours since we place anywhere from 5-10 "special order" parts order daily.  It's a lot to track.  Also we get at least 10 calls a day from impatient customers asking "is my part in yet ?".  While we know that the part hasn't already arrived we still take the time for customer satisfaction reasons to look it up and give them an update.  It's just a part of doing business but something like suggested above would make it much easier for any tech to have the information they need in the primary system.

**Comment by Fazal-RepairDesk** [comment]
Feature request forwarded to planning team

**Comment by Uzair-RepairDesk** [comment]
It's available now
https://help.repairdesk.co/knowledgebase/articles/1949434-how-to-use-special-order-for-non-catalogue-items
