### ISSUE TITLE
Add the option to automatically assign a due date

### ISSUE THREAD

**Issue by josephifixhq** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#241]
We have some issues where employees are not following up with customers when their device is kept on site for a period of time due to a more involved repair being required. It would be advantageous for us to automatically set due dates to a date 24/48/72 hours in the future, this way we are notified as admin when the job has not been completed by the due date and can take action to ensure the customer experience is not adversely affected.

**Comment by Fazal-RepairDesk** [comment]
Hi @josephifixhq 
Thanks for sharing. I've noted down and forwarded your feature request to our development team. I'll keep you posted here about it's progress.

Thanks,
Fazal
RepairDesk.

**Comment by Uzair-RepairDesk** [comment]
Hi @josephifixhq 
We have already given an option to set a default due date & time for repair jobs. You can go to Store Setting > Module Configurations > Repairs > Default due date & time for repairs

Hope it helps
