### ISSUE TITLE
ios App Enhancement

### ISSUE THREAD

**Issue by RedgumPC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#242]
Have the ability to print an invoice from an iPad.

**Comment by Fazal-RepairDesk** [comment]
Hi @RedgumPC 
We're currently working on our iPAD app and this feature is included. I'll keep you posted here.

Regards,
Fazal
RepairDesk

**Comment by Uzair-RepairDesk** [comment]
The feature is available to print an invoice from iPad
