### ISSUE TITLE
Cayan Integration - Invoice number

### ISSUE THREAD

**Issue by wirelessrepairzone** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#243]
The invoice number displayed or passed to Cayan is the record ID, can this be changed to the actual invoice number for example

Invoice Number  433526 as reported on Cayan links back to https://app.repairdesk.co/index.php?r=invoice/view&id=433526   its using the ID number not the system invoice number, is this something that can be modified? If so it would make things a lot easier to match

**Comment by Fazal-RepairDesk** [comment]
Hi @wirelessrepairzone 
Thanks for sharing. I've noted down your request and will discuss it with our team.  I'll keep you posted here about it's progress.

Thanks,
Fazal
RepairDesk.
