### ISSUE TITLE
Ticket statuses not translating to Portuguese

### ISSUE THREAD

**Issue by mlisb0n** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#244]
The tickets statuses are not translatable or not showing the translation.

<img width="1032" alt="2017-05-26 15 17 22" src="https://cloud.githubusercontent.com/assets/6557013/26498359/b7469660-4226-11e7-8ceb-6ce4976c42fa.png">

**Comment by Fazal-RepairDesk** [comment]
Hi @mlisb0n 
Thanks for sharing. I've noted down and forwarded your feature request to our development team. I'll keep you posted here about it's progress.

Thanks,
Fazal
RepairDesk.

**Comment by Uzair-RepairDesk** [comment]
RepairDesk allows adding "Custom Ticket Status" option with a specific type. 
You can check more information from the following link:-
https://repairdesk.uservoice.com/knowledgebase/articles/1121176-how-to-manage-ticket-status
