### ISSUE TITLE
Add Google Analytics function to Website widgets. 

### ISSUE THREAD

**Issue by josephifixhq** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#245]
Adding the ability to easily track events with Google Analytics  inside the book-in and sell device widgets. We would love to know where exactly our customers are closing the widgets. We could achieve this by adding Google Analytics events to individual CSS classes. The ability to target particular CSS classes would possibly help with this, in addition to google analytics targeting particular CSS classes would be helpful to make the widgets more personalised to our website

**Comment by Fazal-RepairDesk** [comment]
Hi @josephifixhq 
Thanks for sharing. I've noted down and forwarded your feature request to our development team. I'll keep you posted here about it's progress. 

Thanks,
Fazal
RepairDesk.

**Comment by Uzair-RepairDesk** [comment]
Hi @josephifixhq 
There is an option to add a tracking code as explained here:
https://help.repairdesk.co/knowledgebase/articles/791394-repairdesk-appointments-booking-widget

![tracking code](https://user-images.githubusercontent.com/22955861/100840636-00eae700-3498-11eb-8764-9dedab75d59e.jpg)
