### ISSUE TITLE
Spelling errors

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#248]
Just checking the JSON for the customers and wanted to submit a few spelling corrections. Here's the sample. Corrections are in bold:
{
            "driving_licence": "",  "**driving_license**": "", 
            "city": "", 
            "refered_by": "", "**referred_by**": "", 
            "contact_person": "", 
            "cid": "579992", 
            "mobile": "+1 555-555-5555", 
            "address1": "", 
            "address2": "", 
            "phone": "", 
            "state": "", 
            "orgonization": "",  "**organization**": "",
            "postcode": "", **postal code** is the correct english term
            "country": "", 
            "fullName": "John Doe", 
            "tax_number": "", 
            "email": "", 
            "network": ""
        },

**Comment by Fazal-RepairDesk** [comment]
Hi @ThinkDigitalRepair 

Thank you for your valuable feedback. I've forwarded this to my team.

Have a great day!

Regards,
Fazal

**Comment by ThinkDigitalSoftware** [comment]
{
            "id": "892344",
            "item_no": "0003",
            "name": "Screen (Digitizer+LCD) Replacement",
            "~manufaturer_name~": "LG", <--- manufacturer_name
            "device_name": "Nexus 5 D821",
            "original_price": "99.00",
            "tax_class": {
                "tax_class": "Indio Tax",
                "id": "7495",
                "tax_percent": "8.750"
            },
            "tax_inclusive": "0",
            "device": "137442",
            "associate_parts": "",
            "price": "99.00",
            "gst": "8.66",
            "warranty_timeframe": "",
            "warranty": "",
            "sort": "0"
        },
