### ISSUE TITLE
Cash drawer 

### ISSUE THREAD

**Issue by wirelessrepairzone** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#249]
Currently there is no way to see who has a drawer open or for a manager to override and close it. At times employees forget to close the drawer at the end of the shift, The next morning someone else comes in and cant use the register, they call me and there is nothing I can do but to lookup the employees access pin, login as them and check to see if the register is open.   I can sort of tell from the Reconciliation Summary Report but there should be a way for the manager to look at the status of each register, see who is logged in and force a close.

**Comment by Fazal-RepairDesk** [comment]
Hi @wirelessrepairzone ,
Thanks for your feedback. I'm forwarding this suggestion to our Project Manager. 
I'll keep you posted here. 

Regards,
Fazal

**Comment by Uzair-RepairDesk** [comment]
We already have a "Transaction Log Report" that allows you to view "Open Cash Registers" and transactions. 
You can check transaction log report from the following link:-
https://app.repairdesk.co/index.php?r=cashDrawer/transactionLog&shift_id=
