### ISSUE TITLE
Tax issue

### ISSUE THREAD

**Issue by wirelessrepairzone** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#250]
When we change the tax code to out of state or another code set to 0 its still charging the tax from the parts to the customer.

**Comment by Fazal-RepairDesk** [comment]
Hi @wirelessrepairzone 

Can you please elaborate a bit more so that I can guide you accordingly?
It would be great if you could share a screenshot as well.
I think perhaps you've activated the trigger which causes tax to be charged on parts as well.

Regards,
Fazal

**Comment by wirelessrepairzone** [comment]
We do have the system configured to charge tax on parts, we are based in
michigan and this is the way we have to calculate tax. As a matter of fact
the tax on on part module was built based on our case.

If I change the tax rate to Out of State, this is a code we created with a
tax rate of 0  then it removed all other tax from the sale (for example
accessories) but not the tax for parts associated with any repairs on the
order.

for example

Image  "normal sale"   - this is a normal sale, as you can see the total
cost is 71.70 thats correct, The repair price is configured at $69 and the
part cost is $45 so at 6% tax the tax is correct at $2.70

Image "tax rate 0" - in this image you can see i changed the tax rate to 0
 but it did not remove the $2.70 tax from the part  (i did not show but it
would have removed tax for normal items like accessories"

image "warranty" - In this example i changed the price of the repair to 0
and the tax rate to 0 you can see its still changing tax, i know this is
the same thing as the tax is calculated from the part price not the repair
price but its an easy way to show what the system is doing


This is causing two issues, first with out of state mail in customers we
cant turn off tax and still record the parts used with the repair. We also
have the same issue with non-taxable customers like schools and
non-profits.

The other issue is with warranty, we are writing up a new ticket for
warranty and changing the price to 0, i know you have a different way to
record warranties but it does not work well for us because it does not show
as an open ticket or show up on the invoces/reports that we use to record
sales in our accounting system.



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by wirelessrepairzone** [comment]
Any update on this? Do you have the information needed to review?
