### ISSUE TITLE
Filtering purchase order by due date

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#251]
We should have a filter to sort all unpaid purchase orders by its due date. Since we always have credit account and for us to make payment for due invoices will become much easier if we know which purchase order is due for payment.
In the purchase order it has the due date for delivery which can be used as due date, simply allow us to filter that field will resolve this query.

Many thanks.

**Comment by Fazal-RepairDesk** [comment]
Hi @quangc 

Thanks for sharing your feedback! I'm forwarding this request to my team. Once I get a feedback, I'll update you accordingly. 

Best,
Fazal

**Comment by Fazal-RepairDesk** [comment]
Hi @quangc 
Following your suggestion, we have added a filter to sort all paid/ unpaid purchase orders called **Payment Status**. 
![filter_1](https://user-images.githubusercontent.com/22954033/29664250-48fb363a-88e8-11e7-8caa-b6c0b93e611b.png)
