### ISSUE TITLE
Trade in API 

### ISSUE THREAD

**Issue by wirelessrepairzone** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#252]
Looking for a way to list the equipment we have for sale on our website, is there any way to link this to the Tradein on the POS system

**Comment by ThinkDigitalRepair** [comment]
According to RepairDesk, this is all the endpoints they support. The closest one is inventory, but that doesn't seem to include trade-in inventory
[https://repairdesk.uservoice.com/knowledgebase/articles/1189105-public-api](url)

**Comment by Repair-Desk** [comment]
@wirelessrepairzone @ThinkDigitalRepair You can use our WooCommerce integration to list trade-in items. More information is available here: https://repairdesk.uservoice.com/knowledgebase/articles/1201576-how-to-set-up-woocommerce-integration-in-repairdes
