### ISSUE TITLE
Recipt and ticket label

### ISSUE THREAD

**Issue by ireparo** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#254]
it will be very helpfull if we can add on the recipt or ticket the physical location of the repair job because the technicians have to entrer to the program to see where is the mobile phone.

**Comment by Fazal-RepairDesk** [comment]
Hi @ireparo Thanks for the suggestion! I'm forwarding it to our team.

**Comment by Uzair-RepairDesk** [comment]
We already added {{device_location}} macro in ticket label under Template Editor. 
Please check screenshot attached
![uzairshah update template](https://user-images.githubusercontent.com/22955861/53226530-1c0ead00-369d-11e9-8376-be4f42d60b45.png)
