### ISSUE TITLE
Serialized Items in RMA

### ISSUE THREAD

**Issue by Fazal-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#255]
Suggestion by Quang:

In the RMA, system does not allow to select serials, so we have to manually delete them from our system. Is this the way at the moment?

The steps are you will create RMA to return some serialized stock and they system did not ask for serials. So the system will not know which item to be returned.

**Comment by Uzair-RepairDesk** [comment]
We have added an option to select serials while creating an RMA
