### ISSUE TITLE
Point of Sale Barcodes

### ISSUE THREAD

**Issue by ChrisDRT** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#257]
Whenever scanning a product bar-code, I always reciev an error saying 'product not available on Point of Sale'

**Comment by Uzair-RepairDesk** [comment]
Hey Chris,
Can you answers the following question so I can assist you:-

1: Did you generate product barcodes from RepairDesk?
2: Can you specify where you exactly scan the barcode from POS screen? 
3: Can you please share a screenshot or a video?

Looking forward to hearing from you

Regards,
Uzair from RepairDesk
