### ISSUE TITLE
Missing resource in widget

### ISSUE THREAD

**Issue by elbakh** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#260]
Using the repair widget/add in on my website and I'm getting a 404 for the following resource:
https://app.repairdesk.co/themes/repairdesk/fonts/AvenirNextLTPro-Regular.otf

**Comment by Repair-Desk** [comment]
@elbakh Can you share link to your repair widget so we can check this for you?

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
