### ISSUE TITLE
Google print

### ISSUE THREAD

**Issue by ireparo** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#261]
There is a problem printing from google print with the recipt because don't print the correct size but if i print directly it prints correct. is any way to change the parameters form printer? Thamns

**Comment by kristan79** [comment]
I have change all parameters on my end.  It has something to do on the back end.  It does it with Print Node also

**Comment by Repair-Desk** [comment]
@kristan79 @ireparo Are you guys still facing issue with printing?
