### ISSUE TITLE
Customer Info Required

### ISSUE THREAD

**Issue by kristan79** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#263]
The  new trade in module  is awesome.  The only issue is when you create ticket,it requires you to put in a customer.  I require all tickets to have a customer and do not want to stop that feature.  We need to save the ticket with the trade in info and not a customer.  Thank you in advance for the fix

**Comment by Uzair-RepairDesk** [comment]
Hey @kristan79 
When you create a refurbishment ticket from the trade-in module, there is trade-in info rather than a customer info. 
Please check at your end and confirm. Thanks.
