### ISSUE TITLE
Printing Labels from PO and RMA section

### ISSUE THREAD

**Issue by kristan79** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#264]
We need to be able to print inventory labels in the Purchase order section.  It is a pain to have to go to inventory for every item to print inventory labels.  The same with the RMA Labels.  You are able to print RMA labels through ticket but if you had an item that you do a RMA for prior to the repair you should be able to print a label from the RMA screen

**Comment by Repair-Desk** [comment]
@kristan79 We have already added an option to print inventory label through GRN however I am adding option to print RMA labels to our product roadmap

**Comment by Uzair-RepairDesk** [comment]
We have an option to Print RMA label from "View RMA" screen.
Please check screenshot attached.
![rma label](https://user-images.githubusercontent.com/22955861/52772936-94e98580-305b-11e9-98c4-e9057fc6678f.png)
