### ISSUE TITLE
Commisson including Tax

### ISSUE THREAD

**Issue by kristan79** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#265]
Commission Report includes taxes.  We should not pay commission on tax to our employees. The report total should only include subtotal not total including tax

**Comment by Uzair-RepairDesk** [comment]
@kristan79  We are re-writing our commission's module and we are adding your above feedback in the updated module.

**Comment by Uzair-RepairDesk** [comment]
Hey @kristan79  
I am pleased to inform you that we’ve gone live with following improvements in employee commission module: 
1: Employee commission can be set in amount or percentage
2: Commission value can be set globally, with respect to inventory item categories e.g. cases, chargers or individual items too.
3: Setup to split commission between a sales-person and technician
4: Configuration to set commission based on total sales or profit earned (Trigger based)
5: Added an option to void commission in case of a refund (Trigger based)
6: Option to pay commission via payroll module.
7: Improved Commission report

For more info on how to setup and use the updated module is available here:
https://repairdesk.uservoice.com/knowledgebase/articles/895878-how-can-i-setup-employee-commission
