### ISSUE TITLE
Getting an Error when Posting a Customer with the OpenAPI

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#266]
I'm using the openAPI customers post function to try to upload a customer, but no matter what I try, I keep getting an error. Here's what I'm submitting using [Postman](https://www.getpostman.com/):

URL:
`https://api.repairdesk.co/api/web/v1/customers?api_key=vrvEPmn-11GC-pRlj-8Fze-VmfTrelf8`

Body:
`"first_name": "Test", "last_name": "Customer", "phone": "", "mobile": "+1 555-555-5555", "address1": "", "address2": "", "postcode": "", "city": "", "state": "", "country": "United States", "email": "noone@example.com", "orgonization": "", "refered_by": "", "driving_licence": "", "contact_person": "", "tax_number": "", "network": "Verizon", "customer_group": {"id": "1", "name": "Individual"}
`
Second Attemt:
Body:
`
"fullName": "Test Customer", "phone": "", "mobile": "+1 555-555-5555", "address1": "", "address2": "", "postcode": "", "city": "", "state": "", "country": "United States", "email": "noone@example.com", "orgonization": "", "refered_by": "", "driving_licence": "", "contact_person": "", "tax_number": "", "network": "Verizon", "customer_group": {"id": "1", "name": "Individual"}`

Response Every Time is:
```
{
    "success": false,
    "statusCode": 400,
    "message": "Please enter required input",
    "data": {
        "fullName": [
            "Please Enter first name or last name"
        ]
    }
}
```
I don't understand the error message. Can it respond with an example of a valid submission? What am I doing wrong?

**Comment by ThinkDigitalRepair** [comment]
![screenshot from 2017-10-31 22-45-56](https://user-images.githubusercontent.com/23037821/32261658-50925be6-be8d-11e7-9158-fe8596c38eea.png)
Nothing with Postman either.

**Comment by ThinkDigitalRepair** [comment]
Got it submitted with this information. Is there any way you can change the response to include correct formatting?
![screenshot from 2017-10-31 22-55-00](https://user-images.githubusercontent.com/23037821/32261880-94c2dc40-be8e-11e7-85e1-e8402c547329.png)
