### ISSUE TITLE
IPad app incorrectly marking tickets as paid when opened in the POS 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#267]
I opened up the ticket in the position to see how it looked and then closed it but when I opened it again and tried to take a payment, it said the invoice was already paid although an invoice hasn't even been created yet. 
![975034a4-a7b3-43a1-b56c-9869a4c6f825](https://user-images.githubusercontent.com/23037821/32191721-4396cfa4-bd6f-11e7-8485-08b30e8c1f66.jpeg)
![8e6b98ad-be0f-48e5-860e-33ff26e26439](https://user-images.githubusercontent.com/23037821/32191722-43c75d40-bd6f-11e7-82da-501f8a328742.png)

**Comment by Repair-Desk** [comment]
@ThinkDigitalRepair Are you still getting the same issue :)

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
