### ISSUE TITLE
Multi Store Low Stock Inventory

### ISSUE THREAD

**Issue by kristan79** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#271]
Every time I go to Low Stock inventory there is a amount in PO.  It is combining both stores.  This need to be separate.  Also all of my Purchase orders are closed and there is still an in PO amount.  Please advise

**Comment by Repair-Desk** [comment]
@usmanalikhan93 Can you check this early next week?

**Comment by kristan79** [comment]
I would love to have this fixed also,  I have to delete my purchase orders to temp fix issue

**Comment by usmanalikhan93** [comment]
Hi @kristan79 

I have checked your concern but unable to reproduce the issue. Can you help us to replicate the issue, so we can release a fix ASAP ? 

Thanks!
Usman Ali

**Comment by kristan79** [comment]
It happens daily.  I will have to show you.  let me know when we will get together

**Comment by usmanalikhan93** [comment]
Ok @kristan79 that would be great, you can contact our support team. They will assist you and you can show them the issue :) 

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
@kristan79 

Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Usman Ali
