### ISSUE TITLE
Discount error on ticket lines

### ISSUE THREAD

**Issue by rlltd** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#276]
If discount is added to a ticket line (either in the device details repair items, or inventory items) the total amount due at the bottom of the ticket is incorrect.

If the total discount is added to the bottom area it is calculated correctly.

This needs fixed as commission will be paid on the totals of the individual items without taking into account the discount. It also skews the reports as they show the total value of items sold even though the discounts should have been added to each item.

**Comment by Repair-Desk** [comment]
Let us take a look to see if we are getting the same issue as you and we'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @rlltd,

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
