### ISSUE TITLE
Discount and Tax report

### ISSUE THREAD

**Issue by rlltd** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#277]
The Tax Collected seems to calculate tax on the full sale value instead of the amount after discount.

When I remove the discount and reduce the price of the item on an invoice to the same amount, the Tax Collected amount decreases and the Profit increases...

**Comment by Uzair-RepairDesk** [comment]
Hey, @rlltd  we have an updated tax report from where you can view the accurate tax amount for each transaction. you can access the report under the sales report. 
Hope this helps.

Regards.
