### ISSUE TITLE
Help Chat Window is removed when navigating repair desk

### ISSUE THREAD

**Issue by TPRS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#279]
Hi,

If you are in a chat with the help team and move from one page on repair desk to another it will be removed and you have to pull it back up each time.

**Comment by repairnz** [comment]
I have this issue as well, very annoying when trying to make changes or test and chat with support at the same time.

**Comment by Repair-Desk** [comment]
Hello @TPRS @repairnz 

We are using third party chat service "Intercom" and when you move from one page on RepairDesk to another it closes automatically. 

What we would recommend is to use chat service from our homepage www.repairdesk.co while we try to find a way out.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
