### ISSUE TITLE
Serialized Parts

### ISSUE THREAD

**Issue by TPRS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#281]
The generate button won't generate a serial.

![image](https://user-images.githubusercontent.com/36774732/36634364-0c5f0e24-1969-11e8-93f3-90327e797d3b.png)

**Comment by TPRS** [comment]
It only seems to happen when we have different integers. 

![image](https://user-images.githubusercontent.com/36774732/36634462-9eb15f74-196a-11e8-9e04-de1341409194.png)
![image](https://user-images.githubusercontent.com/36774732/36634466-a527fa20-196a-11e8-9f03-95117d474594.png)

**Comment by Repair-Desk** [comment]
@TPRS Happy to help you with this. Currently RepairDesk serialized inventory module allow you to generate serials when you give out a range however I've discuss with product team and there should be an option that allow you to automatically generate serials for inventory items.

We are adding this feature to our roadmap and will keep you posted with the progress.

**Comment by Repair-Desk** [comment]
There should also be an option where you can select if it should be included in low stock report or not.

**Comment by Uzair-RepairDesk** [comment]
Hey @TPRS 
I am pleased to inform you that we have updated create serials functionality on your request. You can provide a value and generate serials automatically. 
You can find more details in following updated knowledgebase article:-
https://repairdesk.uservoice.com/knowledgebase/articles/930741-serialized-inventory

If you have further questions/feedback, please feel free to write back, Thanks

Regards,
Uzair from RepairDesk
