### ISSUE TITLE
Can't add manufacturer categories on the fly

### ISSUE THREAD

**Issue by TPRS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#284]
We can't add manufacturers on the fly with the POS.  

![image](https://user-images.githubusercontent.com/36774732/36758557-63938ab2-1bda-11e8-9f26-28b6326c4e0a.png)

To try and prevent this issue from happening I'm trying to add in most manufacturers I can think of for any category. However, I can't add the manufacturer to the category unless I have products under those categories.

![image](https://user-images.githubusercontent.com/36774732/36758694-d0973d3e-1bda-11e8-9ad2-bf3da80aca7a.png)

After I hit save it doesn't add the manufacturer. 

![image](https://user-images.githubusercontent.com/36774732/36758751-ea92a138-1bda-11e8-9e78-7e33a55992b0.png)

**Comment by TPRS** [comment]
This is what I've had to do to mask this issue. Add a 'computer' device to each manufacturer. The problem is these manufacturers have loooooads of different types which is why I wanted to just keep them blank but since I can't add manufacturers on the fly, I had to add in loads of things that we'll never use to prevent us having the add manufacturers to categories on the backend when the customer is in.

![image](https://user-images.githubusercontent.com/36774732/36759781-2875e9ee-1bde-11e8-937d-a788372aea41.png)

**Comment by Uzair-RepairDesk** [comment]
Hi @phonefixdfw 
We made this improvement that if you select a category and there is no manufacturer and you try to add existing manufacturer in the list, the system displays you alert and allows you to associate manufacturer and device with the specific category. 
Please check screenshot attached.

You can review at your end. Thanks. 

![uzairshah pos](https://user-images.githubusercontent.com/22955861/52852091-81145100-3139-11e9-8193-ac6b3dca96a3.png)
