### ISSUE TITLE
Appointment calendar widget - Terms not responsive mobile

### ISSUE THREAD

**Issue by ireparo** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#285]
Hi, at the final of the progress of making an appointent if you tap on terms & conditions is it not responsive from mobie because you cant read all the text and is very anoying to close it.

**Comment by Uzair-RepairDesk** [comment]
Hi @ireparo 
Can you please confirm if it's sorted and working for you now?
