### ISSUE TITLE
Campaign follow up emails going out every 2hours even tho these are switched off

### ISSUE THREAD

**Issue by pyropresents** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#288]
![screen shot 2018-03-13 at 12 00 55](https://user-images.githubusercontent.com/8068715/37340554-6f949e46-26b6-11e8-96e1-0d540193d6b2.png)

**Comment by Repair-Desk** [comment]
We sincerely apologize for the inconvenience and we have released a fix for this issue. Can you please confirm if you are still getting the same issue?
