### ISSUE TITLE
Update Customer Form in POS

### ISSUE THREAD

**Issue by TechnologyTraders** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#29]
Why does it give me the option to choose network when editing customer from pos instead of license no. like when editing customer details from trade-in. Why is everything redundant. Everything should be unified...
![update customer form in pos](https://cloud.githubusercontent.com/assets/22953208/19589468/a9e508e8-97af-11e6-87b2-2a1b5c2eaff4.jpg)
![update customer form in trade-ins](https://cloud.githubusercontent.com/assets/22953208/19589469/a9ecc04c-97af-11e6-9581-0fb462553621.jpg)

**Comment by Uzair-RepairDesk** [comment]
@TechnologyTraders 
We have plan to update customers module and Wholesale Pricing Functionality for B2B customer. I will make sure to take of this part once we do that in couple of weeks.
