### ISSUE TITLE
Choosing "hide tax" on estimate makes it $0.00 instead of hiding it

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#293]
when selecting "hide tax" on estimate receipt settings, it does not hides it but instead makes it seem like there will be no tax. It needs to either say "plus tax" if hidden, or just actually be hidden. Otherwise, customers will say "but it says $0 tax."
![image](https://user-images.githubusercontent.com/37640713/37748929-940df86e-2d53-11e8-8fbb-1ba559da82d8.png)

would also be nice in email templates to have option of using pre or post tax price. I'd prefer an emailed estimate to say "99.99 plus tax" instead of $108.24

**Comment by usmanalikhan93** [comment]
Hey @phonefixdfw 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw  

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.
