### ISSUE TITLE
Google Calnedar integration not updating when the ticket Updated or deleted

### ISSUE THREAD

**Issue by youzlar** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#295]
when  creating a ticket and assigning  to employee

it is showing on google calendar ,  but when updating the due time or even deleting the ticket   it is not affecting on google calednar

**Comment by Repair-Desk** [comment]
Hello @youzlar 

Thanks for sharing your feedback regarding Google Calendar integration. We will review it internally and see if we can release a fix for it in next few weeks.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Usman

**Comment by Uzair-RepairDesk** [comment]
Its working fine, upon updating the ticket its updating ticket and upon deletion ticket is removed from google calendar aswell.
