### ISSUE TITLE
Issue when adding inventory items to ticket

### ISSUE THREAD

**Issue by alexdechant** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#298]
Cannot add more than 1 item to an inventory item to a ticket after it has been created. We need a solution for if a tech comes across a defective part and how we can take multiple out of iinventory

**Comment by Repair-Desk** [comment]
@alexdechant I believe once ticket item has been established and you increase quantity level it doesn't update the row. 

Assigning it to our QA team so they can review it and release a fix early next week!

**Comment by Repair-Desk** [comment]
**@alexdechant** 

We've reviewed this internally. 

By default **"RepairDesk"** allows you to add one stock against a line item. I've marked the task as improvement so we can study its impact analysis and release an improvement accordingly.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Usman
