### ISSUE TITLE
Show on Widget is missing in service import / export

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#303]
When you export service item in XLS format it doesn't have "Show on widget" column. Would be good to have this option incase you want to mass update.

Also Show on widget should be available while you are importing service items

![changes](https://user-images.githubusercontent.com/21986026/40567344-54acbee4-608e-11e8-850b-501f4f99475a.png)

**Comment by Repair-Desk** [comment]
**Eric**

We've just released a fix that will now allow you to map **"Show on widget"** option through XLS spreadsheet. 

<img width="1280" alt="screen shot 2018-06-05 at 10 32 44 am" src="https://user-images.githubusercontent.com/21986026/40956856-d783b780-68ab-11e8-95f3-c371f74e38d6.png">

**Comment by usmanalikhan93** [comment]
Hi @Eric!
Your issue has been fixed. Please verify at your end and do let us know if you have question.
Thanks!
