### ISSUE TITLE
Bulk Upload - List of devices

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#305]
Hello! I have a suggestion for you: it would be really awesome if we could add a list of devices (xls, for example) in "View all devices". We want to add charging connectors that are compatible with many models and we have to do it one by one, because the list given by you is not really complete. Having the option to import a list of devices made in Excel via a table would make things a lot easier.

Thank you! We'd love this feature to be implemented.

**Comment by Uzair-RepairDesk** [comment]
We have the Import/Export feature available under manage devices.
