### ISSUE TITLE
automatic cost estimate

### ISSUE THREAD

**Issue by handyplanet** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#307]
hi development team,

me and much other client of repairdesk want a future for cost estimate like in repairline.de

details:
after we create a Ticket for diagnostic of a device we create a cost estimate after the diagnose is finish
the customer gets an email with a link, from this link he can see the cost estimate for his device and have 2 Buttons with ACCEPT or REJECT.. whatever he clicks the status update will change from waiting response customer to "cost estimate accepted or rejected"

without any call.. this will be great

**Comment by Repair-Desk** [comment]
Sounds like a great feature suggestion. We are re-writing our tickets module where we've also planned repair estimate approval via customer portal or an external link. You will also be able to accept deposit via hosted page. You can read more about it here: https://www.facebook.com/groups/1566154750347714/

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
