### ISSUE TITLE
Point of Sale - Quick search is missing if you browse items by category

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#310]
Under Accessories >> my point is that if you click by category, that quick search box is not there anymore

**Comment by phonefixdfw** [comment]
![image](https://user-images.githubusercontent.com/37640713/40695106-41a6bab2-6385-11e8-9ea1-6264aaf31be3.png)

**Comment by Repair-Desk** [comment]
Thanks for the message, we'll get back to you as soon as
possible!

On May 29, 2018 at 7:15 PM Repair-DeskPOS/RepairDesk-Bugs
wrote:

![image](https://user-images.githubusercontent.com/37640713/40695106-41a6bab2-6385-11e8-9ea1-6264aaf31be3.png
( https://user-images.githubusercontent.com/37640713/40695106-41a6bab2-6385-11e8-9ea1-6264aaf31be3.png ))

--

You are receiving this because you authored the thread.

Reply to this email directly or view it on GitHub:

https://github.com/Repair-DeskPOS/RepairDesk-Bugs/issues/310#issuecomment-393008041
( https://github.com/Repair-DeskPOS/RepairDesk-Bugs/issues/310#issuecomment-393008041 )

Powered by UserVoice. ( http://www.uservoice.com/powered-by?utm_campaign=poweredby&utm_medium=email&utm_source=ticket&uv_company=RepairDesk&uv_contact_url=repairdesk.uservoice.com&uv_experience=email )

**Comment by Uzair-RepairDesk** [comment]
We are catering this in 2.0
