### ISSUE TITLE
Bulk Upload of unlock services not working

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#314]
Initially appears to work but once you go through all the steps it does not import all items after the final step. I was trying to import 6 items and only 1 was added. Importing again added 1 more, then ended up causing duplicates.

**Comment by Repair-Desk** [comment]
Sorry for the trouble. We have received few support requests where customers has mentioned that the import inventory module stops working if you upload more than 5000 items.

We are reviewing and monitoring the bugs closely and will try to release a fix in next 2-3 weeks

**Comment by usmanalikhan93** [comment]
Sure @Repair-Desk!

Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hello @phonefixdfw!

I have checked your concern but unfortunately I am unable to reproduce your issue. Would be great if you can share a video of this issue so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Regards,
Usman Ali
