### ISSUE TITLE
POS - incorrect user assignment

### ISSUE THREAD

**Issue by geelongmicrosoldering** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#322]
In a POS environment with multiple staff members, more than one person may be using the computer throughout a shift.

If User A is logged in, and User B processes a transaction, the pin number for User A is asked at the end of the transaction (if enabled).

If User B changes the user to User B and enters pin, the job or transaction is booked in or processed as User A, because that's who was logged in at the start of the transaction. All initial notes, the creation of the ticket and invoice, are under the wrong user. 

Upon last test, this also throws commissions out, because the person who took the payment may be the person who was logged in in the beginning, not the person who typed the pin at the end.

This could be fixed in one of the following ways.

-Require the pin number at the start of the POS transaction. This is how most POS systems work, and protects the information within POS from unauthorised users. This would be the best approach, and for those with barcode scanners, barcodes could be printed for staff members for quick POS access, without manual pin entry.

-Assign the job notes, payments, ticket and invoice creator, at the end of the transaction rather than the start.

**Comment by Uzair-RepairDesk** [comment]
Hi @geelongmicrosoldering 

If you confirm the PIN of the user, transaction recorded with the same user. Can you please specify the above scenario with examples and screenshots so I can assist you. Thanks

Regards,
Uzair from RepairDesk

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
