### ISSUE TITLE
2 Way SMS Integration outside of the US

### ISSUE THREAD

**Issue by geelongmicrosoldering** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#324]
Clickatell 2 way integration is nice, but for customers in some countries, there are no phone numbers available, so it is not possible.

Research would be required, but 2 way integration with a service like SMS Global (assuming it has available phone numbers) would be nice. 

Failing that, opening the RepairDesk API to support 2 way SMS, would enable developers to achieve this task with their own provided SIM card and hardware, without the need for a subscription service, in any location

**Comment by Repair-Desk** [comment]
**Hey @geelongmicrosoldering,** 

We do want to introduce 2 way SMS option for  **SMS broadcast, Textlocal & SMS Global integration** however I don't have a timeline. I've pinned it to our roadmap and will keep you posted on our progress.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Usman

**Comment by Repair-Desk** [comment]
Hello @geelongmicrosoldering,

We've started development for 2 way SMS and looking to roll it out to production environment in next 2-4 weeks.

I've also attached some of the design so you can get an idea on how this will work:
![email-of-sms-alert 1](https://user-images.githubusercontent.com/21986026/42207797-3dd67e0e-7ec4-11e8-8556-1b35ca25bbd7.jpg)
![sms-alerts-dropdown 1](https://user-images.githubusercontent.com/21986026/42207799-3e11f34e-7ec4-11e8-8c7c-2591b5a1f328.jpg)
![sms-notification 1](https://user-images.githubusercontent.com/21986026/42207800-3e46914e-7ec4-11e8-8769-c5cff44a70ba.jpg)

**Comment by quangc** [comment]
Nice, will look forward to see it works.

**Comment by Uzair-RepairDesk** [comment]
Hi @geelongmicrosoldering @quangc 
We have implemented 2 way SMS feature for "SMS Broadcast" integration. You can find details from the following knowledgebase article link.
https://repairdesk.uservoice.com/knowledgebase/articles/784326-how-can-i-setup-sms-broadcast-api
