### ISSUE TITLE
Add Date and Technician initials 

### ISSUE THREAD

**Issue by smmmobiles3205** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#326]
Hi,

Please Add Date and Technician initials next to customers signature on Tax Invoices. So we have accurate info on when customers take their devices and the Tech who signed them out.

**Comment by geelongmicrosoldering** [comment]
You already have almost all that information. Its all in the notes for the ticket. If you want to use paper to keep records, you can modify the template yourself.

FYI the customer signature line is actually prefilled if you use customer facing display. Thats why its there. Not for paper records.

What would be good though, is knowing who accepted a payment. Especially when multiple payments are made. So sales person in the payment history table on view invoice would be good.

**Comment by Uzair-RepairDesk** [comment]
We have already this information display over the invoice. You can customize it from the template editor as well.
