### ISSUE TITLE
PO and Inventory Transfer not showing product code 

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#328]
when we transfer inventory to another store , we just make a list of product code and then add . 
but when list is big , it becomes headache because it doesn't show the last entered product code. then we always confused if we missed some item. 
can you please make that visible ?

also , process if adding item in Transfer Inventory and PO
is very slow. it actually reload the entire page after each step. that's where most time is take. 

please have a look. 
thx.

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk We should release a fix for this!

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
We have added this feature on your request. If you add an item in PO or Inventory Transfer and there is no SKU exist for the specific item, system displays item ID now. 
Please review at your end. Thanks.
