### ISSUE TITLE
Ability to change warranty period through excel doc upload 

### ISSUE THREAD

**Issue by alexdechant** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#329]
not really a bug, but we don't have the option to update warranty period's on repairs through a excel doc upload.

**Comment by usmanalikhan93** [comment]
Hi @alexdechant!
I have checked your concern and you can update warranty period's on repairs through a excel doc. I am attaching couple of screenshots. 
![36](https://user-images.githubusercontent.com/39614480/40970440-09f62324-68d4-11e8-88d9-d3aa18f6f294.png)
![36_a](https://user-images.githubusercontent.com/39614480/40970441-0a26ba3e-68d4-11e8-940e-c80778172939.png)
![36_b](https://user-images.githubusercontent.com/39614480/40970442-0a581926-68d4-11e8-9150-9027438db70f.png)

**Comment by usmanalikhan93** [comment]
Hi @alexdechant 

I hope you are doing well. Can you check again this ? I hope it's fixed now. If you have any question do let us know. 

Usman Ali.
