### ISSUE TITLE
Feature Request: Unlock API should update cost from vendor

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#332]
In unlocking API, cost needs to be updatable via api.

If we integrate with imeigurus for an s8 unlock that they charge $100 for and they update price to be $160, there is no way to see that in repairdesk. Therefore, we must visit the unlock website anyways to verify price and terms are current. These values should either update on the fly or have a button to click to manually refresh. 

Additionally, allowing a set % or $ markup to convert cost to price would be helpful too.

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk Can we have Zain look into this?
