### ISSUE TITLE
Trigger Email / SMS On Custom Ticket / Purchase Order or Inventory Transfer Status

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#333]
Ticket status' and their canned responses need a major overhaul.

We have option to create a custom ticket status, but if we do that, the new status can't have any sms or email canned response/notification.

Additionally, we really have no clue what canned response gets sent when.

# There needs to be option panel for each ticket status that lets you choose a canned response/notification to trigger when that status is selected.

**Comment by Repair-Desk** [comment]
@phonefixdfw 100% agreed. Pinned to roadmap for improvements

**Comment by Repair-Desk** [comment]
Hello Brandon,

I hope you have been well. Based on your feedback our design team has proposed below designs that will fulfil your workflow needs. 

![Image](https://i.imgur.com/XsLkgsX.jpg)

![Image](https://i.imgur.com/jQKZcjR.jpg)

Do let us know if this will work so we can move forward with the development.

Kind Regards,
Usman

**Comment by Uzair-RepairDesk** [comment]
Hey Brandon @phonefixdfw 
I have already sent you details on Facebook so you can review the updated module on BETA server and share your feedback before we GO LIVE. Thanks

**Comment by phonefixdfw** [comment]
Sorry I have been sick and haven't got to test this yet. I will now. It
will only use these alerts for tickets i make on the beta login, not our
normal site, correct?


9034 Garland Rd, Dallas 75218
4321 Lemmon Ave, Dallas 75219
7340 Highway 78, Suite 260, Sachse 75048
972-587-7433 <https://mail.google.com/mail/u/0/> | www.phone-fix.com

**Comment by Uzair-RepairDesk** [comment]
Hey Brandon @phonefixdfw 
We have made the updated module LIVE.
