### ISSUE TITLE
Photo upload “in progress” or “ post repair” iOS app

### ISSUE THREAD

**Issue by jwfarlow** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#334]
Would it be a big problem to add a "post repair" photo upload option to the ios app?

ill give you a specific example

i had a customer that had a broken selfie cam on a 6s, she said everything was oem with no water damage, i want to be able to photograph the red indicators and aftermarket parts she has in the phone, and to have on file just in case... 

i know this can be accomplished through the website, and thats the current solution, but im starting to send a few guys to do mobile repairs, and that will not be an option.

Thanks in advance!!!!

**Comment by Uzair-RepairDesk** [comment]
We have introduced our new iOS that allows you to upload pre/post repair images
