### ISSUE TITLE
Transactions from one store went to other stores

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#341]
This start to happen with our new store in the system. Transaction from one store went to other store's register and mess up the whole day of sales. Please investigate this one as it is urgent.

**Comment by usmanalikhan93** [comment]
Hey @quangc! 

I hope you are well. We are unable to reproduce your issue. Would be great if you can share a video of this issue so we can release a fix during our next release. You can put together a video using Screencastify

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
usman ali

**Comment by quangc** [comment]
Please see attached photos of today transactions.

**Comment by quangc** [comment]
![screen shot 2018-07-10 at 5 33 18 pm](https://user-images.githubusercontent.com/22993605/42495855-a974b218-8467-11e8-96e0-5873fe4d2e3c.png)
![screen shot 2018-07-10 at 5 33 35 pm](https://user-images.githubusercontent.com/22993605/42495856-a9ace34a-8467-11e8-9d47-dce2bead85cc.png)

**Comment by quangc** [comment]
When staff at Carnegie store started shift at 1:05pm, all transactions from Springvale store go to Carnegie register.

**Comment by usmanalikhan93** [comment]
Hi @quangc , 

Thanks for the update on this. We will need to investigate it internally and will release a fix soon.

Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @quangc 

We have checked your concern but we are unable to reproduce it. Can you check is it now working fine or not?

**Comment by quangc** [comment]
How can u reproduce it after 2 months?

You will need to log into our system and look back on that time frame and see the system logs to find out what happened.

Best Regards,
Quang Cao.
General Manager.
+ Repair Centre Frankston
+ Repair Centre Springvale
+ Repair Partners
P: 1300 89 82 99
A : Shop 6 Shannon Street Mall, Frankston, Vic, 3199.

**Comment by usmanalikhan93** [comment]
@quangc  

We have checked this in that time frame. Let us check once again this on Monday.

**Comment by usmanalikhan93** [comment]
Hi again @quangc   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali.
