### ISSUE TITLE
504 Syntax Error

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#342]
I have this Syntax error and when i am trying to select the correct Woocommerce category it is not working. 

Maybe these are both linked and i cannot select it because the Syntax Error?

**Comment by benjamingartner** [comment]
![image](https://user-images.githubusercontent.com/39751801/41535288-559202ca-7334-11e8-9b7a-9e73a674c898.png)

**Comment by Repair-Desk** [comment]
**Hello @benjamingartner** 

Sorry for the delay however it looks like the integration is not setup properly.

Also are you still getting the same error? Please advise

**Usman**

**Comment by benjamingartner** [comment]
I am still getting the same errors. This image done right now
![image](https://user-images.githubusercontent.com/39751801/42123569-bf98d0da-7c86-11e8-8834-6f6dbd855196.png)

**Comment by benjamingartner** [comment]
I am still experiencing this issue.

**Comment by benjamingartner** [comment]
Also now receiving this error, 
![image](https://user-images.githubusercontent.com/39751801/42127127-d4052034-7cc5-11e8-9859-97ec55baefe4.png) << this product is not showing in Wordpress after i deleted it because it wasnt syncing.

**Comment by benjamingartner** [comment]
And my categories from WooCommerce have gone. 
![image](https://user-images.githubusercontent.com/39751801/42127162-4e700b86-7cc6-11e8-98d2-44c9e0072579.png)

I would assume this has been caused by me updating to SSL on my website?

**Comment by benjamingartner** [comment]
Is there any progress on this?

**Comment by Repair-Desk** [comment]
@usmanalikhan93 Can you report this to product team so they can take a look?

**Comment by usmanalikhan93** [comment]
sure @Repair-Desk

**Comment by benjamingartner** [comment]
Any news?

The longer this takes, the longer my website is malfunctioning and i am trying to finally get more traffic through our website as times are tough atm.

**Comment by Repair-Desk** [comment]
Hellow @benjamingartner 

Please find developer feedback:

It appears to their hosting provider issue. Looks like the server may not support POST or PUT request. We need WordPress login details to debug this further. 

I've also sent you a PM on Facebook for these details :)

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Usman

**Comment by benjamingartner** [comment]
Hi Usman,

I have provided the details to you through PM.

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner ,

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by benjamingartner** [comment]
Guys, thanks for fixing this..... It worked for about 2 days and this again now.

**Comment by benjamingartner** [comment]
![image](https://user-images.githubusercontent.com/39751801/43059384-bbde83ea-8e7e-11e8-8cc3-ff1be9c70f6f.png)

**Comment by Repair-Desk** [comment]
Hey @benjamingartner 

Happy Monday and I hope the weekend went well.

Please find our developer feedback as below:

~~~~~~~~~~~~~~~~~
There was rest authentication issue which required an update in .htaccess file. I've updated the file and product syncing seems to work. Please verify on your end and do let us know if you need further assistance.

Kind Regards,
Usman Butt
