### ISSUE TITLE
New Sell Device canned response

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#348]
Hello,
I do not know if this is a configuration problem, but the programmed response of a new phone sale, "New Sell Device" is correctly configured. However, the customer receives the message all wrong. The image is oversized and the majority of the text is missing. See the two attachments.

<img width="935" alt="canned response" src="https://user-images.githubusercontent.com/40500094/41790863-ee313cae-7621-11e8-8b71-b972d628e618.png">
<img width="525" alt="mail customer receive" src="https://user-images.githubusercontent.com/40500094/41790867-f4ae8028-7621-11e8-8185-3ff2760ac3b8.png">

--
French:
Bonjour,
Je ne sais pas s'il s'agit d'un problème de configuration, mais la réponse programmée d'une nouvelle vente de téléphone, "New Sell Device" est correctement configuré. Cependant, le client reçoit le message tout croche. L'image est surdimensionné et la majorité du texte est manquant. Voir les deux pièces jointes._

**Comment by Repair-Desk** [comment]
@JessicaSOS  👋 Sure thing! Let us take a look to see if we're getting the same issue as you and we'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS!

It may be an account specific issue. Because I have checked it on my end and I am unable to reproduce it. One of our support ninja will reach out to you to get more information. 

Thanks.

**Comment by JessicaSOS** [comment]
@usmanalikhan93 

The email I receive (by being the client) is not like the template registered in the cannded response. The image appears very very big and it misses passages of the text.

We did 2 tests, Ali received the email correctly but, not me. I did a screen shot of what I received. I thought the problem probably came from my email, but some customers tell us they do not understand the email they just received. This is not a problem caused by my email address.

I remain at your disposal if you have other questions,
Have a good day

**Comment by Repair-Desk** [comment]
Hello @JessicaSOS 

Thanks for your email. 

It looks like when an email is received on Gmail it renders properly however when the same email is received on webmail or outlook it's not displayed properly.

I've advised the development team to optimize HTML for your "custom canned response"

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks, and I look forward to a long term partnership here!

Usman

**Comment by JessicaSOS** [comment]
Optimization will be done quickly? 

Can you check all the canned responses to be sure you do not have the same problem in others?

 

-- 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579,204> 418-999-1579 |  <tel:18559991579,204> 1-855-999-1579 | Extension : 204
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375 bvd Guillaume Couture, Lévis, G6V 4Z3
2750 1re Ave, Ville de Québec, QC G1L 3N8
977 route de l'Église, Ste-Foy, G1V 3V3
835 rue St-Joseph Est, St-Roch, G1K 3C8

 <http://www.facebook.com/groups/173894875954415/#!/pages/SOS-Phone/169687599716789> 

 

 

De : Repair-Desk <notifications@github.com> 
Envoyé : 27 juin 2018 05:43
À : Repair-DeskPOS/RepairDesk-Bugs <RepairDesk-Bugs@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-Bugs] New Sell Device canned response (#348)

 

Hello @JessicaSOS <https://github.com/JessicaSOS> 

Thanks for your email.

It looks like when an email is received on Gmail it renders properly however when the same email is received on webmail or outlook it's not displayed properly.

I've advised the development team to optimize HTML for your "custom canned response"

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks, and I look forward to a long term partnership here!

Usman

**Comment by Repair-Desk** [comment]
**Hello @JessicaSOS,**

I don't have a definite timeline but we will try to review it ASAP.

Our default canned response work across all email platforms however if you've customized canned response we would recommend you to test this internally.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

**Usman**

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question. :)

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
Hello,

Sorry for the response time. I tested and it is corrected. 

Thank you very much.

 

 

-- 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579,204> 418-999-1579 |  <tel:18559991579,204> 1-855-999-1579 | Extension : 204
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375 bvd Guillaume Couture, Lévis, G6V 4Z3
2750 1re Ave, Ville de Québec, QC G1L 3N8
977 route de l'Église, Ste-Foy, G1V 3V3
835 rue St-Joseph Est, St-Roch, G1K 3C8

 <http://www.facebook.com/groups/173894875954415/#!/pages/SOS-Phone/169687599716789> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 27 juillet 2018 10:58
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] New Sell Device canned response (#348)

 

Closed #348 <https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/348> .
