### ISSUE TITLE
Customers module - Tickets & Invoice Listing Order

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#349]
So I'm just wondering if others have noticed this. There's no rhyme or reason to the ticket list order under a customer. There is no order to them. Not by job number or by date. Makes it frustrating. I'll confirm jobs on the first page. Yet new jobs could be at the top of the list or on the second page or even half way down. Is there a reason to this unorganisation? Even if I try to sort by id or date at the top of the table there is no logical reason to how it orders it. Seems pointless. Also when we search for customers from the top. And specifically select 'customers' we can't search by company name. Sure we can on the next page when we get no results where we can search by 'organisation' but what's the point to this search feature? We don't only search for customers by name. Also by company name. We might have put an original contact name in (as a new customer requires a full name) but often we just want to search and inspect a companies repair history. Without having to know the direct contact name of someone.

**Reported: Michael - ITZ Computer**

**Comment by Repair-Desk** [comment]
**Hello @usmanalikhan93,** 

Can you please give it a whirl and also check with the development team that in which order does it display tickets or invoices.

**I believe we should add following improvements: -**

![improvements](https://user-images.githubusercontent.com/21986026/42083400-3ddd7c40-7ba4-11e8-92f2-68d4d602e95b.png)

**Comment by Uzair-RepairDesk** [comment]
Improvements for the listing of associated tickets and customers on the manage customers page are suggested above. 

At the moment, we haven't included this option to search customer from the company name at top of the page. I see where you are coming from on this though, so I'm happy to pass on this feedback to the team for you.
We have a plan to improve our complete customer's module. We have completed the functionality specifications however, we will add your feedback in the same document. 

If you have any further feedback you would like to add, just let me know!

**Comment by Uzair-RepairDesk** [comment]
We have made improvements. On customer details page, tickets and invoices listing data will display in order now. You can also sort tickets and invoices listing with respect to "ID" and "Date". 
Note: You need to click on "Date" twice if you want to sort tickets/invoices from "Date" field because system clears the ID sorting first and then sort the listing with dates.
