### ISSUE TITLE
Quickbooks Not Syncing

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#355]
I have now realised an issue with Quickbooks not syncing. I have a bulk amount of invoices that "Failed" to sync.

I am not too happy about this because i have only just had you guys rectify this a few months ago. 

As a result of you rectifying it previously, RepairDesk was synced with Quickbooks several times causing multiple copies in Quickbooks which cost me $1,700 to rectify. 

Very un-happy about this and expect a quick resolution. You need to focus on improving current integrations etc.

**Comment by Repair-Desk** [comment]
Hey @benjamingartner 👋 

Sure thing! Let us take a look and we'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hello @benjamingartner!

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!

**Comment by benjamingartner** [comment]
Sorry, i have just gone with not syncing the two programs. It seems a little hard for now.
