### ISSUE TITLE
Add warranty length

### ISSUE THREAD

**Issue by TheSavageCanadian** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#357]
Would it be possible to add warranty length of the repair on the invoice for each device ? Thank you.

**Comment by Uzair-RepairDesk** [comment]
Hi @TheSavageCanadian , Thank you for sharing the suggestion. Can you please explain if you either want to display warranty duration on the invoice or you are looking for an option to update the warranty time frame for the customer?

Looking forward to hearing from you. Thanks

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
