### ISSUE TITLE
Using same contact number for Different members of family 

### ISSUE THREAD

**Issue by Billsalih** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#359]
when booking in customers at counter and thet is a number that's stored in the system and they come in again and use the same number but different name it does not allow you to cancel and procveed
some families may use same contact number but Differ member of Family

**Comment by Repair-Desk** [comment]
Hey @Billsalih 

At the moment, we haven't included this option that allow you to add relative details. I see where you are coming from on this though, so I'm happy to pass on this feedback to the team for you   
​
If you have any further feedback you would like to add, just let me know! Happy to pass on the best details possible for you

**Comment by Billsalih** [comment]
All that's needed is a cancel button otherwise you can't proceed and have to start again.

**Comment by Uzair-RepairDesk** [comment]
Hi @Billsalih 
Under manage customer section, we have given an option to add "Contact Person Details" with "Relation". You can edit the customer profile and add it. 

Check screenshot attached
![uzairshahRepairDesk-Update-Customer](https://user-images.githubusercontent.com/22955861/89752016-fb821f00-daeb-11ea-9538-dc10fa0f6cfc.png)
