### ISSUE TITLE
commission changes on inventory import only change 1 location

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#361]
I changed commission % via export/import of inventory for certain items. When i reimport that file, the commission only changes for that location. I can't import that same file to another location because it changes the # in stock and other variables. I deleted the in stock column and tried importing, and it made inventory in stock # all 0's. I don't really want to manually edit all the #'s again. I'd say this is a bug.

**Comment by Repair-Desk** [comment]
Hey @phonefixdfw ! 👋 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw  

We are working on Employee commission module. And we hope after the update you issue will be fixed. 
I will let you know once the new module is available for beta testing. Thanks

Thanks 
Usman Ali.

**Comment by Repair-Desk** [comment]
Hello @phonefixdfw,

Just wanted to let you know that I went ahead and flagged this with my product team so they know this is something you'd like to see. Definitely makes sense if you import a commission on head office it should be updated on other locations.

I'll make sure your voice is heard here.

**Usman Butt**
