### ISSUE TITLE
Multiple Issues - Bharat feedback 

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#363]
on one my other comment  Usman replied saying ,  their are only 10 bugs. 
I didn't reply there , coz I know there are more than 50 bugs. 
but I prefer spending my time fixing phones instead of listing bugs here. 

Usman , THERE IS A VERY THIN LINE BETWEEN " BUGS and IMPROVEMENT ".

Perhaps some features your team takes as improvement,,but for end users thats actually a bug. 

for example ;

PO doesn't save the item price in inventory. ITS A BUG , NOT AN IMPROVEMENT. 

Staff is viewing cost pricing in PO even we have untick that option, it's a bug.

In PO , we can search item by product code , but that product code doesn't remain  visible when we save it. 
however if we serach via sku, it remains visible. 
Yes. It's a bug too. 

Sometime POS window gets payment error. YES.THIS BUG IS STILL THERE. 
We have just stopped complaining about it everyday.

so many other small things ....

but we can not focus on bugs, we just skip it and get our work going .

But as Will Arden said,
SOMETIME ITS FRUSTRATING.

I still love repair desk. But I'm just putting all these things just to improve it functionality.

**Comment by usmanalikhan93** [comment]
Sure thing! Let me take a look to see if I'm getting these same issues as you and I'll circle back to you.
