### ISSUE TITLE
sales tax on purchase orders

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#364]
If you add a line to a po and dont select tax exempt before you add that line item, the sales tax is stuck down here. 

You can edit the PO and it will show $0 sales tax in line items but still shows in summary @ the bottom. 

Additionally, why does it always add sales tax by default with 99% of the time, we as a business are not paying sales tax on parts we purchase?

![image](https://user-images.githubusercontent.com/37640713/42524881-61013c8e-8437-11e8-8415-c7308faa3136.png)

**Comment by usmanalikhan93** [comment]
Hey @phonefixdfw , 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Thanks.

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a scenario with us, so we can release a fix during our next release. You can put together a video using Screencastify.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Regards,
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again.
Usman Ali here - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
