### ISSUE TITLE
Customer group discount method revisions

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#365]
Please have the discount method as $ instead of % in customer groups? It is not realistic to discount % of services as some services have really low margin. A specific $ discount will make more sense.

**Comment by Uzair-RepairDesk** [comment]
Hi @quangc 
Thank you for sharing your idea. Can you confirm the following?
If you give $ value discount, do you want to apply it to the total of the item? E.g. if the Item1 price is $100 (along with tax) and you have given $10 value for a specific customer group, do you want to apply it total to make it $90 price?

Looking forward to hearing from you

**Comment by Uzair-RepairDesk** [comment]
Hi @quangc 
Thank you for sharing your idea. Can you confirm the following?
If you give $ value discount, do you want to apply it to the total of the item? E.g. if the Item1 price is $100 (along with tax) and you have given $10 value for a specific customer group, do you want to apply it total to make it $90 price?

Looking forward to hearing from you

**Comment by quangc** [comment]
That is right.
