### ISSUE TITLE
PO is Missing QTY after saving 

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#366]
When we create a po, and save it.
later open it to edit / add more items.
all qty turns to zero.
so we have to update all qty again.

**Comment by usmanalikhan93** [comment]
Hello @bharaaus!

Your reported issue has been assigned to development team and I hopefully it will be fixed this week.
Your patience would be highly appreciated.
Thanks!

Usman Ali

**Comment by usmanalikhan93** [comment]
Hey @bharaaus!

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
