### ISSUE TITLE
Ticket Number are overriding

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#367]
Our tickets number was upto T-17xx . 
but suddenly it has started from begining again.  Like T-031 / T-032 and so on.

Now all those old tickets are overriding. 
Reported this issue from more than a week ago.
It should have done on priority basis.
Important customer data is messing up .
Still there is no fix for it from long time.
Any Idea, when will it be fixed ?

**Comment by Repair-Desk** [comment]
Hello Bharat,

We sincerely apologise for the inconvenience.

For the second store I would recommend you to change ticket initials so RepairDesk doesn’t override the ticket number when you transfer ticket from one store to another store.

Location A ticket number T-17xx (current format)
Location B ticket number T2-xxx

Here’s an article that talks about how to change ticket number: https://repairdesk.uservoice.com/knowledgebase/articles/922107-how-do-i-change-ticket-numbers

Once you change a ticket number it will automatically update the ticket number when you create a new ticket.

**Comment by bharaaus** [comment]
Thank you for reply. 
I will mark store A ticket like ; T-xxx
and 
Store B ticket like; P-xxx

I will test that tomorrow.
