### ISSUE TITLE
Printnode speed issue

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#368]
Printnode speeds suck lately. Is there anything we can do to have instant draw opening rather than sometimes up-to a 1 minute wait.

Source: Facebook

**Comment by bharaaus** [comment]
I have noticed, the speed issue is mainly when we book repair ticket and do payment invoice,
It takes 30-40 seconds. or sometimes even a minute.

But anything else, like printing barcode from PO / GRN : It takes only 3 seconds. Which should be case in all the printing command.
Has you guys found a solution for this 
?

**Comment by bharaaus** [comment]
Hi,
Thanks for the Suggestions. It worked well.
I have removed the logo from the invoice and now printing time is 10-12 Seconds.
However, when we print label or anything  else from system ( not from POS window ) it takes only 3-4 seconds.

Hope you can find something more suggestion to increase print speed from POS window.

**Comment by usmanalikhan93** [comment]
@bharaaus  

Noted. :)
