### ISSUE TITLE
purchase orders 

### ISSUE THREAD

**Issue by Cumbr1at3ch** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#370]
hi guys 
purchase orders, Something incorrect when entering a part the software fills in the field underneath that you are currently entering. and also the description of the field concerned is blank when you print the relevant order off

**Comment by usmanalikhan93** [comment]
Hey @Cumbr1at3ch 👋 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Usman Ali.

**Comment by usmanalikhan93** [comment]
Hey @Cumbr1at3ch!

Your reported issue has been assigned to development team and I hopefully it will be fixed early next week.
Your patience would be highly appreciated.
Thanks!

Usman Ali

**Comment by usmanalikhan93** [comment]
Matt Smith also reported this issue on Facebook.

**Comment by usmanalikhan93** [comment]
Hi @Cumbr1at3ch!

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
