### ISSUE TITLE
P.O Quantity disappear

### ISSUE THREAD

**Issue by alexdechant** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#371]
disappearing P.O quantities frequently happening after saving

**Comment by usmanalikhan93** [comment]
Hi @alexdechant!

Sorry for the inconvenience. This is a known issue. We are already working on it. Hopefully it will be fixed in next 24-48 hours. Your patience would be highly appreciated.

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @alexdechant!

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
