### ISSUE TITLE
SMS and Email canned template does not populated correctly

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#372]
The {fields} don't get populated and stayed at it. I think the code of the fields have changed and did not get updated into the system so it does not understand those fields.

Please investigate and fix asap since we don't want to manually do it. Otherwise please advise new fields name so we can update ourselves

**Comment by quangc** [comment]
![screen shot 2018-07-18 at 10 44 15 am](https://user-images.githubusercontent.com/22993605/42853129-e64be240-8a77-11e8-8d0c-bd80659c4c42.png)

**Comment by usmanalikhan93** [comment]
Hey @quangc @bharaaus 

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Usman Ali

**Comment by usmanalikhan93** [comment]
Hey @quangc!

Just want to confirm that are you facing this issue against all canned responses? 

Usman Ali

**Comment by usmanalikhan93** [comment]
@quangc  

Can you please specify ? it will be easy for us to check then. 

Usman Ali

**Comment by quangc** [comment]
![screen shot 2018-08-01 at 3 07 48 pm](https://user-images.githubusercontent.com/22993605/43502159-ae9d7f36-959c-11e8-8196-cd09203dbbbe.png)

**Comment by usmanalikhan93** [comment]
Thanks @quangc . I am assigning this  to developer and hope it will be fixed soon. I'll get back to you as soon as I have more information! 

Usman Ali

**Comment by usmanalikhan93** [comment]
Hey @quangc  

I hope you are doing well. Can you share a SMS screenshot ? Also we need a test number to test this.

**Comment by usmanalikhan93** [comment]
Hi @quangc  

We are improving this module, See the screenshot 
![572](https://user-images.githubusercontent.com/39614480/44983940-7e131300-af94-11e8-8edf-3a025b3bd481.PNG)
I will let you know once the new module is available for beta testing. Your patience would be highly appreciated.
Thanks!
Usman Ali.
