### ISSUE TITLE
Show on POS trigger is not working in Parts section - Cassandra

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#374]
If we've hidden a part by unchecking Show on POS trigger. It shouldn't display on POS.
But right now if we've a part and its Show on POS trigger is unchecked it still displays on POS while we are on POS and booking a Repair by selecting Category>>Manufacturer>>Devices>>Problems>>**Parts**>>Details

In **Parts** its still displaying.

Please check.
Thanks.

**Comment by usmanalikhan93** [comment]
Hey! @ali-repairdesk 👋 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
Your reported issue has been assigned to development team and I hopefully it will be fixed early next week.
Your patience would be highly appreciated.
Thanks!

**Comment by usmanalikhan93** [comment]
@ali-repairdesk  

Issue is fixed now. Please check on your end.

**Comment by ali-repairdesk** [comment]
Thanks @usmanalikhan93  for the quick fix. I've updated the customer on LiveChat & on call both.
