### ISSUE TITLE
Need Phone Model Visible in Customer Details

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#375]
![need phone model](https://user-images.githubusercontent.com/34261339/42979421-6bf3ce46-8c15-11e8-8c44-a086dd2f6149.png)

Its always takes few click to see customer's repair history.
Can you please add option to view phone model on same window ?

Regards,

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus, Thank you for highlighting this. We have plan to rewrite our customer's module and I believe we should definitely display Manufacturer/Device in Repair history of the customer. I have updated the status and add it to the roadmap with "Improvements in customers module".

**Comment by bharaaus** [comment]
Thank you.
I will update another improvement suggestion regarding customer module in future when you work on it. 
Cheers !

**Comment by Repair-Desk** [comment]
#349

**Comment by Uzair-RepairDesk** [comment]
We have concatenated the Manufacturer and Device with Problem on Manage Customers page under task field.
@bharaaus 
Please review at your end
