### ISSUE TITLE
Can we Bring any New Idea to manage the color of products:

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#376]
One Item has so many colors. It's a headache to add new item every time. One item has so many different product codes.
Have a look at the picture.  
Each case have so many colors. and there are so so soooo many models . Just imagine, when inventrory is growing, how hard it is to manage.

PLEAS NOTE : SERIALIZING EACH ITEM IS NOT A SOLUTION FOR THIS. 
I have tried to use it, but its making things more complicated.
![ice_screenshot_20180720-194731](https://user-images.githubusercontent.com/34261339/42996744-c9a5299e-8c57-11e8-8092-19ef153ba47f.png)

**Comment by Uzair-RepairDesk** [comment]
**Hello @bharaaus** 

I really appreciate that you took the time to share your idea.

Certainly, we suggest a serialized inventory feature for this but if you are not using it, can you suggest your idea to manage the color of products so we can check the feasibility and add value to your suggested idea. 
With a small team and a big roadmap, we have to pick new features (Including your ideas 😃 ) based on the value they’ll add to the most possible users. At the moment, we won’t be able to make this one work during 3the rd Quarter. 

With that said, you can share your idea and we can consider it in our coming quarter. 

 And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

 **Regards,
Uzair from RepairDesk**

**Comment by bharaaus** [comment]
You guys are the best in developing new ideas. You would probably know better than me.
and way, what  i think is The Best possible way is by doing color matrix which we use on websites.

**Comment by Uzair-RepairDesk** [comment]
Hey @BharatPRC 
We are introducing the "Items Variant" functionality in RepairDesk2.0 that will allow you to create variants for each item like "Color" without creating serials. 
Please let me know if you would like to have access to 2.0 to beta test it? I will be happy to give you a walk-through as well. 

Regards,
Uzair
