### ISSUE TITLE
Refunds for Partial Paid Invoices

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#377]
Scenario: customer paid $60 for an item of $160, and they come back asks for $60 refund. The system does not show up the refund button for that invoice unless it has been paid in full.

**Comment by fahadimran303** [comment]
Another customer has 2 Store Locations has came up with the same request:
https://app.intercom.io/a/apps/mq09yl4f/inbox/inbox/search/conversations/21866246855?q=Anthony

For now we have told him a work around however any idea when we can implement that.

Thanks,

**Comment by Uzair-RepairDesk** [comment]
We have added an option to refund the invoices that are partially paid.
