### ISSUE TITLE
Search Filter - Condition

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#378]
Under the 'Condition' tab in an inventory item we have used a few different labels.

New | Used | Discontinued | Order In

New = New and we regularily stock this item.
Used = Simply applies to Refurbished Devices.
Discontinued = Can no longer source this item, once Quantity is '0' we delete.
Order In = We don't stock this and only order it in at customer request

Is there anyway to filter Mobile, Accessories and parts using this field?

I want to run a report for all products that are 'Discontinued' status so i can mark down the products and clear them out as we can no longer get them.
![image](https://user-images.githubusercontent.com/39751801/43122366-55569362-8f53-11e8-9215-3fa4668249ff.png)

**Comment by benjamingartner** [comment]
If not already available, i think this should be a simple change yes?

**Comment by Uzair-RepairDesk** [comment]
Hey @benjamingartner 
We added a feature to search for items from a specific condition. You can find "Condition" search filter under "Manage Accessories & Parts". Check screenshot attached.
Please review at your end. 
![condition search](https://user-images.githubusercontent.com/22955861/45734040-624a7680-bbfc-11e8-8fc8-f772d14644c8.png)
