### ISSUE TITLE
Supplier/Vendor - SKU 

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#379]
We want to have the same SKU for the same vendor on two seperate products.

Currently it says that SKU already exists.

**Comment by bharaaus** [comment]
What's the Scenario?

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner ,

I hope you are doing well. Can you check in Settings> Module Configuration> Inventory> Make uniqueness across SKU is unchecked ? 
If not, try this and I hope it will work for you. I am attaching screenshot for help. 
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
![432](https://user-images.githubusercontent.com/39614480/43242128-87e5661c-90b8-11e8-87d5-3a64d1452044.png)

Usman Ali

**Comment by usmanalikhan93** [comment]
Hey @benjamingartner ,

It looks like there's a bug that just popped up. I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hey @benjamingartner, 

I hope you are doing well. Sorry for the inconvenience. I have checked with developer and he said you can not add same SKU for Vendor/supplier. 

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
 
Thanks
Usman Ali.
