### ISSUE TITLE
Purchase Order Default View

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#380]
Hi Team,
Is it possible that when we open PO, it only shows OPENED po only.
and All CLOSED one are hidden by default.

OPENED = Unpaid/Partially Paid, Wating / Pening.
CLODED = PAID and RECEIVED.

Reason for this is we have so many POs . And sometimes it goes too far down and it skip from our mind to complete it.

I know Search Filter option is there, but there are so many options, its hard to click on each one to check status.
Im talking about HIDE/UNHIDE - CLOSED AND OPENED ONE same option we have in TICKET section.

Please let me know your thoughts on this.

Thanks.

**Comment by Repair-Desk** [comment]
**Hello @bharaaus,**

Thanks for sharing the feedback. Sounds like a good feature suggestion. We can add a trigger under **module configuration >> purchase orde****r** that by default it display open purchase orders.

We will try to get this released hopefully within 2 weeks.

If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

**Usman Butt**

**Comment by Uzair-RepairDesk** [comment]
Hi @bharaaus 

I am pleased to inform you that we have added a trigger on your request under **Store Settings > Module Configurations > Purchase Order > Hide Paid or Accepted Order**
Once you enable the trigger, it will automatically hide the purchase orders that have been received and paid. 

Please review at your end and verify. Thanks. 
![purchaseorder config](https://user-images.githubusercontent.com/22955861/44013100-f792a3ee-9edc-11e8-8e8b-4325c4907949.png)

**Comment by bharaaus** [comment]
![po](https://user-images.githubusercontent.com/34261339/44127340-3c40edf8-a080-11e8-911e-0f949a51fd78.png)

I was hoping something like this.

**Comment by bharaaus** [comment]
I hide this opiton,
but it still shows some of the closed ones at the bottom.

please see picture
![po 2](https://user-images.githubusercontent.com/34261339/44127398-7c35a6d8-a080-11e8-9713-fda2966d4d61.png)

**Comment by bharaaus** [comment]
Sorry to say, but effort you have put on adding this option is has no outcome.
Because this option is useless.
Adding this option has disabled search filter completly.
going back and forth to change this option from setting is not a solution.

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus , Hope you are well. You asked to hide closed purchase orders on the default view and we added a trigger for the same specifically on your request. If you want to hide default purchase orders on default view, you can simply enable the trigger and system doesn't display closed PO's. 
If you want to view closed/paid PO's later on, you can simply apply the search filter. Please check screenshot attached.

Regarding "Hide Closed Ticket" check (you posted now) on ticket search filter doesn't hide closed PO's on default view, it just hides the closed tickets if you don't want to view closed tickets in search results.

**Comment by bharaaus** [comment]
"Regarding "Hide Closed Ticket" check (you posted now) on ticket search filter doesn't hide closed PO's on default view, it just hides the closed tickets if you don't want to view closed tickets in search results.
"

I was hoping similar to that.
Sorry it was my mistake, I couldn't explain it properly in the beginning.

Anyways,
Still In future ( If Possible) you can add this option in PO. That would be a great help.

Thanks So Much.
