### ISSUE TITLE
Du amount error

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#382]
I do not understand why the yellow message prevents me from doing the operation. The bill has an overpaid amount of $ 17.24. I must therefore make a refund of $ 17.24 to the customer. I can not refund a bill paid too much alos, I apply a new payment in the invoice of -17.24 $. This operation has always worked but not anymore. It's not fair in this bill that this problem is present. see attachement.
<img width="923" alt="du amount" src="https://user-images.githubusercontent.com/40500094/43232678-375db69a-9040-11e8-8ffa-46aeb576272c.png">

--
french: 
Je ne comprend pas pourquoi le message jaune m'empêche de faire l'opération. La facture a un montant overpaid de 17.24$. Je dois donc faire un remboursement de 17.24$ au client. Je ne peux pas rembourser une facture trop payé alos, j'applique un nouveau paiement dans la facture de -17.24$. Cette opération a toujours fonctionné mais, plus maintenant. Ce n'est pas juste dans cette facture que ce problème est présent._

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS  👋 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by JessicaSOS** [comment]
Ok tnx 

 

-- 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579,204> 418-999-1579 |  <tel:18559991579,204> 1-855-999-1579 | Extension : 204
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375 bvd Guillaume Couture, Lévis, G6V 4Z3
2750 1re Ave, Ville de Québec, QC G1L 3N8
977 route de l'Église, Ste-Foy, G1V 3V3
835 rue St-Joseph Est, St-Roch, G1K 3C8

 <http://www.facebook.com/groups/173894875954415/#!/pages/SOS-Phone/169687599716789> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 26 juillet 2018 01:40
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Du amount error (#382)

 

Hey @JessicaSOS <https://github.com/JessicaSOS>  👋
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛.

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS  ,

Just an update we have fixed reported issue and it’s available for beta testing on sandbox server. We are hoping to go live with this either today or tomorrow hopefully.

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS ,

Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
Is fixed :)
