### ISSUE TITLE
Purchase Order/GRN Descriptions 

### ISSUE THREAD

**Issue by Cumbr1at3ch** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#384]
Gents 
Despite inventory showing a description, When a GRN or purchase order is printed off. This description isnt replicated. The box is blank. Reported this a week or so ago. Advised this was sorted but its still happening 
![image](https://user-images.githubusercontent.com/40138325/43248973-5b918e6c-90b1-11e8-9a7c-bad6d7958d78.png)

**Comment by usmanalikhan93** [comment]
Hey @Cumbr1at3ch  
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @Cumbr1at3ch ,

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.
