### ISSUE TITLE
Due date in ticket converting from lead

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#385]
When converting a lead into a ticket, the due date of the ticket should be the end time of the appointment entered in the lead and not the start time of the appointment. Can you make the change?

_--
french:
Lorsque l'on convertie un lead en billet, la date dû du billet devrait être l'heure de fin du rendez-vous inscrit dans le lead et non pas l'heure du début du rendez-vous. Pouvez-vous faire la modification?_

**Comment by JessicaSOS** [comment]
Tnx, let me know when is fixed please.

 

-- 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579,204> 418-999-1579 |  <tel:18559991579,204> 1-855-999-1579 | Extension : 204
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375 bvd Guillaume Couture, Lévis, G6V 4Z3
2750 1re Ave, Ville de Québec, QC G1L 3N8
977 route de l'Église, Ste-Foy, G1V 3V3
835 rue St-Joseph Est, St-Roch, G1K 3C8

 <http://www.facebook.com/groups/173894875954415/#!/pages/SOS-Phone/169687599716789> 

 

 

De : Muhammad Uzair Shah <notifications@github.com> 
Envoyé : 27 juillet 2018 02:27
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Due date in ticket converting from lead (#385)

 

Hey @JessicaSOS <https://github.com/JessicaSOS> 
Thank you for your feedback. I am 100% agree with your above give suggestion that the end time of the appointment should be "Due Date" of the ticket when a lead is converted into a repair ticket. I am adding it to the roadmap.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
We have made improvements. When you convert a lead into a ticket, the due date of the ticket is the end time of the appointment now.
Please check at your end and verify. Thanks

**Comment by JessicaSOS** [comment]
Fixed !
