### ISSUE TITLE
Need Inventory Filter by Cost Price

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#388]
![filter by cost price](https://user-images.githubusercontent.com/34261339/43372585-aa29f370-93e5-11e8-99ba-6fbaf9ea3fa5.png)

See the attached picture. It is good we can click on IN STOCK and it shows what items we have ZERO in stock and so on.

We need same thing on COST Price as well.

This would be helpful to check if any item doesn't have cost price .
As we know, PO doesn't sync cost prices to inventory, so every new item we create there and save, we have to manually update cost in inventory tab.
Sometimes we forget about it, so now sorting this out there is no option available.

**Comment by bharaaus** [comment]
Today i noticed , we can filter inventory by cost.
but 
In Stock menu has disabled.
which means we can not change the item qty from this window. we have to click on update product to change qty.

**Comment by Uzair-RepairDesk** [comment]
We added this before on your request and issue of "In Stock" is also fixed
