### ISSUE TITLE
PrintNode missing printing sometime

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#390]
It happens at lest 4-5 time a day. 
We book a ticket or make invoice , it shows the popup saying printing command is sent.
But nothing prints out. 
Then we have to use manual printing. 
But next transaction may work without any problem. 

So it missed sometimes.not all the time. 

I noticed some people have reported this issue on Facebook too. 
Anything can be done about it ?

**Comment by usmanalikhan93** [comment]
Hey @bharaaus 👋 

Thank you for bringing this to our attention! . 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Usman Ali

**Comment by usmanalikhan93** [comment]
Hey @bharaaus 

Can you login into your PrintNode account and check printing activity there?  And I appreciate if you send a screenshot of that or you can share a video with us.  

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again. 
Usman Ali here - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
