### ISSUE TITLE
Need more informations in reports

### ISSUE THREAD

**Issue by phyber51** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#391]
For my accounting, I need more informations for reports.
All reports concern invoices paid, but i would like informations for all invoices generates, paid and unpaid. 
The function (export invoices for excel ) , is great but "items category" is not in the export.

Thanks

**Comment by Repair-Desk** [comment]
Would you like a new column added “item category” and have it say Repair, Networ Unlock, Accessories etc?

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
