### ISSUE TITLE
Upgrade to the Schedule an appointment widget

### ISSUE THREAD

**Issue by markster126** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#392]
On my site when you click (https://www.a1cell4u.com/Scheduleappointment.html) on the pricing and you get to the "select Manufacturer screen"  it would be nice to be able to have HTML option here for some PNG.(whatever ext) photo's

**Comment by markster126** [comment]
https://www.a1cell4u.com/Scheduleappointment.html

**Comment by Uzair-RepairDesk** [comment]
Hi @markster126 
Our widget is script based. We encourage our customers to use the banners/images by using CMS of their own website. Please check following examples to take inspiration to setup the Appointment Calendar Widget. 
https://www.techrevive.com.au/buy-sell-trade
http://phonecarerepairs.com.au/Repair.html
https://www.1stopfix.com/repair.html
