### ISSUE TITLE
WooCommerce Integration - Product Syncs

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#393]
So i use a category for 'Mobile Phone Cases and Covers', In this category LifeProof Fre model cases, OtterBox Defender cases, and OtterBox Symmetry Cases. 

I have been through and unticked the sync with WooCommerce on the LifeProof Fre cases that i dont want to sync.

This option is great to have but whenever i make the mistake of clicking 'Manual Sync with WooCommerce' these "unticked" products seem to sync anyway. 

This is very annoying because i have then got to go and delete them from my site otherwise they look horrible. 

Hope this is explained correctly. I don't want to keep trying to replicate it because it is a pain in my backside having to delete the ones that synced that i don't want.

**Comment by Uzair-RepairDesk** [comment]
@benjamingartner 
Can you help us to replicate this issue? Perhaps you can share relevant screenshots. It will be appreciated

@usmanalikhan93 
We need to run a QA cycle to find the issue.

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

I believe this issue has been fixed in recent update. Can you give it another try?

Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

Since I haven't heard back from you, Please find developer's feedback:- 

"there must be flow issue he hit on sync button without hitting save button after mapping categories. can you ask him if those items are still syncing which are unchecked?"
If yes, then please share screenshot of trigger tab of that specific product.

**Comment by usmanalikhan93** [comment]
Hi again @benjamingartner   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Usman Ali
