### ISSUE TITLE
To able to Send the ticket via email on iPad POS app after creating ticket

### ISSUE THREAD

**Issue by boriszaw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#394]
Would like to request for a function where i will be able to send the Ticket via email after Creating ticket on iPad POS app.

**Comment by Repair-Desk** [comment]
Hi Boris,

Happy to help with this.

I believe when you create an email through iPad POS register it automatically sends out “repair in progress” email to the customer.

Can you perhaps trying creating a ticket as a customer and see if you receive an email or not? 

Usman

**Comment by boriszaw** [comment]
Hi Usman, 

That status email is sent out if create ticket on iPad POS. Thanks. 

Best Regards,

Boris (Thiha Zaw)

**Comment by Uzair-RepairDesk** [comment]
We have this option available to send an email after creating a ticket.
