### ISSUE TITLE
Transaction Log now showing all item

### ISSUE THREAD

**Issue by wirelessrepairzone** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#395]
For the last few weeks the Transaction Log is no longer showing all item, it looks to be limited to just my the current users items not all users, when i select an employees name i get noting listed, when i leave it blank i just get my own

**Comment by usmanalikhan93** [comment]
Hey @wirelessrepairzone , 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Thanks

**Comment by usmanalikhan93** [comment]
Hi @wirelessrepairzone 

I hope you are doing well. We have release a fix for Transaction log, can you check on your end and let us know ? 
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.

Thanks!
Usman Ali

**Comment by wirelessrepairzone** [comment]
still not working correctly with the filter   What i use this for is to see
what older invoices have been paid. For example this morning i know the 1st
invoice from yesterday is 8088 for the Davison store so I would open the
transaction lot select yesterdays date and look for any invoice number
older then 8088 to see if anything was picked up and paid for on an older
invoice.

in the file no filter this is what i get with nothing in the search.
granted before something i would not even see this so its is better

in the file "filter 1" you will see when i select the date from yesterday
and the store davison i get only my own transactions

in the file "Filter 2" i know alex worked most of the day in davison so i
selected her name and added an end date just to be sure

Mike

**Comment by usmanalikhan93** [comment]
Hi @wirelessrepairzone 

We have close the shift, now I hope your issue will be resolved. Can you verify on your end? and do let us know if you have any question. 

Usman Ali.

**Comment by wirelessrepairzone** [comment]
looks to be working now thank you
