### ISSUE TITLE
TONS OF BUGS

### ISSUE THREAD

**Issue by pcrevamp** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#396]
1 - Bookings made on the web interface going through to my Manage Leads, but we're not getting an email to show a booking has been made. This is not on all bookings made, just random ones

2 - some bookings (not very important) have been made at the same time of the day. Causes extra workload but again, not important but still a pain.

3 - The Latest bug is very important. Bug 1 is a pain in the arse alone, but NOW when I go onto Repair Desk Manage Leads, there is NO DUE DATES in any of my leads. If I arrange the lead ID it helps me to know a bit more about the reair being carried out - but when I click into the Lead it does not show any information about the repair or service being carried out. If we're not getting emails with information on the repair, and now we can't see this information on the website, what the heck am I suppose to do?

All of these bugs have been reported several times and I've been told that the issues are at my end (my email account) however this is NOT the case. I think this issue is with your email server not sending out repairs. How come 4/5 email booking confirmations come through OK? This needs to be looked into ASAP as I won't continue for much longer with your services. When I first started using your systems around 3-4 months ago it was fantastic. I had no issues at all. These last 3 weeks have been shocking. There are 100% bugs with your system at the moment.

**Comment by pcrevamp** [comment]
I have gone onto my web mail (not outlook) to make sure all filters and rules have been cleared. Issue is still there.

You can even see on the bookings that leads are missing. The leads go up in numbers 
# L-600
# L-601
# L-602

Then all of a sudden you will see # L-603 missing

If you go to repair desk and check the leads, it will show on there.

**Comment by usmanalikhan93** [comment]
Hey @pcrevamp 

I hope you are well. We are working on this issue. And we hope it will be fixed soon. Your patience would be highly appreciated.

Thanks!
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @pcrevamp 

A lot of our customers recently requested that they wanted an ability to track if an email has been sent, delivered or opened by a customer which we rolled out recently. Now you can check whether the email is sent or not.
