### ISSUE TITLE
New Lead created in main store only

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#397]
Hello,
it looks like the new interface of the leads. However, when we are connected to a shop (example Lévis store), the lead is automatically created in Limoilou (the main store).  It is not created in the shop in which we are connected.
Have a good day

**Comment by JessicaSOS** [comment]
fixed

**Comment by Repair-Desk** [comment]
Hello Jessica,

We sincerely apologise for the inconvenience. I can certainly see you are using global iFrame code here: https://sosphone.ca/reparation-de-cellulaire/prendre-rendez-vous/ that should create a lead / appointment on respective store.

We will create a test appointment to check and will revert back with an update

Usman

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS ,

I have checked your concern and created a lead through Appointment Calendar and selected a Levis store. Lead comes in Levis store as you can see the screenshot 469.png. No lead comes in main store (Limoilou), see screenshot 470.png. 

![469](https://user-images.githubusercontent.com/39614480/43762888-9fb6ecaa-9a42-11e8-8809-c0ecf830711b.png)
![470](https://user-images.githubusercontent.com/39614480/43762889-9fe2c2e4-9a42-11e8-8824-d9d4d4e672bd.png)

**Comment by JessicaSOS** [comment]
Indeed, it seems to work today.

 

-- 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579,204> 418-999-1579 |  <tel:18559991579,204> 1-855-999-1579 | Extension : 204
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375 bvd Guillaume Couture, Lévis, G6V 4Z3
2750 1re Ave, Ville de Québec, QC G1L 3N8
977 route de l'Église, Ste-Foy, G1V 3V3
835 rue St-Joseph Est, St-Roch, G1K 3C8

 <http://www.facebook.com/groups/173894875954415/#!/pages/SOS-Phone/169687599716789> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 7 août 2018 04:06
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] New Lead created in main store only (#397)

 

Hi @JessicaSOS <https://github.com/JessicaSOS>  ,

I have checked your concern and created a lead through Appointment Calendar and selected a Levis store. Lead comes in Levis store as you can see the screenshot 469.png. No lead comes in main store (Limoilou), see screenshot 470.png.

 <https://user-images.githubusercontent.com/39614480/43762888-9fb6ecaa-9a42-11e8-8809-c0ecf830711b.png> 
 <https://user-images.githubusercontent.com/39614480/43762889-9fe2c2e4-9a42-11e8-8824-d9d4d4e672bd.png>

**Comment by JessicaSOS** [comment]
Hello,
it's still not settled. The problem just does not seem to be all the time. This morning, I just created a new lead by being connected to Sainte-Foy and it is created in Limoilou.

_--
french:
Bonjour,
ce n'est toujours pas réglé. Le problème semble juste ne pas être a tous les coups. Ce matin justement, je viens de créer un nouveau lead en étant connecté à Sainte-Foy et il c'est créé à Limoilou._

**Comment by usmanalikhan93** [comment]
@JessicaSOS 

Let us look again in it and we will create a test appointment to check and will revert back with an update. 

Thanks
Usman Ali

**Comment by JessicaSOS** [comment]
No problem you can test it !

 

-- 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579,204> 418-999-1579 |  <tel:18559991579,204> 1-855-999-1579 | Extension : 204
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375 bvd Guillaume Couture, Lévis, G6V 4Z3
2750 1re Ave, Ville de Québec, QC G1L 3N8
977 route de l'Église, Ste-Foy, G1V 3V3
835 rue St-Joseph Est, St-Roch, G1K 3C8

 <http://www.facebook.com/groups/173894875954415/#!/pages/SOS-Phone/169687599716789> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 9 août 2018 02:27
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] New Lead created in main store only (#397)

 

@JessicaSOS <https://github.com/JessicaSOS> 

Let us look again in it and we will create a test appointment to check and will revert back with an update.

Thanks
Usman Ali

**Comment by JessicaSOS** [comment]
As I said, it's not all lead creation. Look at the name of Limoilou's leads on the attachment. They were not transferred ... they were created to limoilou ...
<img width="949" alt="lead" src="https://user-images.githubusercontent.com/40500094/44790848-43f9d980-ab6e-11e8-9415-d3c7b1e07500.png">

**Comment by Repair-Desk** [comment]
@usmanalikhan93 An update would be great :)

**Comment by usmanalikhan93** [comment]
Let me check this again.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked your concern but on my end, it seems everything is working fine. Can you check again and let us know if you are still facing this issue or not ? 

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
We are still faced with this problem. It occurs mainly when a Lead is assigned to an employee. He then transfers to another branch. These are Leads that are created via "manage lead" and not via our website.

**Comment by usmanalikhan93** [comment]
@JessicaSOS 

Ok thanks. I will check this now with this scenario. And will update you accordingly.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
fixed
