### ISSUE TITLE
Missing invoice by customer name

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#398]
Hello,
We are no longer able to know the number of tickets / bills a customer has had, without going to see each branch. See client example: "Renald Laperriere" and 2 screenshots.
<img width="949" alt="renal laperriere saint-roch store" src="https://user-images.githubusercontent.com/40500094/43734648-60606db8-9986-11e8-83b2-7bb56c899303.png">
<img width="944" alt="renald laperriere limoilou store" src="https://user-images.githubusercontent.com/40500094/43734649-606f4374-9986-11e8-9604-4b7a0cd7826a.png">

**Comment by Repair-Desk** [comment]
Hello Jessica,

Thanks for sharing this with us. Let me discuss this with Uzair and revert back.

I believe customer invoices are displayed if they are created and viewed from the same store but I still need to verify this.

Will revert back on this thread shortly.

Usman

**Comment by JessicaSOS** [comment]
This was not the case 2 days ago. We could not see all the details but we could still see the ticket / invoice if there were any.

 

-- 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579,204> 418-999-1579 |  <tel:18559991579,204> 1-855-999-1579 | Extension : 204
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375 bvd Guillaume Couture, Lévis, G6V 4Z3
2750 1re Ave, Ville de Québec, QC G1L 3N8
977 route de l'Église, Ste-Foy, G1V 3V3
835 rue St-Joseph Est, St-Roch, G1K 3C8

 <http://www.facebook.com/groups/173894875954415/#!/pages/SOS-Phone/169687599716789> 

 

 

De : Repair-Desk <notifications@github.com> 
Envoyé : 6 août 2018 23:08
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Author <author@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Missing invoice by customer name (#398)

 

Hello Jessica,

Thanks for sharing this with us. Let me discuss this with Uzair and revert back.

I believe customer invoices are displayed if they are created and viewed from the same store but I still need to verify this.

Will revert back on this thread shortly.

Usman

**Comment by usmanalikhan93** [comment]
@JessicaSOS 

Let me check and I will circle back to you with more information. 

Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS  

I hope you are well. @JessicaSOS it shows store wise.

**Comment by JessicaSOS** [comment]
Not fixed, Can you put it back as before? It is not settled yet.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS  

I have noted your concern. Let me discuss this with my product team. Then I will circle back to you. 

Usman Ali.

**Comment by JessicaSOS** [comment]
We are no longer able to view paid or unpaid invoices in the client interface, manage client. We are able to view invoices made at our branch only. Before it was not like that and in the tickets it's not like that. Can you put it back as before? Since early August we expect that has recovered.

**Comment by JessicaSOS** [comment]
Still not corrected and it's a problem

**Comment by Repair-Desk** [comment]
@JessicaSOS Sorry for the delay. We got caught up with work and didn't get a chance to update this thread.

Our team is scheduled to work on this improvement during next week and more details on upcoming changes can be found here: https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/567

**Comment by JessicaSOS** [comment]
Good, let me know when is live please.

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Repair-Desk <notifications@github.com> 
Envoyé : 18 janvier 2019 14:19
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Missing invoice by customer name (#398)

 

@JessicaSOS <https://github.com/JessicaSOS>  Sorry for the delay. We got caught up with work and didn't get a chance to update this thread.

Our team is scheduled to work on this improvement during next week and more details on upcoming changes can be found here: #567 <https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/567>

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. This module is now live. You can test at your end and do let me know if you have any question.

Thanks!
Usman Ali.

**Comment by JessicaSOS** [comment]
Perfect and fixed :)
