### ISSUE TITLE
Problem with transaction woo-commerce

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#399]
Hello
<img width="939" alt="woocomerce sku item xxx5234" src="https://user-images.githubusercontent.com/40500094/43787001-fa4d3440-9a37-11e8-836b-4074f104a3fc.png">
,

The device was sold online via woo commerce. We do not create any items directly in woo commerce. We always go through repairdesk. This is what I mention in my previous email. "I can not find the item with sku xxx5234." Yet, we see on the transaction woo commerce that it is this item that has been sold.
In summary:
	Could not find the client in repairdesk (as of today it's fixed)
	Can not find bill in repaidesk (still not fixed)
	Can not find item sold (still not fixed)

--
French:
L'appareil a été vendu en ligne via woo commerce. Nous ne créons aucun item directement dans woo commerce. Nous passons toujours par repairdesk. C'est ce que je mentionne dans mon précédent courriel. "Je suis incapable de trouver l'item avec le sku xxx5234." Pourtant, nous voyons bien sur la transaction woo commerce que c'est cet item qui a été vendu.
en résumé: 
	Impossible de trouver la cliente dans repairdesk (en date d'aujourd'hui c'est réglé)
	Impossible de trouver la facture dans repaidesk (toujours pas réglé)
	Impossible de trouver l'item vendu (toujours pas réglé)

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.
