### ISSUE TITLE
Problem with receiving email

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#401]
Hello,
We had some problem last week with emails sent from ticket that was not delivered to the recipient. We thought it was a problem with the email address of one person. However, this problem has reappeared this week with other employees.

Here is the description:
- the problem is intermittent.
- This is an email sent from a ticket from one employee to another employee.
- The problem is that the email does not go to the recipient.

You can see that David (fournier@sosphone.ca) has sent an email to Stacey (stacey@sosphone.ca) via ticket # L-7973 today August 8 at 9:28 am.
We have received this email. But since it is an intermittent problem, a second email has not been delivered. David (fournier@sosphone.ca) sent an e-mail to Stacey (stacey@sosphone.ca) via ticket # L-8361 today, August 8th at 9:33 am. The latter was not received.

We checked on the employee's computer, in his phone. I contacted the person who manages our emails and they tell me that there is no error message, but that the message is not even on the server. It's as if he never existed.

You will understand that this problem makes us lose follow-ups, which affects our customer service. I tried to explain the problem in as much detail as possible to make sure of your understanding. Thank you for correcting it quickly.
<img width="939" alt="email sending" src="https://user-images.githubusercontent.com/40500094/43848115-42fb76f2-9b00-11e8-9d7d-1547f6739c91.png">
<img width="940" alt="ticket received l-7973" src="https://user-images.githubusercontent.com/40500094/43848128-48f0d50c-9b00-11e8-9435-90a41a3e4442.png">
<img width="945" alt="mail server" src="https://user-images.githubusercontent.com/40500094/43848130-4b1e0854-9b00-11e8-988c-a5937d3c4335.png">

--
_french:
Bonjour,
Nous avons eu quelque problème la semaine dernière avec des courriels envoyés à partir de billet qui ne c'était pas rendu au destinataire. Nous avions pensé que c'était un problème avec l'adresse courriel d'une seule personne. Cepedant, ce problème est réapparu cette semaine avec d'autres employés. 

Voici la description:
-- le problème est intermittent. 
-- Il s'agit d'un courriel envoyé à partir d'un billet d'un employé vers un autre employé (aucune employé particulièrement). 
-- Le problème est que le courriel de se rend pas au destinataire.
-- Aucun mesage d'erreur pour l'expéditeur, le destinataire ou lors de l'envois du message.

Voir pièce jointe...

Vous pouvez voir que David (fournier@sosphone.ca) a envoyé un courriel à Stacey (stacey@sosphone.ca) via le billet #L-7973 aujourd'hui le 8 aout à 9h28 am. Nous avons bien reçu ce courriel. 

Mais, puisque c'est un problème intermittent, un second courriel n'a pas été livré. David (fournier@sosphone.ca) a envoyé un courriel à Stacey (stacey@sosphone.ca) via le billet #L-8361 aujourd'hui le 8 aout à 9h33 am. Ce dernier n'a pas été reçu.

Nous avons vérifier sur l'ordinateur de l'employé, dans son téléphone. J'ai communiqué avec la personne qui gère nos courriels et il m'a dit qu'il n’y a aucun message d'erreur, mais que le message n'est même pas sur le serveur. C'est comme s'il n'avait jamais existé.

Vous comprendrez que ce problème nous fait perdre des suivis, ce qui nuit à notre service à la clientèle. J'ai tenté de vous expliquer le problème le plus en détail possible pour m’assurer de votre compréhension. Merci de le corriger rapidement._

**Comment by JessicaSOS** [comment]
tnx

 

-- 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579,204> 418-999-1579 |  <tel:18559991579,204> 1-855-999-1579 | Extension : 204
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375 bvd Guillaume Couture, Lévis, G6V 4Z3
2750 1re Ave, Ville de Québec, QC G1L 3N8
977 route de l'Église, Ste-Foy, G1V 3V3
835 rue St-Joseph Est, St-Roch, G1K 3C8

 <http://www.facebook.com/groups/173894875954415/#!/pages/SOS-Phone/169687599716789> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 9 août 2018 02:20
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Problem with receiving email (#401)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

Sure thing! Let me take a look and I'll get back to you as soon as I have more information!

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

A lot of our customers recently requested that they wanted an ability to track if an email has been sent, delivered or opened by a customer which we rolled out recently. Now you can check whether the email is sent or not. 

See screenshot for reference 
![568](https://user-images.githubusercontent.com/39614480/45204143-c766a980-b297-11e8-91b8-7a711c8a89b0.png)

**Comment by JessicaSOS** [comment]
yes, but we had a problem with emails sent between employees. We unfortunately can not see this detals with the mails between employees. Only mail with customer.

**Comment by Repair-Desk** [comment]
Hey @JessicaSOS 

Sure thing! Let me take a look to see if we're unable to view tracking option against emails that are sent b/w emails using private comments and I'll circle back to you.

Regards,
**Usman Butt**

**Comment by Repair-Desk** [comment]
Hey @Jessica

I have just heard back from the development team that they have already added the ability to track if an email to an employee was sent or not.

I would recommend to give it another whirl and let us know if this works for you or not.

Thanks,
Usman Butt

**Comment by usmanalikhan93** [comment]
@JessicaSOS 

Let me check again.

**Comment by usmanalikhan93** [comment]
@JessicaSOS 

Sorry for the inconvenience. I think something went wrong. It will be fixed tomorrow on urgent basis. I will update you once it will be live.

**Comment by usmanalikhan93** [comment]
@JessicaSOS 

See screenshot for reference. I am sending email Employee to Employee. 
![email](https://user-images.githubusercontent.com/39614480/45692263-c7a65500-bb73-11e8-8037-b4099abe3ecc.png)

Can you tell me are you selecting email in via box?

**Comment by JessicaSOS** [comment]
actually it's fixed. Sorry for the confusuion. I did not know that we had to refresh on the page to visualize.
Have a good day !
