### ISSUE TITLE
Multiple Lead generations 

### ISSUE THREAD

**Issue by jaytronixx** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#402]
When customers are requesting a quote on the sell a device widget it always create multiple up to 6 leads sometimes. We have confirmed this happening for all users and not isolated. 
<img width="1431" alt="screen shot 2018-08-09 at 1 38 34 pm" src="https://user-images.githubusercontent.com/28720537/43915860-fb340eb2-9bd9-11e8-8b0c-d2fbe9825c6e.png">

**Comment by usmanalikhan93** [comment]
Hi @jaytronixx 

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @jaytronixx 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks :)
Usman Ali
