### ISSUE TITLE
iOS Crashing

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#404]
Everytime i load the iOS app it loads the dashboard and then crashes closing it.

**Comment by usmanalikhan93** [comment]
Hey @benjamingartner , 

Usman here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
@benjamingartner  

crashing or working fine ?

**Comment by benjamingartner** [comment]
Working fine now
