### ISSUE TITLE
Admin history missing infor

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#405]
Hey team,

There are big issues with admin history does not show enough information as before. Please see attached screenshot, it suppose to show another record explain why the stock increase or decrease value from transfer or purchase order. Before it shows, but now no more.

**Comment by quangc** [comment]
![screen shot 2018-08-16 at 11 11 45 am](https://user-images.githubusercontent.com/22993605/44181491-668afc00-a145-11e8-87f4-7814021d2c15.png)

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you review it at your end?

**Comment by quangc** [comment]
Any updates please?

**Comment by usmanalikhan93** [comment]
Hey @quangc 

I hope you are doing well. I am reviewing this, if I'm getting the same issue as you, I'll get back to you with information! 

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hey @quangc 

I have checked you concern but it shows every detail in admin history. Please see Screenshot 
![533](https://user-images.githubusercontent.com/39614480/44323254-80d91880-a46a-11e8-92c5-e509d3843563.png)

**Comment by quangc** [comment]
It does not show in my attached screenshot

**Comment by quangc** [comment]
There are lots of missing info in many places, it has been happened for a while. I can try to relocate the exact items so you can investigate.

**Comment by usmanalikhan93** [comment]
Sure @quangc.

**Comment by quangc** [comment]
![screen shot 2018-08-20 at 4 59 52 pm](https://user-images.githubusercontent.com/22993605/44324967-b269d800-a49a-11e8-8d75-701c7b84a3db.png)
![screen shot 2018-08-20 at 4 59 59 pm](https://user-images.githubusercontent.com/22993605/44324968-b269d800-a49a-11e8-8e0a-df79f1761a72.png)
![screen shot 2018-08-20 at 5 01 06 pm](https://user-images.githubusercontent.com/22993605/44324969-b3026e80-a49a-11e8-930b-74c89d367209.png)
![screen shot 2018-08-20 at 5 01 13 pm](https://user-images.githubusercontent.com/22993605/44324974-b3026e80-a49a-11e8-8940-19fe2e770937.png)
Please have a look at these 2 Transfer Order trail back in Feb this year. As you can see, there is no Admin History to show these items have increased in stock but no record of from which Transfer Order.

**Comment by usmanalikhan93** [comment]
Ok @quangc, let me review this.

**Comment by quangc** [comment]
Checking up to 20/03/2018 is still not fixed, but from 31/3/2018 is fixed. There are a time range that affected in the system, I think you can recover those trails?

**Comment by usmanalikhan93** [comment]
Let me discuss this with developer then I will revert back to you. 
@quangc

**Comment by usmanalikhan93** [comment]
Hey @quangc 

I have discussed this with developer. Kindly can you please tell us the date range from when to when we have to recover? It will be more easy for the developer. 

Usman Ali

**Comment by quangc** [comment]
Just to be safe. Recover month January, February and March please

Best Regards,
Quang Cao.
General Manager.
+ Repair Centre Frankston
+ Repair Centre Springvale
+ Repair Partners
P: 1300 89 82 99
A : Shop 6 Shannon Street Mall, Frankston, Vic, 3199.

**Comment by usmanalikhan93** [comment]
@quangc  

Developer is asking for the store name. And he said he will just provide an excel sheet, you have to search it then accordingly.

**Comment by quangc** [comment]
This is no good since your system stuffed up and we have to spend more time to reconcile it?

**Comment by usmanalikhan93** [comment]
Hi @quangc 

Can you contact our support ninja to provide him more details on this?

**Comment by usmanalikhan93** [comment]
Hi @quangc   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
