### ISSUE TITLE
Double Invoice

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#406]
Hello,
Duplicate invoices are created when we apply the payment via the POS. It's not every transaction. We are not supposed to be able to create more than one invoice for the same ticket, or an invoice with the same invoice number to the same customer.
See Attachment.
<img width="928" alt="double invoice" src="https://user-images.githubusercontent.com/40500094/44222522-c4721080-a152-11e8-8590-23269a8c8931.png">
<img width="944" alt="double invoice 2" src="https://user-images.githubusercontent.com/40500094/44222525-c76d0100-a152-11e8-96d4-6ee9ba7114ce.png">
![double invoice registrer report](https://user-images.githubusercontent.com/40500094/44222527-c936c480-a152-11e8-9264-1ac2a1ed01b1.png)

_--
French:
Bonjour,
Des doublons de factures se crée lorsque nous appliquons le paiement via le POS. Ce n'est pas à chaque transaction. Nous ne sommes pas suposé être capable de créer plus d'une facture pour un même billet, ni une facture avec le même numéro de facture au même client.
Voir pièce jointe.__

**Comment by usmanalikhan93** [comment]
@JessicaSOS 

We are already working on this issue, trying to reproduce on our end. Once we find a solution for this, I will update you. 

Thanks. 
Usman Ali.

**Comment by JessicaSOS** [comment]
Ok tnx

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 7 septembre 2018 03:09
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Double Invoice (#406)

 

@JessicaSOS <https://github.com/JessicaSOS> 

We are already working on this issue, trying to reproduce on our end. Once we find a solution for this, I will update you.

Thanks.
Usman Ali.

**Comment by JessicaSOS** [comment]
This is still not fixed, please do not close this task.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

we have your another task which is I think same as this
https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/438
That's why we have just closed one issue.
