### ISSUE TITLE
Extensions for phones number

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#408]
Extensions for phones does not work. We are able to see the word "extention" when we want to add one, but impossible to put numbers after the phone numbers. This is not very practical when it comes to a desk phone ...
<img width="935" alt="extention" src="https://user-images.githubusercontent.com/40500094/44229002-bcbb6780-a164-11e8-828c-d858923129e4.png">

_--
French:
Les extentions pour les téléphones ne fonctionne pas. Nous sommes capable de voir le mot "extention" lorsque nous souhaitons en ajouter une, mais impossible de mettre des chiffres après le numéros de téléphone. Ce n'est pas très pratique lorsqu'il s'agit d'un téléphone de bureau...
Reporter le 17 aout 2017 à Ali et le 16 aout 2018 au site github._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Just an update we have fixed reported issue and it’s available for beta testing on sandbox server. We are hoping to go live with this either tomorrow or Monday hopefully.

**Comment by JessicaSOS** [comment]
Excellent ! let me know when it’s gonna be live

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 13 septembre 2018 01:59
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Extensions for phones number (#408)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

Just an update we have fixed reported issue and it’s available for beta testing on sandbox server. We are hoping to go live with this either tomorrow or Monday hopefully.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.

**Comment by JessicaSOS** [comment]
Fixed ! 👍
