### ISSUE TITLE
Employee Commission report

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#409]
postponed on October 30, 2017,

The commissions reports should correspond, but currently, this is not the case. For the same employee: Stéphanie Cloutier, at the same branch: SOS Phone Limoilou and the same period 1 to July 31, 2018, here are the results:

Connected in my admin deposit, "Report" + "Selling by Product Name" (result 235)
<img width="924" alt="selling by product name" src="https://user-images.githubusercontent.com/40500094/44230142-533d5800-a168-11e8-8c6c-bde2727919a0.png">

Connected in my admin deposit, "Report" + "Employee Commission" (result 225)
<img width="928" alt="employee commissions" src="https://user-images.githubusercontent.com/40500094/44229964-b8447e00-a167-11e8-9210-6e0002481372.png">

Connected in the profile of the employee, (at the side of the profile picture) "My commissions" (result 225)
<img width="928" alt="my commission" src="https://user-images.githubusercontent.com/40500094/44230300-c8a92880-a168-11e8-92a3-0622f522a58f.png">

_--
french:
reporté le 30 octobre 2017, 
Les rapports de commissions devrait corresponde, mais actuellement, ce n'est pas le cas. Pour le même employé :Stéphanie Cloutier, dans la même succursale: SOS Phone Limoilou et la même période 1 au 31 juillet 2018, voici les différents résultats:

Connecté dans mon acompte admin, "Rapport" + "Vente selon le nom de produits"

Connecté dans mon acompte admin, "Rapport" + "Commission des employés"

Connecté dans le profil de l'employé, (à gache de la photo de profil) "Mes commissions"_

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

We are improving our Employee Commission Module. So all your issues related to Commission will be cover in this improvement. I will let you know once the new module is available for beta testing. 

Thanks
Usman Ali.

**Comment by JessicaSOS** [comment]
It should be around when? because I have several problems with few commissions reports...

**Comment by usmanalikhan93** [comment]
@JessicaSOS 

Most probably it will be live in two weeks. I will inform you once this module will be available on beta testing. 

Thanks. 
Usman Ali

**Comment by JessicaSOS** [comment]
Ok tnx

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 5 septembre 2018 00:46
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Employee Commission report (#409)

 

@JessicaSOS <https://github.com/JessicaSOS> 

Most probably it will be live in two weeks. I will inform you once this module will be available on beta testing.

Thanks.
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

We’ve gone live with following improvements in employee commission module: 
1: Employee commission can be set in amount or percentage
2: Commission value can be set globally, with respect to inventory item categories e.g. cases, chargers or individual items too.
3: Setup to split commission between a sales person and technician
4: Configuration to set commission based on total sales or profit earned (Trigger based). A lot of repair stores requested this 
5: Added an option to void commission in case of a refund (Trigger based)
6: Option to pay commission via payroll module.
7: Improved Commission report

If you have any question regarding this do let me know. 

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS  - I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Usman Ali.
