### ISSUE TITLE
Woocomerce integration update

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#410]
I spoke with Uzair on August 30, 2017 via email.

I asked him:
9) I imagine you have thought of a situation in the world of income that the woocommerce brings us? We have given date, monthly, or other ...

Uzair had answered me:
We have already decided to add a number of different types of products. We have added it in our roadmap for the next phase of Woo Commerce integration.

It's been 1 year so when will it be done?

--
French:
J'avais parlé avec Uzair le 30 août 2017 par courriel.

Je lui avais demandé:
9) J'imagine que vous avez pensé à une option de recherche dans les rapports pour connaître les revenus et les dépenses que le commerce électronique nous rapporte? À une date donnée, mensuelle ou autre ...

Uzair m'avais répondu:
Nous avons déjà prévu d'ajouter des filtres de recherche dans nos quelques rapports qui vous permettront de trouver des ventes en ligne avec différents critères. Nous l'avons ajouté dans notre feuille de route pour la prochaine phase d'intégration de Woo Commerce.

Cela fait 1 an alors quand se sera t'il fait?

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
I filtered the email I sent to you. The questions and answer in the email are as follows:-

9) I imagine you have thought of a search option in the reports to find out the income and expenses that the woocommerce brings us? On a given date, monthly, or other ...
**We have already planned to add search filters in our couple of reports that will allow you to find online sales with different criteria’s. We have added it in our roadmap for the next phase of Woo Commerce integration.** 
_**Check screenshot attached**_

After your specific request, we already added a filter in "Manage Invoices" where you can filter all the specific invoices from "Woo Commerce" and also apply a filter with respect to "From Date - To Date".
**_Please check screenshot attached._** 

You can review at your end and if you have any further questions, please feel free to ask. Thanks
![woocommerce filter](https://user-images.githubusercontent.com/22955861/44644096-50eebf80-a9ec-11e8-8cff-f9211c2b2366.png)
![email](https://user-images.githubusercontent.com/22955861/44644097-51875600-a9ec-11e8-87b7-a68b9a2ecc9c.png)

**Comment by JessicaSOS** [comment]
Hello,

Thank you for this follow-up. How to visualized all WooCommerce invoice between one date and another?

Have a good day

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Muhammad Uzair Shah <notifications@github.com> 
Envoyé : 27 août 2018 02:29
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Woocomerce integration update (#410)

 

Hey @JessicaSOS <https://github.com/JessicaSOS> 
I filtered the email I sent to you. The questions and answer in the email are as follows:-

9.	I imagine you have thought of a search option in the reports to find out the income and expenses that the woocommerce brings us? On a given date, monthly, or other ...
We have already planned to add search filters in our couple of reports that will allow you to find online sales with different criteria’s. We have added it in our roadmap for the next phase of Woo Commerce integration.
Check screenshot attached

After your specific request, we already added a filter in "Manage Invoices" where you can filter all the specific invoices from "Woo Commerce" and also apply a filter with respect to "From Date - To Date".
Please check screenshot attached.

You can review at your end and if you have any further questions, please feel free to ask. Thanks
 <https://user-images.githubusercontent.com/22955861/44644096-50eebf80-a9ec-11e8-8cff-f9211c2b2366.png> 
 <https://user-images.githubusercontent.com/22955861/44644097-51875600-a9ec-11e8-87b7-a68b9a2ecc9c.png>

**Comment by JessicaSOS** [comment]
fixed
