### ISSUE TITLE
Physical location of part in a ticket

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#411]
I had asked Ali if it was possible to put the location of the inventory part somewhere in the "used part" section of a ticket. I never had and this new and it date of October 30, **2017**.
<img width="928" alt="physical location" src="https://user-images.githubusercontent.com/40500094/44232836-47559400-a170-11e8-87bd-fb2e27bbf9e2.png">

<img width="945" alt="in ticket location of the part" src="https://user-images.githubusercontent.com/40500094/44232822-373db480-a170-11e8-8cc2-7d73d2c026f7.png">

_--
french:
J'avais demandé à Ali s'il était possible d'inscrire l'emplacement de la pièce d'inventaire à quelque part dans la section "pièce utilisé" dans un billet. Je n'ai jamais eu de nouvelle et cela date du 30 octobre 2017._

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
I really appreciate that you took the time to share your idea.

I can certainly see how suggested improvement would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work during the 3rd Quarter. 

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know. Thanks

**Comment by JessicaSOS** [comment]
Is it possible to do it in a second quarter? 

Going to check the location in the POS when we are in the ticket slowed down our work and since we have a very large inventory, we are often looking for it.

**Comment by JessicaSOS** [comment]
Happy Birthday! This issue was opened a year ago yesterday! We do not want this task to pass the two years ....

**Comment by JessicaSOS** [comment]
Hello,
Do you have a delivery date for this task that promises to be very useful?

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
I have scheduled it to work on it in this coming week.

**Comment by usmanalikhan93** [comment]
For internal use 
https://repairdesk.atlassian.net/browse/REP-1307

**Comment by Uzair-RepairDesk** [comment]
Hello Jessica @JessicaSOS 
I am pleased to inform you that we have made this improvement LIVE. You can view "Physical Location" of ticket item on Manage Tickets now. 
Please review at your end. Thanks

**Comment by JessicaSOS** [comment]
Perfect! :)
