### ISSUE TITLE
Average repair time job

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#413]
We are opening a new shop next Monday, August 27th, and I was wondering if it would be possible to enter the "average repair time" that is recorded in the repair issues so that it is visible in the POS. It would be much easier for the training of our new employees and more convenient for our current employees in order to give customers the right repair time. Can you make this change?
Thank you and good day
<img width="942" alt="average repair time" src="https://user-images.githubusercontent.com/40500094/44235122-7838c780-a176-11e8-8ccf-5b5c24fca44e.png">
<img width="944" alt="pos problem" src="https://user-images.githubusercontent.com/40500094/44235227-cb127f00-a176-11e8-894e-f2d757676cb3.png">

_--
french:
Nous ouvrons une nouvelle succursale lundi prochain le 27 août, et je me demandais si ce serait possible d'inscrire le "temps moyen de réparation" qui est inscrit dans les problèmes de réparation afin qu'il soit visible dans le POS. Ce serait beaucoup plus facile pour la formation de nos nouveaux employés et plus pratique pour nos employés actuel afin de donner le bon délais de réparation aux clients. Pouvez-vous effectuer cette modification?
Merci et bonne journée_

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS
I really appreciate that you took the time to share your idea.
I can certainly see how suggested improvement would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work during 3rd Quarter. We can either add it in our future roadmap. Thank you for your understanding.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
Uzair from RepairDesk

**Comment by JessicaSOS** [comment]
Hello,
I see this text answer often;). I understand that you are overwhelmed, but I am waiting for several changes, improvements and bug for several months, even, for over a year. Can we set a date, because several people ask me this question and I can not inform them.
tnx

**Comment by JessicaSOS** [comment]
Do we have development concerning this? It would be good and very convenient to have it soon!

**Comment by JessicaSOS** [comment]
Hello,
Do you have a delivery date for this task that promises to be very useful?

**Comment by JessicaSOS** [comment]
Hello,
I am still unaware of this task.
Thank you

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
Thank you for your follow up on this. 
I can see that the above-suggested improvement is useful for you. However as I mentioned above, with a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible.
Its already marked with "On-Hold to Consider", we will certainly pick it up according to the priority. 
Hope you can understand. Thanks

**Comment by JessicaSOS** [comment]
I understand perfectly. However, it's been a long time since I asked for it and it's a change that David (the owner) would like to have. It is something that would help us greatly. Are you able to give me a date?

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
I have initiated this request for the documentation. We will be able to start its development in the sprint of August. I will keep you posted on this. Thanks

**Comment by JessicaSOS** [comment]
excellent, the sooner the better!

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
This is to inform you that we have added "Average Repair Time" along with repair service on POS based on your request. Once you set time, it will be displayed on POS now. 
Please check screenshot attached.

![uzairshah - POS1](https://user-images.githubusercontent.com/22955861/63775095-161db100-c8f8-11e9-97a2-9131e50da867.png)
