### ISSUE TITLE
Payment in transaction log

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#414]
The payment methods in the transaction log are not the same in all branches. Yet, they all have the same settings.
There are currently 13 payment methods that appear while they are not in the settings (6 of created in the settings) and not in the woo trade (1 of created in woo trade). 
I would like you to look at this please.
<img width="945" alt="payment in transaction log" src="https://user-images.githubusercontent.com/40500094/44236064-c0a5b480-a179-11e8-865f-3aa343a07611.png">

_--
french:
Les modes de paiements dans le journal de transaction ne sont pas les mêmes dans toutes les succursales. Pourtant, il ont tous les même réglages. 
Il y a en se moment 13 modes de paiements qui apparaissent alors qu'ils ne sont pas dans les réglages (6 de créé dans les réglages) et pas non plus dans le woo commerce (1 de créé dans woo commerce). J'aimerais que vous regardiez cela svp._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you explain me again this issue ?

**Comment by JessicaSOS** [comment]
In the transaction log, there are 11 payment methods. (You can view them in the image named "payment in transaction log")
<img width="945" alt="payment in transaction log" src="https://user-images.githubusercontent.com/40500094/47797562-faa84080-dcfc-11e8-9b41-4be0ab8f1a1b.png">

First, the error is that the payment methods created in the payment method settings do not match those shown in the transaction log. (see pictures of the settings named "payment method")
<img width="936" alt="payment method" src="https://user-images.githubusercontent.com/40500094/47797589-03007b80-dcfd-11e8-82ba-516ae782c17f.png">


In addition, payment method settings are all the same regardless of the branch. However, in the transaction log, the payment methods displayed are different.

I hope I have enlightened you.

_--
French:
Dans le journal des transactions, il existe 11 méthodes de paiement. (Vous pouvez les visualiser dans l'image nommé "payment in transaction log")

Premièrement, l'erreur est que les modes de paiements créé dans les réglages "payment method" ne correspondent pas avec ceux affiché dans le journal de transaction. (voir photos des réglages nommé "payment method")

De plus, les réglages des méthodes de paiement sont tous les mêmes peu importe la succursale. Cependant, dans le journal de transaction, les modes de paiement affiché sont différents.

J'espère vous avoir éclairé._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Sorry for the late reply. I have checked this in your account and found that there are some payments in transaction log with these extra payment methods showed in your transaction log. That's why it is showing in this. I hope it will help.  

Usman Ali

**Comment by JessicaSOS** [comment]
I can assure you that these payments have never been used: "CHROME PAYMENT REQUEST (STRIPE)" "APPLE PAY (STRIPE)". This one had been used when you had suddenly a problem with the accents of the modes of payments: "D? BIT". This task is not fixed and you have examples in photos. Please check correctly and please re-open as I can not do it myself.

--
 Je peux vous assurer que ces paiement non jamais été utilisé: "CHROME PAYMENT REQUEST (STRIPE)" "APPLE PAY (STRIPE)" . Celui ci avait été utilisé lorsque vous aviez eu soudainement un problème avec les accents des modes de paiements: "D?BIT". Cette tâche n'est pas réglé et vous avez des exemples en photos. Merci de vérifier correctement et de la réouvrir svp car je ne peut pas le faire moi-même.

**Comment by JessicaSOS** [comment]
You never reopened this task, despite the fact that I told you that it was not resolved on January 31, 2019. I still have this same problem. Please reopen it and correct it please.
<img width="936" alt="Payment method" src="https://user-images.githubusercontent.com/40500094/80426538-ea523100-88b3-11ea-93bb-8f55d58b918f.png">
<img width="945" alt="payment in transaction log" src="https://user-images.githubusercontent.com/40500094/80426560-f938e380-88b3-11ea-8ac8-637db5a930d2.png">

--
Vous n'avez jamais réouvert cette tâche, malgré le fait que je vous avais mentionné que ce n'était pas réglé le 31 janvier 2019. J'ai toujours ce même problème. Merci de la réouvrir et de corriger svp.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. As I have already told you there are some of the payments which were used in the past, that's they were appearing in Transaction log report. What we can do is delete the extra payment methods from Database but it will also delete entry if there is any. Please do let me know which payment method you want to delete then I will do as per your comment. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
Several have never been used as a Chrome example. So it was not me who created them and it was never used, as mentioned. I made an image with those to keep and those to delete. Before touching on "bank transfer" which is registered in duplicate, I would like that its does not delete the payments. This payment method is used so the information related to it is important. Please look before modifying or deleting it. Look at the payment in my attachment, it appears twice ...
<img width="940" alt="payment methot" src="https://user-images.githubusercontent.com/40500094/80497373-58d8d280-8938-11ea-9c87-0e786206e8f6.png">

--
Plusieurs n'ont jamais été utilisé comme exemple Chrome. Ce n'est donc pas moi qui les a créé et il n'a jamais été utilisé, tel que mentionné. J'ai fait une image avec ceux a conserver et ceux a supprimer. Avant de toucher à "virement bancaire" qui est inscrit en double, j'aimerais que sa ne supprime pas les paiements. Ce mode de paiement est utilisé donc les informations s'y ratachant sont importantes. Regardez avant de le modifier ou supprimer svp. Regardez le paiement dans ma pièce jointe, il apparait en double...

**Comment by usmanalikhan93** [comment]
Thanks for the additional information @JessicaSOS.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-1200

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. We have delete the empty one column and APPLE PAY (STRIPE). But we have found invoices against rest of the payment methods. So we just need to confirm from do you still needs to delete these payment methods as there is data associated with these ? If we delete these your those invoices will become unpaid. Please check excel file
[jessica-payment-methods.xlsx](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/4609146/jessica-payment-methods.xlsx)

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. We have fixed the duplication issue regarding Payment Method. Please verify at your end and do let us know if you have any question.

Thanks
Usman Ali.

**Comment by JessicaSOS** [comment]
Nothing has been done for this problem. Please go to "Transaction log" and you will see that the payment methods displayed are not those entered in the settings. To reopen

**Comment by JessicaSOS** [comment]
all the payments entered in the excel sheets have been modified. You can delete these payment methods, they are no longer charged to any invoice.

**Comment by usmanalikhan93** [comment]
Hello @JessicaSOS

I hope you are doing well. Thank you for the information. Let me check with this with developer and I will update you accordingly.

Regards,
Usman Ali

**Comment by usmanalikhan93** [comment]
Hello @JessicaSOS 

I hope you are doing. Just for the reminder, can you please highlight again those payment methods which you need to remove from the stores.

**Comment by JessicaSOS** [comment]
you have closed this task but it is not resolved. Can you refer to the image above with the colors red, orange and green in order to know which one to keep and which to delete.
