### ISSUE TITLE
Calendar 

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#416]
The agenda, reported february 23, 2018

1) Customers' names do not appear every time. Many are in no customer "walkin customer" instead of displaying the name of the customer. (See attachment "walkin customer").

2) Would it be possible for critical files to appear somewhere in the calendar?

3) When the tickets are completed (with status "completed", "repaired" or "repaired and collected"), can they disappear from the calendar? Or can we have an option to choose this option?

4) Is it possible to have a sound alert before the expiry date of the ticket?

5) I had seen a Beta version that we were supposed to see LEAD and TICKET in the calendar. When will this release come out? I had been told for a few days, but it's been several weeks ...
<img width="931" alt="calendar" src="https://user-images.githubusercontent.com/40500094/44236919-9bff0c00-a17c-11e8-959b-6af51c409688.png">

--
French :
L'agenda, déjà reporté le 23 février 2018

1) Le nom des clients n'apparait pas à tous coup. Beaucoup sont en aucun client "walkin customer" au lieu d'afficher le nom du client. (Voir pièce jointe "walkin customer").

2) Serait-ce possible que les dossiers critiques apparassent a quelque part dans le calendrier?

3) Lorsque les billets sont completé (avec le status "completed", "repaired" or "repaired and collected"), pouvent-ils disparaitre du calendrier? Ou pouvons-nous avoir une option afin de choisir cette option?

4) Est-ce possible d'avoir une alerte sonore avant la date d'échéance du billet?

5) J'avais vu une version Beta que nous étions suposé voir les LEAD et les TICKET dans le calendrier. Quand sortira cette version? On m'avais dit quelque jours, mais cela fait plusieurs semaines...

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
We are working on "Dispatch Module" that will allow you to view all "Leads & Tickets" on Calendar. 
I will ask the team if we can give you access to test it. Thanks

**Comment by JessicaSOS** [comment]
I know but when will it be? I had been told for a few days, but it's been weeks / months ...

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
We have gone live with Dispatch module in BETA. 
Please review and share your feedback on that. 
You can find more information from the following link:-
https://repairdesk.uservoice.com/knowledgebase/articles/1888324-dispatch-module

**Comment by JessicaSOS** [comment]
Hello,
It is very interesting this tab. Here are my comments:

- My employee has access only to his assignment and I can not find any option concerning the dispatch module in the post privileges.

- We should be able to access the ticket when we click on the ticket number or the name of the customer.

- Being able to send text messages is great. If you could add email addresses, it could be fine.

- When we click to see all the lead or see all the ticket, a page appears when the page is refreshed. It's a message page, sms, but it does not stay long enough for me to see it properly.

- It would be nice if we could see all the lead and ticket per store, those who are assigned to a technician and those who are not assigned. Example a checkbox or a default visualization that would show SOS Phone Limoilou, all assignments confused.

- Would it be nice to have the option (time option according to our preference) to activate a sound alert before the expiry date of the ticket?

For the rest, I have it tested by my staff and I'll get back to you if I have any other comments.
Have a good day
--
_french:
Bonjour,
C'est très interessant cet onglet. Voici mes commentaires:

- Mon employé a accès uniquement a son assignation et je n'i pas trouver d'option concernant le module de dispatch dans les privilèges des postes. 

- Il faudrait être capable d'accéder au ticket lorsque nous cliquons sur le numéro du billet ou le nom du client.

- Être capable d'envoyer des textos c'est super. Si vous pourriez ajouter les adresse courriels, ça pourrait être bien.

- Quand on clique sur voir tous les lead ou voir tous les ticket, une page apparait lors du rafranchoissement de la page. C'est une page de message, sms, mais elle ne reste pas assez longtemps pour que je puisse la voir correctement. 

- Sa serait bien si on pourrait voir tous les lead et billet par magasin, de ceux qui sont assigner à un technicien et ceux qui ne sont pas assigné. Exemple une case à cocher ou une visualisation par défaut qui montrerais SOS Phone Limoilou, toutes les assignations confondu. 

- Sa serait bien d'avoir la possibilité (option de temps selon nos préférence) d'activer une alerte sonore avant la date d'échéance du billet ?

Pour le reste, je le fait tester par mon staff et je vous revien si j'ai d'autre commentaire.
Bonne journée_

**Comment by Uzair-RepairDesk** [comment]
Thank you so much for your feedback @JessicaSOS on dispatch module. 
Currently, our module is in BETA and we will certainly consider your feedback while updating dispatch module.

**Comment by JessicaSOS** [comment]
Hello,
are you ready to deploy the live version soon? I have one of my employees working with Dispatch and I could share her comments. However, I do not want to spend time writing to you and translating comments if you do not intend to fix it quickly.

**Comment by JessicaSOS** [comment]
Hello, 
I have several comments to follow the use of "dispatch". Before you share it, can you settle those I previously told you? Here they are:

**In the calendar section:**
1- the names of the clients do not appear. The majority are in "walkin customer"
2- Critical files should appear by default first since they are late, they must be done immediately. They should appear in red.
3- When the tickets are completed (with status "completed", "repaired" or "repaired and collected"), can they disappear from the calendar?
4- Is it possible to have a sound alert before the expiry date of the ticket?

**In the dispatch section:**
1- To be able to see (with an option maybe) all the lead and all the tickets by store, without seeing them by assignment.
2- It would be nice to have the possibility (option of time according to our preference) to activate a sound alert before the due date of the ticket?
3- Critical files should appear by default first since they are late, they must be done immediately. They should appear in red.

**I have several other dispatch options, but I'll wait for them to be corrected before you share them.**

--
_french:
Bonjour, J'ai plusieurs commentaires à faire suite à l'utilisation de "dispatch". Avant de vous en faire part, pouvez-vous réglé ceux que je vous avait précédemment fait part? Les voici:

**Dans la section calendrier:**
1- les noms des clients n'apparaissent pas. La majorité sont en "walkin customer"
2- Il faudrait que les dossiers en critique apparaissent par défaut en premier puisque vu qu'il sont en retard, ils doivent être fait immédiatement. Ils devraient apparaitre en rouge.
3- Lorsque les billets sont completé (avec le status "completed", "repaired" or "repaired and collected"), pouvent-ils disparaitre du calendrier? 
4- Est-ce possible d'avoir une alerte sonore avant la date d'échéance du billet?

**Dans la section dispatch:**
1- Être en mesure de pouvoir voir (avec une option peut-être) tous les lead et tous les billets par magasin, sans les voir par assignation.
2- Sa serait bien d'avoir la possibilité (option de temps selon nos préférence) d'activer une alerte sonore avant la date d'échéance du billet ?
3- Il faudrait que les dossiers en critique apparaissent par défaut en premier puisque vu qu'il sont en retard, ils doivent être fait immédiatement. Ils devraient apparaitre en rouge.

**J'ai plusieurs autre option concernant dispatch, mais je vais attendre que ces derniers soit corrigé avant de vous en faire part._**
