### ISSUE TITLE
Du invoice reminder

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#417]
Resume of speak by phone with Ali on February 14, 2018

Due invoice reminder
1.	The tags in the programmed canned responses do not work. When sending an email to a customer with outstanding bills, nothing is displayed in the email.

2.	The due date should be set automatically, depending on what we have entered in the customer group. However, the customer group has a payment of 30 days and when we create the invoice, the amount due is due immediately. The deadline is not taken into consideration.

3.	Also, the **account statement of the customer group should send itself automatically** according to the due date. In this sense, no email is automatically sent at this time.

Have a nice day

--
French:
parler par téléphone avec Ali le 14 février 2018

1.	Les tags dans les réponses mail programmés ne fonctionnent pas. Lorsqu'on envoie un courriel à un client qui a des factures en souffrance, rien ne s'affiche dans le courriel.

2.	Les date dû devrait se mette automatiquement, selon ce que nous avons inscrit dans le groupe de client. Cependant, le groupe de client a un paiement de 30 jours et lorsque nous créons la facture, le montant dû est dû immédiatement. Le délais n'est donc pas pris en considération.

3.	Aussi, l'état de compte des groupe de client devrait s'envoyer automatiquement selon la date dû. Dans ce sens, aucun courriel ne s’envoie automatiquement actuellement.

Bonne journée

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by JessicaSOS** [comment]
#1 Not fixed. Need to be fixed.

#2 fixed.

#3 Not fixed. Need to be fixed.

**Comment by usmanalikhan93** [comment]
ok thanks. Let me check.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. I have reviewed your concern point 1, it is working fine. See screenshot attached. 
![due_invoice_reminder _](https://user-images.githubusercontent.com/39614480/50885043-7108a380-140e-11e9-9c6b-57af642d69a2.png)
