### ISSUE TITLE
Refurbishment ticket option

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#419]
it would be nice to add the search field by item "Refurbishment" in "manage ticket" in order to easily find the phones of the store versus the phones of the customers. Can you add this option?

_--
French :
sa serait bien d'ajouter le champs de recherche par item "Refurbishment" dans "manage ticket" afin de trouver facilement les téléphones du magasins versus les téléphones des clients. Pouvez-vous ajouter cette option?_

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
I really appreciate that you took the time to share your idea. 
I can certainly see how suggested improvements would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work during 3rd Quarter. We can either add it in our future roadmap. Thank you for your understanding. 

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
Uzair from RepairDesk

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 

You can filter the "Refurbishment" ticket with the search filter of "Refurbishment" under task type. Please check screenshot attached. 
You can review at your end. Thanks

![uzairshah   Ticket](https://user-images.githubusercontent.com/22955861/55619098-7ed18900-57b1-11e9-980d-d21f569167ad.png)

**Comment by JessicaSOS** [comment]
Thank you for this change. It should however, that the search filter works! At the moment, I have several repair tickets (open and closed) with tradein "refurb" devices and yet none are displayed. Whether I put a status or not, no result is displayed. Thank you corrected

--
french:
Merci pour cette modification. Il faudrait cependant, que le filtre de recherche fonctionne! En ce moment, j'ai plusieurs billets de réparation (ouvert et fermé) avec des appareils tradein "refurb" et pourtant, aucun ne s'affiche. Que je mette un statut ou pas, aucun résultat ne s'affiche. Merci de corrigé
