### ISSUE TITLE
iPhone 5 Battery part with other part in POS

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#420]
A part is invisible for the iPhone 5 **in the POS**

We click on "Phone" + "Apple" + (model) "iPhone 5" + (problems) Battery and Screen + (parts) Screen and battery

If we select the "battery" problem, we are able to select the "battery" part.

However, if we select the problem of "battery" + "screen", we are able to select the "screen" part, but not the "battery".

_--
french:
Une pièce est invisible pour l'iPhone 5 dans le POS

Nous cliquons sur "Phone" + "Apple" + (model) "iPhone 5" + (problems) Batterie and Screen + (parts) Screen and batterie

Si nous sélectionnons le problème de "batterie", nous sommes en mesure de sélectionner la pièce "batterie".

Cepedant, si nous sélectionnons le problème de "batterie" + "écran", nous sommes en mesure de sélectionner la pièce "écran", mais pas la "batterie"._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you provide your RD account credentials to Ali Hassan ? I need to review your bugs.

**Comment by JessicaSOS** [comment]
You have Ali?

**Comment by usmanalikhan93** [comment]
@JessicaSOS  

Thanks. He provided me the details.

**Comment by Repair-Desk** [comment]
@usmanalikhan93 Can you share an update on this?

**Comment by usmanalikhan93** [comment]
Sure @Repair-Desk

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Your reported issue has been assigned to development team and I hopefully it will be fixed early next week.
Your patience would be highly appreciated.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
ok thank you, I'm waiting for your news.

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 18 septembre 2018 05:44
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] iPhone 5 Battery part with other part in POS (#420)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

Your reported issue has been assigned to development team and I hopefully it will be fixed early next week.
Your patience would be highly appreciated.

Thanks!
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. I have verified on your account. Please verify at your end and do let us know if you have question.

Thanks!

**Comment by JessicaSOS** [comment]
Fixed !
