### ISSUE TITLE
Bundle, access to edit Bundles

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#421]
I would like the bundles that are editing in the problems, (see attachment bundle) to be editable only by an admin (or with privileges). At this point, any employee can click on the "save item for the future" button at the bottom of the POS page when selecting parts. By clicking this button, the employee has access to modify the bundles that are currently being created.
<img width="935" alt="bundle" src="https://user-images.githubusercontent.com/40500094/44241822-49314e80-a194-11e8-9643-8c9df9b93d68.png">
<img width="945" alt="pos bundle" src="https://user-images.githubusercontent.com/40500094/44241826-4d5d6c00-a194-11e8-818b-ab594fa1d39d.png">

_--
french:
J'aimerais que les bundles qui sont éditer dans les problèmes, (voir pièce jointe bundle) soit modifiable uniquement par un admin (ou avec des privilèges). En se moment, n'importe quel employé peut cliquer sur le bouton "enregistrer l'item pour l'avenir", dans le bas de la page du POS lors de la sélection des pièces. En cliquant sur ce bouton, l'employé à accès à modifier les bundles qui sont actuellement créé._

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS
I really appreciate that you took the time to share your idea.
I can certainly see how suggested improvement would be useful. With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work during 3rd Quarter. We can add it in our future roadmap. Thank you for your understanding.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
Uzair from RepairDesk

**Comment by JessicaSOS** [comment]
In your roadmap of which quarter?

**Comment by Uzair-RepairDesk** [comment]
Hopefully, we will add it in the next quarter. Thank you for your patience

**Comment by JessicaSOS** [comment]
We have been waiting for a long time after this change. When will it be effective?

**Comment by JessicaSOS** [comment]
I have not seen but you have added an option: Allow Item Bundle Creation. I tested it and all works. So we can close this task. Thank you so much !!
