### ISSUE TITLE
hide price on inventory tag

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#422]
In "label size", the option "hide price on inventory tag" does not work. It does not hide the price whether it is checked or not.
<img width="935" alt="setting inventory tag" src="https://user-images.githubusercontent.com/40500094/44242462-cf9b5f80-a197-11e8-84cc-7e7f7b27887e.png">

_--
french:
Dans "taille d'étiquette", l'option "masquer prix sur étiquette d'inventaire" ne fonctionne pas. Elle ne permet pas de masquer le prix qu'elle soit coché ou pas._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Please find developer feedback:- 
"This trigger works for Default Inventory Label, if user customizes his/her label and add item_price tag it will definitely show price on label. If he/she wants to hide it, then he should not add this tag."

I hope it will be helpful. 

Usman Ali khan.

**Comment by Repair-Desk** [comment]
Hi again Jessica - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up! 

Usman Butt

**Comment by JessicaSOS** [comment]
Please reopen this task. 
It was not like that before. You continually change things that work well. "Hide Price on the Inventory Tag", his says what he says. There are inventory tags (such as accessories for sale at the front of the store) that must have a price and others (such as parts in the repair shop) that must not have a price. Thank you for making this option work correctly.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS  

Sorry for the inconvenience. I have noted your concern. Will update once get more info on this.
