### ISSUE TITLE
Will not find products when creating ticket

### ISSUE THREAD

**Issue by msams1** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#423]
When creating a ticket, all the sudden I can not add ticket items. It's not locating them properly and I can not adjust costs or items therefore not allowing for adjustment of inventory or proper number reporting.

**Comment by Uzair-RepairDesk** [comment]
Hi @msams1 
We have recently improved search filter under ticket items. When you search for items, it populates the results with suggestive search and also provides information regarding stock and location. 
Can you please specify if you are facing issue to search the items. 
We have disabled to update cost of the item so you can track the exact cost coming from inventory item.

Moreover, we are concluding "Inventory Adjustment" and "Inventory Evaluation" (FIFO, LIFO, Weighted Average) feature and it will be deployed soon.

**Comment by usmanalikhan93** [comment]
Hi @msams1 

We have revert this. Please check on your end and do let us know if you have any question. 

Usman Ali
