### ISSUE TITLE
Trade In Report - does not work for items SOLD over a period. 

### ISSUE THREAD

**Issue by rlltd** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#425]
I have already reported this issue via chat.

I need to see a report showing details of all Trade Ins SOLD during a date range.

If I select the "SOLD" filter, and select the date range (say 1st August to 20th August), it will only show items which were purchased AND sold in the date range.

**Comment by usmanalikhan93** [comment]
Hi @rlltd 

I have checked your concern, but when I apply SOLD filter with date range, it only displays SOLD items. 
Can you share screen shots ? 

Usman Ali

**Comment by rlltd** [comment]
Ok i will attach 3 screen shots. One of the report filters, one of the total shown in the report, and one of the actual total trade ins sold.

Report shows: 18 
Actual sold: 48

Also, there is no paper trail for items which have been returned and resold... 
A report to show precise movement of trade ins would be necessary for shops like mine where we need to keep a separate spreadsheet.

**Comment by rlltd** [comment]
<img width="268" alt="screen shot 2018-08-27 at 00 41 46" src="https://user-images.githubusercontent.com/36428178/44634473-6d5e0e00-a992-11e8-9e62-aeaa8eff08c1.png">
<img width="602" alt="screen shot 2018-08-27 at 00 41 10" src="https://user-images.githubusercontent.com/36428178/44634474-6d5e0e00-a992-11e8-88f2-c8e46ba2770f.png">
<img width="2" alt="screen shot 2018-08-27 at 00 41 43" src="https://user-images.githubusercontent.com/36428178/44634475-6d5e0e00-a992-11e8-85f4-c6cfedfdc8b1.png">

**Comment by rlltd** [comment]
<img width="2" alt="screen shot 2018-08-27 at 00 41 43" src="https://user-images.githubusercontent.com/36428178/44634487-85359200-a992-11e8-86f0-522806ad4c27.png">

**Comment by rlltd** [comment]
<img width="617" alt="screen shot 2018-08-27 at 00 46 11" src="https://user-images.githubusercontent.com/36428178/44634499-a5fde780-a992-11e8-832a-201a5ac4663a.png">

**Comment by usmanalikhan93** [comment]
@rlltd  

Ok, Let me check this again.

**Comment by usmanalikhan93** [comment]
Hi @rlltd 

Can you share your login details with our support team? I have to investigate this internally.

**Comment by rlltd** [comment]
Hi, I provided these to support.

**Comment by usmanalikhan93** [comment]
Got it. Thanks

**Comment by usmanalikhan93** [comment]
Hi @rlltd 

I have checked in your account. It shows everything accurate. Please see screenshots of your account 
![trade in report](https://user-images.githubusercontent.com/39614480/46065665-1fece080-c18c-11e8-8bf1-522bc1643394.png)
![trade in](https://user-images.githubusercontent.com/39614480/46065666-1fece080-c18c-11e8-9d4e-d4233eaa1a23.png)

**Comment by rlltd** [comment]
HI,

It still is not right.
For the period we are comparing: 1st August to 25th September.
On the report which breaks down Accessories, Repairs, Trade Ins, it shows 48 sold. That is the actual number of devices sold.
The filters on both the trade in report and trade in page show 56.

Lets check this month so far:
1st September to 25th September
On the sales report we see that 47 trade in devices have been sold.
On the trade in reports we see only 17 sold.

What is going on?

**Comment by rlltd** [comment]
Can you block out the customer names and costs on the screenshots please?

**Comment by usmanalikhan93** [comment]
@rlltd So sorry for that. I am hiding it

**Comment by rlltd** [comment]
thanks!

**Comment by rlltd** [comment]
Hi,

It still is not accurate.

Why is it showing 56, when the sales report show 48?

Also check for September 1st to 25th, sales report shows 47 sold, trade in report with sold filter shows 17.

I need an accurate way to keep track of this.

One report shouldn’t be different to another report.

**Comment by usmanalikhan93** [comment]
Alright @rlltd I am looking into it.

**Comment by rlltd** [comment]
> Alright @rlltd I am looking into it.

Sorry i didn't realise the email response was delayed.

**Comment by usmanalikhan93** [comment]
Hi @rlltd 

Just an update we have improved our sales summary report. Can you check and let us know that if you are still facing this issue ?
