### ISSUE TITLE
Ex employee status

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#426]
Hello,
Can we put employees with "ex-employee" status?
Because, at the moment, I reached the limit of 30 users and yet, I have only 17 employees. I do not want to erase them in order to keep their time card, assignment, etc. data in archive. How should I proceed?

_--
french:
Bonjour,
Pouvons-nous mettre des employés avec le statut "ex-employé"? 
Car, en se moment, j'ai atteint la limite de 30 usagers et pourtant, j'ai seulement 17 employés. Je ne veux pas les effacer afin de conservé en archive leur données de fiches de temps, d'assignation, etc... Comment dois-je procéder?_

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
I will ask Ali to get in touch with you on this. Thanks

**Comment by JessicaSOS** [comment]
ok, i await him

**Comment by JessicaSOS** [comment]
Hello,
I am still without news of this. I have an employee who resigned me for this Friday. I will need a new employee next week, but at the moment, I reached the limit of 30 users. Can we put former employees into an Ex-Employee category instead of just disabling them or instead of deleting them?
Thank you for quickly answering me.

--
french:
Bonjour,
Je suis toujours sans nouvelle de ceci. J'ai un employé qui m'a donné sa démission pour ce vendredi. J'aurai donc besoin d'un nouvel employé dès la semaine prochaine, mais en se moment, j'ai atteint la limite de 30 usagers. Pouvons-nous mettre les ancien employé dans une catégorie Ex-employé au lieu de simplement les désactiver ou au lieu de les supprimer?
Merci de me répondre rapidement.

**Comment by Uzair-RepairDesk** [comment]
Hi @JessicaSOS 
Hope you are well. I apologize if it's not sorted yet. We have a plan to add improvements that will allow disabling the employee's account and once its disable, you will not be able to enable it again however you can add a new employee under the same subscription. 
We will do it once we stable the complete employee management module. 
However, I have asked Ali again to contact you to sort our the current concern.

Regards,
Uzair

**Comment by JessicaSOS** [comment]
Ali offers me to increase my current package emloyé. However, I do not currently employ 30 employees. I have many employees who have only worked a few days or months and are no longer active. When do you make these changes?

**Comment by Uzair-RepairDesk** [comment]
If you want to keep the linkage of data for the employees who are no longer active, you should not delete their records and increase your package subscription. However, if you want to list new employees with the same package, you can delete the employee's record and add new employee account in the same subscription. In this case, data linkage of the employee will not be there for you. 
**The above 2 solutions are according to the existing solution.** 

We have the plan to facilitate our customers to give the option to disable the employee account to add new in the same subscription. 
Hope I am able to answer your question.

**Comment by JessicaSOS** [comment]
ok tnx
