### ISSUE TITLE
Ticket Section not finding parts by Name.

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#427]
When adding Ticket items in ticket section, 
inventory can only be search by item code. not by name.
please have a look.

**Comment by usmanalikhan93** [comment]
Hey @bharaaus 

You can only search accessories whose type is part in ticket items. Kindly check the accessory you are searching for is it's type is part ? 
I hope this will help.

Thanks. 
Usman Ali
