### ISSUE TITLE
Inventory 

### ISSUE THREAD

**Issue by Cumbr1at3ch** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#428]
Hi Gents 
My invoice 3336 17/7/18 
Bought one and sold one yet the part 9kinfire7 is still showing one in free stock. There are other issues where i am find physical stock is lower than free stock in RD. When a sale is made the inventory isnt updating and the whole thing is falling down. I need this to be correct. I could scream at you becuase issues are becoming apparent. If this whole RD and its issues cant be sorted i will be cancelling my subscription because inventory updating after sales are made is paramount. How can i rely on out of stock reports when this is falling down /???????????? Sort it for crying out loud

**Comment by usmanalikhan93** [comment]
Hi @Cumbr1at3ch 

Usman here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @Cumbr1at3ch  

Please contact our customer support and provide RD credentials, and do tell them the issues you are facing so we can fix them. 

Thanks
Usman Ali.

**Comment by Repair-Desk** [comment]
@Cumbr1at3ch Definitely strange,

One of our support ninja will be in touch with you tomorrow to help you with this!

Usman Butt

**Comment by usmanalikhan93** [comment]
Hi again @Cumbr1at3ch - Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
