### ISSUE TITLE
Total Sales value on Commission Report doesn't account for discount

### ISSUE THREAD

**Issue by rlltd** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#429]
Hi,
I pay my staff a bonus for the volume of accessories they sell.
When i check the commission report it shows the total sales value as the total BEFORE discount (but it does give the proper commission based on the actual sale value)

My issue is that the total sales is way higher than it should be so i cannot determine who actually sold the highest value of accessories.

If there is another report somewhere, this isn't good enough: there is enough messing around trying to get accurate figures and there really should be a custom report builder that shows exactly what i want to see when i need to see it, instead of all the the work arounds.

**Comment by Uzair-RepairDesk** [comment]
Hi @rlltd 
Thank you for sharing your thoughts. We are already working to update "Employee Commissions" module including the report. You will be able to set specific criteria to apply commissions on "Sales" or "Profit" value. 
You will be able to get the right report according to your configurations. 

I will let you know once the new module is available for beta testing. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi @rlltd 
we have made improvement live where you can select specific criteria to apply commissions on "Sales" or "Profit" value.
For that, you need to go to **Settings** => **Employee** =>**Employee comission** => **Setup Comission**
![image](https://user-images.githubusercontent.com/22955861/73269353-7c3b9680-41fe-11ea-87ab-4be8db86a46e.png)
