### ISSUE TITLE
DUAL Transfer Inventory Created a blunder.

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#430]
DUAL Transfer Inventory Created a blunder.

Look at the photo below.

Staff clicked save, it was loading for more than 1 minute.
then they click save again, then it worked.
But we noticed it created two transfer order with same ID.
and stock got reduced from inventory TWICE.

Its OK if it happned, BUT  there was no option to redo the mistake.

We tried updating TO by:
Deleting Items,
Change Status to Cancelled and pending.

But it was making no modification in inventry stock.

So we spend heaps of time to update qty of each product.

Can you guys have a look into it and make amendment option in future. 
![transfer out](https://user-images.githubusercontent.com/34261339/44764570-b204c780-ab93-11e8-969c-5d806abc9797.png)

**Comment by usmanalikhan93** [comment]
Hey @bharaaus ,
 
Usman ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.
