### ISSUE TITLE
Woo commerce Tradein item #10370

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#433]
Hello,
I mentioned to you that the problem woo commerce was settled and it is the case. It is settled when the item has been put in an invoice. However, here we have a case where a device has been transferred to another branch for sale. It still appears on our website even if it sells because no sales transaction in Limoilou has been made. I did not think it would be a problem, but yes. As soon as the status changes (whether manually or not) the device must be removed from our website automatically.
<img width="941" alt="tradein item" src="https://user-images.githubusercontent.com/40500094/45116570-22c25b80-b121-11e8-87af-44971d944513.png">

_--
French:
bonjour,
Je vous avais mentionné que le problème woo commerce était réglé et c'est le cas. Il est réglé lorsque l'item a été mis dans une facture. Cependant, nous avons ici un cas ou un appareil a été transféré dans une autre succursale afin d'y être vendu. Il apparait toujours sur notre site internet même s'il en vendu, car aucune transaction de vente à Limoilou a été effectué. Je ne croyait pas que sa serait un problème, mais oui. Dès que le statut change (que se soit manuellement ou pas) l'apareil doit se retirer de sur notre site internet de façon automatique._

**Comment by Repair-Desk** [comment]
**Hello @JessicaSOS,**

Thanks for bringing this up! 

I'll go ahead and flag this with my product team so they know this is something you'd like to see. Definitely makes sense how that will improve your workflow. I'll make sure your voice is heard here 

Feel free to reach out next time you have any other questions or feedback for us - we always appreciate it!

**Comment by JessicaSOS** [comment]
Soon I hope ..

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Repair-Desk <notifications@github.com> 
Envoyé : 12 septembre 2018 16:32
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Woo commerce Tradein item #10370 (#433)

 

Hello @JessicaSOS <https://github.com/JessicaSOS> ,

Thanks for bringing this up!

I'll go ahead and flag this with my product team so they know this is something you'd like to see. Definitely makes sense how that will improve your workflow. I'll make sure your voice is heard here

Feel free to reach out next time you have any other questions or feedback for us - we always appreciate it!

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
We need to check this case again.

**Comment by usmanalikhan93** [comment]
For internal Use:
https://repairdesk.atlassian.net/browse/REP-1841

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 
 
Please find developer's feedback below
"If Order is transferred into different store which is not synced with WC then it will not update on RD when item sold on WC this is the functionality"

**Comment by JessicaSOS** [comment]
I understand what you are saying, but there should be an option that we can add when the device is no longer available in the store synchronized with Woocommerce. Or change your settings so that when a phone is sold, that it changes status or that it is transferred, that it withdraws it from Woocommerce. I have waited a long time for a solution / correction for this problem, thank you for reopening this task.
--
Je comprends ce que vous dite, mais il devrait plutôt y avoir une option que nous pouvons ajouter lorsque l'appareil n'est plus disponible dans le magasin synchronisé avec Woocommerce. Ou modifier vos réglages pour que lorsqu'un téléphone est vendu, qu'il change de statut ou qu'il soit transféré, que sa le retirer de Woocommerce. J'attends depuis très longtemps une solution/correction pour ce problème, merci de réouvrir cette tâche.

**Comment by JessicaSOS** [comment]
reopen please

**Comment by usmanalikhan93** [comment]
ok @JessicaSOS let me discuss this with our CTO then I will update you with more info.

**Comment by JessicaSOS** [comment]
thank you,
I await your news,
