### ISSUE TITLE
Registrer problem in transaction log

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#435]
For several weeks, it is impossible to search by a checkout in the search filter of the transaction log. It does not matter if we add other search filters, no results come out.
<img width="936" alt="registrer" src="https://user-images.githubusercontent.com/40500094/45165098-075b5d00-b1c2-11e8-8e55-3bdfa88a9b45.png">

_--
French:
Depuis plusieurs semaines, il est impossible de rechercher par une caisse dans le filtre de recherche du journal de transaction. Peut-importe si nous ajoutons d'autres filtre de recherche, aucun résultat ne sort._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS  

I have checked your concern. Everything is working fine. You have select Store and its Register/Checkout then search. Please check on your end with these steps. 
See Screenshot for reference 
![transaction_log](https://user-images.githubusercontent.com/39614480/45202765-748af300-b293-11e8-944b-d9c5dd96fe22.png)

**Comment by JessicaSOS** [comment]
ok so if I understand correctly, we must absolutely select the store associated with the case for it to work. It was the step I did not do. 
Thank you !

**Comment by usmanalikhan93** [comment]
Yes indeed @JessicaSOS  :)
