### ISSUE TITLE
iPad POS App - Thermal Print Function Does Not Work Correct... 

### ISSUE THREAD

**Issue by ibroken-aus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#436]
The thermal printer does not remain connected and does not cut after printing a receipt. In my opinion this app should use Printnode rather than the direct connection from the iPad to the printer as an iPad does not have drivers for direct printing.

**Comment by Repair-Desk** [comment]
@ibroken-aus Thanks for your feedback. If you've configured PrintNode whenever you create a repair ticket or an invoice using RepairDesk iPAD POS Register it will automatically print a thermal receipt.

Moreover we're also introducing direct print support for the iPAD POS Register through **Star TSP 100** Lan printer early next week. I've also attached list of features that will be released this month.

![c_users_dell_appdata_local_packages_microsoft skypeapp_kzf8qxf38zg5c_localstate_e820e3da-dcfc-4239-8bae-995bf3a8a286 1](https://user-images.githubusercontent.com/21986026/45387633-19a92100-b630-11e8-93c7-3ce23e6767b3.jpg)

Keep an eye for a newsletter.

Thanks and we look forward to helping you grow.

Usman Butt

**Comment by ibroken-aus** [comment]
> PrintNode whenever you create a repair ticket or an invoice using RepairDesk iPAD POS Register it will automatically print a thermal receipt.

Printnode config only provides the following relevant options for automatic receipts. 

1) Thermal Receipt - A docket receipt printed on thermal paper with customer & item information.

This is fine for providing the customer without a reference of the repair when a device is checked in for repair.

2) Invoice - Invoice printed on A4 paper with customer & item information.

Useless in terms of thermal printer use and still only triggers a print job for an accessory sold through POS, not payment of an invoice post ticket completion that shows zero balance outstanding. 

There are no other options for print node thermal printing what we would call a tax receipt showing zero balance after payment. This can only be done manually via the POS app direct with the printer (which would be ok except that it does not cut after printout).

**Comment by ibroken-aus** [comment]
Possibly, i'll check the new release once it's available.

**Comment by usmanalikhan93** [comment]
ok @ibroken-aus
