### ISSUE TITLE
Woocomerce failed transaction

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#437]
We have somebody who has tried to buy devices online. The transaction did not work, yet 2 of the 3 devices in the list were removed from our inventory. So we still have a problem with woo commerce integration. Thank you for correcting quickly!
<img width="951" alt="woocomerce failed transaction" src="https://user-images.githubusercontent.com/40500094/45362755-ae197200-b5a3-11e8-9dca-585d2fe8464e.png">

_--
French:
Nous avons quelque'un qui a tenté d'acheter des appareil en ligne. La transaction n'a pas fonctionné, mais pourtant, 2 des 3 appareils dans la liste ont été retirer de notre inventaire. Nous avons donc encore un problème avec le woo commerce integration. Merci de corrigé rapidement !_

**Comment by JessicaSOS** [comment]
Hello,

See my answers in red below.

Have a good day

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Repair-Desk <notifications@github.com> 
Envoyé : 12 septembre 2018 16:26
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Author <author@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Woocomerce failed transaction (#437)

 

Definitely strange!

Couple of questions: -

*	Did it create an invoice on RepairDesk? If Yes, please share invoice # The woocommerce automatically created the invoice in Repairdesk. I erase it manually.
*	Was the order on woocommerce store was completed successfully? If yes, please share woocommerce order # and email us your backend details for woo-commerce so we check this further The order in the woo trade was rejected. Here is the number: 19684

Usman Butt

**Comment by usmanalikhan93** [comment]
@JessicaSOS  Can you reply again ? I think your message is missing.

**Comment by JessicaSOS** [comment]
Question #1: Did it create an invoice on RepairDesk? If Yes, please share invoice # 
My Answer: The woocommerce automatically created the invoice in Repairdesk. I erase it manually.

Question #2: •	Was the order on woocommerce store was completed successfully? If yes, please share woocommerce order # and email us your backend details for woo-commerce so we check this further 
My Answer: The order in the woo trade was rejected. Here is the number: 19684

**Comment by usmanalikhan93** [comment]
Thanks @JessicaSOS. Let me discuss this with my dev team. I will revert back to you tomorrow on this.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS  

I have assigned this to Dev. Once I get more info on this, I will revert back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Please Find developer's feedback: 
"  Normally we create 3 webhooks:
1- Order Updated
2- Order Created
3- Product Created

But your client has to create another one which is order.deleted "

**Comment by JessicaSOS** [comment]
When a command is erase? I'm the one who erased the bill, because it does not have to be. The devices must not be able to be removed from the inventory if they are not sold. In the case attached, the inventory is updated negatively on 2 of the 3 devices. The webhook is no longer effective if we fraudulently purchase the same item 2 times or 3 times? Is it possible ?

_--
french:
Lorsqu'une commande est effacer? C'est moi qui a effacer la facture, car elle n'a pas lieu d'être. Les appareils ne doivent pas pouvoir être enlevé de l'inventaire si il ne sont pas vendu. Dans le cas en pièce jointe, l'inventaire c'est mis à jour négativement sur 2 des 3 appareils. Le webhook n'est peu-être plus efficace si nous achetons frauduleusement le même item 2 fois ou 3 fois? Est-ce possible ?_

**Comment by JessicaSOS** [comment]
No development? Still not set ... See item # 11483. The payment did not work. The sale is not completed. However, the item has been removed from the inventory and an invoice is created. I have to manually delete the invoice each time. See Attachment.
<img width="931" alt="item 11483" src="https://user-images.githubusercontent.com/40500094/48580242-ad2af680-e8ec-11e8-9e00-d9757b5e35b5.png">
<img width="939" alt="fraudulent invoice" src="https://user-images.githubusercontent.com/40500094/48580253-b1efaa80-e8ec-11e8-88d5-3a4a4eb33f4e.png">
<img width="939" alt="fl-13083" src="https://user-images.githubusercontent.com/40500094/48580276-bd42d600-e8ec-11e8-9e06-8ffe6625fb60.png">

--
french:
Aucun développement? Toujours pas réglé... Voir item #11483. Le paiement n'a pas fonctionné. La vente ne c'est donc pas complété. Pourtant, l'item a été retiré de l'inventaire et une facture c'est créé. Je dois supprimer manuellement la facture à chaque fois. Voir pièce jointe.

**Comment by usmanalikhan93** [comment]
Sorry for the delay @JessicaSOS Let me check this again at my end and will revert back to you if I get this issue on my end.

**Comment by JessicaSOS** [comment]
Hello,
Regarding this problem, the item no longer withdraws from the inventory. It remains "in stock" when the sale is unsuccessful. Which is perfect. However, a "unpaid" invoice creates this even if the transaction is unsuccessful. Is there any programming I could add to prevent an invoice from being created if the transaction is unsuccessful in woo commerce?

--
French:
Bonjour,
Concernant ce problème, l'item ne se retire plus de l'inventaire. Il reste "in stock" lorsque la vente est échouée. Ce qui est parfait. Cependant, une facture "unpaid" ce crée même si la transaction est échouée. Y a t'il une programmation que je pourrais ajouter pour ne pas qu'un facture se crée si la transaction est échouée dans woo commerce?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Can you please explain this issue in detail to Fahad (our support guy). If it is not fixed then I can do some action item against this task. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
The devices that are displayed on our website in the woo commerce are those that have the status "in stock" in repairdesk. When someone wants to buy a phone online, but the transaction fails (for whatever reason), an invoice is created in Repairdesk. This should not be because the transaction failed. So there should be a barrier that prevents invoice creation automatically if the transaction has failed. If the transaction is successful, it's ok to have an invoice.

--
Les appareils qui sont affiché sur notre site internet dans le woo commerce sont ceux qui ont le statut "in stock" dans repairdesk. Lorsque quelqu'un souhaite acheter un téléphone en ligne, mais que la transaction échou (peu importe la raison), une facture se crée dans Repairdesk. Cela ne devrait pas, car la transaction a échoué. Il devrait donc y avoir une barrière qui empêche la création de facture automatiquement si la transaction a échoué. Si la transaction réussi, sa c'est correct d'avoir une facture.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have noted your concern. I will discuss this with developer and will revert back to you.

**Comment by JessicaSOS** [comment]
did you opt to close the task instead of correcting it?

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
I apologize for the inconvenience. Can you please confirm if you are still facing specific issues with woocommerce so we can look into it? Thanks

Appreciate your patience.

**Comment by JessicaSOS** [comment]
Hey @Uzair-RepairDesk

This problem is still present. We have disabled all woocommerce sales for this reason.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
I apologize for this. This is definitely strange. Do you have any video, screenshots, or particular use case to share with us so we can check it again?

**Comment by JessicaSOS** [comment]
I don't have a video and I can't see what I could film. I sent you all the acreenshots previously. Currently, no more sales are made on our website because we have deactivated the woo commerce. There was too much error and invoices were automatically created when people tried to buy an item online without the payment working. I will therefore close this task despite the fact that it is not settled. It might be relevant for your users to correct this, you have all the information previously.

--

Je n'ai pas de vidéo et je ne vois pas ce que je pourrais filmer. Je vous ai envoyer toutes les acreenshots précédemment. Actuellement, plus aucune ventes n'est fait sur notre site internet car nous avons désactiver le woo commerce. Il y avait trop d'erreur et des factures se créaient automatiquement lorsque des gens essayaient d'acheter un item en ligne sans que le paiement fonctionne. Je vais donc fermer cette tâche malgré le fait qu'elle ne soit pas réglé. Ce pourrait être pertinent pour vos utilisateur de corriger cela, vous avez toutes les informations précédemment.
