### ISSUE TITLE
Double invoice

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#438]
I do not know how it is possible that an invoice is created in duplicate. With the same invoice number, same customer, same date, all are the same.
![double invoice in transaction log](https://user-images.githubusercontent.com/40500094/45364768-fb4c1280-b5a8-11e8-928d-bb8235d4335b.png)
![double invoice in customer view](https://user-images.githubusercontent.com/40500094/45364777-ff783000-b5a8-11e8-94a6-700d56a628d0.png)

_--
French:
Je ne sais pas comment c'est possible qu'une facture se crée en double. Avec le même numéro de facture, le même client, même date, tous est identique._

**Comment by Repair-Desk** [comment]
Hello @JessicaSOS,

Sorry for the inconvenience.

Can you please confirm how do you currently create an invoice. Through Point of sale, manage ticket or manage invoice. That might help us track the issue

**Comment by JessicaSOS** [comment]
My employees use the POS for invoice creation or to apply a payment on an existing invoice.

**Comment by usmanalikhan93** [comment]
OK thanks @JessicaSOS  for information.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope this issue is resolved now. If it occurs again in future, you can open this issue again. For now I am closing this. 

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
But you did nothing to correct the situation? No modification? It was not the first time he had arrived. You want another example?

_--
french:
Mais vous n'avez rien fait pour corriger la situation? Aucune modification? Ce n'était pas la première fois que sa arrivait. Vous désirez une autre exemple?_
