### ISSUE TITLE
Lead expired 

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#439]
Leads are expired on their own. I would like to know after how long?

Moreover, we can see in the history of the leads, that it is certain employee who made the modifications of the leads by changing it from "in progress" to "expired". However, it is not these employees who made the change. perhaps you should replace the user who makes the changes for the real user, in this case if, repairdesk. See attachment for example: L-le-20261 & L-le-20259.

It should also have the ability to change the status of a lead that is "expired". We are not able to do our monitoring properly because we can not adapt this status.
<img width="939" alt="lead expired 2" src="https://user-images.githubusercontent.com/40500094/45380412-a3c19d00-b5d0-11e8-90c9-7dc7e803b3dc.png">
<img width="938" alt="lead expired" src="https://user-images.githubusercontent.com/40500094/45380430-aa501480-b5d0-11e8-9c8b-8ac28282ee37.png">

_--
French:
Les leads se mettent expired tout seul. J'aimerais savoir après combien de temps?

Deplus, nous pouvons voir dans l'historique des leads, que c'est certain employé qui ont fait la modifications du leads en le faisant passer de "in progress" à "expired". Ce n'est cependant pas ces employés qui ont fait la modification. peut-être devriez vous remplacer le user qui fait les modifications pour le vrai user, dans ce cas si, repairdesk. Voir pièce jointe pour exemple: L-le-20261 & L-le-20259.

Il faudrait aussi avoir la capacité de modifier le status d'un lead qui est "expired". Nous ne sommes pas en mesure de faire nos suivi adhéquatement, car nous ne pouvons adapter ce status._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 
 
Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Lead expire after 7 days by own. 
The second option needs to be improve. I am notifying my product manager, once he approves this, I will let you know. 

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Now we have improved the lead that you have to manually change the status of lead to expire. It will not changed automatically after 7 days. Please verify on your end and do let us know if you have any question. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
Ok good ! Is it only for the new lead or for the old ones too?

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 23 octobre 2018 08:11
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Lead expired (#439)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

I hope you are doing well. Now we have improved the lead that you have to manually change the status of lead to expire. It will not changed automatically after 7 days. Please verify on your end and do let us know if you have any question.

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
For the old ones too, if its status is not expired yet. 
@JessicaSOS

**Comment by JessicaSOS** [comment]
It seems to be corrected, thank you!
