### ISSUE TITLE
Transaction log/ End Shift has issue

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#440]
Explained in this video.

https://drive.google.com/file/d/1wH5wHaS2mQDon4ruOF5276lHS2UgTxb-/view

two registers got combined together for no reason.

It create big confusion for staff at the end of the day.

**Comment by Repair-Desk** [comment]
Hey Bharat, Usman here 👋 Sure thing! Let us take a look to see if we're getting the same issue as you and one of our teammate will circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I have checked your concern on my end. It looks like everything is working fine. Can you help me to reproduce this issue ? When it comes up or what steps have you perform ?

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I think it may be some glitch. Now it seems everything is working fine. If it happens again you can reopen this task anytime. 

Usman Ali.
