### ISSUE TITLE
Need Option of NOT TO print receipt automatically

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#442]
Most of the times, customer doesn't need invoice or receipt. or we dont want to waste paper.
But every transaction prints out the Cloud Printing.

Is it possible to add option to NOT TO SEND CLOUD PRINT COMMAND TO SERVER ?

![ice_screenshot_20180913-152803](https://user-images.githubusercontent.com/34261339/45468806-f5e9f600-b769-11e8-8bc3-5872900dfd5a.png)

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk  can you check this?

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93  kindly review at your convenience.
