### ISSUE TITLE
REPAIR AND COLLECTED option is Gone from CHECKOUT Window

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#443]
![ice_screenshot_20180913-155837](https://user-images.githubusercontent.com/34261339/45469709-f71d2200-b76d-11e8-9087-e40388b264d0.png)

We noticed that after checkout, repair ticket status remains the same.
Then we noticed , there is no option of " REPAIR AND COLLECTED " option on checkout window anymore.

Have a look guys.

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

Your reported issue has been assigned to development team and I hopefully it will be fixed today or tomorrow. 
Your patience would be highly appreciated.
Thanks!
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @bharaaus  

![629](https://user-images.githubusercontent.com/39614480/45486058-369a3d00-b773-11e8-9a5f-ffa7d8b1e5b2.png)

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.

**Comment by bharaaus** [comment]
Thanks for quick fix. 
I'll test it by tomorrow.

**Comment by usmanalikhan93** [comment]
Welcome @bharaaus :)

**Comment by bharaaus** [comment]
It Came Back Again.
Whats going on ?
