### ISSUE TITLE
New Manufacture or Model Created is not showing up in POS Window

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#444]
Any new model or new manufacture we create  outside POS Window is not showing up in POS Window.

I believe main reason of this , because when we create new, it doesn't have option to choose Category.

So if you guys add option to select Category over there, it should solve the issue.

Am I right ?

![ice_screenshot_20180913-163938](https://user-images.githubusercontent.com/34261339/45471290-f38c9980-b773-11e8-8d9d-15f51c2cf86b.png)

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

You have to enable it "Show on POS" trigger. Go to settings > Module Configuration > View All Manufacturer > Enable that Manufacturer "Show on POS". 
I hope it will be helpful. 

Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
