### ISSUE TITLE
Item Search in POS Sort by Relevance [Enhancement]

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#445]
![2018-09-17 13_17_57-window](https://user-images.githubusercontent.com/23037821/45648058-4fa93380-ba7c-11e8-892f-909d70a4b7b5.jpg)

When searching for an item, I feel that items that contain the exact text should come up first in the list. Items should be searched and sorted by name first, then SKU or item number, then description.

**Comment by Uzair-RepairDesk** [comment]
Hey @ThinkDigitalRepair 
Thank you for highlighting this. 

@usmanalikhan93 
Can you check it at your end? I believe it should certainly bring it on top of the results.

**Comment by ThinkDigitalRepair** [comment]
No problem

**Comment by usmanalikhan93** [comment]
Hi @ThinkDigitalRepair 

We have improved search on POS. Please verify on your end and do let us know if you have any question. 

Thanks 
Usman Ali

**Comment by ThinkDigitalRepair** [comment]
Yo, it's perfect!

**Comment by ThinkDigitalRepair** [comment]
Super happy with the change!
