### ISSUE TITLE
Translate ADD AN OTHER DEVICE

### ISSUE THREAD

**Issue by ireparo** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#446]
Hi, i cant translate ADD AN OTHER DEVICE in the Appointment Calendar widget. 

Thanks

**Comment by ireparo** [comment]
Yes
Edgar@ireparo.es 
iReparo2017

Enviado desde mi iPhone

**Comment by usmanalikhan93** [comment]
Hi @ireparo 

Please delete your credentials from here. As it's public. Do change your password once you get this message.

**Comment by usmanalikhan93** [comment]
Your credentials said invalid email. 
@ireparo

**Comment by usmanalikhan93** [comment]
Hi @ireparo 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
