### ISSUE TITLE
option for printnode to print thermal receipt ONLY when invoice is paid

### ISSUE THREAD

**Issue by SamHext** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#448]
I don't give thermal reciepts to customers until invoice is paid so it doesn't help me any that thermal reciepts only print when ticket is created.  can you please either add the option for printnode to print the reciept once invoice is paid or add the option to manually print receipt through ipad app via printnode

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you please review it first on both web and iPAD?

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk.

**Comment by usmanalikhan93** [comment]
Hi @SamHext 

I hope you are doing well. We already have option for printnode to print the receipt on checkout. And for the other option, I have noted your concern.

**Comment by usmanalikhan93** [comment]
Hi again @SamHext - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
