### ISSUE TITLE
Remove a Discount

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#449]
When we withdraw the discount previously added to a ticket, it stays there. We put it in and pull it out at the end of the line, but it stays at the bottom of the page. It is a problem !

_--
french:
Lorsque nous retirons le rabais préalablement ajouter a un billet, il y reste. Nous le mettons et le retirons au bout de la ligne, mais il reste dans le bas de la page. C'est un problème !_

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
@JessicaSOS can you explain this with a screenshot ? So I can understand this in a better way.

**Comment by usmanalikhan93** [comment]
Thank you so much @JessicaSOS :) I will revert back to you tomorrow once I check with that video.

**Comment by JessicaSOS** [comment]
Tnx 😊

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 26 septembre 2018 10:30
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Remove a Discount (#449)

 

Thank you so much @JessicaSOS <https://github.com/JessicaSOS>  :) I will revert back to you tomorrow once I check with that video.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS  

I hope you are well. I have checked that video and it is an issue. I have verified on my end. I am assigning this to our development team. I hope it will be fixed early next week. :)

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by JessicaSOS** [comment]
It seems to be corrected. Thank you very much.
