### ISSUE TITLE
GRN Fails to save

### ISSUE THREAD

**Issue by ibroken-aus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#451]
When creating a GRN off an existing PO, I proceed to generate serials for all the stock and then 'save' but it does nothing and simply returns me to a blank GRN. There's no GRN showing as saved anywhere in the system.

**Comment by usmanalikhan93** [comment]
Hi @ibroken-aus 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @ibroken-aus 

I have verified this on my end. Please check this video, I have created same you said in above comment. And it's working fine. 
Video link: https://www.screencast.com/t/0Ngpv0yCrV

**Comment by usmanalikhan93** [comment]
Hi again @ibroken-aus  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
