### ISSUE TITLE
Variations on Products

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#452]
I have 16 outlets with repair desk and it would really help to add the following for inventory management.
I would like to request that variation be added to products.
Similar to how you do serialized inventory but allow multiple QTY of each variant.  I am not saying replace serialized just more use that as a base to add variants.  For iPhone 5 LCD I would like 1 product but have 2 variants White/ Black. Instead of creating 2 products.
Shown is an example from another system.
<img width="863" alt="screen shot 2018-09-25 at 3 26 43 pm" src="https://user-images.githubusercontent.com/43588617/46044270-8cf26e80-c0d7-11e8-9906-34225144a75b.png">

**Comment by Uzair-RepairDesk** [comment]
**Hi @Trevorshaw7** 
We certainly have the option to add variants of a specific item while creating serials. When you click on "Create Serials" and click on "Additional Information", the system allows you to set variants like "Colors, Size, Network, Condition or Warranty" 
E.g. If you have 10 items stock available, 5 with black color at different retails and cost. 5 with white at different retails and cost. You can create 5 serials with at one time with additional information and cost and then again create 5 serials with specific cost and variants (additional information).

**Please find screenshot attached.**

**_You can find more details about our serialized inventory feature from the following knowledgebase article:-_**
https://repairdesk.uservoice.com/knowledgebase/articles/930741-serialized-inventory

Please review and if you have any further questions, please feel free to ask. Thanks

**Regards,
Uzair from RepairDesk**

![serial variants](https://user-images.githubusercontent.com/22955861/46058495-d5ac3500-c174-11e8-8ade-afd87139092e.png)

**Comment by Trevorshaw7** [comment]
No, I do not want the variants serialized

**Comment by bharaaus** [comment]
User request is Color Matrix option.
I want this option too. But unfortunatly Usman said its not on roadmap till 2019

**Comment by Uzair-RepairDesk** [comment]
Thank you for your response @Trevorshaw7 and @bharaaus 
Currently, it's not possible to add "Variants" in single items as we have the standard serialized functionality available in RepairDesk that allows you to do that. It also helps you to have clearly traced your inventory items.

With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work during the 4th Quarter. 

However, I am adding a tag "On-hold to consider" so we can discuss it in-house and track it in future.

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know. Thanks

Regards,
Uzair from RepairDesk
