### ISSUE TITLE
Customer Group

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#453]
Hello,
We use a customer group "Business Customers (Net 30 open account)". We have customers in this group (and maybe the other group too I do not know) that automatically changes to "individual". Every month, there are 2 or 3 that change to "individual" because the total number of our customer group "Business Customers (Net 30 open account)" decreases every month. Only one person has permission to change the client group. Of course there is no blocking access at this level, but no employee really knows how to touch modify the customer group and there would be no point in doing so.

Currently we have a total of 65 customers in the customer group "Business Customers (Net 30 open account)". Next month we will be lower than 65 without anybody changing the customer group. What is unpleasant is that we have to send the statements of accounts manually. There is no automatism. So we do not send any billing statement to customers who disappear from this customer group because they are now considered regular "individual" customers and **since they are gone we have no way of knowing who it is !**

--
_French:
Nous utilisons un groupe de client "Clients Affaire (Compte ouvert Net 30)". Nous avons des clients dans ce groupe (et peut-être l'autre groupe aussi je ne sais pas) qui se change automatiquement en "individual". A tous les mois, il y en a 2 ou 3 qui se change en "individual", car le nombre total de notre groupe de client "Clients Affaire (Compte ouvert Net 30)" diminue à tous les mois. Une seule personne a l'autorisation de modifier les groupe de client. Bien sur il n'y a aucun blocage d'accès à ce niveau, mais aucun employé ne sait vraiment comment toucher modifier les groupe de client et il n'y aurait aucun intérêt de le faire.

Actuellement nous avons un total de 65 client dans le groupe de client "Clients Affaire (Compte ouvert Net 30)". Le mois prochain nous serons plus bas que 65 sans que personne change le groupe de client. Ce qui est désagréable, c'est que nous devons envoyé les états de comptes manuellement. Il n'y a aucun automatisme. Nous n'envoyons donc aucun état de compte aux clients qui disparaissent de ce groupe de client, car ils sont maintenant considéré comme des clients réguliers "individual" et **puisqu'ils sont disparu, nous n'avons aucun moyen de savoir qui c'est !_**

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have noticed that now there are 64 customers in that customer group. It's definitely strange. I have to look deeper in it. Once I get more information, I will revert back to you.

**Comment by JessicaSOS** [comment]
Here is the example of a customer who is given individually!
![customer](https://user-images.githubusercontent.com/40500094/47050486-8f903300-d16e-11e8-88b6-e5681af070ef.png)

**Comment by JessicaSOS** [comment]
Here is the name of another customer who has always been in business account but, who comes since we do not know how long, to change into an individual group. Nobody made these changes.
**Yann Louisor**

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I did not find a case that how it disappears. Just want to know that are you still facing this issue ?

**Comment by JessicaSOS** [comment]
yes we still have this problem. I had to correct the client "Yann Louisor" yesterday again ...
