### ISSUE TITLE
Show Cost price for User have no acces to see

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#454]
An employee whose option "view cost price" is disabled in the privilege of his post, has access to visualized the cost price of an item in the history. See Attachment.
<img width="935" alt="costpriceuser" src="https://user-images.githubusercontent.com/40500094/46229393-7a747100-c333-11e8-95b1-3ef15ab2691b.png">

_--
french:
Un employé dont l'option "voir le cost price" est désactivé dans le privilège de son poste, a accès à visualisé le prix coutant d'un item dans l'historique. Voir pièce jointe._

**Comment by JessicaSOS** [comment]
But could not you rather block the cost price in the history for the employee since the latter is entitled and access to the histirique but not the cost price ...

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Till now it's not possible for the developer to block any cost price in Admin history. Best way is to hide the history of that employee.

**Comment by JessicaSOS** [comment]
It's a bit contradictory you do not find? I must remove access to the employee who has access to the history because the option to hide the cost price does not work properly as a whole ... The option to hide the cost price does not work. If you wish to hide it, you must remove access to the RMA, the history in an inventory item, etc ...

**Comment by usmanalikhan93** [comment]
@JessicaSOS  Yes you have to hide history too in this case. I have talked to developer and he said it is not possible to do this now because it can disturb history. So, it is recommended to hide history if you restrict employee to see the cost price.

**Comment by JessicaSOS** [comment]
You should register it somewhere close to the cost price option, for your other customers who like me, think the cost price will hide everywhere when we do not give access ...

**Comment by JessicaSOS** [comment]
tnx

**Comment by JessicaSOS** [comment]
I believe you have removed an employee's "show cost price" option. I would like to know what is the option which allows or not an employee to visualize the cost price of a part?
The only likely options I see now in "manage access roles" are:
1- Show Cost Price in the category: Expense_Management
2- Change Part Cost Price in the category: Ticket
3- Revalue Cost Price in the category: Inventory
4- Change Cost, Retail Price & Tax in the category: Trade_in

What is it about? Is there one missing that I haven't seen? What can we do to correct the problem of the apparent cost price in the history of an item? (see Attachment)

--
French :
Je crois que vous avez retiré l'option "show cost price" a un employé. J'aimerais savoir quelle est l'option qui pemet ou pas à un employé de visualiser le prix coutant d'une pièce?
Les seules options probable que je vois maintenant dans "gérer les rôles d'accès" sont: 
1- Show Cost Price dans la catégorie: Expense_Management
2- Change Part Cost Price dans la catégorie: Ticket
3- Revalue Cost Price dans la catégorie: Inventory
4- Change Cost, Retail Price & Tax dans la catégorie: Trade_in

Du quel s'agit-il? Est-ce qu'il en manque un que je n'ai pas vu? Que pouvons nous faire pour corriger le problème du prix coutant apparent dans l'historique d'un item? (voir pièce jointe)
<img width="940" alt="user jimmy" src="https://user-images.githubusercontent.com/40500094/80427660-40c06f00-88b6-11ea-8a12-2efd4ab0c172.png">

**Comment by Uzair-RepairDesk** [comment]
Thanks, @JessicaSOS for the additional information. 

@usmanalikhan93 Can you please review it and discuss it with Humza. 
Let me know if you guys have any questions.

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-2584

@Uzair-RepairDesk FYI

**Comment by Uzair-RepairDesk** [comment]
We have already catered this request
