### ISSUE TITLE
Locking status after part is put on RMA

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#458]
After a part has been put on a RMA from a warranty claim, the status of the part should be locked, because if you switch it back to "used" it will allow you to do another warranty claim without taking stock out of inventory to be warrantied

**Comment by usmanalikhan93** [comment]
Sure thing @Trevorshaw7 . Let me take a look at this and revert back in 6-12 hours. I will reach out to you if I need more information.

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7

Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Thanks
Usman Ali.
