### ISSUE TITLE
Tag in Payment confirmation email

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#464]
Add the following tags in the automatic email when the customer applies a payment to their invoice:

{store_name} {store_address} {store_email} {store_website} {store_phone} (or {store_mobile})

_--
French:
ajouter les tag suivants dans le courriel automatique lorsque le client applique un paiement à sa facture:

{store_name}  {store_address}  {store_email}  {store_website}  {store_phone} (or {store_mobile})_

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS
I hope you are doing well. Thank you for highlighting this. We are going to start working on canned responses improvements at end of this quarter.
I will include your feedback on the same task. Thanks

**Comment by JessicaSOS** [comment]
Tag problem here too ....

**Comment by JessicaSOS** [comment]
In campaigner too

**Comment by JessicaSOS** [comment]
A year that our customers do not see the right signature. It's very professional!
