### ISSUE TITLE
Password in POS

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#465]
Can not write a code with letters since yesterday in the POS. Only the numbers work.
<img width="582" alt="pos" src="https://user-images.githubusercontent.com/40500094/46417991-cf7c0280-c6f8-11e8-8139-c8686aa92885.png">

_--
French:
Impossible d'écrire un code avec des lettres depuis hier dans le POS. Seulement les chiffres fonctionnent._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up.
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by JessicaSOS** [comment]
Fixed !
