### ISSUE TITLE
Suggestion - iPad POS App to allow adding a part with serial number to a repair.

### ISSUE THREAD

**Issue by ibroken-aus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#468]
We can add an accessory with serial to ticket or invoice, this extended to add parts to repair items would make the iPad POS app more efficient.

**Comment by Uzair-RepairDesk** [comment]
Hi @ibroken-aus 
Thank you for sharing your idea. I am pleased to inform you that we are already working on "Add Part" option while you select the specific repair problem and doesn't have a specific part available. 
We hope to release it in the next update.

**Comment by ibroken-aus** [comment]
Super important that it allows serialized inventory. I know on the old app it didn't allow selection of a part with serial. 

Ideally selection of the part needs to be something that can be added after the device has been checked in for repair.

**Comment by Uzair-RepairDesk** [comment]
Thank you for your response. If you have serialized parts, we already have an option available to "Select Serial" when you select it for the repair. Please check the screenshot attached.
![ipad select part serial](https://user-images.githubusercontent.com/22955861/46721375-4af72a00-cc8c-11e8-9c92-96626aa32239.jpeg)

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
