### ISSUE TITLE
Salary for staff changes for no reason

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#470]
One of our staff got the salary changed from $20 to $18, and we did not make any changes in the system. Even in the staff management, showing as $20.

Another question is why there are 2 places showing the pay rate instead of 1, and how it affect each other if one is set to another figure?

**Comment by quangc** [comment]
![screen shot 2018-10-11 at 5 34 51 pm](https://user-images.githubusercontent.com/22993605/46802130-37d97c80-cda8-11e8-89e7-796a7765c7e3.png)

**Comment by usmanalikhan93** [comment]
Sure thing @quangc. Let me take a look at this and revert back in 6-12 hours. I will reach out to you if I need more information.

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hey @quangc 

Can you confirm the Employee name against you facing this issue ?

**Comment by quangc** [comment]
Trinh Duong / tiffany duong

Best Regards,
Quang Cao.
General Manager.
+ Repair Centre Frankston
+ Repair Centre Springvale
+ Repair Partners
P: 1300 89 82 99
A : Shop 6 Shannon Street Mall, Frankston, Vic, 3199.

**Comment by usmanalikhan93** [comment]
Thanks for the information .

**Comment by usmanalikhan93** [comment]
Hi @quangc 

I am assigning this to dev team. They will further investigate why its changing the rate. I will revert back to you once I get more info on this. 

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @quangc 

Here is the feedback from dev: 

" It was changed manually by client. I have checked in database. Even he has changed pay to 5$ yesterday and than again 20$. If he wants to update his rate in reports, then ask him "

Do you want to change all the 18$ to 20$ in reports against Tiffany doung ?

**Comment by quangc** [comment]
Please send me detailed logs. I want to see who made the changes. Only my account has access to that payroll system ad I did not make any changes myself. This is security breach. I have to investigate urgently.

Best Regards,
Quang Cao.
General Manager.
+ Repair Centre Frankston
+ Repair Centre Springvale
+ Repair Partners
P: 1300 89 82 99
A : Shop 6 Shannon Street Mall, Frankston, Vic, 3199.

**Comment by usmanalikhan93** [comment]
Hi @quangc 

I have checked with our technical department and they said they can not share Database details with you. It was only identified that you have changed the salary in manage employees. It is recommended that if you feel it was changed by someone else, then please change you password.

**Comment by quangc** [comment]
I want to see the record of when (time and date) my account is used to change this.

I’m 100% sure no one access my account except me. It must be from the system or your team.

Best Regards,
Quang Cao.
General Manager.
+ Repair Centre Frankston
+ Repair Centre Springvale
+ Repair Partners
P: 1300 89 82 99
A : Shop 6 Shannon Street Mall, Frankston, Vic, 3199.

**Comment by usmanalikhan93** [comment]
@quangc 

You can check in Employee Activity Report in Reports section.

**Comment by usmanalikhan93** [comment]
Hey @quangc 

I have checked with Danish and he told me what you want. I have assigned to developer, Hopefully he will do the needful :) I will update you once I get more info on this.

**Comment by usmanalikhan93** [comment]
Hi @quangc 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by quangc** [comment]
It has been showed as $20 today. But I still need to know why it happens.

Best Regards,
Quang Cao.
General Manager.
+ Repair Centre Frankston
+ Repair Centre Springvale
+ Repair Partners
P: 1300 89 82 99
A : Shop 6 Shannon Street Mall, Frankston, Vic, 3199.

**Comment by usmanalikhan93** [comment]
@quangc 

I already told you what developer said. It was changed manually.

**Comment by quangc** [comment]
Please give me the date the make was changed so I can look up in the employee activity report. Thanks

Best Regards,
Quang Cao.
General Manager.
+ Repair Centre Frankston
+ Repair Centre Springvale
+ Repair Partners
P: 1300 89 82 99
A : Shop 6 Shannon Street Mall, Frankston, Vic, 3199.

**Comment by usmanalikhan93** [comment]
ok let me ask developer.

**Comment by usmanalikhan93** [comment]
He said he has removed data. I think it was 15th or 16th Oct. @quangc
