### ISSUE TITLE
image duplication in woo commerce after product is updated in RD

### ISSUE THREAD

**Issue by mobilebarn** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#472]
Hi guys, i have been trialing the woo commerce integration and it works great apart from one thing ive noticed. If i upload or have a product in RD with an image, everytime i update that product in RD  and save, it will duplicate the image in my media library within woo commerce. Not sure why this happens but i have worked out so long as i just add the image from within woo commerce and not RD things are fine.

**Comment by usmanalikhan93** [comment]
Sure thing @mobilebarn . Let me take a look at this and revert back in 6-12 hours. I will reach out to you if I need more information.

**Comment by mobilebarn** [comment]
ive created screen recording but unable to attach it @

**Comment by mobilebarn** [comment]
here it is zipped 
[rd bug.mp4.zip](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/2478384/rd.bug.mp4.zip)

**Comment by usmanalikhan93** [comment]
@mobilebarn Thanks for the video. Let me look into it. I will revert back to you soon if I need more info on this.

**Comment by usmanalikhan93** [comment]
Hi @mobilebarn 

Your reported issue has been assigned to development team and I hopefully it will be fixed early next week.
Your patience would be highly appreciated.

Thanks!
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @mobilebarn 

We have fixed your issue. Please also find developers comment on this 
"due to some complication and woocommerce limitation image will only sync first time when product is creating first time on wc from rd."

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @mobilebarn  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Usman Ali
