### ISSUE TITLE
Store Name should be Alternate Store on Ticket under location

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#473]
See attached,
I looked up a ticket from the customer section, and the store name is unidentifiable under location because all my stores have the same name, but have different alternate names.
<img width="1436" alt="screen shot 2018-10-22 at 3 35 07 pm" src="https://user-images.githubusercontent.com/43588617/47321062-a6bc9e00-d610-11e8-8458-bef8deb9d4ef.png">

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Sure thing customer name. Let me take a look at this and revert back in 6-12 hours. I will reach out to you if I need more information.

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Just an update we have fixed reported issue and it’s available for beta testing on sandbox server. We are hoping to go live with this either today or tomorrow hopefully.

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @Trevorshaw7  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali
