### ISSUE TITLE
Time in / Out

### ISSUE THREAD

**Issue by paengkie** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#475]
History must have an option to delete, i manage to do a trial for 2 employees which was successful but i cannot delete my trials time in and out.

**Comment by Uzair-RepairDesk** [comment]
Hi @paengkie 
Thank you for your post. Currently, it's not possible to delete the time log however we certainly give the option to update the time log if you have an admin account. 
You can go to "Timesheet" and click on "Update" to update the time log.

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
