### ISSUE TITLE
Default tickets as un-assigned

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#476]
Be able to make tickets default to un-assigned rather than the person logged in.

Our business process now requires staff to open the ticket prior to starting work and assign themselves to the ticket. Being able to set them as un-assigned when created will help us keep track of what our techs are working on.

**Comment by Uzair-RepairDesk** [comment]
Hi Andrew @afrahm,

Thank you for sharing your idea. Above option facilitates to the user of "One Man Army" and scenario differs with respect to business policies. I will discuss it with the team that what we can do to come up with the solution of the above suggestion. Thanks

Regards,
Uzair Shah
RepairDesk Team

**Comment by Uzair-RepairDesk** [comment]
Hey @afrahm 
We have made this improvement LIVE.
You can go to Store Settings > Module Configurations > Repairs > Ticket assignment to employee > You can select the criteria "Unassigned" that will allow you to create tickets without any assignment.
Hope it helps.

![uzairshah_Repairs_Config](https://user-images.githubusercontent.com/22955861/81063184-cd8bae00-8ef0-11ea-982d-dadb4d6fc317.png)
