### ISSUE TITLE
Reorder levels

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#477]
I need to be able to upload reorder levels at the main store without changing the reorder levels at other stores.  I uploaded inventory today to the main level, but it set reorder levels all the same across all stores.
Also I checked low stock report and nothing was on it, even though all my Quantity on hand are 0 and there are reorder levels set.  I checked a few skus to make sure they were set and once I saved that product it then showed up on the report.

**Comment by usmanalikhan93** [comment]
Sure thing @Trevorshaw7 . Let me take a look at this and revert back in 6-12 hours. I will reach out to you if I need more information.
