### ISSUE TITLE
error in view tickt in ipad app

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#478]
when open view ticket in ipad apps auto close apps ..why?

**Comment by usmanalikhan93** [comment]
Hey @hitman1986 

Are you using latest build? And whats you ios version? If your build is not latest, please download latest build. I have tested but it's working fine.

**Comment by hitman1986** [comment]
yes im used last update from ios and last update from build app ، It seems that the error occurs because the language of the entry for tickets is Arabic

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

We are releasing new release today, hopefully this issue will be fixed in this release. And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

**Comment by hitman1986** [comment]
slove the issue by your employee (danny hasan) thanks
