### ISSUE TITLE
creat ticket without customer information 

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#479]
creat ticket without comustomer information in ipad app, but I have also set the settings to force the employee to enter the information

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Currently settings are not replicating on iPAD app. I will discuss this with my product manager and will revert back to you once I get more info. 

Thanks
Usman Ali

**Comment by Uzair-RepairDesk** [comment]
Hey @hitman1986 
We made this improvement LIVE on iPad POS Register. 
If you made the trigger mandatory in web app under Store Settings > Module Configurations > Repairs i.e "Admin/Employee must add customer information before booking a repair job", It also applies on iPad and doesn't allow admin/users to create a ticket without customer information. 
Please review at your end. Thanks
