### ISSUE TITLE
disable password requaird

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#480]
disable password requaird after checkout on ipad app. i have to disable it from settings

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Till now there no such thing in settings which can disable password after checkout on ipad app. Moreover we have a plan to improve this. Hopefully we will add this in our coming releases.

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Currently settings are not replicating on iPAD app. I will discuss this with my product manager and will revert back to you once I get more info. 

Thanks
Usman Ali
