### ISSUE TITLE
add in search filter

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#481]
i need to add search by type in search filter in low stock report , this is amazing idea to easy search and quickly

**Comment by Uzair-RepairDesk** [comment]
**Hi @hitman1986** 
I really appreciate that you took the time to share your idea.
I can certainly see how suggested improvements would be useful. We are **already working to improve "Low Stock Report" functionality specification document** so I can pass your feedback to the team to incorporate it. We have a plan in the **roadmap to improve the report in this quarter.** 

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

**Regards,
Uzair Shah**

**Comment by hitman1986** [comment]
thank you

**Comment by Uzair-RepairDesk** [comment]
Hi @hitman1986 
I am pleased to inform you that we have gone LIVE with major updates in "Low Stock Report". 
We have also added search filter by Category on your request that will allow you to select criteria by category to search low stock items from any specific category. 
Please check the screenshot attached. 

You can review the updates and share your feedback. Thanks

![uzairshah low stock report](https://user-images.githubusercontent.com/22955861/50556476-59893680-0cfb-11e9-86d2-587bce5f5647.png)
