### ISSUE TITLE
improve checkout

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#482]
Suggestion:
The sales process will certainly be easier and faster. The less the number of clicks on the iPad, for example, the process of ending the sale of accessories requires pressing on: checkout-select the price - Complete payment- new sale
We can shorten it just one click :
If a customer is a walking  without specifying who it is, the sales process is a one click in a button ( Pay the full amount) 
And if it intends to sell in the form of forward payment, it will have another button on the sales screen and I expect this is easier and faster, and that will delight our customers and customers We are in the time of speed.

**Comment by Uzair-RepairDesk** [comment]
Hey @hitman1986 
I really appreciate that you took the time to share your idea. 

I can certainly see how suggested improvement would be useful and save the clicks to mark the full payment like we have the option available on the checkout page of the web. With a small team and a big roadmap, we have to pick new features and improvements based on the value and complete the main features of iPad App.
I am forwarding it to the team so we can consider it to discuss. 
And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards,
Uzair from RepairDesk

**Comment by hitman1986** [comment]
Thanks,it work

**Comment by Uzair-RepairDesk** [comment]
Hey @hitman1986  
We have introduced a new "Checkout Screen" on iPad POS Register. Please update our app.
