### ISSUE TITLE
Inventory adjustement missing in inventory transfert 

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#483]
It seems to be missing a transaction in item history # 3082. By logging on to SOS Phone Limoilou, in the item history, we can not see the inventory adjustment of transfer # TO-2199 from SOS Phone Limoilou to SOS Phone Ste-foy. Still, the invenatire adjustment was done correctly. The pieces were in stock and it was received by the shop of Ste-Foy. What is difficult to understand is not that the transaction is in the history, but rather that no adjustment has been made. It's as if the transfer never took place. So, how can we rely on inventory quantities?

<img width="937" alt="item 3082" src="https://user-images.githubusercontent.com/40500094/47575254-a887a980-d90f-11e8-9518-db5fce2d8a46.png">
<img width="948" alt="to-2199" src="https://user-images.githubusercontent.com/40500094/47575263-ae7d8a80-d90f-11e8-9e7d-d0ab200c099c.png">

_--
french:
Il semble manquer une transaction dans l'historique de l'item #3082. En étant connecter à SOS Phone Limoilou, dans l'historique de l'item, nous ne pouvons pas voir l'ajustement d'inventaire du transfert #TO-2199 de SOS Phone Limoilou vers SOS Phone Ste-foy. Pourtant, l'ajustement d'invenatire a été fait correctement. Les pièces étaient en inventaire et il a bien été réceptionné par la boutique de Ste-Foy. Ce qui est difficile a comprendre, ce n'est pas que la transaction ne figure par dans l'historique, mais plutôt qu'aucun ajustement n'a été fait. C'est comme si le transfert n'avait jamais eu lieu. Alors, comment pouvons-nous nous fier aux quantités en inventaire?_

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
You need to check this concern. Please review ASAP and update @JessicaSOS

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS

I have come up with one use case after testing, this issue comes is case of e.g. when you are logged in on store A and in inventory transfer you select from store B and to store C, it does not log history against that inventory. So for now I recommend you that please select from store in which you are logged in.

Furthermore, I am discussing this with developer for log transfer history in this case. I will update you when I get more info on this.

Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. We have released a fix for this issue as I have mentioned the use case earlier. Now history will be come up in inventory in these cases. I hope in future, you will not face these issues again related to missing transactions. 

For now I am closing all tasks you reported related to missing inventory.

**Comment by JessicaSOS** [comment]
As previously mentioned, we were connected to store A. A transfer was made from A to B and received by B. All was done correctly and there is no C store in the story. This is possibly related to the problem # 432 which has not been solved yet ...
