### ISSUE TITLE
Inventory Valuation no longer an option

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#484]
Why is Inventory Valuation no longer an option?

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Can you explain a bit more if possible with a screenshot or a video ?

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

I believe inventory valuation method is implemented on your account. Please verify on your account. And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Regards
Usman Ali
