### ISSUE TITLE
Negative adjustement in inventory item & note in inventory item

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#487]
Hello,
A customer has a coin on order in a ticket. We do not have it in inventory so the inventory drops to -1 when the coin is put in the ticket.

For another file, I refunded a customer, but I left the room on his phone. So I have to remove the coin in the invenatire manually, because after my refund, the inventory is adjusted to +1 (because of the refund).

In this moment, I am therefore at 0 and I therefore wish to return the invat to -1. Once I receive my order (+1), I will have fallen to 0 since this piece will go for the ticket mentioned above.

1- However, I am unable to make a negative adjustment. An error appears telling me that I can not do it. Is this normal? I think we should be able to do it ...
<img width="943" alt="negative adjustement" src="https://user-images.githubusercontent.com/40500094/47801255-27138b00-dd04-11e8-805b-4c503b025cf2.png">

2- In addition, it is mandatory to leave a note when we make an adjustment. That's great! But the notes do not appear pat. It would be relevant to be able to see them in the product history.

_french:
Bonjour,
Un client a une pièce en commande dans un billet. Nous n'en avons pas en inventaire alors l'inventaire tombe a -1 lorsque la pièce est mise dans le billet. 

Pour un autre dossier, j'ai remboursé un client, mais j'ai laissé la pièce sur son téléphone. Je dois donc aller retirer la pièce dans l'invenatire manuellement, car après mon remboursement, l'inventaire c'est ajusté a +1 (à cause du remboursement). 

En se moment, je suis donc à 0 et je souhaite donc remettre l'invenatire à -1. Une fois que je receverai ma commande (+1), je vais tombé a 0 puisque cette pièce ira pour le billet mentionné plus haut. 

1- Cependant, je suis incapable de faire un ajustement négatif. Une erreur s'affiche me mentionnant que je ne peux pas le faire. Est-ce normal? Je crois que nous devrions être en mesure de le faire...

2- De plus, il est obligatoire de laisser une note lorsque nous faisons un ajustement. C'est super! Mais les notes n'apparaissent nul pat. Sa serait pertinent de pouvoir les voir dans l'historique du produit._

**Comment by usmanalikhan93** [comment]
Sure thing @JessicaSOS . Let me take a look at this and revert back in 12-24 hours. I will reach out to you if I need more information.

**Comment by Uzair-RepairDesk** [comment]
@JessicaSOS 
hope you are fine, currently,
1. you cannot create negative adjustment when you onhand stock is zero. negative adjustment can only be done when the stock is present. 
2. Notes added while doing the adjustment are shown in the report for stock adjustment. it is also for the record that why a user is adding adjustment. but we can work on the option for adding notes along with item admin history. let me confirm with the dev team and I will revert back to you.
Hope this helps you.

**Comment by JessicaSOS** [comment]
1- If I have to make an adjustment from 1 to 0, because there is an error in the inventory and I already have an item put in a ticket, how am I supposed to do? I understand the principle of not being able to adjust unless 0, but if customers are already waiting for this coin and it is put in a note, it is normal to be in negative quantity (-1, -2, - 3 etc ...). Negative adjustment is therefore necessary.

2-I would love to see the notes in the history. I look forward to hearing from you.

3- Also, when taking inventory, if an item is a -1 (quantity listed in inventory) and we want to set it to 0 (quantity in hand), the adjustment does not work. We must make an adjustment of more than 1 (quantity in hand) before going to remodify the quantity for 0. In summary, we therefore need to make 2 adjustments in order to go from -1 to 0 when taking inventory .
--
1- Si je dois faire un ajustement de 1 à 0, car il y a une erreur dans l'inventaire et que j'ai déjà un item de mis dans un billet, comment je suis supposé faire? Je comprend le principe de ne pas pouvoir ajuster à moins que 0, mais si des clients attendent déjà cette pièce et que cette dernière est mise dans un billet, c'est normal d'être en quantité négative (-1,-2,-3 etc...). L'ajustement négative est donc nécessaire.

2-J'aimerais beaucoup voir les notes dans l'historique. J'attends de vos nouvelles a ce sujet.

3- Aussi, lors d'une prise d'inventaire, si un item est a -1 (quantité inscrite en inventaire) et que nous souhaitons la mettre à 0 (quantité en main), l'ajustement ne fonctionne pas. Nous devons faire un ajustement de plus de 1 (quantité en main) avant d'aller remodifier la quantité pour 0. En résumé, nous avons donc besoin de faire 2 ajustements afin de passer de -1 à 0 lors de la prise d'inventaire.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
Hope you are fine.

Point number 1: for this, i had to connect with  Developer and then I will revert back to you. 
Point number 2 is already done, you can see the notes added while adjustment in item history.as you can see in attached screen.
![repair phones edit mobile accessories parts 123465](https://user-images.githubusercontent.com/22955861/51656978-bdceab80-1fc4-11e9-8809-18354b508483.png)


point number 3: when your quantity is -1 and you want to make it zero, the system allows you to add 1 quantity in increase adjustment. and make your on-hand quantity 0.

**Comment by JessicaSOS** [comment]
# 1, I'm waiting for your news.

# 2, you're right, it works perfectly!

# 3, Yes the positive fit works manually, but it does not work in inventory count when taking inventory.
