### ISSUE TITLE
Double scan (sku) in count inventory

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#488]
The double scan works in the Pos. They do not work, however, when we take inventory. Only one of the two scan (sku) is taken into account when taking inventory, even if both scan were previously added to the item. Example: gear4 iphone 6 gold piccadilly sku # 1: 654728952792 sku # 2: 4895200201847

_--
french:
Les doubles scan fonctionnent dans le Pos. Ils ne fonctionnent cependant pas lorsque nous prennons l’inventaire. Seulement un des deux scan (sku) est pris en considération lors de la prise d'inventaire, même si les deux scan ont été préalablement ajouté à l'item. Exemple : gear4 iphone 6 or piccadilly sku #1:654728952792 sku #2 :4895200201847_

**Comment by usmanalikhan93** [comment]
Sure thing @JessicaSOS . Let me take a look at this and revert back in 12-24 hours. I will reach out to you if I need more information.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can explain this to me with Screenshots ? It may be easy for me to understand the issue.

**Comment by JessicaSOS** [comment]
<img width="947" alt="4522" src="https://user-images.githubusercontent.com/40500094/48088162-3d6f8a00-e1cf-11e8-8547-64b5512e7cbf.png">

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up . 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

**Comment by JessicaSOS** [comment]
I will check after the Christmas holidays.

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 17 décembre 2018 06:26
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Double scan (sku) in count inventory (#488)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by JessicaSOS** [comment]
Hello,
Sorry for the response time, I was on vacation. I can not count inventory using sku (single or double). I tried with several items. I therefore consider this problem as unresolved. I ask you to reopen this issue.
Thank you

**Comment by usmanalikhan93** [comment]
ok @JessicaSOS. Let me take a look on this.
