### ISSUE TITLE
Ticket - inventory association problem

### ISSUE THREAD

**Issue by yossigrosskopf** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#489]
When creating a ticket with a repair the ticket isn't associating the inventory item ID
This causes a big problem when updating the inventory.
If you change the inventory Manufacturer, Device/ Model or problem then any open tickets associated with that inventory item will be blank, it will remove all the device and task information.

Another problem is inventory is case sensitive and can allow the system to have duplicates with different cases, for example, I have to manufactures Apple & APPLE

**Comment by Uzair-RepairDesk** [comment]
Hi @yossigrosskopf 
Can you help us to check this concern with relevant screenshots? It will be appreciated. Thanks

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
