### ISSUE TITLE
Note in Lead

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#490]
Whether in "additional information" (under the lead's task) or in "customer comment", the notes entered in these two places do not appear in the client's submission. If the customer wants us to add a detail or a note, it is impossible for him to see it on his submission. The note disappears ...
<img width="938" alt="leaddd" src="https://user-images.githubusercontent.com/40500094/47814576-6f42a580-dd24-11e8-956b-37d74a40a380.png">

_--
french:
Que se soit dans "information supplémentaire" (sous la tâche du lead) ou dans "commentaire des clients", les notes inscrit a ces deux endroit ne s'affiche pas dans la soumission du client. Si le client souhaite que nous ajoutions un détail ou une note, il est impossible qu'il le voit sur sa soumission. La note s'efface..._

**Comment by usmanalikhan93** [comment]
Sure thing @JessicaSOS . Let me take a look at this and revert back in 12-24 hours. I will reach out to you if I need more information.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

With my understanding, you are asking to add customer notes on estimates PDF ?

**Comment by JessicaSOS** [comment]
Yes exactly, because sometimes it is necessary for us or for the customer to have a particular note on his submission (for insurance purposes, to provide a precision or other). Currently, no matter what notes are written under "additional information" or "customer comment", none are visible.

**Comment by usmanalikhan93** [comment]
OK thanks for the feedback. Let me discuss this with Uzair. I will let you know once I get more info on this.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Your reported issue has been assigned to development team and hopefully it will be fixed in this week.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. We have added customer notes in lead estimate receipt. Please verify at your end and do let us know if you have question.

![lead_estimate_live](https://user-images.githubusercontent.com/39614480/50833653-bfb52f80-1373-11e9-86d7-5eb63c3863f1.png)

**Comment by JessicaSOS** [comment]
Whether in the "customer note" or the "additional information", no note written in these two places appears on the estimate, in the lead or in the notes of the lead. At no place. It's simply erased. I also have
try to reset the model of the estimate by default before testing, but without success. Thank you for reopening this task.
--
Que se soit dans le "customer note" ou le "additionnal information", aucune note inscrite à ces deux endroits n'apparait sur l'estimation, dans le lead ou dans les notes du lead. À aucun endroit. Sa s'efface tous simplement. J'ai aussi 
essayer de réinitialiser par défaut le modèle de l'estimation avant de tester, mais sans succès. Merci de réouvrir cette tâche.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Please check this video, are you performing these steps ? 
Video link: https://www.screencast.com/t/NFKBZkFdIUi

**Comment by JessicaSOS** [comment]
Hello,
yes we are doing all the same steps. The only thing I see different is that we click on "add line" before writing the note in customer comment. Maybe that's the problem. Can you test it?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

It's the flow. You have to click on add line after writing the note in customer comment. As it is in video.

**Comment by JessicaSOS** [comment]
Fixed !
