### ISSUE TITLE
Add option «repaired» & «complete» in notification setting

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#491]
Hello,
Can you add in automated notifications:
1- send the customer an **email notification** when the status **"repaired"** was put in a ticket.
2- send the customer an **email notification** when the status **"completed"** has been put in a ticket.
3- send the client an **SMS notification** when the **"repaired"** status has been put in a ticket.
4- send the client an **SMS notification** when the status **"completed"** has been put in a ticket.

Thank you for letting me know and have a good day

_--
french:
Bonjour,
Pouvez-vous ajouter dans les notifications automatisé :
1- envoyer au client une **notification courriel** lorsque le status **"repaired"** a été mis dans un billet.
2- envoyer au client une **notification courriel** lorsque le status **"completed"** a été mis dans un billet.
3- envoyer au client une **notification SMS** lorsque le status **"repaired"** a été mis dans un billet.
4- envoyer au client une **notification SMS** lorsque le status **"completed"** a été mis dans un billet.

Merci de me laisser savoir et bonne journée_

**Comment by Uzair-RepairDesk** [comment]
Hello @JessicaSOS 
We have already automatic notifications available if a ticket is marked "Repaired" or "Completed". 
The system certainly sends an email or SMS (if integration is enabled).
Please go to Store Settings > Email & Notifications > Notification 
and make sure that notification triggers are ON.
Please check the screenshot attached. 
![notification config](https://user-images.githubusercontent.com/22955861/48246189-400cf200-e410-11e8-90ca-2c0e4d40d807.png)

**Comment by JessicaSOS** [comment]
What I was mentioning was separating notifications from status "repaired" and status "completed". Currently, it is written "completed" in the notifications, but a notification is also sent if the status is "repaired". Am I wrong?

**Comment by Uzair-RepairDesk** [comment]
"Completed" and "Repaired" status are considered as the same status for the ticket. 
You can make an SOP to set either "Repaired" status or "Completed" status. 
By the way, we are going to update the complete module to **Link Notifications + Canned Responses + Status.** 
We have completed the documentation and design. **Please find design attached for the reference.** 
We have the plan to start development in the next month. 
![emial-notification-and-event-with-tabs](https://user-images.githubusercontent.com/22955861/48461365-30692100-e7f5-11e8-86f9-3360be0eed9f.jpg)

**Comment by JessicaSOS** [comment]
Can you consider separating the Repaired option and the Completed option? Or put an option if we want them to be together or not? the only problem comes from the ticket transfer. When a ticket is repaired at another branch, the "repaired" status can send a notification to the customer, but the phone is not ready to be picked up at the original branch. That's why I wanted to separate the options. Do you have a better idea for this?
