### ISSUE TITLE
Text note is missing when invoice is sending by mail

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#492]
When we want to email an invoice to a customer, the text we enter in the "note" field does not send. The customer never receives the text sent with his invoice. This is written in no notes location either. See Attachment.
<img width="945" alt="invoice action" src="https://user-images.githubusercontent.com/40500094/47862032-95228580-ddca-11e8-9f4d-580d9b2a86bb.png">
<img width="929" alt="invoice by mail" src="https://user-images.githubusercontent.com/40500094/47862041-9ce22a00-ddca-11e8-95cb-cd97dba491c1.png">
<img width="944" alt="mail received" src="https://user-images.githubusercontent.com/40500094/47862060-a4093800-ddca-11e8-8d9d-1aef32ef7ff0.png">

_--
french:
Lorsque nous souhaitons envoyer une facture par courriel a un client, le texte que nous entrons dans le champs "note" ne s'envoie pas. Le client ne recoit jamais le texte envoyé avec sa facture. Cela s'écrit dans aucune emplacement des notes non plus. Voir pièce jointe._

**Comment by usmanalikhan93** [comment]
Sure thing @JessicaSOS . Let me take a look at this and revert back in 12-24 hours. I will reach out to you if I need more information.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked your concern but unfortunately, I am unable to reproduce your issue. It's working fine kindly check again. See Screenshot below: 
![email_invoice_notes](https://user-images.githubusercontent.com/39614480/48056712-2da67480-e1d4-11e8-9596-29d254e4f957.png)

**Comment by JessicaSOS** [comment]
I found the problem. It was missing a tag in my scheduled responses. The tag "notes" was missing ...
Fixed
