### ISSUE TITLE
Error in the detail sales transaction "Tradein" in the "Location Sales By Item Type" REPORT

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#494]
We sold an iPhone 5 today on November 5, 2018. However, I do not see it in the tradein report. It should appear because it has been sold.

I have attached to you a screenshot of Limoilou's sales report dated November 5, 2018. We can see that 2 devices have been sold. However, 3 devices were sold today. Missing item # 9232.
<img width="946" alt="tradein november5" src="https://user-images.githubusercontent.com/40500094/48013779-18a5e480-e0f3-11e8-8ead-07c52f3139da.png">

I put you a screenshot of the history of item # 9232. We can see that it was sold in invoice FL-10164.
<img width="943" alt="item 9232" src="https://user-images.githubusercontent.com/40500094/48013786-1f345c00-e0f3-11e8-824d-2e77b118180d.png">

I have also attached the invoice # FL-10164. The item has been put correctly in the invoice.
<img width="937" alt="invoice fl-10164" src="https://user-images.githubusercontent.com/40500094/48013799-265b6a00-e0f3-11e8-8342-5f224d176156.png">

Where did the error come from? We had problems with item # 11046 last week. The item does not appear in the sales report of the Limoilou store, but the transaction was done correctly.

Thank you for coming back quickly.

_--
french:
Nous avons procédé à la vente d'un iPhone 5 aujourd'hui le 5 novembre 2018. Cependant, je ne le vois pas dans le rapport de tradein. Il devrait apparaitre, car il a bel et bien été vendu.

Je vous ai mis en pièce jointe une capture d'écran de rapport de vente de Limoilou en date du 5 novembre 2018. Nous pouvons voir que 2 appareils ont été vendu. Cependant, 3 appareils ont été vendu aujourd'hui. Il manque l'item #9232.

Je vous ai mis une capture d'écran de l'historique de l'item #9232. Nous pouvons y appercevoir qu'il a bel et bien été vendu dans la facture FL-10164.

Je vous ai également mis en pièce jointe la facture #FL-10164. L'item a bel et bien été mis correctement dans la facture. 

D'où vien l'erreur ? Nous avons eu des problème avec l'item #11046 la semaine dernière. L'item n'apparait pas dans le rapport de vente du magasin de Limoilou, mais la transaction a pourtant été faite correctement._

Merci de me revenir rapidement.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
I sincerely apologize for the inconvenience. 
@usmanalikhan93 
Please check the above-highlighted issue and assist Jessica accordingly. Thanks

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by JessicaSOS** [comment]
The problem is still here. Another example is item # 10139, sold on December 1, but does not appear in the report.

**Comment by usmanalikhan93** [comment]
HI @JessicaSOS 

Can you specify or you know any case in which it happens ? It will be more easy for me to replicate and try to resolve this issue ASAP.

**Comment by JessicaSOS** [comment]
I did not find the source of the error. It appears regularly, but I do not know the constancy. It's not everyday but it's a few times a week, in any of our shops. Sorry, but I have no more iformation. I mentioned 2 examples a little higher ...

**Comment by usmanalikhan93** [comment]
Sorry @JessicaSOS I have tried to reproduce the use case for this but it is working fine on our test accounts. I will appreciate if you come up with a use case or something which can help us to replicate this.

**Comment by JessicaSOS** [comment]
I'm coming back from vacation so I have not seen this problem lately. I will pay attention in the next few days and write to you when I see this problem.
--
Je revien de vacance donc je n'ai pas vu ce problème dernièrement. Je vais porter une attention dans les prochains jours et vous écrire lorsque je verrai ce problème.

**Comment by usmanalikhan93** [comment]
Sure @JessicaSOS. If you face this issue again, you can reopen this task and I will check.

**Comment by JessicaSOS** [comment]
I have not seen this problem this week and since it is a random and intermittent problem, it is harder to test. I'll let you know if I see this problem again.
