### ISSUE TITLE
ghost adjustement

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#496]
Hello,
I noticed that the inventory is being adjusted for no reason. See screenshot of item # 2286. Adjustments in red are neither inventory adjustments, stocktaking, notes, etc.

It's the same thing in several items. Another example: 2250
<img width="931" alt="item 2286" src="https://user-images.githubusercontent.com/40500094/48030708-eeb6e700-e11f-11e8-89d9-da37903a7125.png">

_--
french:
Bonjour,
J'ai remarqué que l'inventaire se désajuste sans raison. Voir capture d'écran de l'item #2286. Les ajustements encadré en rouge ne sont ni des ajustement d'inventaire, ni des prise d'inventaire, ni des billets, etc... 

C'est la même chose dans plusieurs item. Autre exemple: 2250_

**Comment by Uzair-RepairDesk** [comment]
Hi @JessicaSOS 
I apologize for the inconvenience. Let me check this issue in detail and I revert back to you in the next 24 hours. 
Thank you for your patience.

**Comment by Uzair-RepairDesk** [comment]
Hi @JessicaSOS 
I checked your screenshot in detail. The dates to update inventory is before the "Inventory Adjustment" and "Inventory Valuation" feature. All the stock updates made manually before adjustment. Old records cannot be updated however you will get the valid reason of adjustment if you make any stock updates after the implementation of this feature.

**Comment by JessicaSOS** [comment]
But even before the change, if the employee did not have access to adjust the inventory other than in an inventory count, that may be this adjustment? The inevnatire transfer and the inevnatire count are displayed?

**Comment by Uzair-RepairDesk** [comment]
If you update on-hand inventory with inventory count, it will update it in Admin history with the reason of count. 
The system will automatically add the reason if a stock is adjusted from direct action. 
Hope it helps.

**Comment by JessicaSOS** [comment]
I am going to close this issue because you mention having made an improvement in this module. I am not sure this problem is really fixed. We will see in the future.
Thank you
