### ISSUE TITLE
Reorder levels are set but not showing up on low stock report

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#497]
My reorder levels are set but not showing up on low stock report.  All have 0 QOH but still not showing up

**Comment by Uzair-RepairDesk** [comment]
Hi @Trevorshaw7 
Thank you for sharing your concern. Can you please confirm if you have "Stock Warning" value set along with "Reorder Level" value?
Item comes up in "Low Stock Report" if the item "On Hand" value is equal or less than the "stock warning" value. 
Briefly, item comes up in the low stock report on the basis of both "Stock Warning" and "Reorder Level" value. 
Check screenshot from the low stock report for your understanding. Thanks

I hope it helps.  
![low stock report](https://user-images.githubusercontent.com/22955861/48046850-be228c00-e1b7-11e8-9970-735b19ce42a2.png)
