### ISSUE TITLE
Cancelled inventory transfers do not place inventory back into system

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#498]
![screen shot 2018-11-05 at 4 22 05 pm](https://user-images.githubusercontent.com/43588617/48033066-0b9aec80-e117-11e8-98b6-0f8fd4786fce.png)
If an inventory transfer is cancelled Where does the inventory go?

**Comment by Uzair-RepairDesk** [comment]
Hi @Trevorshaw7 
If you mark cancelled status before marking the status "Shipped", inventory item doesn't transfer and remain in the "On Hand" value of the same store. However, if you mark item shipped then it deducts from "On Hand" and stock value goes into the "In-Transit Report" i.e. a middle layer in inventory transfer.
 
If you mark the status "Cancelled" from the same store before receiving it to another store, the status of "Inventory Transferred" becomes "Cancelled" and "On Hand" value remains in the "In-Transit Report". 
You can access "In-Transit Report" under the inventory reports or from the following link:-
https://app.repairdesk.co/index.php?r=inventoryTransfer/inTransit

You can check screenshots attached for your understanding. Thanks
![uzairshah transferorderdetail inventorytransfer](https://user-images.githubusercontent.com/22955861/48048047-ed3afc80-e1bb-11e8-9f8f-cb4eb1045df4.png)
![uzairshah in transit inventory](https://user-images.githubusercontent.com/22955861/48048049-edd39300-e1bb-11e8-9994-264a7a3027ec.png)

**Comment by Trevorshaw7** [comment]
But how do you account for the inventory? I can see it goes on a report,
but how do you get it back into the transferring store? If it is cancelled
it should go back to the store in which it came from.

**Comment by Uzair-RepairDesk** [comment]
Hi, Thank you for your response @Trevorshaw7 
There are both cases for the cancelation. Most of the chances are that if its cancelled, it means you have lost the items in between the inventory transfer process. 

"However, we can certainly make an improvement in "Inventory Transit Report" that if transfer order is cancelled and items exist in "Transit Report", there should be an option to send adjustment and items should go back to the inventory"

I will discuss it with the team and see if we can prioritize to make this improvement.

**Comment by quangc** [comment]
Cancel means get stocks back to the original store not lost is common sense. How can Cancel is LOST? If Lost it should be Lost status.

**Comment by Uzair-RepairDesk** [comment]
Update: The document is completed for Inventory Transfer and Inventory Transit report and currently in design phase.
We will proceed with the development in the next week.

**Comment by Uzair-RepairDesk** [comment]
**Update:** We have completed development on this enhancement and it's expected to GO LIVE in our next release. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
This is to inform you that we have made this improvement LIVE. Now you can send inventory back to "On Hand" stock once you mark the cancelled status of "Inventory Transfer". You can also do the same from the "Inventory In-Transit Report". 
Please review improvement at your end and share your feedback. Thanks
