### ISSUE TITLE
Customer update (error in phone number)

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#499]
Whenever we want to update information in a customer's profile (name, address or other), an error appears regarding the phone number. Even though we have not made any changes to this level.
<img width="942" alt="customer update" src="https://user-images.githubusercontent.com/40500094/48074234-8236f900-e1ae-11e8-8cae-933fca8f4f19.png">

--
French:
A chaque fois que nous souhaitons mettre à jour une information dans le profil d'un client (son nom, son adresse ou autre), une erreur apparait concernant le numéro de téléphone. Même si nous n'avons fait aucune modification à ce niveau.

**Comment by usmanalikhan93** [comment]
Hey! 👋 @JessicaSOS ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Regards
Usman Ali Khan

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

We sincerely apologize for the inconvenience and we have released a fix for this issue. Can you please confirm if you are still getting the same issue?

**Comment by JessicaSOS** [comment]
Its actually seems to be corrected, thanks!
