### ISSUE TITLE
Inventory transfert modification

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#500]
I put item # 2336 and item # 2337 in an inventory transfer. Once the transfer was recorded, I physically went to the room of our inventory. Unfortunately, there was an error because the room was no longer physically available. So I changed the TO-2306 inventory transfer and removed item # 2337. However, item # 2337 did not recover. Yet, the transfer had just been created just 1 minute ago and it had not been accepted by the other shop.
<img width="944" alt="2337" src="https://user-images.githubusercontent.com/40500094/48153004-4033b300-e293-11e8-9dfb-b04abf351ba2.png">
<img width="938" alt="to-2306" src="https://user-images.githubusercontent.com/40500094/48153015-488bee00-e293-11e8-9351-22f02822f52c.png">

--
French:
J'ai mis l'item #2336 et l'item #2337 dans un transfert d'inventaire. Une fois le transfert enregistrer, je suis allé chercher physiquement la pièce de notre inventaire. Malheureusement, il y a eu une erreur, car la pièce n'était plus disponible physiquement. J'ai donc modifier le transfert d'inventaire TO-2306 et retirer l'item #2337. Cependant, l'item #2337 ne s’est pas remis en inventaire. Pourtant, le transfert venait d'être créé il y a 1 minutes à peine et il n'avait pas été accepter par l'autre boutique.

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS ,
Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

We have released a fix for inventory transfer and done some improvements in this module. Hopefully you will not get this issue in future. 

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
This problem is always present. You only have to test it to see it!
PLease reopen and fix it!

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sorry for the delay. Yes issue is present. Let me assign this to dev. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use
https://repairdesk.atlassian.net/browse/REP-983

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
We are not able to delete an item, a box is gray. By cons, we are now able to put it in canceled and there is an automatism in status that puts the piece in inventory. I tested it and all worked very well. Thank you !
