### ISSUE TITLE
"Invalid Mobile number"

### ISSUE THREAD

**Issue by 1TonyBA** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#501]
Disable "Invalid Mobile number" It will confuse employees when updating customer info because we know that the phone numbers are valid.[
<img width="1426" alt="screen shot 2018-11-07 at 12 54 11 pm" src="https://user-images.githubusercontent.com/44849184/48157367-a36e1700-e28c-11e8-82f7-02f221f865c1.png">
](url)

**Comment by usmanalikhan93** [comment]
Hey @1TonyBA  ,
Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hey @1TonyBA , 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Regards
Usman Ali khan

**Comment by usmanalikhan93** [comment]
Hi @1TonyBA 

We sincerely apologize for the inconvenience and we have released a fix for this issue. Can you please confirm if you are still getting the same issue?
