### ISSUE TITLE
Cost price problem in ticket

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#502]
The sale amount is displayed in the estimated profit without considering the cost price. Yet, the cost is in the room. In addition, the cost price is not displayed next to the coin.
<img width="944" alt="ticket l-10217" src="https://user-images.githubusercontent.com/40500094/48161456-919a6d00-e2a8-11e8-8134-81f92820ba2d.png">

<img width="930" alt="11138" src="https://user-images.githubusercontent.com/40500094/48161443-89423200-e2a8-11e8-95e3-470f6e30f122.png">

--
French:
Le montant de vente s'affiche dans le bénéfice estimé sans prendre considération du prix coutant. Pourtant, le prix coutant est bien dans la pièce. De plus, le prix coutant ne s'affiche pas côté de la pièce.

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS , 
Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by JessicaSOS** [comment]
Fixed, tnx !
