### ISSUE TITLE
Internal Wiki Doesn't Work

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#503]
I'm trying to test this out to see if we can use internal wiki however whenever I click on Internal Wiki I cannot enable it. It just refresh the page and nothing happens

![drphonefix](https://user-images.githubusercontent.com/21986026/48211890-495c7700-e39c-11e8-8776-63c21d2a68d4.jpeg)

Can you please check this and release a fix at your earliest convenience.

Reported By: Dr Phone Fix

**Comment by usmanalikhan93** [comment]
Hi @Repair-Desk  

Issue has been fixed.
