### ISSUE TITLE
Transaction not recorded as paid (but it printed a receipt)

### ISSUE THREAD

**Issue by jeffsand8243** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#504]
transaction was paid with cyan but was marked as not paid in rd even though it was processed and printed a receipt as paid for customer

**Comment by usmanalikhan93** [comment]
Hello Jeff,

I hope you are doing well. It would be highly apreciated if you kindly share the invoice number with a relevant screen shot or it will be better if you share the steps or video as well for better understanding. I have verified it at my end to produce it, but i were unable to produce it. It is working fine at my end.

Waiting for your kind response.

Regards,
Usman

**Comment by usmanalikhan93** [comment]
Hi again @jeffsand8243  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by jeffsand8243** [comment]
no, we are still having that issue!  i just don’t have time to be making videos of the issues

Thanks,
Jeff Sandridge
The Smartphone Medics
256-414-1199 <tel:256-414-1199>
www.TheSmartphoneMedics.com <http://www.thesmartphonemedics.com/>
 <>7449 Highway 72 W. Suite D Madison, AL 35758 <x-apple-data-detectors://2/2>


Locations

Madison (main location) - 
7449 Highway 72 <x-apple-data-detectors://5> between Nance Rd. and Jeff Rd. (Across from Hobby Lobby) 

(Hours) 10-6pm <x-apple-data-detectors://6> Weekdays,
  		 <>10-5pm  <x-apple-data-detectors://4> <>Saturday <x-apple-data-detectors://4>


Huntsville (drop off location) - 
University Drive (inside Boost Mobile)
(Hours)  <>11-7pm <x-apple-data-detectors://5>  <>Monday <x-apple-data-detectors://6> <>-  <x-apple-data-detectors://6> <>Saturday <x-apple-data-detectors://6>

**Comment by usmanalikhan93** [comment]
Hey @jeffsand8243 

Sorry for the inconvenience. Our support team will reach you and try to resolve your issue ASAP.
