### ISSUE TITLE
401 Error - WooCommerce not Syncing

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#505]
Woocommerce will not sync the below newly created products .

![image](https://user-images.githubusercontent.com/39751801/48333391-2ed31800-e692-11e8-8cd9-27acebac8d8f.png)

**Comment by usmanalikhan93** [comment]
Hi again @benjamingartner  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
