### ISSUE TITLE
Need ability to merge two different inventory items

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#506]
We sometimes have situations where there is more than one inventory item for a single product.

Example, someone adds "J7 2017 lcd (black) and another tech adds "J727 lcd (black)"

We may have 1 in stock at one location under one name, and 2 in stock at another location under the 2nd name.

We also consolidate cases once they are no longer a hot item. Originally we list them as "case x - black" and "case x - red" and after they are discontinued we like to combine them to just be "case x"

Obviously, this could be done manually and just delete/hide one of the items but that doesn't carry over stock/history/price/etc like it would if they could be merged.

On a merge, you should be given option to rename the "new" item and adjust other details as well on the "new" product

**Comment by Uzair-RepairDesk** [comment]
Hi @phonefixdfw 
I really appreciate that you took the time to share your idea.

With a small team and a big roadmap, our focus is to improve our existing features and reporting in this quarter. We have to pick new features based on the value they’ll add to the most users possible.
I have added a label "On-hold to consider" so we can discuss it and decided if we can add it in the roadmap for the next upcoming quarters. Thanks

Regards,
Uzair
