### ISSUE TITLE
Clickatell charging me crazy prices randomly

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#507]
I use clickatell integration with 2 way sms. I've always gone weeks without being recharged and suddenly a couple of days ago i started getting billed daily. Something is up and I think its how RD processes the texts.

Standard notificaitons are usually like 1 cent or less. 2 way is higher. However, im getting charged 2 way price for ticket auto notifications now when i never did before.

currently

![image](https://user-images.githubusercontent.com/37640713/48376148-a8b5d200-e68f-11e8-86f1-216021a57051.png)

just a couple days ago
![image](https://user-images.githubusercontent.com/37640713/48376180-bd926580-e68f-11e8-8e84-d9186e48b785.png)

these are the same type ticket alerts but are being handled totally different on their end and billing me insane amounts.

Did something change on RD end or clickatell end? Can we make ticket alerts and such only use the regular API that is cheap and only use 2 way if its a customer message?

**Comment by usmanalikhan93** [comment]
Hey @phonefixdfw ,
There is an issue with the Clickatell side. Please disable it and use their standard notification instead of two way. Please contact Clickatell team to help or sort out your issue.

Hope for answer the question.

Feel free to contact us any time. 

Thanks,
Usman

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Usman Ali
