### ISSUE TITLE
bugs within daily sales reports 

### ISSUE THREAD

**Issue by Cumbr1at3ch** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#510]
.githubusercontent.com/40138325/48557984-fde82280-e8df-11e8-86c1-fbdbdec2913d.png)
![image](https://user-images.githubusercontent.com/40138325/48557991-02acd680-e8e0-11e8-99ce-d76c96f56e04.png)
error within the location dalily sales - the costs are all wrong, The

**Comment by usmanalikhan93** [comment]
Hey @Cumbr1at3ch , 
Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @Cumbr1at3ch 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @Cumbr1at3ch   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
