### ISSUE TITLE
Self checkin bugs and improvements

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#511]
Can we please have ability to change top text? If not, at minimum, can the extra <br> be removed to save a line of space.
![image](https://user-images.githubusercontent.com/37640713/48676205-26169200-eb29-11e8-981c-3fbb306ba25d.png)

Options for this page include:
Hide Device info fields  
Customer email is mandatory  
Hide Network Field  
Hide IMEI Field  
Make How did you find us, (Mandatory) 

Can we add options to hide "how did you hear about us"? 

Ability to not require "check here to agree to conditions" would be nice too. Its small and people miss it on first try. By signing, that should be them agreeing. No point in the check. Make it optional at least

after opening the checkin with POS, there are some bugs and issue.
![image](https://user-images.githubusercontent.com/37640713/48676238-958c8180-eb29-11e8-8a60-ca369af9ccfe.png)
-the imei field is not able to be used. You have to change it to serial then back to imei.
-can manufacture, device and problem be added on a page before, rather than further down this page?
-order should be manufacture, device, problem (right now its manufacture, problem, device) you cant pick a problem until you pick a device so common sense says that should be in order.

**Comment by phonefixdfw** [comment]
![image](https://user-images.githubusercontent.com/37640713/48676271-fd42cc80-eb29-11e8-99a4-91afea4b9b1e.png)

**Comment by phonefixdfw** [comment]
Additionally any ability to alter format would be amazing. Could we do a template like email notifications have? The page looks awful currently and isn't formatted well to use all available space

**Comment by usmanalikhan93** [comment]
Hey @phonefixdfw ! 
Thank you for bringing this to our attention! Let me forward this to our Product Manager and he will look into it. 
@Uzair-RepairDesk can you look into this ?

**Comment by Uzair-RepairDesk** [comment]
This one is also listed on the Facebook user group. 
@usmanalikhan93 
Please check my comments there and please review it. Thanks

**Comment by usmanalikhan93** [comment]
Hey @phonefixdfw  
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
