### ISSUE TITLE
Inventory Transfert SOS Phone Sainte-Foy

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#512]
My store employee in Sainte-Foy is not able to perform an inventory transfer. She only has the option to transfer to her own store. No changes have been made. On my side it works, maybe because I'm an admin? See Attachment.
![ste-foy transfert](https://user-images.githubusercontent.com/40500094/48721434-e6ff4400-ebef-11e8-91f0-46f1004781f9.png)

--
french:
Mon employé du magasin de Sainte-Foy n'est pas capable d'effectuer un transfert d'inventaire. Elle a seulement la possibilité de transféré dans son propre magasin. Aucune modification n'a été faite. De mon côté ça fonctionne, peut-être parce que je suis un admin? Voir pièce jointe.

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

It may be due to she has no access to other stores. Can you check in Manage Employees in settings ?

**Comment by JessicaSOS** [comment]
She has access only to her store (and no question of giving access to all stores to all employees) but, she can not even transfer parts to us. It was not like that some day ago ...

**Comment by JessicaSOS** [comment]
The problem is that all employees have access only to their store. Whether in **inventory transfers** or in the **inventory summary**. It should be corrected quickly, because it is really not very practical.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

There is improvements done in Employee section. Now Employee can access only to those store which have access to them. E.g. to see the reports, employee should have access to that store. 

But for transfer inventory it should display all stores regardless of store permission. 
Let me assign this development team to fix this ASAP. 

Usman Ali.

**Comment by JessicaSOS** [comment]
I expect from you quickly, because it is a real problem now. As much in the summary report as in the transfer of inventory.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

If employee wants to see other store inventory summary report, he/she should have access to that store. 

Thanks!

**Comment by JessicaSOS** [comment]
You have closed this task, however, the Inventory Summary report is not corrected. Thank you for reopening this task.

**Comment by JessicaSOS** [comment]
You have closed this task, however, the Inventory Summary report is not corrected. Thank you for reopening this task.

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 3 décembre 2018 00:17
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Inventory Transfert SOS Phone Sainte-Foy (#512)

 

Closed #512 <https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/512> .

**Comment by Uzair-RepairDesk** [comment]
Hi @JessicaSOS 
We have already fixed the stores issue in Inventory Transfer. Your employee will be able to transfer it to any specific store. Please verify the fix at your end. 
However, employees will be able to view only those stores in search filter of reports where they have access to those stores. 
It's important to make this validation that if any specific employee doesn't have access to a store, he/she should also not able to view that specific store in reports. Admin/Super Admin can view all the stores in search filter though. 
I hope I am able to answer your question.

**Comment by JessicaSOS** [comment]
The report is a summary of all stores. Can you stop changing things that work correctly please. I would like you to correct it as it was before so that an employee can inform his client if a piece is available in another shop.

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 29 novembre 2018 06:31
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Inventory Transfert SOS Phone Sainte-Foy (#512)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

If employee wants to see other store inventory summary report, he/she should have access to that store.

Thanks!

**Comment by JessicaSOS** [comment]
The report is a summary of all stores. Can you stop changing things that work correctly please. I would like you to correct it as it was before so that an employee can inform his client if a piece is available in another shop.

**Comment by JessicaSOS** [comment]
I do not want to give full access to all the stores just to see the inventory. I understand your point but I do not want to give access to all the employees at all the shops, otherwise it is useless to have any restrictions.

 

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Muhammad Uzair Shah <notifications@github.com> 
Envoyé : 4 décembre 2018 00:01
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Inventory Transfert SOS Phone Sainte-Foy (#512)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 
We have already fixed the stores issue in Inventory Transfer. Your employee will be able to transfer it to any specific store. Please verify the fix at your end.
However, employees will be able to view only those stores in search filter of reports where they have access to those stores.
It's important to make this validation that if any specific employee doesn't have access to a store, he/she should also not able to view that specific store in reports. Admin/Super Admin can view all the stores in search filter though.
I hope I am able to answer your question.
