### ISSUE TITLE
Warranty Claim Issue | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#513]
Hi Sir,

**Business Name / Store Name:**
Modesto | DrPhone Fix

**Customer Credentials:** 
Shared via Skype

**OS: Windows / MacBook**
Module: Warranty Claim for Repair Part
Configuration Setting: Correct
Roles & Permissions: Correct

**Issue:** 
Warranty Claim for Repair Parts not working in case of Lifetime.

**Steps to Reproduce Issue/Provide Video:**
1. Go to **Store Settings >> Module Configurations >> Inventory**
2. Set **Default Warranty Period for Inventory Items** as **LifeTime** Also make sure that **Warranty and Warranty Time Frame Fields are empty** so that Default Warranty is taken up by system.
3. Book a **repair job** and add a **part**.
4. Checkout the ticket with complete payment and change status of ticket as Repaired and Collected.
5. Go to POS window again and click on **Warranty Claim**.
6. Enter the **ticket ID**.
7. You will **not** be able to find warranty claim option against the part.

**Current Results:** 
No option for Warranty Claim

**Expected Result:** 
It should give option of Warranty Claim as warranty has been set as Lifetime.

**Comment by ali-repairdesk** [comment]
This issue was fixed however customer still facing issue:
https://repairdesk.atlassian.net/browse/REP-730

**Comment by hamzaakbar4444** [comment]
Hey!
This issue is already open and Developer is working on it.

Thanks..

**Comment by ali-repairdesk** [comment]
Jira task link:
https://repairdesk.atlassian.net/browse/REP-842

Issue will be fixed on Live by end of this week.

**Comment by ali-repairdesk** [comment]
Issue has been fixed.

Waiting for feedback.
