### ISSUE TITLE
Inventory Reconciled Report - Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#515]
**Hi Sir,**

**Business Name / Store Name:**
Modesto | DrPhone Fix [40 Store Locations and looking to SignUp soon]

**Module:** Inventory Count

**Feature Request:** 
Customer has come up with a request that: 
IF there is any way to see an Inventory Reconciled Report [PDF] something they can print that shows the inventory changes by actually listing the items. Customer has given an example with a screenshot. 
[Screenshot Attached]

**Current Results:** 
If an Inventory Count has been done, there is no proper report for that.

**Expected Result:** 
A dedicated report should be there.

**Source:**
WhatsApp

**Comment by ali-repairdesk** [comment]
![inventory reconciliation](https://user-images.githubusercontent.com/26381305/48802783-09997600-ed32-11e8-81f7-3577944c7590.jpg)

**Comment by Uzair-RepairDesk** [comment]
We have certainly an option to download PDF of "Inventory Count" activity. 
You can go to **Inventory Count > Export PDF** for each inventory count. 
![uzairshah manage inventory count](https://user-images.githubusercontent.com/22955861/49060727-9364aa00-f230-11e8-83cd-c8bb7de26c8b.png)

**Comment by ali-repairdesk** [comment]
We are already working on its improvements,

https://repairdesk.atlassian.net/browse/REP-912

Thanks,

**Comment by ali-repairdesk** [comment]
This improvement has gone Live.

Customer will verify this and share an update. We can close this ticket for now.

**Comment by Uzair-RepairDesk** [comment]
@ali-repairdesk 
Please update?

**Comment by ali-repairdesk** [comment]
Please close this ticket. Customer has already been updated on this.
