### ISSUE TITLE
Inventory Count Not Saving - Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#516]
**Hi Sir,**

**Business Name / Store Name:**
Modesto | DrPhone Fix

**Customer Credentials:**
Shared via Skype

OS: Windows / MacBook
Module: Inventory Count
Configuration Setting: Correct
Roles & Permissions: Correct

**Issue:**
Once doing Inventory count, It was completed hit save and entire record disappeared :(

**Steps to Reproduce Issue/Provide Video:**
Customer is suspecting that issue comes up once we are doing Inventory Count at the same time on multi store locations.
We (Support Team) are unable to trace this issue.
We have asked Modesto to share some more steps so that we can try reproducing the issue. This is the video customer shared:
https://drive.google.com/file/d/1WkONh-WeX2ZMpWzZnvJrqlC02B9boXjT/view?usp=sharing

**Current Results:**
Inventory count not getting saved.

**Expected Result:**
Inventory count should be saved properly.

**Comment by hamzaakbar4444** [comment]
Hey!
Dear Ali, i have verified this issue at my end and it is working fine. When i review your video, you can see that you are not reviewing the item with the same id. e.g. when you first update the count, id of item were 2921 and after that the item at which you display the count is 0 the id of that item were 2502. It is your understanding issue.

Hope the answer the question. If you need anything else, feel free to ask any query. 
Thanks

**Comment by ali-repairdesk** [comment]
I have updated customer on it and trying to get the exact steps.

The moment I have an update, I will let you know.

**Comment by usmanalikhan93** [comment]
@ali-repairdesk 

Any update on this issue ?

**Comment by ali-repairdesk** [comment]
We are trying ti figure out the scenario and for 1 scenario we have created a task and its on Beta. I will keep you posted on this piece.

https://repairdesk.atlassian.net/browse/REP-897

Thanks,

**Comment by usmanalikhan93** [comment]
Hi @ali-repairdesk 

Reported issue has been fixed. Please ask customer to verify on his end.
