### ISSUE TITLE
Last modified date not updated when ticket created via customer portal

### ISSUE THREAD

**Issue by afrahm** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#518]
When a customer logs in to the portal and creates a ticket themselves the last modified date is set as 1970
<img width="589" alt="screen shot 2018-11-23 at 8 19 39 am" src="https://user-images.githubusercontent.com/1414304/48923269-e53bc600-eef8-11e8-9087-d919038391e4.png">

**Comment by usmanalikhan93** [comment]
Hey @afrahm  , 
Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hey @afrahm 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @afrahm 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
