### ISSUE TITLE
Customer from woo commerce

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#520]
Can not find a customer who has purchased via woo commerce. No results are displayed. We had this problem in the past and it was corrected. Here he is again.

--
french:
Impossible de rechercher un client qui a acheter via woo commerce. Aucun résultat n'affiche. Nous avions déjà eu ce problème dans le passé et il avait été corrigé. Le voilà à nouveau.

**Comment by Uzair-RepairDesk** [comment]
I believe it shows reference of an Online transaction on the Invoice view page. 
@usmanalikhan93 
Can you check this?

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you share the woo commerce order id against you were searching ?

**Comment by JessicaSOS** [comment]
http://sosphone.ca/wp-admin/user-new.php
User : jeandavid
Pass : sosphone123
* please do not make any changes or modifications. *

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have removed your last comment as it is a public. So everyone can see this.

**Comment by JessicaSOS** [comment]
I do not know how to put a private comment. Thank you !!!!

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked in your account and in manage invoices if we select "View all WooCommerce", it displays all woocommerce invoices. And it does have customer info too.

**Comment by JessicaSOS** [comment]
#520 is fixed !

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 17 décembre 2018 02:54
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Customer from woo commerce (#520)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

I have checked in your account and in manage invoices if we select "View all WooCommerce", it displays all woocommerce invoices. And it does have customer info too.
