### ISSUE TITLE
Make Compulsory While Booking a Repair Job - Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#521]
**Hi Sir,**

**Business Name / Store Name:**
Modesto | DrPhone Fix [40 Store Locations and looking to SignUp soon]

**Module:**
Repair Ticket

**Improvement:**
Customer has come up with a request that:
Once we are booking a repair ticket, just the way there is an option to make compulsory Pre Repair Conditions, there must be an option to make compulsory:
1. Pattern/Passcode
2. Physical Location
3. Device Network.

**Current Results:**
No trigger to make compulsory the above 3 points.

**Expected Result:**
We can add a trigger to make compulsory:
1. Pattern/Passcode
2. Physical Location
3. Device Network.

**Source:**
WhatsApp

**Comment by Uzair-RepairDesk** [comment]
@ali-repairdesk 
Thank you for the request. What is the priority for this improvement?

**Comment by ali-repairdesk** [comment]
Since customer has Signed Up now, so we will be doing this enhancement soon. 

In my opinion the priority needs to be Medium however Usman will be dropping an email to Modesto about the changes that needs to be done.

So I will keep you posted on this piece.

**Comment by Uzair-RepairDesk** [comment]
@ali-repairdesk 
Its already logged on JIRA and story document is scheduled in this week:-
Task Reference: 
https://repairdesk.atlassian.net/browse/REP-927

**Comment by ali-repairdesk** [comment]
Thanks for the update.

Appreciate that.

**Comment by Uzair-RepairDesk** [comment]
We have gone live with the above improvement. Please review and update the customer. @ali-repairdesk

**Comment by ali-repairdesk** [comment]
Thanks, Customer has been updated as well.
