### ISSUE TITLE
Option To Select Date Format - Trevor

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#524]
Is there a way to change the date format? We would like it where the month displays first instead of the day  (11 / 28 / 2018)

**Comment by Uzair-RepairDesk** [comment]
**Backlog task initiated again.**
Task reference for internal use of RepairDesk:-
https://repairdesk.atlassian.net/browse/REP-90

**Comment by fahadimran303** [comment]
@Uzair-RepairDesk Jose from iTech Connection also wants US Date Format in Reports.
