### ISSUE TITLE
Option to View All Stores On Inventory Transfer - Trevor

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#525]
On inventory transfers the logic doesnt make sense. We have employees locked to stores and when they need to to transfer inventory from their store they can not select their store as the from store.

![46831067_327835657803369_2575219183310602240_n](https://user-images.githubusercontent.com/21986026/49134585-de9cbc80-f305-11e8-8d49-4fe06eb145b1.jpg)

**Comment by Uzair-RepairDesk** [comment]
This issue has been fixed and verified on Beta. Task reference:-
https://repairdesk.atlassian.net/browse/REP-832
It will be live in the upcoming release
