### ISSUE TITLE
Estimates say convert to invoice instead of convert to ticket - Trevor

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#527]
When we create an estimate of "Repairs", Why do some record says "Convert to invoice" and some says "convert to ticket".
Check screenshot attached.

If there are repair services, the system should ask to "Convert to Ticket".

I have converted all of them to the ticket after the screenshot but now few estimates say to "View Ticket" but they open "View Invoice". 

RepairDesk Task Reference (Internal Use)
https://repairdesk.atlassian.net/browse/REP-868

![bad apple pos](https://user-images.githubusercontent.com/22955861/49281439-61f91200-f4ae-11e8-9031-9a82b2762cc1.png)
![47319717_263340594355794_4228240525175554048_n](https://user-images.githubusercontent.com/22955861/49281441-6291a880-f4ae-11e8-8627-5f7d9f11f553.jpg)

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk 

Issue has been fixed.

**Comment by Uzair-RepairDesk** [comment]
I have informed to Trevor in my last email.
