### ISSUE TITLE
Please make Multi Store report a Role permission - Trevor

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#528]
Please make Multi Store report a Role permission

**Comment by Uzair-RepairDesk** [comment]
@Trevorshaw7
We have added comprehensive reports permissions under "Employees Roles Permissions" 
It's highly recommended to update permissions for each employee role. 
You can do it by following given steps:-

**Store Settings > Employees > Roles Permissions > Select Role > Update Reports Permissions > Save Changes**
