### ISSUE TITLE
Register Sales Report Issue with Refunds - Trevor

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#529]
When you view register sales on the line that has the refund, it doesn't show a negative in the Paid column, and if you add up the sales manually it is off by the 8.22 that is 
misrepresenting the value for the refund

RepairDesk Task Reference (Internal Use Only)
https://repairdesk.atlassian.net/browse/REP-882

**Comment by usmanalikhan93** [comment]
Hi @Uzair-RepairDesk 

Reported issue has been fixed.
