### ISSUE TITLE
Default Repair Time Set

### ISSUE THREAD

**Issue by faizanzaheer** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#530]
Hi Sir,

Business Name / Store Name:
Sajid Abubaker | Capital Connection (London) Limited

Module:
Point Of Sale

Improvement:
Customer has come up with a request that:
Once we are booking a repair ticket, there is no option to set the time by default according to his will as it shows with an hour difference already by default:

Expected Result:
We can add a function to make Task Due Date & Time set as default as shown in the picture:

Source:
https://app.intercom.io/a/apps/mq09yl4f/inbox/inbox/2313392/conversations/19821631964

![smartphones pos](https://user-images.githubusercontent.com/34411411/49406384-3492b980-f777-11e8-887b-13ee5cddb8a8.png)

**Comment by Uzair-RepairDesk** [comment]
We have the option to set "Due Date & Time" for repairs. You can go to Store Settings > Module Configurations > Repairs > Set due date & time for repairs

![uzairshah_Repairs_Config1](https://user-images.githubusercontent.com/22955861/81291122-ae248a80-9082-11ea-81d4-f8bdca74004d.png)
