### ISSUE TITLE
The inventory does not adjust correctly against invoices

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#531]
The invoice which is created manually in the invoice section will make the system adjust inventory incorrectly. If create using POS then it is working fine.

Please investigate by creating invoice manually and put in 5 items, the system will only deduct 1 and it always 1, does not matter how many item inside the invoice.

If Check out in the POS then it adjust the inventory correctly.

MASSIVE BUG.

**Comment by usmanalikhan93** [comment]
Hi @quangc 
Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @quangc 

I hope you are doing well. I just want to know that are you facing this issue ? If yes, can you identify the steps you are doing when you face this issue. 
I have tried on my end with multiple scenarios but quantity deducts accurately.

**Comment by quangc** [comment]
Yes, the issue is not fixed. But it is very intermittent.

Best Regards,
Quang Cao.
General Manager.
+ Repair Centre Frankston
+ Repair Centre Springvale
+ Repair Partners
P: 1300 89 82 99
A : Shop 6 Shannon Street Mall, Frankston, Vic, 3199.

**Comment by quangc** [comment]
When this URGENT matter will be looked at and fix?

**Comment by usmanalikhan93** [comment]
Hi @quangc 

We are trying to replicate on our end but it didn't reproduce. Once we have a use case for this, we will resolve this ASAP.

**Comment by quangc** [comment]
Who did this into our system? This is not a proper fix to my opinion.
![screen shot 2019-01-04 at 3 52 05 pm](https://user-images.githubusercontent.com/22993605/50674289-e9e7b400-1038-11e9-8194-7d6e377ffef4.png)

**Comment by quangc** [comment]
This is very patchy fix, and they only fix from the date we reported. How about those previous days?

**Comment by usmanalikhan93** [comment]
Hi @quangc 

Did you check employee activity report ?
