### ISSUE TITLE
Bug on purchase order settings page

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#533]
![image](https://user-images.githubusercontent.com/37640713/49627822-a3a22500-f9a6-11e8-8deb-c533565c5c9a.png)
shows 82 results and 6 pages of pagination even though its only the 7 default status' and one page

**Comment by usmanalikhan93** [comment]
Hey @phonefixdfw 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up . 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
