### ISSUE TITLE
tickets do not auto create invoice

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#534]
![image](https://user-images.githubusercontent.com/37640713/49628117-f3cdb700-f9a7-11e8-8c27-5a445c36065d.png)

i have this option unchecked, but when going through POS and making a ticket, it does not create an invoice. Once i edit a ticket, it does ask if i want to create an invoice, and I can or can cancel... 

Is this normal? Or should it create invoice as soon as the ticket is made?

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

Thank you for highlighting your concern. Actually this trigger is referred to when you create ticket from "Manage Tickets" section. Please check this video, it will help you to understand.

**Comment by Uzair-RepairDesk** [comment]
Hi @phonefixdfw 
I just got a chance to check your post. Currently, there is no option to auto-create invoice from POS when you hit "Create Ticket". 
If you want to create an invoice along with the ticket, you can simply click on checkout enter the payment details if required or simply click "Confirm" for "Unpaid Invoice". 
There is already flexibility on POS to create an invoice along with the ticket so currently, we cannot make this option available with "Create Ticket" only.

**Comment by rajeshdungrani** [comment]
Hi @Uzair-RepairDesk 
Since you already have the feature in Manage Ticket section, I would also like to have auto create function enabled from POS section. The solution you mentioned is a work around, which we can use till you enable that functionality. Workaround cannot be permanent solution.
