### ISSUE TITLE
2 way sms (clickatell) suggestions for alerts

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#536]
![image](https://user-images.githubusercontent.com/37640713/49628264-ca615b00-f9a8-11e8-9575-2f6177d4dc9f.png)

alerts settings for 2 way clickatell sms only allow alerts to be set on employees that have that location as a default. Not their default store? They wont see sms alerts. Would be best to do it by store not employee. 

Also, maybe an sms flag for unread messages on ticket queue
![image](https://user-images.githubusercontent.com/37640713/49628302-101e2380-f9a9-11e8-9000-f3b3dd2f2166.png)

also posted some info about 2 way not working in response to some sms notifications on FB post

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 can you please check this?

**Comment by phonefixdfw** [comment]
not to confuse, but lead pop up notification works in the same way

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

I hope you are doing well. I have discussed this with developer and he said, for now we cannot do it store wise as it may cause problem in existing functionality. And for point 2 regarding flag, he said, Clickatell does not send us any response like Sendgrid send response for our emails tracking, So it is not possible to that. 

Thanks
Usman Ali.
