### ISSUE TITLE
a few of issue

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#538]
im facing few issue in ipad app:
1-When the customer pays some of the price of the repair in the ticket does not appear when the full amount is paid as previously paid, but it is possible to pay for more than once and does not appear as in the web program
2-casual-section items are not available in the program
3 It automatically closes the program several times a day
4-The program displays invoices randomly and is not ordered by date
5- When you checkout the ticket and pay for an undefined ticket price = 0 and you set the price you see a jan error

**Comment by usmanalikhan93** [comment]
Hey @hitman1986 ,

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope our support guy Danish has guided you with this and you are all set now. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
