### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#539]
Hello When I print the ticket label with the Google printer, the printed printer is printed vertically but when I print it normally, the computer appears correctly. Why?

**Comment by usmanalikhan93** [comment]
Hey @hitman1986 , 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope our support guy Danish has guided you with this and you are all set now. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
