### ISSUE TITLE
Option to quickly View Repair Services Prices on POS Window | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#540]
**Hi Sir,**

**Business Name / Store Name:**
Modesto | DrPhone Fix

**Module:**
POS

**Improvement:**
Customer has come up with a request that:

**In order to quickly view Repair Services Pricing, there is no quick method.** 

Just the way we have a search bar for Items, Can we have the same thing for Repair Services as well?

**Current Result:**
In order to view Prices for Repairs, Currently there is only 2 ways:
1) From POS screen by going to Repairs
2) Inventory >> Manage Services >> Repairs

**Expected Result:**
Just the way we have search bar for Inventory Items, There must be a quick way for seeing Repairs File

**Source:**
WhatsApp

**Comment by Uzair-RepairDesk** [comment]
We have already an option to search repair service from POS and you can see the price as well. Did you tell the customer about this option?
**Check screenshot attached**
![repair search](https://user-images.githubusercontent.com/22955861/49994002-19f7e600-ffaa-11e8-9d5d-982a852f7078.png)

**Comment by ali-repairdesk** [comment]
Thanks Sir,

Customer was updated accordingly. We can close this ticket.
