### ISSUE TITLE
Select Part Compulsory on POS Window | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#541]
**Hi Sir,**

**Business Name / Store Name:**
Modesto | DrPhone Fix

**Module:**
POS

**Improvement:**
Customer has come up with a request that:

His employees often forget to select Parts,

I have told him to use Bundled Parts option. He has agreed for now however he is still looking for a trigger that can make Selecting Part mandatory.

**Current Result:**
We can book Repair Ticket without selecting the Part as well.

**Expected Result:**
There must be a trigger that will make sure that Repair Ticket is not booked until the part is selected.

**Source:**
WhatsApp

**Comment by Uzair-RepairDesk** [comment]
What is priority for this improvement @ali-repairdesk ?

**Comment by ali-repairdesk** [comment]
For now, Customer is using the feature of Bundled Parts.

However since by end of Jan, he will be on-boarding almost 10-15 Stores so I will request if we can have this feature added by end of Jan.

Please share your thoughts on this.

Thanks,

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk @ali-repairdesk Another idea for this, we might not need to make it mandatory, but maybe a pop up saying you forgot to add a part this this repair, and maybe two buttons on pop up - **Add Part** or **Continue** this way it wont cause issues on services that do not need a part

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk @usmanalikhan93  you guys can close this task
