### ISSUE TITLE
appointment leads not showing on calendar

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#545]
made a test lead with appointment calendar, approved the lead... but shows nothing on calendar view
![image](https://user-images.githubusercontent.com/37640713/49835285-5803c880-fd64-11e8-84ff-1c446a80e91f.png)
![image](https://user-images.githubusercontent.com/37640713/49835348-841f4980-fd64-11e8-9530-5d734deb5895.png)

![image](https://user-images.githubusercontent.com/37640713/49835367-91d4cf00-fd64-11e8-863e-5455744f2312.png)

**Comment by phonefixdfw** [comment]
it would be great if there was a menu item at top, similar to notifications, that you could click and see upcoming appointments

**Comment by phonefixdfw** [comment]
and yes, I understand if i convert it to a ticket that it then shows on calendar... but an appointment shouldn't be a ticket until they show up. And it should be on the calendar as an appointment/lead so store can plan on them showing up, then convert to a ticket upon arrival.

**Comment by Uzair-RepairDesk** [comment]
Hi Brendon @phonefixdfw ,
Thank you for your post. We have already worked on "Dispatch Module" phase 1 that allows you to view "All Tickets and Appointments (Leads)" on a single calendar page. It allows "One Window Operation". 
Please check the screenshot attached. 

Its available for our few customers for beta testing. We have a plan to deploy it on live for all in a couple of weeks. 
If you want to get early access, I can make it active on your account with the help of the development team. If you are interested, you can provide me your account id/ account credentials in private message or email me at uzair@repairdesk.co 

Regards,
=Uzair=
![dispatch](https://user-images.githubusercontent.com/22955861/49851285-74564280-fe02-11e8-9d00-69da94953879.png)

**Comment by phonefixdfw** [comment]
yes, id love to try it out

**Comment by Uzair-RepairDesk** [comment]
Can you share your account details at uzair@repairdesk.co
Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi Brandon @phonefixdfw 
We have activated "Dispatch" module on your account. 
Please note that our current dispatch module is in BETA. It allows you to view "All Tickets and Appointments (Leads)" on a single calendar page. It allows "One Window Operation".

You can review at your end and share your feedback. Thanks

**Comment by phonefixdfw** [comment]
Will test more, things I see now

- when booking an appointment with lead approval on, customer gets a text
and email. When the lead is approved they get another email confirming, but
no text. Text here is super important to confirm.

-the format on calendar of appointment looks weird. This screen shot
attached is mobile phone but looked same on laptop before it died on me.

-will look at it further and test more

9034 Garland Rd, Dallas 75218
4321 Lemmon Ave, Dallas 75219
7340 Highway 78, Suite 260, Sachse 75048
972-587-7433 <https://mail.google.com/mail/u/0/> | www.phone-fix.com
