### ISSUE TITLE
All Invoice are disappear * *

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#546]
All the bills are gone! It's as if the customers had made tickets but we would never have made an invoice. For the client attached, I saw bills last night paid and unpaid. Poutant, there is no bill this morning! It's like that for all customers! Corrected quickly please !!!
<img width="946" alt="invoice disapear" src="https://user-images.githubusercontent.com/40500094/49885812-30fdd300-fe06-11e8-8381-c668e525571c.png">

--
french:
Toutes les factures sont disparu! C'est comme si le clients avait fait des billets mais que nous n'aurions jamais fait de facture. Pour le client en pièce jointe, j'ai vu des factures hier soir en payé et en non payé. Poutant, il n'existe aucune facture ce matin ! C'est comme ça pour tous les clients ! À corrigé rapidement svp !!!

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Thank you for bringing this to our attention. We have released a hotfix for this. Now it's been resolved. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
Fixed tnx !
