### ISSUE TITLE
IP address Dis-Functionality in case of Switch User | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#548]
**Hi Sir,**

**Business Name / Store Name:**
Modesto | DrPhone Fix

**Module:**
Manage Employee Section

Configuration Setting: Correct
Roles & Permissions: Correct

**Issue:**
IP address Dis-Functionality in case of Switch User

**Steps to Reproduce Issue/Provide Video:**
1. Go to **Store Settings >> Employees >> Manage Employees**
2. Against **Employee Irtiza**, go to **Action >> Edit**
3. In **IP WhiteList**, enter the IP address of the machine [PC] you are using at the moment and hit on Save.
4. Now on a different machine login with "Admin" account and please **Switch User**.
5. Select **Employee Name as Irtiza** and enter **Access Pin=1234**
6. Once we do that, it will give access to use the software with Employee Irtiza despite the fact that the IP address of this machine is not whitelisted. 

**Current Results:**
Once we switch user from an IP address not whitelisted, Employee can use the software.

**Expected Result:**
If the IP address is not whitelisted, Employee must not be able to use the software.

**Comment by usmanalikhan93** [comment]
Hey @ali-repairdesk  
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

**Comment by usmanalikhan93** [comment]
Hi @ali-repairdesk 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
