### ISSUE TITLE
WooCommerce - Status not changed for "sold"

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#550]
Hello,
I was looking for a phone that was "in stock", but that I did not have physically. Item # 11008. I have been searching for really long time. Still, it was sold online November 30, 2018. It was shipped and correctly registered as "finished" in the WooCommerce, but the sales status did not change to "sold". Normally, the status changes correctly.

Cepedant, the same thing is produced with item # 11669. It was sold online on December 16, 2018, but the status has not changed for "sold". He stayed in "in stock".

No modification was made to my side in the Woo Commerce settings. Can you look at this problem please. This is not present for all online sales, it seems to be an intermittent problem ...

--
French:
Bonjour,
Je cherchais un téléphone qui était "in stock", mais que je n'avais physiquement pas. L'item #11008. Je l'ai chercher pendant vraiment très longtemps. Pourtant, il a été vendu en ligne le 30 novembre 2018. Il a été expédié et correctement inscrit comme "terminé" dans le WooCommerce, mais le statut de vente n'a pas changé pour "sold". Normalement, le status se change correctement. 

Cepedant, la même chose c'est produit avec l'item #11669. Il a été vendu en ligne le 16 décembre 2018, mais le statut n'a pas changé pour "sold". Il est resté en "in stock". 

Aucune modifiaction n'a été faite de mon côté dans les réglages de Woo commerce. Pouvez-vous regarder ce problème svp. Ce n'est pas présent pour toutes les ventes en lignes, il semble être un problème intermittent...

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS  , 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS just want to confirm whether you are still facing this issue or not ?

**Comment by JessicaSOS** [comment]
I do not think I had this problem again and I have no idea what might have caused this. I'll let you know if it happens again.
