### ISSUE TITLE
Follow up widget texte problem

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#551]
Hello,
Before, we could see the texts of the translation widget (see image). Now nothing is displayed ... (see picture)
Before: 
![suivibilletlongueuil](https://user-images.githubusercontent.com/40500094/50184275-952b0600-02e2-11e9-8e28-fdefb1bfa713.png)
After:
<img width="943" alt="follow up widget" src="https://user-images.githubusercontent.com/40500094/50184289-a542e580-02e2-11e9-834a-f001d92b8bcb.png">

--
french:
Bonjour,
Avant, nous pouvions voir les textes du widget de traduction (voir image). Maintenant, rien ne s'affiche... (voir image)

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS , 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by JessicaSOS** [comment]
This is actually fixed with the detail you mention to me.
Thank you
