### ISSUE TITLE
Inventory Transfer - Display Total Cost

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#552]
It would be great to view total cost on inventory transfer.

Bad Apple

![inventory transfer improvements](https://user-images.githubusercontent.com/21986026/50213381-4db67f80-039f-11e9-9985-9f828e15a129.jpg)

**Comment by Uzair-RepairDesk** [comment]
We have added a "Total Cost" field on "Inventory Transfer" listing page so you can see the "Cost Value" of transferred inventory.
