### ISSUE TITLE
GST Calculation Wrong

### ISSUE THREAD

**Issue by quangc** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#555]
I have recorded into a video file but cannot upload in here.

**Comment by usmanalikhan93** [comment]
Hey @quangc , 
Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @quangc 

I have reviewed your concern on my test account, GST is calculating correctly on PO in case of inclusive. Can you share more info on this ?

**Comment by quangc** [comment]
When you added one item with GST inclusive options, the system will work out the GST wrong. I will take another video shots here for you to see.

**Comment by usmanalikhan93** [comment]
Can you share the video ?

**Comment by quangc** [comment]
Did you try in the Purchase Order area?

**Comment by quangc** [comment]
Just checked again now, all working fine. Someone must fixed it.

**Comment by usmanalikhan93** [comment]
Thanks for the update.
