### ISSUE TITLE
Enter Access PIn To Create Ticket & Invoice Trigger - POS

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#556]
When customer facing display is switched on enter access pin pop up doesn't display before a repair ticket or invoice is created.

In case of customer facing display is switched on "the pop up should display before customer facing display"

Bad Apple

**Comment by Repair-Desk** [comment]
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. I'm gonna reach out to our Engineers to get this taken care of.

We will try to get this issue resolved tonight or by Monday.

**Comment by usmanalikhan93** [comment]
Hi @Repair-Desk 

I have assigned this to development team. Hopefully it will be fixed in the end of this week. 

For internal use:
https://repairdesk.atlassian.net/browse/REP-1034

**Comment by usmanalikhan93** [comment]
Hi @Repair-Desk 

Reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
