### ISSUE TITLE
Inventory Summary - Export Excel, PDF Not Working

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#558]
When you try to export inventory summary to excel or PDF server times out. 

Bad Apple

**Comment by Repair-Desk** [comment]
Since the inventory size is bigger the server time out. there are 2 solutions

1- It only downloads the item displayed on the page.
2- We run the SQL query and it sends you an email with excel + PDF. Please advise

**Comment by usmanalikhan93** [comment]
Hi @Uzair-RepairDesk 

It is on beta server. Hopefully we will go live with today.
