### ISSUE TITLE
Option to View Reports by Specific Days - Matt Sams |  Crack'd Mobile Device Repair

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#562]
**Hi Sir,**

**Business Name / Store Name:**
Matt Sams |  Crack'd Mobile Device Repair

Module:
Reports

Configuration Setting: Correct
Roles & Permissions: Correct

**Improvement:**
Customer is looking for a method in which we are able to run a sale report from a specific day of the week only. For example, I want to run a report showing the total sales from every Sunday in 2018. Usman has advised to post this here.

**Current Results:**
We can apply filter Date Wise only. 

**Expected Result:**
There should be an option for searching Reports via a specific days as well.

**Comment by Uzair-RepairDesk** [comment]
I need more clarity on this. Also please specify the reports. @ali-repairdesk

**Comment by ali-repairdesk** [comment]
He is referring to Sales Summary Report.
He is off the point of view that in case he wants to run report on the basis of days. Lets Suppose he wants to fetch all the sales which were did on Sundays.

Do let us know in case more elaboration is required.

Thanks,
