### ISSUE TITLE
Option to keep track of Damaged Inventory - Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#564]
**Hi Sir,**

**Business Name / Store Name:**
Modesto | DrPhone Fix

**Module:**
Inventory

**Configuration Setting:** Correct
**Roles & Permissions:** Correct

**Improvement:**
Customer is looking for a way in order to track Damaged Inventory Items/Parts. For now there is no Report or any way in which we can track which part was faulty or which is broken. In case we can come up with a way.

For now I have recommended him to create a new item type with named "Damaged Inventory" and than keep track with this. 

**Current Results:**
There is no way to keep track of Damaged Inventory Items.

Expected Result:
There should be a way to keep track of damaged inventory items.

**Comment by ochoaonline** [comment]
Current Work around im using is by Creating a Vendor as Damaged By Employee, but once a status is able to be created would be even better since then i can add it under the Real Vendor and Status would be Damaged by Employee and a section where you can enter name of employee that damaged it.

**Comment by Uzair-RepairDesk** [comment]
Hey @ochoaonline
 
We have added "Damage Part Report" in RepairDesk that will allow you to keep a list of all the faulty items and devices. In this report, you can find all the inventory items, accessories or parts that have been marked as ‘faulty’ and you can either create RMA against them, mark them broken or can add them back into the inventory.
Please review at your end.

![DPF Control Center  Reports](https://user-images.githubusercontent.com/22955861/58079397-5b7c6500-7bca-11e9-8264-1aa975b7d210.png)
