### ISSUE TITLE
Option to Update Working Hours for a Non Admin Account - Modesto | DrPhone Fix 

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#565]
**Hi Sir,**

**Business Name / Store Name:**
Modesto | DrPhone Fix

**Module:**
Payroll Module

**Configuration Setting:** Correct
**Roles & Permissions:** Correct

**Improvement:**
Customer is looking for a way in which Non Admin user with most of the permissions can update Working Hours for his employees. 

For better understanding, I have compiled a small video as well. I will appreciate if you may watch it:
https://drive.google.com/file/d/1cDV8Tlrqx0epiTJ6kIwxy9jltbFqnjIL/view

**Current Results:**
Non Admin account is not having permission to update Working Hours.

**Expected Result:**
Non Admin account should have permission to update working hours.

**Comment by Repair-Desk** [comment]
Dear Uzair,

Thanks for sharing additional info however they are a franchise store and they want their store manager or people who has access to this trigger to update time-log of other employees. Please add it to next week release.

Best,
Usman

**Comment by Uzair-RepairDesk** [comment]
We have already added the permission under employee roles that allow specific role employee to update working hours from timesheet.

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk @Repair-Desk This is not completed yet, 

**Previous Message**
Dear Uzair,

Thanks for sharing additional info however they are a franchise store and they want their store manager or people who has access to this trigger to update time-log of other employees.
-------

The current Trigger only allows Employee 1 to update his / her own hours, not for Employee 1 to update hours of other employees in the same store for example Store owner updating hours for his Techs / Managers

**Comment by Repair-Desk** [comment]
@uzair: Can you please confirm if this is planned for current release

**Comment by Uzair-RepairDesk** [comment]
Currently, If new "Update Clock In/Out" trigger is enabled, it allows the specific role to update only his/her timesheet because we don't allow users to view timesheet of other users. 
We need to add another permission to allows users to view timesheet of other users, once they are able to do that it will also allow users to update clock in/out time for other users. 
I am adding in the coming week plan.

**Comment by Uzair-RepairDesk** [comment]
Hey @ochoaonline Modesto,
We have made this improvement LIVE. You can give permissions to specific employee role to access the "Timesheet" of other employees.
Once you enable the permissions, an employee of a specific role will be able to view timesheet of other employees as well and if you also enable the trigger "Update Clock In/Out", they will also be able to update In/Out time of any specific employee. 
Please check screenshot attached. 
![uzairshah roles permission](https://user-images.githubusercontent.com/22955861/52842596-5f0ed480-3121-11e9-81d1-ea663b87bd6d.png)
