### ISSUE TITLE
Improvements In Customer Module - Option to Display Store Name Under Tickets & Invoice & add store filter under tickets and invoice

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#567]
For corporate customers they need to see invoice across all stores. Would be great if there was a store filter that allows you to view invoices.

![store name](https://user-images.githubusercontent.com/21986026/50711032-fc0e2600-1029-11e9-9442-c033a80c6a84.jpg)

**Comment by Repair-Desk** [comment]
It should display store name against a repair ticket as well

**Comment by Repair-Desk** [comment]
Is it possible to just display store name against ticket and invoice and release a hot fix on Friday?

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk 
I have already discussed it with the developer day before yesterday. We **had the option to view all the tickets and invoices of all stores** under Manage Customers section and only those specific tickets and invoices are clickable that are linked with the same store. Currently, it's not coming under Invoices. 
Its also **linked with Store type functionality** and sharing of customers across stores.

Development **requires a document for this to display invoices and tickets according to the stores**. They also asked for the design to display store search filter.
I have already scheduled it for the document. 

However, I still think that we should update the **"Customers Module" interface** as its quite outdated and same as we did from start.

**Comment by Repair-Desk** [comment]
Thanks for sharing additional info @Uzair-RepairDesk. We can engage Bilal for the update of customer module. 

Looking forward to go live with this improvement soon.

**Comment by Repair-Desk** [comment]
Also if you are in orem store and you're looking for invoice of Riverdale, it will throw a 404 error 

however it can display a pop up, you're opening invoice for Riverdale store and your store will be switched to Riverdale, please confirm which should switch his profile.

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7
We have updated the Manage Customer on your request. You can view tickets and invoices of all stores for each customer. You can also search for any specific ticket and invoice as well. Please check the screenshot attached. 
You can find more details of our release from the following link:-
https://www.repairdesk.co/blog/2019/01/25/release-notes-improvements-fixes

We have planned to also update that the link of another store ticket/invoice should be enabled and pop up should display that your store will be switched (as we have done in Manage Tickets). We are managing it in another task in next week plan. 

![improvements-fixes-e1548334682645](https://user-images.githubusercontent.com/22955861/51729606-46694c80-2096-11e9-9f59-606f639a17bb.png)

**Comment by Repair-Desk** [comment]
When you use the store filter for the first time it works however when you use it for the second time it doesn't work. Please release a fix.

Usman

**Comment by Uzair-RepairDesk** [comment]
We are not able to replicate this issue. It was a cache issue. Closing this now.
