### ISSUE TITLE
Float Count Start/End Shift Reporting

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#568]
Opening and closing float value should never be included in daily takings and needs to be amended in reporting. Current way confuses staff when finalizing shift

**Comment by Uzair-RepairDesk** [comment]
Thank you for sharing your idea Will @TechreviveAu 
Can you please explain your idea along with screenshot and example so I can discuss it with the team in detail. It will be appreciated. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey Will, @TechreviveAu 
We need more details on this. Please let me know if we can schedule a call in next week so we can discuss this in detail. Thanks

**Comment by TechreviveAu** [comment]
Sure thing
