### ISSUE TITLE
Improvements In Ticket, Inventory & RMA Label

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#569]
Following macros should be available on ticket label: 

- store name, 
- customer phone, 
- mobile

**Comment by Repair-Desk** [comment]
It would be good to add store name to RMA label.

**Comment by Repair-Desk** [comment]
It would be good to add following macros to Serialized Inventory:

{{serial_warranty}} Warranty

![rd-inventory-serial-88-28-default](https://user-images.githubusercontent.com/21986026/50735496-4fd55800-116d-11e9-996f-7c52d7fc523a.png)

**Comment by Repair-Desk** [comment]
Item Name on the Inventory label - Serialized Inventory or Trade-In should not be more than 20 characters. In case multiple device items are compatible it creates an issue. See below:

$devicemodels=substr($devicemodels,0,20)

[117230501546603930.pdf](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/2730410/117230501546603930.pdf)

**Comment by Repair-Desk** [comment]
If you would like to implement new ticket label which is in beta you can follow the steps as explained here: https://docs.google.com/.../1cybbLby4FdNJ1yynA12g.../edit... 

I've tested this with manual print option which worked great however I haven't tested that with GCP or Printnode yet. 

Please try this out and would love to get your feedback if you feel a certain macros should be added or not and in case you mess up the label template you can easily reset it as shown attached. 

Recommended Label Size: At least 88mm X 28 mm (Bigger the better :) )

Please do share a screenshot of your ticket label in the comments section so I can see if you were able to successfully configure it or not

**Comment by Uzair-RepairDesk** [comment]
We have made this improvement LIVE.
Admin/Users can select "Professional" template label design for Inventory and Ticket.
We have also updated RMA label design that will be print by default from a specific RMA.
