### ISSUE TITLE
Store Search Filter on Manage Tickets

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#570]
![ticket](https://user-images.githubusercontent.com/21986026/50727553-bdd03f80-10d9-11e9-8d59-8fdea3aa149f.jpg)

Also would be great if you click on ticket number for other store and you should be able to view it or if not possible switch it to other store.

**Comment by Uzair-RepairDesk** [comment]
We have the trigger available "Display all Tickets to super admin on Manage Tickets" under Settings > Module Configurations > Tickets. 
**We can give store search filter only if the above trigger is enabled.** 
In fact, we already have it but on the demo and we didn't make it live so far(Confirmation by Sir Imran).
Trevor discussed it with me on the last call and I recommended the same. 

**Regarding store switch, I discussed with Imran and we can do the following:-**
We can show an alert if user "View" or "Edit" ticket that store will be switched to "Store Name" and store will be switched first to view or edit the ticket but admin/users need to come back to the main store if he/she wants to view tickets of all stores.

Please confirm @Repair-Desk?

**Comment by Uzair-RepairDesk** [comment]
https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/563

**Comment by Repair-Desk** [comment]
**Hello @Uzair-RepairDesk** 

Thanks for sharing additional info and please find my feedback below:

**1- We can give store search filter only if the above trigger is enabled.**
Let's do it.

**2- Regarding store switch, I discussed with Imran and we can do the following:-
We can show an alert if user "View" or "Edit" ticket that store will be switched to "Store Name" and store will be switched first to view or edit the ticket but admin/users need to come back to the main store if he/she wants to view tickets of all stores.**
Let's do it

**Comment by Uzair-RepairDesk** [comment]
Done.
