### ISSUE TITLE
Customer Facing Display Improvements

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#571]
On POS using CFD if customer details are mandatory and you click on create ticket it asks for a pin, you capture customer signature and then it displays an error customer details are required. 

Also sometimes it doesn't request customers to enter their signatures. Would be great if there was an easier way to get customer signatures if the ticket was created. Perhaps on confirmation pop up we can add an option.

**Comment by Repair-Desk** [comment]
Also when CFD is switched on and it sends a request to the front facing display, you find an issue and 
you click on cancel request.

When you correct the issue and click on create ticket, it doesn't request the access pin at all and simply create the repair ticket

**Comment by Repair-Desk** [comment]
It takes good 8-15 sometimes 20 sections before it loads the info. Is there a chance we can make it quicker?

**Comment by Repair-Desk** [comment]
We also need to re-write CFD with option to edit front facing default slide.

**Comment by Repair-Desk** [comment]
Sometime I accept terms and conditions + submit button takes 2-4 taps which is inconvenient

**Comment by Uzair-RepairDesk** [comment]
We have made "Customer Facing Display" module LIVE. You need to reconfigure Customer Facing Display on both the web platform and the iPad POS Register app. You can find more details from following knowledgebase article:-
https://repairdesk.uservoice.com/knowledgebase/articles/1102397-how-to-configure-customer-facing-display
