### ISSUE TITLE
Bug / Improvement In Warranty Claim

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#573]
**Improvements:**

Lets say you do a screen repair whose default warranty period is 60 days.

Customer comes in on 50th day saying there is a problem with screen and if you replace the screen, RepairDesk resets the warranty period to 60 day however it should not.

What would be really cool is, if there was warranty added against a part this should be added towards the screen repair.

Bug: Ticket 161 / Bful
Also if option to close ticket is used under module configuration, and you edit it for a warranty repair it changes the ticket status to nothing and ticket status is pending which is weird.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you check the bug highlighted above in description?

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Whats the update on this?

**Comment by Repairdesk-QA** [comment]
**Update on Bug**

I have checked the bug and it looks likes it is resolved.
