### ISSUE TITLE
Improvements - Sales By Item Type Report

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#575]
![sales by item type report improvements](https://user-images.githubusercontent.com/21986026/50735314-69c16b80-116a-11e9-8334-ccafee24423c.jpg)

1- Also when you export items to excel it doesn't display the item type (category)
2- It doesn't display their totals

**Comment by Uzair-RepairDesk** [comment]
**Logged on JIRA**
https://repairdesk.atlassian.net/browse/REP-1107

**Comment by Uzair-RepairDesk** [comment]
We have gone live with the above improvements
