### ISSUE TITLE
Inventory Summary Report Not Working Properly

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#576]
If you run the inventory summary with a date the report doesn't work right with serialized items.  If there is no date it seems to work.  See attached screen shots for clarification.
<img width="1411" alt="screen shot 2019-01-07 at 4 02 59 pm" src="https://user-images.githubusercontent.com/43588617/50798556-02a0d580-1296-11e9-97cf-3886c0e3b15f.png">
<img width="1412" alt="screen shot 2019-01-07 at 4 02 39 pm" src="https://user-images.githubusercontent.com/43588617/50798559-059bc600-1296-11e9-99fa-2f72011d85ab.png">
<img width="1414" alt="screen shot 2019-01-07 at 4 01 16 pm" src="https://user-images.githubusercontent.com/43588617/50798562-07fe2000-1296-11e9-94ef-cffdb794017d.png">
<img width="1415" alt="screen shot 2019-01-07 at 4 01 00 pm" src="https://user-images.githubusercontent.com/43588617/50798565-0af91080-1296-11e9-840f-00b1788feef4.png">

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 Can you please check

**Comment by Uzair-RepairDesk** [comment]
**Delayne fro Bad Apple Team also reported the following:-** @usmanalikhan93 can we also check this?

"I am still having some issues with the Inventory Summary report.  When it is converted to a csv file a few of the SKU are ending up with a space in front of the Store Name thus creating a new store name in excel. (excel pivot table below). What can be done to fix this? See SKUs below"
![1](https://user-images.githubusercontent.com/22955861/50811691-5f050300-1331-11e9-8281-984f7e334fc0.png)
![2](https://user-images.githubusercontent.com/22955861/50811692-5f050300-1331-11e9-8397-ce62c47ac534.png)

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

I hope you are doing well. I have reviewed your concerns related to inventory summary. It seems to be working fine. Can you provide more info on this ? A short video with a use case will be really helpful.

**Comment by Trevorshaw7** [comment]
Look at the screen shots. It displays differently with a date attached

**Comment by usmanalikhan93** [comment]
Ticket has been created and Assigned it to Dev, https://repairdesk.atlassian.net/browse/REP-1114. We are not seeking this issue in our accounts but its been verfied, its an issue with your account.

**Comment by usmanalikhan93** [comment]
Hey @Trevorshaw7 ,

This issue has been resolved *(mentioned below)*. Please verify it for your convenience. 
If you run the inventory summary with a date the report doesn't work right with serialized items. If there is no date it seems to work.
