### ISSUE TITLE
Enhancement to RMA

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#578]
It would be great to get an RMA report, but in the meantime can you add a cost summary like the inventory counts have?
<img width="1414" alt="screen shot 2019-01-07 at 4 39 36 pm" src="https://user-images.githubusercontent.com/43588617/50800488-ab9efe80-129d-11e9-82f1-3fd5f1e49db6.png">
<img width="1410" alt="screen shot 2019-01-07 at 5 00 16 pm" src="https://user-images.githubusercontent.com/43588617/50800502-bd80a180-129d-11e9-9a19-bf445e54deb6.png">

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
Thank you for sharing your idea. 
We have a plan to improve our complete RMA module however do you want to view a total of RMA on Manage RMA listing page?

**Comment by Trevorshaw7** [comment]
Yes, it would be helpful.

**Comment by Uzair-RepairDesk** [comment]
Hey, @Trevorshaw7  Total added in RMA listing page, kindly verify at your end.
