### ISSUE TITLE
Customer History

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#579]
When viewing a customer you should be able to view the history of all transactions not just a single stores transactions. Also when looking at revenue by customer the report isnt working right.
<img width="1419" alt="screen shot 2019-01-07 at 5 08 03 pm" src="https://user-images.githubusercontent.com/43588617/50800751-d50c5a00-129e-11e9-8297-5dab6f357f1d.png">
<img width="1420" alt="screen shot 2019-01-07 at 5 04 59 pm" src="https://user-images.githubusercontent.com/43588617/50800753-d63d8700-129e-11e9-8785-426e46dcf1bf.png">

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7  Hope you are fine.
Issue related to  revenue by customer reports has been fixed and its live, where as other issue you mentioned is still under development . once that issue is resolved we will update you.

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7
We have updated the Manage Customer on your request. You can view tickets and invoices of all stores for each customer. You can also search for any specific ticket and invoice as well. Please check the screenshot attached. 
You can find more details of our release from the following link:-
https://www.repairdesk.co/blog/2019/01/25/release-notes-improvements-fixes

![improvements-fixes-e1548334682645](https://user-images.githubusercontent.com/22955861/51729606-46694c80-2096-11e9-9f59-606f639a17bb.png)
