### ISSUE TITLE
Inventory Count Export

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#580]
Can we get the store alternate name on this report?
<img width="1084" alt="screen shot 2019-01-07 at 5 14 20 pm" src="https://user-images.githubusercontent.com/43588617/50800963-fcaff200-129f-11e9-80e2-3edab0d52363.png">

**Comment by Repair-Desk** [comment]
Also it would be good to display total inventory dollar value

![transfer](https://user-images.githubusercontent.com/21986026/51075423-06d74500-1640-11e9-96e9-aa377ffd284c.jpg)

**Comment by Uzair-RepairDesk** [comment]
@Trevorshaw7  reported issue is done, kindly verify.
