### ISSUE TITLE
sms reply times are way off

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#581]
![image](https://user-images.githubusercontent.com/37640713/50932703-02d2d980-142c-11e9-8338-f24cd5db7ca1.png)
this customer replied not long after her 3:40pm text and it is time marked hours off. Any ideas on ways to fix?

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw . Can you check the log of your sms service provider ?

**Comment by phonefixdfw** [comment]
I am using clickatell. It does look like time is wrong on clickatell, but why wouldnt it use local time to us like the outgoing message does? and mark the time same as whatever time it comes in at. I dont see a way to change timezone on clickatell but i will keep looking

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

Just Developer needs to know that did you get these SMS on time and it is showing 10:03 PM ? 
For example you get reply on 4:00 PM and on RD it is showing 10:00 PM.

**Comment by phonefixdfw** [comment]
Yes the reply was sent soon after the original text. It looks like customer reply time is using clickatell server time which is south Africa and they say can't be changed. I believe the reply was at 4:03 but says 10:03 because of the server time difference

**Comment by usmanalikhan93** [comment]
Thanks for the information @phonefixdfw . I will discuss this with developer and revert back to you tomorrow.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1141

**Comment by afrahm** [comment]
We have found the exact same thing and we are using SMS Broadcast in Australia
<img width="548" alt="screen shot 2019-01-18 at 8 22 17 am" src="https://user-images.githubusercontent.com/1414304/51352804-6d55da80-1afa-11e9-8f83-6aae1b812cbb.png">

**Comment by usmanalikhan93** [comment]
Sorry for the inconvenience @afrahm. I have already assigned this to developer, he will check why this issue is coming up. I will revert back to you once I get more info on this.

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw @afrahm 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
