### ISSUE TITLE
Reconciliation sms

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#582]
Reconciliation SMS notification to managers is enabled but only works for the manager ending shift.

Would be a good idea to have the option to notify all managers

**Comment by Uzair-RepairDesk** [comment]
Hey Will @TechreviveAu 
If you go to **Store Settings > Cash Register > Notification** 
You can enable "**SMS On Shift Close**" for any store user you want. It sends SMS Reconciliation summary upon shift end. 
Please make sure that **"SMS Integration"** should be enabled and specific admin/users should have **valid "Mobile Number"** in the profile settings.

I have just verified it for the email and its working for me.

**Comment by TechreviveAu** [comment]
It will work for the staff member who ends shift. We would like to have the option to notify multiple managers on end shift. Currently this does not work via SMS.

For example, if my wife ends shift she will get an SMS with totals however I do not.

If I end shift, I get an SMS with totals but my wife does not.

**Comment by Uzair-RepairDesk** [comment]
Thank you for the example Will @TechreviveAu . I can get it checked in case of SMS.
Did you check it with the notifications of email from your account? Can you please confirm if admin/users get the reconciliation email at end of the shift? 
Please refer to the screenshot attached
![uzairshah shiftclosesetting cashdrawer](https://user-images.githubusercontent.com/22955861/51106237-fa541780-180c-11e9-953b-2a59dad375f1.png)

**Comment by TechreviveAu** [comment]
Thanks Uzair for the prompt reply.
I can confirm that both my managers have the "SMS on Shift Close" enabled however only the manager who closes the shift receives the SMS

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Please review and check with development if we can review it with SMS

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
Hi Will@TechreviveAu 

I hope you are doing well. Do discuss this issue with Danish today when you have a remote session with him.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can we have an update on this, please?

**Comment by usmanalikhan93** [comment]
Hi Will @TechreviveAu 

Did you check with Danish on this issue ?

**Comment by TechreviveAu** [comment]
Hi there,
No it wasn’t discussed.

**Comment by TechreviveAu** [comment]
Can we follow up on this during the week please

**Comment by Uzair-RepairDesk** [comment]
Hey Will @TechreviveAu 
I have followed up with Danish on this.

**Comment by Uzair-RepairDesk** [comment]
I discussed it with Danish. He said you are good to go. If you still face any issue. You can contact him directly. Thanks
