### ISSUE TITLE
Trade in devices

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#583]
We have set trade in devices not to display until 30 days has lapsed however you can still search for these in POS when entering the name manually

This option when enabled should not let the user search or select the traded in device under any circumstances until desired time has lapsed.

**Comment by Uzair-RepairDesk** [comment]
Hey Will @TechreviveAu ,

If I am not wrong, you have set "Sale Date" under "Seller Invoice Settings" to "30 Days". 
I also just did the same and set value of 7 days. It doesn't come up in the "Trade-In" listing on POS even the status is "In Stock".
Can you please share more details on this where you are able to search so I can get it fixed?
Screenshots will be appreciated. Thanks.

Hope to hear from you soon. Thanks
![uzairshah tradein config](https://user-images.githubusercontent.com/22955861/51101726-b1489700-17fd-11e9-910c-5ce83650e720.png)

**Comment by TechreviveAu** [comment]
Hi Uzair,
This issue seems to have rectified itself. thanks for getting back to me promptly
