### ISSUE TITLE
Pre and post conditions specific time device type

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#584]
Pre and post condition module needs to be re-written so that conditions can be specific to device category I.e a laptop, tablet, phone etc would all have different scenarios

**Comment by Repair-Desk** [comment]
Assigned to Bilal. We will need to update this on iPAD. @Uzair-RepairDesk I believe hassan has the documentation ready. Please involve Irfan for the mock ups

**Comment by TechreviveAu** [comment]
Would like to see this for use on computer aswell as iPad POS. Our store is not using iPad POS

**Comment by Uzair-RepairDesk** [comment]
Hi Will @TechreviveAu 
We have designed mockup's to update Pre/Post Device Conditions functionality. **Please check screenshots attached.**

Currently, we are planning to tie up with our Repair Categories module. All the categories that are active will come up on "Manage Pre/Post Conditions" and you can mark conditions with each category. This will allow auto-populate Pre Conditions checklist according to selected category while booking a repair job.
**OR,**
we can keep it separate with category module and allow you to create device type to mark "Pre/Post Conditions". You can choose device type from dropdown while creating a repair job.

Your feedback will be appreciated on this so we can develop the functionality accordingly. Thanks
![add-pre-post-repair-against-category](https://user-images.githubusercontent.com/22955861/51529744-2c8ff580-1e5b-11e9-816c-0b6430750c69.jpg)
![add-with-system-default-conditions](https://user-images.githubusercontent.com/22955861/51529745-2d288c00-1e5b-11e9-9da4-f6d56e262162.jpg)
![manage-pre-post-repair-against-categories](https://user-images.githubusercontent.com/22955861/51529746-2d288c00-1e5b-11e9-992e-143cd8d87b9d.jpg)
![pre-post-check-list-on-pos-with-categroy-dropdown](https://user-images.githubusercontent.com/22955861/51529747-2dc12280-1e5b-11e9-9b9f-4b39e76b41a2.jpg)

**Comment by Uzair-RepairDesk** [comment]
We have concluded the design in this week and start development in early next week Will @TechreviveAu

**Comment by Uzair-RepairDesk** [comment]
Hi Will @TechreviveAu 
This is to update you we have started development of above feature enhancement. We are expecting to conclude and GO LIVE in next release.

**Comment by TechreviveAu** [comment]
Brilliant !

**Comment by Uzair-RepairDesk** [comment]
Hey Will @TechreviveAu 
We have made this enhancement LIVE. 
1: You can now choose to view the pre/post conditions of a device as a dropdown or in the toggle mode.
2: From now on, you’ll have the device conditions against every category in the POS section.
3: Default conditions have been specified for your convenience, also you can add/edit any other condition if required against specific category.

You can check more details from the following knowledgebase article:-
https://repairdesk.uservoice.com/knowledgebase/articles/921312-how-to-add-device-pre-post-repair-condition

If you have any questions, please feel free to ask. Thanks
