### ISSUE TITLE
Invoice Sync Issue 

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#585]
**Hi Sir,**

**Business Name / Store Name:**
Orange Phone Care

**Customer Credentials:**
Email: Shared on Skype
Password: Shared on Skype
Admin:  Yes

**Store Name For The Issue:**
Issue coming on all Stores

**OS:** Windows / MacBook
**Module:** QuickBook
**Configuration Setting:** Correct
**Roles & Permissions:** Correct

**Issue:**
Customer has reported an issue that once we do the following:

Integrations >> QuickBook >> Account Configuration >> It asks to connect QuickBook

Once we connect QuickBook on 1 store, the other store gets disconnected.

**Steps to Reproduce Issue/Provide Video:**
1. Login to customer account with the provided login details.
2. Integrations >> QuickBook >> Account Configuration >> It asks to connect QuickBook. Once we connect QuickBook on 1 store, the other store gets disconnected.
Video Link shared on skype.

**Current Results:**
Invoices are not getting synced due to stores getting disconnected with QuickBooks.

**Expected Result:**
Invoices should be synced properly.

**Comment by Repair-Desk** [comment]
@ali-repairdesk Umair will check this first thing Monday morning

**Comment by usmanalikhan93** [comment]
@ali-repairdesk @Repair-Desk 

According to fayyaz comment, this issue has been fixed.
