### ISSUE TITLE
Pin code mandentory issue 

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#587]
Since activating pin code mandentory upon booking in device through pos., I can now no longer save tickets. An error keeps appearing with "Passcode or pattern is required" regardless of if pin or pattern code being saved to ticket

**Comment by usmanalikhan93** [comment]
Hi,
Issue is with the editing of ticket, when the trigger is on. We have created the ticket and will get back to you.
https://repairdesk.atlassian.net/browse/REP-1136

Thanks

**Comment by usmanalikhan93** [comment]
Hi @TechreviveAu 

Your reported issue has been assigned to development team and hopefully it will be fixed tomorrow or day after tomorrow. For the time being, you can switch off the trigger and work with that.  
Your patience would be highly appreciated.
Thanks!
Usman Ali.
