### ISSUE TITLE
Negative on Serialized

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#588]
There is a negative on serialized item, How does this happen?
<img width="501" alt="screen shot 2019-01-14 at 12 57 30 pm" src="https://user-images.githubusercontent.com/43588617/51137584-1dc29680-17fc-11e9-844d-205c7d10db10.png">

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Your reported issue has been fix. Please verify at your end and do let me know if you have any question. 

Thanks. 
Usman Ali
