### ISSUE TITLE
Switching stores

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#591]
Currently every time you switch a store it will send you back to the welcome page.  It would be really nice if it would keep you on the same page that you were in but just change the data according to the store. Check with Uzair for explaination.  It gets really time consuming starting over everytime you need to switch to a different store.  having 11 outlets that time adds up, as well as it makes the servers work more and slow the system down.

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
We have made the above improvement live in the release. It will keep you on the same page if you switch the store now.
