### ISSUE TITLE
Reports Home page

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#592]
Reports home page sends you to the multi store report when it should display all available reports.  If someone wanted to view the multi store report you could click on that to view it.  But currently how it is set up for me to look at parts consumption I have to go through the multi store report to get to reports page, and it get time consuming to be forced into the same report every time.

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
We have updated it on your request. You can review all the reports on "Admin Dashboard" as well once you log in with RepairDesk. Check screenshot attached. 
Please review at your end. 
![uzairshah dashboard](https://user-images.githubusercontent.com/22955861/51729315-fccc3200-2094-11e9-96f5-3cd691ff3224.png)
