### ISSUE TITLE
Employee Productivity

### ISSUE THREAD

**Issue by ireparo** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#593]
All the repairs that are made by the technician do not count them in productivity from the employee to the technician, but they are accounted for by the person who charges and delivers the terminal. In this way you can not know how much the technician generates for the company.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93   kindly check this issue

**Comment by Uzair-RepairDesk** [comment]
Hi @ireparo 
Can you please elaborate it with screenshots? Is it about the "Employee Sales Performance" in productivity? 
Hope to hear from you soon.

**Comment by ireparo** [comment]
As you can see in the image, the technician Bader has made several repairs and they are counted in the lower part but their productivity in employee income does not come out. If I select the person who delivers the device to the customer then the benefit is posted. But I would need you to count it to the technician and not to the person who delivers it.

![captura de pantalla 2019-01-17 07 49 57](https://user-images.githubusercontent.com/30700922/51300643-e850bf80-1a2c-11e9-9f15-e37517b609de.png)
![captura de pantalla 2019-01-17 07 50 10](https://user-images.githubusercontent.com/30700922/51300647-eb4bb000-1a2c-11e9-8d37-66e461b48d45.png)

**Comment by usmanalikhan93** [comment]
Hi @ireparo 

Can you please confirm that your technician does start the repair timer when he/she starts working on the assigned repair and change the status to "repaired" ?

**Comment by usmanalikhan93** [comment]
Hi again @ireparo   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
