### ISSUE TITLE
Employee activity report

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#594]
The employee activity report is not correct.
<img width="1420" alt="screen shot 2019-01-16 at 9 45 36 am" src="https://user-images.githubusercontent.com/43588617/51264428-b3ccfd00-1973-11e9-87b0-c698d461cb18.png">
<img width="977" alt="screen shot 2019-01-16 at 9 25 02 am" src="https://user-images.githubusercontent.com/43588617/51264448-bf202880-1973-11e9-88dc-9ec3617dfcbd.png">

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
We have updated the "Employee Activity Log" report on the new design. We are updating it with missing cases and we are expecting to GO LIVE in next release.

**Comment by Repair-Desk** [comment]
It would be great if employee activity log also shows information on when and by whom a new payment method is added / updated or removed

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
We have updated Employee Activity log report. Please review at your end. Thanks

**Comment by Repair-Desk** [comment]
If you remove multiple inventory items from the inventory listing page there is no record of it. Would be great if we can display the item numbers

item # 991, item # 992, item # 311 were deleted from Manage Inventory. See below:

![dpf control center - employeeactivitylog stats](https://user-images.githubusercontent.com/21986026/53356960-7a15eb80-394e-11e9-851a-d17d21a77094.jpg)

**Comment by Uzair-RepairDesk** [comment]
**In-House Task Reference:-**
https://repairdesk.atlassian.net/browse/REP-1497

**Comment by Uzair-RepairDesk** [comment]
We have made this improvement LIVE. You can track deleted inventory records from "Employee Activity Log" report.
