### ISSUE TITLE
Sales by Item

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#595]
It makes it difficult to account properly when this report splits the item from repair tickets and products.
<img width="734" alt="screen shot 2019-01-16 at 10 35 48 am" src="https://user-images.githubusercontent.com/43588617/51267382-d0206800-197a-11e9-9693-68feb5ec15e4.png">
<img width="554" alt="screen shot 2019-01-16 at 10 35 19 am" src="https://user-images.githubusercontent.com/43588617/51267387-d4e51c00-197a-11e9-8dde-4e931faf9532.png">

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
We have improved the "Sales by Item Type" report. 
We have also added "Repair Categories" criteria separately that allows you to view specific repair categories report or you can also select "Products" and filter report from "Product Categories".
Please review our updated report. Thanks.
