### ISSUE TITLE
All inventory counts are showing a 0 cost

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#597]
Why is there no cost associated with the counts?
<img width="1416" alt="screen shot 2019-01-16 at 5 15 23 pm" src="https://user-images.githubusercontent.com/43588617/51286929-6f148680-19b2-11e9-98cb-9981d6ff95e3.png">

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by Repair-Desk** [comment]
@usmanalikhan93 I believe one of the reason can be COGS for these items are $0.00

When you add a positive inventory count this increase the quantity but doesn't increase the price. @Uzair-RepairDesk what should be the solution in that case :)

**Comment by usmanalikhan93** [comment]
@Repair-Desk we have checked this case but it's working fine on our end. But we are investigating on our end about this issue. I will post here feedback once I get more info on this.

**Comment by Trevorshaw7** [comment]
The inventory count amounts are all wrong. The costs it shows in the total value is not correct at all

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Let me assign this to respective QA. I will revert back to you if I need more info on this.

**Comment by usmanalikhan93** [comment]
For internal use
https://repairdesk.atlassian.net/browse/REP-1287

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

I hope you are doing well. I hope with inventory count improvement update your issues related to these has been fixed now. Can you verify at your end and do let us know if you have any question .

Thanks 
Usman Ali
