### ISSUE TITLE
Ability to Display Admin Dashboard to Employees

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#599]
There should be an option where we can set under employee roles & permission so that they should not just see a technician dashboard 

![employee](https://user-images.githubusercontent.com/21986026/51351149-da9e4700-1acb-11e9-8ec4-b6dc1713f9aa.jpg)

**but admin dashboard. See below:**

![admin dashboard](https://user-images.githubusercontent.com/21986026/51350992-6ebbde80-1acb-11e9-8b67-5f62e487e350.jpg)

**Comment by Repair-Desk** [comment]
Also under employee roles and permission there should be an ability that allow store manager to update time sheet or clock in / out of employee's.

![employee roles](https://user-images.githubusercontent.com/21986026/51351324-69ab5f00-1acc-11e9-9ab1-0446d5a39d3e.jpg)

Currently only super admin can update clock in / out time. See below:

![timesheet1](https://user-images.githubusercontent.com/21986026/51351286-45e81900-1acc-11e9-9964-a2394b67d189.jpg)

**Comment by Uzair-RepairDesk** [comment]
Hey, 
We have updated roles permission module for this request.
Admin can give permission to any specific employee role to access the Admin Dashboard. 
We have also added permission to allow any employee role to update the clock in/out information. 

More details are available in the following release notes:-
https://www.repairdesk.co/blog/2019/01/25/release-notes-improvements-fixes
