### ISSUE TITLE
Inventory Type = Option To Select IF They Should Be Displayed On POS OR Not

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#600]
Currently Parts categories are also displayed on the point of sale screen. **See below:**

![parts](https://user-images.githubusercontent.com/21986026/51351595-184f9f80-1acd-11e9-9f5e-0efd25c14012.jpg)

It would be great if we can setup on the inventory type page which categories should be displayed on POS or not. By default "parts" categories should not be displayed on POS.

![show on pos](https://user-images.githubusercontent.com/21986026/51351627-374e3180-1acd-11e9-96ed-59b32cee5381.jpg)

**Comment by Uzair-RepairDesk** [comment]
We have made this improvement live. You can view more information from our last release notes:-
https://www.repairdesk.co/blog/2019/02/01/end-january-release-notes

**Comment by Repair-Desk** [comment]
Can we make this trigger to work with iPAD app as well? Currently on iPAD app it displays all categories however on web app if you've switched off some categories they are not displayed.

See below: 

![ipad](https://user-images.githubusercontent.com/21986026/53003510-e4abc080-3450-11e9-9076-436246cac67a.jpg)

![web](https://user-images.githubusercontent.com/21986026/53003527-f2f9dc80-3450-11e9-8424-008e728d2629.jpg)

**Comment by Uzair-RepairDesk** [comment]
Already noted and forwarded to Yusra for iPad. @Repair-Desk

**Comment by Uzair-RepairDesk** [comment]
We have implemented it on iPad POS Register as well.
