### ISSUE TITLE
In Transit report isn't accurate, and there is no way to do anything with the inventory.

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#603]
In Transit report isn't accurate, and there is no way to do anything with the inventory.  There has to be a way to resolve the inventory that is intansit.
<img width="1426" alt="screen shot 2019-01-17 at 9 01 08 pm" src="https://user-images.githubusercontent.com/43588617/51364961-33092080-1a9b-11e9-9c9e-b91be32c436d.png">
<img width="1423" alt="screen shot 2019-01-17 at 9 00 41 pm" src="https://user-images.githubusercontent.com/43588617/51364965-3a302e80-1a9b-11e9-9be0-e27f2b8385b2.png">

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Please check this. You can take details from Facebook chat group as well.

**Comment by Trevorshaw7** [comment]
Yes that is what happened

**Comment by usmanalikhan93** [comment]
For internal use
https://repairdesk.atlassian.net/browse/REP-1176

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

"If inventory item has status as shipped and it not received then the user should not able to delete that record. he can change its status to canceled if that item is not received from another store."

Thanks!
