### ISSUE TITLE
Not translated data! Sms error

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#604]
I had a ticket at my sachse location, sw-0455 with 3il ipad repairs on same ticket.

I edited ticket and changed them all from in progress to repaired and it sent this message via clickatell to customer instead of the normal repaired message.

**Comment by Repair-Desk** [comment]
@phonefixdfw Definitely strange.

Can you share a screenshot so we can check this for you?

**Comment by phonefixdfw** [comment]
sorry, i forgot to attach
![image](https://user-images.githubusercontent.com/37640713/51407921-d05b6780-1b22-11e9-87f2-294a878297a0.png)

**Comment by phonefixdfw** [comment]
just noticed it sent "not translated data" email too

**Comment by Repair-Desk** [comment]
Thanks for sharing the screenshot. We will release a hot fix for this issue early next week.

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

Your reported issue has been fixed. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali.
