### ISSUE TITLE
ADD OPTION OF "THIS YEAR" & "ALL" UNDER VIEW INVOICE, DASHBOARD AND REPORTS

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#606]
It would be good to add an option that allow you to view stats for year to date or for all invoices.

**Manage Invoice**
![this year](https://user-images.githubusercontent.com/21986026/51438705-7351e400-1cd1-11e9-9b57-95c07d62da86.jpg)

**Dashboard**

![dashboard](https://user-images.githubusercontent.com/21986026/51438718-a005fb80-1cd1-11e9-992e-98b3d4c8f2b7.jpg)

**Comment by Repair-Desk** [comment]
This option has been added 😊

**Comment by Repair-Desk** [comment]
Please add back the option of "Yesterday" as some of the users have requested it

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk 
Filter from "Yesterday" has been added in search filters of reports
