### ISSUE TITLE
Transfer orders with serial numbers

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#607]
Transfer orders TO-260 from the warehouse, and TO-263 from the warehouse has several serialized items on them.  When you view the serialized items they show the same numbers for each serialized item. Also it only has the serial number and not the rest of the information like the new update for the inventory summary.

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
The above reported issue has been fixed and verified on LIVE. Please review at your end. Thanks

**Comment by Trevorshaw7** [comment]
<img width="683" alt="screen shot 2019-02-01 at 10 42 03 am" src="https://user-images.githubusercontent.com/43588617/52139677-0b26ca80-260e-11e9-8e59-c4f43f6f9fb6.png">
Still only list the serial number without the details

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
Currently, its just display list of serials.
I will discuss it with the team if we can improve the UI of the popup to display serial information along with serial.
