### ISSUE TITLE
Opening Balance listed on the transaction log

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#609]
Can we get the opening balance listed on the transaction log?

**Comment by Uzair-RepairDesk** [comment]
Hi @Trevorshaw7 

While ending shift, there might be a closing balance of different payment methods (Payment methods that are 'accumulative') that becomes the opening balance of next shift on the same register.
Do you want to view "Total Opening Balance" of all possible payment methods on the transaction log report?

Looking forward to hearing from you. 

Regards,
Uzair

**Comment by Trevorshaw7** [comment]
I want to see the opening balance listed as sales are with the amount
listed in the same way.

**Comment by Repair-Desk** [comment]
Will be great to display opening cash balance

**Comment by Uzair-RepairDesk** [comment]
We have added the above-requested improvement and currently in BETA testing. We will GO LIVE next week release along with other Transaction log improvements. 
Screenshot from the beta server is attached below:-
![cm repair center transactions log](https://user-images.githubusercontent.com/22955861/52118124-530e1780-2637-11e9-8886-029293be3444.png)

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
We have made this improvement LIVE. You can view "Opening Cash Balance" and "Closing Cash Balance" at Start/End shift. 
Please review at your end. Thanks
