### ISSUE TITLE
iPAD App - Don't Download More than 25 items under each category When The App is Launched

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#612]
Currently when an app stays in active for 3 - 4 hours or you launch the app for the first time and if it has 17,000 items it will take forever to load. It would be great that it loads 25-30 items under each inventory category (in total) and display those items as well.

Moreover when you're in that category and there should be an option to either scroll down which loads 100 more items just like Facebook feedback

**Comment by YusraZakir** [comment]
It has been fixed for iPad. Verified by QA

**Comment by Repair-Desk** [comment]
@YusraZakir Thanks for the update and I've asked mark to verify this 👍
