### ISSUE TITLE
Sales Report Based on Item Type / Top Category

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#613]
For a store to be able to track sales at the top

1. Mobile Repair Sales
2. Tablet Repair Sales
3. Computer Repair Sales
4. Game Consoles
5. Smart Watch 

and any other top category we create in the system so at the end of the month i can see
i had $5,000 in computer sales, vs Mobile Sales and know which category is one giving me the most sales and also which category is giving me the most profit 
![repair type items](https://user-images.githubusercontent.com/35181467/51555708-3a874b80-1e46-11e9-92ee-daefc50f08f9.jpeg)

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
This is to update you that we have already made this improvement in "Sales by Item Type Report" and currently available on the BETA server for testing. We will make it LIVE in our next release.

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk Thanks for update

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
We have made this improvement LIVE. We have added criteria to filter sales by item type report with "Repair Category". 
Please review at your end. Thanks.

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk Thanks
