### ISSUE TITLE
Option to Change RMA Status directly on Warranty Item 

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#614]
![rma sent to supplier](https://user-images.githubusercontent.com/35181467/51567949-80eca280-1e66-11e9-87ee-7a79c6f4f387.jpg)
If it would be possible, to Add Status option on back end when creating an RMA directly from back end of a Warranty customer, so from one step they are able to Create RMA Mark it as "Sent To Supplier" so inventory will instantly leave the system and be able to have correct stock.

**Comment by Repair-Desk** [comment]
@ochoaonline  I believe we can make this feature trigger based as some store owners would want to make one RMA and send it to the supplier collectively. 

@Uzair-RepairDesk Secondly we can also add a functionality where it ask you to add it to an existing RMA similar to what we have done on low stock report where it ask you if you want to add it in an existing PO or transfer order

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk yes that would be awesome and better, another thing kind of related to this if you can print RMA's from a time period for the same vendor , for some of our vendors we send them a master RMA list, since we ship out RMA once a week or every other week, currently we go on RMA section filter my date range , take screen shot of screen and then print it via browser , and we also do one RMA per part so it can leave the system properly and not stay in inventory 
![drphonefix hq retail rma](https://user-images.githubusercontent.com/35181467/51622704-26eeea00-1f05-11e9-99f1-923116917b31.png)
![inventory change logs headquarters lightspeed retail](https://user-images.githubusercontent.com/35181467/51622705-26eeea00-1f05-11e9-8d88-8f663ab5c174.png)

**Comment by ochoaonline** [comment]
![warranty rma mock](https://user-images.githubusercontent.com/35181467/51625100-56ecbc00-1f0a-11e9-9e89-f5ac774b9dc1.jpg)
MOCK IDEA, of the RMA / WARRANTY this eliminates have to click VIEW RMA, then hitting EDIT on RMA, updated all fields then hit SAVE
@Uzair-RepairDesk

**Comment by Uzair-RepairDesk** [comment]
Thank you for the mockup and details Modesto. @ochoaonline 
I appreciate it. We will plan this to start working on it.

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 

We have made this improvement LIVE. When you claim the warranty or refunds, mark the item faulty and add it to RMA, you can now select the supplier and mark the status of RMA directly from the same pop up (as suggested in above mockup). Supplier automatically populates if it is associated with a specific item. 

**Please review at your end.** 

With regards to your other suggested improvements in RMA, you can log them here #722 so we can have a single dedicated post for all the required improvements.
