### ISSUE TITLE
woo commerce sync problem

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#615]
Nothing has been changed. What's the problem?

![image](https://user-images.githubusercontent.com/40500094/51570894-64546880-1e6e-11e9-9bc4-824be3a7da8c.png)

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you please check this?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS ,

Sorry for inconvinience, issue is present. Let us resolved it asap. Ticket has been created for the dev to work on it https://repairdesk.atlassian.net/browse/REP-1205. We will get back to you ASAP.

Thanks,

**Comment by JessicaSOS** [comment]
If ever his can help you,
I checked with the person in charge of my website before contacting you and he wrote me:
One thing I notice:
The API called via the URL of the webhook (web hook) is the v1 ...
But the version of the WP API is the v2. And there is also v3 ...

Can repairDesk validate with me?
Nicolas 1-418-557-4112

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
