### ISSUE TITLE
Unsubscibe from mailchimp

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#618]
Hello,
When we want to disable the mailchimp status of a client, the change is not saved. We go in client, change the client and click on "unsubscribe from Mailchimp". This change gives nothing even if we wait several minutes / hours. We have to do it 4 or 5 times in a row to make the change.
<img width="944" alt="mailchimp" src="https://user-images.githubusercontent.com/40500094/51632336-0cc10600-1f1d-11e9-81df-99d99ace83b7.png">

--
Bonjour,
Lorsque nous souhaitons désactiver le statut mailchimp d'un client, la modification ne s'enregistre pas. Nous allons dans client, modifier le client et cliquons sur "unsubscribe from Mailchimp". Cette modification ne donne rien même si nous attendons plusieurs minutes/heures. Nous devons le faire 4 ou 5 fois de suite afin d'effectuer la modification.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1234

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Please find Dev feedback below: 

I have tested on live on test account. Integration working fine as you can see in below video
https://drive.google.com/file/d/1Ns7i5sqX3owoeVhraqhEPweEzzDkDJAK/view
I have checked Jessica's account as its showing some network Error
![jessica_mailchimp](https://user-images.githubusercontent.com/39614480/51962055-a5590800-2480-11e9-8ec5-2c62dd5f1252.png)

And tried to login on Mailchimp with saved credentials in Jessica's account and it says incorrect email and password.
Please verify on your end to verify the mailchimp configuration and revert back.

**Comment by JessicaSOS** [comment]
I checked the connection information (user and password) and everything is correct. I did not make any changes in the settings and I only have 1 Mailchimps list. I do not know where the "network error" came from.

In addition, I can see that all customers created in Limoilou this Saturday, January 25, 2019 do not appear in our Mailchimps. In Repairdesk, we can see that all clients created on this date are in "Unsubscribed". There is obviously a problem of synchronization. Maybe it's only with the Limoilou shop because on January 25th, only this shop was open and I do not have Mailchimps data. Since when?
Can you help me settle this please.
<img width="858" alt="mailchimp report" src="https://user-images.githubusercontent.com/40500094/52086839-e4b55080-2575-11e9-8db9-e8ab48e22e82.png">
<img width="923" alt="unsubcribed" src="https://user-images.githubusercontent.com/40500094/52087036-60af9880-2576-11e9-8dc1-03b5404a10ee.png">

--
French:
J'ai vérifié les informations de connection (user et mot de passe) et tout est correct. Je n'ai fais aucune modification dans les réglages et j'ai seulement 1 liste Mailchimps. Je ne sais pas d'où provien l'"erreur réseau".

De plus, je peux voir que tous les clients créé à Limoilou ce samedi 25 janvier 2019 n'apparaissent pas dans notre Mailchimps. Dans Repairdesk, nous pouvons voir que tous les clients créé à cette date sont en "Unsubscribed". Il y a donc visiblement un problème de synchronisation. Peut-être que cMest unqiuement avec la boutique de Limoilou car le 25 janvier, uniquement cette boutique était ouverte et je n'ai pas de données Mailchimps. Depuis quand?
Pouvez-vous m'aider à réglé cela svp.

**Comment by usmanalikhan93** [comment]
Ok let me check with developer if he can do anything on this. I will revert back to you once I need more info on this.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing good. I have checked with developer and he said he needs your mailchimp credential to check this. Can you provide mailchimp credentials to Ali ? So he can give to us.

**Comment by usmanalikhan93** [comment]
Thanks.

**Comment by usmanalikhan93** [comment]
@JessicaSOS 

It has two factor authentication. Can't check. 
![jessica_mailchimp_001](https://user-images.githubusercontent.com/39614480/52461760-45561600-2b92-11e9-99ac-e5bc79dfa320.png)

**Comment by JessicaSOS** [comment]
I can give you the code. Please let me know on whatsapp or text message when you go on mailchimp and im gonna approuve and send you the verification code

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 8 février 2019 01:12
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Unsubscibe from mailchimp (#618)

 

@JessicaSOS <https://github.com/JessicaSOS> 

It has two factor authentication. Can't check.
 <https://user-images.githubusercontent.com/39614480/52461760-45561600-2b92-11e9-99ac-e5bc79dfa320.png>

**Comment by JessicaSOS** [comment]
any news ?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

We will do this to do, once Ali will be in office.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

you have replied to Ali: 
Both Problems are fixed?
1- all customer create un limoilou store was automatically unsubscribed. In other store is subscribed
2- we are not able to change unsubscribed to subscribed
Can you try both issue to confirm if is fixed ?

I have checked for few customers and they were as subscribed. Can you check at your end and let me know if it's working ?

**Comment by JessicaSOS** [comment]
1- all customer create un limoilou store was automatically unsubscribed. In other store is subscribed ****FIXED****
2- we are not able to change unsubscribed to subscribed ****NOT FIXED****

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Please find developer feedback below: 

Mailchimp integration working absolutely fine.
As this error occured on submission of page if record exist more than one with the same mobile/email.
After mailchimp button click. form submitted and it shows customer validation error nothing else. as you can see in attached following video.
https://drive.google.com/file/d/1qC-bWSB1NHHu8dIaJ2FvSoT4-CrqwrSb/view

**Comment by JessicaSOS** [comment]
I understand that the system does not show any error code, but I am not able to subscribe people who are in unsubscribed. Help me please.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked with developer, when I try to subscribe or unsubscribe it shows missing email address. Developer said this issue comes from mail chimp. It is not syncing these email addresses..

**Comment by JessicaSOS** [comment]
But a customer who has an email address but is in "unsubscribed", I should be in order to put it in "subscribed"? Which is not the case...

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Is it working fine on your end now ? I just need to confirm.

**Comment by JessicaSOS** [comment]
yes is fixed !
