### ISSUE TITLE
image display error in email mass mailing

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#621]
I made a template for e-mail sending satisfaction to our customers following their repair (mass mailing). I did it with images, but even if I have "open in a browser", the images do not load. (see attachment and see the email below)

I check with the person who takes care of our emails and he says:
The concern seems to be with your provider, sendgrid, because the images are hosted on the server.
Check with them.
<img width="570" alt="mail received from repairdesk" src="https://user-images.githubusercontent.com/40500094/51691130-2cf9cf00-1fc8-11e9-939a-878bb651283e.png">
<img width="928" alt="massmailing" src="https://user-images.githubusercontent.com/40500094/51691143-33884680-1fc8-11e9-97f9-a643b842ab4c.png">

---
J’ai fait un template pour l’envois de courriel de satisfaction à notre clientèle suite à leur réparation (mass mailing). J’ai l’ai fait avec des images, mais même si je fais « ouvrir dans un navigateur » , les image ne se chargent pas. (voir pièce jointe et voir le courriel plus bas)

J'ai vérifier avec la personne qui s'occupe de nos courriels et il me dit: 
Le souci semble être avec ton fournisseur, sendgrid, parce que les images sont hébergé sur le serveur.
Vérifie avec eux.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1236

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked with Developer and he said you have to use some third party like dropbox or google drive to upload images and give link of that in campaigner email source. 

Developer's comment:
"As checked in HTML content of client. client is using the images uploaded from The Internal WIKI widget . 
Internal wiki provides a feature to upload image and show in-bound for display only. Our software not providing any special space for media to use it in Campaigner. so please guide customer to use any third party media storage like Drop box. attach the images from there and it will work definitely."

I hope you understand.
