### ISSUE TITLE
Inventory Adjustment

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#622]
Inventory adjustment isn't showing cost on the adjustment report.
<img width="1429" alt="screen shot 2019-01-24 at 2 57 00 pm" src="https://user-images.githubusercontent.com/43588617/51711182-94c01200-1fe8-11e9-8e98-dfd0a1c0f855.png">
<img width="1435" alt="screen shot 2019-01-24 at 2 57 19 pm" src="https://user-images.githubusercontent.com/43588617/51711195-9db0e380-1fe8-11e9-9bec-c9727ea89243.png">
<img width="1436" alt="screen shot 2019-01-24 at 2 57 29 pm" src="https://user-images.githubusercontent.com/43588617/51711202-a1dd0100-1fe8-11e9-965b-d124dc81a311.png">

**Comment by Uzair-RepairDesk** [comment]
@Trevorshaw7
We have made this improvement LIVE. Other improvements for "Inventory Adjustment Report" are also done and under BETA testing. These are scheduled to GO LIVE next week.
