### ISSUE TITLE
Inventory Adjustment Tracking

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#623]
Can we get the Inventory Adjustment number listed in the admin history of the part similar to how the Transfer orders are in this picture?
<img width="1435" alt="screen shot 2019-01-24 at 2 57 19 pm" src="https://user-images.githubusercontent.com/43588617/51711303-e5376f80-1fe8-11e9-9b3d-ec0bf874fae6.png">

**Comment by Repair-Desk** [comment]
![drphonefix hq retail - adjustmentreportdetail inventoryadjustment](https://user-images.githubusercontent.com/21986026/51766617-d5a94b00-20fc-11e9-8c71-31f578ccae48.jpg)

**Comment by Repair-Desk** [comment]
![inventory count](https://user-images.githubusercontent.com/21986026/51766893-89123f80-20fd-11e9-989f-57fe3e217d37.jpg)

**Comment by Repair-Desk** [comment]
![colors](https://user-images.githubusercontent.com/21986026/51768295-b6f98300-2101-11e9-9bbd-566980b63a3e.jpeg)

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1240

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
We have made your above-suggested improvements LIVE. Please review at your end. Thanks
