### ISSUE TITLE
Multiple invoices per ticket

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#625]
The ability to have multiple invoices generated against a single repair ticket would be very handy especially for corporate customers who may need to individually pay for a repair and require a seperate invoice for each repair/device on that ticket.

Alternatively the option to move a selected device on a repair ticket to a new ticket would make life easier rather than manually creating a whole new ticket with customer details.

**Comment by Uzair-RepairDesk** [comment]
Hey Will @TechreviveAu 
Since our call is scheduled, we can discuss this over the call in next week 👍

**Comment by TechreviveAu** [comment]
Can we follow up on this during the week please
