### ISSUE TITLE
Minor Improvements In Multi - Store Report

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#627]
1- Add 2 new columns: 
Franchise Fee
Payments Received

2- Add an option in store type of "franchise fee" where admin can enter there franchise fee. It can be set to be charged on total sales or payment received in the selected duration.

Franchise fee can be same for all stores or can be different for each store.

![multi-store report improvements](https://user-images.githubusercontent.com/21986026/51767938-9aa91680-2100-11e9-89e9-f1308c63638d.jpg)

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk
Can i have more details on the concept of “Franchise Fee” in the above given description?
What is the priority to add this field along with “Payments Received”? 
Your response will be appreciated. Thanks

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk idea is to add an option on back end where Franchisors can specify a Franchise Fee percentage and this percentage is displayed next to payments received 
 **For Example** $1,000 Received in payments x 25% Franchise fee = $250
and option to either multiply it by **"Payments Received**" or **"Total Sales"** this might vary by franchisors

**Comment by Repair-Desk** [comment]
Have a look at how Franchise fee Setup screen should be designed.

![franchise fee](https://user-images.githubusercontent.com/21986026/51959172-f95def80-2474-11e9-8928-b0e4625b7243.png)

**Comment by Uzair-RepairDesk** [comment]
**In House Task Reference:-**
https://repairdesk.atlassian.net/browse/REP-1241

**Comment by Uzair-RepairDesk** [comment]
We are completing designs for "Franchise Fee" functionality in this week and start development early next week
@ochoaonline @Repair-Desk FYI

**Comment by ochoaonline** [comment]
Thanks

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk Can you change name of it to "Royalty Fee" once its created, Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
We have added "Payment Received" field on "Multi-Store Sales Breakdown" report and under QA review. 
We have also completed the "Franchise Fee" design's HTML and start development in early next week. 
We are expecting to complete it before the next release. 
I have added your request to add a translation to make it "Royalty Fee" field on the task.
I will keep you posted on this. Thanks.

**Comment by ochoaonline** [comment]
Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
GOOD NEWS! We have added "Payments Received" field in "Multi-Store Sales report". Please review. 
We have also started development to add "Franchise Fee" feature in RepairDesk.
Hopefully, we will GO LIVE with it in next release. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
We have added Franchise fee functionality on your request. 
You can set a specific percentage on the basis of specific criteria to calculate the "Franchise Fee" on "Multi-Store Sales Breakdown" report. 

You can also add a translation of fields from Language editor under dashboard section. 
You can review and find more information in the following knowledgebase article:-
https://repairdesk.uservoice.com/knowledgebase/articles/1902343-franchise-fee-setup

**Comment by ochoaonline** [comment]
Thank guys it works great
