### ISSUE TITLE
Language Editor - Option to copy language settings from HQ to all stores

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#628]
If you're using language editor module and when you make an edit on the HQ store, their should be an option that allow you to copy language settings to other stores.

![copy language changes](https://user-images.githubusercontent.com/21986026/51768684-d2b15900-2102-11e9-89c7-6923330d912d.jpg)

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1242

**Comment by Uzair-RepairDesk** [comment]
We have developed it and under testing. We will GO LIVE next week. @Repair-Desk

**Comment by ochoaonline** [comment]
Great

**Comment by Uzair-RepairDesk** [comment]
Hey @ochoaonline @Repair-Desk 

We have made this improvement LIVE. You can go to the Language Editor > Select language, Once you update the text/translation to the selected language you can click "**Copy selected language to other stores**" > Select store or multiple stores and click on Proceed

**Comment by ochoaonline** [comment]
@Repair-Desk @Uzair-RepairDesk  Checking in on the language editor not copying languages over to other stores, i did id by selecting language and also by selecting the module but neither copied

**Comment by usmanalikhan93** [comment]
Hi @ochoaonline 

Let us check this again.

**Comment by ochoaonline** [comment]
@usmanalikhan93 Thanks

**Comment by Repair-Desk** [comment]
It appears that following labels are not transferred over.

Repair Tickets under repairs doesn't translate or its translation is not copied over
 
<img width="1280" alt="translate 3" src="https://user-images.githubusercontent.com/21986026/53861119-01292a80-4005-11e9-9987-3b8b5f705e6e.png">

![translate 2](https://user-images.githubusercontent.com/21986026/53861075-dc34b780-4004-11e9-960d-e37dccbe964c.jpg)


Also it would be great if there was a select all button so admin doesn't have to make 40 clicks

![translate](https://user-images.githubusercontent.com/21986026/53860974-84964c00-4004-11e9-86f4-9b0eda53410b.jpg)
