### ISSUE TITLE
Option to filter unpaid tickets

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#632]
Currently on tickets page there is no way to view against which tickets invoice has been paid. 

We need to add a filter that allow us to filter tickets that has no invoices

**Comment by Uzair-RepairDesk** [comment]
We have added search filters to view tickets with specific invoice status. Please check screenshot attached.
@Repair-Desk 
Can you please update the customer where he placed the request. Thanks
![uzairshah ticket](https://user-images.githubusercontent.com/22955861/52842715-c7f64c80-3121-11e9-92d3-08364bead10c.png)
