### ISSUE TITLE
Not being able to sale a serial without selecting the serial

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#634]
We need to not be able to sale a serial without selecting the serial.
<img width="1430" alt="screen shot 2019-01-30 at 11 57 05 am" src="https://user-images.githubusercontent.com/43588617/52006739-1cdf6500-248a-11e9-98b7-e212e006f0b2.png">

**Comment by Trevorshaw7** [comment]
Not 100 percent sure

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
