### ISSUE TITLE
We have a tablet not being able to look up on sales by item report

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#635]
We have a tablet not being able to look up on sales by item report
<img width="1425" alt="screen shot 2019-01-30 at 12 17 01 pm" src="https://user-images.githubusercontent.com/43588617/52006797-40a2ab00-248a-11e9-88af-ae3c8353e69a.png">
<img width="1427" alt="screen shot 2019-01-30 at 12 16 38 pm" src="https://user-images.githubusercontent.com/43588617/52006802-44363200-248a-11e9-821d-bca42edbbdba.png">

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1300

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

I hope you are doing well. We have made some improvements in Sales by item type report. I hope now this issue is resolved in it. If you face again this issue, you can open this task anytime. 

Thanks 
Usman Ali.
