### ISSUE TITLE
Expense Module

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#637]
If you copy $12 and then paste it into the column it will record 0

![e3685a59-6953-41e4-9dab-96c6524663d5](https://user-images.githubusercontent.com/21986026/52027069-e4906300-252b-11e9-88bc-16d4cbf18747.jpeg)

**Comment by Repair-Desk** [comment]
Adding a row its for the same expense code, would be cool if added row would be different expenses code and you can just add all 10 expenses from 1 shot

![e05996df-9163-44df-99cb-0d27edec56e3](https://user-images.githubusercontent.com/21986026/52027107-fffb6e00-252b-11e9-88c2-784151bdd400.jpeg)

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1278

**Comment by Uzair-RepairDesk** [comment]
We have made this improvement LIVE. If you copy and paste the value in amount for the expense. The system will pick up the value rather than 0.
