### ISSUE TITLE
Estimate Issue with Serial

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#638]
If you create an estimate for a serialized item when you convert it to an invoice it takes the serial off

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1274

**Comment by Uzair-RepairDesk** [comment]
Issue has been fixed
