### ISSUE TITLE
Repair services - inconsistent across integrations

### ISSUE THREAD

**Issue by brazelab** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#639]
Dear Repairdesk team,

I am experiencing some inconvenience

**Background**
We have recently introduced new names and pricing for our repair services.
We uploaded a new list of items. for all the old repair items, we have disabled the following triggers: Show on POS, Show on widget.

We don't want to delete the old items, because we dont want to lose ticket information and because they allow us to run the reports and review historical performance.

**Issue**
The old repairs are still visible in the ticket creation inside repairdesk. This is not the biggest issue, since we can instruct our team to not select the old repair services.

>> integrations
The old repairs are NOT visible to customers when using the calendar widget = This is good!

The old repair ARE visible to customers using the customer portal = not good!

**Expected solution**
We would expect the customer portal to have the same input as the calendar widget by not showing the old repairs.

I hope you can help,

Thanks!

<img width="1013" alt="1 repair services overview" src="https://user-images.githubusercontent.com/46997379/52050654-8aa29400-2551-11e9-908c-cd17aed5afe1.png">
<img width="578" alt="2 ticket calendar - only showing new items" src="https://user-images.githubusercontent.com/46997379/52050655-8aa29400-2551-11e9-868d-c266c89762e7.PNG">
<img width="1041" alt="3 customer portal - showing new and old items" src="https://user-images.githubusercontent.com/46997379/52050657-8b3b2a80-2551-11e9-8ae3-d61f6e5fd530.png">

**Comment by Uzair-RepairDesk** [comment]
Hey @brazelab 
Thank you for posting your suggestion. Currently, our customer portal is not linked with the "Show on Widget" trigger. 
I will discuss it with the team and revert back to you. Thanks

**Comment by brazelab** [comment]
Thanks Uzair,
Appreciate it

**Comment by Uzair-RepairDesk** [comment]
Hey Adeel @brazelab 
I have discussed it with the team. Currently, repair services for "Customer Portal" is linked with the trigger "Show on POS". If you disable the trigger, it doesn't display on Portal.
Can you please try at your end?
@usmanalikhan93 
Can you please verify it early next week? Thanks.

**Comment by brazelab** [comment]
<img width="477" alt="item triggers" src="https://user-images.githubusercontent.com/46997379/52476790-10e95680-2ba0-11e9-864a-3b306920c9fb.PNG">
<img width="608" alt="partner portal" src="https://user-images.githubusercontent.com/46997379/52476791-10e95680-2ba0-11e9-831e-3679321f683d.PNG">

I can confirm that the POS trigger is *not* linked to the partner portal

**Comment by Uzair-RepairDesk** [comment]
I am planning it for the next week Adeel @brazelab 
@usmanalikhan93 FYI

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1344

**Comment by usmanalikhan93** [comment]
Hi @brazelab 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by Uzair-RepairDesk** [comment]
Adeel @brazelab 
You can disable "show on widgets" trigger for repair services and they will not come up in "Customer Portal". 
Please review
