### ISSUE TITLE
Item populating with HTML codes | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#640]
**Hi Sir,**

**Business Name:**
Modesto | DrPhone Fix

**Store Name:**
Coral Spring

**Module:**
POS

**Configuration Setting:** Correct
**Roles & Permissions:** Correct

**Issue:**
Customer is facing an issue that once they try to populate any item on the POS screen the HTML codes are coming up in the suggestion box.

I am attaching relevant screenshots for the assistance.
![item populating wrong](https://user-images.githubusercontent.com/26381305/52056758-f18d7080-2584-11e9-9deb-85a5cfb68bbb.jpg)

**Comment by usmanalikhan93** [comment]
For internal use
https://repairdesk.atlassian.net/browse/REP-1293

**Comment by usmanalikhan93** [comment]
Hi @ali-repairdesk 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
