### ISSUE TITLE
Cayan - Some invoices are not marked as paid however they are paid in Cayan Portal

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#642]
We need to enable a log for Cayan transactions so that we know if a payment was initiated, collected or refunded. 

The log should be displayed in the invoice footer. 

Also the User Interface for Cayan transactions should be improved.

Icing on cake will be to add Key-ed transaction option

**Comment by Repair-Desk** [comment]
We're redesigning checkout which should fix the above issues.

When a transaction is approved following screen will be displayed:

![approved-1](https://user-images.githubusercontent.com/21986026/53937427-e4f1c000-40ce-11e9-9d77-1c828143b02b.jpg)

If there is an issue with transaction or payment is declined following screen will be displayed:

![decline-2](https://user-images.githubusercontent.com/21986026/53937505-26826b00-40cf-11e9-89ab-cedbcdc07c93.jpg)

When a transaction is processing following screen will be displayed:

![processing-payment](https://user-images.githubusercontent.com/21986026/53937440-ed49fb00-40ce-11e9-87cf-ae0ffc7b5e87.jpg)

**Note:** If a credit transaction is under process admin cannot click on confirm as it will be greyed out. Moreover if a transaction is taken admin cannot close the payment pop up and he will have to click on confirm to completed the payment.

**Comment by Uzair-RepairDesk** [comment]
**Update:**
We have updated payment process from Cayan with new pop up designs. 
Payment log from Cayan in Invoice footer is pending that will be done in next week. 
In-House Task Reference: https://repairdesk.atlassian.net/browse/REP-1749
