### ISSUE TITLE
Blocking Access to Change Name / Category of Items

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#643]
On the system, we created a control center location in the which we create / update items so the names, categories for these parts / accessories are the same across all locations, we also use a special category **Inventoried Screens / Inventoried Batteries** we would like for only super admins to be able to edit names / change categories for items that have already been created by Control Center, 
Currently we are having issues with employees changing Category (Item Type) and now when a store goes to do their inventory counts those items are no longer under the correct category and their counts are wrong / off since they dont include all items 

![drphonefix training pos edit mobile accessories parts ipad 2 back camera](https://user-images.githubusercontent.com/35181467/52131641-44aa0680-260b-11e9-9aa9-cfa564c41f4d.png)

**Comment by Repair-Desk** [comment]
@ #610

**Comment by Uzair-RepairDesk** [comment]
We have made this improvement LIVE. We have added new triggers under "Roles Permissions" of "Inventory" module. You can restrict employees of specific roles to change "Category", "Manufacturer" and "Device" from "Inventory" of RepairDesk.
Please check screenshot attached.
![uzairshah   Roles Permission](https://user-images.githubusercontent.com/22955861/56583041-175d6b00-65f2-11e9-9cd3-9084350d30df.png)
