### ISSUE TITLE
Options to Control Payments Options for POS / Register

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#644]
If there can be an option to have payment types be separated, to control payment types for POS side separate from payment types for Expense module, i went ahead and added many types like Check, ACH, and other methods to the payment types to use on expense module now those are also showing on POS side when trying to check out and store's dont use those methods 

**Mainly should be 3-4 Methods top for stores**
CASH | CAYAN | OFF LINE CC | SQUARE TRADE

![drphonefix training pos pos](https://user-images.githubusercontent.com/35181467/52132060-5344ed80-260c-11e9-9ef3-b9f9f93f08bd.png)

**Comment by Repair-Desk** [comment]
Note for developers: When this option is added make sure "show on POS" is automatically enabled for all customers so that they can go and switch it off when required

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk @Repair-Desk  can we increase the priority of this, also something that can probably fix it also if its not Business Wise, only location wise, because if i delete a payment type from one location or add it will add or delete it in all

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
I have prioritized it and adding it in the plan. Thanks

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 

We have made this improvement LIVE. 
A new trigger called “Show on Checkout” has been added against every payment method in the ‘Store Settings’ that will let you select what methods of payment would you allow to display on checkout or while adding payment. 
You can disable it for the payment methods that you only use while recording the expenses. 
Check screenshot attached
![uzairshah paymentmethods](https://user-images.githubusercontent.com/22955861/54013288-5cd8ec80-419a-11e9-8210-57dd10f51a32.png)

Please review at your end. Thanks
