### ISSUE TITLE
Inventory summary store name is not the alternate anymore

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#645]
<img width="600" alt="screen shot 2019-02-01 at 4 52 33 pm" src="https://user-images.githubusercontent.com/43588617/52155805-e2b8c380-2641-11e9-83fe-bbb4889694e3.png">

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
