### ISSUE TITLE
Total Revenue by Customer Report Issue While Exporting to CSV

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#646]
When exporting the Total Revenue by Customer Report the following outlets will not export:
Valley Fair
West Valley
Draper

![unnamed](https://user-images.githubusercontent.com/21986026/52160003-7df77a80-26ce-11e9-817c-4a836d10cdb4.png)

**Comment by usmanalikhan93** [comment]
Hi @Repair-Desk 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
