### ISSUE TITLE
Open shift function

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#648]
Currently RD allows you to take payment and create invoices without starting a shift.

During this process you are alerted to start the shift but you can simply cancel the dialogue box and continue on.

If this is done, EOD payments are completely out of whack.

The system needs to prevent users from taking any form of payment unless the shift is started and the day has started.

**Comment by Uzair-RepairDesk** [comment]
Hey Will @TechreviveAu 
Thank you for your post. As you mentioned, we already notify admin/users to start a shift on the POS screen if there is no shift log so admin/users must start a shift. 
Do you want us to add a trigger to don't allow the user to make any transaction from POS if the shift is not started?

**Comment by TechreviveAu** [comment]
Yes this would be a great idea

**Comment by Uzair-RepairDesk** [comment]
Hey Will @TechreviveAu 

Good News. We have made your suggested improvement LIVE. A new trigger named as ‘Mandatory to start shift’ has been introduced under ‘**Store Settings > Cash Register Settings > Module Configurations**’ to keep accurate records of all the cash inflows and outflows. If this trigger is enabled, the employees must start their shift to make a payment transaction.

Please review at your end.
