### ISSUE TITLE
Clock in / out issues

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#649]
Currently staff can click in, out or start a break.
They can also edit their times for each.

This needs to be prevented and should only be edited with an admin role or an admin pin to stop dishonest staff or overpaying a staff member

**Comment by Repair-Desk** [comment]
@TechreviveAu Happy to help with this. Currently under employee roles and permission, we have a trigger that allow you to set access for who can update the clock in time

**Comment by TechreviveAu** [comment]
Hi there,
Technician in question is set up as a "technician" with restricted access. Under his permission settings the "Edit" field for clock in/clock out is missing and can physically edit his own hours without an admin pin.

What you have mentioned in your statement above is not correct for our RD account.

**Comment by Uzair-RepairDesk** [comment]
Can you elaborate this Will @TechreviveAu ?

**Comment by TechreviveAu** [comment]
Essentially I don’t want my staff to be able to adjust their own time sheets with out a managers pin being entered
