### ISSUE TITLE
WordPress integration overhaul

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#650]
WordPress integration is terrible and needs to be completely overhauled. Ongoing issues with syncing products and it's very easy to duplicate products each manual / auto sync.

Is this on the cards ?

**Comment by Uzair-RepairDesk** [comment]
Hey Will @TechreviveAu 
We improved Woo-Commerce integration in the last quarter and it's quite working well for most of the customers.
Can you please let me know what are the specific concerns you have with the integration so I can assist you accordingly. Thanks.

**Comment by TechreviveAu** [comment]
last time it was used we had problematic syncs and duplicate products created.
it has since been disabled however I will re-test and revert back

**Comment by Uzair-RepairDesk** [comment]
We already fixed syncing and duplication problem Will @TechreviveAu 
Please review and let me know. Thanks
