### ISSUE TITLE
CFD slow / overhaul

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#651]
Customer front facing display is slow, at times re displays prior tickets for signature and the "accept terms" check box takes for ever to enable.

**Comment by Repair-Desk** [comment]
@TechreviveAu We're re-writing customer facing display module and looking to relaunch it before end of this quarter. I've attached designs for your perusal.

![customer-signature](https://user-images.githubusercontent.com/21986026/52413340-25c3dc80-2b03-11e9-927b-02833fe0b136.jpg)

![select-products-1-a](https://user-images.githubusercontent.com/21986026/52413341-25c3dc80-2b03-11e9-8509-a109fb50e964.jpg)

![store-terms-and-conditions](https://user-images.githubusercontent.com/21986026/52413343-25c3dc80-2b03-11e9-97ae-bc6469f8af78.jpg)

**Comment by TechreviveAu** [comment]
Looks amazing!

**Comment by Uzair-RepairDesk** [comment]
**Update**: We have completed the design and HTML of front and backend. We will proceed with development from next week. 
Backend design is also attached
![configuration-settings-2](https://user-images.githubusercontent.com/22955861/53226187-211f2c80-369c-11e9-8223-d3fb07261cdc.jpg)

**Comment by Uzair-RepairDesk** [comment]
Linked with #571

**Comment by Uzair-RepairDesk** [comment]
Hello Will @TechreviveAu 
We have made "Customer Facing Display" module LIVE. You need to reconfigure account settings related to the Customer Facing Display, on both the web platform and the iPad POS Register app. You can find more details from following knowledgebase article:-
https://repairdesk.uservoice.com/knowledgebase/articles/1102397-how-to-configure-customer-facing-display
