### ISSUE TITLE
Purchase order issues

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#652]
Ongoing issues with purchase order module.
Incorrect calculations for line items and total cost.
Takes 4 to 5 times longer than it should.

" Need to add inclusive / exclusive tax option for each line item.

* Option to pay and complete a purchase order / grn without affecting daily takings (paid via external source)

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 Can you please check this tomorrow?

**Comment by usmanalikhan93** [comment]
Hi Will @TechreviveAu 

I hope you have done screen share with Danish Hassan and all is good. :)
