### ISSUE TITLE
Report by Supplier

### ISSUE THREAD

**Issue by ChelseyShannon** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#653]
I wanted to request an improvement that has become extremely essential the balancing my clients accounting books. They have requested to be able to pull a report by supplier. When I uploaded all the inventory it had a column for suppliers but there is no way to see what inventory has been sold by supplier name. Please let me know your thoughts on possibly adding this to the sales by item report, simply with a drop-down "Suppliers" Thank you very much

**Comment by Uzair-RepairDesk** [comment]
Hi @ChelseyShannon 

I really appreciate that you took the time to share your idea.
I can certainly see how the suggested improvements would be useful. We can certainly add supplier criteria in "Sales by Item type" however the only challenge to apply it if there is "Multiple Supplier SKU's" or "Serialized Inventory" exist for the items. 

I will discuss it with the team to check the possibility to add it so we can add it in the roadmap. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey @ChelseyShannon 
We have made your suggested improvement LIVE. We have added criteria by "Supplier" in "Sales by Item Type" report. 
Please review at your end. Thanks
