### ISSUE TITLE
Color in device

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#656]
Hello,
We are able to choose in a "device" what color it is. Black & white example. Why when the device is programmed with the color black and white (example), we are not able to see the colors in the POS? The color is therefore useless. I would like to be able to choose the color so as not to have to create the same problem twice (once in the dark and once in the white). This will allow you to program the bundles correctly. See picture I did for your understanding.

<img width="939" alt="colorrr" src="https://user-images.githubusercontent.com/40500094/52449597-e945b000-2b05-11e9-8986-f7b1d4672eaf.png">

--
french:
Bonjour,
Nous sommes en mesure de choisir dans un "device" de quelle couleur il est. Exemple noir & blanc. Pourquoi lorsque le device est programmé avec la couleur noir et blanc (exemple), nous ne somme pas en mesure de voir les couleurs dans le POS? La couleur ne sert donc à rien. J'aimerais être capable de choisir la couleur pour ne pas être obligé de créé le même problème deux fois (une fois dans le noir et une fois dans le blanc). Ceci permettera de programmer correctement les bundle. Voir image que j'ai fait pour votre compréhension.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
Currently, it is not possible to add an extra step to choose color of the device. However, we introduced the "Custom Fields" functionality that allows you to add the "Color" field to input the color of the device on the details page of the ticket. 
You can learn more about it from the following knowledgebase article:-

https://help.repairdesk.co/knowledgebase/articles/1921693-custom-fields
