### ISSUE TITLE
Sales By Item Type - Option to filter sales by suppliers

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#657]
I wanted to request an improvement that has become extremely essential the balancing my clients accounting books. 

They have requested to be able to pull a report by supplier. When I uploaded all the inventory it had a column for suppliers but there is no way to see what inventory has been sold by supplier name. Please let me know your thoughts on possible adding this to the sales by item report, simply with a drop down "Suppliers" 

Chelsea

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk 
He has already requested the above improvement here #653
