### ISSUE TITLE
Ticket / Invoice number displayed in POS

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#658]
It would be great to have the invoice number / ticket number displayed in POS when ticket has been confirmed and receipt prints.

**Comment by Uzair-RepairDesk** [comment]
Hey Will @TechreviveAu 
Can you highlight it with a screenshot where you exactly referring it? Thanks

**Comment by TechreviveAu** [comment]
Sure thing

**Comment by TechreviveAu** [comment]
![untitled](https://user-images.githubusercontent.com/46398112/52475995-63069800-2bf1-11e9-8b93-e91ee35a2712.png)

**Comment by Uzair-RepairDesk** [comment]
It can only be possible if you reopen ticket/invoice on POS and checkout Will @TechreviveAu

**Comment by TechreviveAu** [comment]
ok no worries thanks Uzair
