### ISSUE TITLE
Location Sales By Item Type Report on Dashboard is not working | Deepak Sharma | Apps Plaza

### ISSUE THREAD

**Issue by faizanzaheer** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#659]
**Business Name / Store Name:**
Deepak Sharma | Apps Plaza

**Customer Credentials:**
Shared on Jira

**Module:**
Reports

**Configuration Setting:** Correct
**Roles & Permissions:** Correct

**Issue:**
Location Sales By Item Type Report on Dashboard is not working

**Steps to Reproduce Issue/Provide Video:**
a) Go to Reports >> On dashboard if you click to open the Location Sales By Item Type Report it is not working. (As shown in the picture below)
![deepak](https://user-images.githubusercontent.com/34411411/52455718-4b88ca00-2b73-11e9-97e5-4b8140e40057.png)

**Current Results:**
Location Sales By Item Type Report on Dashboard is not working

**Expected Result:**
Location Sales By Item Type Report on Dashboard should show Repairs and Products Data

**Comment by usmanalikhan93** [comment]
For internal use
https://repairdesk.atlassian.net/browse/REP-1319

**Comment by usmanalikhan93** [comment]
Hi @faizanzaheer 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
