### ISSUE TITLE
Tax issue 

### ISSUE THREAD

**Issue by wirelessrepairzone** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#664]
In one of the recent updates both "Charge tax on replacement part cost price" and "Charge tax on replacement part retail price" were turned on in our system. We are in Michigan so we only charge tax on the retail cost of the part not on the full price. With both options turned on the system only charges tax on the cost of the part not the retail this caused us to uncharged the customer on every repair. Shame on us for not checking it but when we went to look at this quarters tax estimates we found the error we are still calculating how much this is going to cost us.

**Comment by usmanalikhan93** [comment]
Hey @wirelessrepairzone 

I hope our support guy Faizan Zaheer has guided you on this. And do let us know if you have any question. 

Thanks. 
Usman Ali
