### ISSUE TITLE
Problem with the cost of RMA labels

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#666]
Hello,
RMA labels have changed. This is not a problem because we can change them. However, as soon as we remove the cost price (because we do not want everyone to know the cost price) the details "reason" and "RMA #" automatically clears. See picture.
Thank you to correct quickly.
<img width="939" alt="rma classic" src="https://user-images.githubusercontent.com/40500094/52644051-2c0fdb00-2eac-11e9-828f-97262bc650d3.png">
<img width="939" alt="rma without cost price" src="https://user-images.githubusercontent.com/40500094/52644061-2fa36200-2eac-11e9-8eda-d92211fe3e71.png">

--
French :
Bonjour,
Les étiquettes RMA ont changé. Ce n'est pas un problème, car nous pouvons les modifier. Cependant, dès que nous retirons le cost price (car on ne veut pas que tous le monde connaisse le cost price) les détails "reason" et "RMA #" s'efface automatiquement. Voir image. 
Merci de corriger rapidement.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 Can you get it checked

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
For Internal Use:
https://repairdesk.atlassian.net/browse/REP-1375

**Comment by JessicaSOS** [comment]
That's gonna be fixed this week ?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

It is fixed and on beta server. Hopefully we will go live with this in this week release. I will update you once it will be available on live server.

**Comment by JessicaSOS** [comment]
Ok, i await yours news, tnx

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 5 mars 2019 23:26
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Problem with the cost of RMA labels (#666)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

It is fixed and on beta server. Hopefully we will go live with this in this week release. I will update you once it will be available on live server.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
fixed tnx
