### ISSUE TITLE
Click on Store Name Behavior | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#668]
**Hi Sir,**

**Business Name / Store Name:**
Modesto | DrPhone Fix

**Module:**
Store Settings

**Configuration Setting:** Correct
**Roles & Permissions:** Correct

**Improvement:**
Customer has reported an improvement that once once you click on Store Name, it should redirect to the home page.

So lets suppose you were viewing Transaction Log on Weston Store and you switched to Cape Coral. You will see the Transaction page window however if you hit once again Cape Coral, it will redirect you to Dashboard of Cape Coral Store.

I have discussed this issue with development team and we will be working on it. 

**Current Results:**
Once we click on Store Name, it stays on the same page.

**Expected Result:**
Once we click on Store Name, it should bring it to Dashboard

**Comment by ali-repairdesk** [comment]
Internal Task Link:
https://repairdesk.atlassian.net/browse/REP-1373

**Comment by usmanalikhan93** [comment]
Reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.
