### ISSUE TITLE
Issue with Purchase Order and RMA | Shahzad Pirani | iRepairIT

### ISSUE THREAD

**Issue by faizanzaheer** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#670]
Hi Sir,

**Business Name / Customer Name:**
• Shahzad Pirani | iRepairIT

**Customer Credentials:**
[Jira reference ](https://repairdesk.atlassian.net/browse/REP-1255)

**Issue:** The Customer wants more Search Options when Creating a Purchase order or an RMA besides SKU/ID or Name. He wants to be able to search Items according to Manufacturer and Devices when he is creating an RMA or a Purchase Order. I can see that Selecting Criteria option can also be used Like the one provided in the Inventory Summary Report.

The Customer is also looking to Improve the Search Bar of the Purchase order, the search bar only fetches an Item according to its name. It should also show the option when a device or a Manufacturer name is written there.

Thanks

**Comment by Repair-Desk** [comment]
@faizanzaheer Thanks for submitting enhancement request in Purchase order on behalf of iRepairIT team. We will review it with the product team and update the thread early next week.

Working together,
Usman

**Comment by Uzair-RepairDesk** [comment]
**Update:** I will get the story for this improvement in this weak so we can prioritize and add it in next week sprint.

**Comment by fahadimran303** [comment]
Internal task link:
https://repairdesk.atlassian.net/browse/REP-1255

**Comment by usmanalikhan93** [comment]
Hey @faizanzaheer @fahadimran303 

We have lived this improvement. Please update iRepairIT team as per discussion. 

Thanks
