### ISSUE TITLE
STEND TIMEOUT / DELAY ON PO SCREEN / AUTO SAVE

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#671]
Is there any way we can increase the delay time before screen times out on PO , when they are creating a large PO, the screen times out and they lose the information and have to Recreate the PO, they also reported similar issue on the Inventory Counts , it timed out and didnt auto save.

**Comment by Repair-Desk** [comment]
@ochoaonline #
Usman here 👋 Sure thing! Let us take a look to see if we're getting the same issue as you and I'll circle back to you.

@usmanalikhan93 Please check timeout time on Purchase order with Fayyaz.

@ochoaonline do you think option to create purchase order using a CSV/xls file will help?

**Comment by usmanalikhan93** [comment]
Sure @Repair-Desk

**Comment by ochoaonline** [comment]
@usmanalikhan93 it would speed up process, for some stores that are CSV / Excel savy vs having to type it in manually

**Comment by ochoaonline** [comment]
@Repair-Desk @Uzair-RepairDesk 
Additional idea, can PO side be scannable like we can use the gun to scan item we want to order, each store can have a binder with items and they just scan UPC Code x amount of time for how many items they need

**Comment by usmanalikhan93** [comment]
Hi @ochoaonline 

Can you help me that how many items you are adding in PO/Count when it timed out ? Just need an estimate, it will help in replicating this issue.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1397

**Comment by usmanalikhan93** [comment]
Hi @ochoaonline 

I have tried to reproduce this issue but unable to reproduce it, I have added more than 50 items after some interval of time and also make it idle for half an hour it doesn't timed out. 
Video link: https://www.screencast.com/t/LLyJmjpDu

Can you please help us in replicating this issue ?

**Comment by usmanalikhan93** [comment]
Hi again Modesto@ochoaonline   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by ochoaonline** [comment]
@usmanalikhan93  yes we can disregard this one for now, no one else has reporting anything else towards it so not big priority on it thanks
