### ISSUE TITLE
Copy selected language to other store

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#672]
In the "Language Editor" widget, the "copy selected language to other store" option does not work. After clicking on the language and then selecting the stores, I click on "proceed". A message mentions me "laguage is copied successfully". However, the translation does not copy (see example). This is one of the examples of translation.

<img width="942" alt="language copied" src="https://user-images.githubusercontent.com/40500094/52791152-4bd30a80-3036-11e9-9813-e7026d33d5da.png">
<img width="938" alt="language limoilou store" src="https://user-images.githubusercontent.com/40500094/52791215-6dcc8d00-3036-11e9-9eb4-2886a6f22ae9.png">
<img width="941" alt="language levis store" src="https://user-images.githubusercontent.com/40500094/52791283-981e4a80-3036-11e9-9839-706a12606ce8.png">

_--
french:
Dans le widget "Éditeur de langue", l'option "copie selected language to other store" ne fonctionne pas. Après avoir cliquer sur la langue puis avoir sélectionné les magasins, je clique sur "proceed". Un message me mentionne "laguage is copied successfully". Cepeandant, la traduction ne se copie pas (voir exemple). Ceci est un des exemples concenrnant la traduction._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can I try to copy language from limoilou store to levis store just for testing ?

**Comment by JessicaSOS** [comment]
Yes you can

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 15 février 2019 06:21
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Copy selected language to other store (#672)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

Can I try to copy language from limoilou store to levis store just for testing ?

**Comment by JessicaSOS** [comment]
yes you can

**Comment by Repair-Desk** [comment]
@usmanalikhan93 What's the latest on this?

**Comment by usmanalikhan93** [comment]
@Repair-Desk 
Just trying to reproduce a use case. It is creating issue but it's coming random. I will work with dev on this today.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1430

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.

**Comment by JessicaSOS** [comment]
Fixed tnx !
