### ISSUE TITLE
Delete Device Physical Locations

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#673]
![image](https://user-images.githubusercontent.com/35181467/52813212-47731580-3067-11e9-807b-ad0c6205e4a6.png)
System has 85 Pages of Device locations with just numbers can we delete them all to be able to add our own, Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
Do you want to delete all of them?

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk yes please, only one to have a yes and no option on all the stores we will currently be using it to upsale tempered glass

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
I didn't get the following point:-
"only one to have a yes and no option on all the stores we will currently be using it to upsale tempered glass"
I have asked Fahad to ask details over the call.

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk just the deleting is fine, i'll take care of the yes and no part thanks

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you create a task for this and add it in sprint so it can be done in next week.

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1468

**Comment by usmanalikhan93** [comment]
Hi Modesto@ochoaonline

We have deleted your Device Physical Locations. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali.

**Comment by ochoaonline** [comment]
Thank you
