### ISSUE TITLE
Custom fields - appointment calendar widget

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#674]
I’d like the ability to add custom fields to the appointment calendar widget on our website
Specifically on the customer details page. Can this be acheIced easily and quickly?

**Comment by Uzair-RepairDesk** [comment]
Hey Will @TechreviveAu 
I really appreciate that you took the time to share your idea.

I can certainly see how the suggested improvements would be useful. You can set custom fields of your choice and customer can fill the required details while booking an appointment from the widget. However, with a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this for now. 
We have plan to improve the UI/UX of Appointment Calendar widget in upcoming quarters and I can certainly keep an eye on this once we start working on it. 

I hope that if there’s anything else I can do for you, you won’t hesitate to let me know. Thanks

Regards,
-Uzair from RepairDesk-
