### ISSUE TITLE
Line item discount - iPad app

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#675]
If you are based out of Australia, all items should be GST inclusive.

let me explain it.

On a $65 Inc tax item, when a $10 discount is applied it should total $55

The ipad app treats the discount as an ex tax figure. Please look into it ASAP and release a fix in next version.

Also check this scenario in the web app.

Customer: iBroken Australia

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk 
I believe it's according to the standard formula applies on Tax inclusive item with "In-line amount discount". 
In case of tax inclusive item/service, the discount applies on "Base Price" and then apply a tax on discounted value. This is a specific reason it calculates "Total" value accordingly. 
We have the same scenario's in both web and iPad app.
