### ISSUE TITLE
IPad app crashes 

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#676]
When you are booking a new repair and go to parts screen to select part.

If the part is a serialize item you can select it however when you hit save the app crashes.

Customer: Jason | iBroken

**Comment by Repair-Desk** [comment]
Crashes when adding inventory items but only during the first time. It works most of the time if creating the ticket first.

**Comment by Uzair-RepairDesk** [comment]
It was already reported by QA and fixed with the new release. 
In-House Task Reference:-
https://repairdesk.atlassian.net/browse/RI-445
@Repair-Desk 
Please update customer or let me know about the source so I can do the needful. Thanks
