### ISSUE TITLE
CATEGORIES / NEW ITEMS / ITEM NAMES

### ISSUE THREAD

**Issue by Uzair-RepairDesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#677]
No one under any role other than changes being made under control center and 
by Super Admins, should affect / make changes on any other store

Shouldn’t be able to make changes to
Existing Devices (Manufacturers, Categories , etc.)
Existing Services (Manufacturers, Categories , etc.)
Existing Inventory items / Parts (Manufacturers, Categories , etc.)
Is ok for them to add new device / new part as long as it’s not already in system, and for it to only show up on their store not all stores.

When someone adds a new category on a regular store does it add it to all our stores, and if it does can we remove this feature

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk you can maybe can combined this one with #643

**Comment by Uzair-RepairDesk** [comment]
We have made this improvement LIVE. We have added new triggers under "Roles Permissions" of "Inventory" module. You can restrict employees of specific roles to change "Category", "Manufacturer" and "Device" from "Inventory" of RepairDesk. 
Please check screenshot attached. 
![uzairshah   Roles Permission](https://user-images.githubusercontent.com/22955861/56582960-e3824580-65f1-11e9-9df8-801e8e4f7c1c.png)
