### ISSUE TITLE
RMA Feedback - Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#678]
Hell Team,

Feedback of RMA will be shared in the comments.

Regards,

**Comment by ali-repairdesk** [comment]
Internal Task Link:
https://repairdesk.atlassian.net/browse/RD-86

**Comment by Uzair-RepairDesk** [comment]
Requested improvement listed here #614

**Comment by ali-repairdesk** [comment]
This is covered in below ticket:
https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/711

So closing this ticket after discussing with Modesto.
