### ISSUE TITLE
RMA Set Sent to Supplier Not in Parts Admin History - DrPhoneFix

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#680]
RMA-069 under HQ Retail iPhone 7+ Battery, RMA was sent to supplier but does not show on the history 
![hq retail battery](https://user-images.githubusercontent.com/35181467/53114057-f18fe900-3510-11e9-8466-a526420a22f8.png)
and the inventory of item did not get adjsuted

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Please check this

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
Hi @ochoaonline 

I hope you are doing well. I have checked your concern but It does show in history if you make RMA of an item. Can you guide how you are making RMA of this item ? It will be helpful for us to track the the issue. 

Thanks 
Usman Ali

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Also discuss it with Fahad today and he can confirm it from Modesto @ochoaonline

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1403

**Comment by usmanalikhan93** [comment]
Hi @ochoaonline 

I hope you are doing well. We have added logs against RMA. We hope you will note face this issue again. 
In any confusion or you have any question you can ask Fahad or message here so we will look into it ASAP.

Thanks!
Usman Ali.
