### ISSUE TITLE
Birthday / Marketing / Promo 

### ISSUE THREAD

**Issue by Bluepointrepairs** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#681]
Hi guys!

I like to know if on New Costumers Tab: can u guys add a new field call DOB.

so the system can auto send a **Electronic Birthday Card** **and a Alert in our POS System**, so we can call them with a Gif in store using a QRCode or Bar Code, and the gifts can be like a Free Temper Glass, a Free Case, a Free USB Cable, Headphones, Holders, 10% off  =, Etc Etc, or anything in our choice, who code expired with in the next 5 days  or so from the date of the email.

so we can promote, marketing, and bring back those Costumers in Another way

**Comment by Uzair-RepairDesk** [comment]
Hey @Bluepointrepairs 

I really appreciate that you took the time to share your idea.
I can certainly see how the suggested improvements would be useful. It will really help to delight and retain your existing customers. 

However, with a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. 
At the moment, we won’t be able to make it right now but I am adding it to our enhancements plan so we can discuss it in-house. Thanks

Regards,
Uzair
