### ISSUE TITLE
"Ticket Status, Assigned to" to be a cleaner Drop Down Menu and alphabetically- DrPhoneFix

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#682]
if we can make it so we can see all status available, when you click to change status you only see a few
![image](https://user-images.githubusercontent.com/35181467/53186062-4a718700-35ce-11e9-9534-4f4efb6c7c03.png)
Vs the way it look on front side POS
![image](https://user-images.githubusercontent.com/35181467/53186136-61b07480-35ce-11e9-8bf6-e1c8f0475f79.png)
or the way assigned tech looks on ticket side which is a full dropdown list and you an easily see what tech you want to assign it

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline, 
It already gives a complete list of status. Do you want to change the view to view all the status with complete text?

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk  it does not give you a complete list, after the dropdown is open you have to scroll down or search to find the right status you need , on the ticket side it only shows like 4 status, vs front end on POS it shows 16+

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk 

I believe most commonly used status should display first or they should be sorted alphabetically. Github issue tracker has a really great label dropdown which we can use for the same :)

**Comment by Uzair-RepairDesk** [comment]
I will see the best possible solution and add it in the sprint as per the priority list of Modesto. @ochoaonline

**Comment by Uzair-RepairDesk** [comment]
We also need to display employee name in Assigned To dropdown alphabetically.

**Comment by Uzair-RepairDesk** [comment]
Hey @ochoaonline @Repair-Desk 
We have made this requested improvement LIVE. You can now see a cleaner dropdown list for status while selecting it from Manage ticket or View/Edit ticket screens. We have also improved the dropdown list of "Assigned to" and it will display employee names alphabetically. 
Please review at your end and share your feedback. Thanks
