### ISSUE TITLE
* * * URGENT * * * Trouble with all emails ! * * *

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#683]
When we send an email via a ticket, we see the green message "the email was sent successfully". However, when we wake up the message, it is written "Not translated data!" In replacement text of the initial message. The message guesses cleared. See picture.
Thank you for settling quickly, because all our communication is reached!
<img width="561" alt="not translated data" src="https://user-images.githubusercontent.com/40500094/53191589-3469c380-35da-11e9-8b50-b59d7ef70c11.png">
![in ticket](https://user-images.githubusercontent.com/40500094/53191637-5400ec00-35da-11e9-9613-1fd3575939f9.JPG)

--
Lorsque nous envoyons un courriel via un billet, nous voyons le message vert "le courriel a été envoyé avec succès". Cependant, lorsque nous reveons le message, il est inscrit "Not translated data! " en texte de remplacement du message initial. Le message devine effacé. Voir image.
Merci de réglé rapidement, car toute notre communication en est atteinte !

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you please verify at your end ? We have release a fix for this, now it showing correct email. Please do let us know if you have any question. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS   - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by JessicaSOS** [comment]
fixed
