### ISSUE TITLE
Custom canned responses

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#685]
I lost some of my programmed responses I made before changing the "notification" settings tab. Can you give me the messages or the source code of these please.

--
J'ai perdu certaines de mes réponses programmées que j'avais faite avant la modification de l'onglet "notification" des réglages. Pouvez-vous me redonner les messages ou le code source de ces dernières svp.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sure, Let me check this with developer.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you specify which were missing ?

**Comment by JessicaSOS** [comment]
It misses more than one but among others that concerning refunds. "remboursement"

**Comment by usmanalikhan93** [comment]
Ok. Let me check this with developer.

**Comment by usmanalikhan93** [comment]
For internal Use:
https://repairdesk.atlassian.net/browse/REP-1525

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Here is your HTML source code for "remboursement" 
[remboursement.txt](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/2929860/remboursement.txt)

Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali
