### ISSUE TITLE
Technician Performance

### ISSUE THREAD

**Issue by cupell08** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#686]
Productivity report is (almost) perfect.  It doesn't show amounts connected to tickets where that technician is assigned,but did not originally create/generate the ticket. 

For example, sales person "Tyler" creates ticket and Assigns Tech "Ben" , under this report the amount that Ben invoices in that ticket would only show under Tyler's productivity Report and not Ben's.

Now when I run report it says Ben isn't bringing in any money , despite the fact that he is the one doing all the work

A workaround suggested to us, was to have front sales people end create ticket , then allow the technician to create invoice. This did work, amounts started showing under the technician BUT there are two issues:

1) it's  tedious for the tech to remember to create  invoice

2) if technician were to complete the ticket, create invoice, and then go back and make an edit,it goes back under the sales person that originally created the ticket for some reason, seems like a glitch

Please advise, we really need the productivity report to show how much money the techs are bringing in instead of all those amounts going to the sales person that originally created the tickets.

**Comment by Repair-Desk** [comment]
Can we add a filter to display sales by technician?

**Comment by cupell08** [comment]
Would that solve our issue? Can you explain more what that would do

Thanks for the reply!

**Comment by Uzair-RepairDesk** [comment]
Hi @cupell08 
This is Uzair from RepairDesk. 
I suggested the above workaround to you so you can get the sales insights with respect to your technician. 

**_Please find my comments to both of your concerns below:-_**
1. it's  tedious for the tech to remember to create  invoice
**When a technician edits the ticket and saves it, RepairDesk automatically gives a notification to ask if the user wants to create an invoice. You can make sure that a technician should create an invoice at that time. Please check screenshot attached** 
![1](https://user-images.githubusercontent.com/22955861/53222385-56714d80-368f-11e9-8b67-a9ae351ca1da.png)


2. if technician were to complete the ticket, create invoice, and then go back and make an edit,it goes back under the sales person that originally created the ticket for some reason, seems like a glitch
I just tried the above case at my end and it doesn't change the employee reference on the invoice. When **I complete the ticket from manage ticket and update the invoice, it still keeps the same reference of the invoice. Can you please let me know what are the exact steps you follow that you face this glitch? Is it possible that I can give you a call and we can discuss it so I can see your workflow and advise you accordingly. Thanks**

**Comment by Uzair-RepairDesk** [comment]
Hi Marcus @cupell08 
As discussed over WhatsApp, let's connect on Monday same time so I can view your workflow and advise accordingly. Thanks.

**Comment by Uzair-RepairDesk** [comment]
Hey Marcus @cupell08 
As discussed over the call, I have reported the issue to the development team with Urgent priority so it should keep the same employee name who created the invoice rather than updating it with the employee name who created the ticket if you update it from Manage Tickets section.
I will update you once it's fixed. Thanks.

**Comment by Uzair-RepairDesk** [comment]
Hey Marcus @cupell08 
I am pleased to inform you that your reported issue has been fixed. 
It will keep the same username that creates the invoice when you update the ticket and save it. 
Now you will be able to view the sales analysis with respect to the technician when you will follow the above workflow and allow your technician to create an invoice. 

Please review at your end and confirm. Thanks

Regards,
Uzair

**Comment by Uzair-RepairDesk** [comment]
We have fixed the issue and i have informed to Marcus @cupell08 over Whatsapp.
