### ISSUE TITLE
repair in progress email

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#687]
typo in the spelling of this macros but more importantly its not working, i renamed to receipt just to test and that didnt populate either

![image](https://user-images.githubusercontent.com/37640713/53216137-3dc65080-3619-11e9-999c-c11c0c45f61a.png)
![image](https://user-images.githubusercontent.com/37640713/53216142-41f26e00-3619-11e9-87fb-55604b39f2ea.png)

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1487

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw
