### ISSUE TITLE
clicking part order in ticket under inventory item changes ticket status to "waiting for parts"

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#688]
![image](https://user-images.githubusercontent.com/37640713/53221131-a15a7900-362d-11e9-830a-1f35df913d1b.png)

The reason this is a problem, I have that default status inactive/disabled. I use my own called "parts ordered" but it changes it automatically to a status I have as inactive. Can you either make it not auto-change, or have it a setting to choose which status it turns to?

**Comment by Uzair-RepairDesk** [comment]
Hi @phonefixdfw 
Currently, its a system default behavior. When you add a part for special order system changes the status to "Waiting for Parts". 
If you don't want to keep the default status, I recommend you to manually change the status from same view/edit page of a ticket to "Parts Ordered" from "Waiting for Parts" once you place an order for the ticket part item.
Hope it helps.

**Comment by phonefixdfw** [comment]
the problem is, its sending email notificaiton when it changes it
automatically to "waiting for parts" even though i dont have it set to do so

its not possible to make an option to select a status as default vs keeping
same default?

**Comment by Uzair-RepairDesk** [comment]
Hi @phonefixdfw 
We have introduced new functionality for special part ordering. You can create a special part order request and you can also create a PO for the special order. You can also disable the automatic notification to customers when you create a special part order and status is marked with "Waiting for Parts". You can learn more about it from the following knowledgebase article:-

https://help.repairdesk.co/knowledgebase/articles/1949434-how-to-use-special-order-for-non-catalogue-items

Hope it helps
