### ISSUE TITLE
Payments Received Currently has Tax included - DrPhonefix

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#689]
Can We remove the taxes from payments received please we use payments received as our method to charged Franchise fee, and taxes are not included in franchise fee payments 

![drphonefix cape coral dashboard](https://user-images.githubusercontent.com/35181467/53261021-faafc000-36a0-11e9-9d00-40f34a3c1ba1.png)

![drphonefix cape coral registersales stats](https://user-images.githubusercontent.com/35181467/53261025-fd121a00-36a0-11e9-85f3-6450dba1de5c.png)

**Comment by Repair-Desk** [comment]
I believe we should have a filter in the right which has following option

With tax
Without tax

This option should be available in store setting as well so they can setup against business profile.

So if there is a customer in australia who wants to see his sales he wants them GST inclusive

**Comment by ochoaonline** [comment]
@Repair-Desk Filter works for everyone :)

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk As per today's meeting please discuss your challenges with @ochoaonline and move forward accordingly

**Comment by Uzair-RepairDesk** [comment]
We are going to introduce a new report with reference #690 so "Payment Received" will actually be a "Net Sales" value without tax. There will also be "Gross Sales" value that will also actually Payment Received with tax (Cash Basis). 
There will also be "Franchise Fee" field that will be applied on "Payment Received / Net Sales (Without Tax) once you set the criteria on the basis of "Payment Received".
