### ISSUE TITLE
Daily and Hourly Sales Report but via Payments received not Accrued Basic

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#690]
If we could have a  Daily Sales / Sales by Hour report similar to these pictures below,
but for it to be Cash Basis (Payments Received) so we can track the actual daily sales of each store 
Thanks 
![sales by day lightspeed retail](https://user-images.githubusercontent.com/35181467/53264967-fe484480-36aa-11e9-928a-50c544f2e5c1.png)

![sales by hour lightspeed retail](https://user-images.githubusercontent.com/35181467/53265135-79115f80-36ab-11e9-9f01-23af2f99f812.png)

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 

Thank you for sharing the report formats. Above requirement falls in "Cash Basis" reporting. I shared a document with you on "Cash vs Accrual Basis Reporting" by email. 
We certainly wanted to proceed with Cash basis reporting however we have few challenges before starting the development with respect to the current behavior of partial payment and refunds. We have listed the challenges in the document that are as follows:-

**Challenges:**

1: Partial Paid Invoices

- Let’s say invoice is created for $100 and customer pay $50 on current date and remaining payment will be done at the time of receiving the device. If I check the report today and sales value will be $50, How system will consider the associated “Tax” and “COGS” of item/items? 
We need to track down the exact COGS, Tax to come up with “Profit” and “Margin”. 
- If there are 2 partial payments received on 2 different dates if admin/users review the report where both dates are included, how system logs and show the data in reports?
- If there are multiple items in one invoice and admin/users logs the partial payment, how the system will figure out the payment with respect to item/items. E.g. Sales by Item type report
Review excel case for details. 

2- Refunds Case
- If an invoice is refunded at a specific date, on the basis of cash base reporting it should deduct value from that specific day sales value. Right?

**Can you share your feedback on the above challenges so we can proceed accordingly?**

**_By the way, did you try our "Register Sales Report" i.e. quite similar to above format and also it's on "Cash Basis"?_** 
https://app.repairdesk.co/index.php?r=stats/registersales

Regards,
UZAIR

**Comment by ochoaonline** [comment]
Some Thoughts: 
1. Tax would be calculated on the remaining balance would probably be easiest route. or 2. a complicated formula would be the other route but this would be using backwards taxing having the system to figure out  X + Tax = $50 (Deposit) , if deposit was taken if i recall correctly, lightspeed wouldn't show deposit / data until full sale was completed

For COGS- maybe they can create two reports- Actual COGS vs Actual cash basis and COGS vs Accrual.COGS vs Accrual is always hypothetic anyways as we all know there could be times where customer never shows up to pick up a device and the balance owner never gets paid. (why we steered away from deposits) I think its important to see both COGS on Cash basis and Accrual. If a deposit is made for $50 part and the COGS is $30 and total repair was $100 and then the customer never shows up to pay the second half. Then the COGS would have to be calculated vs the $50.

**Partial Payments Received**
This would be show as 2 different dates, since each has different Cash received

**Multiple Items**
COG would still be the same for all items , what ever each item really cost, Deposit could be attributed to the 1st line item just an idea, 

**Refunds**
All Refunds should be deducted from the day they occurred, so everyone knows when it happened.

**Comment by Uzair-RepairDesk** [comment]
Further conversation is by email. In-House task reference is as follows. I have logged the conversation on the task:-
https://repairdesk.atlassian.net/browse/RD-332
