### ISSUE TITLE
Documentation on Business Wise / Store Wise Components | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#691]
Hello Sir,

As per reference of email to Sir Uzair, Sir Usman and Fahad, Modesto from DrPhone Fix is looking for:

Do you guys have any documentation / guide we can look at to see what features / settings are Business wise / Store wise.

For the past week plus almost daily we keep getting random changes being made by techs / employees at store level and keep affecting all of us Business wise, and is hard to track down who made the change.

Regards,

**Comment by ali-repairdesk** [comment]
@Uzair-RepairDesk Lets meet today on this.

Moreover I will appreciate if you may see with the team if they have a doc which we can share with Modesto.

Thanks a lot

**Comment by Uzair-RepairDesk** [comment]
**He actually listed the following concerns:-**

•	Employee changing name's of parts for example iphone 7+ was changed to Galaxy Edge 7 affected all locations
•	Items being removed from our Inventoried Categories to new or fake categories affecting all locations inventory counts
•	Parts being added on store level and showing up on all stores, when only one store Control center has that setting enabled
•	New Categories / Category types being added at store level and affecting us business wise
•	Pictures of the Main Categories being changed (Affecting all locations)

![categories](https://user-images.githubusercontent.com/22955861/53314813-2968a900-38e2-11e9-939d-29b82114c5f0.png)

New Pictures

Below weird categories

![12](https://user-images.githubusercontent.com/22955861/53314826-384f5b80-38e2-11e9-8142-b60ee87613a7.png)

i didn't give owners access to any settings to try and avoid these, but looks like staff members with out settings access are still able to make some of these business wise changes

**Comment by Uzair-RepairDesk** [comment]
Fahad @ali-repairdesk 
As discussed please proceed and advise Modesto according to the cases document I sent to you. Thanks

**Comment by ali-repairdesk** [comment]
Sure Uzair Bhai,

Thanks

**Comment by ali-repairdesk** [comment]
We discussed with Modesto and this will be catered during the whole module of Store and Business Wise Settings.

So closing the ticket for now.
