### ISSUE TITLE
Ability to delete item from all store

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#693]
If an employee doesn't have access to delete an item he can still click on action and delete it from selected or all stores. This should be role based

<img width="1280" alt="screen shot 2019-02-25 at 10 44 16 pm" src="https://user-images.githubusercontent.com/21986026/53357145-00cac880-394f-11e9-9a47-8463dd09be04.png">

**Comment by Uzair-RepairDesk** [comment]
**In-House Task Reference:-**
https://repairdesk.atlassian.net/browse/REP-1495

**Comment by Uzair-RepairDesk** [comment]
We have fixed this issue.
