### ISSUE TITLE
Trigger Switchs (Description & Images) for WooCommerce

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#694]
Can you please add a trigger switch for the RD/WooCommerce Description/Short Description Sync.

I would like this to be optional as i would prefer to create the description in Wordpress and nor RD.

**Comment by benjamingartner** [comment]
Can you also please out a trigger for syncing product images. I would like to attach images to RD for viewing on the POS but upload seperately to WooCommerce.

**Comment by Uzair-RepairDesk** [comment]
Hey @benjamingartner 

I am pleased to inform you that we have added a trigger that will allow you to stop syncing the "Description" on your website with "Woo Commerce" integration of RepairDesk. 
Please check screenshot attached. 

![uzairshah   Woocommerce](https://user-images.githubusercontent.com/22955861/55215457-b1144100-521b-11e9-91c1-9eaddc6cac1b.png)


Regarding "Images" request, we only sync image if you sync new product/item to the website. If you want to use a different image on the website, you can simply upload a new image of the product from admin panel of "Wordpress". 
Hope it helps.
