### ISSUE TITLE
Stock warning in Min-Max report

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#695]
Hello,
the stock warning of the product does not work when it is zero. The low inventory report does not see the item (example with the Nexus 5 screen). I have to manually click for each item on the saved button (even without having modified anything in the item). Following this, the report can see the item. Unfortunately, I can not do this for every item. Can you quickly fix this bug please.

--
french:
Bonjour,
le stock warning des produit ne fonctionne pas lors qu'il est à zéro. Le rapport de stock faible ne voit pas l'item (exemple avec l'écran de Nexus 5). Je dois cliquer manuellement pour chaque item sur le bouton enregistré (même sans avoir modifié quoi que se soit dans l'item). Suite a cela, le rapport peut voir l'item. Je ne peux malheureusement pas faire cela a chaque item. Pouvez-vous corrigé rapidement ce bug svp.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
Can you please elaborate it along with screenshots so we can look into it. Thanks

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. I have reviewed your concern on my test account with this scenario and it is working fine. I have checked in your account in store Saint-Roach, you didn't update Re-Order Level of most of the items. May be that's why you were facing this issue. Please kindly review this at your end and do let me know if you have any confusion. 

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
I am not able to put a video in github so can you do it for me please. I sent it to Usman by email.

Thank you

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 4 mars 2019 03:13
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Stock warning in Min-Max report (#695)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

I hope you are doing well. I have reviewed your concern on my test account with this scenario and it is working fine. I have checked in your account in store Saint-Roach, you didn't update Re-Order Level of most of the items. May be that's why you were facing this issue. Please kindly review this at your end and do let me know if you have any confusion.

Thanks
Usman Ali.

**Comment by JessicaSOS** [comment]
I am not able to put a video in github so can you do it for me please. I sent it to Usman by email.
Thank you

**Comment by hitman1986** [comment]
This issue just when upload item by excel sheet 
When upload for any item stock warning 0 and stock level any thing 1,2,3,.. when stock becom 0 not showing in low stock report
Im talking to you for this issue but not sloved, im tired 
When upload 0= empty but when enter the item by web and press save 0 becom 0

**Comment by hitman1986** [comment]
Im talking to mr danish for this issue

**Comment by usmanalikhan93** [comment]
Sure @hitman1986 . Let me check with Danish.

**Comment by usmanalikhan93** [comment]
Hey @hitman1986 

Danish will contact you on personal chat and will try to resolve your issues ASAP. 

Thanks.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1683

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS @hitman1986 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
tested and fixed
