### ISSUE TITLE
Employee Activity Logs - Possibility of making it business wise search

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#697]
Employee activity log, if there's a way for it to have option to search more than one store, or a check to search all stores, kind of like the 
**Multi Store Sales Breakdown Report** has option to select a few or all and show report for those
![image](https://user-images.githubusercontent.com/35181467/53767660-729d9780-3ea4-11e9-92db-42efe03edf16.png)

, trying to make an easier way to track when en employee / store makes a mistake on system wether is delete a part, add a new category , deletes something else like and invoice and things a along those lines 

Also: on the action field there's no option to search / see who added a new category for example picture below someone added a Cell category 

![drphonefix hq retail pos 1](https://user-images.githubusercontent.com/35181467/53767611-4e41bb00-3ea4-11e9-9ea6-81e28a09d798.png)

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
Thank you for sharing your idea. I can certainly discuss it with the development team if we can enhance the employee activity log report and provide a multi-store selection in criteria of store filter so you will be able to track the activity of a specific employee across multiple stores. 
Can you define the priority of this request so I can plan it accordingly? Thanks

Regards,
Uzair

**Comment by ochoaonline** [comment]
@Uzair-RepairDesk is not to track particular employee across multiple locations, is more track specific activity across multiple locations / employees , one search will let me know every time someone deleted a ticket in entire system vs doing a search per location

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk I believe we should include an option to select multiple or all store locations so that an administrator can run desired query to find out who created a inventory item, removed it etc..

**Comment by Repair-Desk** [comment]
Also we should add a column for store name so that its easier to trace in which store this change was made.

I've checked with Bilal and he has confirmed this is possible. Please add this for next sprint

**Comment by Repair-Desk** [comment]
Also we should add a column for store name so that its easier to trace in which store this change was made.

I've checked with Bilal and he has confirmed this is possible. Please add this for next sprint

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
We have made this improvement LIVE. You can now select multiple stores in "Employee Activity Log" report to check the activity logs. 
Please review at your end. Thanks.
