### ISSUE TITLE
Display Billing Error To Store Owner / Super Admin Only

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#698]
Dear @Uzair-RepairDesk 

It would be great if we can display billing error to store owners only. See below:

![billing](https://user-images.githubusercontent.com/21986026/53797958-15afe900-3f59-11e9-9c30-a309dc432051.jpg)

**Comment by Uzair-RepairDesk** [comment]
Noted. Will add it in next sprint. 
@Repair-Desk

**Comment by Uzair-RepairDesk** [comment]
With reference to updates. Billing message displays to "Admin" and 'Super Admin" only.
