### ISSUE TITLE
Broad Search Fix on Parts / Accessories Management Module 

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#701]
A lot of users , techs , owners, managers are having issues on using the Parts Management module, since the search is exact [iPhone Screen] vs broad iPhone Screen and it takes a long time to find the part you are specifically looking for 

![drcomputerfix accessories inventory](https://user-images.githubusercontent.com/35181467/53824694-91526b80-3f42-11e9-9e46-c63abfc73500.png)
vs the same search on POS side
![image](https://user-images.githubusercontent.com/35181467/53824800-c8c11800-3f42-11e9-8b05-625a12bdf990.png)

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk As discussed, can you discuss with imran if we can include manufacturer and device model in the search. I would also recommend to get suggestive search dropdown redesigned

**Comment by Uzair-RepairDesk** [comment]
#765

**Comment by usmanalikhan93** [comment]
Hey Modesto @ochoaonline 

Good news! We have added suggestive search in inventory module to help you in searching inventory. Now you can also search with Manufacturer and Device. 

Please review at your end.
Thanks
