### ISSUE TITLE
Exclude a commission from a product

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#702]
Initial problem: I'd like to know how to exclude a commission from a product. The products "prepay card" and "gift card" must have no commission. As mentioned before, I can not put them in the category "casual" because it does not maintain any sales history in the product. (history that may be necessary sometimes)

When do you think it can be corrected?
--
French:

Problème initial: J'aimerais savoir comment exclure une commission d'un produit. Les produits "parte prépayer" et "carte cadeau" ne doivent pas avoir de commission. Tel que mentionné précédemment, je ne peux pas les mettre dans la catégorie "casual", car cette dernière ne conserve aucun historique de vente dans le produit. (historique qui peut être nécessaire parfois)

Quand pensez-vous que cela pourra être corrigé?

**Comment by JessicaSOS** [comment]
What you wrote to me:

Hello Jessica,
I hope you are doing well.
Faizan passed on your information related to Commission Issue which you are facing for 1 Product item.
Before I come to your concern, I will like to mention here the current work flow of the commission module:
In RepairDesk Commission can be granted on the following basis:
1.	Product Based Commission [Highest Priority]
2.	Product Category Based Commission [Second Highest Priority]
3.	Global Commission [Employee Commission] [Third Highest Priority]
Currently there is no way you can avoid giving commission to a product whose commission has been granted by Global Commission.
The best way will be to assign a different category.
However I agree with you on this and I will recommend you to post this improvement in commission behavior on GITHUB.
I am sure our team will have a look and will consider this improvement in future road map.
Do let me know if you still have any questions or need help with anything else in RepairDesk.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 

Hope you are well. Regarding your above request, I will recommend you to keep "Prepay Card" or "Gift Card" in the "Casual Item" and keep them without commission percentage. 
Yes, we don't have transaction history for a casual item but you can go to Manage Invoices and apply search filter with type "Casual" to filter the invoices of casual items. 

However, if you still keep it in "Products" and commission is calculated, you can go to "Employee Commission Breakdown" report and "Void" commission record. Please check screenshot attached.

![rana mobile lab employee commission report111111](https://user-images.githubusercontent.com/22955861/53858114-9d016900-3ffa-11e9-9578-d51df56162fb.png)

**Comment by JessicaSOS** [comment]
Thank you for this idea to bypass the automatism in order to have a similar result. Even I select VOID, the item still appears in the commissions payable to the employee, so it does not solve my problem. I would prefer to be able to remove a commitison rather than put all my products in the "Casual" category.
For the following reasons:
- Since the products are already well categorized and that category is sync with woo trade.
- To keep the number of items in inventory (gift card example)
- To have the history of sales, modifications and adjustments made in the product.

Are you thinking of making any changes at this level or are I likely to wait a very long time and spend months paying too much commissions to my employees?

--
_french:
Merci pour cette idée de contourner l'automatisme afin d'avoir un résultat similaire. Même je sélectionne VOID, l'item apparait quand même dans les commissions payable à l'employé, alors sa ne règle pas mon problème. Je préfèrerais pouvoir être en mesure de retirer une commisison plutôt que de mettre tous mes produits dans la catégories "Casual". 
Pour les raisons suivantes: 
- Puisque les produits sont déjà bien catégorisé et que cette catégorie est synchroniser avec woo commerce. 
- Pour conserver le nombre d'item en inventaire (exemple carte cadeau)
- Pour avoir l'historique des ventes, des modifications et des ajustements effectué dans le produit._

**Comment by Uzair-RepairDesk** [comment]
Thank you for the details @JessicaSOS . I will check with the team about the possibility of above-requested enhancement and update you accordingly.

**Comment by JessicaSOS** [comment]
Are you thinking of making any changes at this level or are I likely to wait a very long time and spend months paying too much commissions to my employees?

**Comment by Uzair-RepairDesk** [comment]
I have certainly marked it under enhancements. Meanwhile, i will advise you to use "Void" commission functionality. Once you void the commission, it's not payable to the customer. 
Hope it helps

**Comment by JessicaSOS** [comment]
When do you think that this option will be effective, because even I select VOID, the item still appears in the commissions payable to the employee.

--
french:
Quand penser vous que cette option sera effective, car même je sélectionne VOID, l'item apparait quand même dans les commissions payable à l'employé.

**Comment by Uzair-RepairDesk** [comment]
Update: I have added this improvement to do list.

**Comment by JessicaSOS** [comment]
ok tnx

**Comment by JessicaSOS** [comment]
Hello,
The deadline has expired and I still pay commissions to my employees for products that I would not want. Can you tell me when it will be effective?
Thank you and good day

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
We have already updated it on your request that if you will set commission value "0" for the inventory item or service then the commission will not be applied on that product/service. We are expecting to push it on LIVE in our upcoming release. Thanks.

**Comment by JessicaSOS** [comment]
Ok good. When will you talk about next version, when?

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
Our release is expected in this week.

**Comment by JessicaSOS** [comment]
Nice !!

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Muhammad Uzair Shah <notifications@github.com> 
Envoyé : 13 mai 2019 00:43
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Exclude a commission from a product (#702)

 

Hey @JessicaSOS <https://github.com/JessicaSOS> 
Our release is expected in this week.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
We have made your requested improvement LIVE. If you want to exclude a product/service from the commission, you can go to the specific product/service and set individual commission value to "0". Once you do that, the commission will not be calculated on that specific product/service. 
Check screenshot attached. You can review at your end and share your feedback. 

![uzairshahEdit Mobile  Accessories   Parts iPhone X LCD Screen ](https://user-images.githubusercontent.com/22955861/58072946-b0b07a80-7bba-11e9-9c20-59f69ade080c.png)

**Comment by JessicaSOS** [comment]
Ok good! It does not work for the past?
I will check in the next weeks

**Comment by JessicaSOS** [comment]
tested and fixed
