### ISSUE TITLE
Alert of the appointement widget calendar

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#703]
Employees do not receive notifications when a new lead is generated via the "appointement calendar" widget. Still, the alerts are correctly configured. I tested 2 shops (Lvis and Sainte-Foy) but I think this problem is present in all stores.
<img width="938" alt="appointement calendar widget" src="https://user-images.githubusercontent.com/40500094/53904263-9f23f180-4013-11e9-89ba-a77420fd9a63.png">

--
French:
Les employés ne recoivent pas de notifications lorsqu'un nouveau lead est généré via le widget "appointement calendar". Pourtant, les alertes sont correctement configuré. J'ai testé 2 boutiques (Lvis et Sainte-Foy) mais je crois que ce problème est présent dans toutes les boutiques.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have reviewed your concern but it is working fine. Notification comes to those employees on which it is enable. Can you please again verify at your end and let me know if you are still facing this issue. 

Thanks
Usman Ali

**Comment by JessicaSOS** [comment]
I did the test myself being connected with the user of Kelsye Bélair (SOS Phone Lévis) and I have received no sound alert. I will send to Usman a video with we transfer.

**Comment by usmanalikhan93** [comment]
ok Let me test again.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have reviewed it again and it is working fine. Just a quick question, are you making appointment from Levis store ? 
Or can I make a test appointment on your account to check ?

**Comment by JessicaSOS** [comment]
Hello,
For this example, yes the appointment was taken in Lévis. We also tested it with other shop and we have the same problem. You can try to create appointments without problems. Let me know the numbers and I will erase them later.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked by creating a lead in your account and yes notification does not appear. I have made a lead in Levis store L-Le-20496. You can delete it. Let me discuss this with developer and then I will update you accordingly. 

Thanks. 
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1655

**Comment by JessicaSOS** [comment]
Ok !

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 14 mars 2019 02:19
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Alert of the appointement widget calendar (#703)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

I have checked by creating a lead in your account and yes notification does not appear. I have made a lead in Levis store L-Le-20496. You can delete it. Let me discuss this with developer and then I will update you accordingly.

Thanks.
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.
I have made a test lead L-Le-20509 in Levis store. You can delete it. 

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
Yes it works well!
I wanted to change a turn of phrase in the SMS message confirmations appointments and once the message changed, the old appears in a text message. He does not take the new message but the old one. I tried to activate and deactivate the auto send but without success. It is always the old man who sends himself away. Why is it not correct?
--
french:
Oui sa fonctionne bien!
J'ai voulu changer une tournure de phrase dans le message SMS des confirmations de rendez-vous et une fois le message modifié, le vieux apparaît encore dans un texto. Il ne prend pas le nouveau message mais bien l'ancien. J'ai essayer d'activer et de désactiver l'envois automatique mais sans succès. C'est toujours le vieux qui s'envois. Pourquoi est-ce que cela ne se corrige pas?
