### ISSUE TITLE
Notification for LEAD

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#704]
Hello,
Lead notifications do not work properly. I activated the option when a new lead is generated, to automatically send an email to the customer. It works, but not the sms.
I did the test myself by creating a new appointment via the widget, and there are 3 emails that have been sent. You can see in the attached image, that the customer receives the same message as in-house employees. However, the programming of the in-house is not activated. No message should be sent to either in-house or customer. The in-house message should not be sent to the customer. In this case though, the history records that the email was sent, but yet, I only received that one when a new lead is generated.
<img width="939" alt="in house lead notifictaion" src="https://user-images.githubusercontent.com/40500094/53970027-deac1580-40c7-11e9-9966-7a4f486774ee.png">
<img width="943" alt="lead history about notification" src="https://user-images.githubusercontent.com/40500094/53970045-e4096000-40c7-11e9-9129-51ca2f49f9f1.png">

--
French:
Bonjour,
Les notifications des lead ne fonctionnent pas correctement. J'ai activé l'option lorsqu'un nouveau lead est généré, d'envoyer automatiquement un courriel au client. Cela fonctionne, mais pas le sms. 
J'ai fait le test moi-même en créant un nouveau rendez-vous via le widget, et il y a 3 courriel qui se sont envoyé. Vous pouvez voir dans l'image en pièce jointe, que le client reçoit le même message que les employés in-house. Pourtant, la programmation du in-house n'est pas activé. Aucun message ne devrait s'envoyer, ni au in-house et ni au customer. Le message du in-house ne doit surtout pas être envoyer au client. Dans ce cas si, l'historique inscrit que le courriel a été envoyé, mais pourtant, je n'ai recu que celui lorsqu'un nouveau lead est généré.

**Comment by JessicaSOS** [comment]
To rectify, the sms work but the text does not include the accent. It is therefore illegible because the accents are replaced by "?".
--
French:
Pour rectifier, les sms fonctionnent mais le texte n'inclus pas les accent. C'est donc illisible, car les accents sont remplacé par des "?".

**Comment by JessicaSOS** [comment]
Yes it works well!
I wanted to change a turn of phrase in the SMS message confirmations appointments and once the message changed, the old appears in a text message. He does not take the new message but the old one. I tried to activate and deactivate the auto send but without success. It is always the old man who sends himself away. Why is it not correct?
--
french:
Oui sa fonctionne bien!
J'ai voulu changer une tournure de phrase dans le message SMS des confirmations de rendez-vous et une fois le message modifié, le vieux apparaît encore dans un texto. Il ne prend pas le nouveau message mais bien l'ancien. J'ai essayer d'activer et de désactiver l'envois automatique mais sans succès. C'est toujours le vieux qui s'envois. Pourquoi est-ce que cela ne se corrige pas?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you send me a screenshot ?

**Comment by JessicaSOS** [comment]
Regarding this: _"To rectify, the sms work does not include the accent." It is therefore illegible because the accents are replaced by "?"_. I do not know what the error was but it works well.

Regarding this, _"Hello, Lead notifications do not work properly. I activated the option when a new lead is generated, to automatically send an email to the customer. It works, but not the sms.
I did the test myself by creating a new appointment via the widget, and there are 3 emails that have been sent. You can see in the attached image, that the customer receives the same message as in-house employees. However, the programming of the in-house is not activated. No message should be sent to either in-house or customer. The in-house message should not be sent to the customer. In this case though, the history records that the email was sent, but yet, I only received that when a new lead is generated."_, the images are attached, are you missing any other information?

--
french:
Concernant ceci: _"To rectify, the sms work but the text does not include the accent. It is therefore illegible because the accents are replaced by "?" "_ cela est réglé. Je ne sais pas ce qu'était l'erreur mais sa fonctionne bien. 

Concernant ceci: 
_"Hello, Lead notifications do not work properly. I activated the option when a new lead is generated, to automatically send an email to the customer. It works, but not the sms.
I did the test myself by creating a new appointment via the widget, and there are 3 emails that have been sent. You can see in the attached image, that the customer receives the same message as in-house employees. However, the programming of the in-house is not activated. No message should be sent to either in-house or customer. The in-house message should not be sent to the customer. In this case though, the history records that the email was sent, but yet, I only received that one when a new lead is generated."_ , les images sont en pièce jointe. Vous manque t'il d'autre information?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you confirm me on this that is this fixed ? Because I didn't understand what you said in last comment. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
concerning this message, no it is not fixed:

Lead notifications do not work properly. I activated the option when a new lead is generated, to automatically send an email to the customer. It works, but not the sms.
I did the test myself by creating a new appointment via the widget, and there are 3 emails that have been sent. You can see in the attached image, that the customer receives the same message as in-house employees. However, the programming of the in-house is not activated. No message should be sent to either in-house or customer. The in-house message should not be sent to the customer. In this case though, the history records that the email was sent, but yet, I only received a new lead is generated. "

The images are attached a little higher.

**Comment by usmanalikhan93** [comment]
For internal Use: 
https://repairdesk.atlassian.net/browse/REP-1849

**Comment by usmanalikhan93** [comment]
For internal Use:
https://repairdesk.atlassian.net/browse/RB-258

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali
