### ISSUE TITLE
Estimate Notification

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#705]
Hello,
When we create an estimate via a lead, there is no email that is sent to the client, even if the programming is configured so that an email is sent.

<img width="939" alt="estimate notifictaion" src="https://user-images.githubusercontent.com/40500094/53971677-52035680-40cb-11e9-8855-ef66efcbd7d1.png">
--
french:
Bonjour,
Lorsque nous créons une estimation via un lead, il n'y a aucun courriel qui est envoyé au client, même si la programmation est configurer afin qu'un courriel s'envoie.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have discussed this and this does not send email automatically in case of Estimate. You have to send manually to that customer. We will exclude those responses which does not sent automatically. Thanks for highlighting it and sorry for the inconvenience. 

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
ok tnx
