### ISSUE TITLE
assignment disapear when a ticket is transfered

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#707]
Hello,
when we transfer a ticket, the assignment automatically disappears. It's a shame for the technicians' commissions. Can you fix that?
Have a good day

--
french:
Bonjour,
lorsque nous transférons un billet, l'assignation s'efface automatiquement. C'est dommage pour les commissions des techniciens. Pouvez-vous corriger cela ?
Bonne journée

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 
 
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1587

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
I tested the ticket transfer between the branches. Assignments remain according to the store. They should remain as in the last configuration. Example, I assign a repair to David at Limoilou. I transfer the ticket to Lévis because in the end, will be our technician Lévis Jimmy who will make the repair. Once the repair finishes, he completes the ticket, assigns the repair and makes "transfer back". However, once back in Limoilou, the assignment is again that of David. So it was Jimmy who did it. Please understand you?
Please reopen

--
French:
J'ai testé le transfert de billet entre les succursales. Les assignations reste selon le magasin. Elles devraient rester comme à la dernière configuration. Exemple, j'assigne une réparation à David à Limoilou. Je transfert le billet à Lévis car au final, ce sera notre technicien de Lévis Jimmy qui fera la réparation. Une fois la réparation terminer, il complète le billet, s'assigne la réparation et fait "transfert back". Cependant, une fois de retour à Limoilou, l'assignation est à nouveau celle de david. Pouratnt, c'est Jimmy qui l'a éffectué. Comprennez-vous?
Svp réouvrir

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I understand what you said but it will cause issues in reports and commission module. So, we can't do like this. 

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
But if the person who performed the repair should have the commission, it does not matter in which shop the repair was made and especially if the ticket was transferred correctly in order to be completed in another shop.
