### ISSUE TITLE
Register Sales Check Mark Issue

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#708]
![drphonefix leesburg registersales stats 1](https://user-images.githubusercontent.com/35181467/54032475-b1bb3980-417f-11e9-9b32-e0b8e1e73934.png)

Little glitch on the register sales report, When you click the check mark for criteria, the 2nd menu doesn't always come out, you have to click the name, and once you get the 2nd menu to come out and you check mark Cash, credit card, or any of the Methods it does not apply to report filter / search unless you actually click the name Cash

**Comment by usmanalikhan93** [comment]
Hi Modesto @ochoaonline 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Thanks

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1589

**Comment by usmanalikhan93** [comment]
Hi Modesto@ochoaonline 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali khan
