### ISSUE TITLE
Inventory Count 500 Error | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#709]
Hello Sir,

Customer has reported an issue that once they click on Save in order to save Inventory Count, it throws 500 Error.

Store Name: DPF Oldsmar

Development team will be checking the logs and sharing the feedback. Screenshot attached as well.

Regards,

**Comment by ali-repairdesk** [comment]
![Inventory Count](https://user-images.githubusercontent.com/26381305/54053128-25088e00-4208-11e9-813f-47fa115c9e17.jpg)

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1590

**Comment by usmanalikhan93** [comment]
Hi @ali-repairdesk 

Query has been executed on live. Hopefully this error will not come again. Please update customer.
