### ISSUE TITLE
Cross Sales on Locations for Employee Nicole | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#710]
**Hello Sir,**

Customer has reported an issue that Not sure whats causing cross sales on locations but its happened a few times when one of our employees Nicole visits some of the stores and use the training pos to train the employees, basically shift is opened on Leesburg Register, but somehow later in day all sales showed up under training register, so when closing Leesburg register sales are off. [Screenshot Attached]

**Regards,**

**Comment by ali-repairdesk** [comment]
![Nicole 1](https://user-images.githubusercontent.com/26381305/54053945-b37e0f00-420a-11e9-858c-6a03aca24121.jpg)
![Nicole 2](https://user-images.githubusercontent.com/26381305/54053951-b7aa2c80-420a-11e9-9d7f-9a52a947e664.jpg)
![Nicole 3](https://user-images.githubusercontent.com/26381305/54053952-b973f000-420a-11e9-933a-340f48691370.jpg)

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1591
