### ISSUE TITLE
RMA Issue | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#711]
**Hello Sir**

Customer has reported an issue that the RMA's not triggering inventory. A new RMA that didn't deduct from system.

RMA-071 - HQ RETAIL
RMA-069 also with Item # 1315

**Regards,**

**Comment by usmanalikhan93** [comment]
Hello Modesto 

We have added logs in RMA to track down these type of issues. Do let us know if you have any issue. We will investigate for you. 

Thanks
