### ISSUE TITLE
Trade-In Module - It doesn't reflect in customer profile 

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#713]
Hi we did a trade in purchase from a customer, out trade in item # 0791 shows that it was traded in, however if we go to the customer it does not show under their name that we purchased from them.

Store: WirelessER Inc

**Comment by Uzair-RepairDesk** [comment]
Dan from Technology traders also requested the same and it was included in our new "Manage Customers" module and we never got a chance to work on it. 
@Repair-Desk

**Comment by Uzair-RepairDesk** [comment]
Its Live now
