### ISSUE TITLE
Woocommerce Stock Sync

### ISSUE THREAD

**Issue by zoombiefone** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#714]
Hi,
Does anyone have problems with stock level sync with woocommerce? I sold an item through repairdesk app, the stock level does not change in Woocommerce.

**Comment by Uzair-RepairDesk** [comment]
Hi @zoombiefone 
Do you have same SKU of an item in both RepairDesk inventory item and WooCommerce item details?
Also, web job takes time to sync stock? If you want to instantly sync it, you can go to Integrations > WooCommerce Integration > Setup > Triggers > Click on "Manual Sync Now".

Please do let me know if it works. Thanks

**Comment by zoombiefone** [comment]
The SKU is the same. I've waited for hours and the stock doesn't change. I'm fairly sure it doesn't.

**Comment by Uzair-RepairDesk** [comment]
Hey @zoombiefone 
Thank you for your response. Can you share your account credentials along with item details by email so I can check it from your account? 
My email address is uzair@repairdesk.co

**Comment by usmanalikhan93** [comment]
Danish had a detail session with Danny and now he is clear about everything. So I am closing this task as per Danish instrustion.
@Uzair-RepairDesk FYI
