### ISSUE TITLE
Issue With Register Sales Report - Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#717]
**Hello Sir,**

Customer has reported an issue that Register Sales Report and Register Sales via Excel don't match up for dates: 6 March, 7 March, 9 March and 11 March.

[Relevant Screenshot Attached]
![Screenshot 2](https://user-images.githubusercontent.com/26381305/54290757-5ea51480-45cd-11e9-847d-e299668df917.JPG)
![IMG 1](https://user-images.githubusercontent.com/26381305/54290758-5f3dab00-45cd-11e9-9b09-6bc7e17e54d9.png)

**Regards,**

**Comment by ali-repairdesk** [comment]
Internal task link which was fixed previously:
https://repairdesk.atlassian.net/browse/REP-1534

**Comment by usmanalikhan93** [comment]
I have made a new task for this. 
https://repairdesk.atlassian.net/browse/REP-1650

**Comment by usmanalikhan93** [comment]
Hi @ali-repairdesk 

Reported issue has been fix. Please update Modesto about the fix. 

Thanks
