### ISSUE TITLE
Serialized inventory error

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#719]
It says I have an item to serialize,  but when i go to correct the inventory it says they are all serialized.
<img width="518" alt="Screen Shot 2019-03-13 at 2 22 20 PM" src="https://user-images.githubusercontent.com/43588617/54312141-d3f7f180-459b-11e9-82ba-3088b3464379.png">
<img width="1066" alt="Screen Shot 2019-03-13 at 2 22 57 PM" src="https://user-images.githubusercontent.com/43588617/54312143-d65a4b80-459b-11e9-8095-750f01de9939.png">

**Comment by Repair-Desk** [comment]
**@Trevorshaw7** 

Happy to help with this. It appears that you already have on hand stock due to which you're unable to apply an adjustment entry. See below:

![WarehouseEdit Mobile, Accessories   Parts Galaxy S7](https://user-images.githubusercontent.com/21986026/54313832-eb66c700-45fb-11e9-89d7-8be67aecb9f8.jpg)

**Comment by Trevorshaw7** [comment]
<img width="518" alt="Screen Shot 2019-03-13 at 2 22 20 PM" src="https://user-images.githubusercontent.com/43588617/54314067-49fe5780-45a0-11e9-8787-705110e37809.png">

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

I have reviewed your concern and I have checked in your account it works fine. I have made a video for reference. Please check and if you have any question you can ask here. 
Video link: https://www.screencast.com/t/tTCpRIzx

Thanks
Usman Ali.

**Comment by usmanalikhan93** [comment]
I have just checked it's been fixed by Fayyaz.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1656
