### ISSUE TITLE
Clocking in and Timesheets

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#721]
when techs are tying to clock in they keep seeing full list of names even though most of those people are not assigned to their store, can we make it so only employees assigned to that store show up under clocking in 

Also We have an employee that we created and assigned to Davie store as default, but he is not showing up under davie to clocking but somehow shows up under Headquarters (Another Location) that he is not assigned to. employee name is Evan R.

**Comment by Repair-Desk** [comment]
**When techs are tying to clock in they keep seeing full list of names even though most of those people are not assigned to their store, can we make it so only employees assigned to that store show up under clocking in**
@Uzair-RepairDesk can we add the following to our roadmap?

**Also We have an employee that we created and assigned to Davie store as default, but he is not showing up under davie to clocking but somehow shows up under Headquarters (Another Location) that he is not assigned to. employee name is Evan R.**
@usmanalikhan93 can you please check this?

**Comment by fahadimran303** [comment]
**Also We have an employee that we created and assigned to Davie store as default, but he is not showing up under davie to clocking but somehow shows up under Headquarters (Another Location) that he is not assigned to. employee name is Evan R.**

Internal Jira Link for this issue:
https://repairdesk.atlassian.net/browse/REP-1673

**Comment by usmanalikhan93** [comment]
Sure @Repair-Desk

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
As discussed, the list of employees should be according to the access to the stores. Please also get it done in the same task.

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1225

**Comment by usmanalikhan93** [comment]
Hi Modesto@ochoaonline 

I hope you are doing well. Your both reported concerns has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
