### ISSUE TITLE
RMA Improvements - Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by ali-repairdesk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#722]
Hello Team,

Modesto will be sharing his feedback related to RMA here.

Thanks,

**Comment by ochoaonline** [comment]
We would like to add a couple more status to the RMA, or if there's a way we control the status , 1. Denied 2. Damaged by Employee 3. Exchanged and also an area with Dropdown so Tech can select his name: Submitted by:

**Comment by fahadimran303** [comment]
Internal Task Link:
https://repairdesk.atlassian.net/browse/REP-1739

**Comment by Uzair-RepairDesk** [comment]
@fahadimran303 
I believe we have made the suggested improvements. Please confirm and close this.
