### ISSUE TITLE
Category Display in Appointment Calendar  

### ISSUE THREAD

**Issue by wasimafsarkhan** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#723]
1. Customer Name / Business Name:
• Jorge Garcia | iBuy and Repair LLC

2. OS: Windows / MacBook

3. Module: Integrations

5. Configuration Setting: Correct

6. Roles & Permissions: Correct

7. Issue:
Category Display in Appointment Calendar  

8. Steps to Reproduce Issue /Provide Video
Home >> Integrations >> Appointment Calendar 
Moreover, Screenshot attached.

9. Current Result:
The category is not displaying on the Appointment calendar, wheater on POS the category is available or not (Enabled/Disabled) 

10. Expected Result:
As per clients requirement, As POS Category is Shown, so category should also be available on Appointment calendar. 

Thanks
![AC](https://user-images.githubusercontent.com/47608705/54461851-a2e01280-478f-11e9-84ad-61a21bdefd17.PNG)

**Comment by Uzair-RepairDesk** [comment]
Currently, our category module is not linked with Appointment Calendar Wiget. 
We planned to do it when we start working on enhancements of "Appointment Calendar Widget".
Please confirm what is the priority to do it? 
@wasimafsarkhan @Repair-Desk

**Comment by Uzair-RepairDesk** [comment]
Hey @wasimafsarkhan
 
Please inform "Jorge Garcia from iBuy and Repair LLC" that we have added "Repair Category" option in Appointment Calendar Wiget. 
User can go to "Configurations" of "Appointment Calendar Widget" and "Enable repair category" option. 
We have also added an option to change "Primary and Secondary background colors" of the widget. 

You can view the demo from the following the link:-
http://repairdeskdemo.co/appointment/

If you have any questions, please feel free to ask. Thanks
