### ISSUE TITLE
Error when search in manage inventory

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#724]
When searching for any item it is in Arabic language in manage inventory No result found
Just in arabic item

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Sorry for the inconvenience. I have checked this issue and it exists. Let me assign this to development team. Once it will be fix, I will update you here. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1685

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by hitman1986** [comment]
yeah its great , this working
