### ISSUE TITLE
Feature Request - Disable "Due On" feature

### ISSUE THREAD

**Issue by irepairsharlow** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#725]
Hello,
My business does not and will never use the "Due On" feature, the pink highlighting and additional field in the ticket management are disruptive to our processes and it would be better if we had the option to disable this feature so it no longer appears.

Regards
Brendan

**Comment by Uzair-RepairDesk** [comment]
Hi Brendan @irepairsharlow 

Thank you for sharing your idea. Currently, it's not possible to hide "Due On" feature/field from RepairDesk. "Due Date" is one of the most important criteria to find out the "Due" or "Critical" tickets. 
With a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible. At the moment, we won’t be able to make this one work during the current Quarter. 
However, we can certainly pick this up once we update our "Ticket Module" functionality with a new user interface (UI) and functionality that will allow customizing the "Manage Tickets" listing fields according to your choice. I have marked it under "Enhancements". Thanks
