### ISSUE TITLE
Employee privilege Options

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#726]
Nothing appears in the privileges of the employees' positions. I do not have access to modify anything, no options are present.
<img width="944" alt="employee privilege" src="https://user-images.githubusercontent.com/40500094/54609361-31bb8c00-4a29-11e9-9903-8de6b4a5a258.png">

--
French:
Plus rien n'apparait dans les privilèges des postes des employés. Je n'ai pas accès a modifier quoi que se soit, aucune options n'est présente.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
I have just checked it and its working fine at our end. Are you facing it on all accounts? Can you please logout and login again and clear the cache of the browser? 
Please do let me know if there is a specific case when you are facing this issue?

**Comment by JessicaSOS** [comment]
it works well today, problem solved.
