### ISSUE TITLE
Problem with transfers

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#727]
I am trying to transfer a tradein that is "in stock". Once the item is added in an inventory transfer, an error page appears (error 500). I try with 2 different products and the same thing is produced. These are items #12072 and #12064. The inventory transfer does not exist (probably because of the error page). However, the item is floating as a "transfered". It's like he's been put in inventory transfer, but I'm unable to see this transfer. I can not edit or view it either in the original store or in the destination store. I can not change the item either, because it appears as "transfered" and when I click on it, another error page is displayed (error 404).
--
french:
J'essaie de transférer un tradein qui est "in stock". Une fois l'item ajouté dans un transfert d'inventaire, une page d'erreur apparait (erreur 500). J'ai essayer avec 2 produits différents et la même chose c'est produit. Il s'agit des items #12072 et #12064. Le transfert d'inventaire n'existe pas (surement à cause de la page d'erreur). Cependant, l'item est flottant en tant que "transfered". C'est comme s'il avait été mis dans le transfert d'inventaire, mais je suis incapable de voir ce transfert. Je ne peux pas le modifier ou le visualiser ni dans le magasin initial, ni dans le magasin de destination. Je ne peux pas non plus modifier l'item, car il apparait en tant que "transfered" et lorsque je clique dessus, une autre page d'erreur s'affiche (erreur 404).

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1713

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

We have again changed the status of item 12072 as in stock. And I have checked item 12064, it is already sold and can be open. You can verify at your end and do let me know if you have any question. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
12072 is non-existent ... It is completely missing ...

--
French:
12072 est inexistant... Il est complètement disparu...

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

It's fixed now. Please verify at your end.

**Comment by JessicaSOS** [comment]
ok tnx
