### ISSUE TITLE
Cost price in inventory transfers

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#729]
An employee who does not have access to viewing cost prices should not be able to see them. You have added cost prices in inventory transfers. You have taken care to remove the costs in the inventory transfer for employees who do not have access. However, you forgot to remove the cost price total on the main inventory transfer page. See the view of an employee who does not have access to the cost price attached.
<img width="944" alt="cost price inventory transfert" src="https://user-images.githubusercontent.com/40500094/54628999-064a9880-4a4d-11e9-94d3-1c84cd7e13d7.png">

--
French:
Un employé qui n'a pas accès à visualiser les prix coutant ne doit pas pouvoir les voir. Vous avez ajouté les prix coutant dans les transferts d'inventaire. Vous avez pris soin de retirer les prix coutant dans le transfert d'inventaire pour les employés n'y ayant pas accès. Cependant, vous avez oublié de retirer le total des prix coutant sur la page principale des transfert d'inventaires. Voir la vue d'un employé qui n'a pas accès aux prix coutant en pièce jointe.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
We added the "Total Cost" field in inventory transfer. You are 100% right "Hide Cost Price" trigger should also apply to this. I have added a task to make this improvement. 
I will update you once we go LIVE with this improvement. 
I appreciate your patience. Thanks

**Comment by JessicaSOS** [comment]
When should this be? Because for the moment, all the employees who do not have access to see the cost price have now access ...

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1711

**Comment by Uzair-RepairDesk** [comment]
Hi @JessicaSOS 
I apologize for the delay in this task. We have already fixed this issue. We will deploy it early next week.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
