### ISSUE TITLE
Generated by and created by in a ticket

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#730]
Sometimes a ticket that is created by my employee "Stacey Rheault" is written that the ticket was generated by another of my employees "Luca Bertrand". We can see from the ticket history that it was created by Stacey. In addition, my employee Luca never creates a ticket. It's like regularly, but not in every ticket. I do not know in which context precisely this problem appears. Can you look at this problem please.
<img width="942" alt="L-11973" src="https://user-images.githubusercontent.com/40500094/54632401-63961800-4a54-11e9-8eba-8bdb8e6cc269.png">
<img width="936" alt="stacey created" src="https://user-images.githubusercontent.com/40500094/54632448-858f9a80-4a54-11e9-8671-c27e4f16b79d.png">

--
French :
Parfois, un billet qui est créé par mon employée "Stacey Rheault" est inscrit que le billet a été généré par un autre de mes employés "Luca Bertrand". Nous pouvons bien voir dans l'historique du billet qu'il a été créé par Stacey. De plus, mon employé Luca ne crée jamais de billet. C'est comme à régulièrement, mais pas dans tous les billets. Je ne sais pas dans quel contexte précisemment ce problème apparait. Pouvez-vous regarder ce problème svp.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you please log the ticket and try to reproduce this issue at your end?

**Comment by usmanalikhan93** [comment]
Sure @JessicaSOS @Uzair-RepairDesk 

Let me check this and try to reproduce this issue on my end.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have tried to reproduce this issue but it works fine. We have faced one issue related to this in last month but it was fixed. If you face again this issue you can message me on this task. 

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
Hello,
This problem is always present and regular. See exenple of the L-12321 SOS Phone Limoilou. Please reopen this task.
tnx

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Let me check this again.

**Comment by usmanalikhan93** [comment]
For Internal Use:
https://repairdesk.atlassian.net/browse/REP-1846

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have tried different scenarios but failed to reproduce this issue. Can you help me to find the case where this issue occurs ? In future when ever you face this issue, do let me know the steps. I will appreciate your help. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
I have no idea how this happens because it looks like it happens randomly. I will inform you if I come across these files personally.

**Comment by JessicaSOS** [comment]
Exemple: SOS Phone Limoilou ticket L-12585

**Comment by JessicaSOS** [comment]
Exemple: SOS Phone Limoilou ticket # L-12406

**Comment by JessicaSOS** [comment]
Exemple: SOS Phone Limoilou ticket: # L-12468

**Comment by usmanalikhan93** [comment]
Let me check this @JessicaSOS and I will try to reproduce a use case for this.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Just wanted to know are you still facing this issue ?

**Comment by JessicaSOS** [comment]
Yes we still have problems with this.
