### ISSUE TITLE
Taxes showing on none taxable items 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#731]
Taxes are still showing on none taxable items. Its causing for the bookkeeping department to charge does taxes as none paid taxes and its also given reflecting the amount as due or over once the costumer has already paid for the item.

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 
Can you please specify the report that you are tracking and able to see taxes on non-taxable items? 
Can you also elaborate with screenshot and description so I can further assist you? Thanks.

**Comment by Omar1892** [comment]
I will get back to you with that info.

**Comment by Omar1892** [comment]
![Screen Shot 2019-03-27 at 2 39 04 PM](https://user-images.githubusercontent.com/47898011/55114226-98cae780-509e-11e9-84ac-c91b5c217936.png)

**Comment by Omar1892** [comment]
I have uploaded the image the transaction where I was having issue. In the casual we don't charge taxes to the costumer and in this case the system was charging 0.02cents. The reason why it came to 2cents it was because we choose the option to no taxes on the drop box

**Comment by Omar1892** [comment]
And this is the way we have to do deposits. Since with the accrual basis doesn't work for us.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you please check this?

**Comment by Omar1892** [comment]
Yeah I already did 
    On Thursday, March 28, 2019, 5:48:05 AM PDT, Muhammad Uzair Shah <notifications@github.com> wrote:  
 
 
@usmanalikhan93
Can you please check this?

**Comment by fahadimran303** [comment]
@usmanalikhan93 This issue has been fixed.

We can close this ticket.
