### ISSUE TITLE
Accrual Basis VS Cash Basis 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#732]
Ive been working with you guys for the past 1 1/2 and from day one we can't take a deposit from a costumer because the system reflects the payment as accrual basis. Accrual Basis works on other countries or bigger companies. But not for small companies. For example: If we take a deposit on accrual basis the system reflect that we took the payment all at once when we only took part of the payment not the full amount. What happens next is, we have to pay the taxes for the full amount when the costumer only made a partial payment. This could work on companies that make millions on sales but not for small companies where 1 dollars makes a difference. Also by following the accrual basis we have to switch our whole accounting and booking system just to make it work accrual basis and for us to take a deposit. As instead if we work on cash basis the payments would reflect what we took only that day and what the costumer paid in taxes that day only. If a costumer doesn't come and pick their device up in accrual basis we would end up loosing money just by taking a simple deposit. I hope that I only speak for my self. If you guys can make the system both cash basis friendly and accrual basis so that we can choose what type of account we can follow that would be great. Im in the USA by the way.

**Comment by Uzair-RepairDesk** [comment]
Hi Omar @Omar1892,

Thank you for your suggestion. 
We are certainly looking to add a "Cash Basis" report in RepairDesk. We will develop a dedicated "Cash Bases Report" so you will be able to track down the actual payment received each day. 
Same request is listed here #690 
We have few challenges with current system behavior so we cannot replicate it in all our existing reports, however, we are working on a new report format that will bring the data on the cash basis. 

We are expecting to complete the document and design soon to start the development of the report. Thanks

**Comment by Omar1892** [comment]
Thats great news! It will help my account business a whole lot. Since for the past few months we have had to hold meetings since the system is glitchy and cash is being projected in the wrong way in some accounts. Hope fully you guys can look in to the report as well.

**Comment by Uzair-RepairDesk** [comment]
Hey @Omar1892 |

Thank you for your response. We are going to develop a dedicated "Cash Basis Report" so you will be able to track the sales that you actually make. 
Please find report design attached for your perusal. You can review and share your feedback. 

![With-Note](https://user-images.githubusercontent.com/22955861/55159658-6646ea80-5183-11e9-9cb7-bad34b1078eb.jpg)

The estimated time for the development of this report is around 2 weeks.

**Comment by Omar1892** [comment]
Hello, thank you for sharing. An issue that we constantly have is that we can't take deposits do to actual basis. If you could create a ticket and take a partial payment to see how the system reflects the payment if as accrual basis or cash basis? If we can take a partial payment via cash basis than we would be able to take deposits and the system should reflect the second payment on the day that is taken. This a suggestion that we have had for the past months. 


    On Thursday, March 28, 2019, 6:01:04 AM PDT, Muhammad Uzair Shah <notifications@github.com> wrote:  
 
 
Hey @Omar1892 |

Thank you for your response. We are going to develop a dedicated "Cash Basis Report" so you will be able to track the sales that you actually make.
Please find report design attached for your perusal. You can review and share your feedback.



The estimated time for the development of this report is around 2 weeks.

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 
Thank you for your feedback. With the help of new above report, you will be able to track deposit payment on the cash basis (that you actually receive). You can check the report format for more details. 

If you currently want to track the actual payment received, you can go to "Register Sales Report" that gives you insights of actual "Payment Received" and "Account Receivables" with the reference of Invoice.

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 

We have introduced a new report name with "Profit & Loss Reports" that is solely on a cash basis. Currently, we pushed it on LIVE for limited users to BETA test it. 
If you want to review it, can you please share your account credentials with me at uzair@repairdesk.co s I can make it enable to your account as well. Thanks

Hope to hear from you soon. Thanks.
