### ISSUE TITLE
Updating Parts consumption report with Category Criteria

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#733]
Have the ability to search parts consumption report by category similar to how the inventory summary operates.

**Comment by Trevorshaw7** [comment]
<img width="1395" alt="Screen Shot 2019-03-20 at 9 13 04 PM" src="https://user-images.githubusercontent.com/43588617/54731677-39784f00-4b55-11e9-8fc7-5bad103a6799.png">
<img width="843" alt="Screen Shot 2019-03-20 at 9 12 29 PM" src="https://user-images.githubusercontent.com/43588617/54731680-3c733f80-4b55-11e9-924e-827a342b98a4.png">

**Comment by Trevorshaw7** [comment]
Have the same search criteria,  as well as have the store drop downs and the ability to . select multiple stores

**Comment by Trevorshaw7** [comment]
But with the category as the search it will still list individual parts.  basically the inventory summary with the parts consumption data

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 

I am pleased to inform you that we have added "Category" criteria in the search filter of "Parts Consumption Report". 
You can filter the report with any specific category. 
Please check screenshot attached. 

![FIXAPHONE-Part-Consumption-Report](https://user-images.githubusercontent.com/22955861/55213084-08161800-5214-11e9-8b87-583162c723af.png)

**Comment by Trevorshaw7** [comment]
Thank you for this.  Is there also a way to make it so we can select multiple stores as well?
