### ISSUE TITLE
Notifications & email 

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#734]
There is now just one place where we can create notifications. Whether it is a message sent to the customer automatically or a message that we send manually via a ticket, there is only one place. It's in "settings" then "notification and email".

I created a message in the ticket tab when we use the "repaired and collected" status. This message asks customers if they liked their experience by suggesting they post their comment on the Google page of our company. I have set this automatic email message when we use this status. It works very well. We can also use it manually at the bottom of a ticket to send it to a customer who has not received it. This message is set differently by store since the link on the Google page is different for each store.

For example, the link of SOS Phone Limoilou is different from that of SOS Phone Lévis. Although the text is the same in all stores, the link has been modified and adapted according to the store. All of them work well at this level for the automatic sending of these emails when we use the "repaired and collected" status.

However, when we manually send the same message via a customer's ticket, only the main store link (SOS Phone Limoilou) is used. Even if we are connected in another store. There is a problem with the source of the message predefined in the tickets. As mentioned above, for automatic sending using a status, it works well.

Also, there is no color background configured in the source code of this same message. However, the background of the message is blue when sent using the "repaired and colected" status. I am unable to remove the color since it does not appear in the source code. For the same message sent via a ticket, the message background is white (no background). This is problematic, because when a link is used, the words that serve to lead a link are underlined and written in blue. The bottom of the message is blue, the link that leads to our Google page is almost transparent. Easy problem you think? I put the text of the link in white to make it stand out on the blue background, but via a ticket the bottom is white. White writing on a white background = nothing at all. The problem is not solved. Can you make sure that the messages in the "notifications & email" settings work the same with the statuses as the tickets and links work correctly between each store because they are configured differently?

Also, it is impossible to record messages without setting status. Example, I want to set up a message when we send a customer's phone in the mail. It does not happen that regularly and it may be possible that the client has the status "repaired" or "completed" or "repaired and collected" or "canceled" or "unlocked" etc ... so I can not the connected with a statutes. I also can not do an automatism with this message because it must be used manually as needed. Yet, I am not able to create a message without linking it to a status. Once the status is linked, it can no longer be used in another message. So I can not connect it to any one.

Suggestion, it would be nice to have a checkbox "apply this message in all shops" to avoid having to copy all the messages when the message applies to all shops._
<img width="944" alt="Notifcation   email" src="https://user-images.githubusercontent.com/40500094/54695330-1ec7bb00-4b00-11e9-833f-4928f6ab9c26.png">
<img width="535" alt="sent automatically because of the status" src="https://user-images.githubusercontent.com/40500094/54695340-24250580-4b00-11e9-933c-e31e3d5dd94a.png">
<img width="544" alt="Received from ticket (send manually)" src="https://user-images.githubusercontent.com/40500094/54695349-28512300-4b00-11e9-8e89-b3996d6b11e9.png">

_French:
Il y a maintenant juste un endroit ou nous pouvons créer des notifications. Que ce soit un message qui s'envoie au client automatiquement ou que ce soit un message que nous envoyons manuellement via un billet, il n'y a qu'un seul endroit. C'est dans "réglages" puis "notification et email".

J'ai créé un message dans l'onglet des billets lorsque nous utilisons le statuts "repaired and collected". Ce message demande aux clients s'ils ont aimé leur expérience en leur suggérant d'inscrire leur commentaire sur la page Google de notre entreprise. J'ai réglé ce message automatique par courriel lorsque nous utilisons ce statut. Cela fonctionne très bien. Nous pouvons aussi l'utiliser manuellement dans le bas d'un billet pour l'envoyer à un client qui ne l'aurait pas reçu. Ce message est configurer différemment par magasin puisque le lien de la page Google est différent pour chaque magasin.

Par exemple, le lien de SOS Phone Limoilou est différent de celui de SOS Phone Lévis. Bien que le texte soit le même dans toutes les boutiques, le lien a été modifier et adapter selon le magasin. Tous fonctionne bien à ce niveau pour l'envoie automatique de ces courriels lorsque nous utilisons le statut "repaired and collected".

Cependant, lorsque nous envoyons manuellement ce même message via le billet d'un client, seulement le lien du magasin principal (SOS Phone Limoilou) est utilisé. Même si nous sommes connecté dans un autre magasin. Il y a comme un problème avec la source des message prédéfini dans les billets. Tel que mentionné plus haut, pour l'envois automatique en utilisant un statut, cela fonctionne bien.

Aussi, il n'y a aucun fond de couleur de configuré dans le code source de ce même message. Pourtant, le fond du message est bleu lorsqu'il est envoyé en utilisant le statut "repaired and colected". Je suis incapable de retirer la couleur puisqu'elle n'apparait pas dans le code source. Pour le même message envoyé via un billet, le fond du message est blanc (aucun fond). Cela cause problème, car lorsqu'un lien est utilisé, les mots qui servent a dirigé un lien sont souligné et écrit en bleu. Le fond du message étant bleu, le lien qui mène sur notre page Google est donc presque transparent. Problème facile vous penssez? J'ai mis le texte du lien en blanc pour le faire ressortir sur le fond bleu, mais via un billet le fond est blanc. Écriture blanche sur un fond blanc = rien du tout. Le problème n'est donc pas résolu. Pouvez-vous faire en sorte que les messages dans les configurations "notifications & email" fonctionnent pareillement avec les statuts qu'avec les billets ainsi que les liens fonctionnent correctement entre chaque magasin puisqu'ils sont configuré différemment?

Aussi, il est impossible d'enregistrer des message sans mettre de statut. Exemple, je veux configurer un message lorsque nous envoyons le téléphone d'un client par la poste. Cela n'arrive pas si régulièrement que cela et il peut être possible que le client ai le statut "repaired" ou "completed" ou "repaired and collected" ou "cancelled" ou "unlocked" etc... Je ne peux donc pas le relié avec un statuts. Je ne peux pas non plus faire un automatisme avec ce message, car il doit être utilisé manuellement selon le besoin. Pourtant, je ne suis pas capable de créé un message sans le relié à un statut. Une fois que le statuts est relié, il ne peut plus être utilisé dans un autre message. Je ne peux donc pas le relié à n'importe lequel.
Suggestion, sa serait bien d'avoir une case à cocher "appliquer ce message dans toutes les boutiques" afin d'éviter d'avoir à toutes les recopier lorsque le message s'applique à toutes les boutiques._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1722

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. I have checked your concern related to this and it is working fine. I am attaching video for reference. Kindly check this and do let me know if you have any question. 

Video link: https://www.screencast.com/t/mq6ie1xQgL

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
I can not see the video I took a lot of my time to demonstrate the problem. I showed you screenshots and a detailed text of the problem. It does not work on my side. Please check again, perhaps with our users.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Whats the update on this?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you confirm me is this issue fixed or not ?

**Comment by JessicaSOS** [comment]
Not fixed yet!

 




	Jessica Fugère
Vice-présidente, SOS Phone

 <tel:4189991579> 418 999.1579 |  <tel:4506771579> 450 677.1579 |  <tel:18559991579> 1 855 999.1579 
 <mailto:jessica@sosphone.ca> jessica@sosphone.ca
 <https://sosphone.ca/?utm_source=signature&utm_medium=urlsite&utm_content=sosphone.ca&utm_campaign=outils> sosphone.ca
5375, boul. Guillaume Couture, Lévis, G6V 4Z3
2750, 1re Avenue, Limoilou, G1L 3N8
977, route de l'Église, Ste-Foy, G1V 3V3
835, rue St-Joseph Est, St-Roch, G1K 3C8
926, boul. Sainte-Foy, Longueuil, J4K 1V7

 <https://www.facebook.com/sosphonecanada/> 

 

 

De : Usman Ali Khan <notifications@github.com> 
Envoyé : 8 août 2019 03:28
À : Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS <RepairDesk-BUGS-IMPROVEMENTS@noreply.github.com>
Cc : JessicaSOS <jessica@sosphone.ca>; Mention <mention@noreply.github.com>
Objet : Re: [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS] Notifications & email (#734)

 

Hi @JessicaSOS <https://github.com/JessicaSOS> 

Can you confirm me is this issue fixed or not ?

**Comment by JessicaSOS** [comment]
not fixed yet

**Comment by JessicaSOS** [comment]
I really feel like you are closing tasks without even taking the time to look at what the problem is. there is nothing settled in this task. Do you know how much time I spend describing everything in as much detail as possible and making screenshots, retailers and identifiers so that it is easy to understand, translating each text before sending it to you? It takes me time, time I don't have. I also have to keep track of myself and most of the time, these tasks are closed without even being watched by your team. I am very disappointed with this. You asked me twice if it was settled and I told you that it was not. You have made no changes to the problem and no follow-up. You just closed the issue. Quite simple as a problem solving ...
--
J'ai vraiment l'impression que vous fermer des tâches sans même avoir pris le temps de regarder de quel problème il s'agit. il n'y a rien de réglé dans cette tâche. Savez-vous combien de temps je passe à tout décrire de facon la plus détaillé possible et en faisant des captures d'écran, les détaillants et les identifiants pour que ce soit facile à comprendre, en traduisant chaque texte avant de vous l'envoyer? Ça me prend du temps, temps que je n'ai pas. Je dois en plus me garder des suivis et la plupart du temps, ces tâches sont fermé sans même qu'elle ait été regardé par votre équipe. Je suis très décu de cela. Vous m'avez demandé a 2 reprises si c'était réglé et je vous ai mentionné que non. Vous n'avez fait aucune modification pour corrigé se problème et aucun suivi. Vous avez simplement fermé l'issue. Assez simple comme résolution de problème...

**Comment by Uzair-RepairDesk** [comment]
Hello @JessicaSOS 
I apologize on behalf of my team. We will make sure that we don't close any task without your confirmation. I have reopened it and we will review it again. Thanks

@usmanalikhan93 FYI

Regards,
Uzair

**Comment by JessicaSOS** [comment]
fixed now
