### ISSUE TITLE
Manual in and Out Transaction - Option to Upload Receipt

### ISSUE THREAD

**Issue by ochoaonline** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#736]
![DrPhoneFix Training Pos  Transactions Log](https://user-images.githubusercontent.com/35181467/54713322-b7703200-4b24-11e9-921b-98227e550631.png)

If is possible to be able to upload receipt of what was bought , to reflect on the Manual Out , this way management can easily see, the Transaction, the reason for it and the actual receipt for it

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 
Thank you for sharing your idea. We have plan to work on Manual In/out feature to give an option to "Edit" the record during the shift. #469 
I can link the above-requested improvement with the same so we can proceed with this at the same time.

**Comment by ochoaonline** [comment]
Thank You

**Comment by Uzair-RepairDesk** [comment]
Hey Modesto @ochoaonline 

Good News! We have added an option to upload "Reference Document" along with "Cash In/Out" record. 
You can also download the reference document from the report. 
We have also given the option to update/edit the record of "Cash In/Out" before you end the shift. 
You can find details from the following link:-
https://repairdesk.uservoice.com/knowledgebase/articles/810864-what-is-cash-in-out

Please review at your end.
