### ISSUE TITLE
Serialized Inventory option in RMA - Trevor | Bad Apple

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#737]
Hello Team,

Trevor from Bad Apple has come up with a request that he will like to send a Serialized Phone to supplier via RMA.

Currently we don't have the feature of sending serialized inventory item via RMA.

Thanks,

**Comment by Uzair-RepairDesk** [comment]
We have enhanced RMA module to link it up with Serialized inventory according to the requirement.
