### ISSUE TITLE
Add clone button within item view

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#738]
Request to add clone button within item view so you can easily and quickly add and clone new products.

**Comment by Uzair-RepairDesk** [comment]
Hi Will @TechreviveAu 
We have an option to "Clone" product from listing page. You can go to Action and clone the product to add a new product with the same details. Check screenshot attached. 
Currently, we don't have any specific action item available on the view ticket page. Is there any specific reason if you want it on the view page as well?

![clone product](https://user-images.githubusercontent.com/22955861/54909148-54f3a900-4f0b-11e9-86ab-1726e4164b9f.png)
