### ISSUE TITLE
Delete multiple tickets

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#739]
It would be great to select multiple tickets in the "Ticket View" screen so you can delete them instead of deleting one by one.

**Comment by Repair-Desk** [comment]
Hey Will,

Happy to help with this. We're looking to re-write repair ticket module that will allow you to

1- Delete multiple tickets
2- Update ticket status of multiple tickets
3- Option to display certain fields based on repair ticket workflow e.g. computer repair / MSP 
4- Deposits
5- Create multiple invoice against a ticket

We're looking to launch new ticket module hopefully by mid of Q3 however we will keep you posted on our progress and will certainly reach out to you for additional feedback :) 

Working together,

**Usman** 
**Your friend at RepairDesk**

**Comment by TechreviveAu** [comment]
No worries, looking forward to it :)
