### ISSUE TITLE
Individual stock costings

### ISSUE THREAD

**Issue by TechreviveAu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#740]
Stock has different cost prices depending on when it was purchased.
For example a supplier may have a special on iPhone 6 screens and they are significantly cheaper than other iPhone 6 screens purchased at a different time.

How can Repair Desk differentiate the cost of individual parts?

Currently repair desk only allows for cost price as a whole against stock. 

Would i have to start serializing my inventory to overcome this ?

**Comment by Repair-Desk** [comment]
Hello @TechreviveAu 

In the above scenario we would recommend you to use any of the below Inventory valuation methods:

- Weighted Average Cost (WAC)
- First In, First Out (FIFO)
- Last In, First Out (LIFO) 

The major difference b/w the method is how COGS is calculated. Most businesses in cellphone repair space prefer WAC (Weighted average cost) or FIFO (first in, first out). More info is available here: https://repairdesk.uservoice.com/knowledgebase/articles/1876849-what-is-inventory-valuation-and-how-it-works-in-re

If Inventory valuation methods are not implemented against your RepairDesk account please let us know and we will activate it against your RepairDesk account.

Working together,

Usman

**Comment by TechreviveAu** [comment]
Thank you. Speaking with Danish now :)
