### ISSUE TITLE
error when search a ticket in ipad app

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#741]
When you search for any ticket in ipad app in view ticket by entering the customer name in Arabic, no result is shown, why?

**Comment by Repair-Desk** [comment]
**Hey @hitman1986,** Sure thing! Let us take a look to see if we're getting the same issue as you and we'll circle back to you next week.

**@usmanalikhan93** Can you please check with iPAD team if customer name search supports arabic / unicode characters?

**Comment by usmanalikhan93** [comment]
Sure @Repair-Desk

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I have checked with iPad team and they said iPad app does not support multilingual language for now. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by hitman1986** [comment]
Thanks its working
