### ISSUE TITLE
error in label print

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#742]
When I print the ticket label from the iPad application it prints it incorrectly, sometimes it does not print the customer's name and sometimes does not print the problem of the device and sometimes prints it correctly knowing that when I print the same ticket that was printed incorrectly by the web program by google print cloud prints it correctly,why ?
Note that I write in Arabic.

**Comment by Repair-Desk** [comment]
Hi @hitman1986 

Can you please share a screenshot of ticket label that is printed through iPAD app?

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

We have checked your concern on our test account and it is printing successfully. Can you please check your printer settings with Danish ? 

And do share a screenshot with us of ticket label when it prints incorrectly.

**Comment by hitman1986** [comment]
I dont know ,how i can import screen shot in github

**Comment by hitman1986** [comment]
No this issue not in printer setting,because it printing normaly in wep by defulte or by google print , issue just when print by ipad app

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope your issue has been now resolved. I have talked to danish he has confirmed that we are good now.

**Comment by hitman1986** [comment]
Thanks ,issue sloved

**Comment by hitman1986** [comment]
Yes working now

**Comment by hitman1986** [comment]
Thank to you and danish
