### ISSUE TITLE
Refund a with Square not an option on the iPad APP.

### ISSUE THREAD

**Issue by 1TonyBA** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#743]
When doing a refund on the iPad there is not an option to process it through Square, it only gives you a "Cash" option. Is there a setting for this or something we are overlooking? 
![img_0012 3 57 26 PM](https://user-images.githubusercontent.com/44849184/54957209-b02b9880-4f17-11e9-90a7-646f755338f7.png)
![IMG_0011](https://user-images.githubusercontent.com/44849184/54957210-b0c42f00-4f17-11e9-8aeb-84667c31a95a.PNG)
![IMG_0010](https://user-images.githubusercontent.com/44849184/54957211-b0c42f00-4f17-11e9-837e-5a95181aa582.PNG)

**Comment by Uzair-RepairDesk** [comment]
Hey @1TonyBA 
The refund option is available with "Square Deep" integration if you process it with iPad POS Register. The above transaction seems to be done using Square redirect integration.

You can find more details about our "Square Deep" integration from the following knowledgebase article:-
https://repairdesk.uservoice.com/knowledgebase/articles/1877980-square-deep-integration-and-repairdesk-ipad-pos-re
