### ISSUE TITLE
Partial Refunds 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#744]
Hello, 

today I had an issue with a costumer where we had to downgrade the repair to a cheaper repair on an invoice that was paid for 1 month ago. At check out the system would not recognize the due refund amount and was projecting the amount as a pending balance that the costumer owed us. I had to do the refund from the ticket it self as on the Add A Payment. It did let me do the refund but I wasn't able to do it from the POS. If you guys can look it to it to make it easier when this comes up.

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 
Currently, RepairDesk allows doing refunds for full "Paid" invoices from POS. 
If you proceed with refunds from POS, you can refund with respect to quantity or amount. 
You can find more details from the following link:-
https://repairdesk.uservoice.com/knowledgebase/articles/895113-how-can-i-process-refund-exchange-in-repairdesk

If you want to refund for "Partial" paid invoices, you can either do it from the "Add Payment" option from Ticket or Invoice. 

Hope it helps.

**Comment by Omar1892** [comment]
Thats the way we usually we do it. But this is what happened. The costumer had came in 2 months ago for a repair thats worth $129.99 he had come back in because he was having an issue with the part we had installed and the only way to fix it was to downgrade the repair from $129.99 to $89.99 so we had to do a partial refund on the already paid invoice/ticket. When we did the modification the system was telling us at check out that the costumer owed the repair amount of $89.99 but in this case we owed the costumer the difference of $40.00 dollars since he was down grading to a cheaper repair. If you wan't just close this issue. im going to recreat the issue with a rep so I can show him what I did and they might be able to explain what happen much better than I can.

**Comment by Uzair-RepairDesk** [comment]
Thank you for your response @Omar1892 
I have asked one of my "Customer Relationship Executive" to give you a call on this. He can check the scenario in detail and advise you accordingly. Thanks

**Comment by Omar1892** [comment]
Thank you, they did. 
    On Thursday, March 28, 2019, 5:57:49 AM PDT, Muhammad Uzair Shah <notifications@github.com> wrote:  
 
 
Thank you for your response @Omar1892
I have asked one of my "Customer Relationship Executive" to give you a call on this. He can check the scenario in detail and advise you accordingly. Thanks
