### ISSUE TITLE
Not being able to revert Trade-in from sold to in stock.

### ISSUE THREAD

**Issue by GR-Phones** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#745]
I am trying to change a Trade-in from sold to back in stock as this was returned from a customer.

![image](https://user-images.githubusercontent.com/49067571/55234476-27687180-5223-11e9-9b9c-b9f9c5796918.png)

I have had no issues previously it would let me change this no problem.

Please can you revert this option as it is something that I need to do daily. 

I am unsure as to why you removed this option.

**Comment by fahadimran303** [comment]
Hello Alexandros,

I hope you are doing well.

**Not being able to revert Trade-in from sold to in stock**

In order to standardize the reports, we have added this functionality that **Sold Status of Trade In** can't be changed.

Appreciate your understanding,

Regards,

**Comment by GR-Phones** [comment]
Hi, 
Is there a way to revert 2 items as i can not add the sales details for this to keep our sales up to date. They were just manually changed before a sale was created.

Also how do we put the item back in to stock if the customer returns the item? As we would not want to add the item again as the sales figure would then show as sold twice.

This has made it harder to use your software and if this is not something that can be change we may have to use a different software all together.

**Comment by usmanalikhan93** [comment]
Hi @GR-Phones 

Sure thing. Let me discuss this with developer and sort your query ASAP.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1786

**Comment by usmanalikhan93** [comment]
Hi @GR-Phones 

We have updated your those 2 trade in's which you have mentioned to Danish. Please verify at your end and do let us know if you have any question. 

Thanks
Usman Ali.
