### ISSUE TITLE
Problem with "marketing automation"

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#747]
Hello,
While doing tests, I created repair tickets in my name. I received the automatic email that is in the "marketing automation" (see attachment). However, the setting is not enabled. So, I do not understand why I received this. In addition, I imagine that all my clients receive this and it should not be the case since the option is disabled. Can you please come back to me.
Have a good day
<img width="943" alt="Marketing Automation disactivated" src="https://user-images.githubusercontent.com/40500094/55250107-e6249180-5223-11e9-9bb6-4824cac250d4.png">
<img width="917" alt="suivi de réparation" src="https://user-images.githubusercontent.com/40500094/55250132-ee7ccc80-5223-11e9-8a60-e33ff0c86fe1.png">

--
French:
Bonjour,
En faisant des tests, j'ai créé des billets de réparation à mon nom. J'ai reçu le courriel automatique qui est dans le "marketing automation" (voir pièce jointe). Cependant, le réglage n'est pas activé. Alors, je ne comprend pas pourquoi j'ai reçu cela. De plus, j'imagine que tous mes clients recoivent cela et sa ne doit pas être le cas puisque l'option est désactivé. Pouvez-vous me revenir svp.
Bonne journée

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by JessicaSOS** [comment]
do you see ?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Yes I checked it thoroughly. I have checked the content even it does not matched. Email was not from the campaigner. If campaigner is not active then no email sent to anybody. Please check this again at your end. 

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali.

**Comment by JessicaSOS** [comment]
ok let's do that
