### ISSUE TITLE
RMA has tax listed

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#748]
RMA has tax listed, this does not make sense, because this isn't a sale and tax wouldn't be applicable in this scenario.  Can we delete the tax category from the RMA, because currently it is overstating the RMA amount by this tax amount
<img width="1425" alt="Screen Shot 2019-03-29 at 11 18 02 AM" src="https://user-images.githubusercontent.com/43588617/55250679-5deac000-5214-11e9-903f-bf9b6d194e23.png">

**Comment by Repair-Desk** [comment]
****Hello @Trevorshaw7**** 

Thanks a lot for sharing your feedback. I see where you are coming from on this though, so I'm happy to pass on this feedback to the team for you  

We will discuss this internally early next week and update this thread accordingly. 

If you ever have any other questions, or if I can do anything else at all for you, you know where to find me! Have a great day! 🎉 

Best,
**Usman**

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7,
Currently item populates according to the tax class, we will still see the feasibility to exclude tax from RMA however I will advise you to select “Tax Exempt” class for the item if you want to keep the price without tax.

**Comment by Trevorshaw7** [comment]
It's a step that should not have to be taken though. And I do t trust that
my employees will take that step.

**Comment by Uzair-RepairDesk** [comment]
**Update:** I am adding it the sprint plan so we can give an option to set default tax class for RMA. You will be able to select the "Tax Exempt" class so there should not be any tax value once you create an RMA.

**Comment by Uzair-RepairDesk** [comment]
Hey @Trevorshaw7 
We have made your requested enhancement LIVE. You can now select a default tax class for RMA from Store Settings > Module Configurations > RMA > Default Tax class for RMA's
You can select the "Tax Exempt" class if you don't want to include a tax value on items while creating an RMA. 

Please review at your end. Thanks. 

![uzairshah   Rma Config](https://user-images.githubusercontent.com/22955861/56575486-40c0cb80-65df-11e9-8d44-50becc384ac6.png)
