### ISSUE TITLE
RMA Uploading Issue 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#751]
When editing an RMA and pressing save once all the modifications have been done. My computer screen turns white and it won't upload do anything else. This just started happening.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-1767

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali.
