### ISSUE TITLE
"Assignment" in the management of employees

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#753]
It would be nice to be able to assign "Assignment" in the management of employees without having to give access to this person ... I say this because currently, without access, it is impossible for me to send an email from a ticket whose person has access due to a ticket transfer. That is not very practical.

--
French:
Sa serait bien d'être capable d'assigner "Assignment" dans la gestion des employés sans avoir à donner accès a cette personne...Je dit cela car actuellement, sans accès, il m'est impossible d'envoyer un courriel à partir d'un billet dont la personne à accès à cause d'un transfert de billet. Ce n'est pas très pratique.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 

Thank you for your suggestion however it's not possible to set "Assignment" without giving "Access" to that specific store. If a user doesn't have "Access" option and you assign him/her ticket/lead of any activity, he/she will not be able to view details. 

If a specific user wants to send an email to another user only, you can give "Access" of the store without giving him "Assignment" of that store. Hope you can understand. Thanks

**Comment by JessicaSOS** [comment]
But if this person has "Access" to the store, she has access to view everything from the store. However, if a ticket comes from Limoilou and I send it for repair in Longueuil (by transferring a ticket), I do not want to give access to the Limoilou store to my Longueuil employee only so that he can send me an email for a ticket about the limoilou shop. I only want him to be able to repair and send emails to anyone. If I follow your logic, so that we can continue to speak this through the system, I must give access to all my employees at the 5 shops. It does not make sense.

--
french:
But if this person has "Access" to the store, she has access to view everything from the store. However, if a ticket comes from Limoilou and I send it for repair in Longueuil (by transferring a ticket), I do not want to give access to the Limoilou store to my Longueuil employee only so that he can send me an email for a ticket about the limoilou shop. I only want him to be able to make the repair and send e-mails to whom he is entitled. If I follow your logic, so that we can continue to speak this through the system, I must give access to all my employees at the 5 shops. It does not make sense.

**Comment by Uzair-RepairDesk** [comment]
Hey @JessicaSOS 
Perhaps you got the confusion in this workflow.
Let me explain your concerns below:-

1: his person has "Access" to the store, she has access to view everything from the store.
**If you give "Access" to the store, you can restrict employee to only access certain areas from "Roles & Permissions" module. If there is access, it doesn't mean that specific employee can access everything.** 

**2: When you transfer a ticket you can assign it to an employee who has "Access" to that store and he can also access to the ticket from the same store. Once employee repairs the device, he/she can also send an email from the same store. There is no need to give access to the first store to that employee.** 

If there is any other case in the transfer, please share the screenshots with the description so I can assist you further. Thanks.

**Comment by JessicaSOS** [comment]
I understand that it is not because a person has access to the store, that it is necessary to have access to all in this store. However, in post privileges, we can grant access to privileges, but these same privileges are also available in branch offices. So if I give access to the ticket creation in the default store to an employee, he will have access to create tickets in all the branches I will give him access to. So that's not what I want. What I want is only to assign it when a ticket has been transferred since it is this person who made the repair. I want to be able to send him an email about the ticket he repaired as well. It's not bad all. Do you understand that the employee will have access to do all that he can currently do in his default store, but in all other stores that I will give him access.

--
french:
Je comprends que ce n'est pas parce qu'une personne a accès au magasin, qu'elle est obliger d'avoir accès à tous dans ce magasin. Cependant, dans les privilèges des postes, nous pouvons donner accès a des privilèges, mais ces mêmes privilèges sont également disponible dans les succursales. Donc si je donne accès a la création de billet dans le magasin par défaut a un employé, il aura accès a créer des billets dans toutes les succursales dont je lui donnerai accès. Ce n'est donc pas ce que je veux. Ce que je souhaite c'est uniquement de l'assigner lorsqu'un billet a été transféré puisque c'est cette personne qui a effectuer la réparation. Je veux pouvoir lui envoyer un courriel concernant le billet qu'il a réparé également. C'est pas mal tout. Est-ce que vous comprenez que l'employé aura accès a faire tous ce qu'il peux actuellement faire dans son magasin par défaut, mais dans tous les autres magasins dont je lui donnerai accès.

**Comment by JessicaSOS** [comment]
I give access to all employees in all branches in order to be able to see inventory in the summary of invention and to be able to send e-mails to our colleagues from other stores. All the worlds can therefore do in all stores. It was not what I wanted, but since you closed this task, I understood that it was the only solution ...
