### ISSUE TITLE
Problem with Appointements in Lévis Store

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#754]
Hi!
Online appointments work for all stores except Lévis. However, we touched nothing and all the settings of RepairDesk are similar to Lévis in other shops. I wanted to go see the iFrame code that is registered and nothing has changed to level. I have access to see the devices and repair available. The problem is that I have no date available to make an appointment. However, in the settings of the Lévis store, the opening hours are from Monday to Friday and the hours are correctly configured. (see attachment) In addition, there is no vacancy or set holiday period that could have interfered with the hours of operation. What's the problem ??
Thank you and good day
<img width="946" alt="Lévis store appointement setting" src="https://user-images.githubusercontent.com/40500094/55574030-62621d80-56d9-11e9-8314-277b2cdcd86f.png">
<img width="938" alt="appointement online" src="https://user-images.githubusercontent.com/40500094/55574039-6726d180-56d9-11e9-8cc3-a6f14d2dbc5c.png">

--
french:
Salut!
Les rendez-vous en ligne fonctionnent pour toutes les boutiques, sauf Lévis. Pourtant, on a touché a rien et tous les réglages de RepairDesk sont pareil à Lévis que dans les autres boutiques. Je voulais aller voir le code iFrame qui est inscrit et rien n'a changé a se niveau. J'ai accès a voir les appareils et les réparation disponible. Le problème c'est que je n'ai aucune date de disponible pour prendre un rendez-vous. Pourtant, dans les réglages du magasin de Lévis, les heures d'ouvertures sont du lundi au vendredi et les heures sont correctement configuré. (voir pièce jointe) De plus, il n'y a aucune période de vacance ou de jour fériés de configuré qui aurait pu interféré avec les heures d'ouvertures. Quel est le problème ??
Merci et bonne journée

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
I have checked this @JessicaSOS, there is something wrong. I have discussed this with developer. He will look into it.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1821

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Your lead L-Le-20512 in Levis store has set date from 25 May 2019 to 25 March 2019. May be someone done this accidentally. This is the reason you are not seeing calendar in Appointment Widget. Now I have done it as 25 March 2019. Now everything is perfect. Please verify at your end. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
oh, tnx! Is fixed ;)
