### ISSUE TITLE
Integration: Pop Up Screen At Check Out 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#755]
Hello, I would like to share an idea. When were checking out a costumer at the end of a repair it would be a good idea for a pop up screen to remind us to offer accessories or any deals that we have going on in the store. 

Another thing, a lot of iPhones are having a lot of motherboard issues lately. And it would be a good idea that a device is selected a pop screen comes just as a reminder of what issues that phone has and possibly during a repair they can come up. For example the iPhone 7/7+ has the mic issue that once the chip on the motherboard gets damaged it can cause the touch to go faulty as well and it isn't the part it self. This would save us as techs a lot of RMAs and sales can increase in the stores.

**Comment by Uzair-RepairDesk** [comment]
**Hi @Omar1892** 

I really appreciate that you took the time to share your ideas. I can certainly see how the suggested improvements would be useful. The above requested enhancement is actually "**Suggestive Sales Alert**" functionality. We already planned to do it for "Inventory Items" where you can mark few inventory items and the system can give you an alert to add them in the transaction. 
We can't do it specifically for services as well however it's certainly possible for "Inventory" and "Casual" items. 
We made a functionality specification document for this as well. If you are interested, I can share a document with you so you can review and share your feedback. 

Our current focus is "Product Stability" and "Updates in existing features", however, we certainly have to work on this feature in the coming quarter. 

If you have any further question, please feel free to ask. Thanks.

**Comment by Omar1892** [comment]
Yeah, if you like to send me an email I can check it out.

Thank you.
