### ISSUE TITLE
Booking In A Ticket 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#756]
I would like to report an issue when booking in a repair. Instead of creating a ticket, it will create an invoice and it won't let us create a ticket. It has happen 2 times in this week.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I have checked your concern but it seems to work fine on my test account. Can you help me to reproduce this issue ? The steps you were performing while making a ticket.

**Comment by Omar1892** [comment]
Hi, it happen randomly to me and my business partner last week. Since than we haven't had the issue again. But if it happens again ill just take a screen shot so I can send it over to you guys.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Thanks for the response. For now I am closing this task. If you face this issue again, you can message me here with a screenshot or a short video. 

Thanks 
Usman Ali.
