### ISSUE TITLE
Address Search

### ISSUE THREAD

**Issue by SajAbu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#757]
If we could search for customers using their address or post code as we have many duplicate names and customers don't usually remember their mobile numbers

**Comment by Uzair-RepairDesk** [comment]
Hi @SajAbu
 
Happy to help you with this. Currently, there are the following 2 primary keys to make a unique record for each customer:-
1: Email Address
2: Mobile Number

You can keep an email address as well and search it from email if you find out a unique record. 

Hope it help.

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by SajAbu** [comment]
is it possible to re open this. We want to be able to search for customers using their postcode. is it possible to add a search function to do this?

**Comment by Uzair-RepairDesk** [comment]
Hi @SajAbu 
Hope you are doing well 
Have a good news for you! As you have requested earlier, we have added the functionality to search customer through POSTCODE and ADDRESS Field. Please give it a review at your end and let us know if it works for you. 

Looking forward to your feedback. 

Regards,

**Comment by SajAbu** [comment]
Just tested it. works like a charm! Thank you!

Kindest Regards,

Sajid Abubaker
*Company Director*
*Capital Connection (London) Limited*
154 Mile End Road | Stepney Green | London | E1 4LJ
020 7265 9999
www.capitalconnections.co.uk
