### ISSUE TITLE
Problem with refunds

### ISSUE THREAD

**Issue by ireparo** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#758]
https://drive.google.com/file/d/123FsDkBg8YS9SN90CKQX6ilXMlAl3lDq/view

I get 0€from a refund

**Comment by usmanalikhan93** [comment]
Hi @ireparo 

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @ireparo 

I hope our support guy has guided you with the solution and you are now good with steps. And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks 
Usman Ali.
