### ISSUE TITLE
POS items disappear on checkout window

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#760]
It happens every day. 2-3 times at least.
It is very hard to make video of this bug and expalin it exactly when its appearing. 
because it comes randomly and its so annoying.

What happens is :
We add some products for sale in pos . when we click checkout payment windows appear.

Now here three types of issue happening (Sometimes )
1. while this payment window is opened, the added products in pos disappears at the background.
So when we click add payment, or whatever, it does nothing, it just go back to pos page without doing anything. and we will have to do whole process again.
2.  after adding product , when we click checkout the amount comes there 0.00 (ZERO).
then we do checkout, software does nothing.it just go back to pos page without doing anything. and we will have to do whole process again.
3. if pos have ticket item and inventory item both added in pos , and we click on checkout, we can see that inventory item get disappears in background but ticket items stays there (and vise-versa).
Second scenario appears very less as compare to first one.

Issue happens randomly, we have tested, in all means. such as;
we added product by scanning,
we added product manually by search.
item added in pos and we waited for 40-50 seconds to click on checkout.
item added in pos and checkout is pressed qucikly in few seconds.

it doesn't happens all the time, it happens sometimes. so please do not ask me to make a video proof of this issue because i can't run video recorder whole day as i dont know when it will appear.

My staff is so scared from this bug that when any customer is buying so many products, they actually go to Repair Tab and click on New Invoice and do all process of adding product there.

**Comment by usmanalikhan93** [comment]
Hey Bharat @bharaaus ,
 
Usman Ali, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Are you able to replicate the reported issue?

**Comment by bharaaus** [comment]
This is tagged as HELP Wanted ?

This is a serious Bug which we face everyday.

Any update on this ?

My staff is so pissed due to this bug

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I have tried this so many times but it was not appear on our test accounts. Did you open POS in multiple tabs on same browser ?

**Comment by bharaaus** [comment]
no .
only one tab.

have tried clear caches/history etc.

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
Is it possible to share a video if you randomly face it so we can replicate it at our end and get it fixed?

**Comment by bharaaus** [comment]
I can't put the camera on the computer whole day and wait for it to happen.

**Comment by Uzair-RepairDesk** [comment]
I understand this. I just requested that if you face it again and if it possible then please share a video with us. 
@usmanalikhan93 
I believe you have already escalated it in the team, please keep track on it and keep trying to replicate it.

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk Sure, I will try to replicate this on my test account.

**Comment by bharaaus** [comment]
[New Project.zip](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/3168534/New.Project.zip)

Video of Bug !

For password plz contact me private, because video has customer detail .

Please note that this error is random. In video we have two tabs opened, and item asked for serialization.
But bug occurs even for common sale items as well.

**Comment by bharaaus** [comment]
@usmanalikhan93  . Try to replicate this error in you test account with USER PIN enabled. 
May be its due to that.

**Comment by bharaaus** [comment]
[New Project-123.zip](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/3168560/New.Project-123.zip)

Another video of bug occurs again.

We prefer to use Mozilla Firefox because this bug appears less in Mozilla. In chrome it trouble us more.


Im surprise you guys can not replicate this at your end.
and my topic is still marked as " Help Wanted "

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

Thanks for the information you provided. Let me try these steps and replicate this issue on my end.

**Comment by bharaaus** [comment]
Any luck fixing this issue ?
Its still poping up everyday.

**Comment by usmanalikhan93** [comment]
No @bharaaus didn't replicate on my side but I am trying to do so, so we will fix this. Once we get the use case it will easy for developer to fix this issue. I will update you once I get any luck on this.

**Comment by bharaaus** [comment]
you couldn't get it from video ?
It is happeing now at leaset 5-10 times a day.
I can send you more videos of it if you like.

**Comment by bharaaus** [comment]
check my store settings as well, and try to do same settings on your account to see if its something from settings. ?

Such as :
Employee Pin Activate
Number of Employee Registgerd
etc.

or anything. 

You guys are the expert , you should figure it out quickly that why im facing this issue everyday, but you are not.

**Comment by usmanalikhan93** [comment]
@bharaaus ok let me try to replicate these settings on my test account and check with this.

**Comment by bharaaus** [comment]
did you try before by enabling the emplyee pin, or without pin ?

**Comment by usmanalikhan93** [comment]
Yes I have checked by enabling the employee pin.

**Comment by bharaaus** [comment]
Any update on this guys !
This bug is so annoying

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
We are just back to work after EID Holidays. 

@usmanalikhan93 Can we have an update for our friend? 
Can you again post an update on an internal task and request all QA team to replicate it? 
Also, discuss it with CTO once. Thanks

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk. 

For internal use: 
https://repairdesk.atlassian.net/browse/RB-147

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I have tried almost every scenario to reproduce this issue but it doesn't come on our browsers once. What I get in my mind is that install your browser again may be that will resolve this issue. Do let me know once you do this.
