### ISSUE TITLE
Need Color Option in POS while booking ticket

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#764]
It will be much helpful if we can choose the color of the phone while booking the repair job.

We are adding color in description, but doens't looks professional.

Can you consider adding this opiton ?

**Comment by Uzair-RepairDesk** [comment]
Hi Bharat, @bharaaus 

Hope you are well. I am pleased to inform you that we have added "Custom fields functionality" in RepairDesk. 

Our goal at RepairDesk is to empower repair shops including cell phone and computer repair stores, by providing them tools that help them move forward and today, we’re a step closer to that goal, with the release of custom fields.

With custom fields, now you can create a text field for device type, color, special order notes, priority, or anything else that’s important to your workflow for a more personalized system that also gives your technicians clarity on repair jobs across the board and these fields are specific to each repair category. We hope you LOVE it!

There are three types of custom fields you can create in RepairDesk:

- Textfield
- Dropdown
- Checkbox

You can check knowledgebase and video to use custom fields functionality in RepairDesk

https://repairdesk.uservoice.com/knowledgebase/articles/1921693-custom-fields

Please also check screenshot attached

![color custo fields](https://user-images.githubusercontent.com/22955861/64323902-cf5a4600-cfde-11e9-963b-43112f0c8df7.png)

If you have any questions, please feel free to ask. Thanks
