### ISSUE TITLE
Need Smart Search Option in Inventory Section and/or on Top Menu

### ISSUE THREAD

**Issue by BharatPRC** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#765]
In Inventory tab, There is only Search Filter, but there is no SMART SEARCH option.
Smart Search like in POS, where we type anything and it brings up the product.

Instead there is a search which demands the exact product name which is not possible for us to type exactly as product name every time.

and search filter is sometimes time consuming.

Also, it would be very usefull to have this opiton on top tab all the time (where you have search option already ) so we can search any product fast, instead of going to inventory or pos window only.

**Comment by Uzair-RepairDesk** [comment]
Hey Bharat @bharaaus, 
We are already working on this improvement to allow suggestive search under "Manage Inventory" when you search item from "Product/Item" name. 
It's expected to GO LIVE in next week release. 

Thank you for your suggestion to also search inventory item from the top bar search as well.  We can certainly look into that as well. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
We have added "Suggestive Search" functionality under Manage inventory if you search any product/item with "Item Name" field. 
Please review at your end. Thanks

**Comment by bharaaus** [comment]
I have review at my end.
Its not working still.

**Comment by Uzair-RepairDesk** [comment]
Hi @bharaaus 
Can you please share screenshot where you exactly reviewing it so I can look into it. Thanks

**Comment by bharaaus** [comment]
![ice_screenshot_20190429-142840](https://user-images.githubusercontent.com/34261339/56876496-1a8da680-6a8b-11e9-816d-2e6a00f42aee.png)

**Comment by Uzair-RepairDesk** [comment]
@bharaaus 
Thank you for highlighting this. We reverted the code from this specific area. I have discussed it with the team to update it. I will inform you once it's updated again.

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
We have added "Suggestive Search" functionality for "Item Name" under "Manage Inventory > Mobile, Accessories & Parts".
Please check screenshot attached.
![search](https://user-images.githubusercontent.com/22955861/58078778-f83e0300-7bc8-11e9-99d4-f35924db6c8f.png)


We are also working on the document to add "Inventory" search in the global search along with Invoices, Tickets & Customers. We will start development after document and design.

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
We are going to develop a dedicated global inventory search inventory module that will allow you to search inventory item from the popup that will come up from the global search. Hopefully, we will start the development next week. 
Please review and share your feedback. Thanks

Check screenshot attached. 

![search-inventory-popup-dpdated-1](https://user-images.githubusercontent.com/22955861/60337525-b91b8280-99bc-11e9-92af-aeac51352d4e.jpg)

**Comment by bharaaus** [comment]
Thanks, But on your above picture, it doesnt looks like it has smart search option, please make sure to add that in the update
