### ISSUE TITLE
Newly added Device not showing in Repair Category in POS

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#766]
When we create new mobile device, it doesn't show in repair category in POS window.
Even if SHOW IN POS trigger is enabled.
To show it there, I will have to go to Settings>Module Configration>View All Repair Category>
and edit each Catgory/Manufacture > Find the model and add in category.
It is so time consuming.
It always cause trouble. because while booking repair, if we dont see the phone model there, we click on Add New, and while adding, it shows error saying Product is Already Available.

When customer is in front of us, we can not go to setting and add that model in cateogry manually.

Show on POS Trigger is not adding the phone model in repair category.

Please have a look at it.Thanks

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you review this?

**Comment by usmanalikhan93** [comment]
Hi @Uzair-RepairDesk 

Sure thing.

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I hope Danish has messaged to discuss this issue. Do let me know if you have any question.

**Comment by bharaaus** [comment]
I have made a video of this bug.

It was reported more than year ago, but nothing is done with it.
New Model added outside pos windows are not showing in POS when chossing repair. Even though option of " SHOW IN POS " is active.

This is happeing because whenever we add new model in pos window, it doenst have option to choose Category which we have enabled in pos.


[ice_video_20190514-213226.zip](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/3177412/ice_video_20190514-213226.zip)

**Comment by usmanalikhan93** [comment]
Thanks for the information @bharaaus . Let me check this.

**Comment by bharaaus** [comment]
Guys !
This is so frustating that this issue is not fixed yet.

Everytime I had to go to settings>product category> then rechoose the model to add under that category , which should be added by itself.

and i have already disucussed with you that when we make new model in pop up menu, it doesn't have option to choose category, that is why new model doens't sit under any category.

Are you guys willing to fix this issue ? or you just ignoring it ?

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

We are doing internal QA of Repairs section and I will try to accommodate this task in it once I get approval by our product manager. I will update you once I have more information on this. 

Thanks
Usman Ali

**Comment by bharaaus** [comment]
Any update ?
This is fricking annoying. 
This is a freaking bug , not a new task which needs approvals.

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I have tried this to reproduce on my end but it does display on POS. Please see video. 
Video link: https://drive.google.com/file/d/10NgNAwW2xgK_dtumXqTbSOwEfQRqM5VZ/view

**Comment by bharaaus** [comment]
Bravo !!! 

It took you 4 months to get back to me with this Answer?
And if there is no issue, why you guys were waiting for approval from product manager? 
What were you guys doing from last 4 months?

**Comment by bharaaus** [comment]
The issue is still there.
You guys are just ignoring it and not discussing it.

https://www.screencast.com/t/K9bXlmslkS

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

What you were saying is only possible when you disable repair category then it will work accordingly. But we cannot map devices like this as it may rush on POS. So you have to map it in that category in which you show it on POS. 
Danish will also guide you tomorrow on call. I apologize for the delay but I can say its not a "BUG", it's our workflow. 
Do let me know if you have any question.

Thanks
Usman Ali

**Comment by bharaaus** [comment]
No Question Mate!
You guys have already wasted my 4 months just in the wait of reply that there is nothing you can do about it.
Appreciate it!
