### ISSUE TITLE
Intransit after accepted

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#767]
We have a phone that is in transit after it was accepted from a transfer
![image (1)](https://user-images.githubusercontent.com/43588617/55893955-7c3aaf00-5b76-11e9-99bc-6850c1391759.png)
![image](https://user-images.githubusercontent.com/43588617/55893957-7c3aaf00-5b76-11e9-84fc-1f77a5a56e87.png)

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

I believe this issue has been fixed and Fayyaz has updated you on messenger. Do let me know if you have any question. 

Thanks
Usman Ali.
