### ISSUE TITLE
Duplicating items on a stock transfer

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#768]
The ipad was added after hitting save for the second time, so it it sending 2 when there should only be 1.  It happens after you hit save
![Screen Shot 2019-04-10 at 9 50 17 AM](https://user-images.githubusercontent.com/43588617/55894202-efdcbc00-5b76-11e9-97ea-776ebb237a0f.png)

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Can you tell me the transfer order ID ? And in which store it is ?

**Comment by Trevorshaw7** [comment]
Sugarhouse

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

I hope you are doing well. I believe this issue has been fixed by Fayyaz. I hope that if there’s anything else I can do for you, you won’t hesitate to let me know.

Thanks 
Usman Ali.
