### ISSUE TITLE
Voided Commission 

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#769]
I clicked on "void" for all the commissions of Olivier dated of April 8, 2019 while it is another employee who worked on his use that day. I release this report in the detailed commission report. However, when I go into commissions payable to the employee, nothing changes. It's like I did not have to click on "void" to voided all those bills.
<img width="946" alt="Voided commission Olivier" src="https://user-images.githubusercontent.com/40500094/55910896-83c97a80-5bad-11e9-8643-d56b11a6ac0c.png">
<img width="944" alt="commission report Olivier" src="https://user-images.githubusercontent.com/40500094/55910912-888e2e80-5bad-11e9-8b42-ba27e41c8707.png">

_--
french:
J'ai cliqué sur "void" pour toutes les commissions d'Olivier en date du 8 avril 2019 pusqu'il c'est un autre employé qui a travailler sur son user cette journée là. J'ai sortie ce rapport dans le rapport détaillé des commissions. Cependant, quand je vais dans les commissions payable a l'employé, rien ne change. C'est comme si je n'avais pas cliquer sur "void" afin de voided toutes ces factures._

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you explain this more ?

**Comment by JessicaSOS** [comment]
Voided serves to not pay the employees for the commits. So I "voided" the bills of the day that I did not want to pay to the employee. Once all invoices are "voided", no change is displayed. It's like nothing happened.

**Comment by usmanalikhan93** [comment]
Ok let me check this @JessicaSOS.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sure thing. Let me discuss this with my product manager then I will revert back to you.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-259

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
