### ISSUE TITLE
Multiple Minor Improvements

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#771]
1- While entering employee pin it will be really helpful if you can search employee name by entering their initial. Also employee names should be listed alphabetically.

![RepairDesk - Search employee profile](https://user-images.githubusercontent.com/21986026/55984856-e444de80-5cb7-11e9-8991-e79bde8ce226.jpg)

2- It would be super helpful if you can set a default tax class for purchase orders so you don't have to manually select a tax class from the dropdown everytime. Most purchase orders have tax exempt tax class.

See below: 
![RepairDesk - Select tax class dropdown](https://user-images.githubusercontent.com/21986026/55984721-86b09200-5cb7-11e9-9a3d-68fa28c4f32a.jpg)

**Comment by Uzair-RepairDesk** [comment]
**Update:** I have added it in sprint plan.

**Comment by Uzair-RepairDesk** [comment]
We have made both improvements LIVE. 
1: You can now search employee while entering access PIN
2: You can select a default tax class for a purchase order from Store Settings > Module Configurations > Purchase Order > Default Tax class for Purchase orders.
