### ISSUE TITLE
Item stuck in an inventory transfer

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#772]
Item # 12161 is in stock at Ste-Foy. An error message is displayed stating that the quantity available for the transfer can not be less than the quantity in stock. However, the item is "in stock" so available. I wish to transfer this item and despite the error message, I was able to put it in the transfer from Ste-Foy to Limoilou # 3242. I can visualize the item in the inventory transfer, but as soon as I try to open it for viewing the transfer or in order to receive the item, the product is gone and is no longer in the inventory transfer .
Thank you for going to see the transfer mentioned above.

--
french:
L'item #12161 est en stock à Ste-Foy. Un message d'erreur s'affiche mentionnant que la quantité disponible pour le transfert ne peut pas être inférieur à la quantité en inventaire. Pourtant, l'item est "in stock" donc disponible. Je souhaite transféré cet item et malgré le message d'erreur, j,ai été capable de le mettre dans le transfert de Ste-Foy vers Limoilou #3242. Je peux visualisé l'item dans le transfert d'inventaire, mais dès que j'essaie de l'ouvrir pour visualisé le transfert ou afin de réceptionné l'item, le produit a disparu et n'est plus dans le transfert d'inventaire.
Merci d,aller voir le transfert mentionné ci-haut.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. This issue is has already been fixed. Can you please make a new transfer order for this item ? And do let me know if you have any other question. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
I do not even believe you tested it. Nothing has changed and nothing is fixed.
<img width="945" alt="inventory transfert" src="https://user-images.githubusercontent.com/40500094/56134535-cb108c00-5f5c-11e9-9805-5c9be57d1f98.png">
<img width="941" alt="list transfert" src="https://user-images.githubusercontent.com/40500094/56134559-d5cb2100-5f5c-11e9-83be-c797e1dac32f.png">
<img width="944" alt="no item" src="https://user-images.githubusercontent.com/40500094/56134569-d9f73e80-5f5c-11e9-845e-e3f0b836fad0.png">

**Comment by usmanalikhan93** [comment]
I have already said please make a new transfer order for this item and ignore this one. Can you please do this ?

**Comment by JessicaSOS** [comment]
That's exactly what I did.

**Comment by usmanalikhan93** [comment]
ok let me check this.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. We have made this trade in as in stock in Limoilou store. You can verify at your end. Just ignore the transfer order as they were giving that error message. Do let me know if you have any question. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
fixed tnx
