### ISSUE TITLE
Transaction ID Number on Thermal Receipt | Ben Meinhart | iHelpU.Tech

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#773]
**Hello Sir,**

Customer has reported an improvement that once we try to process payments via Credit Card [Cayan or Other], the card number should be displayed on Thermal Receipt.

There is no tag for this in Thermal Receipt Template.

Please check the attached screenshot.

**Thanks and Regards,**
![Thermal Receipt](https://user-images.githubusercontent.com/48645240/56100599-47db4000-5f34-11e9-805f-a3218642cf71.png)

**Comment by fahadimran303** [comment]
Also once we export these Invoices, Can we have a way that the Card Number entered against device can also be exported?

**Comment by Uzair-RepairDesk** [comment]
What is the priority for this @fahadimran303 ?

**Comment by fahadimran303** [comment]
For Internal Use:
https://repairdesk.atlassian.net/browse/REP-1912

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303 
We have made this improvement LIVE. You can now enable the triggers under Module Configurations > Receipt to show transaction ID/Cheque # on service or thermal receipt. 
You can also enable it for Invoice. 

Please review at your end. Thanks
