### ISSUE TITLE
Create Invoice is missing time option

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#774]
Trying to create an invoice from an old date.
It does allow me to select date, but picking up the current computer time.

On the same time, If we click on add payment, this does have option to choose date and time both.

Can you please make time option avaialbe in Create Invoice Module ?

![ice_screenshot_20190415-171407](https://user-images.githubusercontent.com/34261339/56113949-c078e580-5fa2-11e9-963b-57f4a043f0e8.png)

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
can you create a task on JIRA for the team to look into it.

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1927

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I hope you are doing well. We have added time option on creating new invoice. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali
