### ISSUE TITLE
Drop Down is behind the header on activity log

### ISSUE THREAD

**Issue by Trevorshaw7** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#775]
<img width="349" alt="Screen Shot 2019-04-16 at 4 15 42 PM" src="https://user-images.githubusercontent.com/43588617/56247754-17de8a80-6063-11e9-8583-91a773a4fdaf.png">

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 
 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1851

**Comment by usmanalikhan93** [comment]
Hi @Trevorshaw7 

Your reported concern has been fixed and deployed on live server. Please verify at you end and do let us know if you have any question. 

Thanks
Usman Ali
