### ISSUE TITLE
Easy Viewing IMEI in ticket section

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#777]
We try to add imei number of all the phones which we fixed.
but sometime if we get busy, we dont fill imei info on pos .
It is really good that you have option to display the part if its been added against ticket or not.
but it will be more better, if we can see imei number against that ticket on main view.

Please consider adding this in upcoming updates.

**Comment by bharaaus** [comment]
![ice_screenshot_20190423-131919](https://user-images.githubusercontent.com/34261339/56551227-21b83e80-65cb-11e9-8a85-0880c9e9de2e.png)

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
Hope you are well. I will certainly discuss it with the team and consider to add it in the roadmap. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hey @bharaaus 
Good News, We have made this improvement LIVE. You can now view IMEI/Serial on Manage ticket page below the device. 
Please review at your end. Thanks

**Comment by bharaaus** [comment]
Amazing !
Thanks a lot.
This is really really helpful to track tickets with missing imei info.

You guys are amazing.
