### ISSUE TITLE
remove colour option on booking widget 

### ISSUE THREAD

**Issue by SajAbu** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#778]
is it possible to remove the option to choose a colour on the booking widget. it confuses customers. you can see the widget/link on our website. please message me directly for the weblink. thanks

**Comment by Uzair-RepairDesk** [comment]
**Hi @SajAbu** 

You can certainly disable the "choose color" option from "Appointment Calendar" widget. You can go to **Integrations > Appointment Calendar Widget > Configuration > Disable option 'Enable Color Pickup' under Advanced Settings**. 
Please check screenshot attached. 

You can review at your end. Thanks

![uzairshah   Bookrepair Config](https://user-images.githubusercontent.com/22955861/56632156-d73dcd00-6671-11e9-9981-ed82d1332fde.png)
