### ISSUE TITLE
the refurbishment cost has been doubled in sale report

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#779]
Looks like the refurbishment cost has been doubled for no reason. Can you please check. item #9989
<img width="939" alt="item #9989" src="https://user-images.githubusercontent.com/40500094/56597805-3bed1f00-65c1-11e9-9ca0-16663c998647.png">
<img width="943" alt="sale report item 9989" src="https://user-images.githubusercontent.com/40500094/56597902-6ccd5400-65c1-11e9-9b52-19d435de5ec3.png">

--
French :
On dirait que le coût de remise à neuf a été doublé sans raison. Pouvez-vous vérifier svp. item#9989

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 can you please check this?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked on my test account and it didn't replicate. I am trying to reproduce the use case. Once it will be done, I will update you. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/REP-1940

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
This has not been corrected for this item.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. It has been now fixed for this item too. Please verify at your end and do let us know if you have any question. 
![779_cost_issue](https://user-images.githubusercontent.com/39614480/57357913-94a9e380-718d-11e9-8140-7cd8fde7ae49.png)
