### ISSUE TITLE
Appointment booking app

### ISSUE THREAD

**Issue by Cumbr1at3ch** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#781]
Guys you have an issue - unresponsive on smartphones tablets. 
When customers trying to accept t&c they can’t go beyond this. It just hangs won’t go any further

**Comment by usmanalikhan93** [comment]
HI @Cumbr1at3ch 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @Cumbr1at3ch 

I have checked you concern on iPad tablet. It is working fine after checking terms and condition. Can you please try it again ?

**Comment by usmanalikhan93** [comment]
Hi again @Cumbr1at3ch  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
