### ISSUE TITLE
Customer message don't work

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#782]
All my employees no longer have access to sending pre-made emails to customers. Yet they all have permission in post privileges. Can you help me with that please. See Attachment.
<img width="941" alt="customer message" src="https://user-images.githubusercontent.com/40500094/56685243-79c07500-669f-11e9-99a9-f2c395b4c584.png">
![customer message in ticket](https://user-images.githubusercontent.com/40500094/56685248-7dec9280-669f-11e9-81bf-bb67e13c01db.png)
![acces denied](https://user-images.githubusercontent.com/40500094/56685255-82b14680-669f-11e9-8eaa-985a818ea959.png)

--
french:
Tous mes employé n'ont plus accès à envoyer des courriels pré-fait aux clients. Pourtant, ils ont tous l'autorisation dans les privilèges des postes. Pouvez-vous m'aider avec cela svp. Voir pièce jointe.

**Comment by JessicaSOS** [comment]
Impossible for my 5 stores to contact customers ... not very practical! Thank you to correct quickly.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked this in your account and it seems to be working fine. Please check screenshot
![Jessica_Github_782](https://user-images.githubusercontent.com/39614480/56877154-780efc80-6a65-11e9-9a6d-8b1d5eabc684.png)

**Comment by JessicaSOS** [comment]
Thank you for trying with the pre-made messages as mentioned with the big red arrow!

**Comment by usmanalikhan93** [comment]
Ok let me check this with pre made messages. @JessicaSOS

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked and yes it seems that there is some issue. I have forwarded this to development team. 

For internal Use: 
https://repairdesk.atlassian.net/browse/REP-1969

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can you please give a try again ? 
![Jessica_github_782_2](https://user-images.githubusercontent.com/39614480/56957686-6a3ea180-6b61-11e9-8dac-b5891b60940b.png)

**Comment by JessicaSOS** [comment]
fixed tnx !
