### ISSUE TITLE
Action button in the employee time report

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#783]
The action button no longer exists in the employee time report. I am therefore no longer able to add or modify erroneous data.
<img width="944" alt="action missing" src="https://user-images.githubusercontent.com/40500094/56768466-74852800-677c-11e9-9b56-566ca4d6c1f2.png">

--
French:
Le bouton "action" n'existe plus dans le rapport d'heure des employés. Je ne suis donc plus en mesure d'ajouter ou de modifier des données erronés.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked with Admin account and it does show "update" option in Employee Payroll Report. Can you please provide more info on this ? are you login through admin account or employee account ?

**Comment by JessicaSOS** [comment]
I am logging on my user who is admin. See Attachment. There is no cursor at the bottom to move to the right and there is no "action" button to change the current data.
<img width="943" alt="punch" src="https://user-images.githubusercontent.com/40500094/56916827-e2d12f80-6a87-11e9-98ee-33ac34678847.png">

--
french:
Je suis connecter sur mon usager qui est admin. Voir pièce jointe. Il n'y a pas de curseur dans le bas pour se déplacer vers la droite et il n'y a pas de bouton "action" pour modifier les données actuels.

**Comment by usmanalikhan93** [comment]
Ok let me check this @JessicaSOS

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked in your admin account and it does show the update option for it. See screenshot for reference
![Jessica_github_783](https://user-images.githubusercontent.com/39614480/56955158-0664aa80-6b5a-11e9-89d3-f154d89240b8.png)

**Comment by JessicaSOS** [comment]
I understand, but did you see my screenshot? It misses the last collonne and it is not a question of zoom. What's the problem?

**Comment by Uzair-RepairDesk** [comment]
@JessicaSOS 
can you highlight the browser you are using? Moreover, you can also update log from "Timesheet". Please check screenshot attached
![SOS Phone Limoilou  Employee TimeSheet](https://user-images.githubusercontent.com/22955861/57060459-f6bca180-6cd2-11e9-827e-e8f5706b45fc.png)

**Comment by JessicaSOS** [comment]
I use Google Chrome as always. I did not make any changes at this level.

The timesheet is accessible only by the employee. I can not edit or even view other timesheets than mine. So, since I am the owner and do not use time sheets, I do not see any data at this location.

I am looking to change the timesheets of my employees in the usual place, but it does not work. As many of my employees forget to register their hours, I have to make the changes quickly since I have to produce payroll on Monday, May 6th. The problem must be corrected before this date.

**Comment by usmanalikhan93** [comment]
That's totally strange @JessicaSOS as when I reviewed it shows update option there. Can you share the login details which you are using to access this and video on this email address usmanali@repairdesk.co. I will appreciate that.

**Comment by JessicaSOS** [comment]
I used the same software as you to record videos, but I only have the trial version. So I can not record any videos apart if I can be on your account.

The login information is the same as you have, those have my email address. I will send them privately to usmanali@repairdesk.co

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

The credentials you have sent to me on my email was an employee account and from that you can not update employee time report. But the fournier account has access to update because it's an admin account. 
These are my findings. Do guide me if I am missing something.

**Comment by usmanalikhan93** [comment]
As you can see in the picture this role is not a super user. If you want make these changes you need to be admin/super user. 
![Jessica_github_783_001](https://user-images.githubusercontent.com/39614480/57121403-bc193e80-6d90-11e9-8172-f8590fd62d0d.png)

Other workaround you can do is do make an access to these triggers in role "proprio" so you can view other employees times and can update from Employee Time sheet in clock in/out. 
![Jessica_github_738_002](https://user-images.githubusercontent.com/39614480/57121465-2b8f2e00-6d91-11e9-893c-2c87b2a3ce9e.png)

I hope this will help you.

**Comment by JessicaSOS** [comment]
Oh my God! It was only that! It works. Thank you!
