### ISSUE TITLE
Issue with tickets at check out 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#784]
We flag our notes at the end of the repair and when ever were about to check a costumer out at the pos. The notes pop up but the ticket closes and I have to close the notes and re-open the ticket once again for the notes to pop up and for the ticket to stay. This has happens every day.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I have checked your concern and it seems like everything is working fine. Can you please check this video and guide me if you are performing some other tasks. 

Video link: https://drive.google.com/file/d/146NJK65NeT96Kn0RtZX8nNQL8g3XLisR/view

**Comment by usmanalikhan93** [comment]
Hi again @Omar1892 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
