### ISSUE TITLE
Transaction ID On Payment Screen is Not Saving Unless You Click Save Button

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#785]
If you don't press the green icon it doesn't save transaction ID. 

![ecef8d5f-663c-4eb5-8dee-88a4c3675e59](https://user-images.githubusercontent.com/21986026/57208545-c2f0bd00-6fed-11e9-83bc-fba8d2aad735.jpeg)

Clicking on the green button and then clicking on the confirmation will be a hassle when the store gets busy.

It should be saved when we click on confirm or full payment.

**Comment by Uzair-RepairDesk** [comment]
Noted

**Comment by Uzair-RepairDesk** [comment]
We have split payment functionality available in RepairDesk where you can record payment with more than one payment method in one specific transaction. 
It's important to keep "green button" to log and confirm payment from one specific payment method after you enter "transaction id/reference or cheque no". 
If we remove it to directly record the reference with the payment might conflict the split payment functionality. Also if you select a different payment method after entering transaction reference, the system considers the transaction from the selected payment method and ignore the transaction reference.
