### ISSUE TITLE
Error in Employee Commissions Report

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#786]
Jimmy is an employee who works only in the Lévis store. He regularly repairs tablets from other stores, but works in Lévis. In order to know his commissions on the sold accessories and on the carried out repairs, I go in the report of commissions of employee. I select in the search filter the month of April 2019, the employee "Jimmy Fortin" and I tick all stores. Then I start the search. When I click on the total of the repairs to run the sub-menu corresponding to the detail of the total, what is displayed does not correspond to reality. Among other things, he displays bills for accessories from the Limoilou store that have no connection with Jimmy. Here is some example of what appears and should not:
FL-16012
FL-15927
FL-16237
FL-16135
FL-16103
FL-16095

What's the problem? I pay commissions to duplicate employees? Thanks for getting back to me.
<img width="935" alt="commission Jimmy" src="https://user-images.githubusercontent.com/40500094/57230975-933eb680-6fe7-11e9-9982-0426997ce18a.png">

--
French:
Jimmy est un employé qui travaille uniquement dans le magasin de Lévis. Il répare régulièrement des tablettes d'autres magasins, mais il travaille à Lévis. Afin de connaitre ses commissions sur les accessoires vendus et sur les réparations effectuées, je vais dans le rapport de commissions d'employé. Je sélectionne dans le filtre de recherche le mois d'avril 2019, l'employé "Jimmy Fortin" et je coche tous les magasins. Ensuite je lance la recherche. Lorsque je clique sur le total des réparations afin de faire dérouler le sous-menu correspondant au détail du total, ce qui s'affiche ne correspond pas à la réalité. Il m'affiche entre autres des factures d'accessoires du magasin de Limoilou qui n'ont aucun lien avec Jimmy. Voici quelque exemple de ce qui s'affiche et qui ne devrait pas:
FL-16012
FL-15927
FL-16237
FL-16135
FL-16103
FL-16095

Quel est le problème? Je paie des commissions aux employés en double? Merci de me revenir.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 can you please review this? Thanks

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
For internal Use: 
https://repairdesk.atlassian.net/browse/RB-48

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. We have identified the case in which this issue is coming. Now it's been resolved. But for old invoices, we have to manually make them correct. Can you help to identify those so we can do the needful ? 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
I only noted the one listed previously.

**Comment by usmanalikhan93** [comment]
Ok @JessicaSOS
