### ISSUE TITLE
Traduction in customer facing display widget

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#787]
Hello,
I would like to change the translation of the widget "customer facing display" since since the update of the widget, all is displayed in English. When I go to the widget "language manager", all is currently translated. I do not understand why these are the words in English that appears. Can you inform me about please.
Thank you and good day

--
French:
Bonjour,
J'aimerais modifier la traduction du widget "customer facing display" puisque depuis la mise à jour du widget, tous s'affiche en anglais. Lorsque je vais dans le widget "language manager", tous est actuellement traduit. Je ne comprend pas pourquoi ce sont les mots en Anglais qui s'affiche. Pouvez-vous me renseigner à se sujet svp.
Merci et bonne journée

**Comment by Repair-Desk** [comment]
Sure thing Jessica! Let us take a look to see if we're getting the same issue as you and we'll circle back to you.

**Comment by usmanalikhan93** [comment]
For Internal Use: 
https://repairdesk.atlassian.net/browse/RB-45

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

For now you can change these through setting section in language translator. See screenshot for reference. 
Once these will be transferred to Customer facing display, I will let you know. 

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
Sorry. I am attaching it again. Hopefully it will be transferred to customer facing display in next week. I will let you know. 
![Jessica_Github_787](https://user-images.githubusercontent.com/39614480/57428904-c3829100-7243-11e9-8f7d-add3882b0fc4.png)

**Comment by JessicaSOS** [comment]
He was actually with the "setting". It's settled, thanks!
