### ISSUE TITLE
Display serialize inventory info under product tab

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#788]
we would like to change the listing of the device inventory so that the serials available are listed under product info tab rather stock tab

![Serialized Inventory](https://user-images.githubusercontent.com/21986026/57284011-ca859400-70c9-11e9-9685-ffd9bde3938a.jpg)

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk the reason to keep it under "Stock" tab is that "serials count is directly associated with On Hand stock". Admin/users can easily visualize the on hand stock and create serials/count or manage serials accordingly.

**Comment by Uzair-RepairDesk** [comment]
We have made this improvement LIVE
