### ISSUE TITLE
Automatically Calculate end of day cash payout amount by bill denomination 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#789]
At the end of the day, I always take out all bills larger than $10 and leave the rest for change for the next day. This means I have to manually total up the total and put it in the payout withdrawal section each day. It would be nice to be able to set a flag ( right there in that section, not in the settings) that would allow me to automatically select bills that are withdrawn and total it up for me. Really all it would do is total the 1s, 5s and 10s and subtract that from the total and set that amount as the payout withdrawal. It's always accurate since it's calculated from what was actually counted at the end of the day, so there's room for error. I can also confirm this amount before hitting "End Shift"

**Comment by Uzair-RepairDesk** [comment]
We have catered this request in our updated cash register module
