### ISSUE TITLE
Option to Give Access to Integrations | Modesto | DrPhone Fix

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#790]
Hello Sir,

Customer is looking to give access to its Franchise Owner the permission to play around with the Integrations.

For all the integrations which are set store wise, they are looking for a permission in which they can grant access to Store Owners.

Thanks,

**Comment by Uzair-RepairDesk** [comment]
@fahadimran303 

We already updated it under "Employee Roles Permissions". You can allow or restrict specific employee role to access "Integrations". Please check screenshot attached

![uzairshah   Roles Permission](https://user-images.githubusercontent.com/22955861/57431370-05afd080-724c-11e9-89d9-3784fc90b487.png)
