### ISSUE TITLE
INVENTORY 

### ISSUE THREAD

**Issue by Cumbr1at3ch** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#791]
3 items sold over last few weeks 
item numbers 
Samj320case inv 4050
i4sb16 inv 4078
iPhone SE Space Grey 16GB  inv 4066

**Comment by usmanalikhan93** [comment]
Hi @Cumbr1at3ch 

Can you please provide more info on this ?

**Comment by Cumbr1at3ch** [comment]
Hi Usman
It would appear that the majority of non-stock items the stock level isn't been updated to reflect a sale of this.
Even though the item has been sold - stock level is remaining on here.
Having said that, There has been over these last few months whereby its stock which isn't been updated when the item has been sold.
I have found many items where the stock is showing when in actual fact physical stock isn't there.
As you can imagine this is having many repercussions upon the business, When customers are asking can you do this today, check stock on RD to then find its not there. I need to have confidence in this inventory management system as I rely on stock levels been correct and my daily check of low stock report reflects what I have on my shelves. See your colleagues response to this below.
Just a quick one - my monthly subscription has increased over the last couple of months by $10 was there a price rise I'm not aware of ?
Sean
________________________________


fyi
Hello Sean!

Thank you for bringing this to our attention! It looks like there's a bug that just popped up [bug] .

I'm going to reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information on that! [smiley]



--


[Robinson]

Robinson from RepairDesk


Get Outlook for iOS<https://aka.ms/o0ukef>

**Comment by usmanalikhan93** [comment]
Hi Sean @Cumbr1at3ch 

Let us check this on our end. I will revert back to you once I get more info on this. 

Thanks


For internal use: 
https://repairdesk.atlassian.net/browse/RB-53

**Comment by usmanalikhan93** [comment]
Hi Sean @Cumbr1at3ch 

I hope you are doing. I hope Danish has guided you and all is settled down. If you have any question do let me know. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi Sean @Cumbr1at3ch 

since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali
