### ISSUE TITLE
Notification in appointement calendar

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#792]
Hello,
A client told us that he had not received confirmation of his appointment. My employee believed the client was wrong. She did a test with her cell number by creating an appointment via the widget. She told me that she did not receive any confirmation. I went to see all the notification settings and nothing was changed, the sms are activated for the creation of a new appointment. (see picture)

The sms service only activated and works well in repair tickets. The settings in the "hunt" widget are also correctly configured.

I did a test with my personal cell number and it does not work. I advised all employees some time ago to no longer confirm appointments since an email was automatically sent. Can you tell me what is the problem please?
<img width="947" alt="sms notification" src="https://user-images.githubusercontent.com/40500094/57535047-69e79880-730f-11e9-9929-68535abeb05b.png">
<img width="944" alt="Lead L-L-20917" src="https://user-images.githubusercontent.com/40500094/57535053-6f44e300-730f-11e9-968e-d870fb864580.png">

--
French:
Bonjour,
Un client nous a mentionné qu'il n'avais pas reçu de confirmation de son rendez-vous. Mon employé croyait que le client était dans l'erreur. Elle a fait un test avec son numéro de cellulaire en se créant un rendez-vous via le widget. Elle m'a mentionné n'avoir reçu aucune confirmation. Je suis aller voir tous les réglages de notification et rien n'a été modifier, les sms sont bien activé pour la création d'un nouveau rendez-vous. (voir image)

Le service sms que activé et fonctionne bien dans les billets de réparation. Les réglages dans le widget "appointement" sont également correctement configurer.

J'ai fait un test avec mon numéro de cellulaire personnel et sa ne fonctionne pas. J'ai aviser tous les employés il y a quelque temps de ne plus effectuer de confirmation de rendez-vous puisqu'un courriel s'envoyait automatiquement. Pouvez-vous me dire quel est le problème svp?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked this on my test account by enabling clickatell integration. It is working fine. Can you please try once more ? Then do let me know if you still face issue.

**Comment by JessicaSOS** [comment]
is not working
<img width="932" alt="appointement on our website" src="https://user-images.githubusercontent.com/40500094/57626188-69474000-7563-11e9-950d-a9d3fea159d6.png">

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Can I test this with my number on your Appointment Calendar ? Just need to verify this.

**Comment by JessicaSOS** [comment]
Of course! You only have to do the lead later or cancel it.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. I was testing this but I am unable to login in your clickatell account. Can you please share your updated clickatell credentials on this email usmanali@repairdesk.co. So I can check this further. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have checked this with updated credentials also I have changed the password of clickatell integration with updated one on your RD account. It sent the message and I have checked log in clickatell reporting. 
I have created lead L-L-20982 in Limoilou store. Please check screenshot for reference. 
![Github_792_2](https://user-images.githubusercontent.com/39614480/58535125-8ab45700-8206-11e9-83cf-45a2d3559fa5.png)
![Github_792_1](https://user-images.githubusercontent.com/39614480/58535126-8b4ced80-8206-11e9-8cde-f546c310ef1e.png)

**Comment by JessicaSOS** [comment]
I did a test on the shop of Sainte-Foy and the shop of Limoilou and I did not receive any SMS on my phone. Did you receive the SMS on your side or did you only have the confirmation on the clickatell website?

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I did not receive the SMS on my phone. I have checked this with developer and he said if you see log on clickatell website it means RD is sending SMS but clickatell is not. 
Please contact to clickatell support for this issue. It's not a RD end issue. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
Ok, thank you for this clarification, I will look with Clickatell what is the problem.
