### ISSUE TITLE
Monthly Sales and Sales Tax HUGE ISSUE! 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#793]
Hello, 

Monthly Reports; The monthly reports are always off by penis to +$100 dollars off. The report from the Over View are always different from the Reports from Sales By Item Type and Location Method Payment. This always happens. My bookkeeper uses this 3 reports to verify that all amounts are matching and correct to what it was collected. This issues has been on going since we first started and the reps have been notify of this issue and they tell me that they will get back to me or fix it and they nothing has happened. The pictures below shows the reports that we use to verify the amounts. If you guys can look at the report from April and add up the amounts are incorrect. 04/01/2019 to - 04/30/2019 are incorrect the amounts.

**Comment by Omar1892** [comment]
![Screen Shot 2019-05-10 at 4 39 33 PM](https://user-images.githubusercontent.com/47898011/57561815-f2cbf780-7342-11e9-8bf3-bcfb57cace93.png)
![Screen Shot 2019-05-10 at 4 39 27 PM](https://user-images.githubusercontent.com/47898011/57561816-f3648e00-7342-11e9-96db-ee45d8db74a0.png)
![Screen Shot 2019-05-10 at 4 39 20 PM](https://user-images.githubusercontent.com/47898011/57561817-f3648e00-7342-11e9-8e99-e66f6b353bb9.png)

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Can you please share you login details with Fahad ? So I can look this into your account in detail.

**Comment by Omar1892** [comment]
Yes, Ill have him call me tomorrow. I was able to take the call today.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. I believe you have a call with Fahad and he has guided you. I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali
