### ISSUE TITLE
Adding Customer phone number picking up PAKISTAN as default country

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#794]
It used to be very easy to add customer number.
buy now it gives error everytime.
We have to select Australia manually or enter the number with +61 to add the mobile number.
Its time consuming . 
Please revert back the setting as it was before.

Please check video.

[ScreenRecorderProject2.zip](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/3168540/ScreenRecorderProject2.zip)

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I hope you are doing well. Sorry for the inconvenience. I have reported to dev team and hopefully it will be fixed soon and ready to go live in 2 - 3 days.

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-58

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if  you have any question. 

Thanks 
Usman Ali
