### ISSUE TITLE
"repair tracking" page (follow up)

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#795]
Hello,
The "repair tracking" page on our website no longer works. When we go, we are able to access the selection of the store, but after this step, the page is only downloaded, without ever being available. I put an image as an attachment. You can try it yourself by following this link: https://sosphone.ca/reparation-de-cellulaire/verifier-le-statut-de-votre-reparation/
<img width="938" alt="follow up on website" src="https://user-images.githubusercontent.com/40500094/57656168-a7655380-75a5-11e9-921c-ab812e8126de.png">

----
French :

Bonjour,
La page "suivi de réparation" sur notre site internet ne fonctionne plus. Lorsque nous y allons, nous sommes capable d'acceder à la sélectione de la boutique, mais après cette étape, la page ne fait que se télécharger, sans jamais être disponible. Je vous ai mis une image en pièce jointe. Vous pouvez l'essayer vous même en suivant ce lien: https://sosphone.ca/reparation-de-cellulaire/verifier-le-statut-de-votre-reparation/

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-59

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed and I have verified through given link. Please verify at your end and do let us know if  you have any question. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
fixed tnx
