### ISSUE TITLE
Part Auto Selection 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#796]
The system is auto selection the same part multiple times for the same repair. Picture below is shows issue were having. 
![Screen Shot 2019-05-13 at 2 55 09 PM](https://user-images.githubusercontent.com/47898011/57657223-81cd4f80-758f-11e9-893b-121e6c199c9e.png)

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Thank you for bringing this to our attention. It's already been fixed and is on beta server. It will be go live today or hopefully tomorrow. I will let you know once it will be pushed on live server. 

Thanks 
Usman Ali

For internal use: 
https://repairdesk.atlassian.net/browse/RB-46

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. Your reported issue has been fixed and available on live server. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali.
