### ISSUE TITLE
US phone number format messed up

### ISSUE THREAD

**Issue by phonefixdfw** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#798]
wrong flag, and no longer pre-selecting the +1 like it did before
video https://drive.google.com/file/d/1hdXRBvQ-KylLHXw4Edqzj2oaWHfGjyar/view

**Comment by usmanalikhan93** [comment]
Hey! @phonefixdfw 
 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if  you have any question. 

Thanks 
Usman Ali
