### ISSUE TITLE
Option to merge existing customer data at check in

### ISSUE THREAD

**Issue by rlltd** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#799]
Hello.

When entering customer data which turns out to be a duplicate, we only get an option to "choose existing record".

This might not be suitable as their phone number or email may have changed, or I may have taken other new information like their address and license number when trading in a phone.

An option to merge new info to the existing customer record (or create a new record) would be easier than selecting the existing record, then having to go and edit to and add the new information for a second time.

Sometimes people use other phone numbers when booking in phones, they could provide their mothers phone number for example. Then later in the year the mother comes in and creats her own account - but it conflicts with the childs account.

**Comment by Uzair-RepairDesk** [comment]
Hey @rlltd 

Thank you for your post. Currently, there are 2 following primary keys in the customer record:-
1: Email Address
2: Mobile Number 

If any of the above fields match with an existing record, the system notifies so admin/users can select the existing record. Admin/users can also edit existing customer information if it's updated. 

Regarding merging details of 2 customers, currently its not available in RepairDesk. Can you please explain how you exactly want to merge the details? E.g. if 2 customers have a separate account in RepairDesk with the different Name, email address, and mobile numbers, what will be the preference to update the details while merging the 2 customer details?

Looking forward to hearing from you

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
