### ISSUE TITLE
Missing transaction again

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#800]
Post on the 5th of September 2018 and we still have this problem!

transactions are disappearing again. See picture. We go from 10 to 9 without any reason ...
![#2347](https://user-images.githubusercontent.com/40500094/57869713-9e59c980-77d3-11e9-94cb-b01cb81011c7.jpg)
yesterday:
<img width="946" alt="#9148 item" src="https://user-images.githubusercontent.com/40500094/57869856-eaa50980-77d3-11e9-911b-81eee22558ee.png">

--
French :
Reporter le 5 sepmtebre 2018 et nous avons encore ce problème !

des transactions disparaissent encore. Voir image. Nous passons de 10 a 9 sans aucune raison...

**Comment by usmanalikhan93** [comment]
HI @JessicaSOS 

Sure let me review this. I will revert back to you once I have more info on this.
