### ISSUE TITLE
Mail problem

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#801]
Hello,
emails @ me.com does not work. Customers tell us all that they do not receive our messages. Also, in the ticket history, we see the email status as "bounced" or "deffered".
<img width="941" alt="@me 2" src="https://user-images.githubusercontent.com/40500094/57955072-d429ab80-78c2-11e9-9cb6-2d7dd31b4b72.png">
<img width="944" alt="@me" src="https://user-images.githubusercontent.com/40500094/57955076-d7bd3280-78c2-11e9-91d4-1f37dc1e3f54.png">

--
french:
bonjour,
les courriels @me.com ne fonctionne pas. Les clients nous mentionnent tous qu'ils ne reçoivent pas nos messages. Deplus, dans l'historique du billet, nous voyons le statut du courriel comme "bounced" ou "deffered".

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Let me check with developer why it is bounced emails on this domain. I will revert back to you with more information. 

Thanks

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-98

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. I have discussed this with developer and he said these our i Cloud domains. Cannot send emails on these domains. 
Can you confirm me is it working in the past ? Or can you can give me any ticket so I can show this to developer. I will appreciate your help. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
The examples were in the photos attached. Here they are:
SOS Phone St-Roch: Ticket # R-1847
SOS Phone Sainte-Foy: Ticket # F-5103

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have reviewed these in detail and found out that email used in these tickets are not valid. Please check these again or contact to these person for valid email address. 

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
Why do you say these addresses are invalid? We checked with one of these two clients, several times the email address with him. The customer really wanted to receive our emails and invoice by email. He told us that he never received it, and it looks like the email is not sending properly. This does not happen regularly, but this task has not been evaluated correctly.

--
french:
Pourquoi dites-vous que ces adresses ne sont pas valide? Nous avons vérifier avec un de ces deux clients, plusieurs fois l'adresse courriel avec lui. Le client souhaitait vraiment recevoir nos courriels et sa facture par courriel. Il nous mentionnait qu'il ne l'a jamais reçu, et on dirait que le courriel ne s'envoie pas correctement. Cela n'arrive pas régulièrement, mais cette tâche n'a pas été évalué correctement.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

This issue has been fixed. iCloud was blocking our ip address that's why this issue happened. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali
