### ISSUE TITLE
Purchase orders: Remove Tax being the default.

### ISSUE THREAD

**Issue by Mariaaredondo** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#803]
Most parts that a repair shop purchases are through wholesalers. Therefore we do no pay tax. When creating a purchase order we have to manually change each and every line to no tax. sometimes we are creating purchase orders of over 100 items for new stores. 

Fix: Please make the default to be "no tax"

**Comment by usmanalikhan93** [comment]
Hi @Mariaaredondo 

I hope you are doing well. You can make it as tax exempt. When you select items in purchase order, there tax class will be as tax exempt (no tax). Go to Settings > Module Configuration > Purchase Order > Select "Default Tax class for Purchase orders" as Tax Exempt. 
![Drphonefix_803](https://user-images.githubusercontent.com/39614480/58149511-bc647580-7c7c-11e9-9e6c-b98e8f798ca7.png)

**Comment by phonefixdfw** [comment]
I have this turned on in po settings and it only works randomly. Some lines will get tax, some won't. Very inconsistent

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

Let me check and I will revert back to you if I need more info.

**Comment by Mariaaredondo** [comment]
Thank you! Somehow I missed the release of this improvement.

*Maria Arredondo*
*Director of Operations*

*Office:* 754-200-8917

*Mobile:* 305-600-9204

*Email:* Maria@drphonefixfrancise.com

*LinkedIn*: mariacarredondo <https://www.linkedin.com/in/mariacarredondo/>

**Comment by usmanalikhan93** [comment]
Hi @phonefixdfw 

I have checked your concern but it seems it's working fine may be there was some glitch. Can you please try it again ? Do let me know if you find any problem. 

Thanks
Usman Ali.
