### ISSUE TITLE
Inventory Adjustment from POS - Never Worked for me

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#804]
Inventory Adjustment from POS
![RD Attached](https://user-images.githubusercontent.com/34261339/58140389-64307200-7c82-11e9-865f-8ab4ef9f22f1.png)

It was released on Mid January. 
According to this update, if item is not in stock, We should be able to update stock from POS window popup rather than going to a different tab to increase qty.

But when i click on it, instead of opening pop-up, it opens a new tab.
Have a look at the video.

[POS item.zip](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/3205121/POS.item.zip)

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I have reviewed this video. From where you are trying to add adjustment, it will redirect to you item master page. When you go to Accessories tab on POS and you have inventory item which is in stock = 0, 
you will click on that item and it will show you pop and you can add adjustment from there on POS page. 
Please check this video for better understanding
Video link: https://www.screencast.com/t/kpl8y85rOa

Thanks 
Usman Ali

**Comment by bharaaus** [comment]
Thank you for explaining the process.
But Wouldn't be nice if pop up window comes on the position where i suggest in my video ?

Can you consider adding this feature over there?

**Comment by usmanalikhan93** [comment]
Thanks for the suggestion @bharaaus , I will discuss this with @Uzair-RepairDesk and will revert back to you.

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk can you check this whether we can add this functionality or not ?

**Comment by Uzair-RepairDesk** [comment]
Hi @bharaaus  
Thanks for highlighting the above Issue, I am discussing it with the development team to check it's possibility. I will update you once I get feedback.

**Comment by Uzair-RepairDesk** [comment]
Hi @bharaaus 
I have checked with the development team, unfortunately, the requested option is not possible As the system doesn't allow such functionality.
