### ISSUE TITLE
Tickets Update 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#805]
Hello, 

when ever I try to look up an old ticket in the ticket search box it takes me to the ticket section but it won't look up the ticket that Im looking for. I have to enter the ticket number in the new search box that you guys have created in the ticket section. I don't know if this is due to the new update you guys have done to the ticket section. 
![Screen Shot 2019-05-31 at 11 52 13 AM](https://user-images.githubusercontent.com/47898011/58727975-a3557600-839a-11e9-8d95-ff5319171793.png)
![Screen Shot 2019-05-31 at 11 52 02 AM](https://user-images.githubusercontent.com/47898011/58727976-a3557600-839a-11e9-94b4-001fed8f0ba2.png)

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-140

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Your reported issue has been fixed and pushed on live server. Please verify this at your end and do let us know if you have any question. 

Thanks 
Usman Ali

**Comment by Omar1892** [comment]
Its working fine now. Thank you!
