### ISSUE TITLE
Serialized Merchandize 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#806]
I have a suggestion, in the inventory items when ever an item is instock and serialized it comes up all the way at the bottom or on the next page. And this is do because the merchandise that was already sold shows up on the first lines. Why not do it the other way around. The merchandise that sold last or sold already should be shown last and what ever is in stock shows up fist. That way we don't have to scrawl all the way down the page or go to the next page.

**Comment by Uzair-RepairDesk** [comment]
Hey @Omar1892 

Thank you for your post. We certainly had the same functionality that On Hand serials use to come first in the list and sold status is last.

It looks like there's a bug that just popped up 🐛. 

I'm gonna reach out to our Engineers to get this taken care of.

@usmanalikhan93 I have asked Humza to create a task for this to get it done. Can you please track this. Thanks.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-141

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Your reported concern has been fixed. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali

**Comment by Omar1892** [comment]
Thank you it works great now.
