### ISSUE TITLE
Error refund!!!??

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#809]
When refunding any invoice containing more than one item and specifying any item for return, delete another item, just by ipad app

**Comment by usmanalikhan93** [comment]
Hey @hitman1986 
 
Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Your reported issue has been fixed. Please download our latest release in order to get the fixes. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali

**Comment by hitman1986** [comment]
Thank you, its working
