### ISSUE TITLE
Invoice and Receipt Pictures 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#813]
The system gives you the option to upload picture in the invoice or receipt. When I try to upload two different pictures in the invoice the picture in the receipt sections changes to what I just uploaded. I would like to upload two different pictures but it doesn't seem to work.

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 
Can you please elaborate it in detail? Are you uploading the "Logo" image for invoice and receipt that changes? 
Screenshots will be appreciated from your side. Thanks

**Comment by Omar1892** [comment]
yes, so for example in the Invoice I would like it to have the Business logo. And on the thermal receipt I want it to have another logo that says Limited Life Time Warranty.

**Comment by Uzair-RepairDesk** [comment]
Hey @Omar1892 
We certainly allow uploading different logo files for invoice and receipt. 
@usmanalikhan93 
Can you check if its work with the scenario shared in the description?

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-204

**Comment by Omar1892** [comment]
I was trying to do it couple of times in different ways. But it seems that if I change one the other logo will get replaced by what I had change.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Your reported issue has been fixed. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali
