### ISSUE TITLE
Check Out Reminder 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#814]
A pop up screen should appear once were checking a costumer out reminding the employee to offer the costumer a tempered glass or a case. This could increase sales in stores.

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 

I really appreciate that you took the time to share your idea.

I can certainly see how the suggested improvements would be useful. We certainly have the plan to add "Suggestive Sales Alert" functionality in RepairDesk that will allow marking items to populate in sales alert and when admin/users make a sale, they will get a pop-up window with the selected items list to upsell. 

However, with a small team and a big roadmap, we have to pick new features based on the value they’ll add to the most users possible and our current focus is the stability of the platform. We will plan it in the next quarter or so. I hope that if there’s anything else I can do for you, you won’t hesitate to let me know. Thanks

Regards,
Uzair

**Comment by Omar1892** [comment]
Sounds good. Hopefully it can be added soon, it will make a difference in sales.
