### ISSUE TITLE
Cash basis and Sales Reports

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#815]
I would like to know if you when will their be in improvements in the Sales Reports and an option to change to Cash basis instead of doing Accrual basis? Its really important for the numbers to match since they never do, do to issues on the reports. And cash basis could let us do deposits. We need updates soon for this thins since we have had been requesting this issues for the past 1 year 1/2

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 

Your same request is already logged here #732 
I updated it with the following and waiting for your response:-

We have introduced a new report name with "Profit & Loss Reports" that is solely on a cash basis. Currently, we pushed it on LIVE for limited users to BETA test it.
If you want to review it, can you please share your account credentials with me at uzair@repairdesk.co s I can make it enable to your account as well. Thanks

**By the way can you also please highlight the improvements you are looking for in existing sales report?**

Looking forward to hearing from you

Regards,
Uzair

**Comment by Omar1892** [comment]
Ill just wait till you guys have it ready. Thank you for the update!
