### ISSUE TITLE
Need an option when adding inventory to be store specific or universally available at all stores

### ISSUE THREAD

**Issue by mobilebarn** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#816]
hey guys is there a way to keep inventory store specific instead of universal. i.e store 1 adds a brand of cable to theyre inventory but store 2 does not stock this, is there a way to keep that seperate rather than being availble in all stores?

**Comment by Uzair-RepairDesk** [comment]
Hi @mobilebarn 
Yes, you can certainly do that. 
If you want to add a new product/item and you don't want to create it on another store, you can go to Store Settings > General Settings and mark the trigger "Auto create inventory & service items on other stores" to "NO". 
Please check screenshot attached.
Hope it helps. Thanks

![uzairshah   Settings Stores](https://user-images.githubusercontent.com/22955861/59579192-1f62f400-90e5-11e9-96a0-5c36a43c6424.png)
