### ISSUE TITLE
Ticket Filter has become so annoying and bug in ticket section

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#817]
the new ticket filter is so annoying and its not user-friendly at all.
We mainly search by filtering Device | IMEI |  Task . 
But these field we have to select every time when we want to search something.

![ice_screenshot_20190615-103503](https://user-images.githubusercontent.com/34261339/59544904-11349c80-8f5a-11e9-81f7-9d375d91ad93.png)

and bug in ticket section please see attached video.

[ice_video_20190615-103818.zip](https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/files/3292583/ice_video_20190615-103818.zip)

**Comment by usmanalikhan93** [comment]
Hi Bharat @bharaaus 

Thank you for highlighting these issues. Let me forward this to development team and I will update you once issue will be fix. 

Thanks 
Usman Ali.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-182

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

**We mainly search by filtering Device | IMEI | Task .
But these field we have to select every time when we want to search something.**
We have improved it like our reports filter section. So for we can't display all things in filter search. You have to apply criteria for search.

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
