### ISSUE TITLE
Error in search in manage ticket

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#819]
When search in manage ticket by status ticket You will be able to modify the status of any ticket and then return you to the first page of tickets!!??

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Can you provide more info on this ?

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-182

**Comment by hitman1986** [comment]
When enter in atlassian show me error account

**Comment by hitman1986** [comment]
![Screenshot_٢٠١٩٠٦١٧-١١١٢٠٢_Samsung Internet](https://user-images.githubusercontent.com/44485797/59588743-ffd1c880-90f0-11e9-8b68-a5abc2e96121.jpg)

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

It for our internal use. I have identified the issue. I will try to resolve this ASAP. I will update you once it is fixed. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by hitman1986** [comment]
Thank you is sloved
