### ISSUE TITLE
Feature Request: Add phone type to ticket search

### ISSUE THREAD

**Issue by fetchwireless** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#82]
If we need to look up a ticket by the phone or ticket item it is very tedious.  There should be a search option for searching by device or repair ticket item.

**Comment by Repair-Desk** [comment]
@fetchwireless We will be look into it during mid of January.

**Comment by Uzair-RepairDesk** [comment]
We added improvement a few months back that allows you to search ticket from the header as well as you can search ticket by Ticket id, Phone or Mobile number as well from Manage ticket search filters.
