### ISSUE TITLE
Serialized Merchandize 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#820]
Hello, a suggestion. The way the serialized merchandize was under stock made more since than having it on the product info. The reason why is because when ever inventory count is done or if you want to check the inventory items have to be checked. Both the inventory on hand and serialized merchandise have to be checked just by staying on stock tab. Now we have to go to Product info and back to Stock to verified if what we have on hand matches with what we have with serialized.

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 
Thank you for sharing your concern. I agree with you. I have asked the team to replicate the same section under "Stock" tab as well so you can have less confusion about this. 
We will keep it at both 'Product Info' and 'Stock' tab.

I will update you once it's done and we make the changes LIVE. Thanks

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Your reported concern has been added. Now you can also Add or See serialized inventory in "Stock" tab. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali

**Comment by Omar1892** [comment]
Thank you, yes its on both tabs now.
