### ISSUE TITLE
Error in expense

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#821]
When make any expense from wep app and in end shift i find that the total money is incorrect and the expenses were not deducted

**Comment by usmanalikhan93** [comment]
Hey @hitman1986 , 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I have checked this on my end and it looks it's working fine. Can you provide more info on this ? It will be really appreciate if you attach screenshots or a video so it will be helpful for me to replicate this issue. 
Waiting for your response. 

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Just wanted to know that are you still facing this issue ?

**Comment by hitman1986** [comment]
Yes im tell to mr danish about this issue and im sended video to explaind about this issue

**Comment by usmanalikhan93** [comment]
@hitman1986  ok let me discuss this with Danish Hassan.

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I have checked your video and discussed this with iPad team. Yes it seems like there is some issue, data is not fetching on iPad. I have reported this and it will be fixed soon. I will update you once this issue pushed on our live server. 

Thanks 
Usman Ali

**Comment by hitman1986** [comment]
I hope add this expense tab in ipad app.

**Comment by hitman1986** [comment]
It sloved thank you and thank to mr danish
