### ISSUE TITLE
Issue in rma

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#822]
When I allow the employee to set up RMA he shows his cost price with I did not let him see it in settings

**Comment by usmanalikhan93** [comment]
Hey @hitman1986 , 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-194

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

From where you are setting to hide RMA cost price to employees ?

**Comment by hitman1986** [comment]
From employee role -inventory- uncheck cost price

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

We are adding trigger in RMA settings of employee role permission on which if you apply this trigger then employe can't see the cost price, tax and total. I will update you once it will be push on live. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope you are doing well. We have added trigger of "Show price, tax and total" in RMA. If you uncheck this trigger then your employee belongs to that role can't see the cost price, tax and total in RMA. We have verified on live. Please verified at your end and do let us know if you have any question. 

Settings > Employees > Manage Roles Permission > RMA > Show Price, Tax and Total
![Github_hitman](https://user-images.githubusercontent.com/39614480/59917235-dd1a1980-943a-11e9-8e0f-976d2da13936.png)


Thanks 
Usman Ali

**Comment by hitman1986** [comment]
Thank youuuuuu, great.
