### ISSUE TITLE
No Tax 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#823]
Hello, 

Hello, Im having issues when I choose not to charge taxes at check out it won't accept that option. I have checked my stetting but they seem to be they way they have always been.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Can you please tell us are you referring to iPad or Web app ?

**Comment by Omar1892** [comment]
Its on my computer

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I have checked your concern and it seems to be working fine. Can you please provide screenshots or a short video so we can check this at our end with those steps. Also please provide your credentials via email at danish@repairedesk.co

**Comment by Omar1892** [comment]
It seems to be working fine now. I wasn't deducting the taxes when I was choosing not to. Thanks.
