### ISSUE TITLE
Tranaction Logs are not showing the detail of Ticket invoice payments

### ISSUE THREAD

**Issue by bharaaus** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#824]
have a look at 2 pics below.
its from today's tranactions.

Some inovices info is missing in transaction logs.

![ice_screenshot_20190624-145436](https://user-images.githubusercontent.com/34261339/59992777-c240e280-9690-11e9-8f18-efd17fe1ec9e.png)

![ice_screenshot_20190624-145804](https://user-images.githubusercontent.com/34261339/59992783-cbca4a80-9690-11e9-9d09-dd26030eb0fb.png)

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

For internal use:
https://repairdesk.atlassian.net/browse/RB-216

**Comment by bharaaus** [comment]
Just doing End Shift now,
and there is lot of discrepancy due to missing invoice.

Please fix this urgently .

**Comment by usmanalikhan93** [comment]
Hi @bharaaus 

We have added these three invoices in register Robin. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali

**Comment by bharaaus** [comment]
Yes ! Fixed. 
Thanks
