### ISSUE TITLE
Sales and Tax Reports Don't Add Up 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#825]
Hello, 

We've been having issues with this reports for the past year or since we started using the system. I've been told that fixes are on their way but nothing has happened. The screen shots show the sales from April 2019 and Sales from May 2019 are starting to not match with the reports. The only report that acuity makes sense it the "Transaction Log". But we need the reports in the front of the page since we need to brake down our sales and see what is been sold through out the month accurately. We need huge fixes to the reports please. This has been going for too long already. We have also spoken to the reps for help but we only get answers that fixes are on their way but as mention before nothing has been done. 

![Screen Shot 2019-06-25 at 2 19 24 PM](https://user-images.githubusercontent.com/47898011/60134786-22995800-9755-11e9-99c3-c66fc15cf642.png)

![Screen Shot 2019-06-25 at 2 19 34 PM](https://user-images.githubusercontent.com/47898011/60134790-25944880-9755-11e9-94be-4d7711f4a5d1.png)

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. Our support ninja Fahad will contact you on this query and will guide you accordingly. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I believe our support guy Fahad has explained you about the scenarios and I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up. 

Thanks 
Usman Ali
