### ISSUE TITLE
Check Out Button Frozen

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#826]
When ever we try to check out for a sale or when we finish a repair the check out is the only button thats frozen and it won't let us check out.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I have checked your concern but it's working fine on our end. Can you please attach any screenshot or steps to reproduce this issue so I can look into it ?

**Comment by Omar1892** [comment]
Its doing it on the my HP 15 computer. It freezes and it won't let us check out. We have deleted all cookies, history and cache from the computer. But it does it randomly.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Definitely strange, Let me check again today while testing, If I will face this issue I will get back to you.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I have checked your concern but I am unable to replicate this on my end. It seems it's working fine. Are you still facing this issue ?

**Comment by usmanalikhan93** [comment]
Hi again @Omar1892 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali
