### ISSUE TITLE
PassCode Field limited to 20 characters.

### ISSUE THREAD

**Issue by ben-ihelputech** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#827]
The password field on the POS window and in the 'Pre / Post Device Condition' tab is limited to 20 characters. This poses a problem when a customer brings a device with a password that is more than 20 characters long or is unsure of one single password.

**Comment by Uzair-RepairDesk** [comment]
Hey @ben-ihelputech 

Thank you for your suggestion. I will discuss it with the team about the feasibility of this request and update you soon. 

Regards,
Uzair from RepairDesk

**Comment by Uzair-RepairDesk** [comment]
Hi @ben-ihelputech 

I am pleased to inform you that we have increase limit of passcode field to 30 characters.

Please review at your end. Thanks
