### ISSUE TITLE
Seling after end shift

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#828]
There is an issue selling after end shift without start shift in ipad app

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Can you please provide more information on this ?

**Comment by hitman1986** [comment]
When you end shift in ipad app you can checkout any item without start shift ,this wrong.

**Comment by hitman1986** [comment]
Im sorry for bad my English language

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Did you checked option of mandatory start shift from web app in Settings > Cash Register > Mandatory to start shift ?

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Sorry for the misunderstanding. I have checked this with iPad team and this trigger is not implemented yet on iPad. We will work this on future. I will update you once it will be live. For now please start manually before any transaction on iPad app. 

Thanks '
Usman Ali
