### ISSUE TITLE
Another time app ipad crash

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#829]
Another time ipad app crash when change price ticket from 0 to any price،
Note that this problem was previously resolved by you earlier but returned.

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope you are doing well. Our iPad release has been live. Please update your version. This bug has been resolved. Do let me know if you have any question. 

Thanks
Usman Ali
