### ISSUE TITLE
Ipad app crash when search in invoice by customer name

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#830]
Ipad app crash when search in invoice by customer name , knowing that not every customer has some customers working properly and some of them crash the app , note : i use arabic language when search

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Can you specify any customer on which you are getting app crash ?

**Comment by hitman1986** [comment]
الدعجة

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I have checked your concern on iPad and it is working fine. Can you please check it again ? If you still face an issue please send us a video so we can look it into further.

**Comment by hitman1986** [comment]
Im sended video to mr danish to explain this issue

**Comment by usmanalikhan93** [comment]
Thank you @hitman1986

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I believe Danish has updated you on this issue. Do let me know if you are still facing this issue.

**Comment by hitman1986** [comment]
yes im still facing issue
.

**Comment by usmanalikhan93** [comment]
Hey @hitman1986 

Just wanted to confirm are you still facing this issue ?

**Comment by usmanalikhan93** [comment]
Hi again @hitman1986  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
