### ISSUE TITLE
Add payments for purchase order

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#832]
I need when add payment to purchase order discount this payment from cash in end shift

**Comment by Uzair-RepairDesk** [comment]
Hi @hitman1986 
Thank you for your post. When you add payment in a Purchase order, it's actually your expense that you pay to your supplier. 
Currently its not automatically logged in RepairDesk however once you add payment in the Purchase order, we suggest to go to the expense and log the same payment value in the expense. You can create an expense code with a relevant name like "Supplier's payment" and give PO reference in reason while logging the expense. 

You can find more information regarding Manage Expenses from the following article:-
https://repairdesk.uservoice.com/knowledgebase/articles/1827157-how-to-enter-track-expenses-via-expense-manageme

Can you please let me know why you are exactly want to log it in "Cash In" value?

**Comment by hitman1986** [comment]
How to make it remind me of the payment date

**Comment by hitman1986** [comment]
I hope you will add this feature in the future

**Comment by Uzair-RepairDesk** [comment]
I believe you have already logged it here #831 

I hope the above description will assist you in logging expense in RepairDesk when you add payment in RepairDesk. Thanks
