### ISSUE TITLE
Purchase Order Not Displaying on Inventory Admin History

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#834]
When i enter into the single page of a part and go to the "Admin History" section at the bottom of the page even though the product is on an active PO it does not show in this section. 

From the product page i am unable to identify if the product has been placed onto a PO already. I have to manually open the PO page and go through them to find the product.

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

Thanks for highlighting this concern. Let us check all the scenarios and I will update you once I will discuss this with our product manager. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/REP-2119

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

We have added PO history in inventory item. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali
