### ISSUE TITLE
Purchase Order Template

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#835]
Default Purchase order template does not display correctly when you add internal notes to the PO. 

The internal notes box on the left causes the display errors for the totals on the right when exporting to PDF.

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

Your reported issue has been fixed. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali

**Comment by benjamingartner** [comment]
Thank you.
