### ISSUE TITLE
Ticket Task Type is Defaulting to Refurbishment

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#836]
Every ticket we create it is defaulting to Refurbishment instead of Walk-in etc.

**Comment by usmanalikhan93** [comment]
HI @benjamingartner 

Can you provide more information on this ?

**Comment by benjamingartner** [comment]
This is the default everything is going to when we create new tickets. 
![image](https://user-images.githubusercontent.com/39751801/60871464-f9f38100-a271-11e9-9cd3-5ff5728b7132.png)

**Comment by benjamingartner** [comment]
I dont know why it is defaulting to Refurbishment when these other options are available.
![image](https://user-images.githubusercontent.com/39751801/60871556-2909f280-a272-11e9-8436-414eaf698478.png)

**Comment by usmanalikhan93** [comment]
Thanks @benjamingartner 

Let me check this.

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

It is just coming as default as it is on top of the list I think.

**Comment by benjamingartner** [comment]
This seems to be fixed.
