### ISSUE TITLE
Mailchimp Tags in RD

### ISSUE THREAD

**Issue by BG-RLTech** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#838]
We have recently started organising our customers in Mailchimp with tags, Such as Apple, iPhone X, Education, Commercial etc. 

It would be handy to select the Tag within RD upon creation so it automatically assigns that Tag in Mailchimp. 

When we create a campaign in Mailchimp and select the Tag it has already populated from RD.

**Comment by Uzair-RepairDesk** [comment]
Hi Benjamin @benjamingartner 

I really appreciate that you took the time to share your idea. Currently, our MailChimp integration is supported with a single list of MailChimp. Once you select the list while integrating it with RepairDesk, all the customers sync to that specific list. 
You can find more information from the following link:-
https://repairdesk.uservoice.com/knowledgebase/articles/1197193-how-can-i-integrate-mailchimp-with-repairdesk

I can certainly see how the suggested improvements would be useful.  Our current focus is the stability of the platform and we pick new features based on the value they’ll add to the most users possible. At the moment we won’t be able to make this immediately, however, I am adding this under enhancements and marking a label with MailChimp so we can incorporate the feature of adding multiple lists once we improve the integration. Thanks

Regards,
Uzair (Product Manager at RepairDesk)

**Comment by Uzair-RepairDesk** [comment]
**Hi Benjamin @BG-RLTech** 

Good News, we have updated MailChimp integration with tags functionality. You can now select tags to sync with customers. You can either use tags with a single mailing list or you can also use the "Multiple Mailing List" to sync customers based on specific tags. 
You can pick tags based on the following:-
- Store location
- Customer Group
- Product Category
- Repair Category
- Manufacturer
- Device

**Please check the following knowledgebase article for your understanding:-**
https://help.repairdesk.co/knowledgebase/articles/1197193-how-can-i-integrate-mailchimp-with-repairdesk

If you have any questions, you can comment or send an email at support@repairdesk.co

Be sure to let us know if there's anything we can do to make it even better. Thanks

**Regards,
Uzair**
