### ISSUE TITLE
Predicted Date covers actual Calendar In PO "Add Payment"

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#839]
When you select "Add Payment" to the Purchase Order section the pop up window appears. 

If you select the date field the calendat normally pops down for a selection to be made. 

Recently a predictive popup appears with dates that covers the calendar.

![image](https://user-images.githubusercontent.com/39751801/60964417-db5eba00-a345-11e9-89bf-19424eb13f82.png)

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

Thank you for bringing this to our attention! I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! For now you can press "esc" button and then select date. 

For internal use: 
https://repairdesk.atlassian.net/browse/RB-273

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

Your reported issue has been fixed. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali
