### ISSUE TITLE
Merge Customers

### ISSUE THREAD

**Issue by BG-RLTech** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#840]
We are seeing a number of customer with duplicate entries, one with an email address and another with mobile number under the same name. 

Can you merge contact to save having to manually enter each ticket and change over etc.

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

It will be difficult to merge these because it may cause any issue in tickets data. Anyhow I will discuss this with relevant developer for the feasibility and I will update you on Monday.

**Comment by benjamingartner** [comment]
Thanks Usman, basically i am having to open one of the customers. Edit the ticket and re-search for the correct customer. Surely this process can be automated if you tick two customers and select which one you want to make primary? Maybe not i just thought if the process can be done manually maybe it can be done automatically. 

Cheers for considering.
![image](https://user-images.githubusercontent.com/39751801/61048311-14fdf680-a414-11e9-9d85-0e9696fcb151.png)

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk can you please review this ?

**Comment by Uzair-RepairDesk** [comment]
Hey Benjamin @benjamingartner 

Currently, it's not possible to merge the customers in RepairDesk. We recommend the following solution if you find a duplicate customer in RepairDesk. 
You can edit its ticket and invoices and mark with the primary customer details. Once you do that you can update details of the primary customer and delete the secondary customer. 

Hope it helps.

However, I am marking your request under enhancements so we can pick it up in future if we decide to develop the "merge customer" functionality.

**Comment by mobilebarn** [comment]
Surely there has to be a way @Uzair-RepairDesk ? This is a badly needed feature, one that would benefit many.

**Comment by Uzair-RepairDesk** [comment]
Hi @BG-RLTech 
Hope you are staying safe. 

I am here with an update for you on this thread. We have added the merge customers functionality in RepairDesk as you have requested. Please give it a review and share any feedback if you have. 

You can learn more about it from our [knowledgebase article](https://help.repairdesk.co/knowledgebase/articles/1945498-merge-customers-in-repairdesk). 

Looking forward to your feedback. 

Regards,
