### ISSUE TITLE
Correct Format for Mobile Number

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#841]
We have found many of our customer profiles has the mobile number in the incorrect format. 

Is there a way the 0 can be removed and +61 added without doing it manually?

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

Let me discuss this with relevant developer whether it can be done or not.

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

We have added +61 where 0 is in start of the number. Please check this at your end and do let me know if you have any question. 

Thanks 
Usman Ali.

**Comment by benjamingartner** [comment]
Hi Usman, for the most part this seems to have worked however there are quiet a few anomolies like the attached which i will have to go through and rectify. But not as many as doing it the other way. 
![image](https://user-images.githubusercontent.com/39751801/61265736-2c4a3480-a7c4-11e9-915d-a84075a3b6f5.png)


My bigger problem is since having this fix done we seem to have lost our customised 'Item Conditions' which is much more important to me.

**Comment by benjamingartner** [comment]
PLEASE UNDO WHAT EVER YOU HAVE DONE!

Not sure what was changed but all of our custom settings have gone also. The customised payment options we set up have gone also, there were others populated here.

![image](https://user-images.githubusercontent.com/39751801/61267225-987b6700-a7c9-11e9-866a-3ec03665dd08.png)

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

Sorry for the trouble. It was not because of phone number fix. Let me investigate this case what happened to inventory condition. I will update you once I get more info from development team.

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let Danish know if you have any question.

Thanks!
Usman Ali

**Comment by benjamingartner** [comment]
I noticed the conditions came back Yesterday. I allocated about 50 products again. I just noticed 10 minutes ago you wiped them all. Is that final now. I can start repopulating our item conditions for every product?

**Comment by usmanalikhan93** [comment]
Hi @benjamin

Yes it is final now. You can add item conditions in products.
