### ISSUE TITLE
Repair Widget Mobile Phone Field

### ISSUE THREAD

**Issue by benjamingartner** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#842]
The Mobile Phone Number field on the Repair Widget is the cause of alot of our customers being entered into our database incorrectly. 

It would be good if this saved the mobile number (0424******) in the correct format as required by RD (+61 424******) instead of just how it was entered. 

![image](https://user-images.githubusercontent.com/39751801/61048770-62c72e80-a415-11e9-80ed-074cf63df164.png)

**Comment by usmanalikhan93** [comment]
Hi @benjamingartner 

You can change it by unchecked the trigger in Appointment Calendar "Pick phone number in any format". It will resolve your issue. Settings > Integrations > Appointment Calendar > Configuration. Please check Screen shot for reference. 
![Github-842](https://user-images.githubusercontent.com/39614480/61103977-ddcc2b80-a48d-11e9-8de2-ab5c37242234.png)

**Comment by usmanalikhan93** [comment]
Hi again @benjamingartner - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
