### ISSUE TITLE
Import/export support for serialized items

### ISSUE THREAD

**Issue by lopugit** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#846]
When exporting/importing your inventory using excel, serialized items are not included, it would be really good if you could edit serialized items through excel too! because right now incrementing quantity, then adding serialized item takes quite a while.

maybe the excel sheet could have a column for parentItemNo which links the child/serialized item with that parent

**Comment by Uzair-RepairDesk** [comment]
Hi @lopugit 

I really appreciate that you took the time to share your idea.

I can certainly see how the suggested improvements would be useful. It will certainly save time and effort to create serials however there are multiple criteria's available to create serials that are not possible to add with excel file to import items in bulk.
At the moment, we won’t be able to make this one work during our current quarter however I will discuss it internally and check possibility with the team to add it in RepairDesk.  Thanks.

**Comment by Uzair-RepairDesk** [comment]
Import/Export option for serialized items is available in RepairDesk
