### ISSUE TITLE
VAT - incorrect rounding

### ISSUE THREAD

**Issue by BRZLab** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#848]
Repairdesk is incorrectly rounding the vat.

**Actual calcution**
Cost: 102,39
VAT (21%):  21,5019
Total:  123,89

**Repairdesk calculation**:
Cost 102.39
VAT (21%): 21,51
Total: 123,90

It's not a big difference, but its creating minor inconsistencies with our corporate customers and is not in line with tax regulations. (NL)

Background:
3rd number behind the comma decides whether the figure is rounded up or down.
Is the 3d number below 5 = round down
is the 3d number 5 or above = round up.

**Comment by usmanalikhan93** [comment]
Hi @BRZLab 

I have reviewed your concern but it is working fine. You can check this in video it's calculating correctly. 
Video link: https://drive.google.com/file/d/1armhugkWXDNplPyJTSLq8XxeYm_afQdL/view

**Comment by usmanalikhan93** [comment]
Hi again @BRZLab  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks
Usman Ali
