### ISSUE TITLE
Woocomerce integration enabled by default on new items

### ISSUE THREAD

**Issue by cupell08** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#849]
Can there please be an option to have Woocomerce integration enabled by default on new items created?

**Comment by Uzair-RepairDesk** [comment]
Hi @cupell08 

Thank you for sharing your idea. Currently, we allow marking specific categories to sync with the woocommerce. 
It's not always necessary that user wants to sync a new item automatically so we didn't add a default option to sync a new item with woocommerce. However, while adding a new item, there is an option available to mark an item to sync with woocommerce under "Triggers". You can enable the option "Sync With WooCommerce" if you want to sync new item as well. 

Please check screenshot attached. 

I have still logged your request with an enhancement so I can discuss it with the team to check the possibility to add in RepairDesk. Thanks

![AwesomeScreenshot-AlternateEdit-Mobile-Accessories-Parts-iPhone-6-Mic-2019-07-15-17-07-76](https://user-images.githubusercontent.com/22955861/61217981-5e0ebd00-a72a-11e9-84fb-a7dec03e6e42.png)
