### ISSUE TITLE
Note to customer in ticket message section

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#850]
Regularly and randomly, we are not able to send an email to the customer via a ticket. We are not able to enter a private note or diagnostic note. In short, nothing is accessible except the first column "all". We can send emails to employees, but not write diagnostic notes or contact the customer via the ticket. Here is some example:
SOS Phone Lévis: LE-4826
SOS Phone Ste-Foy: F-4939

Thank you and good day

<img width="942" alt="customer mesage note" src="https://user-images.githubusercontent.com/40500094/61242305-5e4f8e00-a713-11e9-9e85-b7bf506b085b.png">

--
French: Régulièrement et de façon aléatoire, nous ne sommes pas en mesure d'envoyer un courriel au client via un billet. Nous ne sommes pas capable d'inscrire une note privée ou une note de diagnostique. Bref, rien n'est accessible sauf la première colonne "all". Nous pouvons donc nous envoyer des courriels entre les employés, mais pas inscrire des notes de diagnostisque ou contacter le client via le billet. Voici quelque exemple:
SOS Phone Lévis: LE-4826
SOS Phone Ste-Foy: F-4939

Merci et bonne journée

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS ,
 
Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Thanks
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-301

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
