### ISSUE TITLE
Keyboard shortcuts in trade-in section

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#851]
Hello,
Since a few days, we are no longer able to click on "enter" to start the search, for fields circled in red in the attachment. This is the tradein section. To start the search, we must absolutely click on the "search" button in blue with our mouse instead of clicking on the "enter" button on our keyboard. Fields that are not outlined in red work well with the "enter" key. Before, all the fields were available with keyboard shortcuts. Can you please watch.
<img width="940" alt="tradein enter" src="https://user-images.githubusercontent.com/40500094/61244034-4c6fea00-a717-11e9-883d-e276386b49a9.png">

--
French:
Bonjour,
Depuis quelque jours, nous ne sommes plus en mesure de cliquer sur "enter" pour commencer la recherche, pour les champs encerclé en rouge dans la pièce jointe. Il sagit de la section tradein. Pour lancer la recherche, nous devons absolument cliquer sur le bouton "rechercher" en bleu avec notre souris au lieu de cliquer sur la touche "enter" de notre clavier. Les champs qui ne sont pas encadrer en rouge fonctionne bien avec la touche "enter". Avant, tous les champs était disponible avec le raccourcie clavier. Pouvez-vous regarder svp.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

Thanks
Usman Ali

For internal Use:
https://repairdesk.atlassian.net/browse/RB-299

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

We have added some validations against these fields that only number will be acceptable. That's why it is taking Enter as special character and do not work. It is in library which we were using for the validation. So developer said you have to click on search button.

**Comment by JessicaSOS** [comment]
Perfect, I wait for your news.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
