### ISSUE TITLE
Refurbishment Batch 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#852]
Hello, 

I'm having an issue with the adding parts to a Refurbish Batch. A category and parts have been created for this especific category. This issue happens for iPhone 7 when I try to add any parts to the batch. The Select Device Problem doesn't appear altho their are parts already signed to this category. For the iPhone 6 it works just fine. 

![Screen Shot 2019-07-15 at 11 38 15 AM](https://user-images.githubusercontent.com/47898011/61245979-9c908180-a702-11e9-9a17-adfaf7d887b6.png)

**Comment by Uzair-RepairDesk** [comment]
Hi @Omar1892 

Repair service is associated with the device of the serial. When you select a serial and there is a specific device, you are able to see the device problem. When you select the problem and create a ticket from refurbishment batch, then the part is automatically populated on the ticket if it is bundled with the repair service. 
You can find more information regarding refurbishment batch functionality from the following knowledgebase article. 
https://repairdesk.uservoice.com/knowledgebase/articles/1906375-refurbishment-module

If you still facing any issue in a specific device, you can share your account credentials with me by email (uzair@repairdesk.co) so I can look into it. Thanks

**Comment by Omar1892** [comment]
Im going to close the issue for now and have one of the reps help understand how it works. If anything ill get back to you guys. Thank you.
