### ISSUE TITLE
UNLOCKING TAB 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#853]
I have an issue with writing notes when adding a new unlock to the unlocking tab. As you can see in the screen shot the description of what it is that has to be done to unlock or to offer the service is pretty crowded. When I try to space them out in the instruction box it does it but when I save the info entered it gets really crowed and it makes it harder for the person to do the unlock to read through everything instead of spacing things out and just pointer of what it is that they need to get from the costumer. 
![Screen Shot 2019-07-15 at 1 20 52 PM](https://user-images.githubusercontent.com/47898011/61246312-656ea000-a703-11e9-8cec-6b142c49e450.png)
![Screen Shot 2019-07-15 at 11 37 17 AM](https://user-images.githubusercontent.com/47898011/61246313-66073680-a703-11e9-8269-c87d87e20cd3.png)

**Comment by Omar1892** [comment]
??

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Sorry for the delay. Let me check this for you.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I have checked with developer and he said it can be done. I will schedule this for next week. I will update you once it will be done. 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-311

**Comment by Omar1892** [comment]
Sounds good thank you!

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
