### ISSUE TITLE
PARTS ARE SHOWING IN THE ACCESSORIES TAB 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#854]
Hello, 

The repair parts are showing in the wrong tab. Parts are showing in the accessories tab but the parts show no inventory in this section. But when you look in the parts tab and click on the galaxy parts it does show that we have parts. I would like the galaxy parts not to show on the accessory tab 
![Screen Shot 2019-07-16 at 2 55 34 PM](https://user-images.githubusercontent.com/47898011/61332860-34ad6a00-a7da-11e9-8de6-3cc3ed4c3a8f.png)

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. I have assigned this task to development team. I will update you once I get more info on this.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-292

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Developer said "Manufacturers are mutual between Repairs and Accessories. Currently it is not possible to hide it from Accessories only."

**Comment by Omar1892** [comment]
But it isn't showing any inventory in that tab and we have inventory that tab in the part section. Is their any way that, that tab can be removed from the accessories section since its causing confusion? I don't want to get rid of any inventory in this tab just not to show in the Accessories side.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

For now it is impossible according to developer. And I hope Fahad has also guided you on this piece.
