### ISSUE TITLE
Still problems in employee commissions

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#856]
The commissions on the accessories should be to the person who made the sale, and the commissions on the repairs should be to the person who is assigned the repair.

Employee commissions are set as follows in the settings: 1% repairs and 5% accessories.

Stacey was at SOS Phone Sainte-Foy on July 16th and worked all day. When I look at her commission report, it's as if she did not make any commission on repairs and no commission on accessories. Yet both were sold that day at St Foy's shop by Stacey. See his report attached "Stacey Commission".
<img width="942" alt="stacey commission" src="https://user-images.githubusercontent.com/40500094/61478505-a2cf6980-a95f-11e9-8f5e-945ff45d7edd.png">

1-The employee commission report that employees view is inconsistent with the employee commission report detailed in the reports.

I can see in the "employees commission report" that Stacey made a commission on the invoice FF-7540. See image attached "employee commission report Stacey" 
<img width="944" alt="employee commission report Stacey" src="https://user-images.githubusercontent.com/40500094/61478535-b1b61c00-a95f-11e9-925b-a9e653c8282f.png">

Yet all she did in the ticket history is to charge the customer. It was Kelsye who created the ticket, it was David who did the repair, it was Simon who made the "transfer back" and Stacey who proceeded to the payment of the customer. See the F-5409 SOS Phone Sainte-Foy ticket for historical details. So I can see that Stacey has a commission on this bill, but when I go to view her commissions in "my commission", she does not see any for this day.

2- The report "employees commission report" is therefore in error since Stacey is not entitled to commissions for this invoice.

We can see that David has also been paid for this bill. See attachment "david commission" and Stacey also has been paid, see "Stacey commission FF7540".
<img width="937" alt="stacey commission FF7540" src="https://user-images.githubusercontent.com/40500094/61478569-c1356500-a95f-11e9-8152-797718df0938.png">
<img width="944" alt="david commission" src="https://user-images.githubusercontent.com/40500094/61478578-c5fa1900-a95f-11e9-835f-b3d968eb96d3.png">

--
French :
Les commissions sur les accessoires devrait être à la personne qui a effectué la vente, et les commissions sur les réparations devraient être à la personne qui c'est assigné la réparation.

Les commissions des employés sont configuré comme suit dans les réglages : 1% des réparations et 5% des accessoires.

Stacey était au SOS Phone Sainte-Foy le 16 juillet et elle y a travaillé toute la journée. Lorsque je regarde son rapport de commission, c’est comme si elle n’avait fait aucune commission sur les réparation et aucune commission sur les accessoires. Pourtant, les deux ont été vendu cette journée là à la boutique de Sainte-Foy par Stacey. Voir son rapport en pièce jointe « Stacey commission ».

1-Le rapport de commission des employés que les employés visualisent ne concorde pas avec le rapport de commission des employés détaillé dans les rapports. 

Je peux voir dans le « employees commission report » que Stacey a fait une commission sur la facture FF-7540. Voir image en pièce jointe « employee commission report Stacey » Pourtant, tous ce qu’elle a fait dans l’historique du billet est de faire payer le client. C’est Kelsye qui a créé le billet, c’est David qui a fait la réparation, c’est Simon qui a fait le « transfert back » et Stacey qui a procédé au paiement du client. Voir le billet F-5409 SOS Phone Sainte-Foy pour consulter l’historique. Je peux donc voir que Stacey a une commission sur cette facture, mais lorsque je vais visualiser ses commissions dans « my commission », elle n’en vois aucune pour cette journée. 

2- Le rapport « employees commission report » est donc en erreur puisque Stacey n’a pas le droit à des commissions pour cette facture.

Nous pouvons voir que David a également été payé pour cette facture. Voir pièce jointe « david commission » et Stacey aussi a été payé, voir « Stacey commission FF7540 ».

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Thanks 
Usman Ali

**Comment by MuhammadAdnan32** [comment]
Hey! @JessicaSOS 
**1-The employee commission report that employees view is inconsistent with the employee commission report detailed in the reports.**
![image](https://user-images.githubusercontent.com/50608942/64763119-d215e780-d558-11e9-89dc-80da931a5ca1.png)
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 

**2-The commissions on the accessories should be to the person who made the sale, and the commissions on the repairs should be to the person who is assigned the repair. On the repair commission  should go to the person which make an invoice.** Employee commissions are working fine. I have checked in your account and found that you have enabled this triggers "Commission is splitted between the technician and a salesperson who books a repair job" that's why it is showing you commission for both.
![Setting-Employee-commison2](https://user-images.githubusercontent.com/50608942/64762652-fae9ad00-d557-11e9-8cc4-75a151405b17.png)
That's why David has also been paid for this bill and Stacey also has been paid.

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-436

**Comment by MuhammadAdnan32** [comment]
Hey @JessicaSOS 
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have a question.

Thanks!

**Comment by JessicaSOS** [comment]
A sale for you is the person who cashes the money? For me, a sale is the one that makes the ticket or invoice. In the options, it is written that it is the person who reserves a repair order. So it's not very clear.

For example, if Stacey creates a repair ticket and David performs the repair. Simon puts the repaired status and the ticket asks us "do you want to apply the changes to the invoice?" or "create an invoice?" and he clicks yes, even if he did not do anything for this client, he will have the sales commission? If it's me Jessica who pays the customer, who will have the commission of the sale?

Also, the term "shared" is for me a separation of the amount in two, a kind of sharing. In your case, you doubled the amount since each employee has a percentage. That's right?

Thank you for giving me more information about this.

Also, I do not have the choice to click on the option "Commission is splitted between the technician and a salesperson who books a repair job" so that the saleswoman and the technician have commissions. The other options are just at the sales level and just at the repair level. How to make the saleswoman have the commissions of the accessories (for example) and that the technician have the commissions of the repairs that he carried out?

------- FRENCH-------

Une vente pour vous est la personne qui encaisse l'argent? Pour moi,  une vente est celle qui fait le billet ou la facture. Dans les options, il est inscrit que c'est la personne qui réserve un bon de réparation. Ce n'est donc pas très clair.

Si par exemple, si Stacey crée un billet de réparation et que David effectue la réparation. Simon met le statut repaired et le billet nous demande "voulez-vous appliqué les modifications à la facture?" ou "créé une facture?" et qu'il clique sur oui, même s'il n'a rien fait pour ce client, c'est lui qui aura la commisison sur la vente? Si c'est moi Jessica qui fait payé le client, qui aura la commission de la vente?

Aussi, le terme "shared" est pour moi une séparation du montant en deux, un genre de partage. Dans votre cas, vous doublé le montant puisque chaque employé a un pourcentage. C'est bien ça?

Merci de me donner plus d'information à ce sujet.

Aussi, je n'ai pas le choix de cliquer sur l'option  "Commission is splitted between the technician and a salesperson who books a repair job" pour que la vendeuse et le technicien ai des commissions. Les autres options sont juste au niveau de la vente et juste au niveau des réparations. Comment faire pour que la vendeuse ai les commissions des accessoires (par exemple) et que le technicien ai les commissions des réparations qu'il a effectué?

**Comment by usmanalikhan93** [comment]
@MuhammadAdnan32 can you please check ?
