### ISSUE TITLE
more than 20 item in a purchase (trade in)

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#857]
It is impossible to add more than 20 phones in a single purchase. The 20th device always erases the 19th.

It was 20 item maximum yesterday and 23 item maximum 2 weeks ago. I tried different days, different computers and different items.

_--
french:
Il est impossible d'ajouter plus de 20 téléphones dans un même achat. Le 20ème appareil efface toujours le 19ème.

C'était 20 item maximum hier et 23 item maximum il y a 2 semaines. J'ai essayer différentes journées, differents ordinateurs et différents items._

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-320

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
It is settled and it is also much faster, thank you!
