### ISSUE TITLE
Cost price not the same in each store

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#858]
Hello,
When we transfer inter-branch items, we have noticed that some products have no cost price. Yet, by going to see the item (example # 11137) we can see that there is indeed a cost. The problem is that the cost is not in all shops. As if he had gone to Limoilou's shop only. Many items are like that. Can you correct the problem please.
<img width="946" alt="From Lévis to Limoilou item #11137" src="https://user-images.githubusercontent.com/40500094/61480627-589cb700-a964-11e9-814b-fcd9f2959898.png">

<img width="944" alt="item #11137" src="https://user-images.githubusercontent.com/40500094/61480596-4cb0f500-a964-11e9-9d50-641a13a95ea5.png">
<img width="938" alt="#11137 Lévis store" src="https://user-images.githubusercontent.com/40500094/61480611-50dd1280-a964-11e9-9170-c5f04f79529b.png">

--
French:
Bonjour,
Lorsque nous transférons des item inter succursales, nous avons remarqué que certain produit n'ont pas de prix coutant. Pourtant, en allant voir l'item (exemple #11137) nous pouvons voir qu'il y a bien un prix coutant. Le problème, c'est que le prix coutant n'est pas dans toutes les boutiques. Comme s'il s'avait mis uniquement à la boutique de Limoilou. Plusieurs item sont comme ça. Pouvez-vous corriger le problème svp.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Every store has it's own inventory cost price. Cost price doesn't sync between stores. That's why you are seeing item cost 0 in second store. You have to manually update in store to store.

**Comment by JessicaSOS** [comment]
But the costing item was put in item # 11137 in Limoilou's shop at $ 259.48 and then the item was transferred to Inventory Transfer # TO-3790. In the transfer, we can see that the cost is $ 0. it's not normal. The transfer was made after adjusting the cost price. 
See picture:
<img width="946" alt="#11137 sos phone LImoilou history" src="https://user-images.githubusercontent.com/40500094/61538584-b7ffd300-aa07-11e9-9309-76f2183de5ff.png">
<img width="943" alt="TO-3790" src="https://user-images.githubusercontent.com/40500094/61538598-bd5d1d80-aa07-11e9-83cd-83a891f3d4e3.png">

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Ok let me check with this case.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I believe this issue has been fixed on 15th July 2019. There is some case in which it was causing cost price as 0. Can you give it another try and let me know it it works or not. Because I have checked and it is working for me. I will wait for your response. 


Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
It was not the same problem, but I will watch and come back to you.

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks
Usman Ali

**Comment by JessicaSOS** [comment]
I confirmed with my staff and they told me that the problem was fixed. 
Thank you
