### ISSUE TITLE
Price that appears on the customers facing display

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#859]
Hello,
the price that appears on the iPad signing customers is not good. This is the selling price before taxes plus the first tax. Its should be the price before or after both taxes. Can you correct please.
![price on iPad](https://user-images.githubusercontent.com/40500094/61480848-e11b5780-a964-11e9-9106-b3d873f42e58.jpg)
<img width="933" alt="LG-372" src="https://user-images.githubusercontent.com/40500094/61481056-39eaf000-a965-11e9-8c2c-5b4e7acd7bff.png">

--
French :
Bonjour,
le prix qui s'affiche sur le iPad de signature des clients n'est pas le bon. Il s'agit du prix de vente avant taxes plus la première taxes. Sa devrait être le prix avant ou après les deux taxes. Pouvez-vous corriger svp.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
This could be the case in case of dual tax. Please get it checked with Afnan today and give a hotfix by Uzair dev. Thanks

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-321

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
fixed yes ! Tnx
