### ISSUE TITLE
Customer facing display no signature

### ISSUE THREAD

**Issue by BG-RLTech** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#860]
The signature is only working some customers, and not at all for the converted leads.

**Comment by Uzair-RepairDesk** [comment]
Hey Benjamin, @benjamingartner 

Can you please elaborate? Is there any specific case when it doesn't work for you? 

Your detailed description with screenshots will be highly appreciated. Thanks

**Comment by usmanalikhan93** [comment]
Hi again @BG-RLTech - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali
