### ISSUE TITLE
Refurbishment Ticket Costumer info 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#861]
We are having issues when we edit the refurbishment ticket. Once edited it ask us to enter the costumer info. But their is no costumer, so were just putting our business info as a costumer if we don't do it this way it won't let us save the ticket with the parts that where add it to the repair. We have enable the setting for any new ticket that is created for costumer information to be taken. Could this be the issue?

**Comment by Omar1892** [comment]
![Screen Shot 2019-07-19 at 3 41 53 PM](https://user-images.githubusercontent.com/47898011/61570379-08475700-aa41-11e9-8236-1e713d948c9e.png)
 
This is where it ask us to enter the costumer info.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

Yes you are right basically ticket page is same on which you are adding repair. So when you mark mandatory customer information, you can't save ticket without it.

**Comment by Omar1892** [comment]
It would be good to have an option that it won't make it mandatory for Refurbishing tickets only.
