### ISSUE TITLE
Need on the Fly Item Purchase

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#863]
In your current system, we need to raise a PO to purchase items and then receive the items. Now at times we have to do on the fly purchases. Like I need Iphone X LCD urgently, I wud purchase it on the shelf by paying cash. Here I do not need to send any purchase order.
Request you to provide option for Parts purchase without raising purchase order

**Comment by rajeshdungrani** [comment]
No update from team???

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

Currently, it's not directly possible to log the purchase without creating a purchase order. However, i would suggest the following workaround.

1: Once you purchase the item, you can directly add an inventory item with all the relevant item details, supplier and the cost of an item.
2: You can create an expense code in RepairDesk and log expense entry of your purchase by using "Manage Expense" module. 
You can find more details regarding expense module from the following knowledgebase article:-

https://repairdesk.uservoice.com/knowledgebase/articles/1827157-how-to-enter-track-expenses-via-expense-manageme

Hope it helps.

**Comment by rajeshdungrani** [comment]
Thank you very much for suggeting a workaround. Can we get a summary report of this workaround done, so that we can track total purchases done and cost

**Comment by Uzair-RepairDesk** [comment]
I will recommend you to keep a dedicated "Expense Code" in this case. So once you log the expense of your purchase with that specific code, you can track your expense of purchase from expense report. 

Please check screenshots attached for your assistance. 

![AwesomeScreenshot-uzairshah-Manageexpense-Expenses-2019-07-29-16-07-86](https://user-images.githubusercontent.com/22955861/62046572-b0b7a100-b221-11e9-96ff-ebd48c2edb2d.png)

![AwesomeScreenshot-uzairshah-Manageexpense-Expenses-2019-07-29-16-07-91](https://user-images.githubusercontent.com/22955861/62046583-b57c5500-b221-11e9-86a2-0a2a3456a95c.png)

**Comment by Uzair-RepairDesk** [comment]
Hi, Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
