### ISSUE TITLE
All items appear when adding Item line

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#864]
When we add Parts on edit ticket, and search for parts all parts are visible. For e.g If have created a ticket for Iphone X, and after diagnosis I require Battery for Iphone X, I would go to Add Item and try to add battery for Iphone X. Now when I type battery in search box, it shows all batteries of all models which are present. 
![image](https://user-images.githubusercontent.com/12892217/61711240-3397b200-ad71-11e9-8931-9c2a76dafab4.png)

**Comment by Repair-Desk** [comment]
@Uzair-RepairDesk Is it possible to display iPhone X parts first? I believe when you click on the parts it should automatically start display iPhone X parts so its easier for user to pick one. 

Please also check with Imran if it will not slow down the search or have any other issues

**Comment by rajeshdungrani** [comment]
Any update?

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 
Thank you for your follow up. We are already discussing it in-house to check the speed impact of search if we give priority to a device in search results. I will update you soon on this.

**Comment by Uzair-RepairDesk** [comment]
Hey @rajeshdungrani 
I am pleased to inform you that we have improved the search criteria according to your request. 
Please review it at your end. 

When you click on the parts it will start displaying parts based on device reference so its easier for a user to pick one.
