### ISSUE TITLE
Problem task's price issue on POS - Marcus Cupello

### ISSUE THREAD

**Issue by usmanalikhan93** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#865]
Example:

Change iPhone 8 Screen Repair price from $159 to $149 on main store.

On POS it shows $149 at main store , but other stores shows $159 . But if you add to ticket , shows accurate price . And if you look in manage  repair , shows accurate price

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-330

**Comment by Repair-Desk** [comment]
Marcus, 

It looks like this bug has been squashed! Can you refresh your browser and let me know if you're able to see correct price on the point of sale?
