### ISSUE TITLE
INVOICE EMIALS ARE NOT BEEN SENT 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#866]
Hello, 

Email ticket aren't been received once tickets are created and are sent by us to costumers. 

![Screen Shot 2019-07-23 at 5 25 07 PM](https://user-images.githubusercontent.com/47898011/61806410-75197300-adec-11e9-906a-ad991e7851e7.png)
![Screen Shot 2019-07-23 at 5 24 56 PM](https://user-images.githubusercontent.com/47898011/61806418-777bcd00-adec-11e9-800c-7a78a2de1a5a.png)

**Comment by usmanalikhan93** [comment]
Hey @Omar1892 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I have checked your concern but it is working fine on my test account. Can you please check triggers in Email and Notifications ?

**Comment by usmanalikhan93** [comment]
Hi again @Omar1892 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali
