### ISSUE TITLE
Error 524 When opening new tab

### ISSUE THREAD

**Issue by BG-RLTech** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#867]
So perform the below actions and get a Error 524 page on the new tab. 

Inventory > Manage Inventory > Mobile Accessories and Parts > Right Click on Item ID > Open Link In New Tab.

I get the below page every time and i was wondering if this is a RD problem or specific to my computer.
![image](https://user-images.githubusercontent.com/39751801/61838279-22f35300-aebb-11e9-8ca2-25e39f052da9.png)

**Comment by usmanalikhan93** [comment]
Hi @BG-RLTech 

Sorry for the inconvenience you faced. It may be server glitch. Can you please check now and inform whether you are still facing this issue or not. Waiting for your reply. 

Thanks 
Usman Ali

**Comment by BG-RLTech** [comment]
Please disregard this is rectified
