### ISSUE TITLE
Minor Improvements In Customer Search

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#868]
You should be able to search customer by organization name. Also if you've created a customer group and added contact person name you should be able to search by contact person name

**Comment by rajeshdungrani** [comment]
Infact, we shud be able to search customer by all fields that we enter in customer details like - City, Network Type, referred by. Since we are feeding all details, let all fields be available in search option

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk 
Currently, you can search a third party customer of a specific customer group. You can go to 
"Manage Customer > Select Customer Grup and check "Display third party customers" 
Can you please specify the area where you want to search customer by "Organization". Is it about a global search of customers? Currently, we have an option available to search customer by the organization under "Manage Customer". 

Thank you for sharing your thoughts on this @rajeshdungrani 
We have the plan to improve manage customers page with new search filters as we did on "Manage Tickets" and "Manage Invoices". We can certainly add all the relevant criteria's to search customer with city, network, referred by, etc.
