### ISSUE TITLE
Add Customer - Custom Fields

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#869]
When adding or editing a customer profile there should be an option to customize this form. 

- It would be handy to add secondary contact mobile number
- Also it would be handy to make some fields mandatory
- Lastly it would be great if we can choose which items should display on the first page

**Comment by rajeshdungrani** [comment]
I agree, certain fields should be made mandatory. I also would like to have that feature. So that we can have customer data in uniform format.

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 
Hope you are doing well 

I am here with an update for you regarding custom fields functionality for our customers module. We have added this functionality for you and now you can create custom fields against customers. To learn more on how this works, please read our [knowledge base article.](https://help.repairdesk.co/knowledgebase/articles/1945435-custom-fields-against-customers) 

Looking forward to your feedback. 

Regards,
