### ISSUE TITLE
universal settings for multi-store

### ISSUE THREAD

**Issue by mobilebarn** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#872]
Hey guys, can we implement a feature that allows the settings to be synced across all stores so each stores logo and terms and conditions ect. are all the same and dont have to be setup for each store.

**Comment by Uzair-RepairDesk** [comment]
Hi @mobilebarn 

Thank you for sharing your idea. We are already working to improve the onboarding process. Once you add a new store, we will give an option to replicate all the settings from your default store. You will be able to select specific settings as well. 

I will update you once we GO LIVE. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi @mobilebarn 
We have gone LIVE with our new "onboarding/sign up funtionality". Once you add a new store, system asks you to replicate all the settings from the default store to a new store. 

Please review at your end. Thanks.
