### ISSUE TITLE
hide part cost on ios app

### ISSUE THREAD

**Issue by mobilebarn** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#873]
can we have the ability to hide the part cost on ios app, so if customer is standing with you they dont see :)

**Comment by Repair-Desk** [comment]
@mobilebarn 

Are you referring to the iPAD POS app or mobile app?

**Comment by mobilebarn** [comment]
iPad pos app. I noticed since we made our pos all organised and pretty with pictures the customers tend to watch as we book them in and at the inventory selection screen the part cost is visible

**Comment by mobilebarn** [comment]
Btw we use our iPad POS as a backup to main terminals that utilize the web app on a PC when busy. Thats the only reason customers see the iPad and what were booking in as we're usually on the shop floor with them :)

**Comment by Uzair-RepairDesk** [comment]
Hi @mobilebarn 

I have reviewed it at my end. When you select a part while booking a repair job from iPad POS Register, there is a "Retail Price" that displays with the item on POS. 

It will be appreciated if you provide more information along with screenshot where it's displaying cost price with the part item on iPad POS Register app? Thanks

**Comment by mobilebarn** [comment]
ah my apologies you are right :)

**Comment by Uzair-RepairDesk** [comment]
No problem. Thank you for the confirmation.
