### ISSUE TITLE
Improvement in Mail Chimp for Single or Multi-stores

### ISSUE THREAD

**Issue by mobilebarn** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#874]
does mailchimp integration work with multi store and if not is this something you could add to your roadmap

**Comment by Repair-Desk** [comment]
Hello @mobilebarn 👋

Happy to help with this! At present, our mailchimp integration doesn't work with multiple stores. 

This do sounds like a great idea! I could see adding support for multiple stores will be super useful for a ton of merchants who has more than one store location where they would like to create Google listing for an individual store and direct customers to leave review there.

I also feel that when a customer is synced with Mailchimp we should add following tags so you can create custom audience for each campaign:

- {store name} e.g. Store 1, Store 2
- {item type} e.g. Repair, network unlock, accessories
- {manufacturer} e.g. Apple
- {device} e.g. iPhone 7
- {product category} e.g. Pre-owned phone, case, tempered glass

I'll let the dev team know this is something that's worth considering. They're always looking for ways to improve the product and detailed examples like this are super helpful in guiding that process.

If you have any further feedback you would like to add, just let me know! Happy to pass on the best details possible for you.

Your friend at RepairDesk!
Usman Butt

**Comment by Uzair-RepairDesk** [comment]
https://github.com/Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS/issues/838

**Comment by Uzair-RepairDesk** [comment]
**Hi @mobilebarn **

Good News, we have updated MailChimp integration with multiple mailing list and tags functionality. You can now select tags to sync with customers. You can either use tags with a single mailing list or you can also use the "Multiple Mailing List" to sync customers based on specific tags. 
You can pick tags based on the following:-
- Store location
- Customer Group
- Product Category
- Repair Category
- Manufacturer
- Device

**Please check the following knowledgebase article for your understanding:-**
https://help.repairdesk.co/knowledgebase/articles/1197193-how-can-i-integrate-mailchimp-with-repairdesk

If you have any questions, you can comment or send an email at support@repairdesk.co

Be sure to let us know if there's anything we can do to make it even better. Thanks

**Regards,
Uzair**
