### ISSUE TITLE
Ticket Listing - Option to filter tickets by Network

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#876]
We should add another criteria which allow merchants to search for customer profile through customer network

**Comment by rajeshdungrani** [comment]
Any update on this

**Comment by Uzair-RepairDesk** [comment]
Hey @rajeshdungrani you can search customers using the network from manage customers. 
![image](https://user-images.githubusercontent.com/22955861/99499898-679dda00-299b-11eb-8df7-825e7994e085.png)
Hope this helps.

Regards,
