### ISSUE TITLE
Minor Improvement In Inventory Summary Report

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#877]
It would be great if we can display total inventory value along with total inventory items on top of inventory summary report.

Currently a user has to download the inventory summary report to view this info

**Comment by Uzair-RepairDesk** [comment]
Added in the current sprint

**Comment by Uzair-RepairDesk** [comment]
it's done and lived.
