### ISSUE TITLE
Option to add notes against line item & overall discount

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#879]
When adding a discount there should be an option for employees to add notes against a discount so admin can review it later.

Also a dedicated report or a filter inside a report that lets you view discounted report will be super helpful.

In case of overall discount we let customers enter discount in a popup window.

**Comment by Uzair-RepairDesk** [comment]
Improvement pushed live.

**Comment by Uzair-RepairDesk** [comment]
We have enabled repair shop owners to add notes in discounts now. This option is trigger-based, and the store owner can see the reason for the line item/overall discount offered to customers by store employees.

Your discount notes can be viewed in the Register Sales Report and Sales by Item Type report.

![discount-popup png  455×347 ](https://user-images.githubusercontent.com/22955861/70716068-67b64400-1d0d-11ea-9688-7b2b71873875.png)
