### ISSUE TITLE
Self Check-In - Customer Phone number should automatically add +1 

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#880]
I think I am having issues with the sms service, it does not send customers sms like it should when the repair is done. I believe it is because they don't have the +1 area code from self check in sheet.

Is there a way to add the +1 automatically somehow or make it work without the +1, because here no one will manually write +1 when checking in.

**Comment by usmanalikhan93** [comment]
Hi @Repair-Desk  

Reported issue has been fixed and pushed on live server. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
