### ISSUE TITLE
Page refreshes and it takes me to the repair category 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#883]
Its being happening today when I modify an inventory item in stock and I hit SAVE the page refreshes. But once it refreshes it takes me to the Repair category. Its a glitch from what I can tell.

**Comment by Uzair-RepairDesk** [comment]
Hey @Omar1892 it seems to be working fine at my end, can you please share more detail or a video so that I can look into it.
Regards
