### ISSUE TITLE
Email Receipt Not Being Sent 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#884]
Hello, 

When ever I create a Ticket or at check out costumer aren't receiving our emails receipts. I have checked my spam folder and trash folder and they don't arrive.

**Comment by Uzair-RepairDesk** [comment]
Hey @Omar1892 

Can you check if you have trigger enabled to send an automatic email to the customer while creating a repair ticket?
You can go to Store Settings > Email & Notification > Customer Events > Repair Ticket > 'Send Email Automatically' trigger in turned ON

Please also make sure that you are using the right email address of a customer in customer details. 

Once you check it, please do let know so I can get it checked from your account. You can share your account credentials at uzair@repairdesk.co

**Comment by Omar1892** [comment]
Hello, yes I have enabled the settings and I had a rep called me and the emails are not been sent to my email address.

**Comment by Uzair-RepairDesk** [comment]
Hey @Omar1892 

Can you confirm if you are using a web app or iPad app when it's not working? Can you also please share your account details at uzair@repairdesk.co with an example of an event that doesn't send an email so I can personally check it at my end. Thanks

**Comment by Omar1892** [comment]
We only use computers. I don't how to share detail aside from explaining whats going on. So when we check out the system gives you several options to hand out a receipt including sending an email receipt to the costumer. We have chosen the email receipt and when we send it it doesn't arrive. We have tried several different emails on our side and the emails don't arrive.

**Comment by Uzair-RepairDesk** [comment]
Can you also please share your account details at uzair@repairdesk.co with an example of an event that doesn't send an email so I can personally check it at my end. Thanks

**Comment by Omar1892** [comment]
I have already sent you an email.

**Comment by Uzair-RepairDesk** [comment]
Thanks. I got your following email:-
**Hello, its actually happening on all my tickets. So if you go to one of the tickets that has already been Repaired and Collected and send a receipt or invoice by email it won't arrive. You can try any ticket in any status.** 

I have checked it at my end and its working for me in all the scenarios. It will be appreciated if you can share a screenshot/short video where you exactly sending an email at your end and it's not working. 
Hope to hear from you soon.

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
