### ISSUE TITLE
Date issue in Register Sales Report

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#885]
In register sales report, it is showing payment date in column of invoice date. 
![image](https://user-images.githubusercontent.com/12892217/62188670-b381d580-b38a-11e9-8d22-efe5a43ef523.png)

![image](https://user-images.githubusercontent.com/12892217/62188699-c98f9600-b38a-11e9-8c6c-a19157007b4a.png)

**Comment by usmanalikhan93** [comment]
Hello @rajeshdungrani ,

Thanks for highlighting it. We have created a ticket in development environment for changing the name of it https://repairdesk.atlassian.net/browse/RB-354.

I will updated, once the fixed pushed on live.

Thank you for your patience and time.

**Comment by usmanalikhan93** [comment]
Hi @rajeshdungrani  

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
