### ISSUE TITLE
Category Filter option in Manage Ticket Search

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#887]
Need to have Category Option in Manage Ticket search screen. This would help me if want to check only laptops or only mobiles etc

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

Thank you for sharing your idea. Currently, it's not possible to search for specific tickets with a category. We are working to introduce categories while making a ticket from Manage Tickets, once we do that we will be able to add criteria to search for tickets by "Category" as well. 

Currently, if you want to view sales from a specific category then you can track it from "Sales Summary Report" 
You can go to "Sales Summary Report > Select Type 'Repairs' > Select Criteria 'Repair Category' > You can select a specific category and time duration to view sales from a specific category. 

I am adding your request under "Enhancements" so we can add "Category" under "Manage Tickets" once we introduce category selection under manage tickets.

**Comment by Uzair-RepairDesk** [comment]
Hey @rajeshdungrani 
Hope you are doing well, the above improvement is now live and you can now search for tickets by repair category from manage ticket listing.
![image](https://user-images.githubusercontent.com/22955861/91521099-5307f380-e910-11ea-83fd-afabe62a0df3.png)
