### ISSUE TITLE
employees Time sheet edit

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#888]
I am no longer able to change the hours of my employees on the report of their timesheets. I do not have the option anymore. Thank you for viewing the attachment.
<img width="938" alt="punch employé" src="https://user-images.githubusercontent.com/40500094/62311597-2a39d400-b45a-11e9-81fa-cd1ebee55793.png">

--
French:
Je ne suis plus capable de modifier les heures de mes employés sur le rapport de leurs fiches de temps. Je n'ai plus l'option. Merci de voir la pièce jointe.

**Comment by usmanalikhan93** [comment]
Hello @JessicaSOS ,

Sorry for the trouble. We have created a ticket for the development team https://repairdesk.atlassian.net/browse/RB-356.

We will update you on it after the fix.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by JessicaSOS** [comment]
fixed tnx
