### ISSUE TITLE
GRN Wrong Inventory Value

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#889]
Hello, Im having an issue with the Goods Received Note. When the items have arrived to the store and a GRN is created with already existing inventory is calculating the wrong inventory value for example: 

I have 6 batteries at total value of $54.66 (quantity of 6) + new inventory total value of $65.10 (quantity 7) = The total value is $119.76 / 13 items = $9.21 (actual inventory Value). The system is saying that the total value is $9.30 the price is higher by $0.08 per item. Its a small amount but after a while it will add up and reports will be miss leading.

**Comment by Uzair-RepairDesk** [comment]
Hey @Omar1892 I have checked this issue it seems to be working fine, kindly share screens so that we can view the issue in detail and rectify the issue.
kind Regards

**Comment by Omar1892** [comment]
I have 6 batteries at total value of $54.66 (quantity of 6) + new inventory total value of $65.10 (quantity 7) = The total value is $119.76 / 13 items = $9.21 (actual inventory Value). The system is saying that the total value is $9.30 the price is higher by $0.08 per item. Its a small amount but after a while it will add up and reports will be miss leading.

![Screen Shot 2019-08-02 at 10 23 57 AM](https://user-images.githubusercontent.com/47898011/62388164-74ca5780-b511-11e9-9bdd-59750cd668f7.png)
![Screen Shot 2019-08-02 at 10 37 21 AM](https://user-images.githubusercontent.com/47898011/62388202-8875be00-b511-11e9-8a87-e71f3c25bfc8.png)
![Screen Shot 2019-08-02 at 10 24 46 AM](https://user-images.githubusercontent.com/47898011/62388215-8f9ccc00-b511-11e9-87a9-54397e9f13da.png)
![Screen Shot 2019-08-02 at 10 23 57 AM](https://user-images.githubusercontent.com/47898011/62388227-94fa1680-b511-11e9-9f2c-457ca7cc2de0.png)

**Comment by Uzair-RepairDesk** [comment]
@Omar1892  in the first post you said that the value should be 9.21, and now in a second post, you are saying that it should be 9.30.
kindly share your credentials so that it can look into it. but 9.20 seems fine as per calculation.

kind regards

**Comment by Omar1892** [comment]
I spoke to Fahad and he's going to set up my inventory method as WAC thats the reason why it wasn't doing what I wanted. Thank you
