### ISSUE TITLE
Tax problem ?

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#891]
Hello,
It's been a few times that we see that there is nothing registered in the fields reserved for taxes. Yet, in the repair ticket, the taxes were properly set. We see that taxes have been calculated correctly, but they do not appear in the POS or it should appear. This problem is not with all tickets, only a few and randomly. We had this problem in SOS Phone Limoilou's L-13984.
I send you in another email a video that I made.
--
french:
Bonjour,
Sa fait quelque fois que nous voyons qu'il n'y a rien d'inscrit dans les champs réservé pour les taxes. Pourtant, dans le billet de réparation, les taxes se sont correctement mises. Nous voyons que les taxes ont été calculé correctement, mais elles n'apparaissent pas dans le POS ou elle devrait apparaître. Ce problème n'est pas avec tous les billets, seulement quelques'un et de façon aléatoire. Nous avons eu ce problème dans le billet L-13984 de SOS Phone Limoilou.  
Je vous envoi dans un autre courriel un vidéo que j'ai fait.

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have tried with multiple use case to reproduce this issue but I am unable to do this. Can you please check again when you face this issue do let me ho you created ticket and added items in it ? May be it will help.

**Comment by JessicaSOS** [comment]
This happens to us occasionally, I can not tell you how to reproduce it. What I can tell you is that it happens when we are in the POS.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-392

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I hope you are doing well. Issue has been fixed from now onward. You will not face this bug again in tickets. Please verify at your end and do let us know if you have any question. 

Thanks
Usman Ali
