### ISSUE TITLE
Issues With Tickets 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#893]
Hello, 

when the tickets get the status changed to any status the page refreshes like it has been since we started using the system. But lately the system when it refreshes the page the tickets get moved around. Take explore of picture below. 

First picture shows how the tickets look before, we change the category status. 

![Screen Shot 2019-08-05 at 9 30 28 AM](https://user-images.githubusercontent.com/47898011/62480459-c1f23780-b764-11e9-8eba-bdf3e06f8efc.png)

The second pictures shows how they get moved around once the category status gets changed. 

![Screen Shot 2019-08-05 at 9 31 01 AM](https://user-images.githubusercontent.com/47898011/62480543-f960e400-b764-11e9-8a2d-ed745f92172d.png)

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. It is working fine. Please see the video attached. 
Video link: https://drive.google.com/file/d/1IwKUWC7AHwiXIimrdl-Xr1n6eg8gngwh/view

**Comment by usmanalikhan93** [comment]
Hi again @Omar1892 - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by Omar1892** [comment]
Sorry I could not get back to you we were really busy at the store. But the issue still there. The pictures I showed you its doing what I had told you. Im going to share my credentials by email and take a look at it because it could be a bud in my account. Thank you.
