### ISSUE TITLE
Smart search parts in edit ticket 

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#894]
Suggestion: We want the search to be smarter and faster in selecting the item  of the ticket, for example when we search for a spare part for a phone that shows the search results only of the type of spare parts and not search all the stock ,just show the parts from spare parts category.

**Comment by hitman1986** [comment]
And show parts for same phone model,and then show more parts for others model,thanks for assist.

**Comment by Uzair-RepairDesk** [comment]
**Hey @hitman1986** 

This is to inform you that we have optimized the search for ticket items (parts) under the edit ticket section. Once you search from the specific keyword, systems bring the parts relevant to the device first. 
If you want to bring items from specific categories under the parts, you can go to "Manage Product Categories" and mark "Is Part" trigger to specific categories. Once you do that, all items from that category will start coming up under the parts search. 

**Please check the screenshot attached.** 

![image](https://user-images.githubusercontent.com/22955861/69785569-29cc0280-11da-11ea-9bd5-082f17d2f3cd.png)

Hope it helps

**Comment by hitman1986** [comment]
Thanks
