### ISSUE TITLE
Allow the ability to edit the default Ticket Status

### ISSUE THREAD

**Issue by BG-RLTech** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#895]
I would like the ability to change the colour of the default Ticket Status Label Colour instead of having to create a duplicate item just because i want the colour different.

![image](https://user-images.githubusercontent.com/39751801/62600552-c152d000-b921-11e9-97e9-f63510337a7e.png)

![image](https://user-images.githubusercontent.com/39751801/62600571-ce6fbf00-b921-11e9-93d4-70417c7963b1.png)

**Comment by Uzair-RepairDesk** [comment]
Hi @BG-RLTech 

Thank you for sharing your idea. However, currently, default status values are linked with specific actions along with default color codes. 
We will not be able to give an option to update the color code of default status. 

You can disable the default status if you don't want to use them and add "Custom" statuses with the specific type and colors of your choice. Hope it helps.

Thank you for your understanding.
