### ISSUE TITLE
Spares Consumption Report date issue

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#896]
Hi, Spares consumption report is shown as per ticket date and not actual spares consumption date. Let me explain further:
1. Ticket Created date - 2nd August 2019
2. After diagnosis, spares consumed on 6th August 2019
 Now this spares is shown on date 2nd and not on 6th. Actually it shud show when we search for date 6th bcos we actually consumed the spare on 6th.
![image](https://user-images.githubusercontent.com/12892217/62604541-e80b0980-b915-11e9-8eed-734c45410899.png)

![image](https://user-images.githubusercontent.com/12892217/62604576-fa854300-b915-11e9-8fc3-2d97a30a1a06.png)

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk can you please review this ?

**Comment by rajeshdungrani** [comment]
Any update

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

Thank you for your follow up. We are just back to work after religious holidays. 

Currently, date filter works according to the created date rather than the data when a specific part is associated as we recommend to auto bundle the parts with repair service when you create a ticket. 

However, I will discuss it in-house with the development team if it's possible to also apply date filter according to the part used. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

This is to inform you that we have scheduled this improvement for development. We will add new criteria to filter the records with the date when the part is consumed on the ticket. 

I will keep you posted about the progress of this improvement.

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

We have added search criteria "Part Consumed Date" based on your requirement. You can now filter the report based on the date when a part is consumed on the ticket. Please check screenshot attached 

![image](https://user-images.githubusercontent.com/22955861/65038458-70df8100-d969-11e9-8e27-cc697c0aece1.png)

Please review and share your feedback on this. Thanks

**Comment by rajeshdungrani** [comment]
Thanks you very much. I tried to download sample reports and found some descripency  Few spares not showing even if consumed on same day. For e.g I checked for 19th Sept 2019
![image](https://user-images.githubusercontent.com/12892217/65372282-700d5e80-dc8b-11e9-85aa-9c973ca77866.png)
But this part is not showing when we extract spares consumption report for 19th Sept

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 
Can you share your RD account credentials at uzair@repairdesk.co so we can verify it from your account to find the exact use case? Thanks

**Comment by rajeshdungrani** [comment]
rajeshdungrani@gmail.com
Kshem#212

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

Thank you for the credentials. I just verified from your account. "LCD Screen - Oppo A5" certainly consumed on ticket ID: 24737 at 19 September 2019. 
However, the invoice is not created yet for the same ticket. "Parts Consumption Report" is accrual-based sales report and data comes up when a sale actually happens (when you create an invoice in the system).

It will certainly come up in the report once you create an invoice for the same ticket. 

Hope it helps. Thanks

**Comment by rajeshdungrani** [comment]
Ok. But we create invoice only at the time of delivery. It should show when
I consume the spares. Is it possible to track repair ticket wise and not
invoice created

**Comment by Uzair-RepairDesk** [comment]
Currently, it's not possible without an invoice.
