### ISSUE TITLE
Wrong Customer group fetched when creating ticket

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#897]
While creating ticket thru Manage Ticket, when we search for customer, it fetches all cistomer details except the customer group. Also on saving, the customer grp changes to default grp 
![image](https://user-images.githubusercontent.com/12892217/62611177-b8aec980-b922-11e9-9765-3890cf55b0dc.png)

**Comment by usmanalikhan93** [comment]
Hi @rajeshdungrani ,

Sorry for inconvenience. This issue has been reported to the development team https://repairdesk.atlassian.net/browse/RB-367.
Its been resolved in beta  environment. We will push it on live tomorrow. 

Thanks for the patience.

**Comment by rajeshdungrani** [comment]
Have you pushed it live? Becos facing lot of inconvenience

**Comment by usmanalikhan93** [comment]
Hi @rajeshdungrani 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by rajeshdungrani** [comment]
Thank you for quick response. It is working fine now
