### ISSUE TITLE
Export Customers need details - Ticket Generated and Ticket amount

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#898]
When I am exporting customer details from manage customers, I am not getting Tickets Generated and Ticket amount
But I can see the same on screen.
Can we have the Tickets Generated and Ticket amount in the exported excel file, it will help us for analysis

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

Thank you for sharing your idea. Currently, there could be multiple tickets and invoices linked with a specific customer. With a small team and a big roadmap, we have to pick new features that are feasible for us and based on the value they’ll add to the most possible users. 

At the moment, we won’t be able to add it in RepairDesk. However, we can consider after we update our complete customer's module. 

And I hope that if there’s anything else I can do for you, you won’t hesitate to let me know. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 
Hope you are doing well 

Good News Here For You! We have implemented your desired functionality to have number of tickets and their overall value in exported file against the customers. Please review at your end and let us know if it satisfies your requirements. 

Looking forward to your response. 

Regards,
