### ISSUE TITLE
Please add (assigned to) in report by sales item

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#899]
Please add (assigned to) in report by sales item in repair ticket section in Criteria filter, To know the performance of each employee and compare them In net profit.

**Comment by Uzair-RepairDesk** [comment]
Hey @hitman1986 

I am pleased to inform you that we have added "Assignee" criteria in search filters of "Sales By Item Type" report based on your requirement. You can filter the report accordingly.
Please check screenshot attached
![uzairshah- Sales By Item Report](https://user-images.githubusercontent.com/22955861/65038218-e7c84a00-d968-11e9-825d-02b9a44dc07e.png)


Please review at your end. Thanks

**Comment by hitman1986** [comment]
Thank you
