### ISSUE TITLE
All defined Status Summary on Dashboard

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#901]
You have made a wonder Dashboard when we open Manage Ticket. I have a suggestion, if we could have all defined status update there intead of just Open, On Hold, Closed.
For e.g 
1. Under Repair - 9
2. Repaired - 10
3. Customer Approval - 5
4. Oustseide Repair - 10
5. Parts Pending - 5
 and likewise all status

![image](https://user-images.githubusercontent.com/12892217/62774762-68bb3880-bac3-11e9-8dfe-c404c2ff9c73.png)

This will help us to get the Complete status over view on the fly

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

I really appreciate that you took the time to share your idea.

I can certainly see how the suggested improvements would be useful. Currently, the idea to keep the dashboard insights simple so you can have a quick overview of open closed or on-hold tickets. There might be alot of custom statuses and we cannot exceed it with a specific limit on a dashboard area. 

l advise you to use the "Repair Status" search filter if you want to filter tickets from a specific status. You can also select multiple statuses at one time. 
Please check screenshot attached.

![AwesomeScreenshot-app-repairdesk-co-index php-2019-08-16_4_09](https://user-images.githubusercontent.com/22955861/63163926-3cae3300-c040-11e9-87fb-34619a03479e.png)

I am still marking it under "Enhancements" to we can look into the possibility to add it.
