### ISSUE TITLE
Add Payment on Action Button

### ISSUE THREAD

**Issue by JaviPlana** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#905]
I'd like you to consider to add another action (Add Payment) to the Action Button when listing ticket so, once found the ticket once the customer comes to collect their device, we can immediately do the check out. Instead of editing the ticket, make invoice, add payment as we are doing now. Unless we're doing it wrong.

**Comment by Uzair-RepairDesk** [comment]
Hi @JaviPlana 

Thank you for your suggestion. Currently, it's important to create an invoice with a ticket before you add a payment. We have a few validations on manage tickets listing page so we have options to "Make Invoice" and "Add Payment" available on Add/Edit ticket page.

We give a quick option to checkout to create an invoice from an existing ticket on "Point of Sale" screen. You can either scan the barcode, search or reopen the ticket from "View Tickets" tab. Once you reopen the ticket, you can simply click on checkout to create an invoice and add payment quickly. 

You can check the following video for your understanding:-

https://repairdesk.uservoice.com/knowledgebase/articles/921069-how-to-create-invoice-for-an-existing-repair-ticke

If you have any further question, please feel free to ask. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi, Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
