### ISSUE TITLE
Purchase order duplicating orders 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#906]
Hello, 

I was checking the re-order report for phones and I notice that it said that I have 6 phones coming in and we only order 3 device. The system is duplicating the purchase orders. But when I went to the purchase order to fix the error the 2nd order is missing and isn't showing. I checked the purchased order to see if the quantities are correct and they are. I took some screen shots of the issue. 

Im going to be gone by friday and I will back back on tuesday. If I don't get back to you guys please don't close my issue. 

First picutres is the Purchase Order 
![Screen Shot 2019-08-14 at 10 37 21 AM](https://user-images.githubusercontent.com/47898011/63043818-ccf24980-be81-11e9-91d2-1255bacdd5ed.png)

Second picture is the re-order report. And it shows that we have 6 items coming in. When we only have 3 items coming in. 
![Screen Shot 2019-08-14 at 10 43 37 AM](https://user-images.githubusercontent.com/47898011/63043876-f0b58f80-be81-11e9-979f-c121d37eeb64.png)

3rd picture is when I clicked on the number 6 to check the purchase order. And it showed two purchase number. but only one exists. 
![Screen Shot 2019-08-14 at 10 42 28 AM](https://user-images.githubusercontent.com/47898011/63043940-12167b80-be82-11e9-881a-d4da61e65f8d.png)

Second Picture is

**Comment by usmanalikhan93** [comment]
Hey @Omar1892 

Usman Ali here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 what the update on this issue?

**Comment by MuhammadAdnan32** [comment]
@Uzair-RepairDesk Issue has been explained to Fahad Bhai and he will contact the customer on live chat.
