### ISSUE TITLE
Issue with barcode reader in ipad app

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#907]
When connect barcode scanner to ipad by bluetooth, keyboard it hidden , problem of this issue when i select in keyboard language arabic and connect barcode scaner and read any barcode on ipad app ,read barcode number exambl : (٤٢٦٣٢٦) And on this version does not read the application and show me a message there is no item or ticket
Just accept numper same: (426326).
The solution to this problem is to automatically convert any barcode the reader reads into English numbers.

**Comment by hitman1986** [comment]
It is also better to always show the keyboard and not hide it when the barcode Reader connected with the iPad

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Can you please share the video to Danish ? So we can check it accordingly.

**Comment by hitman1986** [comment]
Im sended video to mr danish

**Comment by hitman1986** [comment]
It would be great!  If you have supported the barcode reader via Bluetooth properly will facilitate the work on the iPad application

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

This issue has been fixed in our new release. Once our release goes live, I will update you and you can download it. 

Thanks 
Usman Ali

**Comment by hitman1986** [comment]
Thanks, im wating the new update

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Our ipad version 4.1 is now live. You can download it and verify the fix. Do let me know if you have any question. 

Thanks 
Usman Ali.
