### ISSUE TITLE
History in ticket

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#909]
A ticket from the Limoilou shop has had activities in the history. Then, the ticket was transferred to Lévis. There were also activities in Lévis. Following this, the ticket returned to the Limoilou shop. However, we can not view the notes, system activity, history or other activity that was done in Lévis during the transfer. Although it was made in another shop, since it is a ticket originally from Limoilou, it would be appropriate to view them in order to inform the client of the development if necessary. Here is ONE example.
<img width="943" alt="limoilou view" src="https://user-images.githubusercontent.com/40500094/63285032-da914000-c282-11e9-82b3-99aecfbc5617.png">

<img width="946" alt="lévis view" src="https://user-images.githubusercontent.com/40500094/63285045-df55f400-c282-11e9-962b-2836fd03c08e.png">

--
french:
Un billet de la boutique de Limoilou à eu des activités dans l'historique. Ensuite, le billet a été transféré à Lévis. Il y a également eu des activité à Lévis. Suite à cela, le billet est revenu à la boutique de Limoilou. Cependant, nous ne pouvoir pas visualisé les notes, activité du système, historique ou autre activité qui ont été fait à Lévis lors du transfert. Bien qu'il ont été fait dans une autre boutique, puisqu'il s'agit d'un billet initialement de Limoilou, sa serait approprié de les visualisé afin d'informer le client des déveolppement si necessaire. Voici UN des exemple.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have noted down you request. We have to check the feasibility of this task with developer. I will update you once I get more information on this task. 

For internal use: 
https://repairdesk.atlassian.net/browse/RB-391

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Your reported issue has been fixed. Please verify at your end and do let us know if you have any question. 

Thanks 
Usman Ali
