### ISSUE TITLE
WooCommerce Product Sync with Variants for Serialised Inventory

### ISSUE THREAD

**Issue by jpcodev** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#910]
Hey RepairDesk Team !

I'm currently building our online store for our shop and have ran into a few issues with variant & attribute information syncing to WooCommerce.

Our Variant Info needs to sync with the WooCommerce server so we can accurately sell & track our inventory. 

You can see from the screen shot below that our retail price is directly related to the specific serial number, color, size, and condition. 

<img width="1420" alt="Screen Shot 2019-08-21 at 4 47 48 pm" src="https://user-images.githubusercontent.com/36390402/63409292-3949eb80-c434-11e9-87ed-a179a36afc5a.png">

As of right now when you sync products it does not bring over any variant information or the retail price related to the itemised inventory. 

The WooCommerce integration currently in place is built to bring over the basic information from these available product information fields including a general retail price that does not apply to our itemised inventory. 

<img width="1428" alt="Screen Shot 2019-08-21 at 4 56 26 pm" src="https://user-images.githubusercontent.com/36390402/63409633-e02e8780-c434-11e9-8010-79da08d0876b.png">

We are selling mobile phones & computers that need to be sold as single products with multiple variant options on our website. 

Please let me know if this can be added into the WooCommerce integration or I will have to search for other options so our local sales & online sales can be managed in one place. 

Thank you for your time !

I look forward to hearing back from the team.

John @ iRepairs
https://irepairsbyronbay.repairdesk.co/

**Comment by Uzair-RepairDesk** [comment]
Hi John @jpcodev 

Thank you for your post. Currently, Serialized inventory of RepairDesk is not integrated with WooCommerce. There is the following reason behind this:-

- You can manage variants of product/item by creating a serial of an item and WooCommerce doesn't allow to manage serials in default functionality. You can only create direct variants in WooCommerce. 

I will still discuss it with the development of the possibility and update you soon on this. Thank you.

**Comment by Uzair-RepairDesk** [comment]
Hey John @jpcodev 

As mentioned above, serialized inventory is not supported in WooCommerce. However, we have made the updates and you can follow the following steps to make it possible to sync serialized inventory with RepairDesk.

1: Once you sync items/products from RepairDesk to woocommerce website, you can create variants of each item manually from your website. You can check the following video to manage variable product on woocommerce website
https://www.youtube.com/watch?v=Lalb-8G05Z8

2: Once you customer purchase the item from the website and you ship the product serial item, you can note it down 

3: Once the invoice is created on RepairDesk from your online sale, you can go Manage Invoice > Edit Invoice > "Select the same" serial under the Qty and Save Invoice. 

It will update the status of the serial to sold.

By following the above steps, you can manage and keep syncing your serialized inventory with woocommerce website. 

Hope it helps. Thanks

**Comment by jpcodev** [comment]
Hi Muhammad,

Thank you for outlining the current process of the way that WooCommerce integrates with RepairDesk.

The main issue I’m facing now is that when a serialised phone with multiple variants is sold in our local store it will only remove the total amount of phones available.

For example when a iPhone 7  | 32gb | Black | A grade | is sold in store it will change the WooCommerce level from 10 - 9. If a customer were to purchase the same exact iPhone online before the variant stock level is manually updated on the website then we would not be able to provide the customer with the phone they purchased.

Do you have any plans in the future of the Product Sync working with multiple variant conditions applied ?

https://www.vendhq.com/au provide this ability with Shopify and their Point of Sale / back end system.

Thanks,
John

On 3 Sep 2019, at 10:53 pm, Muhammad Uzair Shah <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey John @jpcodev<https://github.com/jpcodev>

As mentioned above, serialized inventory is not supported in WooCommerce. However, we have made the updates and you can follow the following steps to make it possible to sync serialized inventory with RepairDesk.

1: Once you sync items/products from RepairDesk to woocommerce website, you can create variants of each item manually from your website. You can check the following video to manage variable product on woocommerce website
https://www.youtube.com/watch?v=Lalb-8G05Z8

2: Once you customer purchase the item from the website and you ship the product serial item, you can note it down

3: Once the invoice is created on RepairDesk from your online sale, you can go Manage Invoice > Edit Invoice > "Select the same" serial under the Qty and Save Invoice.

It will update the status of the serial to sold.

By following the above steps, you can manage and keep syncing your serialized inventory with woocommerce website.

Hope it helps. Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi John @jpcodev 

I understand your concern. Since we have integrated with a third-party platform, we are restricted with this. Perhaps, Shopify allows doing that however, WooCommerce doesn't allow to sync serialized inventory variants. 

Our idea to integrate with woocommerce is that you can manage your online stock by keeping it sync with RepairDesk and also you can track your online invoice. 
With the above certain requirement, you can follow the steps I suggested above and proceed with the manual tracking for now in this case. 

I hope you can understand our situation. Thanks.
