### ISSUE TITLE
Quick Improvement - Additional Identifier for Devices

### ISSUE THREAD

**Issue by jpcodev** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#911]
Hey Team !

I was hoping that you guys could code in an additional information field or control group for the individual "devices" back end. Currently the only way to " look up " devices through our point of sale is by attaching model numbers to the end of the Device Name. We work with iPhones & Macbook Computers that have multiple model numbers for the same devices.

<img width="739" alt="Screen Shot 2019-08-21 at 5 13 53 pm" src="https://user-images.githubusercontent.com/36390402/63410631-166d0680-c437-11e9-8273-ddb2a0069871.png">

These could be solved by simply adding an additional field or control group on your devices back end.

Manufacturer*
Device*
Model* <- proposed identifier 
<div class="control-group"><label class="control-label" for="Model">

<img width="1294" alt="Screen Shot 2019-08-21 at 5 09 34 pm" src="https://user-images.githubusercontent.com/36390402/63410857-98f5c600-c437-11e9-8432-d91bd4fb3c3d.png">

Thank you for your time ! 

John @ iRepairs
https://irepairsbyronbay.repairdesk.co/

**Comment by Uzair-RepairDesk** [comment]
**Hi John @jpcodev ,**

Thank you for your suggestion. I can certainly see how suggested improvements would be useful in your case. 

Currently, our device workflow is dependent on the Manufacturer. If it's really important for you to log the "Model" of the device, you are using the right way with respect to the data required for the ticket for now. 
We will not be able to add additional identifier with a current scope however I want to update you that we are working on "Custom Fields" option based on repair category that will allow you to add a custom field and you can provide input while booking a repair ticket. 
We are expecting to make this feature LIVE soon. 

Once we make it LIVE, you can simply keep the device with a name like "iPhone 5C" and then you can enter model easily with a custom field. 
**Please check screenshots attached**

![JM1 - POS](https://user-images.githubusercontent.com/22955861/63433834-5e8f2780-c43d-11e9-94c3-3185894f0aae.png)

![JM1 - POS1](https://user-images.githubusercontent.com/22955861/63433844-63ec7200-c43d-11e9-9393-cd774f9b62ae.png)

**Comment by Uzair-RepairDesk** [comment]
Hey John @jpcodev 

This is to inform you that we have made "Custom features" LIVE. You can proceed to update the "Device Model" field against relevant categories. You can log the model number while booking a repair ticket (as suggested above in the screenshot).

You can find more details regarding custom fields functionality from following knowledgebase article (you can also watch a video for your understanding). 
https://repairdesk.uservoice.com/knowledgebase/articles/1921693-custom-fields

Hope it helps. If you still have any questions/concerns please feel free to ask. Thanks. 

Regards,
Uzair from RepairDesk.
