### ISSUE TITLE
issue withe epson printer

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#913]
im sended report of issue and video to mr danish from since 1 month, please slove it

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

Let me check with Danish and he will update you further.

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I believe Danish has updated you on live chat. Do let me know if you have any question.
