### ISSUE TITLE
Unrepaired Devices Status

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#914]
Currently when we do checkout, the final status comes is "Repaired and Collected". Now there are cases where devices are Unrepaired and Collected. How do we get this status

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

Hope you are well. Repaired & Collected option on the checkout page is to facilitate the customer's to quickly mark it when you checkout, handover the device and take payment from the customer.

In your above case, I will recommend you to mark the status of a ticket to "Canceled" or you can add and mark a custom status "Unrepaired & Collected" with type "Closed. You can mark the status from Manage ticket /view or edit screen or you can reopen the ticket on POS and update the status. 

Now, when you check out the same ticket you can simply select "No" in "Repaired & Collected" option so it will keep the same status of the ticket. 

Hope it helps.

**Comment by rajeshdungrani** [comment]
Ok. Thanks for the workaround
