### ISSUE TITLE
Ticket Items (Repair Parts Being Used) Serial numbers missing 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#919]
Hello, 

It seems that you guys updated the ticket section in the repair category. I just notice that the serial numbers aren't showing up when the parts have being selected in the repair ticket. Before it was showing the serial number that we had to choose for the repair now it isn't showing anything and we don't know what serial number to get. We keep 80%-90% of our inventory serialized and it was extremely helpful to see what serial number we had to get to do the repair to keep our inventory organized as well as the serial number. 
![Screen Shot 2019-09-03 at 9 19 43 AM](https://user-images.githubusercontent.com/47898011/64192381-6385ab00-ce2f-11e9-999e-3b4fdeca1212.png)

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
For internal use:
https://repairdesk.atlassian.net/browse/RB-418

**Comment by kristan79** [comment]
That is not the only issue.  You are able to select the serial number to be used but it is staying in inventory showing still "On HAND"

**Comment by usmanalikhan93** [comment]
Hi @kristan79 

Thank you for bringing this to our attention. We have reproduced this issue and it is coming from Manage ticket section. Kindly use POS for the time to attach serial part with problem. I will let you know once this issue will be fixed. Your cooperation will be highly appreciated. 

Thanks 
Usman Ali

For internal use: 
https://repairdesk.atlassian.net/browse/RB-420?oldIssueView=true

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 @kristan79 

I hope you both are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by Omar1892** [comment]
Its fixed. Thank you!
