### ISSUE TITLE
In-Stock Inventory Issue

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#920]
Hello, 

the in-stock inventory is been miscount counted. It shows that we have 0 items in stock with 1 item serialized. We do have the item in stock and the serial number that is been displayed is correct to the item that we have in-stock. This has been happening for the last couple of weeks. The other thing it was doing yesterday it was that it was going to 1 item in stock with 1 item serialized to with in couple of hours it went to 0 items in stock with 1 item serialized. 
![Screen Shot 2019-09-04 at 1 56 42 PM](https://user-images.githubusercontent.com/47898011/64291138-48449980-cf1c-11e9-802a-c0ac6b41dab8.png)

**Comment by MuhammadAdnan32** [comment]
@Omar1892 Please, Can you share your RD credentials? So I can check it on your account. Thanks

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-420

**Comment by Omar1892** [comment]
Information has been sent to the email you sent me.

**Comment by MuhammadAdnan32** [comment]
I have received your you email. Sure thing! Let me take a look and I'll circle back to you. Thanks

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by Omar1892** [comment]
Hello, still saying that I have 1 item serialized and 0 instock. Should I just updated the inventory and let you know if it happens again?

**Comment by MuhammadAdnan32** [comment]
Hi,
Yes Omar, you need to update it manually. We have fixed this issue and it
don't happen again. And let us know if you have any query.Thanks,
Regards,
Repairdesk QA
