### ISSUE TITLE
Send Invoice Oustanding Reminder to multiple customers at a time

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#921]
Currently we have to send Invoice Outstanding Payment to individual customer. But we need option to send Outstanding reminder to multiple or all customers at a time. Can we have such option.

**Comment by Uzair-RepairDesk** [comment]
Hi @rajeshdungrani 

Thank you for your post. Yes, you can certainly send an "Invoice Reminder" to multiple customers at one time. 

You can use the following steps to enable this functionality. 

1: You can go to Store Settings > Module Configurations > Invoices > Enable trigger "Enable partial/UnPaid Invoice Reminder".

2: You can go to Manage Invoices, filter unpaid/partial paid invoices to send reminders to customers

3: Select multiple invoices of your choice > Click on Actions > Send Reminder > You can edit the content and click on Send

It will send an email to customers relevant to invoices. 

You can also set the default content for an invoice reminder email from Store Settings > Email & Notifications > Invoices > Update 'Remind customer when invoice has passed due date' 

You can details from following knowledgebase article:-
https://repairdesk.uservoice.com/knowledgebase/articles/1859353-how-can-i-send-multiple-invoice-reminder-to-custom

Hope it helps. Thanks
