### ISSUE TITLE
Pre/post device condition 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#922]
Hello, 

We have been having an issue with the Pre/Post Device condition. When ever we add a new item to a repair on a existing ticket 2 pop up screen apear. 1 to write notes and the second one is the Pre/post device condition. The Pre/post device condition we have it set up to do the Toggle selection, but when it apear it doesn't give me any option to mark the part as if its working or not it only shows a check mark box and thats it. 2nd issue, to add the repair to the ticket we have to do the Pre/post device condition as its mandatory in the store, since the issue pops up it won't let us add the repair to the ticket. So what we figured out is that we can just add it by saving the ticket. Basically a lot of issues are happening at once when ever we try to add a new repair to an existing ticket. One other thing once we're able to add the part to the ticket and we try to test the device since it didn't let us do it before hand. The Pre/post device condition comes up blank. This happens when we do the Pre/post device condition from the Action button in the ticket section. 
![Screen Shot 2019-09-06 at 11 25 49 AM](https://user-images.githubusercontent.com/47898011/64456072-2d049600-d0a4-11e9-9dcb-1d54f61154dd.png)
![Screen Shot 2019-09-06 at 11 25 09 AM](https://user-images.githubusercontent.com/47898011/64456074-2d049600-d0a4-11e9-97db-9428386ec1e6.png)
![Screen Shot 2019-09-06 at 11 25 24 AM](https://user-images.githubusercontent.com/47898011/64456075-2d049600-d0a4-11e9-9551-d83d0676ad02.png)

**Comment by usmanalikhan93** [comment]
Hey @Omar1892 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-430

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. Your reported issue has been fixed. Do verify at your end and do let us know if you have any question. 

Thanks
Usman Ali
