### ISSUE TITLE
Problem with employees commission !

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#923]
-- Employee commissions still do not work. Look at this example. Stacey created the L-14604 ticket at the Limoilou store. There is no accessory, only a repair. Repair commissions are set to 1%. It was the Sybile employee who did the repair. The ticket has been assigned to Sybile. Stacey billed and paid with the client (Invoice FL-18997). The commission for the repair goes to Stacey. however, she should go to Sybile since she did the repair. See picture of Stacey's ticket history and commission statement.
<img width="944" alt="history L-14604" src="https://user-images.githubusercontent.com/40500094/64628523-8c71e700-d3bf-11e9-8a52-ac9ed7ba36dc.png">
<img width="945" alt="commission report Stacey" src="https://user-images.githubusercontent.com/40500094/64628618-b5927780-d3bf-11e9-9df9-152db2380418.png">

-- Same for L-14609 and FL-19003. Ticket assigned to Sybile but commissions go to Stacey instead of going to Sybile.
<img width="940" alt="history L-14609" src="https://user-images.githubusercontent.com/40500094/64628941-508b5180-d3c0-11e9-8831-adc3f4e046a2.png">
<img width="938" alt="Stacey commission report L-19003" src="https://user-images.githubusercontent.com/40500094/64629070-892b2b00-d3c0-11e9-9e99-eb68a331dabb.png">

-- in addition, when we look at employee commissions, the totals of all employees add up each time we add an employee by selecting them. the total of each employee thus becomes the total of the commissions of all the employees together. As if all employees have made the same repairs and sales. See picture.
<img width="937" alt="few employes commisisons report" src="https://user-images.githubusercontent.com/40500094/64629678-a7455b00-d3c1-11e9-8539-970ea6c17dac.png">

-- It's the employee Simon who has done the most repair and it is he who has the least commissions for the month of August. Employees are paid on commission, so how can I trust it if it's not good information?

--
French: 
Les commissions des employés ne fonctionne toujours pas. Regardez cet exemple. Stacey a créé le billet L-14604 à la boutique de Limoilou. Il n'y a aucun accessoire, uniquement une réparation. Les commissions des réparations sont configuré à 1%. C'est l'employé Sybile qui a effectué la réparation. Le billet à été assigné à Sybile. Stacey a faire la facture et a procédé au paiement avec le client (Facture FL-18997). La commission pour la réparation va à Stacey. pourtant, elle devrait aller à Sybile puisque c'est elle qui a effectué la réparation. Voir image de l'historique du billet et le relevé de commission de Stacey.

Même chose pour le billet L-14609 et la facture FL-19003. Billet assigné à Sybile mais les commissions vont à Stacey au lieu d'aller à Sybile.

de plus, lorsque nous regardons les commissions des employés, les totaux de tous les employés s'additionne à chaque fois que nous ajoutons un employé en le sélectionnant. le total de chaque employés devien donc le totaux des commissions de tous les employés ensemble. Comme si tous les employés ont fait les mêmes réparations et ventes. Voir image.

C'est l'employé Simon qui a fait le plus de réparation et c'est lui qui a le moins de commissions pour le mois d'août. Les employés sont payé à commission, alors comment je peux m'y fier si ce n'est pas les bonnes informations?

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by MuhammadAdnan32** [comment]
Hey! @JessicaSOS 
-Employee commissions are working fine. I have checked in you account and found that you have enabled this triggers "Commission is splitted between technician and a sales person who books a repair job" that's why it is showing you commission for both. 
![Setting-Employee-commison2](https://user-images.githubusercontent.com/50608942/64758634-83fbe680-d54e-11e9-95a2-10430b6b06bf.png)
![Setting-employee1](https://user-images.githubusercontent.com/50608942/64758638-8a8a5e00-d54e-11e9-9f6e-ab4a23c1c634.png)
I have checked this on your account and it looks like it is working fine. 
-We have an issue with My Commission report Employee filter.
Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information!

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-434

**Comment by MuhammadAdnan32** [comment]
Hey @JessicaSOS ,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have a question.

Thanks!

**Comment by JessicaSOS** [comment]
Sybile had no commission and she did the repair. I understand that you give 1% commission, but it is to Sybile that it should have gone, it is she who made the repair!

--
French:
Sybile n'avait aucune commission et c'est elle qui a fait la réparation. Je comprend que vous donnez 1% de commission, mais c'est à Sybile que sa l'aurait du aller, c'est elle qui a fait la réparation!

**Comment by usmanalikhan93** [comment]
@MuhammadAdnan32 can you please check ?
