### ISSUE TITLE
Price display - Retail and SALE

### ISSUE THREAD

**Issue by MirkazFMP** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#926]
Hi, 
I need retail and sale price to be displayed same time on the calendar widget.

like : 
retail : 100 USD
Sale : 75 USD
Discount : 25%

Beeing able to translate (Retail, Sale, Discount from language addon in Widget tab)

**Comment by Uzair-RepairDesk** [comment]
![Retail-and-sales-price-update-1](https://user-images.githubusercontent.com/22955861/65868067-05e27100-e391-11e9-8d50-139b7a977b03.jpg)

**Comment by MirkazFMP** [comment]
OK for me, please make sure i can translate 
"Retail Price"
"Sale price"
In Translator in Apointment calendar widget tab !
Thanks

**Comment by Uzair-RepairDesk** [comment]
Hi @MirkazFMP 

I am pleased to inform you that we have made your requested improvement LIVE in our release. 
Once you set the sale price and enable the trigger "Enable Sale Price if applicable" under configurations of "Appointment Calendar Widget", your customers will be able to view Sale price along with the retail price. 

![uzairshah - Bookrepair Config](https://user-images.githubusercontent.com/22955861/68022344-e6a76e00-fcc5-11e9-9cbe-3af25b1a002b.png)

Please review it at your end. Thanks
