### ISSUE TITLE
Repairs Description - WYSIWYG

### ISSUE THREAD

**Issue by BG-RLTech** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#929]
Can you make the description field in repairs formatable. 

If you put spaces or line spaced currently it disregards those and just puts is continuos. Are you able to make it formattable so we can centre, skip a line, bold, italic etc?

**Comment by MuhammadAdnan32** [comment]
Hey BG-RLTech ,
Can you please share an image or video with us where you are referring?
Regards,
Repairdesk QA,

**Comment by usmanalikhan93** [comment]
Hi again @BG-RLTech - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by BG-RLTech** [comment]
Hey Usman, no it hasnt been rectified i was just busy and couldnt update. In an individual repairs item you can write a description as below.

It would be best if all formatting in this description replicated what shows on the website widget. It would be great if this field allowed formatting like bolding text etc. 

When it displays on the widget it ignores any formatting which is slightly annoying.
![image](https://user-images.githubusercontent.com/39751801/66004420-5bc33000-e4db-11e9-9c83-a243e619996a.png)
![image](https://user-images.githubusercontent.com/39751801/66004438-6aa9e280-e4db-11e9-8772-ba0494215b9f.png)

**Comment by usmanalikhan93** [comment]
Hi @BG-RLTech 

Thanks for the information. Let me check this on my end and report it to development team. I will update you once it will be live. 

Usman Ali

**Comment by usmanalikhan93** [comment]
For internal use: 
https://repairdesk.atlassian.net/browse/RB-500

**Comment by usmanalikhan93** [comment]
Hi @BG-RLTech 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
