### ISSUE TITLE
Default Status "Waiting"

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#930]
When creaeting a new ticket, if no status is assigned then a default status "Waiting" is assigned. Now the issue is I cannot search for these "Waiting" status calls as there is no filter available to check it. Need option to get default Status or a filter to search such "Waiting" status

**Comment by afnanforex** [comment]
Hello Rajes, I just want to update you about the "waiting" status in Manage tickets section. I discussed with my team.
If you create ticket then status by default will be "In Progress". Once you open ticket in edit mode and left blank the ticket status field. It will become "waiting". So I will recommend please do not left blank ticket status field.
To sort this out you can create custom ticket status named as "waiting" than this status will be present in filters as well. By doing this you can identify all the ticket which have status "waiting".

**Comment by usmanalikhan93** [comment]
Hi again @rajeshdungrani  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
