### ISSUE TITLE
Dashboard items - Clickable

### ISSUE THREAD

**Issue by rajeshdungrani** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#931]
You have a veru wonderful dashboard. To make it more friendly, you can make all items clickable where we can get the report on clicking the item.
![image](https://user-images.githubusercontent.com/12892217/65954988-c2f1cd80-e464-11e9-8a76-14a9a8657e31.png)

**Comment by Uzair-RepairDesk** [comment]
Most of the legends are clickable to explore the relevant data.
