### ISSUE TITLE
Costumer Facing Display 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#932]
Hello, 

When opting for the costumer to enter their personal information such as phone number and name. The iPad will display the information on the screen but when it get successfully saved on my computer the costumer info doesn't show up. This happens on 2 computers.

**Comment by MuhammadAdnan32** [comment]
Hey Omar1892, 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you. Thanks

**Comment by MuhammadAdnan32** [comment]
Hey Omar1892,
Its working fine for me. Could you please share a video or detailed steps to reproduce the issue? 
Thanks

**Comment by Omar1892** [comment]
/var/folders/w4/w40bg7vs1kz5_wfnlh63wr580000gn/T/com.apple.iChat/Messages/Transfers/IMG_3155.mov

**Comment by Omar1892** [comment]
I sent an email of the issue that Im having to usmanalik93@gmail.com

**Comment by Omar1892** [comment]
Do you have any updates? Its slowing us down when were booking in the repair.

**Comment by Omar1892** [comment]
Do you have any updates? Its slowing us down when were booking in the repair.

**Comment by Omar1892** [comment]
Do you have any updates? Its slowing us down when were booking in the repair.

**Comment by MuhammadAdnan32** [comment]
Its working fine for me and I have check this on the customer account as well. I have discussed this with the support team and they will contact the customer.

**Comment by fahadimran303** [comment]
Had a discussion with him. He said he will test that again and the issue will be fixed.

**Comment by Omar1892** [comment]
The issue still there. No fix. I tried it with 2 different iPads and the issue still there. Use an iPad and my account to recreate the issue other wise the issue will not be fixed if you have not done so.

**Comment by Omar1892** [comment]
Can you guys take a look it at. Its causing us a lot of issues. I know you guys have mentioned that it works on your side but I wound't be WASTING MY TIME letting you guys know that something isn't working when it is. Ive been reporting this issue since 27 days ago and its really frustrating that this hasn't been fixed and that its taking you guys so long to fix this issue!

**Comment by fahadimran303** [comment]
Jira Link:
https://repairdesk.atlassian.net/browse/RB-573

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
