### ISSUE TITLE
Serialized Merchandise Condition Selection 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#933]
When a GRN is created and the option to create a serial number is chosen it gives you the option to select the condition the product is in. The system isn't given us that option when option to select the condition of the product in the GRN. The system is only given us the option to add a condition description once the item is in the added to the system and you go to the inventory for the item and the item get edited. 
![Screen Shot 2019-10-04 at 11 46 44 AM](https://user-images.githubusercontent.com/47898011/66232126-fdde4600-e69c-11e9-8f6e-1142d311ed86.png)
![Screen Shot 2019-10-04 at 11 45 25 AM](https://user-images.githubusercontent.com/47898011/66232127-fdde4600-e69c-11e9-9656-5739fd8db57d.png)

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892, 
Adnan here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks

**Comment by MuhammadAdnan32** [comment]
Hey!  
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! Thanks

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-520

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 

I hope you are doing well. I have discussed with my development team, it's not a bug. It looks like it's an improvement. I will discuss this with the product manager about this functionality and will update you in 12 - 24 hours.
Thanks

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892,
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have a question.
Thanks!
