### ISSUE TITLE
Inventory Count 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#934]
On Inventory Count the system isn't recognizing that some item are missing when ever the count is paused. It only recognizes that items are missing when you look at the Unmatched item report. Today it only showed that 2 items are missing when it was 3 items that where missing. Yesterday it didn't on a bigger scale it was showing that 2 where missing but after checking the other report it was 10 items missing. 
![Screen Shot 2019-10-04 at 12 15 00 PM](https://user-images.githubusercontent.com/47898011/66234009-80690480-e6a1-11e9-8427-47e7f910fbc0.png)
![Screen Shot 2019-10-04 at 12 15 13 PM](https://user-images.githubusercontent.com/47898011/66234021-865ee580-e6a1-11e9-81d8-caf60465196e.png)

**Comment by MuhammadAdnan32** [comment]
Hey Omar1892, 
Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.Thanks

**Comment by MuhammadAdnan32** [comment]
Hey! Omar1892,
Can you please elaborate more on the issue as its working for me?
Thanks

**Comment by Omar1892** [comment]
When im doing an inventory count and I paused the count on the home screen of the inventory count it gives you the items that are missing if any. Well the item that aren't missing isn't the right quantity of items that aren't missing. How do I know this is because when you start counting item by item on the report you can start to notice that their are more than what the report is showing in missing items. This could be going on, on my account because of the old account I didn't have this issue. If you want I can send you my account email and password you can test it your self. But the issue is there for sure. It happen on all the inventory counts I did that day.

**Comment by Uzair-RepairDesk** [comment]
Hello 👋  
 @Omar1892 Omar
Just wanted to double-check and see if you can share a video of what you're seeing here so I can see exactly what is happening on your end. Thanks!

**Comment by Omar1892** [comment]
Ill share a video by tomorrow. We aren't doing an inventory count until than.

**Comment by MuhammadAdnan32** [comment]
I have discussed this issue with support team and he will contact the customer.

**Comment by fahadimran303** [comment]
We will have a session on Wednesday, 30th Oct in order to troubleshoot.

**Comment by Uzair-RepairDesk** [comment]
What's the update on this @fahadimran303 @MuhammadAdnan32 ?

**Comment by fahadimran303** [comment]
I had a session yesterday however we were not able to reproduce the issue.
Will check in next week.
