### ISSUE TITLE
GRN Received Notes

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#936]
When ever we get new inventory we have to count everything manually and make sure that all items arrived match the GRN. This takes a long time depending one how big the order we made is. Instead of counting everything manually it would be a good idea if you guys can add a box where we can scan the items that arrived and once scanned the received quantity can get updated with the items that just arrived. The search box could be similar to the inventory count box where when ever you scan an item it comes up, but in this case when ever we scan an item it will be counted on the GRN.

**Comment by Uzair-RepairDesk** [comment]
We have introduced an option to scan the barcode in GRN to receive the quantity of the items
