### ISSUE TITLE
add/remove fields at the add new customer page

### ISSUE THREAD

**Issue by gijoe911** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#941]
is it possible to add/remove fields at the add new customer page on the ipad app?

for example the "select network" for me is almost useless because it's not really an attribute. so instead could i change that field into something like gender or age range? that way i could capture more info about my customers and do better analysis.
![WeChat Image_20191010155357](https://user-images.githubusercontent.com/25240657/66549631-45217680-eb76-11e9-8c30-eedefacfeb89.jpg)

**Comment by Uzair-RepairDesk** [comment]
Hi **@gijoe911**
I really appreciate that you took the time to share your ideas. Currently its not possible in iPad app to add/edit default fields while adding customer. 

I have noted it down as an enhancement and we will definitely try to take this up for you in next quarter. Meanwhile if you came across more suggestions, please don't hesitate to list them out on this platform. Customers like you who make such suggestions are the real reason behind the success of company and are true assets for us. 

Meanwhile your cooperation on it will be highly appreciated!

**Kind regards,**
