### ISSUE TITLE
Trade in - Barcode scanning

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#943]
Hello! When I print the barcode for trade in items it is scanning as the SKU. Can i change this to be only the item number?

**Comment by Uzair-RepairDesk** [comment]
I believe by default, barcode should be generated on the basis of IMEI/Serial of the device in trade-in. Your thoughts @Repair-Desk ??

**Comment by Uzair-RepairDesk** [comment]
We already informed the customer.
If there is SKU, the system generates barcode on the basis of SKU and if there is no SKU, system automatically generates barcode on the basis of item ID.
