### ISSUE TITLE
Supplier/Vendor

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#944]
Hello, 

After you guys upgrade my account to a new account the vendors in all of the items for sale that we have didn't get added. Witch is causing us an issue with placing orders and other inventory issues. If possible can you guys get it fixed ASAP because to place an order we have to go through all the sales reports to see what has sold during the past weeks.

**Comment by Uzair-RepairDesk** [comment]
Hey @Omar1892 
I will ask Fahad to give you a call on this so he can assist you with your concern.

**Comment by Omar1892** [comment]
Ok thanks.

**Comment by fahadimran303** [comment]
We have already done a call yesterday. It will be sorted out today.

I will update this thread once done.

**Comment by fahadimran303** [comment]
Call has been. Close this task.
