### ISSUE TITLE
warranty period imported not aligned with ipad POS

### ISSUE THREAD

**Issue by gijoe911** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#946]
there’s an issue with the warranty period imported in the device issues not aligning with the warranty period in the iPad pos. can we please look into this because staff will forget to enter in the warranty period manually. thanks

**Comment by Uzair-RepairDesk** [comment]
Hi **@gijoe911** 
Thanks for listing down your concerns. I have checked this with development team and certainly its an improvement to align warranty period against imported items with iPad app. We will be happy to take this up for you after the launch of Offline Mode Version for iPad which will definitely be valuable for your business and will not disturb your workflow in absence of internet connection. 

Thank you for your patience and understanding through some of the bumps in the road – I am working with our development team to make sure we make these improvements more quickly and provide you with better experience with our iPad app. 

**Kind regards,**
