### ISSUE TITLE
Issue when  edit  stock warnin

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#949]
Thank you for modifying the inventory warning without having to enter each item , but there is a problem that I cannot modify and activate items that were not activated before, and when I edit from empty qty( value) to any number I get an error message

**Comment by MuhammadAdnan32** [comment]
Hi @hitman1986,
Could you please share a video or detailed steps to reproduce the issue?
Thanks

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**Comment by hitman1986** [comment]
Im sended video to mr danish

**Comment by usmanalikhan93** [comment]
Thanks @hitman1986. @MuhammadAdnan32 can you please check this ?

**Comment by MuhammadAdnan32** [comment]
Hi @hitman1986 ,
I have checked it, the system doesn't allow to update reorder level and stock warning when on-hand is zero. If you have items in stock then it will be working fine for you. We advise you to set reorder level and stock warning when you have on-hand quantity of more than zero.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,

**Comment by hitman1986** [comment]
Thank you for assistants im sended another video to mr danish to explain this issue.

**Comment by MuhammadAdnan32** [comment]
Hi @hitman1986,
Adnan here! Thanks for sharing another video.Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-618

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali

**Comment by hitman1986** [comment]
Yes thank you it working
