### ISSUE TITLE
diagnose photo to send customer ( for example water damage)

### ISSUE THREAD

**Issue by smartfastfix** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#950]
warranty repair:
customers breng to us their device after we chance screen( after 1 week ....etc)they say device doesnt start so we make diagnose but there is water inside so we make photo but we cant send photo directly to customer otherwise they say no water en we get problem with customer.
Samsung service use same model if we send device to warranty they make foto end send us end then we show photo to customer

**Comment by Uzair-RepairDesk** [comment]
**Hi @smartfastfix** 
Thank you for your post.

We don't have a direct option to send a photo to the customer within RepairDesk, however, there is following workaround functionality y**ou can follow to make it happen according to your workflow needs**.

**1:** We have a **"Pre/Post Device Image" feature that allows you to upload "Pre and Post" images of the device in a ticket**. Once you diagnose the device, you can take the photo and upload it under Pre condition images. Similarly, you can upload it on the ticket once "Samsung Service" send you the images of the device.
You can check following knowledgebase article for your understanding:-

[1: How I upload the device Pre or Post repair device condition image against a repair ticket?](http://help.repairdesk.co/knowledgebase/articles/921930-can-i-upload-device-pre-or-post-repair-device-cond)
[2: How I upload the device Pre or Post repair device condition image against a repair ticket from iPad POS Register](http://help.repairdesk.co/knowledgebase/articles/1921105-how-to-upload-pre-post-repair-images-from-ipad-pos)

2: Once you have the image, You can click on it. **Right-click and you can copy the image path.**
**Check screenshot attached**

![copy image address](https://user-images.githubusercontent.com/22955861/67364804-b22b0800-f589-11e9-8934-0c6cde6ff46d.png)

3: Once you have the image path, you can go to the **"Email/SMS**" section of the ticket, you can draft an email or keep a canned response. Along with that, you can **paste the image path in the email** to send it to the customer. 

![email to customer](https://user-images.githubusercontent.com/22955861/67365475-2a45fd80-f58b-11e9-8f2a-16578d135bdc.png)

![email](https://user-images.githubusercontent.com/22955861/67365482-2d40ee00-f58b-11e9-8f56-fb4bddf1669e.png)

You can review it and if you have any questions, please feel free to ask. Thanks. 

**Regards,
Uzair**

**Comment by usmanalikhan93** [comment]
Hi again - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!
