### ISSUE TITLE
Add more than one devices to the ticket

### ISSUE THREAD

**Issue by gsmgps-star** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#951]
hi.

it would be great if can add more than one devices and manufacturer in to ticket order?

regards

**Comment by Uzair-RepairDesk** [comment]
Hi @gsmgps-star 
You can certainly add multiple devices into one ticket.

You can go to Manage Tickets > Edit Ticket > Add New Line under 'Device Details' > Save
![Update Ticket](https://user-images.githubusercontent.com/22955861/67566751-feb94380-f741-11e9-8a01-b056fe75c572.png)

If you have any questions, please feel free to ask. Thanks

**Comment by gsmgps-star** [comment]
ok tnx.
i will try yours method :-)
tnx
