### ISSUE TITLE
Serial numbers are not being marked as USED 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#953]
Hello, 

The serial number are still not being marked as used, Ive had this issue in the past and I was told that it was fixed but it still happening. We started noticing this issue when we started using the Purchase order and GRN. I took video of the issue, I will send it throughs the chat. This issue won't happen on the first try, this issue happens randomly. 

This is causing us a big issue because, yesterday we were booking in 2 repairs on the same model and color device. The system showed us that we had to serial in stock but we did not notice that their was only 1 part in stock. Since the part wasn't marked as not in-stock we proceeded with the repair. Once we had the phones take apart we found out that their was only 1 item in stock but 2 serial numbers in-stock. We had to put 1 of the phone back together and the costumer wasn't happy. I don't blame them because they had already left the store and plus we lost the repair.

**Comment by MuhammadAdnan32** [comment]
Hey @Omar1892 , 
Adnan here Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks

**Comment by Omar1892** [comment]
I think that the issue is coming from the PO and GRN. The system is creating more serial numbers than what we are actually having on hand. The serial number are created on the GRN when new inventory comes in and we are sure to count all the inventory.

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892,
Thank you for bringing this to our attention! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share a video of this issue so we can release a fix during our next release. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks

**Comment by Omar1892** [comment]
Thank you for checking. But theres basically no way for me to recreate something that happens randomly in any random part category. Instead of recreating the issue on your side, once this happens you can login in to my account and you can check the issue your self. Because we can't be removed part and serial number for no reason. If this issue is happening on my account and im reporting it for the last couple of months It is happening and I need it to be fixed.

**Comment by usmanalikhan93** [comment]
@MuhammadAdnan32 please check

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892,
I have double-checked it at my end. But unfortunately, I am not able to reproduce your issue at my end. Can you please check it again at your end? If the issue still persists, please help us to replicate the issue.
Thanks

**Comment by Omar1892** [comment]
@MuhammadAdnan32 I have sent a video to Usman Ali Khan

**Comment by Omar1892** [comment]
Hello, I think I know where the issue is coming from. Its coming from the RMAs. When an RMA is created we mark it as Sent to Supplier so that the part and serial number would be removed from the inventory instock. What I notice the system has being doing in some cases it removes the serial number from the inventory in stock but it won't update the inventory in-stock. And in most other cases it removes both it updates the quantity in-stock + the serial number.

**Comment by MuhammadAdnan32** [comment]
Hi omer1892,

Adnan here 👋 Sure thing! Let me take a look to see if I'm getting the same
issue as you and I'll circle back to you. Thank you for bringing this to
our attention!

Thanks,

Regards,

Adnan

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
I have checked your concern but unfortunately, I am unable to reproduce your issue. And it's working fine for me. Kindly avoid using zero on-hand part with the ticket that creates a hurdle for you. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out. Be sure to let us know if there's anything we can do to make it even better :)
Thanks

**Comment by usmanalikhan93** [comment]
Hi again @Omar1892  - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali
