### ISSUE TITLE
Unlocks not marked as Repair & Collected 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#954]
Hello, 

To unlocks phone we use a third party vendor and not the vendors you guys have on the integrations. So when ever we book in a repair and the costumer comes to pick the device up, it doesn't get marked as repaired and collected once we check out. We have to do it manually and we have to ask the staff to see if it was repair and collected because the system doesn't updated the ticket once the invoice is paid for. Can you guys fix that so that we take a payment for unlocks it will update to Repaired and Collected?

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 

I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks

**Comment by MuhammadAdnan32** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-599

**Comment by Omar1892** [comment]
Ok, thanks.

**Comment by usmanalikhan93** [comment]
Hi @Omar1892 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
