### ISSUE TITLE
Phone accessories aren't being removed from inventory 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#957]
A phone case was sold with ticket T-60 but the case was not removed from the inventory when it was purchased. The item was removed manually. Please check the records below. 
![Screen Shot 2019-11-13 at 3 18 06 PM](https://user-images.githubusercontent.com/47898011/68812968-3fadc500-0629-11ea-89c7-f1c1c1fb2515.png)

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892,
I have checked your concern but unfortunately, I am unable to reproduce your issue. Would be great if you can share more details or a video of this issue so we can release a fix during our next release.
Thanks

**Comment by Omar1892** [comment]
Sorry, I gave you the wrong example. Please disregard the first post. So what happened was that we went from 0 items in stock to 2 items in stock and than 1 item was sold on invoice #183 after it was sold product was reduced from 2 to 1. but when we where doing the inventory check 1 item was missing. But the thing is that the item wasn't sold or missing. Similar things has happening and I notice that this issue started happening after we started using the PO and the GRN. What I believe its happening is that extra serial number are being created on the GRN but not by accident, the system could be miss counting the amount of items we are receiving. Sorry I can't provide a video since this happens randomly and I don't know to recreate something like this.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 @MuhammadAdnan32

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892,
Adnan here, Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks

**Comment by usmanalikhan93** [comment]
@MuhammadAdnan32 any update on this ?

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892,
I have double-checked it at my end. But unfortunately, I am not able to reproduce your issue at my end. Can you please check it again at your end? If the issue still persists, please help us to replicate the issue.
Thanks

**Comment by Omar1892** [comment]
@MuhammadAdnan32  Hello, I have reported this issue about 5 times in the past and you guys come around with the same answer. But I need more than what you guys have told me in the past. When I see it happen again can you guys just login in to my account and check the issue out your self. Like I have mentioned before this can't be replicated to be shared as a video because I have no control on how it happens nor i have any idea of how it happens. I really need this issue to be step in more in depth.

**Comment by usmanalikhan93** [comment]
@MuhammadAdnan32 whats the latest on this ?
