### ISSUE TITLE
Disable IMEI filed, only keep Serial number field

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#959]
For businesses that doesn't do cellphone repair it would be great if we can add a trigger under module configuration >> repair tickets which allow them to disable IMEI or serial number

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk 
We have made this improvement LIVE. You can now select the default input criteria either IMEI or Serial under Store **Settings > Module Configurations > Repairs**  

You can also disable the IMEI if it's not applicable. 
Release Notes: https://www.repairdesk.co/blog/2019/12/26/web-release-notes-email-campaigns-for-bill-payments/

Can we please update to the customer where he actually requested it? Thanks
