### ISSUE TITLE
Default status at ticket creation is "pending". I want to change that to "in progress"

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#960]
It would be great if admin can select default repair ticket status from module configuration

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk 
We have already made this improvement which is expected in the next release.
We have given an option to mark a "Default" status that will populate while creating a ticket.

**Comment by Uzair-RepairDesk** [comment]
We have made this improvement LIVE. 
You can now mark one status default from Store Settings > Order Status > Ticket Status 
Please check screenshot attached

![uzairshah - Admin OrderStatus](https://user-images.githubusercontent.com/22955861/69718186-89b99f00-112f-11ea-9114-a413976cf487.png)
