### ISSUE TITLE
How did you hear about us - Legends are not displayed on mobile view

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#963]
On how did you hear about us report you can see legends on desktop version. **See below:**

![Desktop](https://user-images.githubusercontent.com/21986026/69025743-017a2200-09ea-11ea-894b-96cca3752887.jpg)

However while viewing the report from mobile it doesn't display anything. Is it possible to fix it.

![73358340_2409569509141210_3606917422126202880_n](https://user-images.githubusercontent.com/21986026/69025773-27072b80-09ea-11ea-9aa0-f721caa3d103.jpg)

**Comment by usmanalikhan93** [comment]
For internal use:

**Comment by usmanalikhan93** [comment]
I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
