### ISSUE TITLE
If I edit any aspect of a estimate, ticket, or invoice, I want it to automatically email the customer.

### ISSUE THREAD

**Issue by hjtse** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#964]

**Comment by hjtse** [comment]
Currently I have to remember to manually email the customer. Would like to automate this process

**Comment by Uzair-RepairDesk** [comment]
Hi @hjtse 

Thank you for sharing your idea. 
Regarding tickets, RepairDesk certainly allows you to set automatic notification to send it to the customer based on a specific action. You can set notification relevant to a specific status. Once you update the ticket, you can select the specific ticket status and an automatic email will be sent to the customer. 
You can learn more about email notifications from the following link:-
**[How to setup automatic emails against linked statuses?]**(https://help.repairdesk.co/knowledgebase/articles/1893760-how-to-setup-automatic-emails-against-linked-statu)

Currently, there is no possibility to send an automatic email from the invoice and estimate once you update it however you can go to a specific customer's view page and send a manual update to the customer. 
Please check the screenshot attached. 

![uzairshah - Customerdetail Customer](https://user-images.githubusercontent.com/22955861/69030771-558d0280-09fa-11ea-88d1-75b783a8dacf.png)

If you have any further questions or if there is anything else with which I may assist, please do not hesitate to reach out.
