### ISSUE TITLE
iPAD POS does not have an option to convert ticket to invoice 

### ISSUE THREAD

**Issue by hjtse** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#965]

**Comment by Afnan-Mahmood** [comment]
Hello @hjtse 

If you want to create invoice from iPad you need to checkout the ticket. Open existing ticket in edit mode and click on checkout this will create invoice.

As Invoice not created automatically on IPad by changing status.

Best,
Afnan

**Comment by hjtse** [comment]
Checkout does not create invoice
I am only presented with payment options. I dotn deal with in person payment, only online. 
![image](https://user-images.githubusercontent.com/5474554/69515596-f2bccf00-0f03-11ea-948d-0957a7e23068.png)


Thus I need to have the invoice sent with paypal like this
![image](https://user-images.githubusercontent.com/5474554/69515612-fbada080-0f03-11ea-82ff-f7ab683b98e8.png)

![image](https://user-images.githubusercontent.com/5474554/69515513-a2de0800-0f03-11ea-9634-2344d54d3a66.png)

**Comment by Afnan-Mahmood** [comment]
Hello @hjtse 

Happy to help with this. Your need to complete the process of checkout with unpaid invoice. First click on checkout than click on "Complete payment" button. This will redirect to the next screen and unpaid invoice will be created and email forwarded to the customer with the described email template. From that email customer can click on paypal link and pay for invoice.

Please check this on your side and i hope this helps. If you need any further assistance please don't hesitate to reach out.

Best,
Afnan
