### ISSUE TITLE
I created a lead, but my dashboard does not show the details like number of leads, estimates, tickets, etc.

### ISSUE THREAD

**Issue by hjtse** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#967]
![image](https://user-images.githubusercontent.com/5474554/69026886-9f85d200-0981-11ea-81b4-202d77991b87.png)

**Comment by hjtse** [comment]
I want my master admin dashboard to look like employee
![image](https://user-images.githubusercontent.com/5474554/69026910-b7f5ec80-0981-11ea-9f3c-87038c16dfad.png)

**Comment by Uzair-RepairDesk** [comment]
Hey @hjtse 
Currently, it's not possible to change the dashboard view for a super admin. 
However, you can certainly make it possible under "Employee Roles & Permissions". 
I will advise to just unchecked the trigger "Make this role a super user" but assign all the permissions to the super admin.
If you do it, specific employee role users will be able to access all the module/sub modules however, he will be able to view "Employee Dashboard". 
Please check all screenshot attached

![uzairshah - Roles Permission](https://user-images.githubusercontent.com/22955861/69031720-8ff79f00-09fc-11ea-9a83-fa5d09d084f3.png)

Hope it helps. Thanks
