### ISSUE TITLE
Employee dashboard, I want to include leads, estimates in the dashboard. Remove "unlocks" category

### ISSUE THREAD

**Issue by hjtse** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#968]
![image](https://user-images.githubusercontent.com/5474554/69026927-ce03ad00-0981-11ea-8baa-e3a9658f5b60.png)

**Comment by Uzair-RepairDesk** [comment]
Hey @hjtse 

Thank you for sharing your idea. 

Currently, it will not be possible to display estimates on the dashboard as estimates are not assigned to any specific user. 
However, I have logged the request to hide unlocking if you hide the unlocking tab from module configurations and your request to display leads on the employee dashboard. 

Thanks for helping us make this a platform you'll depend on and we hope to support your business for many years to come

**Comment by usmanalikhan93** [comment]
For internal use:
https://repairdesk.atlassian.net/browse/RB-609

**Comment by usmanalikhan93** [comment]
Hi Han @hjtse 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
