### ISSUE TITLE
Estimate traduction

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#970]
The model editor is the same for all our shops (I'm going to copy the source code)
The language edit is the same for all our shops (I'm going to copy the selected language in all stores)
Still, SOS Phone St-Roch is the only store that does not have the same text that appears in the estimates created from leads. See Attachment.

The font of the text, some passages of texts and interfaces are not the same ....
<img width="651" alt="Estimate from SOS Phone Limoilou" src="https://user-images.githubusercontent.com/40500094/69276095-c1fb3380-0bab-11ea-816f-f77bf036cad9.png">
<img width="667" alt="Estimate from SOS Phone St-Roch" src="https://user-images.githubusercontent.com/40500094/69276101-c6bfe780-0bab-11ea-9b8f-078c0f3baca3.png">

--
french:
L'éditeur de modèle est le même pour toutes nos boutiques (je suis aller copier le code source)
L'éditer de language est le même pour toutes nos boutiques (je suis aller copier la langue sélectionné dans tous les magasins)
Pourtant, SOS Phone St-Roch est le seul magasin qui n'a pas le même texte qui apparait dans les estimations créé à partir des leads. Voir pièce jointe.

La police du texte, certains passage de textes et interfaces ne sont pas les mêmes....

**Comment by MuhammadAdnan32** [comment]
Hi @JessicaSOS ,
Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks

**Comment by MuhammadAdnan32** [comment]
Hi @JessicaSOS,
I have checked on your account and I am not able to reproduce the issue. Could you please share more details or a video to reproduce the issue?
Thanks

**Comment by JessicaSOS** [comment]
I no longer have a valid license for the "snagit" screen recorder. If you have a license that you can provide me, I will be happy to make a video. In the meantime, if you want to replicate, you can log in to my user and account to test the problem.
--
Je n'ai plus de license valide pour l'enregistreur d'écran "snagit". Si vous avez une license que vous pouvez me fournir, il me fera plaisir de vous faire un video. Entre temps, si vous souhaitez reproduire, vous pouvez vous connecter sur mon utilisateur et mon acompte afin de tester la problème.

**Comment by MuhammadAdnan32** [comment]
Hi @JessicaSOS,
I have double-checked it on your user account and unfortunately, the issue has been not reproduced. Can you please check it again at your end? If the issue still persists, please help us to replicate the issue.
Thanks

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks
Usman Ali
