### ISSUE TITLE
Customer message in customer profil

### ISSUE THREAD

**Issue by JessicaSOS** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#972]
My employees are not able to send emails to customers via client(customer) / client (manage customer). (see screenshot)
Yet, I am able to do it. So I think it's an option in access control. Can you guide me on which options are involved because the "customer messages" option is activated correctly in the "customer" tab.
![acces](https://user-images.githubusercontent.com/40500094/69357911-f9251f80-0c53-11ea-8b88-d5763c610e00.jpg)

--
Mes employé ne sont pas en mesure d'envoyer des courriels aux clients via client/client. (voir capture d'écran)
Pourtant, moi je suis en mesure de le faire. Je crois donc qu'il s'agit d'une option dans les contrôle d'accès. Pouvez-vous me guider sur quelle options est en cause svp car l'option "customer messages" est bien activé correctement dans l'onglet "customer".

**Comment by Uzair-RepairDesk** [comment]
**Hey Jessica,** 

Please check following permission of employees:-
Store Settings >> Employees >> Manage Roles Permissions >> Select Roles > Set permissions "Customer Messages" under "Customers".

Please check the screenshot attached.
![Roles Permission-customers](https://user-images.githubusercontent.com/22955861/69398964-233b1800-0d0e-11ea-9d8e-c9693e9c9bbf.png)



If you still find any problem, please feel free to ask. Thanks.

**Comment by JessicaSOS** [comment]
customer message is activate already, look attached picture
<img width="954" alt="customer message" src="https://user-images.githubusercontent.com/40500094/69827035-b6c78980-11e3-11ea-9fb7-c2e36c1eb68c.png">

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Please check the updated status of this

**Comment by usmanalikhan93** [comment]
Sure @Uzair-RepairDesk

**Comment by usmanalikhan93** [comment]
@Uzair-RepairDesk I have checked and it's working fine. 

Hi again @JessicaSOS - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Thanks 
Usman Ali

**Comment by JessicaSOS** [comment]
Hello,
Have you tested something? I showed you the accesses which are checked as well as the error page. can you correct the problems AND TEST them before closing the tasks please. There is nothing corrected in it. To reopen
Thank you
--
Bonjour,
Avez-vous testé quelque chose? Je vous ai montré les accès qui sont coché ainsi que la page d'erreur. pouvez-vous corriger les problèmes ET LES TESTER avant de fermer les tâches svp. Il n'y a rien de corrigé la dedans. A réouvrir
Merci

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.

**Comment by usmanalikhan93** [comment]
Hi @JessicaSOS 

I have tested in your account with employee "Jessica" and with "Mallette" it is working fine. Can you please check again and let me know if it working for you or not ? 

Thanks 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hi again @JessicaSOS - since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

Regards, 
Usman Ali

**Comment by JessicaSOS** [comment]
You can try with user Stacey. This problem has never been corrected. Please read again above.

**Comment by usmanalikhan93** [comment]
Hello @JessicaSOS 

I hope you are doing well. Thank you for the information. Let me check with this employee and I will update you accordingly. 

Regards, 
Usman Ali

**Comment by usmanalikhan93** [comment]
Hey @JessicaSOS  

Thank you for bringing this to our attention! It looks like there's a bug that just popped up 🐛. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 😃

For internal use: 
https://repairdesk.atlassian.net/browse/RB-1792

**Comment by usmanalikhan93** [comment]
Hello @JessicaSOS 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!

**Comment by JessicaSOS** [comment]
fixed yeah !
