### ISSUE TITLE
Inventory Label Professional Template Should Have Character Limit For Product Description 

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#973]
![Product Description](https://user-images.githubusercontent.com/21986026/69418351-54cad800-0d3c-11ea-8649-7701e4f3f64b.png)

If Inventory item has a long description it prints on 2 labels

**Comment by usmanalikhan93** [comment]
Issue has been fixed on live chat done by Danish Hassan.
