### ISSUE TITLE
Translate some text

### ISSUE THREAD

**Issue by gsmgps-star** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#975]
HI
i have issue for translate some text.
i need to translate:

1. ticket status (pending, repair...)
2. on printed ticket  (name of months)
3. on self check-in widget (submit button)

please see the attached pictures

1. https://s3.us-east-2.amazonaws.com/repairdesk/uploads/gallery/10876mediumWhatsApp%20Image%202019-10-13%20at%2019.45.21.jpeg.jpg

2. https://s3.us-east-2.amazonaws.com/repairdesk/uploads/gallery/10877WhatsApp%20Image%202019-11-10%20at%2011.18.40.jpeg.jpg

3. https://s3.us-east-2.amazonaws.com/repairdesk/uploads/gallery/10878WhatsApp%20Image%202019-11-10%20at%2011.18.36.jpeg.jpg

4. https://s3.us-east-2.amazonaws.com/repairdesk/uploads/gallery/10879mediumWhatsApp%20Image%202019-10-15%20at%2020.51.09.jpeg.jpg

regards

**Comment by usmanalikhan93** [comment]
Hi @gsmgps-star 

Usman Ali here 👋 Sure thing! Let me take a look to see if I'm getting the same issue as you and I'll circle back to you within 24 hours.

**Comment by MuhammadAdnan32** [comment]
Hi @gsmgps-star ,
I hope you are doing well. Currently, we don't have such functionality in the system which you was mentioned.
1- Ticket status (pending, repair...)> We advise you kindly create a custom status in your language as we don't have such functionality to convert default status.
2- On printed ticket (name of months) > This is not possible in the current situation.
3- On self-check-in widget (submit button)> I have forward this to our development team and they will be looked into it and prioritize it and we will fix it as soon as possible.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,
Regards,

**Comment by MuhammadAdnan32** [comment]
For internal Use:
https://repairdesk.atlassian.net/browse/RB-738

**Comment by MuhammadAdnan32** [comment]
Hi @gsmgps-star, 
I hope you are doing well. Your reported issue related to the Self-check-in widget (submit button text need to be translated) has been fixed. Please verify at your end and do let us know if you have a question.
Thanks!
Regards,
M Adnan
