### ISSUE TITLE
Serial Number on edited tickets 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#977]
@usmanalikhan93

Hello, 

Ive sent a video with the explanation through email.

**Comment by Omar1892** [comment]
@usmanalikhan93

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
I hope you are doing well. I really appreciate that you took the time to share a video. We have no such functionality to give an option to select serials while you editing the tickets parts. If you want to change the serials you have to delete the parts first and then again select another serial. And you can see your added serials when you view the tickets and when you will edit the ticket serials are not displaying.
If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks,

**Comment by Omar1892** [comment]
Hello, thank you for getting back to me. But you guys use to have that option once you guys did a big change on the system a couple of months back that was removed. It was a lot easier to see what serial number was used and with out having to delete the part we can switch it up.

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
I hope you are doing well. You can view your used serials from the ticket view page in the ticket line items. And you can update the serial by deleting the attached serials and then add new serials with the ticket. We have no such functionality to give an option to select serials while you editing the parts of the ticket. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out.
Thanks
