### ISSUE TITLE
Option to display turnaround against device issue

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#979]
It would be great if we can display turn around time against device issue on POS, edit ticket, appointment calendar and customer portal so staff can quote accurate time to the customer.

**Comment by Uzair-RepairDesk** [comment]
@Repair-Desk 
Is it about to add a new field of "Turn Around Time" with each repair service like "Average Job Time" or schedule of repair jobs while booking a ticket?

**Comment by Uzair-RepairDesk** [comment]
If you set up "Average Job Time" in each service, it displays the service on the POS screen.

**Comment by Uzair-RepairDesk** [comment]
Customer updated on this
