### ISSUE TITLE
[OpenAPI] Missing endpoint for device repair categories

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#982]
<img width="862" alt="Screen Shot 2019-12-04 at 2 34 58 PM" src="https://user-images.githubusercontent.com/23037821/70187520-474e1000-16a3-11ea-9717-0e266d2155a3.png">

**Comment by Uzair-RepairDesk** [comment]
Hey, @ThinkDigitalSoftware 
 Can you please share more details so that we can look into it?

**Comment by ThinkDigitalSoftware** [comment]
If we want to get a lost of these categories, we don't have a way to. Like Mac & PC, or all devices under Mobile

**Comment by Uzair-RepairDesk** [comment]
@ThinkDigitalSoftware  can you please explain "lost of these categories"  means? or you can come to live chat and over customer support can guide you.

**Comment by Repairdesk-QA** [comment]
Hello @ThinkDigitalSoftware,
Hope You are doing well.

Since I haven't heard back from you, I’m assuming you're all set for now, but you can always give me a shout here if anything else comes up!

**_Regards,_**
Quratul Ain
