### ISSUE TITLE
Automatic Email / SMS Triggers Aren't working For Custom Templates

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#983]
If you've created a custom email / sms template which should be sent to a customer when a repair status is marked as in progress or completed system does not send out the message automatically to a customer.

**Comment by Afnan-Mahmood** [comment]
Hello @Repair-Desk 

Issue with email and notification has been fixed. Now emails working properly as per custom status settings.

Best,
Afnan Mahmood
