### ISSUE TITLE
RMAs Issue 

### ISSUE THREAD

**Issue by Omar1892** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#987]
Hello, 

ive sent you a video via email of the issue that im having.

**Comment by Uzair-RepairDesk** [comment]
Hello @Omar1892 
Can you please confirm where you exactly shared the video. Thanks.

**Comment by Omar1892** [comment]
Hello, it was sent to Muhammad Adnan

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 , 
 Sure thing! Thanks for sharing the video with us. Let me take a look to see if I'm getting the same issue as you and I'll circle back to you.
Thanks,
Regards,
Adnan

**Comment by MuhammadAdnan32** [comment]
Hi @Omar1892 ,
I have checked your concern but unfortunately, I am unable to reproduce your issue. And it's working fine for me. Kindly avoid using zero on-hand part with the ticket that creates a hurdle for you. If you have any questions or if there is anything else with which I may assist, please do not hesitate to reach out. Be sure to let us know if there's anything we can do to make it even better :)
Thanks
