### ISSUE TITLE
When you clone system generated serialized inventory item it generates duplicate serials

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#988]
when using self inputted serial and clone it does it the correct way, only on system generated serials it clones serials also itleast on my system.

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Did you check this?

**Comment by usmanalikhan93** [comment]
For Internal Use: 
https://repairdesk.atlassian.net/browse/RB-693

**Comment by usmanalikhan93** [comment]
Hi @Repair-Desk 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
