### ISSUE TITLE
Tap on each Scan – iPad POS App: 

### ISSUE THREAD

**Issue by Repair-Desk** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#990]
Currently, cashiers/users have to tap every time they want to scan an item using the barcode scanner. Furthermore, once an item is scanned, to add that item to cart the user needs to tap again. That is a lot of work for users who are catering the customers who have a lot of things to buy. Therefore, to simplify the retail part of the application, these taps should be eliminated, so the user can simply scan an item using a Bluetooth scanner and the item is automatically added into the cart without any taps before or after the scan

**Comment by Uzair-RepairDesk** [comment]
Internal Task:-
https://repairdesk.atlassian.net/browse/REP-2331

**Comment by Uzair-RepairDesk** [comment]
We have made this improvement LIVE in the last release of the iPad. You can simply tap on the search field, scan any item through the barcode to add it to the cart automatically.
