### ISSUE TITLE
RMA Label Not Showing Via PrintNode | Corey Berdini | DrPhoneFix & Repair Weston

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#993]
Hello,

RMA doesn't give you the option to Print via Google Cloud Print and PrintNode.

Can we have this added.

Thanks,

**Comment by fahadimran303** [comment]
![RMA PrintNode](https://user-images.githubusercontent.com/48645240/70742382-38b8c600-1d3f-11ea-9570-ea3ebb147bcf.png)

**Comment by fahadimran303** [comment]
This option should also be in Inventory >> RMA

**Comment by Uzair-RepairDesk** [comment]
@fahadimran303 
Who actually requested this? Do we have a log of this improvement on JIRA? Please confirm?

**Comment by Afnan-Mahmood** [comment]
@Uzair-RepairDesk 

Jira created. Link is attached in live chat.

**Comment by Uzair-RepairDesk** [comment]
Hey @fahadimran303 
Required improvement is live.
