### ISSUE TITLE
Not showing all item in “low stock report”

### ISSUE THREAD

**Issue by hitman1986** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#994]
After last update not showing all item in low stock report 
![11BB055E-C41D-45BB-8B05-72F7DD995275](https://user-images.githubusercontent.com/44485797/70861294-9104e900-1f34-11ea-8d74-7250783c6ef0.jpeg)
![32CDD28E-2E29-4350-8EF1-ADCD170EF6F1](https://user-images.githubusercontent.com/44485797/70861299-995d2400-1f34-11ea-8344-143425b975f4.jpeg)
Im send video to mr danish to explain this issue

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93  can you please look into it?

**Comment by hitman1986** [comment]
Urgently, i need fast fix for this issue because my work its broken down!!

**Comment by usmanalikhan93** [comment]
Hi @hitman1986 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
