### ISSUE TITLE
Square Integration Issue | Sal Pirani

### ISSUE THREAD

**Issue by fahadimran303** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#995]
Dear Sir,

Sal Pirani has reported an issue related to **Square Deep Integration** on their **Buckhead Location**. 

All transactions recorded on **Buckhead Location** goes in the **Midtown Square Account**

All the settings on RepairDesk is correct and they are logged into the **Buckhead Square App**

He spoke with with square team and they believe it's not an issue with their end. 

It seems like the Deep Integration is for some reason is integrated with the Midtown Square account, and not the Buckhead one

Issue happens only when we use the deep integration, it goes into the wrong account (into the Midtown)

**Comment by Uzair-RepairDesk** [comment]
@usmanalikhan93 
Can you please get it checked?

**Comment by usmanalikhan93** [comment]
I believe it is fixed yesterday. @fahadimran303 can you please update here ?
