### ISSUE TITLE
Refurbishment Ticket Status Update

### ISSUE THREAD

**Issue by antoinegali** [Repair-DeskPOS/RepairDesk-BUGS-IMPROVEMENTS#999]
Hello,

When I create a refurbishment ticket for a Trade-In device, if I change the status to "Completed" before I save that ticket, it won't update the Trade-In status from "Pending Refurbishment" to "In Stock". I have to change the ticket status after I click on save to it updates. 

Is this a known issue? Quite annoying since I'm going to be processing tons of Trade-ins.

Thanks,
Antoine

**Comment by MuhammadAdnan32** [comment]
Hi @antoinegali ,
I hope you are doing well. Thank you for bringing this to our attention! It looks like there's a bug that just popped up. 
I'm gonna reach out to our Engineers to get this taken care of, I'll get back to you as soon as I have more information! 
Thanks,
Regards,
M Adnan

**Comment by MuhammadAdnan32** [comment]
For Internal use:
https://repairdesk.atlassian.net/browse/RB-744

**Comment by MuhammadAdnan32** [comment]
For Internal use:
https://repairdesk.atlassian.net/browse/RB-744

**Comment by usmanalikhan93** [comment]
Hi @antoinegali 

I hope you are doing well. Your reported issue has been fixed. Please verify at your end and do let us know if you have question.

Thanks!
Usman Ali
